### ISSUE TITLE
Show drop position when dragging over the editor

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#1]
Either as a pseudo-cursor or (if doable and performant) as the dragged content itself.

**Comment by mohsen1** [comment]
#12 is duplicate of this I guess. Most editors won't insert the actual content. It can mess up the layout and confuse the user.

**Comment by sbarysiuk** [comment]
Ideally would be nice to control and be able to extend this. Showing at least a placeholder/cursor is absolutely required (as Google Docs).

**Comment by marijnh** [comment]
Fixed via #53
