### ISSUE TITLE
Collaborative demo occasionally corrupts documents

### ISSUE THREAD

**Issue by DaveJarvis** [ProseMirror/prosemirror#10]
# Replicate

1. Open Firefox 40 (Ubuntu Linux)
1. Visit http://prosemirror.net/demo_collab.html#edit-Example

# Expected Results

The cursor is inside the text area.

# Actual Results

Text area is collapsed. See attached.

![firefox-bugs](https://cloud.githubusercontent.com/assets/2131950/9536977/91e6ac56-4ce7-11e5-9913-1367ea82e607.png)

**Comment by marijnh** [comment]
The document appears to have gotten corrupted somehow. I've restarted the server and saved its state for later debugging.

**Comment by mscdex** [comment]
Yes, I noticed the same thing on Firefox 40 on Windows. On Chrome 45 it shows up just fine.

**Comment by marijnh** [comment]
The collapsed content is only a symptom -- the underlying issue is that the library is crashing due to the document getting corrupted. I'm still debugging this.

**Comment by marijnh** [comment]
This was fixed in 19614e58333bc
