### ISSUE TITLE
Editor does not preserve line breaks with `docFormat` of "markdown"

### ISSUE THREAD

**Issue by zane** [ProseMirror/prosemirror#100]
## Repro Steps
1. Navigate to the [Markdown editing demo](http://prosemirror.net/demo_markdown.html)
1. Enter several line breaks after the first sentence
1. Check the "WYSIWYM" radio button
1. Check the "Markdown" radio button

## Expected Results
The line breaks are preserved.

## Actual Results
Only one line break remains.

**Comment by marijnh** [comment]
The markdown parsing serializing is lossy. If you mean intra-paragraph line breaks, those can't be expressed in ProseMirror's document model at the moment. There's several similar issue with preserving precise indentation and markup characters used and link reference positioning. Lossless markdown conversion is out of scope for now.

**Comment by katepol** [comment]
@marijnh didn't you include this in your plans?:)
