### ISSUE TITLE
Transform/Transaction - Add ability to map ResolvedPos through a Mappable object

### ISSUE THREAD

**Issue by AnthonyWeston** [ProseMirror/prosemirror#1001]
### Issue details

Sometimes it may be useful to map a ResolvedPos through a Transaction rather than having to map a number through the Transaction's mapping

Scenario:  Suppose I have a ResolvedPos `$pos` and a Transaction tr, where `$pos.doc` refers to a doc in `tr.docs`, and I want to map the position in `$pos.doc` to `tr.doc`, I would have to figure out how to map `$pos.pos` back to the position in tr.before (which if you're mapping backwards from an inserted node, may not exist), and then map that position through tr.mapping. I would like to be able to map `$pos` using the Transaction object, which would handle matching `$pos.doc` with a doc in tr.docs, and mapping `$pos.pos` through only the steps after that point.

### Steps to reproduce

Example code: 

```
// It's tempting to store tr.selection.$cursor.pos here so I can map it through tr.mapping at the end,
// but tr may already have some steps at this point, and if it does I'd need to map tr.selection.$cursor.pos
// back to tr.before, which may not be a position that exists in that document.

const $pos = tr.selection.$cursor

// Do some stuff

tr.insert(someContent)

const $newPos = tr.map($pos)

// Do some stuff with $newPos
```

### ProseMirror version

    "prosemirror-commands": "^1.0.7",
    "prosemirror-gapcursor": "^1.0.3",
    "prosemirror-history": "^1.0.4",
    "prosemirror-inputrules": "^1.0.1",
    "prosemirror-keymap": "^1.0.1",
    "prosemirror-menu": "^1.0.0",
    "prosemirror-model": "^1.7.0",
    "prosemirror-state": "^1.2.4",
    "prosemirror-tables": "^0.7.10",
    "prosemirror-test-builder": "^1.0.1",
    "prosemirror-transform": "^1.1.3",
    "prosemirror-utils": "^0.7.7",
    "prosemirror-view": "^1.8.8",

### Affected platforms

- [ x ] Chrome (78.0.3904.97 (Official Build) (64-bit))
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

N/A

**Comment by AnthonyWeston** [comment]
I'd be willing to develop this if the maintainers approve.

**Comment by marijnh** [comment]
I don't think this is a useful feature. Mapping the raw number and re-resolving is easy enough. And keeping track of which document a position refers to so that you can map it through the right sub-mapping is also not hard.

**Comment by AnthonyWeston** [comment]
Any chance you could provide a code sample of how you think this should be accomplished?

**Comment by marijnh** [comment]
You can always use `tr.selection.$from` to get a position that is valid in the transaction's current document. If you have a specific position from the start document that you want to map to the transaction's current document, you can to `tr.doc.resolve(tr.mapping.map(pos))`. If a position was valid after the Nth step of the transaction, you can map it to the current doc via `tr.mapping.slice(N)`.

**Comment by jhnsnc** [comment]
In our code base we have these two shorthand utilities for doing what Marijn describes above:

```
/**
 * A shortcut to apply a transaction mapping to a position and resolve the result
 */
export const $map = (tr: Transaction, pos: number, assoc?: number): ResolvedPos => {
    return tr.doc.resolve(tr.mapping.map(pos, assoc));
};

/**
 * A shortcut to apply a partial transaction mapping to a position and resolve the result
 */
export const $mapFrom = (tr: Transaction, mapFrom: number, pos: number, assoc?: number): ResolvedPos => {
    return tr.doc.resolve(tr.mapping.slice(mapFrom).map(pos, assoc));
};
```

I initially had difficulty with the concept of tracking the `mapFrom`, but after rewriting a few commands with it, I feel that it does tend to result in code that is a better balance of readability and efficiency.
