### ISSUE TITLE
Can't refocus after click outside

### ISSUE THREAD

**Issue by lcswillems** [ProseMirror/prosemirror#1004]
### Issue details

This code:

```
document.getElementById('my-button').onClick = () => {
  window.view.focus();
}
```

doesn't refocus the editor when the button is clicked.

### Steps to reproduce

https://glitch.com/edit/#!/maroon-airedale?path=index.js

If I click on the "click on me" button, editor should refocused, but it doesn't.

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by jakeknerr** [comment]
try changing `.onClick` to `.onclick`

**Comment by lcswillems** [comment]
Thank you! Stupid error...

**Comment by jakeknerr** [comment]
We have all been there!  I am glad I could be helpful :)
