### ISSUE TITLE
isInSet should return a bool

### ISSUE THREAD

**Issue by lcswillems** [ProseMirror/prosemirror#1005]
### Issue details

I got a bug in my code. After some investigation, I found it was coming from this:

```
return markType.isInSet($cursor.marks())
```

It was returning me `undefined`. But, I was persuaded (given the name) that `isInSet` should return a boolean.

So, I tried to find what I was doing wrong, but I found nothing... So, I thought that I might have misunderstood what `isInSet` returns. So I checked the documentation:

![image](https://user-images.githubusercontent.com/5437552/68996249-a89a7480-0897-11ea-8c4c-6fd33851ebd9.png)

But it was saying that `isInSet` returns a boolean. Weird... So I checked the definition of the function:

![image](https://user-images.githubusercontent.com/5437552/68996262-e6979880-0897-11ea-88ce-c10b24d091d8.png)

But it was always returning a boolean. Weird... Why `isInSet` returns undefined??

After some time, by luck, I understood that I was checking the `isInSet` of a mark and not of a mark type and that, maybe, the signature would be different. And indeed, it is:

![image](https://user-images.githubusercontent.com/5437552/68996301-73425680-0898-11ea-9408-ce0cd1b84a9d.png)

It returns a mark type or undefined. So I changed my code into:

```
return !!markType.isInSet($cursor.marks())
```

It took me 30 mns to correct this.

I open this issue because I think the current return type of `markType.isInSet` is error prone:

1. It is `undefined | MarkType` which is very uncommon for a function whose name starts by `is`. I never encountered before a function with such a name that doesn't return a boolean...

2. There is another function with the exact same name and the exact same description that doesn't have the same return type.

So I would suggest to change the return type of `markType.isInSet` to be boolean.

**Comment by marijnh** [comment]
Firstly, getting access to the mark of a given type in a set is useful (and is being used by current code). Secondly, changing this would be a breaking change, so that's not going to happen in the 1.x series of releases. Thirdly, since the return value converts to bool in the proper way, you'd only get bugs from this in very specific cases (such as checking with `== false`).

So sorry, this is just the way it is for now.

**Comment by lcswillems** [comment]
> Getting access to the mark of a given type in a set is useful

Sure! But not with a function has this name. This name is misleading.

I understand it is a breaking change and will not be done in 1.x, but if there is a 2.x one day, I think it would be a very good idea to rename it.
