### ISSUE TITLE
[Feature request] isInSet for Node and Node type

### ISSUE THREAD

**Issue by lcswillems** [ProseMirror/prosemirror#1007]
There are `isInSet` for `Mark` and `MarkType`. I thought they were a `isInSet` for `Node` and `NodeType` too, but there is not.

I think it would be a nice to add them in order to make it easier to test if a node type is in set, but also to make the API more consistent, and hence, easier to learn for newcomers.

**Comment by marijnh** [comment]
When do you need to use sets of node types?

**Comment by lcswillems** [comment]
For example, I somewhere want to know if a node is of list type. Hence, I have to do:

```
node.type === schema.nodes.ul || node.type === schema.nodes.ol
```

Somewhere else, I need to check if node is either h1, h2 or h3. Hence do:

```
node.type === schema.nodes.h1 || node.type === h2 || schema.nodes.node.type === schema.nodes.h3
```

Etc...

**Comment by marijnh** [comment]
Right. So why not `set.indexOf(node.type)` or even `set.includes(node.type)`?

**Comment by lcswillems** [comment]
Yes, it would work. But why having a `isInSet` function for mark and mark type? I am learning Prosemirror API but it feels inconsistent.

**Comment by marijnh** [comment]
> Yes, it would work. But why having a isInSet function for mark and mark type?

Because comparing marks is more involved than just `===`, as a cursory look at the code or the concepts involved would have shown.

Please stop opening issues about subjective 'inconsistencies'. Interfaces are trade-offs, and code size is one of the factors. You cannot expect methods to exist just because another analogous method exists, and if that's hindering you from understanding the interface, I think you should take a good look at your assumptions.

**Comment by lcswillems** [comment]
> Please stop opening issues about subjective 'inconsistencies'

'inconsistencies' are always subjective. So, if you don't want issues about subjective 'inconsistencies', you don't want issues about consistency at all.

But, consistency is one of the most important quality factor of an API. If the API is made of functions with unexpected behavior or misses expected functions, this makes the API very hard to learn and to use.

So it makes sense for me to open issues about inconsistencies, because:
1. I think that, as an API user, I am legitimate to raise inconsistencies, and likely more legitimate than the author, because 99% of the users of this API are people who didn't design it.
2. People facing the same inconsistencies will benefit from your answers.

So if you don't care about inconsistencies issues, I think you should take a good look at your assumptions.
