### ISSUE TITLE
Example on prosemirror.net is broken in IE 11

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#1009]
### Issue details

The example ProseMirror editor on prosemirror.net is broken IE 11.

### Steps to reproduce

1. Go to prosemirror.net
2. Example ProseMirror  editor is not working (Javascript error: `Proxy is undefined`)

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![image](https://user-images.githubusercontent.com/8322279/69960687-61081f80-150a-11ea-8d9e-ec1e4a1a4127.png)

**Comment by marijnh** [comment]
It seems recent versions of crel, a dependency of prosemirror-menu, don't run in IE11. I've downgraded that dependency.
