### ISSUE TITLE
Is it possible to migrate a project currently using Codemirror?

### ISSUE THREAD

**Issue by dalareo** [ProseMirror/prosemirror#101]
I am trying to include collaborative editing feature in Prose.io, which I guess is the best and more simple Github document editor. Is it possible to substitue Codemirror (the editor Prose.io uses) with Prosemirror and have collaborative editing??

**Comment by marijnh** [comment]
No. They have different APIs, different document models, and different use cases. You might be able to build something on top of ProseMirror, but it will not just be a matter of substituting it in.

**Comment by dalareo** [comment]
OK. Thanks!
