### ISSUE TITLE
User visible selection differs from prosemirror selection in Edge.

### ISSUE THREAD

**Issue by marywhite** [ProseMirror/prosemirror#1011]
### Issue details

After selecting across multiple nodes of text and toggling a mark via menu action, the visible user selection differs from prosemirror selection. A workaround for this has been to removeAllRanges from the current selection, and then re-add the old range.

### Steps to reproduce

1. Go to https://prosemirror.net/ in the Edge browser
2. Using the mouse, select all visible text within the prosemirror editor
3. Click on the bold menu icon

### ProseMirror version

prosemirror-view@1.13.4

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other (Edge)

### Screenshots / Screencast (Optional)

![edge-selection](https://user-images.githubusercontent.com/5373900/70160770-a4849a00-1680-11ea-8fc4-2f0ac642b734.gif)

**Comment by marijnh** [comment]
Thanks for the report. Seems Edge is happily reporting a selection to the script that doesn't correspond to the actual selection it is showing the user in some cases. There was a workaround for a similar bug in IE11, I've widened it to also cover this case in attached patch.
