### ISSUE TITLE
Cannot delete list Items with the entire block of text selected in iOS 13

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1012]
### Issue details

When selecting all of the text in a list item and hitting backspace on iOS 13, we were seeing the selection update and the content not being deleted.

I narrowed this down but I don't know the proper way to get the context to create a PR. The "ruleFromNode" function here

```js
function ruleFromNode(parser, context) {
  return function (dom) {
    var desc = dom.pmViewDesc;
    if (desc) {
      return desc.parseRule()
    } else if (dom.nodeName == "BR" && dom.parentNode) {
      // Safari replaces the list item or table cell with a BR
      // directly in the list node (?!) if you delete the last
      // character in a list item or table cell (#708, #862)
      if (result.safari && /^(ul|ol)$/i.test(dom.parentNode.nodeName))
        { return parser.matchTag(document.createElement("li"), context) }
      else if (dom.parentNode.lastChild == dom || result.safari && /^(tr|table)$/i.test(dom.parentNode.nodeName))
        { return {ignore: true} }
    } else if (dom.nodeName == "IMG" && dom.getAttribute("mark-placeholder")) {
      return {ignore: true}
    }
  }
}
```

Is hitting this condition on iOS 

`if (result.safari && /^(ul|ol)$/i.test(dom.parentNode.nodeName))`

However, "context" is a ResolvedPos from "$from" passed in on parseBetween here

```js
  var sel = null, doc = parser.parse(parent, {
    topNode: $from.parent,
    topMatch: $from.parent.contentMatchAt($from.index()),
    topOpen: true,
    from: fromOffset,
    to: toOffset,
    preserveWhitespace: $from.parent.type.spec.code ? "full" : true,
    editableContent: true,
    findPositions: find,
    ruleFromNode: ruleFromNode(parser, $from),
    context: $from
  });
```

while "matchTag" at `parser.matchTag(document.createElement("li"), context)` expects "context" to be a "ParseContext" instance.

This type mismatch is causing an error when "matchesContext" is executed on "matchTag"

```js
DOMParser.prototype.matchTag = function matchTag(dom, context) {
  for (var i = 0; i < this.tags.length; i++) {
    var rule = this.tags[i];
    if (matches(dom, rule.tag) &&
        (rule.namespace === undefined || dom.namespaceURI == rule.namespace) &&
        (!rule.context || context.matchesContext(rule.context))) {
      if (rule.getAttrs) {
        var result = rule.getAttrs(dom);
        if (result === false) { continue }
        rule.attrs = result;
      }
      return rule
    }
  }
};
```

I'd be happy to submit a PR but I'm not sure what the best approach is.

**Comment by marijnh** [comment]
Ah, that is indeed broken, but the bug only manifested itself in very specific circumstances (triggering this case in Safari with a parse rule for `<li>` nodes that has a `context`. Could you check if attached patch helps?

**Comment by jljorgenson18** [comment]
Yep that fixed it! It seems like iOS 13 started hitting this condition for lists. Our QA team didn't see this on iOS 12.
