### ISSUE TITLE
Chrome selection wrong after adding mark

### ISSUE THREAD

**Issue by hitsthings** [ProseMirror/prosemirror#1013]
### Issue details

Chrome shortens the selection after an addMark() transaction, and ProseMirror doesn't force the selection. From source comments this case sounds like the IE/Edge behavior that you have already handled.

The important ingredients for this seem to be:
- inline elements with differing style (e.g. words with different `color` properties.)
- a programmatic selection (if you do the selection manually, Chrome is fine.)

### Steps to reproduce

See https://pm-chrome-select.glitch.me/

After 5 seconds it will programmatically focus the editor and select a particular block of text (which text you select matters, but I haven't figured out why).

Then every second it will toggle a highlight mark on the selection range. You will see "the menu to" (last three words of the selection) are not visually selected. When the mark is removed, they are selected again (in this case I believe force selection _is_ getting called for Chrome).

### ProseMirror version

Demo runs off latest

### Affected platforms

- Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- OSX Catalina

### Screenshots / Screencast (Optional)

![chrome-select-issue](https://user-images.githubusercontent.com/631812/70676372-10e64580-1ce0-11ea-996c-1c529a600e5b.gif)

**Comment by marijnh** [comment]
This seems to be another instance of #710, which the existing workaround didn't catch. I've adjusted it in attached patch (and unified it with the handling of a similar bug in IE and Edge).

**Comment by hitsthings** [comment]
Thanks a ton for the fix! There's no way in hell I can judge it (I really have very little idea what was going on there), but now I can understand the logic behind the code to fix it. :) With that in mind, it looks great!
