### ISSUE TITLE
Shift-Mod-z triggers Mod-z on Mac+Chrome

### ISSUE THREAD

**Issue by mariosvlad** [ProseMirror/prosemirror#1016]
### Issue details

On Mac+Chrome, keyboard shortcut `Shift-Mod-z` triggers `Mod-z`'s function. 
I noticed that at [this line in prosemirror-keymap](https://github.com/ProseMirror/prosemirror-keymap/blob/6f112c45fcfb9006d65c36988ab9285229157897/src/keymap.js#L84), on firefox and safari `name` has value `Z` while on chrome it's `z` so `modifiers(name, event, !isChar)` returns `Meta-z` on chrome (`Meta-Z` on others) and so it triggers `direct` function (`Mod-z`'s function in this case).

### Steps to reproduce

https://codesandbox.io/s/dazzling-moon-tdlvv

- type something, pause, type again (so it adds a few undo steps)
- undo using `cmd+z`
- redo using `cmd+shift+z` (does undo again instead of redo)

### ProseMirror version

prosemirror-keymap: 1.1.3

### Affected platforms

So far i found that only Mac+Chrome has this issue (tested on windows+chrome, mac+chrome/safari/firefox)

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Could you see if the issue goes away if you replace this line in `w3c-keynames/index.js`...

    var brokenModifierNames = chrome && +chrome[1] < 57 || gecko && mac

With this one...

    var brokenModifierNames = chrome && (mac || +chrome[1] < 57) || gecko && mac

(Or in index.es.js if that's what your bundler reads.)

**Comment by mariosvlad** [comment]
Thanks for your reply, yes, with that change it works

**Comment by marijnh** [comment]
Okay, thanks for testing. I've published a new version of `w3c-keyname` with a fix. (Upgrading a transitive dep like that will probably involve clearing your package lock file.)
