### ISSUE TITLE
Strange Decoration widget default mark

### ISSUE THREAD

**Issue by brechtm** [ProseMirror/prosemirror#1019]
### Issue details

Adding a new widget decoration without supplying any marks to `Decoration.widget` applies the same mark as the next mark further in the paragraph (not the next node). See the reproduction steps below.

I'm not 100% sure this is a bug. I might just be misinterpreting the documentation. In any case, I found this very intuitive behavior. Thankfully, I can prevent this from happening by passing `{marks: []}` as the _specs_ argument to `Decoration.widget`.

### Steps to reproduce

* go to the [Linting example](https://prosemirror.net/examples/lint/)
* select the word "comma"
* toggle the emphasis style
* the decoration widget is also applied the emphasis mark (you can see the exclamation mark become italicized)

### ProseMirror version

Test with latest of all relevant prosemirror-* packages.

### Affected platforms

Tested with Firefox, Chrome and Safari on macOS.

**Comment by marijnh** [comment]
This is by design — for many types of widgets you don't want to create a break in the surrounding styling, so the default behavior isn't unreasonable, and since it's easily worked around it's not something we'll consider breaking backwards compatibility for.

**Comment by brechtm** [comment]
I get that you want to preserve surrounding styling. However, in the example above, the mark being applied to the decoration widget is a couple of words away from where the widget is being inserted, so it's not even touching that mark.

**Comment by marijnh** [comment]
Oh, that _is_ a bug. Attached patch fixes it.
