### ISSUE TITLE
Cannot select text by double tap on Firefox on Android

### ISSUE THREAD

**Issue by phamvuau** [ProseMirror/prosemirror#1020]
### Issue details

Cannot select text by double tap on Firefox

### Steps to reproduce
1. Go to [https://prosemirror.net/](https://prosemirror.net/) using Firefox (v68.3.0) on Android (9)
2. On the homepage, double tap on a word

Current behavior: the word is not selected
Expected behavior: the word is selected

### Affected platforms
- [x] Firefox on Android

### Screenshots / Screencast
![WhatsApp Image 2020-01-01 at 7 54 36 PM](https://user-images.githubusercontent.com/259848/71641612-8a66c780-2cd1-11ea-8064-f686720a0f75.jpeg)

**Comment by marijnh** [comment]
Is this about double-tap, or double-clicking with an external pointing device?

**Comment by phamvuau** [comment]
@marijnh it's double-tap

**Comment by marijnh** [comment]
That doesn't appear to work in a non-ProseMirror editors either. The way to select words on Android is to long-press them. Or am I missing something?

**Comment by phamvuau** [comment]
> That doesn't appear to work in a non-ProseMirror editors either. The way to select words on Android is to long-press them. Or am I missing something?

You're right that the issue happens for other editors as well. It's so weird that after a long-press to select a word then another long-press to select another word become very difficult and sometimes doesn't work.
