### ISSUE TITLE
Invalid marks applied to node when pasting a slice

### ISSUE THREAD

**Issue by marywhite** [ProseMirror/prosemirror#1022]
### Issue details

I'm seeing some unexpected behavior when attempting to paste an HTML list into the prosemirror editor, where the first list item gets lifted from it's parent list. This occurs exclusively when the list contains a style attribute that meets the criteria for a parse rule (i.e. font-weight: bold) that wouldn't be allowed for that node type. In my case, I was able to fix this by ensuring that the NodeContext created for that lists only contains attributes that would be permitted for that type. 

### Steps to reproduce

1. Go to https://glitch.com/edit/#!/lopsided-variraptor
2. Using the mouse, select the entire contents of the HTML above the editor to clipboard
3. Hit enter to insert a newline into the prosemirror editor
4. Paste the list. (first item gets wrapped in a paragraph tag outside of the list)

### ProseMirror version

prosemirror-model@1.9.0

### Affected platforms

- [x ] Chrome
- [ x] Firefox
- [ ?] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

My solution is here: https://github.com/ProseMirror/prosemirror-model/pull/48
Let me know what you think, I could be missing something about how the parse rules are intended to work here :)

**Comment by marijnh** [comment]
Fixed via https://github.com/ProseMirror/prosemirror-model/commit/8a083ac7f00caaf4f7bdb35f25bf0b4e3b3ed4e0
