### ISSUE TITLE
Different input rule behavior between prosemirror-view 1.8.9 and 1.9.0 with IME

### ISSUE THREAD

**Issue by buddh4** [ProseMirror/prosemirror#1023]
### Issue details

The **start**/**end** and **selection** values of an input rule differ between prosemirror-view v1.8.0 and v1.9.0 when using IME. I'am not sure if this change is intended or why the results differ.

### Steps to reproduce

Given the following simple input rule:

```
let testRule = function(schema) {
    return new InputRule(new RegExp('(^|[\\s])@$'), function (state, match, start, end) {
        console.log('Start: '+ start);
        console.log('End: '+ end);
        console.log('Selection.from: '+ state.selection.from);
        console.log('Selection.from: '+ state.selection.to);
    })
};
```
Typing @ will result in:

### prosemirror-view@1.8.9:

**No IME**:

Start: 1
End: 1
Selection.from: 1
Selection.from: 1

**With Windows IME**:

Start: 1
End: 1
Selection.from: 1
Selection.from: 1

### prosemirror-view@1.9.0:

**No IME**:

Start: 1
End: 1
Selection.from: 1
Selection.from: 1

**With Windows IME**:

Start: 1
End: 2
Selection.from: 2
Selection.from: 2

### ProseMirror version

prosemirror-view v1.9.0

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
> I am not sure if this change is intended or why the results differ.

This is intended—rather than treating an entire composition as a single transaction, the editor now fires transaction for each change that happens during the composition.

Is this causing a specific problem for you?

**Comment by buddh4** [comment]
No, I think a small alignment will be fine, just wanted to make sure its intended to behave like this. Thanks for the clarification!
