### ISSUE TITLE
Composition breaks on Firefox when starting a composition next to an inline node that has marks

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1024]
### Issue details

On Firefox when a mark is applied to an inline node and a composition is started next to that inline node, the composition breaks and you cannot type more than a single character

### Steps to reproduce
1. Open the Prosemirror Dino example (https://prosemirror.net/examples/dino/) in Firefox with Japanese (Hiragana) enabled
2. Go to a blank line and apply a bold or italic mark to set a stored mark.
3. Insert a Dinosaur node such that the mark is applied to the node and the cursor is to the right of the new node
3. Begin typing to start a composition

Expected result:
Composition works as intended and a full string of characters is displayed

Actual result:
A single character is added and the composition is not continued

### ProseMirror version

* prosemirror-view: 1.13.7

### Affected platforms

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

This happens on both Mac and Windows

### Screenshots / Screencast (Optional)

http://g.recordit.co/bLeMqzdoLX.gif

**Comment by marijnh** [comment]
Attached patch should help.

**Comment by jljorgenson18** [comment]
This seems to fix it!
