### ISSUE TITLE
Gapcursor causes error when navigating beyond document consisting of only inline nodes

### ISSUE THREAD

**Issue by fluidsonic** [ProseMirror/prosemirror#1025]
### Issue details

> Uncaught RangeError: There is no position before the top-level node

### Steps to reproduce

1. Go to https://glitch.com/~immediate-charger
2. Place the cursor in the editor.
3. Try to move the cursor beyond the document boundary with any arrow key.

### ProseMirror version

Whatever the examples are using.

### Affected platforms

I'm on Chrome on macOS.

**Comment by marijnh** [comment]
Thanks for the report. Attached patch should help.
