### ISSUE TITLE
how prevent delete or replace custom node using "filterTransaction"?

### ISSUE THREAD

**Issue by jarl-alejandro** [ProseMirror/prosemirror#1026]
I have built a custom node but I don't want it to be deleted using the keyboard if not a button.
I have already done the delete with the button but the way that it is not deleted with the keyboard I have no idea I have searched and says that the best option is to use "filterTransaction" but I have no idea how to use it

**Comment by marijnh** [comment]
The issue tracker is not the place for questions, sorry.
