### ISSUE TITLE
Updating marks on Safari can cause uneditable paragraphs

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1027]
### Issue details

With the recent changes to prosemirror-view on 1.13.10, it looks like paragraphs can have contentEditable=false set on them on Safari even though they should be editable.

### Steps to reproduce

1. Go to the demo editor in Safari https://glitch.com/edit/#!/remix/prosemirror-demo-basic
2. Remove all of the content
3. Type two lines
4. Do a select all
5. Hit "bold"
6. Try to edit the second paragraph

The paragraph is no longer editable and you cannot place your cursor inside of it

prosemirror-view: 1.13.10

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari
- [ ] Other

**Comment by marijnh** [comment]
Ah, thanks for catching that. I messed up the boolean logic and had that condition fire too often. Attach patch (released as 1.13.11) should help.

**Comment by jljorgenson18** [comment]
It all seems to be fixed now.
