### ISSUE TITLE
Pasting long text causes page to scroll

### ISSUE THREAD

**Issue by janiskelemen** [ProseMirror/prosemirror#1028]
Pasting a very long text into the editor will cause the page to scroll down.

https://codesandbox.io/s/52940pk6zx

### ProseMirror version
    "prosemirror-commands": "1.1.2",
    "prosemirror-dropcursor": "1.3.2",
    "prosemirror-gapcursor": "1.1.2",
    "prosemirror-inputrules": "1.1.2",
    "prosemirror-keymap": "1.1.3",
    "prosemirror-model": "1.8.2",
    "prosemirror-state": "1.3.2",
    "prosemirror-view": "1.13.7",

**Comment by marijnh** [comment]
The scroll code wasn't taken the distance scrolled in the inner container into account when scrolling the body. Attached patch should help.
