### ISSUE TITLE
Cannot type Chinese directly after a link.

### ISSUE THREAD

**Issue by zhaoyao91** [ProseMirror/prosemirror#1029]
### Issue details

If the first character of the Chinese typing is the same with the last charater of the link, this character will be occupied.

### Steps to reproduce

![Kapture 2020-02-10 at 13 08 57](https://user-images.githubusercontent.com/3808838/74122581-ae89c280-4c06-11ea-9091-c4c991a6234c.gif)

### ProseMirror version

https://prosemirror.net/examples/basic/

Just on the example website

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Attached patch should fix this.

**Comment by marijnh** [comment]
And by 'attached' I mean patch https://github.com/ProseMirror/prosemirror-view/commit/c2756d4fe49056135c6f77bb6d8c4a104fe17a09

**Comment by zhaoyao91** [comment]
Cool, it was fixed in the demo.

BTW, may I ask a question, is it ok to typing Chinese directly after a **void element**, such as a variable placeholder, which has some text in it but it is not editable, (though I have no idea how to make it using PM and I didn't find such a demo of PM by now)

I have tried a lot of solutions, draft, slate ... none of them works in this case: 
https://github.com/ianstormtaylor/slate/issues/3490

So I don't know if it is a difficult edge case in the whole RTE world and don't have much confidence to dig a big framework like PM :(

**Comment by marijnh** [comment]
>  is it ok to typing Chinese directly after a void element, such as a variable placeholder, which has some text in it but it is not editable,

Browsers (especially Safari and Chrome) are really stupid about this, treating the uneditable text as part of the composed content and randomly copying parts of it into the editable content. You can usually work around this by setting the uneditable element to `display: inline-block` (though that will also often change its vertical position).

**Comment by zhaoyao91** [comment]
@marijnh in the slate case, the mention is already an inline-block. I tried to change the mention into inline-block in draft-wysiwyg, no luck.

Anyway, thanks verfy much :)

**Comment by zhaoyao91** [comment]
Cool, I have made some changes to the dino example to examining the placeholder feature, it works like a charm! Everything, including that it can only be applied styles as a whole, works well.

Here are the snippets, you may includes them as a demo:

```
const placeholderNodeSpec = {
  attrs: {
    text: { default: "placeholder" },
    key: { default: "default-placeholder-key" }
  },

  inline: true,
  group: "inline",
  atom: true,

  toDOM: node => [
    "span",
    {
      "data-node-type": "placeholder",
      "data-placeholder-key": node.attrs.key,
      style: "border: solid 1px blue; border-radius: 2px; border-color: blue;"
    },
    node.attrs.text
  ],

  parseDOM: [
    {
      tag: 'span[data-node-type="placeholder"]',
      getAttrs: dom => {
        return {
          text: dom.textContent,
          key: dom.getAttribute("data-placeholder-key")
        };
      }
    }
  ]
};

const dinoSchema = new Schema({
  nodes: schema.spec.nodes
    .addBefore("image", "dino", dinoNodeSpec)
    .addBefore("text", "placeholder", placeholderNodeSpec),
  marks: schema.spec.marks
});
```

```
 <p>
    <span
      data-node-type="placeholder"
      data-placeholder-key="i-am-here">I AM HERE</span>
  </p>
```
