### ISSUE TITLE
prosemirror-view scrolls on edit if editor is higher than view port height

### ISSUE THREAD

**Issue by MarMun** [ProseMirror/prosemirror#1030]
### Issue details

**Expected behavior:** Editor do not scroll view on text editing (typing / formatting).
**Observed behavior:** Editor scrolls view upon text editing (typing / formatting).

Happens post 'prosemirror-view 1.13.11' / since 'prosemirror-view 1.14.1'.

Maybe related to #1028 

### Steps to reproduce

- Scroll a **higher-than-viewport** editor to an arbitrary position.
- Start typing / editing text. 
- The editor scrolls the point of editing
  - out of view port (sometimes multiple view heights) (chrome)
  - to very bottom of viewport (firefox)
  - somewhat near viewport center (safari)

### ProseMirror version

    "prosemirror-commands": "^1.1.3",
    "prosemirror-history": "^1.1.3",
    "prosemirror-keymap": "^1.1.3",
    "prosemirror-menu": "^1.1.2",
    "prosemirror-model": "^1.9.1",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-state": "^1.3.2",
    "prosemirror-transform": "^1.2.3",
    "prosemirror-view": "^1.14.2",

### Affected platforms

- [ X ] Chrome (latest)
- [ X ] Firefox (latest)
- [ X ] Safari (latest)

**Comment by marijnh** [comment]
I'm not seeing this when I, for example, past a bunch of stuff into the demo on https://prosemirror.net and then edit somewhere in the middle. Could you double-check the circumstances that trigger the issue?

**Comment by MarMun** [comment]
Hmmm... I cannot reproduce on the mentioned page either...

My problem is I don't even know were to begin to double check. I have multiple editors on same page. Multiple levels down in dom tree (nested vue components) :-(

All i know is it did not happen @1.13.11

None the less: I try to create a simple case that reproduces this issue.

**Comment by MarMun** [comment]
Ok. Error on my side (who could have guessed that ;-) )...

**Reason: A 'parent' a couple of levels up had its height set to 100vh.**

The content is way bigger than 100vh.
The editor in question has an offsetTop of 6000+ ...
In 'scrollRectIntoView' this leads to the assumption that a scroll up is necessary...

No idea why this wasn't a problem earlier, though...

However. I'll remove this (legacy) rule. 

Thanks for taking the time and sorry for the wast of it!!
