### ISSUE TITLE
Wrong cursor position just before a custom inline node

### ISSUE THREAD

**Issue by zhaoyao91** [ProseMirror/prosemirror#1031]
### Issue details

I have made a variable placeholder node which contains some text but not editable.
The cursor after the node is right positioned, but the cursor before the node is in wrong position.
It should be outside the box, but it is actually inside the box.

![Kapture 2020-02-13 at 16 47 51](https://user-images.githubusercontent.com/3808838/74416783-98873680-4e80-11ea-8599-dc8b0a198bad.gif)

### Steps to reproduce

Below is the code of the node spec:

```
{
      attrs: {
        key: { default: "variable" },
        text: { default: "placeholder" }
      },

      inline: true,
      group: "inline",
      atom: true,

      toDOM: node => [
        "span",
        {
          "data-node-type": "variablePlaceholder",
          "data-attr-key": node.attrs.key,
          style:
            "border: solid 2px black; border-radius: 4px; padding: 2px; margin: 0 2px;"
        },
        node.attrs.text
      ],

      parseDOM: [
        {
          tag: 'span[data-node-type="variablePlaceholder"]',
          getAttrs: (dom: any) => {
            return {
              key: dom.getAttribute("data-attr-key"),
              text: dom.textContent
            };
          }
        }
      ]
    }
```

### ProseMirror version

- prosemirror-model: 1.9.1
- prosemirror-state: 1.3.2
- prosemirror-view: 1.14.2

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
This is a piece of browser behavior that ProseMirror can't do anything about—Chrome is very weird about cursor placement on boundaries between inline nodes, apparently assuming it doesn't matter which side of the boundary the cursor is on, even when one side isn't editable.

The recommended workaround is to set `display: inline-block` on the node.
