### ISSUE TITLE
Issue when typing first and last characters in Korean on IE11

### ISSUE THREAD

**Issue by MoonSupport** [ProseMirror/prosemirror#1032]
### Issue details

When i write text in Korean, I had **two problems**.

**The first issue** like below:
![first_input](https://user-images.githubusercontent.com/41575415/74504735-84067500-4f38-11ea-9fb9-4f15bf727cc9.gif)

If I type Korean in the first input, the editor does not receive the contents.
But I typed Korean after the first, It worked.

**The second issue** like below:
![last_cut](https://user-images.githubusercontent.com/41575415/74505220-ef047b80-4f39-11ea-8dff-7f2f67577d88.gif)

When I write in Korean and change the next line, the last letter will be lost.

### Steps to reproduce

1. Open IE11 
2. Go https://prosemirror.net/
3. Input Korean ( It is first letter in any line ) <- first issue
4. Input Korean after typing something 
5. Write last characters in Korean and change next line <- second issue

### ProseMirror version

latest? 1.14.2?
https://prosemirror.net/ <- this version

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [ ] Other

**Comment by MoonSupport** [comment]
If you aren't enough the above information or need additional information, please comment anytime.

**Comment by rubang** [comment]
Hi, I'm a Korean developer also using Prosemirror in my project.
My prosemirror-view patch below will work for you.
I also fixed another issue that you don't have reported.
That is an issue where the selection would change to next line
when deleting content during composition of the first letter of a sentence.
Hope this will help you.

https://github.com/ProseMirror/prosemirror-view/pull/69
