### ISSUE TITLE
Can't type return after single-character paragraph on mobile Safari

### ISSUE THREAD

**Issue by dgreensp** [ProseMirror/prosemirror#1034]
### Issue details

After typing a single-character paragraph such as "a," the "return" key on the onscreen keyboard on iOS doesn't do anything.

### Steps to reproduce

In any ProseMirror (such as the basic example), on mobile Safari, start with the insertion point on a blank line.  Then type a letter such as "a," followed by "return."  The "return" will not do anything.

**Comment by dgreensp** [comment]
The problem seems to be related to whether the browser selection is attached to the paragraph or the text.

**Comment by jljorgenson18** [comment]
I experienced this as well. It looks like it's the result of the fix for https://github.com/ProseMirror/prosemirror/issues/982.

**Comment by marijnh** [comment]
It seems no actual DOM changes are generated in this case, preventing the code that is supposed to handle this from running. Investigating.

**Comment by marijnh** [comment]
Attached patch works around this. I've released it as prosemirror-view 1.14.4. Can you confirm that it solves the issue for you?

**Comment by jordoh** [comment]
Attached patch (and 1.14.4) solves the issue for me (iOS 13.3, on both simulator and physical device, which were exhibiting the issue on 1.14.2)

**Comment by marijnh** [comment]
Wonderful. Closing this for now.
