### ISSUE TITLE
Wrong selection in Chrome when adding text to empty paragraph and setting selection

### ISSUE THREAD

**Issue by dgreensp** [ProseMirror/prosemirror#1035]
### Issue details

This seems to be another instance of #710.

With the cursor in an empty paragraph in an empty editor, run this code:

```
    const tr = // create transaction
    tr.insertText('a')
    tr.setSelection(TextSelection.create(tr.doc, 1, 1))
    // apply transaction
```

The correct behavior is for the cursor to be before the letter A.  Behavior in Safari is correct.  Behavior in Chrome is incorrect, because the cursor goes after the letter A.  This seems to be a case where the browser reports a different selection via the DOM API than it is actually showing.  The selection the browser reports is (P, 0, P, 0) where P is the paragraph, but actually the cursor is shown at the end of the line.

This bug occurs when using prosemirror-collab with the `mapSelectionBackward` option.

### Steps to reproduce

You can use this glitch:

https://glitch.com/~honey-narcissus-p0mfaq48cw

You have to click to position the cursor in the empty editor within 3 seconds of the page loading, because the "a" is added in a 3-second setTimeout.  You can see this works differently in Chrome and Safari, with Chrome having incorrect behavior.

### ProseMirror version

prosemirror-view 1.14.2

### Affected platforms

- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Kludgy Workaround

After updating the view with a new state, detect this bad (P, 0, P, 0) browser selection, where P is any node whose first child is a text node, and set it to a better one:

```
    const browserSelection = window.getSelection()
    if (
      browserSelection &&
      browserSelection.anchorOffset === 0 &&
      browserSelection.focusOffset === 0 &&
      browserSelection.focusNode &&
      browserSelection.focusNode === browserSelection.anchorNode &&
      browserSelection.focusNode.firstChild &&
      browserSelection.focusNode.firstChild.nodeType === 3
    ) {
      const textNode = browserSelection.focusNode.firstChild
      const r = document.createRange()
      r.setStart(textNode, 0)
      r.setEnd(textNode, 0)
      browserSelection.removeAllRanges()
      browserSelection.addRange(r)
    }
```

**Comment by marijnh** [comment]
That was possibly a regression, since I cleaned up the kludge from 6f9dcf3f last December, and may have broken it for some cases there. Bringing back the old code seems to fix this one.

**Comment by marijnh** [comment]
See patch https://github.com/ProseMirror/prosemirror-view/commit/f5198a342079cbee6e12f8aa4d24864392f544ef

**Comment by dgreensp** [comment]
Wonderful, thank you!
