### ISSUE TITLE
Cell selection and resize not working when table is inside a block

### ISSUE THREAD

**Issue by zssng** [ProseMirror/prosemirror#1036]
### Issue details

![GIF 2-26-2020 10-01-07 AM](https://user-images.githubusercontent.com/11711477/75304742-fe12f400-587e-11ea-82af-4688a0586efc.gif)
put table inside a block,containing block schema look like this
![image](https://user-images.githubusercontent.com/11711477/75304802-2569c100-587f-11ea-93ac-3cf395fd06b6.png)
Problem : cannot make cell selection(no `selectedCell` class in dom) and resizing,but keyboard works(eg. shift+arrow)

### ProseMirror version

+-- tiptap-extensions@1.28.6
| +-- lowlight@1.13.0
| | +-- fault@1.0.4
| | | `-- format@0.2.2
| | `-- highlight.js@9.16.2
| +-- prosemirror-collab@1.2.2
| | `-- prosemirror-state@1.3.2 deduped
| +-- prosemirror-history@1.1.2
| | +-- prosemirror-state@1.3.2 deduped
| | +-- prosemirror-transform@1.2.3 deduped
| | `-- rope-sequence@1.3.2
| +-- prosemirror-model@1.8.2 deduped
| +-- prosemirror-state@1.3.2 deduped
| +-- UNMET PEER DEPENDENCY prosemirror-tables@1.0.0
| | +-- prosemirror-keymap@1.1.3 deduped
| | +-- prosemirror-model@1.8.2 deduped
| | +-- prosemirror-state@1.3.2 deduped
| | +-- prosemirror-transform@1.2.3 deduped
| | `-- prosemirror-view@1.13.4 deduped
| +-- prosemirror-transform@1.2.2
| | `-- prosemirror-model@1.8.2 deduped
| +-- prosemirror-utils@0.9.6
| +-- prosemirror-view@1.13.4 deduped
| +-- tiptap@1.26.6 deduped
| `-- tiptap-commands@1.12.5 deduped

### Affected platforms

- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
The table logic isn't part of the core library. You could try opening this in https://github.com/ProseMirror/prosemirror-tables instead.
