### ISSUE TITLE
Underline appears in iOS selection tooltip, but does not work

### ISSUE THREAD

**Issue by dminkovsky** [ProseMirror/prosemirror#1037]
### Issue details

On iOS 13.3, the selection tooltip contains options for bold, italic, and underline, but underline does not work.

Please see video: https://imgur.com/a/w7sx9HJ

I'm guessing this is intentional, because web "best practices" seem to have concluded that underlining rich text is an antipattern, because only links should be underlined. 

ProseMirror is the only text editor I've seen that supports this native interface, and that's *awesome*, but is there a way to remove the underline from this menu?

Thanks a lot.

### Steps to reproduce

On an iOS device, go to the PM homepage and try to underline with the selection tooltip.

### ProseMirror version

Latest running on prosemirror.net

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x ] Other (iOS)

### Screenshots / Screencast (Optional)

https://imgur.com/a/w7sx9HJ

**Comment by marijnh** [comment]
Client code has zero control over what iOS shows in its tooltips—at least, that was the situation last time I checked, a few years ago. If you schema implements underlines (and specifies a parse rule that matches whatever iOS creates when you use this tooltip function), it should work.

But I don't think there's anything ProseMirror can do about this, unless someone finds some way to explicitly disable these.

**Comment by dminkovsky** [comment]
Thank you! Sounds good.

Out of curiosity, do you remember how displaying and interacting with the formatting options  is implemented? Could you point me there in the code? I've been searching for this on and off in general for a long time, and have never found it.

**Comment by marijnh** [comment]
> Out of curiosity, do you remember how displaying and interacting with the tooltip formatting options is implemented?

The tooltip (if you mean the iOS one) is entirely native, and not something ProseMirror does anything for or with. When you select an option from it, the browser will mutate the editable DOM, at which point ProseMirror detects the change (in view/src/domobserver.js) and parses the changed part of the document (in view/src/domchange.js, via model/src/from_dom.js). It then compares the parsed content to the matching part of the old document to determine what changed.

**Comment by dminkovsky** [comment]
Oh wow you are, of course, totally right. If you [make a contenteditable div](https://codesandbox.io/s/vigilant-hoover-2ozzx), on iOS the tooltip will have those items: 

<img width="368" alt="Screen Shot 2020-02-29 at 9 35 35 AM" src="https://user-images.githubusercontent.com/218725/75609472-dc13ae80-5ad6-11ea-902c-5b60d62b6152.png">

Thanks for the explanation. I guess that leaves me wondering, then, why other editors don't have this? Maybe there is some way to customize the tooltip? Maybe Safari detects something about the contenteditable and doesn't display them?

Anyway, thanks. You really clarified that for me. I kept searching and not finding any answers.
