### ISSUE TITLE
Copy + Pasting rich content is broken

### ISSUE THREAD

**Issue by liyasthomas** [ProseMirror/prosemirror#1040]
### Issue details

Copy + Pasting rich content is broken.
shows this error in console:

```
prosemirror.min.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at Re.findPlace (prosemirror.min.js:1)
    at Re.enter (prosemirror.min.js:1)
    at Re.addElementByRule (prosemirror.min.js:1)
    at Re.addElement (prosemirror.min.js:1)
    at Re.addDOM (prosemirror.min.js:1)
    at Re.addAll (prosemirror.min.js:1)
    at Re.addElement (prosemirror.min.js:1)
    at Re.addDOM (prosemirror.min.js:1)
    at Re.addAll (prosemirror.min.js:1)
    at Re.addElement (prosemirror.min.js:1)
```

### Steps to reproduce

1. `Select all + copy` contents from any site ex: https://www.wikipedia.org/
2. Go to https://codepen.io/muthu32/pen/rNBzpRK
3. Try pasting copied contents from `step #1` into codepen editor demo
4. See error in console

If you look closely, you can see content is pasted for an instance but flushed out due to some error.

**Expected behavior**
Pasted content should be visible and not getting flushed out.

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
There is no error when pasting into the demo at https://prosemirror.net, so you'll have to figure out what it is about your setup that's causing this if you want me to look into it.

**Comment by liyasthomas** [comment]
That demo uses an old iife compiled prosemirror bundle file. And I couldn't find a way to iife bundle latest prosemirror.

**Comment by marijnh** [comment]
My demo is using the latest version of the library. If you're looking for a bundling tool, try [rollup](http://rollupjs.org/guide/en/)

**Comment by liyasthomas** [comment]
I went with this (https://github.com/netaisllc/prosemirror-starter-app) example using rollup, but couldn't make it working.

I'm using TipTap editor.

Any help is appreciated.

**Comment by colelawrence** [comment]
@liyasthomas you might want to cross post your issue to TipTap as well to see if they can reproduce.

**Comment by andreasvirkus** [comment]
For future Googlers, here's the open issue on Tiptap for this: https://github.com/ueberdosis/tiptap/issues/577
