### ISSUE TITLE
Duplicate links as a result of `toggleMark()`

### ISSUE THREAD

**Issue by loreanvictor** [ProseMirror/prosemirror#1044]
### Issue details

Duplicate link when a selection including the first character of the parent paragraph is toggled to have a mark (like strong) and then toggled again to remove said mark. Toggling the mark back on causes the duplicate link to disappear and toggling it back off again makes it reappear.

#### Further Investigation of the Issue

Rebuilding the DOM representation from `view.state.doc` actually removes the duplicate link. I.e., running something like:

```js
view.dom.innerHTML = "";
view.dom.appendChild(DOMSerializer.fromSchema(schema).serializeFragment(view.state.doc.content));
```

Removes the duplicate link, which might be an indicator that the editor model is not corrupt and the view basically forgets to remove a residual DOM element.

### Steps to reproduce

1. Go to [ProseMirror website](https://prosemirror.net/)
1. On the example editor, on the second line (which says `Try it out ...`) select the first word (`Try`)
1. Press Ctrl+B (or CMD+B on Mac) twice.

### ProseMirror version

I assume the version that is running on the website?

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [x] Other

### Screenshots / Screencast (Optional)

![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/13572283/77300096-c9635280-6ced-11ea-8611-bf1a254b80ac.gif)

**Comment by marijnh** [comment]
Fixed in https://github.com/ProseMirror/prosemirror-view/commit/83afae625d2c76dacf4cdb23a26cdb7ba925f409
