### ISSUE TITLE
Possible Gap Cursor bug after Prosemirror View v1.10.0 update

### ISSUE THREAD

**Issue by Ben-Davis1** [ProseMirror/prosemirror#1045]
### Issue details

Hi.

I'm trying to implement the Gap Cursor plugin in my application and, although it's working to an extent, there's a problem where the caret still shows on the previous node alongside the Gap Cursor being rendered.

The Gap Cursor worked fine before [this](https://github.com/ProseMirror/prosemirror-view/commit/4a56bc7b7e61e96ef879d1dae1014ede0fc09e43) change so I think removing the cursor wrapper "hack" caused problems.

### Steps to reproduce

- Go to [this](https://glitch.com/edit/#!/platinum-environment) example
- Move the caret from the title to the "top" of the image to trigger the Gap Cursor

**Comment by alexeygolev** [comment]
I played around with the current version and it seems like adding the zero-width [non-breaking space](https://github.com/ProseMirror/prosemirror-view/commit/4a56bc7b7e61e96ef879d1dae1014ede0fc09e43#diff-1fdf421c05c1140f6d71444ea2b27638L376) back fixes this. 

I don't understand the reasons behind having or not having it there so I can't make any suggestions. But as far as I understand if that div is empty the caret will be placed into the next valid text node
