### ISSUE TITLE
Two new lines got added when pressing "return" once on IOS

### ISSUE THREAD

**Issue by kongdivin** [ProseMirror/prosemirror#1047]
### Issue details

Given that the cursor is placed at the beginning of the line following by some characters, when we press `return`, two new lines got added instead of one. However, this behavior doesn't happen on the first line.

After a bit of research, I believe it's due to the fix of #1034.

### Steps to reproduce

1. Enter some text on the second line
2. Place the cursor at the beginning of the line
3. Press `return`

### ProseMirror version

I'm using all the latest versions of ProseMirror modules.

- `prosemirror-view`: 1.14.6

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other: IOS browsers; iPhone XR; IOS 13.3.1

### Screenshots / Screencast (Optional)

![RPReplay-Final1586244229](https://user-images.githubusercontent.com/52546124/78642523-bad97700-7867-11ea-841f-773bb1dac6f9.gif)

**Comment by kongdivin** [comment]
This is a workaround I came up with for the time being in case anyone finds it useful.
```js
// Put this plugin at the begining of the plugin list
// so that it blocks the `keypress` event 
// and only the `keydown` event will go through.
new Plugin({
  props: {
    handleKeyPress(view, event){
      if (event.keyCode === 13) return true;
    }
  }
}),
```

**Comment by marijnh** [comment]
Attached patch should help.
