### ISSUE TITLE
[prosemirror-transform] step.from and step.to are not public

### ISSUE THREAD

**Issue by Dattaya** [ProseMirror/prosemirror#1048]
### Issue details
I've found `step.from` and `step.to` very useful in my app, is there any reason not to make them public? 
I can add those fields to the [Step class](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1ea6b2f41ff5211fb4c1dfd124768ce63c305031/types/prosemirror-transform/index.d.ts#L424) in `DefinitelyTyped` if they were not meant to be private.
Thanks.

**Comment by marijnh** [comment]
`Step` is an abstract superclass, and not all subclasses will have these properties. So they can't be public and you really shouldn't rely on them being present.

**Comment by Dattaya** [comment]
Got it, thanks, for now I rely on them heavily, as they're very convenient, but will try to adopt in case  you decide to remove them in favor of something else.
