### ISSUE TITLE
EditorView dispatch isn't sending metadata from a NodeView

### ISSUE THREAD

**Issue by gauravtiwari** [ProseMirror/prosemirror#1049]
### Issue details

The setMeta function seems to be setting the metadata correctly but `this.state.apply(transaction)` is stripping it out for some reason. 

<img width="1398" alt="Screenshot 2020-04-13 at 19 40 23" src="https://user-images.githubusercontent.com/771039/79149191-ae50a380-7dbe-11ea-9345-24c740e7025f.png">

The first one is before `this.state.apply(transaction)` and the second is after apply and then accessing transaction via `state.tr` inside a plugin. 

```js
update(view, lastState) {
  console.log(view.state.tr)
}
```

It's not even working inline:

```js
console.log(transaction) // has metadata
const newState = this.state.apply(transaction)
console.log(newState.tr) // does not have metadata
```

### Steps to reproduce

Use the code editor example and trying setting metadata onSelection from the code editor NodeView and then try listening the transaction from plugin or from `dispatchTransaction`. 
 
https://prosemirror.net/examples/codemirror/

### ProseMirror version

Latest

### Affected platforms

All

---

Thanks for your help 🙏

**Comment by marijnh** [comment]
`EditorState.tr` returns a new transaction every time it is accessed. As such, this is the expected behavior.

**Comment by gauravtiwari** [comment]
Thanks @marijnh for replying. That makes sense.
