### ISSUE TITLE
rangeHasMark can accept a mark too

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#1050]
Documented signature is:
rangeHasMark(from: number, to: number, type: MarkType) → bool

however it also works with:
rangeHasMark(from: number, to: number, mark: Mark) → bool

which is great, so it would be nice if documentation reflected that ?

**Comment by marijnh** [comment]
That seems to be more or less by accident, but sure, makes sense. Want to create a pull request?

**Comment by kapouer** [comment]
No, but i'll do it anyway :)
