### ISSUE TITLE
scrollIntoView flawed when there is a horizontal scroll bar

### ISSUE THREAD

**Issue by boljen** [ProseMirror/prosemirror#1051]
### Issue details

scrollIntoView doesn't work as expected when there is a horizontal scroll bar as it doesn't scroll the entire line into view.

### Steps to reproduce

First make an editor in a page with a horizontal scroll bar. Then type until scrollIntoView is triggered 

See https://glitch.com/~twilight-versed-recess

### ProseMirror version

    "prosemirror-view": "^1.14.5",

### Affected platforms

On windows 10. Doesn't seem to affect edge

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Attached patch should help.

**Comment by boljen** [comment]
thank you!
