### ISSUE TITLE
Can't click inside a selected block node with content in Safari

### ISSUE THREAD

**Issue by timhor** [ProseMirror/prosemirror#1052]
### Issue details

When a block node containing content is selected, it is not possible to single click inside to edit that content until deselecting the node again. This is only an issue in Safari – it works as expected in Chrome.

### Steps to reproduce

1. See https://glitch.com/~butternut-whispering-caterpillar
2. Select the node (e.g. triple click the border)
3. Try and click inside (e.g. on the text)

**Expected behaviour:** the ProseMirror selection is removed and the cursor moves to the position that was clicked on

**Actual behaviour:** the ProseMirror selection remains

### ProseMirror version

Latest (using Glitch)

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other: Safari (version 13.1, running on macOS 10.15.4)

### Screenshots / Screencast (Optional)

![ProseMirror Safari bug](https://user-images.githubusercontent.com/14193387/80329085-88c69e00-8884-11ea-8f3c-22a42b13ff17.gif)

**Comment by marijnh** [comment]
Safari seems to consider draggable nodes as indivisible units when it comes to mouse click behavior. Attached patch works around that.
