### ISSUE TITLE
Can't set NodeSelection on position resolving to node containing text node

### ISSUE THREAD

**Issue by timhor** [ProseMirror/prosemirror#1053]
### Issue details

When attempting to set a NodeSelection on a position that resolves to a node containing a child text node, ProseMirror tries to add a class to the text node, which fails because it is not a DOM element.

Setting the selection on the position immediately prior to that works, but the resolved node is `doc`.

### Steps to reproduce

1. See [https://glitch.com/~flicker-flax-river](https://glitch.com/~flicker-flax-river)
2. Click on `Select Node C`
3. Browser throws an error, `Uncaught TypeError: Cannot read property 'add' of undefined`, and the node does not get selected (first issue)
4. Click on `Select before Node C`
5. The `doc` node gets selected (second issue)

### ProseMirror version

Latest (using Glitch)

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
The demo is creating an invalid node selection—a node selection should point before the selected node, but this one is pointing inside of it. Text nodes cannot be selected.
