### ISSUE TITLE
Paste in IE broken while using focus locks 

### ISSUE THREAD

**Issue by AlecTroemel** [ProseMirror/prosemirror#1056]
thanks in advance for taking a look at this issue, and for prosemirror in general!

### Issue details
w3c A11y  suggest creating "focus traps" (focus stays within a sub section of the page) for some UI elements, such as dialog boxes.

however, for browsers that have "broken clipboard api's", pasted text gets placed at the beginning of the editor, regardless of where the cursor is.

From some digging, it looks like prosemirror attempts to create a new element at the root of the pages document (often the `body`) and focus too it during copy/paste. [The logic here](https://github.com/ProseMirror/prosemirror-view/blob/ff08f541daf7313e32bc3ff1dbbd0be1059a425e/src/input.js#L511) looks to be being clobbered by what focus traps are doing.

I believe a solution would be to add that new dom element as a sibling of the editor instead of at the root of the page, so that focus never leaves the "trap" part of the page. There's really not a good way (that I know of) for any focus trap to special case/work around what prosemirror is doing here.

### Steps to reproduce

I've set up an example here https://glitch.com/~atlantic-animated-astronaut, simply open that link in IE and try to paste text while the lock is active.

### ProseMirror version
latest

### Affected platforms
- [ ] Chrome
- [ ] Firefox
- [X] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)
![image](https://user-images.githubusercontent.com/8620042/81218070-359acc80-8fa3-11ea-812e-87dea7552660.png)

![image](https://user-images.githubusercontent.com/8620042/81218107-46e3d900-8fa3-11ea-9119-8a45a6a5c321.png)

**Comment by marijnh** [comment]
Does attached patch help for this?

**Comment by AlecTroemel** [comment]
@marijnh from just looking at the patch, it looks like what I need! I'm still working on testing the patch out locally, I'll comment here once I do that. Thanks for working on this!

**Comment by AlecTroemel** [comment]
@marijnh I've confirmed that your patch resolves the issue for my use case. thanks again! Closing this issue

**Comment by marijnh** [comment]
Thanks for the confirmation. I've released this as prosemirror-view 1.14.10
