### ISSUE TITLE
Inline decoration remove mark(link) if they have same text range

### ISSUE THREAD

**Issue by domio** [ProseMirror/prosemirror#1063]
### Issue details

If decoration and mark(link) have the same text range and add a space after this text, then mark(link) is deleted and there is no space after the text.

### Steps to reproduce

https://prosemirror.net/examples/lint/

1. Add link to `obviously`
2. Set cursor after `obviously`
3. Tap space

**Actual result**: link is removed and there is no space after `obviously`

**Expected result**: link exist and space is added

**Researching**:

Add space -> DOMObserver react on adding of decoration -> readDOMChange function -> isMarkChange function -> current text node hasn't mark(link) -> tr.removeMark

### ProseMirror version

Reproduced using the version hosted at https://prosemirror.net/examples/prosemirror.js (2020-05-27).
Additionally reproduced with prosemirror-view 1.14.5 in my own environment.

### Affected platforms

- [x] Chrome

**Comment by marijnh** [comment]
What apparently happened is that Chrome updated the DOM from `<a><span>text</span></a>` to `<span><a>text</a> </span>` (where the span was created for the decoration) when this editing pattern occurs. The code that hides decoration spans from the content parsing didn't expect that, and ended up discarding the `<a>` tag. Attached patch should help.
