### ISSUE TITLE
`Missing comma or closing paren` using getdocs 0.6.1

### ISSUE THREAD

**Issue by aisnoek** [ProseMirror/prosemirror#1065]
### Issue details

Since updating to prosemirror-model (1.10.0) i receive the following message when using your other library getdocs (0.6.1):

```
SyntaxError: Missing comma or closing paren for node_modules/prosemirror-model/src/node.js:225
    at Input.error (/Users/manuel.snoek/projects/brandspot-ng/ui-ioc/node_modules/builddocs/node_modules/getdocs/src/parsetype.js:46:11)
```

This is caused by the pipe (`|`) in the following commit: https://github.com/ProseMirror/prosemirror-model/commit/04ec15d38a916d7e10a01f9d1c37ec9570817751

### ProseMirror version

prosemirror-model 1.10.0
getdocs 0.6.1

**Comment by marijnh** [comment]
Oops, I accidentally used TypeScript notation there. Attached patch should help.

**Comment by aisnoek** [comment]
This change fixes it, thanks for the quick response!
I'll be looking forward to the next release now 😄

**Comment by aisnoek** [comment]
@marijnh, could you create a release for prosemirror-model? Due to policies i can't apply your changes as a patch.
We would be greatful!

**Comment by marijnh** [comment]
Why are you running getdocs locally, though?

**Comment by marijnh** [comment]
Ah, you're in luck, another bug in prosemirror-model forced a new release anyway, so 1.10.1 is out without this issue.

**Comment by aisnoek** [comment]
> Why are you running getdocs locally, though?
We're using it to generate typescript-definition files. Quite useful from time to time.

> Ah, you're in luck, another bug in prosemirror-model forced a new release anyway, so 1.10.1 is out without this issue.
Nice to see luck is in my favor. Thank you very much.
