### ISSUE TITLE
[prosemirror-keymap] regression in w3c-keyname @> 2.2.2 dependency

### ISSUE THREAD

**Issue by cge** [ProseMirror/prosemirror#1067]
### Issue details

Having issues with [prosemirror-keymap](https://github.com/ProseMirror/prosemirror-keymap) used in a component library published with rollup and consumed in a (cra) react app.

Everything worked fine, until the `prosemirror-keymap` sub-dependecy, [w3c-keyname](https://github.com/marijnh/w3c-keyname), [moved from version 2.2.2 to higher versions](https://github.com/marijnh/w3c-keyname/commit/6bb3aba1b762382ef1ae66f2812f20cfaeedab44)

This happens because of the following matcher for ["w3c-keyname": "^2.2.0"](https://github.com/ProseMirror/prosemirror-keymap/blob/master/package.json#L20)

Since `w3c-keyname` version `2.2.3` or higher `prosemirror-keymap` breaks and errors with `Uncaught TypeError: w3cKeyname.keyName is not a function` or similar.

### Steps to reproduce

Use `"prosemirror-keymap": "1.1.4"` as described above, with:

- `node -v` : `v12.17.0`
- `npm -v` : `6.14.4`
- `yarn -v` : `1.22.4`

### ProseMirror version

```
"dependencies": {
    ...,
    "prosemirror-keymap": "1.1.4"
  },
```

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Edge

### Screenshots / Screencast (Optional)

![w3cKeyname keyName_not_function](https://user-images.githubusercontent.com/1171773/84660345-fe5ff980-af18-11ea-9408-0d37ef32c7d2.png)

**Comment by marijnh** [comment]
Can you show a minimal rollup config that displays the problem?

**Comment by cge** [comment]
Hi @marijnh , thank you for the quick support ! Sure, here you go:

```js
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import external from 'rollup-plugin-peer-deps-external';
import filesize from 'rollup-plugin-filesize';
import postcss from 'rollup-plugin-postcss';
import resolve from 'rollup-plugin-node-resolve';
import url from 'rollup-plugin-url';
import svgr from '@svgr/rollup';

const pkg = require('./package.json');

export default {
  input: './index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true
    }
  ],
  plugins: [
    external(),
    postcss({
      modules: true
    }),
    url({ exclude: ['**/*.svg'] }),
    svgr(),
    babel({
      exclude: 'node_modules/**',
      externalHelpers: true
    }),
    resolve(),
    commonjs(),
    filesize()
  ],
  external(id) {
    return !/^[\.\/]/.test(id);
  }
};
```

With
- `pkg.main` : `lib/index.js`
- `pkg.module` : `dist/index.es.js`

**Comment by marijnh** [comment]
That's not minimal though—I'm asking you to do the work of figuring out which of those the plugins and options aren't related to the problem, so that I have less to debug.

**Comment by cge** [comment]
Understood, it is a little busy here right now. Will make a minimal example as soon as time allows. Thanks again for taking a look. For the moment I can quickly share some `exact` dev dependencies:

```js
{
"devDependencies": {
    "@babel/cli": "7.10.1",
    "@babel/core": "7.10.2",
    "@babel/plugin-external-helpers": "7.10.1",
    "@babel/plugin-proposal-decorators": "7.10.1",
    "@babel/plugin-proposal-do-expressions": "7.10.1",
    "@babel/plugin-proposal-export-default-from": "7.10.1",
    "@babel/plugin-proposal-export-namespace-from": "7.10.1",
    "@babel/plugin-proposal-function-bind": "7.10.1",
    "@babel/plugin-proposal-function-sent": "7.10.1",
    "@babel/plugin-proposal-json-strings": "7.10.1",
    "@babel/plugin-proposal-logical-assignment-operators": "7.10.1",
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.10.1",
    "@babel/plugin-proposal-numeric-separator": "7.10.1",
    "@babel/plugin-proposal-optional-chaining": "7.10.1",
    "@babel/plugin-syntax-dynamic-import": "7.8.3",
    "@babel/plugin-syntax-import-meta": "7.10.1",
    "@babel/preset-env": "7.10.2",
    "@babel/preset-react": "7.10.1",
    "@svgr/rollup": "5.2.0",
    "cross-env": "6.0.3",
    "enzyme": "3.10.0",
    "enzyme-adapter-react-16": "1.15.1",
    "node-sass": "4.14.1",
    "npm-force-resolutions": "0.0.3",
    "npm-run-all": "4.1.5",
    "npmversion": "1.7.0",
    "react-test-renderer": "16.12.0",
    "rimraf": "3.0.2",
    "rollup": "1.31.1",
    "rollup-plugin-babel": "4.3.3",
    "rollup-plugin-commonjs": "10.1.0",
    "rollup-plugin-copy": "3.3.0",
    "rollup-plugin-delete": "1.2.0",
    "rollup-plugin-filesize": "6.2.1",
    "rollup-plugin-node-resolve": "5.2.0",
    "rollup-plugin-peer-deps-external": "2.2.2",
    "rollup-plugin-postcss": "2.1.1",
    "rollup-plugin-url": "3.0.1"
  }
}
```

**Comment by cge** [comment]
The issue seems to have nothing to do with rollup, as I can reproduce it inside a lerna / yarn workspaces environment where code is linked and hot-reloaded without any extra transformation. I invite you to check the report here before going any further: https://github.com/cge/prosemirror-react-example/tree/master/issues

**Comment by marijnh** [comment]
This is working for me, in two projects (my CommonJS-based ProseMirror setup and my ES module based CodeMirror/next setup). If you want me to look into it, show a simple file that, with a simple bundling config (preferably rollup), fails to load, so that I can reproduce the problem.

**Comment by cge** [comment]
First wanted to document clearly a [setup](https://github.com/cge/prosemirror-react-example) that fails (using versions of tools stated in the readme) and if nothing is obviously wrong, try to find time for a minimal example.. though it will have to wait some days. Aah, CodeMirror/next - so many great tools (thanks!) and really don't want to waste time. Would love the most basic React + pm example to work though, so the minimal example may still contain that.. Cheers!

**Comment by cge** [comment]
Btw, this seems related https://github.com/scrumpy/tiptap/issues/665 ..not sure what to make of everything, but many users cannot upgrade their Node version when they want and staying off the bleeding edge seems hard when sub-dependencies continue upgrading themselves. Lock files seem inadequate without assistance from yarn resolutions or an equivalent npm hack.

**Comment by cge** [comment]
Please excuse the wait. It is also working fine for me in a new vanilla CRA setup (not using example workspaces setup), so happy to put it down to something esoteric. Let's close. Will re-open if it becomes a problem again, thanks.
