### ISSUE TITLE
[prosemirror-view] Regression with copy & paste with embedded Codemirror

### ISSUE THREAD

**Issue by kommen** [ProseMirror/prosemirror#1068]
### Issue details

We recently upgraded prosemirror and discovered a regression that broke copy & paste when the codemirror was focused with the mouse. The effect in our app is that the clipboard is empty after a copy: in the `copy` callback `view.state.selection.content()` is empty. We only observe the problem when the selection is inside an embedded codemirror NodeView.

We’ve bisected and identified
https://github.com/ProseMirror/prosemirror-view/commit/6ffaa35c2475a91167cda78167adfd925270220b as the culprit. Earlier versions work.

Also overriding the NodeView's `ignoreMutation` callback to just check for `contentDOM` again on this makes copy work again with latest prosemirror-view (1.14.13).

Some further observations:

If the codemirror node was focused using the mouse, when the codemirror cursor blinks the `ignoreMutation` callback is called with `type` `"selection"`. Instead, if the keyboard is used to focus the codemirror node (we handle arrow up and down and disptach appropriate `setSelection` transactions), cursor blinks do not result  `ignoreMutation` calls with `type` `"selection"`.

### Steps to reproduce
Unfortunately we have not yet been able to reproduce the problem with the built-in prosemirror examples. We differ a bit from the standard prosemirror/codemirror example in that we allow inline nodes as content for code cells, specially our code cells have:

```content: "inline*" code:false defining: true isolating: true```

Should we try to create a selection or clipboard-test reproducing the issue? Any further info we can provide?

### ProseMirror version
1.13.9 and later affected

### Affected platforms
- [x] Chrome
- [x] Firefox
- [x] Safari

**Comment by marijnh** [comment]
> Should we try to create a selection or clipboard-test reproducing the issue?

A minimal reduction of the setup in which I can reproduce the issue would be helpful. I haven't managed to reproduce this so far, and don't see any obvious reasons why it might be happening.

**Comment by marijnh** [comment]
We took another look at the code, and concluded that adding an `ignoreMutation() { return true }` handler to the node view is the appropriate solution there. (Copy events were deferred to the outer ProseMirror, and the selection handling was setting that editor's selection to empty on DOM selection change events.)
