### ISSUE TITLE
Textnode doesn't support hasAttribute

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#107]
I have content that looks like
`<label class="textfield" contenteditable="false" pm-offset="227" pm-leaf="true">asdf<input type="text" name="test" size="20"></label>`
In edit/draw/redraw the following code fails:
(129) if (!first || first.hasAttribute("pm-ignore") || first.hasAttribute("pm-offset")) break
`first.hasAttribute` fails because hasAttribute is undefined.  First is the Textnode("asdf").  Do I have the elements wrong?  I added !first.hasAttribute to the above test and it fixed the problem.

**Comment by marijnh** [comment]
What kind of node is producing this HTML? Does it allow child nodes? Is it inline or a block node?

**Comment by pboysen** [comment]
I have since decided to get rid of the label wrapper because it was adding too much complexity.  Below might work if I made the label a node with a textfield as a child.  You can close if this is not a valid configuration since I no longer have an error.

export class Textfield extends Inline {}

Textfield.attributes = {
	name: new Attribute(),
	label: new Attribute(),
	loc: new Attribute(),
	size: new Attribute({default: "20"})
}
Textfield.prototype.serializeDOM = node => {
	let loc = node.attrs.loc
	let input = elt("input", {name: node.attrs.name, type:"text", size: node.attrs.size})
	if (loc == "left")
		return elt("label",{class: "textfield"}, 
			node.attrs.label + " ",
			input
		)
	else if (loc == "top") {
		return elt("label",{class: "textfield"}, 
			node.attrs.label,
			elt("br"),
			input
		)
	} else {
		return 	elt("label",{class: "textfield"},
			input,
			" "+node.attrs.label
		)
	}
}
