### ISSUE TITLE
multiple versions of prosemirror-model

### ISSUE THREAD

**Issue by u12206050** [ProseMirror/prosemirror#1070]
### Issue details

Trying to add new content:

"Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)"

### Steps to reproduce
Using tip-tap and an editable content area and trying to add new line of text but the cursor just jumps back.

### ProseMirror version
     prosemirror-model "version": "1.10.0",

previously worked on prosemirror-model   "version": "1.9.1",

### Affected platforms

--all browsers

### Screenshots / Screencast (Optional)

![Skjermbilde 2020-06-18 kl  13 44 32](https://user-images.githubusercontent.com/6641242/85016366-e03d0800-b169-11ea-935a-a56742c4bd49.png)

**Comment by u12206050** [comment]
This issue broke two production websites right after 25 May 2020. Luckily I could match that up with the changelog of [prosemirror-model](https://prosemirror.net/docs/changelog/) and see that it was updated from 1.9.1 > 1.10.0

**Comment by marijnh** [comment]
Have you investigated whether you are in fact loading prosemirror-model multiple times? Because that's not something this library can fix for you.

**Comment by u12206050** [comment]
I am only loading it once, but since it is an SPA it might be reusing an old instance or something, but it breaks even on a full refresh. I have revert back to the previous version and that works. Will look into a bit myself, I realize this is probably more unique than I first though.

**Comment by mbenadda** [comment]
Hey @u12206050, did you end up finding the cause of this problem? I'm struggling with this at the moment and reverting to 1.9.1 did not fix it for me.

**Comment by u12206050** [comment]
No sorry,  I just stuck to using the old version

**Comment by csytan** [comment]
I had this same error happen after upgrading `prosemirror-view` to the latest version. I fixed it by deleting my `yarn.lock` file and `node_modules` and reinstalling.

See also:
https://github.com/ProseMirror/prosemirror-example-setup/issues/6#issuecomment-362641056

**Comment by NickLaiacona** [comment]
I had this same problem with prosemirror-model 1.14.3. Solution @csytan mentions works for me as well.

**Comment by mmmulani** [comment]
Ran into this issue when upgrading prosemirror-view past 1.24.0, removing `@types/prosemirror-view` from my package.json solved the issue.

**Comment by mltucker** [comment]
I ran into this issue when upgrading to webpack 5. It looks like some code is loading `prosemirror-model/dist/index.js` and other code is loading `prosemirror-model/dist/index.cjs`. Will update if I find a solution.
