### ISSUE TITLE
Unexpected behavior of ProseMirror with Google Translate Extension

### ISSUE THREAD

**Issue by svetq** [ProseMirror/prosemirror#1074]
### Issue details

When used with Google Translate extension the functionality isn't as expected. Please check the following recording:

### Steps to reproduce

Install the [Google Translate Extension](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb?hl=en)

Go to the example from the following article:
https://prosemirror.net/examples/basic/

Click "Translate this page" of the Google Translate Extension.

Change the language from English to something else (in my case to Bulgarian).

Start typing in the Editor and notice the behavior. 

### ProseMirror version

latest

### Affected platforms

any browser

### Screenshots / Screencast (Optional)

http://somup.com/cYiilOQJu1

**Comment by marijnh** [comment]
Dealing browser plugins that crudely mess with the DOM is not something that I know how to do. This will probably never work (unless you find a way to notify such a plugin to leave the editor's DOM in peace).

**Comment by MKlblangenois** [comment]
Just facing with the same issue when there's a link in my text content and my browser automatically translate the content.

However, there is a possibility to prevent this problem, just add the classe `notranslate` on the element or the parent to avoid translating certain parts of a site. I've tried on my side and it's work with Google Translate on Chrome : https://streamable.com/zy8ruy

@marijnh, maybe you can add this fix in the roadmap of ProseMirror, but it would be useful to fix this problem, and avoid having a loss of content in the case where a browser automatically translates and the editor saves the content

**Comment by marijnh** [comment]
Does `translate=no` also work in your tests? That's at least [standardized](https://www.w3.org/TR/html51/dom.html#the-translate-attribute).

**Comment by MKlblangenois** [comment]
> Does `translate=no` also work in your tests? That's at least [standardized](https://www.w3.org/TR/html51/dom.html#the-translate-attribute).

No, `translate=no` isn't working on my side, even if I apply the attribute directly on element

**Comment by marijnh** [comment]
In my [test](https://translate.google.com/translate?hl=&sl=nl&tl=en&u=https%3A%2F%2Fmarijnhaverbeke.nl%2Fupload%2Ftranslate.html), google translate seems to respect neither. Am I doing something wrong?

**Comment by marijnh** [comment]
Oh, hold on, it's a _class_, not an attribute. That's exceedingly dumb, especially since a standard exists. I'm a bit conflicted about adding such poorly-conceptualized and probably-unstable stuff to the core library.

**Comment by marijnh** [comment]
Google Translate seems to have improved in the time since this discussion, and now supports the standard translate=no attribute. Attached patch adds this by default to the editor element. Which I guess means we can finally close this issue.
