### ISSUE TITLE
Make StepMap.ranges public

### ISSUE THREAD

**Issue by Narretz** [ProseMirror/prosemirror#1075]
### Issue details

The StepMap.ranges property currently isn't documented as publicly accessible, both in the docs and in the types. You can access in in code obviously.
My use case is that I have an existing step from which I want to create a new step, that moves the start range a certain value. In the end, the step maps should match step maps from a different source exactly, so inserting steps
For this, I need to access the ranges. StepMap.offset() doesn't really work here, because it moves positions, but doesn't modify the start of a range.
Now I can obviously silcence typescript here, but it would be nice if ranges was public, or at least reachable with a getter.
Another option would be to have an instance startOffset function that applies the offset to the range start and returns a new StepMap: 
https://prosemirror.net/docs/ref/#transform.StepMap^offset
I also assume there was a reason, why ranges isn't public, but I can't really see what it would be (except to prevent modifying in place).

### ProseMirror version

prosemirror-transform@1.2.7

**Comment by marijnh** [comment]
Why not use the `forEach` method?

**Comment by whawker** [comment]
My two cents. Would be useful to know if a stepMap is empty. I've seen a few examples of people doing `stepMap.ranges.length === 0` 

Would it be possible to make the length public (`stepMap.length` / `stepMap.size`)?

**Comment by marijnh** [comment]
You should in most cases be able to compare against `StepMap.empty` to determine whether a map has any changes in it. As of prosemirror-transform 1.3.4 this is guaranteed to work.
