### ISSUE TITLE
bin/pm watch conf.output.forEach is not a function

### ISSUE THREAD

**Issue by Xheldon** [ProseMirror/prosemirror#1077]
https://github.com/ProseMirror/prosemirror/blob/57ae62d04698b1c393c45b0fbe9204caa8f86cf4/bin/pm.js#L290

when run `bin/pm watch` an error throw out: `conf.output.forEach is not a function`, maybe conf.output should treated as an object?

I find @marijnh  has a pr to deal with it by purpose

https://github.com/ProseMirror/prosemirror/commit/57ae62d04698b1c393c45b0fbe9204caa8f86cf4

but it seems wrong?

my dev env info: 

Node: 10.15.1

npm: 6.4.1

rollup: ^0.49.0

**Comment by marijnh** [comment]
Try to find out which rollup.config.file it is loading when the error occurs. I'm using this in my local dev setup and there it works (all submodules have an array in their rollup config output field)

**Comment by Xheldon** [comment]
I re-run the command and the error is gone... I'll try to find out why.  Anyway, thanks!
