### ISSUE TITLE
PreserveWhitespace:true inserts space at beginning of inline node following a br node.

### ISSUE THREAD

**Issue by tubsandcans** [ProseMirror/prosemirror#1079]
### Issue details

In my attempt to accurately render paragraphs with leading whitespace, I discovered the 'preserveWhitespace' parser option. This correctly preserves the leading whitespace in paragraphs, but seems to add a leading space to any inline/text nodes immediately following a \<br\> node. Similarly, if I set this option to 'full', it adds a newline to the beginning of any inline/text nodes immediately following a \<br\> node.

### Steps to reproduce

Use the DOMParser (with option preserveWhitespace: true) to parse an html string like:

`<p>Text<br># A \"heading\" with no blank line before it</p>`

The line: `# A \"heading\" with no blank line before it` gets rendered with an extra leading space.

### ProseMirror version

"prosemirror-model": "^1.7.5"
"prosemirror-state": "^1.2.4"
"prosemirror-view": "^1.12.3"

### Affected platforms

- [84.0.4147.89] Chrome
- [75.0] Firefox

**Comment by marijnh** [comment]
I'm not seeing this...

```
let div = document.createElement("div")
div.innerHTML = `<p>Text<br># A "heading" with no blank line before it</p>`
console.log(DOMParser.fromSchema(schema).parse(d, {preserveWhiteSpace: true}).toString())
// ==> doc(paragraph("Text", hard_break, "# A "heading" with no blank line before it"))

**Comment by tubsandcans** [comment]
You're right, I guess markdown-it was adding the newline after the `<br>`. This would also explain why `preserveWhitespace: 'full'` would behave as it was with this input.
