### ISSUE TITLE
The buildParamsForm select box does not update with current value

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#108]
In menu/menu.buildParamsForm the current code at line 195 does not set the correct value for selected.  The current code is:
field = elt("select", {name}, (param.options.call ? param.options(pm) : param.options)
                 .map(o => elt("option", {value: o.value, selected: o == val}, o.label)))
It should be:
      field = elt("select", {name}, (param.options.call ? param.options(pm) : param.options)
                  .map(o => elt("option", {value: o.value, selected: **o.value** == val}, o.label)))

I tested it and it sets the value correctly.  Unfortunately it still doesn't work because I think the select has to be reloaded.  Not sure where to do that.

**Comment by marijnh** [comment]
The showing of parameter forms (and menu items) is a bit of an ad-hoc mess at the moment. I appear to be using the `default` property in two inconsistent ways. I'll try to clean this up this week.
