### ISSUE TITLE
[Android] On devices with Gboard can't apply bold or italic to symbols inside word

### ISSUE THREAD

**Issue by 8alery** [ProseMirror/prosemirror#1080]
### Issue details

On Android devices with GBoard applying format inside single word doesn't work if there are any suggestions. For example I type "Som" and than select "B" from toolbar. If there are suggestions at the bottom style won't change. And it has different behaviours than you change style back (you want to bold only several letters) or than you wont the rest of the word bold. In first case style wont stick at all. And in second it will be applied after first space. 

### Steps to reproduce

1. Open https://glitch.com/edit/#!/remix/prosemirror-demo-basic on Android device with Gboard
2. Type "Som"
3. Turn on Bold
4. Type "eth"
5. Turn off Bold
6. Type "ing"

Expected result: eth is bold
Actual result: all letters is normal

Alternate scenario:
1. Open https://glitch.com/edit/#!/remix/prosemirror-demo-basic on Android device with Gboard
2. Type "Inter"
3. Turn on Bold
4. Type "stellar"

Expected result: stellar is bold
Actual: stellar is normal until I hit Space

### ProseMirror version

Should be

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [+] Other

Android 10 Chrome (Gboard)

### Screenshots / Screencast (Optional)
http://g.recordit.co/q0aimqafuD.gif

**Comment by marijnh** [comment]
Does attached patch help for you?

**Comment by marijnh** [comment]
Patch https://github.com/ProseMirror/prosemirror-view/commit/dd8026e52a18f1fedbbe56fbd5db42ef17b96677 that is.

**Comment by 8alery** [comment]
Yes, it works perfectly! Thank you so much!
