### ISSUE TITLE
Possible bug on chrome when inserting nodes while editor not focused

### ISSUE THREAD

**Issue by ifiokjr** [ProseMirror/prosemirror#1084]
### Issue details

When the editor is not focused and I insert an atom node it looks like everything is okay for a while but when typing text afterwards the selection jumps from what ProseMirror says to an earlier position in the document. This only happens in Chrome and not in **Firefox** or **Safari**.

**EDIT:** Updated broken links in response to comment from @kepta

### Steps to reproduce

Unfortunately, I only have reproduction right now in the [remirror playground][playground].

1. Open chrome
2. Navigate to the **[playground]**
3. You should see an editor at the bottom of the screen

![image](https://user-images.githubusercontent.com/1160934/90319148-51602800-df2d-11ea-8b7c-2f8b175f3e99.png)

4. Click outside the editor first to lose focus
5. Tap the **Hr** buttons two or three times.
6. Now start typing
7. Your text will appear above the first `hr` rather than after it.
8. For further inspection you can open `prosemirror-dev-tools` located in the bottom right hand corner of the page.

![image](https://user-images.githubusercontent.com/1160934/90319244-2a562600-df2e-11ea-9010-87b214bf143a.png)

### ProseMirror version

**`prosemirror-view`**: 1.15.4

### Affected platforms

- [x] Chrome `84.0.4147.105`
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

#### Chrome with focus ✅

![2020-08-15 15 05 56](https://user-images.githubusercontent.com/1160934/90315474-cc1c4980-df13-11ea-81c7-3dfd34521c10.gif)

#### Firefox without focus ✅

![2020-08-15 15 23 52](https://user-images.githubusercontent.com/1160934/90315498-fb32bb00-df13-11ea-9cd8-256e5736e37e.gif)

#### Safari without focus ✅

![2020-08-15 15 24 20](https://user-images.githubusercontent.com/1160934/90315502-04bc2300-df14-11ea-9ec7-3e071a50ef9f.gif)

#### Chrome without focus ❌

![2020-08-15 15 06 58](https://user-images.githubusercontent.com/1160934/90315486-e3f3cd80-df13-11ea-8f64-68eebf2beb53.gif)

[playground]: https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjyF8jBhVr0cAEXIA3ACqZMzUsLET8AcnmKrq-nsvPQMMHAJqVgRcWBMAMQBhWLJyAGVcVlxyd3FMSRkFKNxdfUNwkwAhF34AUQAPLN5SFExeHM8Cv2UVcgbyJpbeFQAjapLQowIiAEkM5hQEesbm1va86RAFS27e5cGVFDmF8bLjIgBVAXJsed5yJf6VtpFc-M2unB6+gdaVPkCbig7icwmd8AAJcisfhAzgPH7PDzrTrbT67R77AAWUJhvE4IMmJnBOBQAC9WnNKMRmPdvk81m8tko0XSsSTybw5gBabDU8gE8pEAAyKFIuDM5AoBBeHXeqNU6AUUpU8zFArB1HlZkwdhQAOSFAAsqxeKxONcDVQPthLYxMM1cINrgyNkz-CpCtFxghWmL8DUABoOGoAOVS0wA8mH8ABefAAbX0+HwdwA7hCcbD4U8ABQASlgSZT5HTVWYtVZrXzhbaxfTs1Y80Wld41aLafwlwBt1peyrBfbJfwIrFEqlbdrHeJ2DJFMbVJp2cG+f0AF0QvpRHxooN8Ib+sR84Qi8mfU0pvgfWAwCb+KRYkUUHZyLFdUORHGUprmdgc0RWMQuCYOc6D8Jk5CQPguC8tkQh5hutbJgouDENgbQ5ieyb4AAPDCdgAHyYVhOHDIBQG8ERxH4K0CRNgA1jGwBHjG+GXnkN4CKQAB0QGcJwNJlvw+ZCJRxFiuwNKMUQogUgA6uQKCcJiuCQY+z5caM5ZHgA-N4mn8F4+CQf85CiEC5CCEIImIVRhE2VR+AVKJOEjGRrR2Q5ybYaRuDkc5yY0fRjHMaxV4cXePGYHxNINk2wn+fg4mScA0lyQpSkqfgankFxhyNgsOl6dUhnGVcZl3JZ1mefgHnVfg0zOdhrm+e5jU+X59lUYFCwMUxeaxqF7G3txvH8eQXbXD28WdWJuASeQUliGlinKapO7qSZgJ3IVXj6SVJBleZlXObV1XnI1zXkadVHeW5FEzVh3UIL1IVsdew2RdF5CQtCsJ-vgNLPswkHQMIeZVXVSULSlS2cvJK2ZdlXHYr9eL-YD5DA-goNwfgum7cVRkHYE5UWcIEMOddDngtAF3ta1D23S1911dRvC0T1wX9Sxb3hSNUVjT9uKcOj9iY5BABMYMU55UOLTJcPpatWXrTlKPC6LQOS2DeNFeW+0maTx0PVTVHghLdN3abXn0yzdVPS93OsUQYUfUCFB4NOs6cvOfL-aKcSYAgKT8JBb6psjrCkIHwekEeuNWQlcswwruDwxla2Oup6t-UQGNY1LuP43tROG0d5MnQl4LYJbzOm01eHXfBRbWfoKgAFTt0m7f4A4mKim9WB3JybE++7UHYvgFmHDgWUCHP7BQc4zDDKw2CkCoCCYhI2SHPgCgAI7EHQkpcd3Kj6GefqpDezDMDUMJAdgkGJLG+CvcARZXxe5q4JQzjigYOge8vNhruE-BQb8-h8whCQuQFCaF36YVwk+eueFCBcUwb-f+mBAGYGAcJfAKh677l4MQIh10G6oKLM3XgQgELf3wDfRs99H44FktgVg6B0DOjjB-L+voCDogRMaU05psBvxSKIs01wcyBmDGGSMYZaGnkESYOwjZiAvjZgkTEJpzTgJIJA60LAODcEwP8HMwinjSPEfBIhKh8C2BpFkCeA8exFmQqhdCyCoHKG1LqAElEOIyOwIxaxgxbHXBlsmDRzAtGMTiVomJOi9F4mhjRNJ5oZZoOoTNbCzC74PxnhI4holsLagsD+Wwjhl5uDKZ1KhBFkEqD8UwBggTri1VofQ-Q+heiEhJgBZgBBCmsJKRwrhPDsA6BAEIIAA

**Comment by kepta** [comment]
I opened the link to [playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjyF8jBhVr0cAEXIA3ACqZMzUsLET8AcnmKrq-nsvPQMMHAJqVgRcWBMAMQBhWLJyAGVcVlxyd3FMSRkFKNxdfUNwkwAhF34AUQAPLN5SFExeHM8Cv2UVcgbyJpbeFQAjapLQowIiAEkM5hQEesbm1va86RAFS27e5cGVFDmF8bLjIgBVAXJsed5yJf6VtpFc-M2unB6+gdaVPkCbig7icwmd8AAJcisfhAzgPH7PDzrTrbT67R77AAWUJhvE4IMmJnBOBQAC9WnNKMRmPdvk81m8tko0XSsSTybw5gBabDU8gE8pEAAyKFIuDM5AoBBeHXeqNU6AUUpU8zFArB1HlZkwdhQAOSFAAsqxeKxONcDVQPthLYxMM1cINrgyNkz-CpCtFxghWmL8DUABoOGoAOVS0wA8mH8ABefAAbX0+HwdwA7hCcbD4U8ABQASlgSZT5HTVWYtVZrXzhbaxfTs1Y80Wld41aLafwlwBt1peyrBfbJfwIrFEqlbdrHeJ2DJFMbVJp2cG+f0AF0QvpRHxooN8Ib+sR84Qi8mVCp8A5sSQKPgsA6ndh8JjnABrfCN5iYVNuUQ4fC4bAohfWF-yvBBiHofoCAoGkd1WIFQOycgYVwHAADoT3wH0mimUZcFQsBYhpUQYnwBRRBEOMUjte9WmuHMvGGYhhmGGkvDzDda2TbC-SIH0wDAE1+FIWIihQOxyFiXUh0o68rXlHMiFYYhUPOdB+EychIH-XlsiEDjMJ4lxyDQz9OEUmDyDg3htOk1M0LFTSHPIWDHVaNDXliTFWFIOJMHA0hbJQEs0O83z-LIfN9M4zCFFwCC2hzTDkwAHhhOwyPIUQY2AciRDFdgaRyog8IIoistIu9DkGbSvFYYZSBcFTyC8WIhCEAA+ZLk3wFKmPw1pup6-BWgSJsXxyo8Yw6rC8kEgRSDQ1DOE4Gky34KKhp6gqiuAIhf05AB1cgUE4TFcG0sSJLQ0ZyyPAB+bxbv4Lx8G0-4sqBZDhCELauq44aeoqLaUpGFTUN4f7AZ6vrwcGgHodG8bJrzWMZv4+bhKWzAVppBsm02hHAZ28hirECljtO87Lp3a7DkbBYHqe6pXveq5RC+wR2r+rbk2mEGwYGyGQf6iHeZG3gxoWCbgCm9G5qExbltW8gu2uHtCeh4aSbJg7cEps6LvfWmTI+wE7iZxiWbekh2c5n6eaJ4bzgF0XWihrXYaF8WkellG0dmgTFex3HyEhaFYUU-AaQk5htOgYQ81+p3ttwQrSb28mjpOw2acda7sQjvEo5jlz48T-BHqt8tWdtwIObuLnk61-APZb8FoFduHhZTr2xZT5NfYQGW5cDzGlZxlXw9xcyiFLuP8AAJkT5uW-wHXM71g3qeN-OTMLmeS-sMul4rqvntrj6G++7mU7brXwUXruhfv4a+-hteJal4f-emkwMeDkCCgeBpyzk5POPkUdRR+QCshIKIUwowMiqjfSDsB7rzTrtfaFMc47yuvvTMxc57HwXsvVB59rZs3rvbW+LdX6A3BNgZ+EN6Gg3SvfAytZk76H0CoAAVHwpMfCLyYlFIHLAdxOSzXAUAxC+BkKHD-EJd8vB2D-mcMwYYrBsCkBUAgTEEhsiHEygAR2IHQSUGE2h8JUPoHiBBUiCWYMwGoKEcDaUSLGfAo9gBFnsSYc0uBKDOHFAwdAIkx6K3cFRCgmpmTYHzCEZMcUEreMwmlcSrD0qEDQrkwJwTMChMwOEqK+AVCsP3LwYgZT75sMyUWThQgQj+McR+VxijsCHUAugdAzo4w+L8b6Ag6IETGlNOaR8MTyBjLNPRQMwYwyRjDJw7iQyTB2EbMQSSX9vJ4j0l4lIcT-AsA4NwTA-wcwjKeDMiZHEynnlsDSLIoExE9iLCk7AiV0lHOUNqXUAJurzVmdgHKVzBg3OuKvYaGzmBbJyjCrZUKeqjV2eaHKKKTTmiRVk+pTsUqtOce01Cj5ylDRStqCw8TbCOA0W4UlRM6l2FqSoH5TAGD-OuB7RpnFeiEnrspZgDinEuLcZ07pvTsA6BAEIIAA), but I am not seeing the ui menu bar:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/6966254/91006488-586ee200-e58e-11ea-9835-7d4cba4f1d71.png">

**Comment by ifiokjr** [comment]
Oh, yeah I pasted the wrong link with a broken floating menu. Here's the correct **[link](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjyF8jBhVr0cAEXIA3ACqZMzUsLET8AcnmKrq-nsvPQMMHAJqVgRcWBMAMQBhWLJyAGVcVlxyd3FMSRkFKNxdfUNwkwAhF34AUQAPLN5SFExeHM8Cv2UVcgbyJpbeFQAjapLQowIiAEkM5hQEesbm1va86RAFS27e5cGVFDmF8bLjIgBVAXJsed5yJf6VtpFc-M2unB6+gdaVPkCbig7icwmd8AAJcisfhAzgPH7PDzrTrbT67R77AAWUJhvE4IMmJnBOBQAC9WnNKMRmPdvk81m8tko0XSsSTybw5gBabDU8gE8pEAAyKFIuDM5AoBBeHXeqNU6AUUpU8zFArB1HlZkwdhQAOSFAAsqxeKxONcDVQPthLYxMM1cINrgyNkz-CpCtFxghWmL8DUABoOGoAOVS0wA8mH8ABefAAbX0+HwdwA7hCcbD4U8ABQASlgSZT5HTVWYtVZrXzhbaxfTs1Y80Wld41aLafwlwBt1peyrBfbJfwIrFEqlbdrHeJ2DJFMbVJp2cG+f0AF0QvpRHxooN8Ib+sR84Qi8mfU0pvgfWAwCb+KRYkUUHZyLFdUORHGUprmdgc0RWMQuCYOc6D8Jk5CQPguC8tkQh5hutbJgouDENgbQ5ieyb4AAPDCdgAHyYVhOHDIBQG8ERxH4K0CRNgA1jGwBHjG+GXnkN4CKQAB0QGcJwNJlvw+ZCJRxFiuwNKMUQogUgA6uQKCcJiuCQY+z5caM5ZHgA-N4mn8F4+CQf85CiEC5CCEIImIVRhE2VR+AVKJOEjGRrR2Q5ybYaRuDkc5yY0fRjHMaxV4cXePGYHxNINk2wn+fg4mScA0lyQpSkqfgankFxhyNgsOl6dUhnGVcZl3JZ1mefgHnVfg0zOdhrm+e5jU+X59lUYFCwMUxeaxqF7G3txvH8eQXbXD28WdWJuASeQUliGlinKapO7qSZgJ3IVXj6SVJBleZlXObV1XnI1zXkadVHeW5FEzVh3UIL1IVsdew2RdF5CQtCsJ-vgNLPswkHQMIeZVXVSULSlS2cvJK2ZdlXHYr9eL-YD5DA-goNwfgum7cVRkHYE5UWcIEMOddDngtAF3ta1D23S1911dRvC0T1wX9Sxb3hSNUVjT9uKcOj9iY5BABMYMU55UOLTJcPpatWXrTlKPC6LQOS2DeNFeW+0maTx0PVTVHghLdN3abXn0yzdVPS93OsUQYUfUCFB4NOs6cvOfL-aKcSYAgKT8JBb6psjrCkIHwekEeuNWQlcswwruDwxla2Oup6t-UQGNY1LuP43tROG0d5MnQl4LYJbzOm01eHXfBRbWfoKgAFTt0m7f4A4mKim9WB3JybE++7UHYvgFmHDgWUCHP7BQc4zDDKw2CkCoCCYhI2SHPgCgAI7EHQkpcd3Kj6GefqpDezDMDUMJAdgkGJLG+CvcARZXxe5q4JQzjigYOge8vNhruE-BQb8-h8whCQuQFCaF36YVwk+eueFCBcUwb-f+mBAGYGAcJfAKh677l4MQIh10G6oKLM3XgQgELf3wDfRs99H44FktgVg6B0DOjjB-L+voCDogRMaU05psBvxSKIs01wcyBmDGGSMYZaGnkESYOwjZiAvjZgkTEJpzTgJIJA60LAODcEwP8HMwinjSPEfBIhKh8C2BpFkCeA8exFmQqhdCyCoHKG1LqAElEOIyOwIxaxgxbHXBlsmDRzAtGMTiVomJOi9F4mhjRNJ5oZZoOoTNbCzC74PxnhI4holsLagsD+Wwjhl5uDKZ1KhBFkEqD8UwBggTri1VofQ-Q+heiEhJgBZgBBCmsJKRwrhPDsA6BAEIIAA)** and I've updated the original post.

**Comment by marijnh** [comment]
I'll gladly take a look if you can reproduce this in a plain ProseMirror, but as long as you can only reproduce this in a bigger system, I don't really want to take time to do the reduction work on my side.

**Comment by ifiokjr** [comment]
That makes a lot of sense. I was hoping someone had seen something similar before. I'll check if I can replicate and update this issue soon.

**Comment by ifiokjr** [comment]
I'll close this until I have more time to investigate.

**Comment by ifiokjr** [comment]
Turns out it was my own damn fault. 

You can see the code that resolved it here in case you're seeing similar issues https://github.com/remirror/remirror/pull/641
