### ISSUE TITLE
ReplaceAroundStep in list + decoration mapping leads to crash

### ISSUE THREAD

**Issue by yyjhao** [ProseMirror/prosemirror#1086]
### Issue details

A typical pattern to use decoration is to do something like

```
decorations: state.decorations.map(tr.mapping, newState.doc)
```

to move the decoration in response to document state update.

However, when this happens after the list command where we lift the paragraph out of the list, it can lead to invalid decoration set which leads to a crash.

### Steps to reproduce

[Here](https://tidy-oasis-hiss.glitch.me/) is a demo. Open the link, notice that the second line "ab" is wrapped in some decoration to make it look bold (for demo purpose). Now, open the console

1. move your cursor to the start of the list item in the first line (before "a")
2. hit backspace, this should remove the list item and life the paragraph containing "a" out of the list
3. notice that nothing happens, and an error is logged in the console `Uncaught TypeError: Cannot read property 'nodeType' of undefined`

Upon closer inspection, I can see that the mapped decoration set is `[3, 7, {local: [{from: -1, to: 0}]}]`.

If I set a break point and manually shift the decoration set by adding 1 to all the numbers so that there's no negative number, it works as expected.

### ProseMirror version

Repro in the latest version as of the time this is written (1.15.3)

### Affected platforms

This affects all platforms since the code operates on model data.

### Screenshots / Screencast (Optional)

![crash](https://user-images.githubusercontent.com/1331494/91081786-84c14780-e5fc-11ea-9958-8ded6c216faf.gif)

**Comment by yyjhao** [comment]
Interestingly, if the next next line is just a single character (e.g. "b") the crash is not triggered.

**Comment by marijnh** [comment]
Should be fixed by attached patch.
