### ISSUE TITLE
Prosemirror selection is collapsed after drag & drop

### ISSUE THREAD

**Issue by ncpierson** [ProseMirror/prosemirror#1087]
### Issue details

Prosemirror selection is collapsed after drag & drop.

### Steps to reproduce

This is reproducable on prosemirror.net as of today. I recommend watching the attached screen recording (below), but here are the steps:

Insert the following text:

```
Hello
* Item one
* Item two


```

Then, highlight from 'Hello' until after 'Item two' and try to drag the highlighted text into the empty paragraph at the bottom of the editor. Notice that the selection is collapsed to the beginning of the dropped text instead of remaining around it.

### ProseMirror version

It seems this is a regression introduced between `prosemirror-transform` v1.2.5 and v1.2.8.
Possibly related to Issue #1078 

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Safari

### Screenshots / Screencast

https://recordit.co/qPq2dnIBOQ

**Comment by marijnh** [comment]
Patch https://github.com/ProseMirror/prosemirror-view/commit/dc979ab33ef5917ced2ba7eda75e87f3a3e339bd should help with this.

**Comment by jljorgenson18** [comment]
Although the fix works, we are still seeing other similar test failures for custom paste handling. The prosemirror-view fix seems to be working around an underlying bug inside of prosemirror-transform. I think we can try to submit a different bug if we can repro, but it seems like the collapsed selection may occasionally pop up in other contexts besides drag and drop.

**Comment by marijnh** [comment]
> The prosemirror-view fix seems to be working around an underlying bug inside of prosemirror-transform

There's no bug, just the way `replaceRange` and position mapping interact.

**Comment by jljorgenson18** [comment]
Got it. It seems like more of a breaking change than a bug. It also seems like replaceRange has a new tendency to have a negative bias for position mapping, even on the "to" position of a range. I think we can workaround it but it's difficult without knowing why prosemirror-transform is moving our selections around.

**Comment by marijnh** [comment]
> It also seems like replaceRange has a new tendency to have a negative bias for position mapping, even on the "to" position of a range.

That doesn't sound right. Bias is purely passed as an argument to a position mapping call and doesn't depend on the steps. What was happening the drag scenario (and has been happening like that for a long while, I'm pretty sure) is that the replace step generated, since the slice ends in a list but starts with an open paragraph, deletes the paragraph end token. Thus it is not a pure insert, and won't move positions directly in front of the replacement forward. But it's worked like that since the very beginning.
