### ISSUE TITLE
Pressing enter key while using Japanese (and possibly other) IME causes a new line to unexpectedly be inserted on Safari

### ISSUE THREAD

**Issue by yyjhao** [ProseMirror/prosemirror#1088]
### Issue details

Using enter key to select a result of Japanese Input method inserts a new line but it shouldn't. This probably also applies to other IME.

### Steps to reproduce

1. Using Mac and Safari 13.1.2 and switch to Japanese Input method
2. Go to https://prosemirror.net
3. Type out some Japanese characters and press enter to confirm the selection
4. Notice that a new line is inserted in addition to the Japanese input being confirmed.

### ProseMirror version

Latest version on the example website.

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other (Safari)

### Screenshots / Screencast (Optional)

![jap](https://user-images.githubusercontent.com/1331494/91623469-76eb2980-e950-11ea-81be-1cf2292c02d7.gif)

**Comment by marijnh** [comment]
I tried with macOS' Hiragana and Katanaka IME, but could not reproduce this. Neither of those look like the one in the screencast though, so it'd be helpful if you tell us which IME you are using.

**Comment by yyjhao** [comment]
Hmm I can no longer repro as well. Perhaps it was fixed by some other patches?
