### ISSUE TITLE
Android soft keyboard dismissed on backspace  across word boundaries

### ISSUE THREAD

**Issue by pilosof** [ProseMirror/prosemirror#1089]
### Issue details

backspace across word boundaries (in Hebrew) 
I think it's related to autocomplete marking done by android 
it happened in english in previous versions of prosemirror 

### Steps to reproduce

use this test:
אחד שתיים שלוש
then start hitting backspace 

### ProseMirror version

1.15.5 ? (prosemirror site) 

### Affected platforms

Chrome on Android

### Screenshots / Screencast (Optional)

![ezgif-7-0c9a90057869](https://user-images.githubusercontent.com/627208/91995384-6d8f0200-ed40-11ea-8c6e-88fba0234cc0.gif)

**Comment by marijnh** [comment]
Which virtual keyboard app are you using?

**Comment by pilosof** [comment]
yep sorry you are right, doesn't happen on google keyboard, I'll contact the keyboard developer
