### ISSUE TITLE
make wrapIn work with Inline in parseDOM

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#109]
Currently, `state.wrapIn` doesn't have any effect during parsing of the DOM if the node is an Inline node.

**Comment by marijnh** [comment]
There does not seem to be anything about `wrapIn` that makes it not work for inline nodes, and if I change, for example, the `Image` method to use it, images are still parsed correctly.

**Comment by johanneswilm** [comment]
Ah, I see. I guess one has to extent the Inline Node to make it work, like this:

```
class Footnote extends Inline {
  get contains() { return "inline" }
}
