### ISSUE TITLE
Text cursor doesn't move right away inserting linebreak in Safari (with fix)

### ISSUE THREAD

**Issue by dgreensp** [ProseMirror/prosemirror#1092]
### Issue details

When inserting BRs in Safari (Mac, desktop), the browser doesn't immediately move the text cursor to the right place, which looks and feels weird.

### Steps to reproduce

Visit https://prosemirror.net/examples/basic/ and press Shift-Return a few times in a row.

### ProseMirror version

1.15.6

### Workaround

Currently I am calling this function after applying the transaction that inserts a linebreak:

```
function resetBrowserSelection() {
  const s = document.getSelection();
  if (s) {
    const r = s.getRangeAt(0);
    if (r) {
      s.removeAllRanges();
      s.addRange(r);
    }
  }
}
```

**Comment by marijnh** [comment]
Ugh, very strange behavior (the DOM selection is somewhere else, but the visual cursor is still shown in its old place momentarily). But seems to be fixed by attached workaround.
