### ISSUE TITLE
Missing `mark` when pasting `HTML` which contain nested `mark match rule`

### ISSUE THREAD

**Issue by lastnigtic** [ProseMirror/prosemirror#1093]
### Issue details

When pasting HTML's content like `<p style="font-weight: bold;">1<strong>2</strong>3</p>`.
The content before `3` wiill apply the 'bold' mark. But '3' is not being applyed.

### Steps to reproduce

It can be reproduced at [prosemirror.net](https://prosemirror.net)  by pasting the `HTML` content like `<p style="font-weight: bold;">1<strong>2</strong>3</p>`.

### prosemirror-version
```
prosemirror-model: '1.10.0'
```

**Comment by lastnigtic** [comment]
I found that this is because the `applyPending` in the 'HTML parsing process' matches the same `markType`.
The duplicate "MarkType" will be added to the "activeMarks", which will replace the "Mark" with the same type.
And the "Mark" will be deleted after "addElement", which will cause the "Mark" to be lost.

I think it can be solved by keeping the duplicate MarkType stack.
If the maintainer agrees with my suggestion, I am very willing to solve this issue.

**Comment by marijnh** [comment]
I'm not quite sure how your suggested solution works, but if it solves this, feel free to open a pull request.

**Comment by gmickel** [comment]
This fix (i.e. any version of prosemirror-model after 1.11.0) broke nested mark behavior in our application. We make heavy use of nested marks to allow the designation of optional pieces of content.

As it's hard to explain I will try to demonstrate it graphically using a one paragraph node with 2 (nested) marks:

![image](https://user-images.githubusercontent.com/139907/99902545-e27a3400-2cbe-11eb-93ad-87e197bb0a66.png)
This is the result using prosemirror-model 1.11.0. I have adapted our CSS to show the marks more clearly. As mentioned, this is one paragraph with two nested marks. The outer mark ends before "Quisque".

![image](https://user-images.githubusercontent.com/139907/99902627-777d2d00-2cbf-11eb-9967-d9d9891de7c5.png)
This is the result using prosemirror-model 1.11.1. The "outer" mark now incorrectly spans the entire paragraph node.

Both examples are using the exact same content:

![image](https://user-images.githubusercontent.com/139907/99902647-a0052700-2cbf-11eb-8171-caa5839e8293.png)
Example content that shows that the last text node should not have a mark applied to it.

I have rolled back to 1.11.0 of prosemirror-model for now.

**Comment by lastnigtic** [comment]
This is really awkward.I'm sorry.

What is "outer" mark?Is it a block mark?

**Comment by gmickel** [comment]
No problem!

No, they are all "inline" marks which is why the issue is arising I would guess.

The outer and inner marks seen above are both marks of the same mark type. As an example, we allow our users to specify:

- in this paragraph node, "the following sentence is optional" -> outer mark
- in the optional outer mark "the following word is optional" -> inner mark

Hope that explanation helps!

**Comment by lastnigtic** [comment]
Thank you. I'll try to fix the error.

**Comment by lastnigtic** [comment]
Sorry for late reply.

I've added a test like below, but it can pass.Is there anything I am misunderstanding?
![image](https://user-images.githubusercontent.com/17680884/100546963-25c83a00-329f-11eb-9ac4-d99cafad0a10.png)


Do you mean the second paragraph should be `<span class="comment" data-id="1"><p>second</p></span>` instead?

**Comment by gmickel** [comment]
> ```Do you mean the second paragraph should be <span class="comment" data-id="1"><p>second</p></span> instead?```
In my example above there is only one paragraph (the styling of the marks just gives it the appearance of it being two paragraphs).

The issue occurs only with working with marks inside of one paragraph block. I will try to elaborate further:

**Using the resulting HTML as an example:**

This would be the correct resulting HTML structure/output (i am using the class name to hopefully make the example more clear). This is what 1.11.0 outputs (please note my: "this is correct" comment)

```
<p>
    <span class="mark">
        <span class="mark">
           Some text.
        </span> <!-- / close inner mark 1 -->
        Some text that is inside the outer mark but not inside the inner mark.
    </span> <!-- / close outer mark (this is correct)-->
    Some Text that is not in any of the marks (see structure in the previously posted screenshots)
</p>
```

This is the incorrect HTML structure/output that is generated using prosemirror-model 1.11.1 upwards (please note my: "this is wrong" comment):

```
<p>
    <span class="mark">
        <span class="mark">
           Some text.
        </span> <!-- / close inner mark 1 -->
        Some text that is inside the outer mark but not inside the inner mark.
    Some Text that is not in any of the marks (see structure in the previously posted screenshots)
    </span> <!-- / close outer mark (this is wrong) -->
</p>
```

![99902647-a0052700-2cbf-11eb-8171-caa5839e8293](https://user-images.githubusercontent.com/139907/100640784-1ac0e880-3337-11eb-813c-75f6b95d3a29.png)

As you can see in the image I posted earlier. The last node (which is just a text node) does not have any marks applied to it. However, v 1.11.1 of prosemirror-model upwards renders it inside the outer mark.

I hope this clarifies the issue, I think the screenshots that made it appear as if there were multiple paragraphs may have confused things, apologies.

**Comment by gmickel** [comment]
@lastnigtic @marijnh Any update on this?

**Comment by lastnigtic** [comment]
Sorry, I am busy these days. 😣
And thank you for your detailed description, I'll deal with it today.

**Comment by lastnigtic** [comment]
@gmickel Please check to check if the problem has been solved.

**Comment by gmickel** [comment]
@lastnigtic Will do, won't get around to it until late Monday though probably.

Thanks!

**Comment by gmickel** [comment]
@lastnigtic Sorry for the late reply. I was able to test the newest version of prosemirror-model quickly and your fix solved the problem. Thanks very much! I'll report back if I run into any issues with our more complex documents.
