### ISSUE TITLE
undoInputRule doesn’t work with dead keys

### ISSUE THREAD

**Issue by philippkuehn** [ProseMirror/prosemirror#1094]
I’m using an inputRule which converts \`code\` to a code tag. If I call the `undoInputRule` command afterwards, an error is thrown.

```
Uncaught RangeError: Empty text nodes are not allowed
```

This is because `undoable.text` is empty but should be '`'. https://github.com/ProseMirror/prosemirror-inputrules/blob/master/src/inputrules.js#L111

This only happens when using a German keyboard layout. '`' is a dead key here.

Interesting: When calling `undo()` from the `history` plugin, everything works as expected: `<code>` transforms back to \`code\`.

**Comment by marijnh** [comment]
Attached patch should fix this.
