### ISSUE TITLE
Allow asynchronous toDOM()?

### ISSUE THREAD

**Issue by strogonoff** [ProseMirror/prosemirror#1098]
### Issue details

It could be useful to allow node spec’s `toDOM()` to be asynchronous (let it return a Promise).

#### Use case

Let’s say we let authors to link not just to any web page, but to specific entities, such as books (or ISO standards, etc.).

At first approach, it seems like an elegant solution if we could keep links in source document structure as standardized object identifiers (e.g., `urn:isbn:...`), rather than freeform URLs.

At document generation stage, we’d then fetch the metadata about respective entities, and render them as `<a>` links (probably with some configurable extra markup like an icon, etc.).

For that purpose we’d use a third-party library that communicates with some registry in order to fetch entity’s metadata (e.g., title and stage for ISO standards), as well as its canonical URL. However, that involves a network request and would have to be asynchronous.

I don’t know whether this at all aligns with the spirit of ProseMirror, and/or whether there is a more appropriate way of achieving similar functionality that I should look into—would appreciate any pointers.

**Comment by marijnh** [comment]
This would hugely complicate a _lot_ of things, and generally require us to make a big part of the interface that's currently synchronous async. So no, it's not going to happen.

**Comment by strogonoff** [comment]
Yes, that would have required revamping a lot of the library to be asynchronous :)

**Comment by strogonoff** [comment]
(Forgot to mention that I’d be willing to contribute async support, though if it’s not aligned with the library in general then no matter)

**Comment by marijnh** [comment]
No, sorry, this would be too much of a headache and complexity-bomb for me to be interested in it.

**Comment by jljorgenson18** [comment]
@strogonoff Why not just make a nodeView and handle async rendering there? nodeViews are supposed to be how you do more advanced rendering.

**Comment by strogonoff** [comment]
> @strogonoff Why not just make a nodeView and handle async rendering there? nodeViews are supposed to be how you do more advanced rendering.

@jljorgenson18 this is a good point and would work for fetching item metadata/URL at authoring time. However, it could be neat if it was possible at the time when document is serialized to HTML. That way, if things changed (e.g., metadata of some linked entity), it would be possible to just regenerate document and get it updated. With a node view, it seems like it would be required to actually open the editor and possibly go through linked entries to make them update.

**Comment by strogonoff** [comment]
What I might go with instead is allowing my editor’s plugins to define post-processing passes on its nodes to be run at serialization time. Those passes would be async.

Then the editor would provide an async wrapper around ProseMirror’s serialization logic that would call plugin’s post-processing pass, if defined, on its nodes.

**Comment by jljorgenson18** [comment]
I think that sounds reasonable. It wouldn't be too hard to decorate the raw HTML elements.

We had a similar requirement  where we fetch metadata and then update node attributes. We created a system where we track the various node positions in plugin state and then use the view section of the plugin to fetch metadata whenever a new node is added. Then, we cache the attributes on each node and resync them on note load.

**Comment by strogonoff** [comment]
I am trying to keep the editor headless-friendly, which is why plugin views appear not enough and I guess I have to add layers on top of ProseMirror.

(I want to support dynamic data loading not only during editing, but also when HTML is being generated from schema & ProseMirror source without editor participation, which could happen e.g. in server environment during automatic deployment.)
