### ISSUE TITLE
[Firefox]: Entering text at the end of a line with `white-space: pre-line` drops spaces

### ISSUE THREAD

**Issue by ankon** [ProseMirror/prosemirror#1099]
### Issue details

For some reasons we needed to configure out prosemirror editor element with `white-space: pre-line`. This worked just fine in Chrome, but produces really odd issues in Firefox:

1. One cannot enter more than one consecutive space character at the end of a line
2. Entering a space followed by a non-space will remove the space character
3. Entering text in the middle of a line works just fine.

Switching to `white-space: pre-wrap` resolves the issues for us.

### Steps to reproduce

See glitch example here: 
https://glitch.com/edit/#!/sunny-enshrined-lock?

### ProseMirror version

Unclear to specify, whatever the glitch basic setup uses right now reproduces it.

Seen in our app with remirror 1.0.0-next.49, which depends on these:
```
    "prosemirror-commands": "^1.1.4",
    "prosemirror-dropcursor": "^1.3.2",
    "prosemirror-gapcursor": "^1.1.5",
    "prosemirror-history": "^1.1.3",
    "prosemirror-inputrules": "^1.1.3",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-model": "^1.11.2",
    "prosemirror-schema-list": "^1.1.4",
    "prosemirror-state": "^1.3.3",
    "prosemirror-suggest": "^1.0.0-next.49",
    "prosemirror-tables": "^1.1.1",
    "prosemirror-transform": "^1.2.8",
    "prosemirror-view": "^1.16.0"
```

### Affected platforms

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer (_not tested_)
- [ ] Other (_not tested_)

### Screenshots / Screencast (Optional)

[![Video](https://img.youtube.com/vi/21dN9UgiiNQ/0.jpg)](https://youtu.be/21dN9UgiiNQ)

**Comment by marijnh** [comment]
Using different `white-space` styling is not something the library aims to support, sorry.

**Comment by ankon** [comment]
Fair enough --  at least the issue / video / glitch can provide documentation / guidance. It took me a long time to pin this down on the specific CSS attribute. :)

**Comment by reivilibre** [comment]
Thanks for reporting this, this bit me as well — wasn't even aware of the use of `white-space` attribute so would have been totally in the dark about it.
