### ISSUE TITLE
Question: would a client id of 1 for “our” client and client id of 2 for “other” clients work for collaborative editing?

### ISSUE THREAD

**Issue by calebmer** [ProseMirror/prosemirror#1101]
This is a question, mostly looking to validate a design I’m considering. Could I use `prosemirror-collab` with only two client ids? Where 1 represents “our” client and 2 represents everyone else? So locally everyone would think their id is 1. I’m considering this design because the realtime networking layer already has the concept of “our” realtime payloads vs “other” realtime payloads so reusing that concept would simplify the design of the system a bit.

Looking at the code, it would appear that client ids are only really used to determine ”our” vs “other” transactions but wanted to validate that the design makes sense.

**Comment by marijnh** [comment]
Since client ids, in `receiveTransaction` tend to come from the server, I don't see how this could work, since in the server, the distinction between 'our' and 'other' isn't meaningful.

In the future, please use the [forum](https://discuss.prosemirror.net/), not the bug tracker, to ask questions.
