### ISSUE TITLE
Not able to set selection at caret position

### ISSUE THREAD

**Issue by ligne13** [ProseMirror/prosemirror#1102]
Hi,

I have a contenteditable div on which I use the focusin event to replace with a Prosemirror editor instance.
When the focusin event occurs I get the caret position with this helper function: https://stackoverflow.com/questions/4811822/get-a-ranges-start-and-end-offsets-relative-to-its-parent-container/4812022#4812022. The caret position returned by this function is correct.

Then I need to set the text selection to this caret position in the Prosemirror editor, using:
`view.dispatch(view.state.tr.setSelection(TextSelection.near(view.state.doc.resolve(theCaretPosition.start)));`

But the caret position rendered in the editor is incorrect: it is always set a few characters before the actual caret position returned by the helper function.

Thanks in advance for your help !

**Comment by marijnh** [comment]
ProseMirror's [position system](https://prosemirror.net/docs/guide/#doc.indexing) counts not just characters, but also opening and closing nodes, so it's unlikely to align with the number that that stackoverflow answer gives you. You'll have to figure out some other way to associate the DOM selection with a position in the ProseMirror document, for example by manually counting characters in a [`descendants`](https://prosemirror.net/docs/ref/#model.Node.descendants) callback.
