### ISSUE TITLE
Overlapping decorations with nodeName and class are not rendered correctly

### ISSUE THREAD

**Issue by hedgepigdaniel** [ProseMirror/prosemirror#1105]
### Steps to reproduce

See demo: https://glitch.com/edit/#!/mixolydian-early-trail

1. Select some text (not including the black obstacle) - notice that the selected text is highlighted in red
1. try extending the selection to overlap with the black obstacle - notice that the editor enters a weird state where the decorations are not correctly applied to the DOM nodes.

The issue seems to occur when using a combination of:
 - inline decorations using `nodeName`
 - inline decorations using `class` which change and may overlap with or encompass those with `nodeName`

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://photos.app.goo.gl/9oR6DiYmNLp2eq9q7

**Comment by marijnh** [comment]
Thanks for providing a reproduction. Attached patch (released as 1.16.2) should help—let me know if you run into further issues.

**Comment by hedgepigdaniel** [comment]
Yes that does fix it, thanks :)
