### ISSUE TITLE
Cursor position not updated after press ENTER key in an empty code in Firefox

### ISSUE THREAD

**Issue by Violeta-Amza** [ProseMirror/prosemirror#1106]
### Steps to reproduce

1. Load http://prosemirror.net/
2. Insert a block code by typing ```
3. Press ENTER key

#### Expected:  
   Cursor should appear on the new line
#### Actual:   
   A new line is inserted, but cursor position remains the same (the selection is also updated: if you type any text, this will be inserted on the new line)

### Affected platforms

- Firefox

**Comment by marijnh** [comment]
This seems to be the same Firefox bug as #1073. Attached patch tries to extend the workaround for that to also cover this, and seems to work for me. Could you give it a try?

**Comment by Violeta-Amza** [comment]
Thanks for your response.

It's true that the attached patch covers some scenarios, but I still face this problem if press ENTER in a code node.
This happens because the condition for brKludge variable is evaluated to false(the previous node is not a BR node (it is a text with a new line))

Please see: https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L574 and https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L230

I was thinking if there a way to extend current condition to pass those situations as well.

Thanks

**Comment by marijnh** [comment]
>it is a text with a new line

That's exactly what patch https://github.com/ProseMirror/prosemirror-view/commit/4d067de8fcbfcbb1e8a7605e0c91bdab5ec5ae01 adds handling for. Did you test with the patch?

**Comment by Violeta-Amza** [comment]
Thank you for your response.

You are right, I do not test with the attached patch. (I checked with the attached patch from the related issue).

Now, I tested with the attached patch, it seems to be okay.

**Comment by marijnh** [comment]
Great. I've released prosemirror-view 1.16.3 with that change.
