### ISSUE TITLE
No way to put cursor into empty list item if "paragraph* block*" are allowed as list_item content

### ISSUE THREAD

**Issue by andrey-skl** [ProseMirror/prosemirror#1107]
### Issue details

In my application I have a little bit extended the content allowed in list_item node:
`"paragraph block*" => "paragraph* block*"`

Unfortunately this causes a bug that there is no way to put cursor inside such list item if it is empty:

### Steps to reproduce

1. Take a [basic ProseMirror example](https://prosemirror.net/examples/basic/)
2. Change list_item allowed content:
```js
const mySchema = new Schema({
  // nodes: addListNodes(schema.spec.nodes, "paragraph block*", "block"),
  // replace with: 
  nodes: addListNodes(schema.spec.nodes, "paragraph* block*", "block"),
  marks: schema.spec.marks
})
```
3. Change prosemirror predefined text to:
```html
  <ol>
    <li></li>
    <li></li>
  </ol>

  <p>click in the list</p>

  <ul>
    <li></li>
    <li></li>
  </ul>

  <p>test</p>
```
4. Run example and try to put cursor into list item either by mouse or keyboard

See reproduced case here: https://glitch.com/edit/#!/chestnut-cherry-band

### ProseMirror version

The latest, prosemirror-view@1.15.7, prosemirror-state@1.3.3

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer (Unknown)

### Screenshots / Screencast (Optional)

![2020-11-23 12 35 02](https://user-images.githubusercontent.com/4318513/99947033-69dfaa00-2d88-11eb-8a0f-1efbd5842d00.gif)

**Comment by marijnh** [comment]
You'll want to make sure your block elements are never empty, for example by changing the content expression to `paragraph+ block* | block+`. Empty blocks in editable content aren't handled well by browsers.

**Comment by andrey-skl** [comment]
@marijnh Thanks a lot for such a quick answer, the `block+` seems to be working just OK!
