### ISSUE TITLE
posAtIndex position result, off by one

### ISSUE THREAD

**Issue by ddosanjh** [ProseMirror/prosemirror#1109]
### Issue details

ResolvedPos posAtIndex method returns position one less than expected

It looks like [in this line](https://github.com/ProseMirror/prosemirror-model/blob/master/src/resolvedpos.js#L128) of the implementation, `pos` should have `+ 2` instead of `+ 1`; the value referenced in `this.path` looks like the (inclusive) end position of the parent's ancestor, so one position forward would be the start of the parent, and one past that, the start of child(0); we then add the size of child(0) to arrive at the start position of child(1), and so on ...

Unless of course we intentionally return a position just before the indexed child, in which case that should be documented.

### Steps to reproduce

see repro: [glitch repro](https://glitch.com/~prosemirror-pos-at-index-off-by-one)

```
/**

document     pos
--------     ---
<doc>           0
  <ul>          1
    <li>        2
      <p>       3
        foo     4, 5, 6
      </p>      7
    </li>       8
    <li>        9
      <p>       10
        bar     11, 12, 13
      </p>      14
    </li>       15
  </ul>         16
</doc>          17
**/

console.log(state.doc.nodeSize) // 18

console.log(state.doc.resolve(0).node().type.name) // doc
console.log(state.doc.resolve(1).node().type.name) // bullet_list
console.log(state.doc.resolve(2).node().type.name) // list_item
console.log(state.doc.resolve(3).node().type.name) // paragraph

console.log(state.doc.resolve(2).parent.type.name)  // list_item

console.log(state.doc.resolve(2).posAtIndex(0, -1)) // 1 <-- exect 2 
console.log(state.doc.resolve(2).posAtIndex(1, -1)) // 8 <-- expect 9  

```

### ProseMirror version
prosemirror-model: 1.12.0

### Affected platforms

- [*] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
This output seems to correspond to what I'd expect. `doc.resolve(2)` points at the start of the first list item, so one level above that (the `-1` passed to `posAtIndex`), we are in the bullet list. The position at index 0 in the bullet list is indeed 1 (directly after the `<ul>` token), and the position at index 1 is after the first list item, which is at 8.

**Comment by ddosanjh** [comment]
@marijnh if this is expected as you suggest then I will close the issue.

Thanks for the response and indeed for all your contributions, which I am finding immensely useful for my project. 

Cheers

Dave
