### ISSUE TITLE
Node#nodeAt(position) returns null for empty nodes

### ISSUE THREAD

**Issue by Dev1an** [ProseMirror/prosemirror#1110]
Given the following document:

> <details>
>  <summary>Expand Prosemirror doc (26 lines)</summary>
> 
> ```json
> {
>   "type": "doc",
>   "content": [
>     {
>       "type": "paragraph",
>       "content": [
>         {
>           "type": "text",
>           "text": "One"
>         }
>       ]
>     },
>     {
>       "type": "paragraph"
>     },
>     {
>       "type": "paragraph",
>       "content": [
>         {
>           "type": "text",
>           "text": "Three"
>         }
>       ]
>     }
>   ]
> }
> ```
> </details>

The token sequence with positions looks like this:

```html
0     1   2 3 4 5    6   7    8   9 10 11 12 13 14    15      16
 <doc> <p> O n e </p> <p> </p> <p> T  h  r  e  e  </p>  </doc>
```

The documentation of [prosemirror-model's `Node#nodeAt` method](https://github.com/ProseMirror/prosemirror-model/blob/79f90c99dbdb1fdbdea13558b4f135cdaf6b8542/src/node.js#L187-L195) states:

- **`nodeAt(pos: number)`** → ?`⁠Node`
       Find the node directly after the given position.

So one would expect that `document.nodeAt(6)`, in the above example, should return the empty `<p></p>`. But instead it returns `null`.

### Steps to reproduce

|> `npm install prosemirror-test-builder`

create a file `bug.js`
```js
const {doc, p} = require('prosemirror-test-builder')
const exampleDocument = doc(p("One"), p(), p("Three"))
console.log(exampleDocument.nodeAt(6))
```

|> `node bug.js`

### ProseMirror version

prosemirror-model
"version": "1.12.0"

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] nodejs

**Comment by marijnh** [comment]
The `<doc>` token doesn't exist _in_ the document and doesn't take up space. Position 0 is directly before the first paragraph (and the position before the empty paragraph is 5).

**Comment by Dev1an** [comment]
OK, @marijnh. Thanks for the quick response.
So the token sequence of the before mentioned document should be:
```html
0   1 2 3 4    5   6    7   8 9 10 11 12 13    14
 <p> O n e </p> <p> </p> <p> T h  r  e  e  </p>
```

But the null behaviour still seems strange to me.

And **two questions remain**: 
 - Given position 6 (which can come from a `Selection` in the editor for example), **how can we know which node it points into**? Should we manually parse the document or is there some other kind of API that I'm missing?
 - What do you mean then by _"directly after"_ (in the docs)?
For me the `<p>Three</p>` comes directly after the empty `<p></p>`. And if I call `nodeAt(6)` which is a position that points directly into the empty paragraph, I expect it to return the empty paragraph (or maybe the paragraph directly after it). Because if I call `nodeAt(10)` (which points into the third paragraph) I also get the third paragraph as a result. If that is not what `Node#nodeAt` is meant to do, maybe it would be good to explain this in the documentation: calling `nodeAt` with a position that points into a node with no contents does **not** return that node, but returns null instead.

**Comment by marijnh** [comment]
> how can we know which node it points into? 

`doc.resolve(pos)` returns a [`ResolvedPos`](https://prosemirror.net/docs/ref/#model.ResolvedPos) that will tell you everything you need to know about a position.

> What do you mean by "directly after" (in the docs)?

Occurring immediately after the given position. There is nothing directly after 6, since the parent node at that position ends there.
