### ISSUE TITLE
iOS workarounds not working on iPad

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1111]
### Issue details

The check for ios is not returning true for ipad on newer versions of iPadOS. iOS split iOS and iPadOS in v13 and now it seems like the user agent check is not working for iPadOS. This means that all of the fixes for iOS (like the iOS enter check) are not working for iPad. 

This is the check

```js
  result.ios = !ie && /AppleWebKit/.test(navigator.userAgent) && /Mobile\/\w+/.test(navigator.userAgent)
```

And this is the user agent for new versions of iPad

```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)"
```

I think the fix would be creating a new iPadOS entry for the browser module and keying off of that on each of the various iOS checks or it could be fixed by updating the result.ios check. I'd be happy to work on this if there is a preference on a fix as this causes a lot of issues for iPad

### ProseMirror version

"prosemirror-view": "^1.16.4"

### Affected platforms

iPad

**Comment by marijnh** [comment]
Until we run into issues that differ between iPadOS and iOS, I'm happy to just group them together under the `ios` flag. But that userAgent string seems a bit useless, in that it doesn't appear to contain anything that obviously identifies it as a being an iPadOS browser. Is there anything more helpful in `navigator.platform`?

**Comment by jljorgenson18** [comment]
I'll take a look a bit later. I think it makes sense to group them together as these flags are really only there for cross platform bugs and iOS and iPadOS should have the same exactly bugs 99.9% of the time (at least for the next couple of years is my guess).

**Comment by jljorgenson18** [comment]
This is what I'm seeing for the navigator

```
appCodeName: "Mozilla"
appName: "Netscape"
appVersion: "5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)"
cookieEnabled: true
geolocation: Geolocation {getCurrentPosition: function, watchPosition: function, clearWatch: function}
language: "en-US"
languages: ["en-US"] (1)
maxTouchPoints: 5
mediaCapabilities: MediaCapabilities {decodingInfo: function}
mimeTypes: MimeTypeArray {length: 0, item: function, namedItem: function}
onLine: true
platform: "MacIntel"
plugins: PluginArray {length: 0, item: function, namedItem: function, refresh: function}
product: "Gecko"
productSub: "20030107"
standalone: false
userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko)"
vendor: "Apple Computer, Inc."
vendorSub: ""
webdriver: false
```

It seems like devs are using maxTouchPoints plus the platform to tell the difference

https://stackoverflow.com/questions/56578799/tell-ipados-from-macos-on-the-web

**Comment by jljorgenson18** [comment]
@marijnh Would you like me to submit a PR with a solution that uses maxTouchPoints?

**Comment by marijnh** [comment]
Yes, that seems to be the least dodgy approach, so let's do that.

**Comment by marijnh** [comment]
Solved by https://github.com/ProseMirror/prosemirror-view/pull/83
