### ISSUE TITLE
StoredMark is missing when composing input with the same characters

### ISSUE THREAD

**Issue by lastnigtic** [ProseMirror/prosemirror#1112]
I found that when the input is composed of the same characters, the storedMark will be lost.

It can be reproduced at [https://prosemirror.net/](https://prosemirror.net/).
![missing](https://user-images.githubusercontent.com/17680884/102516492-da4cc300-40c9-11eb-84de-07db5953245c.gif)

I find the this is because the result of the `findDiff` function in `readDOMChange` did not return the "correct" position, which caused the `insertText` method to insert into the wrong position and fail to obtain the "correct" `mark` information.

I fixed this with the code below, but I think this is not the right way to deal with this problem.
![image](https://user-images.githubusercontent.com/17680884/102516800-3c0d2d00-40ca-11eb-8b85-5ab8ab024b66.png)

Please take a look at this issuse.

Thank you for providing such a great project!

**Comment by marijnh** [comment]
I haven't been able to reproduce this with IBUS IME on Linux. I suspect the fact that your cursor appears to stay before the inserted character at the first insertion might be related to this problem—but it doesn't behave like that for me.

Wouldn't it be cleaner to fix this at the point where `findDiff` is called? Maybe by tweaking `preferredPos`/`preferredSide` to handle this specific situation?

**Comment by marijnh** [comment]
Oh, never mind, I can get something like this to happen on Chrome. Investigating.

**Comment by marijnh** [comment]
It was in fact an issue in Chrome, not the IME software. Attached patch works around it. Could you see if it works for you?

**Comment by lastnigtic** [comment]
The patch solve the problem. Thank you very much!
