### ISSUE TITLE
coordsAtPos Returns Wrong Values in v1.17.0

### ISSUE THREAD

**Issue by amxmln** [ProseMirror/prosemirror#1114]
### Issue details

I’m using `EditorView.coordsAtPos` to draw a fake caret in code blocks when the selection changes. Up to v1.17.0 this worked well, however your recent simplifications to the function seem to have broken that functionality. Instead of the actual position of the caret, it now returns a position as if the caret was at the start of the text in the code block (so the top left) **when I’m on an empty line at the end** of the code block.

As far as I can tell, this only happens in code blocks (so `<pre><code></code></pre>`), so my guess is that perhaps since `<code>` is technically an inline element and you seemed to have changed the handling of those in the updated `coordsAtPos` function, that’s what’s causing the regression?

### Steps to reproduce

- Log the result of `EditorView.coordsAtPos(EditorState.selection.from, 1)` after applying the transaction in a `dispatchTransaction`
- Enter some text in a code block and observe how the logged value corresponds to the actual position of the caret in the editor
- Enter a new line (so the caret is at an empty line at the end of the code block) and observe that the logged value no longer matches the actual caret position

### ProseMirror version

v1.17.0

### Affected platforms

- [X] Chrome
- [X] Firefox
- [ ] Internet Explorer
- [ ] Other

Thank you for your continuous hard work!

**Comment by amxmln** [comment]
After some further investigation, I found out that using `coordsAtPos(selection, 0)` does not cause this issue, so it might actually be related to the `side` parameter now being passed to `domAtPos`. So for the time being a workaround is to set `side` to `0` manually, since the default is `1`.

Despite that, I still think this is a bit of a regression that might deserve being addressed, or at least acknowledged in the changelog.

**Comment by marijnh** [comment]
No, that's definitely a regression. Attached patch should fix it.

**Comment by amxmln** [comment]
I’ve just upgraded to the new release and can confirm that the regression was fixed in my usecase.

Thank you for fixing this so quickly!
