### ISSUE TITLE
Bug: cannot put cursor after inline block after upgrading prosemirror-view from 1.16.5 to 1.17.0

### ISSUE THREAD

**Issue by zhaoyao91** [ProseMirror/prosemirror#1115]
### Issue details

After upgrading `prosemirror-view` from 1.16.5 to 1.17.0, I can't put cursor after an inline block.

### Steps to reproduce

This bug can be reproduced on the example page: https://prosemirror.net/examples/dino/

https://user-images.githubusercontent.com/3808838/104269897-4f959300-54d2-11eb-802d-616161aca85e.mp4

An the following is what on my app. The first pic is correct behavior for 1.16.5, and the second pic is incorrect behavior for 1.17.0

https://user-images.githubusercontent.com/3808838/104270045-88ce0300-54d2-11eb-9acb-d7f3b19e6f5b.mp4

https://user-images.githubusercontent.com/3808838/104270050-8b305d00-54d2-11eb-9cef-ec57cae45390.mp4

### ProseMirror version

prosemirror-view: 1.16.5, 1.17.0

### Affected platforms

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Oh, that's pretty bad. Attached patch should fix it—I'll follow up with a release in a moment.

**Comment by Dosant** [comment]
@marijnh, thanks for the patch, 
In our case we noticed that hard break stopped working inside list items. 

https://user-images.githubusercontent.com/7784120/104429297-c049b780-5585-11eb-9683-b0636bd7c7de.mov

https://github.com/ProseMirror/prosemirror-view/commit/206b48171f242016da734eaf2173423ccfb99a29 and 1.17.2 has fixed this. 


Just posting in case someone will be searching for "hard break inside lists are broken"
