### ISSUE TITLE
Node.check does not verify that marks conform to "excludes"

### ISSUE THREAD

**Issue by gkubisa** [ProseMirror/prosemirror#1116]
### Issue details

The [Node.check](https://prosemirror.net/docs/ref/#model.Node.check) function does not verify that marks present on a node conform to the [excludes](https://prosemirror.net/docs/ref/#model.MarkSpec.excludes) property in [MarkSpec](https://prosemirror.net/docs/ref/#model.MarkSpec).

### Steps to reproduce

```javascript
const schema = new Schema({
    nodes: {
        doc: { content: 'text*', marks: 'm' },
        text: {},
    },
    marks: {
        m: { attrs: { a: {} } },
    },
})
const json = {
    type: 'doc',
    content: [
        {
            type: 'text',
            text: 'TEST',
            marks: [
                {
                    type: 'm',
                    attrs: { a: 1 },
                },
                { // A duplicate mark of the same type which is not allowed by the default `MarkSpec.excludes` property.
                    type: 'm',
                    attrs: { a: 2 },
                },
            ],
        },
    ],
}
const doc = schema.nodeFromJSON(json)
doc.check() // It should throw an error but it does not.
```

### ProseMirror version

prosemirror-model: 1.13.1

### Affected platforms

- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Other

**Comment by marijnh** [comment]
That's a good point. Attached patch adds this check.
