### ISSUE TITLE
state.schema and state.doc.type.schema may differ

### ISSUE THREAD

**Issue by gkubisa** [ProseMirror/prosemirror#1117]
### Issue details

`state.schema` and `state.doc.type.schema` may differ which is inconsistent and should not be allowed in my opinion. 

### Steps to reproduce

```javascript
const schema = new Schema(...)
const doc = schema.topNodeType.createAndFill()
const differentSchema = new Schema(...)

const state = EditorState.create({ schema: differentSchema, doc })
state.doc.type.schema !== state.schema
```

OR

```javascript
const schema = new Schema(...)
const doc = schema.topNodeType.createAndFill()
const differentSchema = new Schema(...)

const initialState = EditorState.create({ schema, doc })
const state = initialState.reconfigure({ schema: differentSchema })
state.doc.type.schema !== state.schema
```

### ProseMirror version

prosemirror-model: 1.13.1

### Affected platforms

- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Other

**Comment by marijnh** [comment]
I consider that a user error—checking all argument for consistency would add a lot of extra code and a significant performance cost, so the library, on the whole, expects function arguments to have sensible values.

**Comment by gkubisa** [comment]
Makes sense, thanks. :+1:

**Comment by gkubisa** [comment]
> I consider that a user error—checking all argument for consistency would add a lot of extra code and a significant performance cost, so the library, on the whole, expects function arguments to have sensible values.

Based on the above I understand that a state in which `state.doc.type.schema !== state.schema` is invalid and it's up to the user to ensure consistency. I'm fine with that, however, it also means that `EditorState.reconfigure` should never be used to change schema, as it would inevitably produce an invalid state. Are there any valid use cases for changing schema using `EditorState.reconfigure`? Should `EditorState.reconfigure` be modified to disallow changing schema?

**Comment by marijnh** [comment]
That's a very good point. Attached patch removes the option from `reconfigure`, and tweaks `EditorState.create` to behave more reasonably (preferring the schema from the doc).

**Comment by nathggns** [comment]
How would you suggest you go about updating an EditorState's schema then? I'm trying to dynamically add new node types and can't quite figure out how to go about it.

**Comment by marijnh** [comment]
You'll have to create a new state. Plugins probably won't be able to deal with changing schemas anyway (for example, the undo history wouldn't be able to use old content to undo, because that'd be defined in the old schema).

**Comment by nathggns** [comment]
Do you think it's possible to find a way to add support for new node types (but not remove them) dynamically without breaking undo history?

**Comment by marijnh** [comment]
Not really—creating a new schema means all the `NodeType` objects get recreated, so they wouldn't work with content from the old schema anymore. Having all plugins be able to upgrade/move to a new schema would be a lot of additional complexity that doesn't currently exist and that I feel would be more trouble than it'd be worth.
