### ISSUE TITLE
[prosemirror-view] intermittent error: `Cannot read property 'nodeType' of undefined`

### ISSUE THREAD

**Issue by jonathonherbert** [ProseMirror/prosemirror#1119]
### Issue details

At the moment, in a reasonably complex prosemirror-setup, we're getting a very intermittent error – `Cannot read property 'nodeType' of undefined`. It's thrown as a result of `dom` not being defined [here](https://github.com/ProseMirror/prosemirror-view/blob/a67f66d0077e56f560ec4407c2ea94e09a1f0253/src/viewdesc.js#L466).

We're not sure what's going wrong to produce this result – as far as we can see, all of the plugins that we use deterministically provide this argument, but possibly things are being cleaned up underneath us. Following this, there are two questions –

- is it possible that there's a bug in Prosemirror that could produce this result, or is this very likely the result of consumer code? The only other code that I can see creating widgets within `prosemirror-view` seems related to the cursor.
- if the latter, would it be sensible to add some error handling at this point, providing a more descriptive error to help debugging? Here's [a quick and dirty take](https://github.com/jonathonherbert/prosemirror-view/tree/jsh/throw-on-empty-toDOM). I wasn't quite sure where to write the check – if this is always set within `Decoration.widget` and never touched, perhaps it'd be better placed there.

### Steps to reproduce

It's difficult to provide steps as this is so intermittent – this is more of an RFC for the error behaviour.

### ProseMirror version

```
    "prosemirror-view": "1.17.0"
```

### Affected platforms

- [X] Chrome
- [ ] Firefox (Untested, our users do not use it)

**Comment by marijnh** [comment]
> is it possible that there's a bug in Prosemirror that could produce this result, or is this very likely the result of consumer code?

I'd say the latter—there's a very clear, simple path from the code that defines `dom` to the line to linked, and nothing can set `dom` to null there.

The thing with this kind of error checks is that there's a thousand places where they could make sense in a codebase this size, but adding them all isn't practical. You could try adopting TypeScript, which could help warn about such problems. For now, you should be able to figure out which widget is broken by adding `if (!dom) console.log(widget)` and figuring out where that value is defined.

**Comment by jonathonherbert** [comment]
Gotcha, thanks for confirming – really appreciate the steer.
