### ISSUE TITLE
Cannot input text when multi-paragraph selection is active

### ISSUE THREAD

**Issue by hyperkun** [ProseMirror/prosemirror#112]
How to reproduce:
* Take any ProseMirror document with multiple paragraphs (for example, a document on http://prosemirror.net/).
* Focus into this document.
* Start multi-line selection with Shift+arrow up or Shift+arrow down. Expand this selection further until it spans on multiple paragraphs.
* Try to write text in place of this multi-paragraph selection.

Nothing happens, although deleting multi-paragraph selection with Backspace or Delete works fine.

Tested with last versions of Firefox and Chrome in Linux 3.13.0, Ubuntu distro with Unity DE. Tested on http://prosemirror.net/ and latest commit from this repo. No errors are written into console.

**Comment by marijnh** [comment]
Thanks! Attached patch should help.
