### ISSUE TITLE
Schema is not normalizing/respecting gathered marks that should be allowed for inline nodes

### ISSUE THREAD

**Issue by clauderic** [ProseMirror/prosemirror#1121]
### Issue details
It appears like the schema isn't respecting the gathered marks that are found when parsing the `marks` entry for the Node Spec of an inline node.

### Steps to reproduce

Minimal schema to reproduce:
```js
const schema = {
  nodes: {
    doc: {
      content: 'inline*',
    },

    text: {
      group: 'inline',
    },
    
    token: {
      group: 'inline',
      inline: true,
      atom: true,
      marks: '',
    },
  };
  
  marks: {
    bold: {
      group: 'inline',
      parseDOM: [
          {tag: 'strong'},
      ],
      toDOM() {
        return ['strong', 0];
      },
    },
  },
}
```

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Other

### Screenshots / Screencast (Optional)

![Screen Shot 2021-01-25 at 4 13 05 PM](https://user-images.githubusercontent.com/1416436/105767091-a36b9780-5f28-11eb-9f68-3120e64797b9.png)

As you can see from the screenshot above, the gathered marks is correct, it is an empty array, yet is not being respected and normalized properly by the schema.

**Comment by marijnh** [comment]
[`marks`](https://prosemirror.net/docs/ref/#model.NodeSpec.marks) in a node spec specifies the marks allowed on _children_ of the node, not the node itself.

**Comment by clauderic** [comment]
I see, I missed that nuance. How does one prevent certain or all marks from being applied on the node itself?

**Comment by marijnh** [comment]
That's not possible (unless the same restriction exists for all other nodes that appear in the parent node).

**Comment by clauderic** [comment]
This feels like a big limitation, is there a reason for this limitation or is it something that hasn't been considered to be implemented yet?

**Comment by marijnh** [comment]
It hasn't really been something people need, so far.

**Comment by clauderic** [comment]
It seems like a fairly common use-case, for example if you have an editor that supports mentions or tokens, you typically will not want any marks to be able to be applied on those mentions / tokens.

Are there workarounds you can think of? Custom normalization of the marks that are applied on a node after they are applied perhaps?

**Comment by marijnh** [comment]
One workaround would be an [`appendTransaction`](https://prosemirror.net/docs/ref/#state.PluginSpec.appendTransaction) hook that, if a transaction adds such marks the node, removes them again.
