### ISSUE TITLE
Dropcursor doesn't render correctly within a fixed element with overflow:auto

### ISSUE THREAD

**Issue by oodavid** [ProseMirror/prosemirror#1123]
**What happens?**
My editor is within a `position: fixed` element that can scroll. This allows me to have a sidebar, toolbar etc.

When the editor container is scrolled, the dropcursor doesn't respect the scrolled position.

I can see that the dropcursor position is calculated from the viewport.

**How can others reproduce the issue?**
https://svelte.dev/repl/52e1725010034078b971cfd4f30543e6?version=3.31.2

**Do you have a screenshot?**
![tiptap-dropcursor](https://user-images.githubusercontent.com/46879/106130561-69cda300-6159-11eb-9154-90542af79397.gif)

**What’s your environment?**
 - MacOS
 - Chrome
 - Desktop

_this example uses TipTap, but the issue is related to the underlying prosemirror dropcursor_

**Comment by marijnh** [comment]
Attached patch should help with this.
