### ISSUE TITLE
[prosemirror-view]: Zero-width inline decorations occasionally produce 'Uncaught TypeError: Cannot read property 'nodeType' of undefined'

### ISSUE THREAD

**Issue by jonathonherbert** [ProseMirror/prosemirror#1124]
### Issue details

Adding zero-width inline decorations occasionally produces the error `Uncaught TypeError: Cannot read property 'nodeType' of undefined`. It's the result of `dom` not being defined [here](https://github.com/ProseMirror/prosemirror-view/blob/a67f66d0077e56f560ec4407c2ea94e09a1f0253/src/viewdesc.js#L466).

It feels a little the inline decoration is being mistaken for a widget decoration – I'm suspicious because of a line in [the docs](https://prosemirror.net/docs/ref/#view.Decoration.to) that refers to `from` and `to` remaining the same, but this is just a guess at present.

NB: This is, I think, what was causing https://github.com/ProseMirror/prosemirror/issues/1119. Is it valid to create zero-width inline decorations (from a rendering point of view they're a noop)? This is a reminder for us to filter them out, in any case – if it's not expected perhaps it'd be a good idea to throw early with a sensible error.

### Steps to reproduce

Repro [here](https://glitch.com/edit/#!/boundless-leeward-tortoise?path=index.js%3A28%3A2). You should see the error in the console, and a broken editor. The order seems to matter – a zero-width decoration seems to cause problems if it follows a decoration with a width, but not vice-versa.

One thing to note: when inspecting well-behaved and problematic DecorationSets created with the same decorations in different orders, we can see that they differ – the code

```js
const decosBad = DecorationSet.create(state.doc, [
  Decoration.inline(1, 2)
]).add(state.doc, [
  Decoration.inline(3, 3)
])

const decosGood = DecorationSet.create(state.doc, [
  Decoration.inline(3, 3)    
]).add(state.doc, [
  Decoration.inline(1, 2)
])

console.log(JSON.stringify([decosBad, decosGood]))
```

produces the result

```
[
  {
    "local": [],
    "children": [
      0,
      15,
      {
        "local": [
          { "from": 0, "to": 1, "type": { "spec": {} } },
          { "from": 2, "to": 2, "type": { "spec": {} } }
        ],
        "children": []
      }
    ]
  },
  {
    "local": [],
    "children": [
      0,
      15,
      {
        "local": [{ "from": 0, "to": 1, "type": { "spec": {} } }],
        "children": []
      }
    ]
  }
]
```

### ProseMirror version

```
 "prosemirror-view": "1.17.0"
```

### Affected platforms

- [x] Chrome (88.0.4324.96)
- [x] Firefox (74.0.1)
- [ ] Internet Explorer (untested)
- [ ] Other (untested)

**Comment by marijnh** [comment]
Thanks for the reproduction! Zero-length inline decorations don't really do anything, and in normal circumstances these are filtered out when creating the decoration. But it seems the `add` method wasn't doing that. Patch https://github.com/ProseMirror/prosemirror-view/commit/0427936b4c141ebe59ad9eb403f01d5837275de2 should address that.
