### ISSUE TITLE
Weird behavior on Firefox Mobile 85.1.1

### ISSUE THREAD

**Issue by qurben** [ProseMirror/prosemirror#1125]
### Issue details

On FF85.1.1 mobile the first letter of a block is repeated when typing.

Backspace also doesn't remove a paragraph block.

### Steps to reproduce

This behavior exists on the basic example on the website: https://prosemirror.net/examples/basic/

### ProseMirror version

Latest version, not sure which module causes this bug. 

I guess `prosemirror-view` causes this, which is at version `1.17.2` in my project.

### Affected platforms

Firefox Mobile 85.1.1 on Android 10

- [ ] Chrome
- [x] Firefox (Mobile)
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)
Screencast GIF: https://i.imgur.com/4gdejwn.gifv

**Comment by marijnh** [comment]
The editor was putting the selection _after_ the `<br>` node in an empty `<p><br></p>` textblock, which greatly confused composition and backspace behavior on mobile Firefox. Attached patch seems to resolve both.

**Comment by qurben** [comment]
Thanks!
