### ISSUE TITLE
Browser crash from infinite selection loop

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1126]
### Issue details

I'll see how well I can explain it and if this explanation isn't sufficient, I can try my best to come up with a repro case with the Prosemirror demo app.

Under certain conditions inside of nodeviews, the selection can end up at a spot between two document positions (e.g. between two table cells). The selection being changed (like a CellSelection being set) can sometimes modify the dom. This dom mutation will then fire an additional mutation that is registered which causes the selection to be reparsed. However, the bias when calling selectionFromDOM is now flipped and the tracked Prosemirror selection jumps somewhere else. This is due to this line in selectionFromDOM

`let bias = origin == "pointer" || (view.state.selection.head < $head.pos && !inWidget) ? 1 : -1`

The first time the Prosemirror selection is parsed from the dom selection, `view.state.selection.head < $head.pos` is one value and the next time around, it gets flipped to other value. That bias being flipped every parse causes selectionBetween to return a different selection value each time, causing an infinite selection loop and crashing the browser.

This is ad difficult issue to create a repro case without advanced node views due to how browsers treats native selections, but this has popped up numerous times and we have often worked around it by just throwing view.focus in various spots. A potential fix would be to use the previous bias if the last time selectionFromDOM was called was within a few milliseconds, but I'm not sure.

I'd be happy to research this and create a PR if you have any suggestions but we are a bit stuck at this point without a fix inside of prosemirror-view

### ProseMirror version

prosemirror-view: 1.17.12

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Other

**Comment by jljorgenson18** [comment]
Update: This infinite loop seems to have something to do with focus. If the document isn't focused, then selectionToDOM returns early so the selection is NOT in the right spot when the next mutation is registered. A lack of focus seems to be a necessary condition here.

**Comment by marijnh** [comment]
>  The selection being changed (like a CellSelection being set) can sometimes modify the dom

But it does this with a decoration, right? Which is applied with a stopped DOMObserver, in principle. Are you doing something asynchronous, or is the DOMObserver pausing somehow failing to work?

**Comment by jljorgenson18** [comment]
> But it does this with a decoration, right? Which is applied with a stopped DOMObserver, in principle. Are you doing something asynchronous, or is the DOMObserver pausing somehow failing to work?

I think this really depends and I've seen a number of different mutation types trigger this. For example, just syncing the selection causes a dom mutation to occur because the classList on view.dom changes because selection.visible is toggled.

I should clarify that this really only seems to happen on custom node views with contentDOM elements. Basically any element that is in between the dom and contentDOM in the node view that may be updated can trigger a mutation that is rightfully ignored via ignoreMutation, but the selection is still parsed from dom each time "flush" is called. All it takes is one mutation while the editor is not focused in an ambiguous native selection and the infinite loop starts.

**Comment by jljorgenson18** [comment]
For the sake of the discussion, a simple example (as you mentioned) is a decoration being passed into the node view that shows selection styles if that component has the selection in a certain spot. That decoration could cause a dom mutation and will change each time the selection changes. That dom mutation restarts the parsing process.

**Comment by marijnh** [comment]
I tried to create a situation to reproduce this, so that I can study it in detail, but didn't manage to. I know there's probably a lot of pieces involved, but I really want to have a sound basis for a patch, so it'd help a lot if you could create a minimal example.

**Comment by jljorgenson18** [comment]
Sounds good. I was holding out hope that you would see the issue and know a brilliant solution right away but I figured we would need a repro case. I started trying to create one yesterday but got side tracked. I'll work on one today.

**Comment by jljorgenson18** [comment]
That was a bit of a struggle but I created a repro case https://codesandbox.io/s/flamboyant-williamson-uhxw2?

An important thing to note here is that the selection updating in the "break stuff" handler happens occasionally when you replace a paragraph with a leaf node. The shape of that selection is what it looks like but but just to be more deterministic, I just set the selection myself.

**Comment by marijnh** [comment]
Thanks for isolating that. Attached patch fixes it by always updating `currentSelection` to the selection as it is at the end of `DOMObserver.flush`, to make sure the same selection won't trigger further flush cycles.

**Comment by jljorgenson18** [comment]
Awesome! This one has plagued us for quite awhile but we never could quite pinpoint it. Thank you so much.
