### ISSUE TITLE
Inner dom node of a node spec split on Enter with iOS Safari

### ISSUE THREAD

**Issue by samwillis** [ProseMirror/prosemirror#1127]
### Issue details

iOS seems to have an issue with splitting inner dom nodes when you hit enter with a spec such as:

```
  toDOM: node => {
    const { value, guid } = node.attrs
    return [
      'div',
      {
        'data-type': 'test',
      },
      ['div', { class: 'test-content' }, 0],
      ['div', { class: 'test-other', contenteditable: 'false' }, 'not editable bit'],
    ]
  },
```

When you are in `test-content` and hit enter (if you are at the start or end of it) it will create another `test-content` div rather than a new paragraph below.

(see glitch and videos below)

### Steps to reproduce

https://glitch.com/edit/#!/twisty-melted-plastic?path=index.js%3A18%3A4

### ProseMirror version

Latest version of ProseMirror in my own code, and whichever is default in the glitch example I based the test case on.

### Affected platforms

- [X] iOS Safari
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

In iOS safari (in simulator but is the same on a device) it is splitting the inner node:

https://user-images.githubusercontent.com/31130/106675618-541f0a00-65ad-11eb-8386-5ef000267624.mov

In desktop safari (and chrome) it works as expected:

https://user-images.githubusercontent.com/31130/106675575-3baeef80-65ad-11eb-9adb-2c9899a0f1d0.mov

**Comment by samwillis** [comment]
I have tried to do a little more looking into this and it also seems to happen when using the responsive design mode in desktop Safari which simulates the user agent of iOS. And so it think it must be code path based on the user agent?

It looks like there have been similar issues before, could it be related to the iOS specific code in:
https://github.com/ProseMirror/prosemirror-view/blob/master/src/domchange.js

**Comment by marijnh** [comment]
The glitch page isn't loading for me, but if I try to set up my own script with a node type that has a `toDOM` like that, I don't see the issue occurring. Could you paste your script in some more reliable place?

**Comment by samwillis** [comment]
Hi @marijnh, thanks for taking a look. (also prosemirror is amazing!)

I think it was deleted because I hadn't signed up to glitch when I forked your example. I have now and rebuilt it.

Code here:
https://glitch.com/edit/#!/mulberry-tree-howler?path=index.js%3A1%3A0

View here:
https://mulberry-tree-howler.glitch.me

You can see the node being split on either an iOS device, in the simulator or in safari responsive design mode (you need to refresh the page so the user agent changes to look like iOS)

(I'm fully prepared for this to either be my mistake or something that prosemirror can't support...)

Copying code below incase it is deleted again:
```js
// index.js

const testNodeSpec = {
  
  group: "block",
  
  content: 'text*',

  toDOM: node => [
      'div', { 'data-type': 'testLine' },
      ['div', { class: 'test-content' }, 0],
      ['div', { class: 'test-other', contenteditable: 'false' }, 'not editable bit'],
    ],
  
  parseDOM: [
    {
      tag: 'div[data-type="testLine"]',
      priority: 51,
      contentElement: '.test-content',
    },
  ]
}

const {Schema, DOMParser} = require("prosemirror-model")
const {schema} = require("prosemirror-schema-basic")

const testchema = new Schema({
  nodes: schema.spec.nodes.addBefore("image", "test", testNodeSpec),
  marks: schema.spec.marks
})

let content = document.querySelector("#content")
let startDoc = DOMParser.fromSchema(testchema).parse(content)

const {MenuItem} = require("prosemirror-menu")
const {buildMenuItems} = require("prosemirror-example-setup")

// Ask example-setup to build its basic menu
let menu = buildMenuItems(testchema)

const {EditorState} = require("prosemirror-state")
const {EditorView} = require("prosemirror-view")
const {exampleSetup} = require("prosemirror-example-setup")

window.view = new EditorView(document.querySelector("#editor"), {
  state: EditorState.create({
    doc: startDoc,
    // Pass exampleSetup our schema and the menu we created
    plugins: exampleSetup({schema: testchema, menuContent: menu.fullMenu})
  })
})
```

```html
<!doctype html>
<meta charset=utf8>
<link rel=stylesheet href="https://prosemirror.net/css/editor.css">
<script src="https://prosemirror.net/examples/prosemirror.js"></script>
<script src="require-pm.js"></script>

<script src="index.js" defer></script>
<base href="http://prosemirror.net/">

<style>
  [data-type="testLine"] {
    display: flex;
    flex-direction: row;
    border: 1px solid #f00;
  }
  [data-type="testLine"] .test-content {
    border: 1px solid #0f0;
    width: 50%;
    margin: 3px;
  }
  [data-type="testLine"] .test-other {
    border: 1px solid #00f;
    width: 50%;
    margin: 3px;
  }
</style>

<div id="editor"></div>

<div id="content" style="display: none">
  <p>Test</p>
  <p>Test</p>
  <p>Test</p>
  <div data-type="testLine">
    <div class="test-content">
      This is the content
    </div>
  </div>
  <p>Test</p>
  <p>Test</p>
</div>
```

**Comment by marijnh** [comment]
Ah, now I see what was going on (I had given the node block content in my test). Attached patch should help.
