### ISSUE TITLE
Pressing "Enter" in code blocks doesn't advance cursor in Firefox

### ISSUE THREAD

**Issue by hamvocke** [ProseMirror/prosemirror#1128]
### Issue details

In Firefox (85.0 on macOS here), pressing <kbd>Enter</kbd> in a code block doesn't always advance the cursor to the next line. Only once I press another key (could be <kbd>Enter</kbd> or any character) the cursor moves to the next line. I can see that the first <kbd>Enter</kbd> press does in fact insert a newline - I can use my mouse to put the cursor there.

It might also be notable that this only happens if my cursor is _the end_ of a code block. If I put the cursor somewhere in the middle of my text, the cursor will be moved just fine.

### Steps to reproduce

1. open https://prosemirror.net in Firefox
2. empty the content of the demo editor
3. select _Type_ -> _Code_ from the menu
4. start typing: "Some" <kbd>Enter</kbd> "code" while watching the cursor movement

### ProseMirror version

It looks like this is caused by `prosemirror-view` version `1.17.0`. I've seen this issue pop up in one of our projects once we upgraded `prosemirror-view`  from `1.16.5` to `1.17.0` (the issue still exists with `1.17.3`.

### Affected platforms

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![Kapture 2021-02-03 at 10 24 13](https://user-images.githubusercontent.com/491469/106725759-ff5dac80-6609-11eb-98dc-7c0c5080e6ae.gif)

**Comment by marijnh** [comment]
This definitely used to work. It seems that Firefox has regressed—setting the selection programmatically after a newline seems to now always show the cursor before the newline. I've opened [bug 1690502](https://bugzilla.mozilla.org/show_bug.cgi?id=1690502) and added a kludge in attached patch.

**Comment by marijnh** [comment]
I have reverted the change made in response to this again, since it caused #1373. I cannot reproduce the original issue anymore in current Firefox versions, so I hope the Firefox bug that caused this has been fixed in the browser.

**Comment by marijnh** [comment]
Kludge reinstated in attached patch—though it's hard to reproduce now, #1388 shows the problem still exists.
