### ISSUE TITLE
Crash when creating decorations after prosemirror-view 1.17.3

### ISSUE THREAD

**Issue by pmairoldi** [ProseMirror/prosemirror#1129]
### Issue details

I just tried to update my project to use prosemirror-view 1.17.3 and I got a bunch of test fails and my project now crashes when creating node decorations. 

I've check the changelogs and the change `Fix a bug where adding invalid decorations (for example zero-length inline decorations) with DecorationSet.add would fail to drop those.` causes my crash.

### Steps to reproduce

Here is a project that has the crash with as little code as possible. The error should show in the preview on the side.
https://stackblitz.com/edit/prosemirror-view-17-3-decoration-bug

And here is the same code but with 1.17.2
https://stackblitz.com/edit/prosemirror-view-17-2-decorations-good

### ProseMirror version

`prosemirror-view 1.17.3`

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)
Expected:
<img width="2038" alt="Screen Shot 2021-02-03 at 2 53 33 PM" src="https://user-images.githubusercontent.com/296718/106801402-b4ef2680-662f-11eb-8133-91e0e5d5ad9e.png">

Actual:
<img width="2038" alt="Screen Shot 2021-02-03 at 2 53 45 PM" src="https://user-images.githubusercontent.com/296718/106801421-bcaecb00-662f-11eb-8d95-0f63e74b9e7b.png">

**Comment by marijnh** [comment]
Thanks for the reproduction. Attached patch should take care of this.

**Comment by pmairoldi** [comment]
Awesome thanks!
