### ISSUE TITLE
Parsing a certain HTML structure leads to an invalid document node

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#1130]
### Issue details

I'm parsing HTML content that I have no control over and ran into the following issue.

Using `DOMParser.fromSchema(schema).parse` with the following HTML:
```html
<div>
  <div>
    <strong>
      <strong>Some content in bold</strong>
    </strong>
  </div>
  <span>Text in unstyled span</span>
</div>
```
Returns the following node:
```json
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "marks": [{ "strong" }],
          "text": "Some content in bold"
        }
      ]
    },
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "text": "Text in unstyled span"
        }
      ],
      "marks": [{ "strong" }]
    }
  ]
}
```
As you can see a strong mark is set on the second paragraph, which is unexpected. Additionally, it is set on the block level node (paragraph) and as soon as the content of this paragraph is modified, the strong mark is moved to the text node.

### Steps to reproduce

Live site: https://gravel-available-event.glitch.me
Code: https://glitch.com/edit/#!/gravel-available-event

1. The initially rendered JSON represents the state right after parsing the HTML content.
2. When typing something in the second paragraph the strong mark is moved to the text node (this might not be important/relevant for this issue as the strong mark shouldn't be there in the first place).

### ProseMirror version

prosemirror-model 1.13.1

### Affected platforms

- [X] Chrome 87.0.4280.141
- [X] Firefox 84.0.2

**Comment by marijnh** [comment]
Thanks for the report. Attached patch should resolve this.

**Comment by kiejo** [comment]
Thanks for fixing this so fast, I can confirm that the issue is resolved!
