### ISSUE TITLE
Destroy method of custom NodeView for marks never called

### ISSUE THREAD

**Issue by clauderic** [ProseMirror/prosemirror#1131]
### Issue details

It appears like the `destroy` method of custom `NodeView`s for marks is never called when the mark is removed from the document.

### Steps to reproduce
Delete the custom element marks from the document, the `destroy` method is never called:

https://glitch.com/edit/#!/occipital-grand-blade?path=index.js%3A39%3A0

### ProseMirror version
Latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Other

**Comment by bZichett** [comment]
https://github.com/ProseMirror/prosemirror-view/blob/85d9f1516b45a03bd5a64d90f77689f8e4c49062/src/viewdesc.js#L16

I recalled this being brought up many months ago so I was able to find the comment in NodeView class that explains this is unsupported.  

It came up when I was deciding between decorations and MarkViews for inline comments

**Comment by clauderic** [comment]
The comment doesn't really explain why this limitation exists, would be curious to know if there's a rationale as to why mark NodeViews only implement `dom` and `contentDOM` and do not support any of the other methods of node views (other than API simplicity).

**Comment by bZichett** [comment]
Yep, doesnt describe why.  I'd imagine @marijnh might chime in that he just hasn't prioritized it.  There may be other ways to achieve what you really need with the current library, perhaps by creating decorations at each mark position, and then using it's `onRemove` spec.

**Comment by marijnh** [comment]
Custom mark views don't have their `destroy` method called. That was somewhat implicit in the docs—attached patch clarifies it.

**Comment by clauderic** [comment]
Hey @marijnh, thanks for your response. Would you be able to explain why this limitation exists?1

**Comment by marijnh** [comment]
There is nothing mark views can do except create a single node view, so the need for `destroy` methods on them has never come up. What is your use case?

**Comment by clauderic** [comment]
I'm working on a React NodeView layer that can render React in the ProseMirror document similar to how [remirror](https://remirror.io/) and the [Atlassian ProseMirror editor](https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/packages/editor/) works (see also https://discuss.prosemirror.net/t/a-modified-version-of-atlassians-react-typescript-pm-editor/3441/3), in that you connect the NodeView as a [React Portal](https://reactjs.org/docs/portals.html) target, update it when the node's attributes change, and remove the portal when the NodeView's destroy method is called.

I'm hoping to re-use existing components from our internal [component library](https://polaris.shopify.com/) within the ProseMirror document. This works well for nodes and inline nodes, but not for marks (because of the aforementioned limitation)

I understand that some of these limitations can be can be worked around, for example, by using widget decorations or an editor-wide plugin as mentioned in [this thread](https://discuss.prosemirror.net/t/there-is-a-bug-in-marks-nodeview/2722/4), but this forces consumers to re-invent the wheel if they already have existing component libraries that have built-in features like popovers, tooltips, etc.

**Comment by marijnh** [comment]
The thing is that the library is simply not capable of rendering complicated structure for marks (there's a bunch of conceptual problems with that in general), so using React in that context is probably not going to be useful anyway.

**Comment by BrianHung** [comment]
> I understand that some of these limitations can be can be worked around, for example, by using widget decorations or an editor-wide plugin as mentioned in [this thread](https://discuss.prosemirror.net/t/there-is-a-bug-in-marks-nodeview/2722/4), but this forces consumers to re-invent the wheel if they already have existing component libraries that have built-in features like popovers, tooltips, etc.

I'm curious, what type of component are you trying to integrate with what type of mark @clauderic if you don't mind me asking? I've seen tiptap use tippy.js for their text suggestions [popovers](https://github.com/ueberdosis/tiptap/blob/main/examples/Components/Routes/Suggestions/index.vue) so I'm wondering what different challenges have been encountered.
