### ISSUE TITLE
Cursor issue with decorations

### ISSUE THREAD

**Issue by yyjhao** [ProseMirror/prosemirror#1133]
### Issue details

This used to work but after https://github.com/ProseMirror/prosemirror-view/commit/d1200b75e55dcf0c47ac3d3bdd0c7a339cdccc7f cursors won't show up correctly with decorations.

### Steps to reproduce

1. Go to https://profuse-polydactyl-suede.glitch.me
2. Try to click after the 'widget' text (it's a widget decoration followed by an inline decoration)
3. Notice that the cursor doesn't show up

This is related to https://github.com/ProseMirror/prosemirror/issues/1069 where the previous text is wrapped in an inline decoration with contenteditable=false.

However, if you go into the code and remove the `contenteditable: false` part on the inline decoration, also notice that the cursor now appears before the widget rather than after the widget per the specification of the `side` parameter.

You can test the 'before' behavior by setting a breakpoint in some ViewDesc function (e.g. in domFromPos), then override the function with the old code:

```
this.constructor.prototype.domFromPos = function domFromPos (pos, side) {
    if (!this.contentDOM) { return {node: this.dom, offset: 0} }
    for (var offset = 0, i = 0;; i++) {
        if (offset == pos) {
          while (i < this.children.length && (this.children[i].beforePosition || this.children[i].dom.parentNode != this.contentDOM)) { i++; }
          return {node: this.contentDOM,
                  offset: i == this.children.length ? this.contentDOM.childNodes.length : domIndex(this.children[i].dom)}
        }
        if (i == this.children.length) { throw new Error("Invalid position " + pos) }
        var child = this.children[i], end = offset + child.size;
        if (pos < end) { return child.domFromPos(pos - offset - child.border) }
    
      offset = end;
    }
  };
```

notice that the selection now works correctly.

### ProseMirror version

Latest version

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Attached patch should help with the `side: -1` behavior. But I'm not clear on whether it also solves your other issue. Could you take a look?

**Comment by yyjhao** [comment]
Yep that fixed it! Thanks!
