### ISSUE TITLE
createParagraphNear GapCursor is broken

### ISSUE THREAD

**Issue by carlobeltrame** [ProseMirror/prosemirror#1136]
### Issue details

The most recent [update](https://github.com/ProseMirror/prosemirror-commands/commit/423e6e60fe5c7443197f6f901f216737247eada0) to prosemirror-commands broke support for pressing Enter when GapCursor is active. Typing normal text still works. The reason as far as I can tell is that a `GapCursor` selection is not `instanceof NodeSelection`. It could be fixed by extending the changed `if` statement to something like the following:
```js
// change this:
if (!(sel instanceof NodeSelection) || $from.parent.inlineContent) return false
// to this:
if (!(sel instanceof NodeSelection || sel instanceof GapCursor) || $from.parent.inlineContent) return false
```
But prosemirror-commands so far knows nothing about prosemirror-gapcursor. So maybe you have a better solution to loosen this check.

### Steps to reproduce

1. Go to the [ProsemirrorDemo](https://prosemirror.net/examples/basic/)
2. Insert two horizontal rules back to back
3. Place the cursor in between them, so the GapCursor appears
4. Press Enter

In prosemirror-commands versions previous to 1.1.6, this created an empty paragraph at the GapCursor position, via a transaction with a single `ReplaceStep`. In prosemirror-commands 1.1.6, a transaction without any steps is triggered, and no paragraph is created.

### ProseMirror version

prosemirror-commands 1.1.6

### Affected platforms

All of them as far as I know, but these are the ones I was able to test:

- [x] Chromium 88.0.4324.182
- [x] Firefox 85.0.1
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/7566995/108682454-970b3800-74f0-11eb-9355-202d3538d6fb.mp4

**Comment by marijnh** [comment]
Oh, thanks for noticing that. Version 1.1.7 should fix this.
