### ISSUE TITLE
Unexpected, partially hidden text curser between two adjacent horizontal rules

### ISSUE THREAD

**Issue by styxlab** [ProseMirror/prosemirror#1137]
### Issue details

When you insert two, adjacent horizontal rules and then navigate with ArrowUp/Down, you'll discover an almost hidden text cursor in between the two horizontal rules. This cursor allows to insert text in between two horizontal rules. There should be no text cursor between adjacent horizontal rules, nor should it be possible to enter text in between them.

### Steps to reproduce

Just go to `https://prosemirror.net/`, insert 2 horizontal rules and navigate through the nodes with the arrow keys (see screencast).

### ProseMirror version

PM version on official PM website.

### Affected platforms

- [x] Chrome
- [x] Firefox

### Screenshots / Screencast

![Peek 2021-02-22 23-02](https://user-images.githubusercontent.com/19638263/109324476-04063100-7855-11eb-9d0e-450b5a49dd54.gif)

While it is rather uncommon to insert two horizontal rules, it's still a bug which I hope can be fixed.

**Comment by marijnh** [comment]
It's not a bug, it's intentional behavior. See the [gap cursor](https://prosemirror.net/docs/ref/#gapcursor), and disable that extension if you don't want it.
