### ISSUE TITLE
Broken navigation behaviour in code node after paste text content containing new lines.

### ISSUE THREAD

**Issue by Violeta-Amza** [ProseMirror/prosemirror#1138]
### Issue details

Can not navigate using the arrow keys(up/down) inside code node after paste text content containing new lines.

### Steps to reproduce

1. load https://prosemirror.net/ 
2. create a code node by typing ```
3. paste a similar content as the one shown in the attached picture 
![notepad_content](https://user-images.githubusercontent.com/32900172/110616848-b3b89880-819d-11eb-8797-90a899d34d0c.JPG)
 (copied from notepad)
4. press up arrow key to move the caret on the empty line 

Current Behaviour: the cursor is placed at the beginning of the third line; try to press up arrow key one more time => nothing happens
Expected Behaviour: the cursor should be placed on the second line.

### ProseMirror version

lastest

### Affected platforms

- [ ] Chrome

Notes: tested on Firefox => the behaviour is correct

**Comment by marijnh** [comment]
I can't reproduce this, but I don't have Notepad and am not on Windows. Could you provide the value of `JSON.stringify(view.state.doc.textContent)` when this occurs? It might be related to stray carriage return characters in the content.

**Comment by Violeta-Amza** [comment]
another steps that i can reproduce it 
paste a copied generated text from here https://www.lipsum.com/feed/html 
![test_prosemirror](https://user-images.githubusercontent.com/32900172/110621339-c386ab80-81a2-11eb-802a-0a3857ad4c33.JPG)
![copied_text](https://user-images.githubusercontent.com/32900172/110621367-cbdee680-81a2-11eb-8abb-f647cab026d7.JPG)

**Comment by Violeta-Amza** [comment]
Unfortunately, the patch doesn't work for me. Not sure way, but the change made is not applied to this flow. 

In exchange, I tried to sanitize the copied text (here: https://github.com/ProseMirror/prosemirror-view/blob/master/src/clipboard.js#L44) 
` text = text.replace(/\r\n?/g, "\n");
return new Slice(Fragment.from(view.state.schema.text(text)), 0, 0) }`

and it seems to be okay;

**Comment by marijnh** [comment]
That's odd. It works for me when I intentionally put some code with `\r\n` line breaks on the clipboard and paste into a code block.

**Comment by Violeta-Amza** [comment]
Sorry for the delayed response.

My notes:

Case 1: If the text is pasted in a code node, than "inCode" variable is true. So, only a text node containing the unmodified pasted text is created(https://github.com/ProseMirror/prosemirror-view/blob/master/src/clipboard.js#L44 ).

Case 2: If the text is pasted in any other node than the code node (e.g: paragraph node) 
the pasted text is parsed here: https://github.com/ProseMirror/prosemirror-view/blob/master/src/clipboard.js#L51 
and the "ParseContext.addTextNode" method(https://github.com/ProseMirror/prosemirror-model/blob/master/src/from_dom.js#L411) is used in the parsing process.

**Comment by marijnh** [comment]
> Do you put the input text in clipboard as html/ text, or as both?

Both, I think. But you're right that the plain-code path in `parseFromClipboard` will still let the `\r` characters through. Does changing that (for example by running a replace on the string before giving it to `schema.text`) fix your case?

**Comment by Violeta-Amza** [comment]
Yes, it is okay if the copied text is sanitized before.
`text = text.replace(/\r\n?/g, "\n"); 
return new Slice(Fragment.from(view.state.schema.text(text)), 0, 0);`

**Comment by marijnh** [comment]
Great to hear. Attached patch implements that.
