### ISSUE TITLE
Event attached to a custom node view dom element not detected

### ISSUE THREAD

**Issue by Bartaf83** [ProseMirror/prosemirror#1139]
In this [codesandbox](https://codesandbox.io/s/use-prosemirror-basic-example-forked-5dcdn?file=/src/App.tsx) I have a custom node view which generates a dom element (h1) for which I attached an event listener for several events (i tried keydown, blur , paste, input…) but it never triggers.

I tired stopEvent but it also never triggers for such as events as well How i can control my nodeview ?
[https://i.imgur.com/BjqWXLm.gif](https://i.imgur.com/BjqWXLm.gif)

**Comment by marijnh** [comment]
Such events are delivered to the focused element, not child around the cursor. That's just how the DOM works, and doesn't related to ProseMirror.
