### ISSUE TITLE
Native prosemirror's lists commands attached to custom menu sub-items not working

### ISSUE THREAD

**Issue by Bartaf83** [ProseMirror/prosemirror#1140]
I'm getting native prosemirror's lists commands by calling **prosemirror-schema-list**'s **wrapInList** and i'm also using prosemirror-commands's (wrapIn for blockquote, setBlockType for headings and toggleMark for strong and em).
In this [codesandbox](https://codesandbox.io/s/native-commands-not-working-k1jqx) there is a menu where all these commands are attached to menu subitems (the menu is build the same way as in the [prosemirror's menu example](https://prosemirror.net/examples/menu/).
In the begining i got heading and blockquote commands working like a charm but then i don't know why did they stop working (i don't know what did i change in the code so they stop working!)
The lists command also didn't work
What's wrong ?!

**Comment by marijnh** [comment]
You're mixing multiple schemas (`schema` vs `mySchema`) and passing node specs, rather than node type objects, to the list command functions.
