### ISSUE TITLE
Pressing enter at the beginning of a word on Android places the cursor at the end of the word on a new line

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1144]
### Issue details

1. Open Prosemirror on Android
2. Type a word
3. Place cursor at beginning of word
4. Hit enter

Expected Result:
Cursor is at the beginning of the word on the new line

Actual Result:
Cursor is at the end of the word on the new line

I can see that natively and with a plain contenteditable container, Chrome wants to put the cursor at the beginning of the word but somewhere when the mutation is flushed, the selection is put after the word. I'm trying to pinpoint it inside of Prosemirror but I haven't been able to yet. It seems like maybe the new selection isn't flushed at the right time.

### ProseMirror version

prosemirror-view: 1.17.7

### Affected platforms

Chrome Android only

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/5751354/112385826-12156900-8cbe-11eb-93f9-70afaaa345fc.mp4

**Comment by jljorgenson18** [comment]
I just tried installing prosemirror-view 1.14.0 and I was still seeing the behavior there (although that was our app and not the Prosemirror basic setup demo)

**Comment by jljorgenson18** [comment]
Looks like it can happen in other situations as well, not just enter


https://user-images.githubusercontent.com/5751354/112506977-42134980-8d5c-11eb-97a5-59fa140cebd9.mp4

**Comment by jljorgenson18** [comment]
Narrowed it down! The problem seems to be in this block in domchange.js

```js
  if (parse.sel) {
    let sel = resolveSelection(view, tr.doc, parse.sel)
    // Chrome Android will sometimes, during composition, report the
    // selection in the wrong place. If it looks like that is
    // happening, don't update the selection.
    // Edge just doesn't move the cursor forward when you start typing
    // in an empty block or between br nodes.
    if (sel && !(browser.chrome && browser.android && view.composing && sel.empty &&
                   (sel.head == chFrom || sel.head == tr.mapping.map(chTo) - 1) ||
                 browser.ie && sel.empty && sel.head == chFrom))
      tr.setSelection(sel)
  }
  ```

If that Android condition is not there, everything seems to work ok and both issues are fixed. I don't quite understand why that extra condition was needed, but maybe Chrome starting reporting the selection correctly and something else inside of readDOMChange is setting the selection after. I'd be happy to help with a fix if you have any suggestions.

**Comment by marijnh** [comment]
Thanks for narrowing this down. I think attached patch should help. It's hideous, but the problem appears to be that Chrome (or more likely the IME program) deletes and then re-inserts the composition for no discernable reason in this situation, and that ended up triggering our hack for another bug, leading to the incorrect cursor position.

**Comment by jljorgenson18** [comment]
Thank you! Yea these Android issues are really tough and often warrant these types of hacks. I'll give this a shot.

**Comment by jljorgenson18** [comment]
I can confirm that this does seem to work! I'll keep a look out for any other tweaks or patch updates.
