### ISSUE TITLE
Children in a list item get deleted after enter

### ISSUE THREAD

**Issue by vladislav-chentsov** [ProseMirror/prosemirror#1146]
### Issue details

Reproduction of https://github.com/ProseMirror/prosemirror/issues/886 with the same steps

**Comment by marijnh** [comment]
This isn't happening when I try it. Could you be a bit more specific?

**Comment by katepol** [comment]
The exact steps are:
put cursor at `two` end, delete `two` and press `Enter` at empty paragraph.
![image](https://user-images.githubusercontent.com/484436/121542056-7bc92780-ca10-11eb-9af1-65e26d0bb9aa.png)
the related model is `doc(bullet_list(list_item(paragraph("one"), bullet_list(list_item(paragraph("two"))), paragraph("three"))))`

**Comment by katepol** [comment]
@marijnh any updates?

**Comment by marijnh** [comment]
Attached  patch seems to help. Let me know if you run into other issues with this.
