### ISSUE TITLE
Trigger event after state updates

### ISSUE THREAD

**Issue by panayotisk** [ProseMirror/prosemirror#1147]
### Issue details

More of a question, actually. I am trying to create a plugin that auto-indents a mix of code blocks and paragraphs.
The auto-indent code needs to be triggered after any content is changed. I put the code in the handleKeyDown prop of the plugin, but this works with a state before the change. 
Is there some other way I can trigger my auto-indent code when the state has been updated (or get the updated state in the handleKeyDown prop)?

### Screenshots / Screencast (Optional)
Expected result:
![image](https://user-images.githubusercontent.com/44521424/113585982-9dcfb380-9635-11eb-9d78-32b265bd1151.png)

**Comment by panayotisk** [comment]
Ok, I just realized that the correct event handler for what I need is to use inside a plugin is the view update:
https://prosemirror.net/docs/ref/#state.PluginSpec.view^returns.update

**Comment by jljorgenson18** [comment]
@panayotisk If you haven't already, you may want to check out the discussion forum for stuff like this https://discuss.prosemirror.net/
