### ISSUE TITLE
Return doesn't work after last Headline 1 on Android Chrome

### ISSUE THREAD

**Issue by nikgraf** [ProseMirror/prosemirror#1148]
### Issue details

On Android Chrome 89 when you add a Headline 1 as last line you and press `Return` no new line will be created.
Works fine on Chrome Desktop

### Steps to reproduce

see Issue details & Screencast

### ProseMirror version

Fails on the demo editor https://prosemirror.net/

### Affected platforms

- [x] Chrome (Android)

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/223045/113684353-6f011e00-96c5-11eb-9931-197cc9abf7e9.mov

**Comment by marijnh** [comment]
The issue was caused by ProseMirror's DOM parser completely dropping the `<div><br></div>` node produced by the browser in this case. Attached patch should help.

**Comment by nikgraf** [comment]
great thx 👍
