### ISSUE TITLE
Enter with Android keyboard suggestion has no effect at end of nested DOM node

### ISSUE THREAD

**Issue by jordoh** [ProseMirror/prosemirror#1150]
### Issue details

This seems to be another case of Android/Gboard predictive text performing an odd composition update, similar to #1059. When the cursor is after the last word in a nested DOM node, and the word is underlined (text suggestions active), enter does not do anything, though there is a brief flicker of the keyboard.

`readDOMChange` does get called (once), but `findDiff` returns `null` and the selection is unchanged.

### Steps to reproduce

https://glitch.com/edit/#!/curious-confusion-brace

Render a node view (or generate via schema `toDOM`) that adds an additional nested DOM node:
```
class ParagraphView {
  constructor(node) {
    this.dom = document.createElement("p");
    this.contentDOM = document.createElement("p");
    this.dom.appendChild(this.contentDOM);
  }
}
```

1. Place cursor at end of the last word in a paragraph (delete any ending punctuation first).
2. Press enter.

Expected result:
Cursor is placed at the beginning of a new node.

Actual result:
Cursor stays where it is; document is unchanged.

### ProseMirror version

Observed in 1.17.7 in our application; latest version (presumably 1.18.2) in glitch link above.

### Affected platforms

Chrome Android (reproduced on Android 11 with Gboard)

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/450345/113783261-55bd9900-96e8-11eb-8fae-c9d39142f077.mp4

**Comment by marijnh** [comment]
Thanks for the report. That was a bad interaction between the fact that the library can't capture Enter key presses on Android (because it fires no useful key events) and the fact that extra DOM structure in such nested nodes was simply discarded. Attached patch extends a similar iOS-related kludge to also work on Android. Could you see if it helps?

**Comment by jordoh** [comment]
Thanks @marijnh - I can confirm that the attached patch fixes the issue. 👍
