### ISSUE TITLE
Paragraphs with display: contents not editable in Chrome, Edge

### ISSUE THREAD

**Issue by idreyn** [ProseMirror/prosemirror#1151]
### Issue details

To make properly text-aligning lists easier, I would like to use the following technique to prevent paragraphs within list elements from getting their own boxes in CSS:

```css
li > p {
     display: contents;
}
```

This enables proper positioning for bullets/counters for center-aligned lists; as long as there is a block element inside of an `li`, it seems impossible to correctly manage their placement. For historical reasons I am confined to a Prosemirror schema which nests `paragraph` inside of `list_item`.

However, this makes editing or even focusing on the list items impossible, as demonstrated in the reproduction linked below. Since this only happens in Chrome and Edge it seems likely that this is a Blink-specific quirk that I might have to live with, although this does not seem to prevent editing nodes in a [raw `contenteditable` element](https://codepen.io/ian-kfg/pen/QWdqavY). I figured I'd report it in case there's something Prosemirror can do to accommodate this case.

### Steps to reproduce

- Visit the [repro on Glitch](https://glitch.com/edit/#!/prosemirror-display-contents)
- Start an unordered list
- Try typing into the first list item and observe that you cannot; focus returns to the previous block instead

### ProseMirror version

`prosemirror-view@1.18.2` (and whatever is loaded from https://prosemirror.net/examples/prosemirror.js on Glitch)

### Affected platforms

(on macOS 10.15.7)

- [x] Chrome 89.0.4389.114
- [x] Edge 89.0.774.68
- [ ] Firefox 87.0
- [ ] Safari 14.0.3

**Comment by marijnh** [comment]
I _am_ seeing the same issue in raw contenteditable for empty paragraphs (and I only see it for empty paragraphs in the glitch demo as well), so yeah, I think this is entirely a Chrome bug, and I'm going to close this issue as out of scope for the library.
