### ISSUE TITLE
Selection causes scroll to top in Android WebView in a certain situation.

### ISSUE THREAD

**Issue by hrsto** [ProseMirror/prosemirror#1153]
### Issue details

When a select is made anywhere in EditorView, the editor scrolls to the top of the document. This happens when additional CSS is used to make the editor window to 100% height.

### Steps to reproduce

1. Apply CSS to make EditorView fill the height of its container: `.ProseMirror { height: 100%; }`
2. Then create a long enough document so that it becomes scrollable.
3. Select anywhere. Selection occurs where it should be, but the editor scrolls to the top.

A workaround is easy enough by making the EditorView container flexbox with `flex-direction: column`. Then use `.ProseMirror { flex-grow: 1; }`. This fills the height of the container and selection works normally.

### ProseMirror version

prosemirror-view:  ^1.17.2

### Affected platforms

- [X] Chrome - WebView - `Mozilla/5.0 (Linux; Android 6.0.1; ASUS_Z00AD Build/MMB29P; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36`. 
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

In Android emulator - Nexus 5X API 29 x86 this problem does **not** occur.

**Comment by marijnh** [comment]
I'm not going to be able to test/debug this, so you'll have to diagnose where the issue comes from yourself if you want to progress on it. A good start would be to check if the same issue occurs with a regular contentEditable element, without ProseMirror involved.

**Comment by hrsto** [comment]
Tested with a plain html page without any ProseMirror, or other libs, and the issue occurred in the same way. The work around is also valid.

So this is unrelated to ProseMirror.

Thanks.
