### ISSUE TITLE
Draggables have the 'copy' cursor in Chrome

### ISSUE THREAD

**Issue by blakedovetail** [ProseMirror/prosemirror#1156]
### Issue details

I think this is a bug with how Chrome handles `dropEffect`. After some investigation, it seems to always end up `copy` when dragging it on a contenteditable text.

I managed to 'fix' this by adding `e.dataTransfer.effectAllowed = 'copyMove'` to the drag start handler but this leaves the cursors unstylable.

### Steps to reproduce

1. Open the dino example in Chrome https://prosemirror.net/examples/dino/
2. Drag the dinosaur images around in the editor
3. Observe the `copy` cursor is visible even without a meta key pressed.

### ProseMirror version

Whatever version the examples use at the time this issue was created.

### Affected platforms

- [x] Chrome (v 89) checked on macOS 10.15 and Windows 10
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

Chrome 89 in macOS 10.15:

https://user-images.githubusercontent.com/80667024/114794339-9e074600-9dcf-11eb-9d75-cca62fe85b4b.mov

**Comment by marijnh** [comment]
> but this leaves the cursors unstylable.

What does that mean? Unstylable in which way?

**Comment by blakedovetail** [comment]
Sorry, I forgot to add some extra context. In the dino example, if you add the style:

```
* {
   cursor: grabbing !important;
}
```
When you click and drag the dinosaur, the cursor will still become the `copy` cursor, instead of being the `grabbing` cursor as expected.

---

When I add `e.dataTransfer.effectAllowed = 'copyMove'`, this same styling issue applies (you do not get the `grabbing` cursor as expected), but it is the `move` cursor instead of `copy`.

**Comment by marijnh** [comment]
So you're saying setting `"copyMove"` doesn't cause any additional problems?

Would it be reasonable to only set `"copy"` or `"move"` depending on the value of `dragging.move`, so that the icon is locked to correspond to the editor's actual behavior?

**Comment by blakedovetail** [comment]
> So you're saying setting "copyMove" doesn't cause any additional problems?

Correct.

> Would it be reasonable to only set "copy" or "move" depending on the value of dragging.move, so that the icon is locked to correspond to the editor's actual behavior?

Probably - from my testing `copyMove` was smart enough to use the right cursor depending on the meta key, but using `dragging.move` should work too.

**Comment by marijnh** [comment]
I went with `copyMove` after all, since dragging out of the editor into some element _will_ copy, even without modifiers. Does attached patch solve this for you? I'm not seeing any difference in cursors on Linux, so I didn't directly test.

**Comment by blakedovetail** [comment]
yeah, that solves it.

I suppose the cursor styling (the real issue I was having) is a separate bug probably for the chromium team. Thanks for investigating this.

**Comment by thatsjonsense** [comment]
Hi @marijnh , I came across this issue while investigating a bug I'm having where drags sometimes copy instead of moving, even when no modifier key is pressed. Your comment above says that will happen when "dragging out of the editor". Could you explain a bit more on why this is the case?

In my case, it's happening when I drop within the editor, but just outside the contentDOM of a node view. See video: https://www.loom.com/share/0a72183afc2348239ee44dc95ff57bc8

Happy to file this as its own issue if that's helpful, but I suspect there may be a simple explanation here that I'm missing

**Comment by marijnh** [comment]
> Could you explain a bit more on why this is the case?

ProseMirror only does moving within its content. If you drag to some other field, it'll just copy.

A separate issue with a way for me to reproduce this would be great.

**Comment by thatsjonsense** [comment]
Thanks Marijn, I created a new issue here: https://github.com/ProseMirror/prosemirror/issues/1208
