### ISSUE TITLE
ContentEditable=false attribute sticks around after quick click

### ISSUE THREAD

**Issue by JakeCoxon** [ProseMirror/prosemirror#1157]
### Issue details

I have a draggable node but when I click it it sometimes gets stuck in an uneditable state. 

Narrowing down I found that there is a timeout to disable contentEditable

```
  if (this.mightDrag.setUneditable)
        setTimeout(() => this.target.setAttribute("contentEditable", "false"), 20) 
```

and in the done() handler it removes it.
```
if (this.mightDrag.setUneditable) this.target.removeAttribute("contentEditable")
```

However if click is less than 20ms then the timeout will happen afterwards, and the removeAttribute won't apply.

This fix seems to be to just clearTimeout in the done handler to prevent the contentEditable=false being applied

### Steps to reproduce

https://halved-berry-odometer.glitch.me

Press anywhere in the padding of the red border, but outside of the text paragraph. If you click less than 20ms then the text will become uneditable

### ProseMirror version

1.18.3

### Affected platforms

- [ ] Chrome
- [X] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
I wasn't able to create clicks short enough to trigger this, but the logic problem is clear enough. Does attached patch work for you?

**Comment by bZichett** [comment]
Hah seems like your mouses debounce is still functioning as designed.  I had a (poorly engineered I suppose) silent mouse once that when clicked, sporadically submitted two mouse events with one physical depression.
