### ISSUE TITLE
Event handlers of mousedown not unhooked if mouseup doesn't reach document

### ISSUE THREAD

**Issue by igandrews** [ProseMirror/prosemirror#1158]
### Issue details

The MouseDown object [hooks the mousemove and mouseup events](https://github.com/ProseMirror/prosemirror-view/blob/dc35f710172c70d9c4a8887640e4fab18fb85ad1/src/input.js#L320) when it is constructed and are not removed until its [done](https://github.com/ProseMirror/prosemirror-view/blob/dc35f710172c70d9c4a8887640e4fab18fb85ad1/src/input.js#L325) method is invoked. That happens when the **up** method is invoked or when **dragstart** is invoked. So if neither of those happens that instance will remain hooked into the events even if another mousedown occurs. In my case I found this because an element was handling the mouseup and calling stopPropogation so the root (document) that prosemirror was listening to never got the up invoked. So if you mouse down lots of times then you end up accumulating lots of listeners for the move and up events.

### Steps to reproduce
Add an event listener for the mouseup event on any element between the document and the editor's host - e.g. the body of the document. In that event handler call stopPropogation on the event. 

I put a basic sample here but I can't demonstrate the crux of the issue because really you need to debug the prosemirror code to observe when the up and done methods of the MouseDown are invoked. So if you click around the editor a bunch of times and then on the link you should get multiple up's invoked on the MouseDown corresponding with each down you had made before.
https://glitch.com/edit/#!/early-gem-nickel?path=index.js%3A18%3A1

While I understand that you can't know the up occurred when the propogation was stopped (unless maybe you also listen to a capture version of the event with some settimeout to ensure its released but that's not ideal) I think that the mousedown handler [should check if the view.mouseDown is still set](https://github.com/ProseMirror/prosemirror-view/blob/dc35f710172c70d9c4a8887640e4fab18fb85ad1/src/input.js#L270) and cancel it or invoke its done. In my situation I wish I could have tell the editor to use a particular element as the root rather than assuming the document because an ancestor element out of my control may be listening. I might try inserting a shadow dom so maybe it uses that as the root instead.

### ProseMirror version

1.16.5 (but didn't see any change in the master branch that would indicate this has been fixed since)

### Affected platforms

I imagine it's all browsers since its not platform specific code but I was testing in Chrome on Windows.

**Comment by marijnh** [comment]
Good point. Attached patch adds two workarounds for this — cleaning up the object when a mousemove event with no buttons pressed happens, and always cleaning it up when a new one is installed.
