### ISSUE TITLE
pasting from vscode loses whitespace on the beginning of some lines

### ISSUE THREAD

**Issue by mmorearty** [ProseMirror/prosemirror#1159]
### Issue details

When copying code from VSCode (Visual Studio Code), and pasting into my ProseMirror editor, it loses whitespace from the beginning of some lines — specifically, those lines that had a colored (syntax-highlighted) keyword after the leading whitespace.

I was able to work around this by modifying `ParseContext.prototype.addTextNode()` in prosemirror-model/index.es.js. That function currently skips any `<span>` that contains only whitespace, even if preserveWhitespace is set to `"full"`.

### Steps to reproduce

This project demonstrates the problem: https://glitch.com/edit/#!/carnation-yummy-xenoposeidon

In that project, I'm calling the parser with `preserveWhitespace: "full"`. The contents in index.html come from what I copied and pasted out of VSCode.

In VSCode, I had this in a TypeScript file (for the purposes of demonstrating this bug):

```ts
function f() {
    const c = [
        1,
        2
    ];
}
```

Here's how it looked with my font and color scheme:

<img width="119" alt="code" src="https://user-images.githubusercontent.com/207671/115750660-41ff6d00-a34d-11eb-9ef3-7afe153b784b.png">

It's important to note that of the indented lines, the lines starting with "const", "1", and "2" have a color for the first token on the line; the line starting with "]" does not. That's relevant to this bug.

As you can see, when you load that project, lines that start with a color word are not indented. The "]" line, which starts with a black word, is indented properly:

<img width="485" alt="demo" src="https://user-images.githubusercontent.com/207671/115751401-03b67d80-a34e-11eb-9f7f-b4f6957498c5.png">

My real-world scenario is of course slightly different from this demo. In the real-world scenario, (a) I'm not parsing the entire document with `preserveWhitespace: "full"`, only the tags that should have that, and (b) I'm doing it via copy/paste. But this demo shows the problem.

If you look at index.html, you can see the HTML that VSCode put on the clipboard when I copied from it:

```html
<div style="color: #24292e;background-color: #ffffff;font-family: 'Hack, Cascadia code, Menlo, Monaco, 'Courier New', monospace', Menlo, Monaco, 'Courier New', monospace;font-weight: normal;font-size: 12px;line-height: 18px;white-space: pre;"><div><span style="color: #d73a49;">function</span><span style="color: #24292e;"> </span><span style="color: #6f42c1;">f</span><span style="color: #24292e;">() {</span></div><div><span style="color: #24292e;">    </span><span style="color: #d73a49;">const</span><span style="color: #24292e;"> </span><span style="color: #005cc5;">c</span><span style="color: #24292e;"> </span><span style="color: #d73a49;">=</span><span style="color: #24292e;"> [</span></div><div><span style="color: #24292e;">        </span><span style="color: #005cc5;">1</span><span style="color: #24292e;">,</span></div><div><span style="color: #24292e;">        </span><span style="color: #005cc5;">2</span></div><div><span style="color: #24292e;">    ];</span></div><div><span style="color: #24292e;">}</span></div><br></div>
```

### ProseMirror version

prosemirror-model@1.14.0

### Affected platforms

All

**Comment by marijnh** [comment]
In what situation are you running into this? It seems that, for regular pasting, even if the leading whitespace is preserved, the result (each line in its own paragraph) is pretty useless.

Pasting into a code block (a block element with `code: true` on its node spec) will use the plain text from the clipboard, and should do the right thing. Pasting code as HTML is rather hard to get right (given that the library doesn't know that it's code that's being pasted). The regular paste handler will not pass the preserveWhitespace flag to the parser, so even if we change the behavior with that flag enabled, that won't make a difference when pasting this kind of HTML.

**Comment by mmorearty** [comment]
Our editor's behavior is as follows (we used ProseMirror as a replacement for a legacy editor, and set up ProseMirror to follow these same constraints, although we continue to make tons of enhancements to our editor):

* Only paragraphs; no divs
* Paragraphs have zero top and bottom margins. If want some space between paragraphs (which pretty much everyone does), you're expected to just press Enter to add a blank line.
* We support monospace text, but we do not (yet) have code blocks. This is a key point — currently, when you paste code from VSCode, IntelliJ, or any other place that has monospace text, we will insert it as monospace inline text. Code blocks would be better, but we don't do that yet.

Here's an example of how things actually look in our editor. In this example, the blank lines are empty `<p>` tags (containing just a `<br>`), and the two lines of code are also just regular paragraphs that happen to contain monospace text (again, I realize this is not the best we could do, but it's where we are for now):

![example](https://user-images.githubusercontent.com/207671/115917756-895c2b00-a42b-11eb-84c2-8eaaa13566e6.png)

We do have a `clipboardParser` schema that's different from the main schema, if that's relevant. If you need a more fleshed-out example, let me know and I can try to create one.

**Comment by marijnh** [comment]
All right, but that is very much not the use that ProseMirror is designed for, and I'd say the difference between what happens here and what you want is a result of that conceptual mismatch.

That being said, I think it would be reasonable to not ignore whitespace-only nodes in preserveWhitespace: full mode, which you could use to build a custom paste handler that covers this situation. Would that work for you?

**Comment by mmorearty** [comment]
Yes, that would be perfect, thanks.

**Comment by marijnh** [comment]
Implemented in attached patch.
