### ISSUE TITLE
Wrong caret position after typing text

### ISSUE THREAD

**Issue by maksimr** [ProseMirror/prosemirror#1160]
### Issue details

When type a character cursor jump back to the start of typed symbol

### Steps to reproduce

- Open sandbox
- Type 'a', 'b'

https://codesandbox.io/s/strange-thunder-d8kbt?file=/src/index.js:278-321

### ProseMirror version

    "prosemirror-state": "1.3.4",
    "prosemirror-view": "1.18.3"

### Affected platforms

- [x] Chrome 89.0.4389.128

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/616193/115792605-3eaec480-a3d3-11eb-8aa9-5b0c411b93f7.mov

**Comment by marijnh** [comment]
You'll want `text*` instead of `text?` in your content expression (though adjacent text nodes will get merged when possible, determining whether content is valid in a given place will be queried as if the nodes haven't been merged yet).

**Comment by maksimr** [comment]
@marijnh nope, I want to wrap every text char in a separate node. As I see semantic of * and ? similar to regular expression so “text*” would consume all text chars in one span but “text?” wrap every char to own node.

**Comment by marijnh** [comment]
That's not how it works, though. A text node can be any sequence of characters. More generally, wrapping each character in a different node does not seem like a useful thing to do with this library. What is the motivation for that?

**Comment by maksimr** [comment]
> More generally, wrapping each character in a different node does not seem like a useful thing to do with this library. What is the motivation for that?

Agree. Currently, I'm just playing with prosemirror to understand philosophy, pros and cons. The example above was an attempt to mimic our current custom solution for homemade query language input in a project. Where we wrap every letter in a separate node by historical reasons. So I was just curious that prosmirror didn't work as I expected. Yup I found in the code why this happens and how it calculates position, but I thought it's a bug but looks like I was wrong and this is an expected behavior. Thnx you for the clarification
