### ISSUE TITLE
[Firefox] Cursor does not represent where the changes happen

### ISSUE THREAD

**Issue by Hanz123** [ProseMirror/prosemirror#1163]
### Issue details

The editor cursor does not represent where the changes happen on Firefox, e.g. cursor appears at one location, when an insertion happens, the insertion happens in a different location.

### Steps to reproduce

- Go to https://prosemirror.net/examples/dino/ using Firefox
- Put 2 dinos next to each other
- Insert a character between the 2 dinos
- Notice that the cursor is on the right side of the character.
- Press backspace

Expected result: the newly inserted character is removed
Actual result: the dino on the right side of the cursor is removed.

### ProseMirror version
- I noticed this issue when upgrading from 1.9.12 to 1.15.4
- And lastest version: 1.18.4

### Affected platforms

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast

https://user-images.githubusercontent.com/10228558/117106528-5b7bcc80-adc3-11eb-8f3d-93cccd276950.mov

**Comment by marijnh** [comment]
This is very much a Firefox bug. Filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1709536

Attached patch seems to work around this, at least in the case you described (not sure in what other situations the bug might occur)
