### ISSUE TITLE
Safari: You can't create a cursor inside a NodeSelection containing a text node

### ISSUE THREAD

**Issue by blakedovetail** [ProseMirror/prosemirror#1167]
### Steps to reproduce

1. Open https://ash-placid-shake.glitch.me in Safari.
2. Click the button to select the blockquote node.
3. Try to click inside the selected blockquote as you would to insert more text. You can't.
4. (Also note that typing text will prepend text to the following text node.)

### Issue details

I think the root cause of this is Safari's `caretRangeFromPoint` returns after the selected node for some reason. Probably needs some kludge.

### ProseMirror version

https://prosemirror.net/examples/prosemirror.js retrieved 12 May 2021

### Affected platforms

- [x] Safari

Chrome and Firefox are unaffected

**Comment by marijnh** [comment]
There was a workaround for this already, but it only handled the case where the selected node was the direct parent of the text. Attached patch extends this to work for any selected ancestor nodes.
