### ISSUE TITLE
Backspacing the last character in a paragraph in a nodeview inserts indestructible BR or empties the entire node

### ISSUE THREAD

**Issue by thatsjonsense** [ProseMirror/prosemirror#1168]
### Issue details

I'm using a NodeView with block content. When I backspace in a paragraph with only one character, one of two things will happen:
(1) The entire parent node gets erased and replaced with a BR tag
(2) Just the paragraph node gets replaced by a BR tag, which can't be deleted or navigated past via the cursor

### Steps to reproduce

Please see https://gamma-editor-prototype-git-jon-nodeviewbug-gamma-app.vercel.app/nodeviewbug2. In the second line, or on any line you add, try backspacing the last character on a line.

Oddly enough, the exact same issue doesn't repro when I put the exact same code in a codesandbox: https://codesandbox.io/s/node-view-bug-simplified-b3m2k?file=/src/App.tsx

The rendered HTML is the same. I can't figure out what the difference could be. Some hypotheses:
- We're using NextJS, could it be adding something that changes behavior?
- Are we on a different ProseMirror version than what Codesandbox is getting? See below
- Some kind of other CSS or JS we're using is impacting the behavior. I've tried removing all of these and the issue still happens locally.

It sounds similar to https://github.com/ProseMirror/prosemirror-view/blob/c6ed7c2af3ff9f1eb9b1b2ef1e288eb92269b92a/src/domchange.js#L23 and https://github.com/ProseMirror/prosemirror/issues/930, but those appear to already be fixed and the issue doesn't seem to be browser specific. Would appreciate any guidance!

### ProseMirror version

The version theory is my leading hypothesis, but it looks like I'm using a recent version of prosemirror-view.

├─ @types/prosemirror-collab@1.1.1
├─ @types/prosemirror-commands@1.0.4
├─ @types/prosemirror-dropcursor@1.0.1
├─ @types/prosemirror-gapcursor@1.0.3
├─ @types/prosemirror-history@1.0.2
├─ @types/prosemirror-inputrules@1.0.4
├─ @types/prosemirror-keymap@1.0.4
├─ @types/prosemirror-markdown@1.5.1
├─ @types/prosemirror-model@1.13.0
├─ @types/prosemirror-schema-list@1.0.3
├─ @types/prosemirror-state@1.2.6
├─ @types/prosemirror-transform@1.1.2
├─ @types/prosemirror-view@1.17.1
├─ prosemirror-collab@1.2.2
├─ prosemirror-commands@1.1.7
├─ prosemirror-dropcursor@1.3.4
├─ prosemirror-gapcursor@1.1.5
├─ prosemirror-history@1.1.3
├─ prosemirror-inputrules@1.1.3
├─ prosemirror-keymap@1.1.4
├─ prosemirror-markdown@1.5.1
├─ prosemirror-model@1.14.0
├─ prosemirror-schema-list@1.1.4
├─ prosemirror-state@1.3.4
├─ prosemirror-tables@1.1.1
├─ prosemirror-transform@1.3.2
├─ prosemirror-utils@0.9.6
├─ prosemirror-view@1.18.2

I'm using Tiptap as a wrapper around ProseMirror and have [cross-posted this issue there](https://github.com/ueberdosis/tiptap/issues/1311), but I suspect the issue is in prosemirror-view based on similar bugs described above.

### Affected platforms

Experiencing the issue on Chrome and Safari, haven't tried others

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://www.loom.com/share/3e8f5d83a006409195bf005306edc3ae

Thanks in advance for your help!

**Comment by marijnh** [comment]
Doesn't ring a bell. You'll have to figure out the answers to those questions about the context in which this occurs yourself, and provide a minimal reproduction, if you want me to look at this.

**Comment by thatsjonsense** [comment]
This was resolved by updating Tiptap to the latest version. Thanks for reading Marijn.
