### ISSUE TITLE
Editor scrolling when replacing document in Safari

### ISSUE THREAD

**Issue by rebolyte** [ProseMirror/prosemirror#1169]
### Issue details

When using Safari, replacing a document that already has content will cause the editor to scroll down to the first node that matches what was in the DOM before.

From my investigation, it turns out the root of this is that Safari does not support [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor) (diff [here](https://github.com/ProseMirror/prosemirror-view/compare/1.9.6..1.9.7)), and the fallback behavior that prosemirror-view follows seems to go like this:

1. I initialize document with a placeholder `<p>` tag (e.g. “Add your page content here”).
2. ProseMirror grabs the scroll position of the top of the container DOM as well as finds an element near the top of the editor ([`storeScrollPos`](https://github.com/ProseMirror/prosemirror-view/blob/1.18.4/src/domcoords.js#L59)).
3. I then fire a `replaceDocument` transaction, and my document content gets placed in the DOM. It appears that ProseMirror tries to reuse as many DOM nodes as possible, because the in-memory reference to the `<p>` tag now points to the first paragraph that appears in the document, but with the updated text content.
4. ProseMirror [resets the scroll](https://github.com/ProseMirror/prosemirror-view/blob/1.18.4/src/domcoords.js#L87) so that DOM node it stored originally should be at the top of the editor, but it’s now lower in the viewport, so we scroll down.

### Steps to reproduce

```js
const placeholder = {
    "type": "doc",
    "content": [
        {
            "type": "paragraph",
            "content": [{ "type": "text", "text": "Add your page content here" }]
        }
    ]
}

const myDoc = {
    "type": "doc",
    "content": [
        {
            "type": "heading",
            "attrs": { "level": 1 },
            "content": [{ "type": "text", "text": "testing" }]
        },
        {
            "type": "paragraph", // <-- editor will always scroll to here
            "content": [{ "type": "text", "text": "lorem ipsum" }]
        }
    ]
}

let tr = view.state.tr
  .replaceWith(0, view.state.doc.nodeSize - 2, Node.fromJSON(mySchema, myDoc))
  .setMeta('addToHistory', false);

view.dispatch(tr);
```

Minimal reproduction here: https://glitch.com/edit/#!/brawny-careful-package
(make your window short, maybe 450px tall)

### ProseMirror version

prosemirror-view 1.18.4

### Affected platforms

- [x] Safari (tested on 14.0.2)

### Screenshots / Screencast (Optional)

![Kapture 2021-05-13 at 13 19 33](https://user-images.githubusercontent.com/6430933/118169219-51bf1e00-b3ee-11eb-9ee8-9c55baeeb1fd.gif)

**Comment by marijnh** [comment]
The main issue is that the view only has access to the new state, not the transactions, and thus doesn't know whether such a change was a full replace or just modified content outside of the identical paragraph. As such, it doesn't really have the information to decide what kind of scroll preservation to do. If you recreate (or reconfigure) your state, it will scroll back to the top. Maybe that's the appropriate thing to do here anyway, since replacing the document will preserve undo history and such?
