### ISSUE TITLE
Babel 6 can't compile

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#117]
As of this commit: https://github.com/ProseMirror/prosemirror/commit/06b243137557470703c3f281c50424092a8e337f#diff-8057c968bf5955d09b880825ea6799faR39 , because of Babel 6's opinion that this is a duplicate declaration.

```
./~/prosemirror/src/menu/tooltipmenu.js
Module build failed: TypeError: /prosemirror/src/menu/tooltipmenu.js: Duplicate declaration "items"
  77 | 
  78 |   items(inline, block) {
> 79 |     let items
     |         ^
  80 |     if (!inline) items = []
```

**Comment by marijnh** [comment]
ProseMirror specifies its babel dependency to be 5.x. This is a Babel bug, and I suggest you [submit it](https://phabricator.babeljs.io) to their bug tracker if you want to have it fixed.

**Comment by forresto** [comment]
Fair enough.

It is already reported here: https://phabricator.babeljs.io/T2684
