### ISSUE TITLE
splitBlock throwing TransformError: Invalid content for node doc

### ISSUE THREAD

**Issue by rflprr** [ProseMirror/prosemirror#1172]
### Issue details

For a particular type of schema (see below), when I split a node which is expected to be a singleton (heading) and the position is at the beginning of such node, a TransformError is thrown with the message "Invalid content for node doc".

```js
{
  nodes: {
    doc: {
      content: "paragraph* heading paragraph+"
    },
    heading: schema.spec.nodes.get("heading"),
    paragraph: schema.spec.nodes.get("paragraph"),
    text: schema.spec.nodes.get("text")
  },
  marks: schema.spec.marks
}
```

### Steps to reproduce

1. Open this glitch project: https://glitch.com/edit/#!/nebula-abrasive-ox
2. In the editor, position the cursor at pos 0 (zero)
3. Press enter

### ProseMirror version

prosemirror-commands@1.1.7
prosemirror-dropcursor@1.3.4
prosemirror-gapcursor@1.1.5
prosemirror-history@1.1.3
prosemirror-inputrules@1.1.3
prosemirror-keymap@1.1.4
prosemirror-model@1.14.1
prosemirror-schema-basic@1.1.2
prosemirror-schema-list@1.1.4
prosemirror-state@1.3.4
prosemirror-transform@1.3.2
prosemirror-view@1.18.7

### Affected platforms

I believe this is not browser dependent, but I tested on:
1. OS: macOS Bit Sur (Version 11.2)
2. Browser: Chrome (Version 90.0.4430.212 (Official Build) (x86_64))

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![transform-error](https://user-images.githubusercontent.com/1487471/119199731-36d55500-ba51-11eb-977b-55cbb7a6c1b6.gif)

**Comment by marijnh** [comment]
Attached patch should address this.

**Comment by rflprr** [comment]
Works perfectly, @marijnh. Thanks for this and for your monumental work with prosemirror so far. Have a great week!
