### ISSUE TITLE
Crash when using drop cursor and appendTransaction that deletes content

### ISSUE THREAD

**Issue by pmairoldi** [ProseMirror/prosemirror#1174]
### Issue details

In the editor that I am building there are some nodes that need to be duplicated when inserted into a specific container and then removed when move outside of it. The problem that I have having is the dropcursor updateOverlay method will cause an exception since the cursorPos is no longer in the document. Below is an example of that behaviour.
![May-24-2021 15-25-38](https://user-images.githubusercontent.com/296718/119398609-cd01b900-bca5-11eb-8476-0c0f9bae3f6a.gif)

### Steps to reproduce

Here is a project that reproduces the issue https://stackblitz.com/edit/prosemirror-dropcursor-crash?file=index.js. The reproduce the bug the green box 1 just have to be moved just below the red box as it says in the document.

### ProseMirror version

`prosemirror-dropcursor 1.3.4`

### Affected platforms
I have only tested Chrome but probably applies to all browsers
- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![May-24-2021 15-34-35](https://user-images.githubusercontent.com/296718/119398471-99bf2a00-bca5-11eb-9621-57027674f43c.gif)

**Comment by marijnh** [comment]
Attached patch should address this (somewhat crudely).

**Comment by pmairoldi** [comment]
Thanks once again for the fast response!
