### ISSUE TITLE
addMark adds two marks

### ISSUE THREAD

**Issue by amk221** [ProseMirror/prosemirror#1175]
### Issue details

`addMark` adds two marks, one inside the node and one outside

### Steps to reproduce

Demo: [https://glitch.com/edit/#!/sunset-concise-yttrium](https://glitch.com/edit/#!/sunset-concise-yttrium?path=index.js%3A1%3A0)

1. Click the `example` node
2. Add a link to it
3. Inspect the generated markup

### ProseMirror version

<details>
<summary>Versions</summary>

```
prosemirror-commands 1.1.7
prosemirror-dropcursor 1.3.3
prosemirror-history 1.0.0
prosemirror-inputrules 1.0.0
prosemirror-keymap 1.0.0
prosemirror-model 1.14.1
prosemirror-schema-basic 1.1.2
prosemirror-schema-list 1.0.0
prosemirror-state 1.0.0
prosemirror-view 1.18.4
```
</details>

### Affected platforms

Only tested in Chrome

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/382061/119806741-64e7e880-beda-11eb-846c-2a2fa90ccd84.mp4

### Notes

* In our real-world app, the `example` Node Type is backed by a Node View to prevent text-inputting. I left that out of the test case because it didn't play a part in the reproduction. Thought it was worth mentioning though.

* Demo app uses adding a link, but the problem occurs for any mark (`strong`, `em`) etc...

**Comment by marijnh** [comment]
`AddMarkStep` will add the mark to any inline content in the range whose parent allows the mark, so this is more or less by design. You could disallow marks inside your `example` node if you're going to treat it like an atomic element anyway—that would prevent this.

**Comment by amk221** [comment]
Apologies!
