### ISSUE TITLE
Initial selection not empty when first node is atomic

### ISSUE THREAD

**Issue by robbertbrak** [ProseMirror/prosemirror#1177]
### Issue details

The initial selection of the editor is not empty when the first node of the content is atomic

### Steps to reproduce

Initialize the demo editor with a `<hr>` element, as in https://glitch.com/edit/#!/somber-successful-sundae (https://somber-successful-sundae.glitch.me). After initializing the view, log whether the initial selection is empty:

```
window.view = new EditorView(document.querySelector("#editor"), {
  state: EditorState.create({
    doc: DOMParser.fromSchema(mySchema).parse(document.querySelector("#content")),
    plugins: exampleSetup({schema: mySchema})
  })
})

console.log("Selection empty?", window.view.state.selection.empty);
```

The result logged to the console is `Selection empty? false`

**Expected result:** The initial selection should be empty.

This causes issues in my project, because we sometimes show a tooltip when an atomic node is selected.
My current workaround (which I'd rather not have to apply) is to explicitly make the selection empty after initialization, i.e.:

```
let selection = TextSelection.create(view.state.doc, 0, 0);
view.updateState(view.state.apply(view.state.tr.setSelection(selection)));
```

### ProseMirror version

Latest

### Affected platforms

- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Other

**Comment by marijnh** [comment]
> Expected result: The initial selection should be empty.

That's not something the library promises, though.

> `let selection = TextSelection.create(view.state.doc, 0, 0);`

Here you're creating an invalid selection (text selections should point into inline content), which is likely to cause other problems.

I think you're just going to have to deal with the fact that the initial selection isn't always empty, somehow.

**Comment by robbertbrak** [comment]
> That's not something the library promises, though.

That may be the case, but it sounds like a _reasonable_ expectation to me: I didn't select the first node when I created the editor, so it is surprising to me that the editor reports that the first note _is_ selected. Is there a particular reason why the editor behaves like this?

**Comment by marijnh** [comment]
As I mentioned, there is no valid cursor selection at the start of the document when the document starts with a block atom. So a node selection is the only valid type of selection there.

**Comment by robbertbrak** [comment]
Continuing the above scenario as follows:

* Place the cursor in the editor and press the "up" arrow key until the gap cursor appears at the beginning of the editor.
* Open the developer console and log the selection:

```
>> window.view.state.selection.toJSON()
Object { type: "gapcursor", pos: 0 }

>> window.view.state.selection.empty
true
```

So it _is_ possible to have an empty selection at the beginning of the document. Even though this is a "gapcursor" selection, it still seems more reasonable than setting the selection to the first node.

**Comment by marijnh** [comment]
Feel free to add custom logic to create a gapcursor in this case. prosemirror-gapcursor isn't part of the core, so prosemirror-state, which manages the creation of the initial selection, doesn't know about it.
