### ISSUE TITLE
[TypeScript] Transform.split typesAfter should allow null?

### ISSUE THREAD

**Issue by ccorcos** [ProseMirror/prosemirror#1178]
### Issue details

Right here:
https://github.com/ProseMirror/prosemirror-schema-list/blob/400e0b395896ebb123db6d119a113a846321afce/src/schema-list.js#L145-L147

We're calling `tr.split` with`types` that has a null in it.

```js
let types = nextType &amp;&amp; [null, {type: nextType}]   
if (!canSplit(tr.doc, $from.pos, 2, types)) return false    
if (dispatch) dispatch(tr.split($from.pos, 2, types).scrollIntoView())
```

TypeScript isn't happy about this though:

```ts
    /**
     * Split the node at the given position, and optionally, if `depth` is
     * greater than one, any number of nodes above that. By default, the
     * parts split off will inherit the node type of the original node.
     * This can be changed by passing an array of types and attributes to
     * use after the split.
     */
    split(
        pos: number,
        depth?: number,
        typesAfter?: Array<{ type: NodeType<S>; attrs?: { [key: string]: any } | null }>,
    ): this;
```

### ProseMirror version

```
    "prosemirror-model": "^1.14.1",
    "@types/prosemirror-model": "^1.13.0",
```

Is this the right place for type issues? I can fix the types, but it looks like there's generated documentation and I also don't know what the documentation should say for the null case.

**Comment by marijnh** [comment]
The [offical docs](https://prosemirror.net/docs/ref/#transform.Transform.split) have a question mark in front of the object type, which indicates null/undefined are allowed. When the typescript declarations don't agree with the docs, you can assume the types are wrong. Submitting PR against https://github.com/DefinitelyTyped/DefinitelyTyped would be the best way to handle this.
