### ISSUE TITLE
RangeError for headings on enter

### ISSUE THREAD

**Issue by philippkuehn** [ProseMirror/prosemirror#1179]
### Steps to reproduce

- go to https://prosemirror.net/
- add a heading at the end of the document
- place the cursor at the start of the heading
- press enter
- see error "Index 1 out of range for ..."

### ProseMirror version

latest

### Affected platforms

- [x] All

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/2500670/120765769-d3035f80-c519-11eb-9373-4ad1ec5fe8df.mp4

**Comment by marijnh** [comment]
Thanks for reporting that. Was a regression since 1.1.8. Attached patch should address it.
