### ISSUE TITLE
A dot is inserted when typing two spaces immediately after a custom inline element

### ISSUE THREAD

**Issue by dfernandez79** [ProseMirror/prosemirror#1180]
### Issue details

A dot (`.`) text is added while inserting two spaces after an inline node.

### Steps to reproduce

It's possible to see this problem by using the Dino example: https://prosemirror.net/examples/dino/ (although I'm having this issue in a component that I'm working on right now).

1. Go to the Dino example: https://prosemirror.net/examples/dino/
2. In the editor insert a dino, then press SPACE twice. (or position the cursor immediately after a dino node and press SPACE twice)
3. A dot is added after the node.

After a bit of debugging it seems that the dot is coming from a DOM mutation.

### ProseMirror version

* `prosemirror-view`: `1.18.7`
* `prosemirror-model`: `1.14.1`
* `prosemirror-state`: `1.3.4`
* `prosemirror-transform`: `1.3.2`
* `prosemirror-commands`: `1.1.9`
* `prosemirror-inputrules`: `1.1.3`

### Affected platforms

- Chrome: 91.0.4472.77

### Screenshots / Screencast

![Kapture 2021-06-09 at 19 40 05](https://user-images.githubusercontent.com/1102266/121438589-a8bb0300-c95a-11eb-8af3-1787bca8f390.gif)

**Comment by jljorgenson18** [comment]
This is actually default OS behavior when ending a sentence. You can try deleting the period after "dinosaurs" and it will also occur there if you hit space twice.

**Comment by marijnh** [comment]
Yes, that's something the browser (or even OS) is implementing, and ProseMirror generally doesn't try to block such behavior (on the assumption that most users are used to it and expect it). You could do so with a custom space handler, though.

**Comment by dfernandez79** [comment]
Many thanks for the response! In the issue report forgot "the detail" that this happens in macOS, and today I learned that the two-space to dot substitution is part of the defaults 🤦🏽 (hehe after an hour of debugging, thinking it was something that I did in my plugin).

Thanks!
