### ISSUE TITLE
Inline decorations at the end of a document cause strange behavior when content is deleted

### ISSUE THREAD

**Issue by b-kelly** [ProseMirror/prosemirror#1183]
### Issue details

When content is deleted from an inline decoration at the end of a document, the editor appends additional, undeletable characters.

This specific behavior only happens in Chrome. Firefox exhibits a different bug (not expanded on in this issue) under the same conditions, which leads me to believe the root cause of this issue may be more widespread.

When deleting text from the end of an inline decoration _at the end of a document_ an extra `br` is appended to the end of the decoration _in addition to_ the one that is normally appended to the end of the document. Then, typing any character causes it to duplicate itself (an extra is appended to the document). Then, typing any _other_ character duplicates the first character, appending it as well.

### Steps to reproduce

Reproduction:

https://glitch.com/edit/#!/prosemirror-inline-decoration-bug-repro

<details><summary>source in case link dies</summary>

index.html

```html
<!doctype html>
<style>
    .highlight {
        color: red;
    }
</style>
<meta charset=utf8>
<link rel=stylesheet href="https://prosemirror.net/css/editor.css">
<script src="https://prosemirror.net/examples/prosemirror.js"></script>
<script src="require-pm.js"></script>

<script src="index.js" defer></script>
<base href="http://prosemirror.net/">

<div id="editor"></div>
```

index.js

```js
const { baseKeymap } = require("prosemirror-commands");
const { keymap } = require("prosemirror-keymap");
const { Schema } = require("prosemirror-model");
const { EditorState, Plugin } = require("prosemirror-state");
const { Decoration, DecorationSet, EditorView } = require("prosemirror-view");

const schema = new Schema({
    nodes: {
        doc: {
            content: "inline*",
            marks: "",
            code: true,
        },
        text: {
            group: "inline",
        },
    },
    marks: {},
});

const getDecorations = function(doc) {
    let decos = [];
    if (doc.content.size) {
        decos = [ Decoration.inline(0, doc.content.size, { class: "highlight" }) ];
    }
    return DecorationSet.create(doc, decos);
}

const plugin = new Plugin({
    state: {
        init(_, instance) {
            return getDecorations(instance.doc);
        },
        apply(tr, data) {
            if (!tr.docChanged) {
                return data;
            }

            return getDecorations(tr.doc)
        }
    },
    props: {
        decorations(state) {
            return this.getState(state);
        }
    }
});

window.view = new EditorView(document.querySelector("#editor"), {
    state: EditorState.create({
        schema: schema,
        plugins: [
            keymap(baseKeymap),
            plugin
        ],
    }),
});
```

</details>

#### Steps

* Enter some text
  * `~~~`
* Hit enter, then enter some more text
  *  `<ENTER>` + `test`
* Delete the text you just entered one character at a time
  * `<BACKSPACE><BACKSPACE><BACKSPACE><BACKSPACE>`
* Enter any additional characters
  * **This is where the bug manifests**
  * `asdf`
* Note that the text displayed in the editor is incorrect
  * `asdfaaaa` instead of `asdf`

### ProseMirror version

In the minimal reproduction above, these are the dependency versions in my local package.json:

```json
  "dependencies": {
    "prosemirror-commands": "^1.1.9",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-model": "^1.14.2",
    "prosemirror-state": "^1.3.4",
    "prosemirror-view": "^1.18.7"
  },
```

### Affected platforms

- [x] Chrome 91
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![prosemirror-bug](https://user-images.githubusercontent.com/14169651/122824561-ae3b1600-d295-11eb-98b8-fbd20ccb1a93.gif)

**Comment by marijnh** [comment]
Chrome moves the `<br>` node into the decorated span in this case, which the library wasn't handling correctly. Attached patch should help. And maybe https://github.com/ProseMirror/prosemirror-view/commit/0922883cacda01ea3e3a359218f15807f0a92756 addresses the Firefox issue you allude to.

**Comment by b-kelly** [comment]
Incredible work! I tested this locally (`npm i github:ProseMirror/prosemirror-view`) on both my contrived example as well as my much more complex production library and _both_ fixes work like a charm. Thank you so much for taking a look into it! Any chance we could get a prosemirror-view package bump to go with it? 🙏

I'll go ahead and close this issue, as it has been resolved (and then some).
