### ISSUE TITLE
Bug with text highlighting

### ISSUE THREAD

**Issue by Dinver** [ProseMirror/prosemirror#1184]
### Issue details
When highlighting a word and opening a menu, the entire paragraph is highlighted.

### Steps to reproduce
Mouse double left click
Mouse right click

### ProseMirror version
last

### Affected platforms
Tested on multiple devices.
Windows 10 x64
- FireFox 89.0.1 (64 bit)
- Google Chrome 91.0.4472.106 (64 bit)

### Screenshots / Screencast (Optional)

Current behavior:
![demo_bug](https://user-images.githubusercontent.com/36528841/123040897-2ec85680-d3fd-11eb-9b9d-74eeb3603f2f.gif)

Expected behavior:
![demo_normal](https://user-images.githubusercontent.com/36528841/123040917-38ea5500-d3fd-11eb-8989-053eb1c295e2.gif)

**Comment by marijnh** [comment]
Attached patch should address this.
