### ISSUE TITLE
Drag and drop drags html content instead of node content on Chrome

### ISSUE THREAD

**Issue by pmairoldi** [ProseMirror/prosemirror#1186]
### Issue details

When you try to drag with your cursor just outside the node's content on Chrome it drags the html content as opposed to the node's serialized content. This leads a a copy of the node being created and sometimes causes a crash because the node's schema is no longer valid.

### Steps to reproduce

Here is a project that reproduces the issue https://stackblitz.com/edit/prosemirror-drag-drop-bug-simple. To reproduce the bug click on the page break node to select it and then place the cursor near the bottom border of the page break node like the following (https://recordit.co/es8M1ayH1E). In the screencast, the first drag and drop results in the actual html representation being dropped while the second drag and drop behaves like expected. 

When looking through the code it seems like this if statement gets executed in this case. Not sure if this causes the problem though. 
<img width="803" alt="Screen Shot 2021-07-06 at 8 46 59 PM" src="https://user-images.githubusercontent.com/296718/124683584-58708b80-de9b-11eb-8a4f-ed64160abe7f.png">

### ProseMirror version

`prosemirror-view 1.18.8`

### Affected platforms

- [X] Chrome (91.0.4472.114)
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by pmairoldi** [comment]
Based on what happens in other browsers I believe the correct behaviour would be that nothing gets dragged.

**Comment by marijnh** [comment]
Yeah, this appears to be some rather dodgy behavior on Chrome's part, where it fires a `dragstart` event but the event's `target` isn't actually the node that's being dragged. Attached patch shuffles a bit of code around to avoid the way that confused ProseMirror.

**Comment by pmairoldi** [comment]
Thanks. Seems to fix the problem.

**Comment by pmairoldi** [comment]
When will this fix be released?

**Comment by marijnh** [comment]
I've tagged 1.18.10
