### ISSUE TITLE
handleClickOn no longer firing for middle mouse clicks

### ISSUE THREAD

**Issue by ashley-austincoder** [ProseMirror/prosemirror#1187]
### Issue details

Regression in prosemirror-view 1.18.8 (not an issue in 1.18.7), handleClickOn is no longer firing for middle mouse clicks, which results in links no longer being opened with a middle click.

It looks like in [this commit](https://github.com/ProseMirror/prosemirror-view/commit/46a4db15cefe7066371e190be9656f32e5dcfcf0#diff-a743a70eedc60de7891c3d15e07a751b56994584e1a568a88fb8e7f862d5a4f4R312) there was a change to this.allowDefault, which makes allowDefault true in the MouseDown class if event.button != 0, such as a middle mouse click. Then, in the MouseDown up() method, handleSingleClick() is skipped if allowDefault is true. 

### Steps to reproduce

1. Create a link
2. Middle click link => opens link in 1.18.7, does nothing in 1.18.8

### ProseMirror version

prosemirror-view 1.18.8

### Affected platforms

Any platform which handles mouse clicks

**Comment by marijnh** [comment]
Thanks for the report. Release 1.18.9 should fix this.
