### ISSUE TITLE
I want to empty the content, or the default content is the container that can be specified.

### ISSUE THREAD

**Issue by HeebeLee** [ProseMirror/prosemirror#1188]
After inputting certain contents in the editor, we can select all of them and press the delete key to delete them. Finally, the contents of the editor change back to this way.

```
<p>
<br>
</p>
```

But what we expect is that when the editor content is empty, it can keep the container we expect, such as this.

```
<h1>
<br>
</h1>
```

We try to use the decoration plug-in method to do it, but we still can't get the expectation. How can we do it?

thank you.

**Comment by marijnh** [comment]
The default content generated for a given position in the document depends on the order of the node specs in the schema definition. If you put your header node in front of your paragraph node, you'll get a header here (but also when pressing enter at the end of a paragraph, so it's probably not really what you want). In any case, this is the bug trackers, and not the place for questions.
