### ISSUE TITLE
Safari - A bug about handling composition when stored marks exist

### ISSUE THREAD

**Issue by KentoMoriwaki** [ProseMirror/prosemirror#1190]
### Issue details

In Safari on Mac and with Japanese IME, typing enter key to finish composition accidentally breaks line when stored marks exists.

The cause is that when composition is completed, MutationObserver fires before keydown and compositionend in Safari.
In the transaction dispatched in MutationObserver, if there is a storedMark, it will clear the composition. [here](https://github.com/ProseMirror/prosemirror-view/blob/3aa9ae0c49ddfca12807ea61621b46bc280a0fb1/src/index.js#L122)
Therefore, in the subsequent keydown, the composition is considered to be already finished and the Enter key is not ignored.

In Chrome, there is no problem because MutationObserver does not fire and compositionend is called after the keydown.

I created a PR to fix this problem https://github.com/ProseMirror/prosemirror-view/pull/97 and I confirmed this fixed the issue, but it's still WIP (need to consider older browsers which does not support CustomEvent) . If you think this solution is correct, I will implement the rest. or please let me know better solution.

Thanks. 

### Steps to reproduce

https://glitch.com/edit/#!/teal-jungle-capri?path=index.html%3A15%3A0

In Safari on Mac and enabling Japanese IME (MacOS standard, not Google IME), 

1. Set stored mark (like by ctrl+b)
2. Type some Japanese word
3. Press enter key to complete composition
4. Reproduced

### ProseMirror version

My projects' package.json
```
    "prosemirror-commands": "^1.1.7",
    "prosemirror-dropcursor": "^1.3.4",
    "prosemirror-gapcursor": "^1.1.5",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-model": "^1.14.1",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-schema-list": "^1.1.4",
    "prosemirror-state": "^1.3.4",
    "prosemirror-transform": "^1.3.2",
    "prosemirror-view": "^1.18.7",
```

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other (Safari)

### Screenshots / Screencast (Optional)

**Safari**

https://user-images.githubusercontent.com/3349436/126857190-d76f0948-7a59-4f4d-926d-de45cfe9aeaf.mov

**Chrome**

https://user-images.githubusercontent.com/3349436/126857193-0e675188-a1a8-4074-8a0e-19b10e26e2cf.mov

**Comment by marijnh** [comment]
Solved in https://github.com/ProseMirror/prosemirror-view/pull/97
