### ISSUE TITLE
deselectNode called direclty after selectNode on editable node in Chrome.

### ISSUE THREAD

**Issue by jmichel84** [ProseMirror/prosemirror#1193]
### Issue details

In Firefox everything behaves correctly. When the text box is clicked, only the selectNode method is called.

Nevertheless, in chrome 92. The deselectNode is called directly after the selectNode.
I believe this was already working in an earlier Chrome version.

### Steps to reproduce

1. Define an editable text box element in the prosemirror schema.

```javascript
  ds_text_box: {
    attrs: {},
    content: "(block)+", 
    defining: true,
    draggable: true,
    toDOM: (node) => {
      return ["ds-text-box", {}, 0]
    }
    ,
    parseDOM: [{
      tag: "ds-text-box",
      getAttrs: (node) => {
        return {}
      }
    }]
  }
```

2. Create a custom node view for the text box

```javascript
export default class {

  constructor(node, view, getPos) {
    this.node = node
    this.view = view
    this.getPos = getPos

    this.dom = document.createElement("ds-text-box")
    this.dom.contentEditable = "true";

    this.content = document.createElement("div")
    this.dom.appendChild(this.content)

    this.contentDOM = this.content;
  }

  selectNode() {
    console.log("selectNode")
    this.dom.classList.add("ProseMirror-selectednode")
  }

  deselectNode() {
    console.log("deselectNode")
    this.dom.classList.remove("ProseMirror-selectednode")
  }

}
```

3. Register the node view in the ProseMirror EditorView

```javascript
 import DsTextBoxView from "./prosemirror-ds-text-box-view";
````
```javascript
nodeViews: {
  ds_text_box: (node, view, getPos) => new DsTextBoxView(node, view, getPos)
}
```

4. Implement the handleClickOn method in the ProseMirror EditorView to select the text box when clicked

```javascript
handleClickOn: (view, pos, node, nodePos, event, direct) => {
  if(!direct) return false;
  // only for ds_text_box nodes
  if(node.type != schema.nodes.ds_text_box) return false
  // create a node selection
  const resolvedPos = view.state.tr.doc.resolve(nodePos);
  var ns = new NodeSelection(resolvedPos)
  // select the node
  this.view.dispatch(this.view.state.tr.setSelection(ns));
},
```

### Dirty Fix

I did not manage to fix the issue for Chrome. A dirty fix to prevent the deselectNode to be called on the nodeView is to trigger an exception on the end of the handleClickOn method.

```javascript
handleClickOn: (view, pos, node, nodePos, event, direct) => {
  if(!direct) return false;
  // only for ds_text_box nodes
  if(node.type != schema.nodes.ds_text_box) return false
  // create a node selection
  const resolvedPos = view.state.tr.doc.resolve(nodePos);
  var ns = new NodeSelection(resolvedPos)
  // select the node
  this.view.dispatch(this.view.state.tr.setSelection(ns));

  throw('Some exception to prevent deselectNode to be called on the text box node view in Chrome')
},
```

### ProseMirror version

    "prosemirror-commands": "^1.1.10",
    "prosemirror-history": "^1.1.3",
    "prosemirror-inputrules": "^1.1.3",
    "prosemirror-keymap": "^1.1.4",
    "prosemirror-model": "^1.14.3",
    "prosemirror-schema-list": "^1.1.5",
    "prosemirror-state": "^1.3.4",
    "prosemirror-tables": "^1.1.1",
    "prosemirror-view": "^1.18.11",

### Affected platforms

- [x] Chrome Version 92.0.4515.107 
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Return `true` from `handleClickOn` to prevent the browser's default behavior from happening right afterwards.
