### ISSUE TITLE
parseFromClipboard's addContext transforms slice in an invalid way.

### ISSUE THREAD

**Issue by pmairoldi** [ProseMirror/prosemirror#1197]
### Issue details
I've run into an issue with tables in my editor where copy/pasting content of a cell to a paragraph causes a table to be pasted. My expectation is that copy/paste should work like the drag and drop behaviour. 

From debugging here is what I found. `addContext` seems to be adding a table and tableRow to slice again.
![Screen Shot 2021-08-13 at 11 13 46 AM](https://user-images.githubusercontent.com/296718/129381328-bb54dae1-3825-47cc-bd3f-9b31bd89247f.png)

Before calling `addContext` my slice is as follows:
```json
{
  "content": [
    {
      "type": "table",
      "content": [
        {
          "type": "tableRow",
          "content": [
            {
              "type": "tableCell",
              "content": [
                {
                  "type": "paragraph",
                  "content": [{ "type": "text", "text": "one" }]
                },
                {
                  "type": "paragraph",
                  "content": [{ "type": "text", "text": "two" }]
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "openStart": 4,
  "openEnd": 4
}
```

and after it is as follows: 
```json
{
  "content": [
    {
      "type": "table",
      "content": [
        {
          "type": "tableRow",
          "content": [
            {
              "type": "table",
              "content": [
                {
                  "type": "tableRow",
                  "content": [
                    {
                      "type": "tableCell",
                      "content": [
                        {
                          "type": "paragraph",
                          "content": [{ "type": "text", "text": "one" }]
                        },
                        {
                          "type": "paragraph",
                          "content": [{ "type": "text", "text": "two" }]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "openStart": 4,
  "openEnd": 4
}
```

### Steps to reproduce

Here is an example project with the issue.
https://stackblitz.com/edit/prosemirror-drag-drop-bug-simple-2pg5bf?file=index.js

To reproduce:
- select "one" and "two" 
- copy
- place cursor in paragraph after table
- paste

And here is gif of how to reproduce it. It shows what happens when you drag and drop vs copy/paste.
https://recordit.co/ZGkvETywke

### ProseMirror version

`prosemirror-view`: 1.18.11

### Affected platforms

- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Other

**Comment by marijnh** [comment]
Attached patch should address this.

**Comment by pmairoldi** [comment]
Thanks for the fix!

The fix works for the case I showed but it caused some of my other tests to fail specifically copy/pasting multiple table cells. 

To reproduce the issue:
- integrate `prosemirror-tables`
- select multiple cells
- paste cells in paragraph 

Expectation:
The whole table is pasted like it was before in 1.18

Actual:
Only part of the table is pasted.

Here is the 1.18 example: 
https://stackblitz.com/edit/prosemirror-drag-drop-bug-simple-1unamh?file=style.css
https://recordit.co/cGHu43vBtd

Here is the 1.19 example: 
https://stackblitz.com/edit/prosemirror-drag-drop-bug-simple-kemrfn?file=style.css
https://recordit.co/IjBOhlDSSL

**Comment by marijnh** [comment]
Ah, indeed, that's not great either. Attached patch should solve that case.

**Comment by pmairoldi** [comment]
Thanks!
