### ISSUE TITLE
Stale left-over decoration when deleting a nested node using prosemirror-commands package

### ISSUE THREAD

**Issue by Zubnix** [ProseMirror/prosemirror#1198]
### Issue details

Stale left-over decoration when deleting a nested node, see repro example.

### Steps to reproduce

https://glitch.com/edit/#!/magic-delirious-vacation

### ProseMirror version

prosemirror-commands 1.0.4

### Affected platforms

- [x] Chrome
- [x] Firefox
- ? Internet Explorer
- ? Other

**Comment by marijnh** [comment]
It looks like you're simply not removing those decorations from your decoration set. Am I misunderstanding something?

**Comment by Zubnix** [comment]
I assumed that to be the initial problem, but I never really figured out how to do that. As that would require me to analyze the transaction(?) and somehow figure out which nodes were removed/moved and then manually delete my corresponding decorations somehow?

I (incorrectly?) assumed that applying the mutation `this.currentDecorations = decorationSet.map(tr.mapping, tr.doc)` would remove them as that seems to be what is happning if I remove any other node.

If I'm supposed to remove them manually how would I do that?

**Comment by Zubnix** [comment]
Another funny thing, is that if I select the glitching node + it's decoration at the same time and then press delete, it does seem to work correctly.

**Comment by Zubnix** [comment]
> Rebuild your decoration set or use its `add` and `remove` methods to update it.

Rebuilding the decorations is a too heavy operation in my case and would make the editor really slow.

I'm already using add for adding decorations as you can see, the issue is how to know the position of a moved and/ore deleted nodes and how to associate it with old decorations. If that's what I'm supposed to do that completely manually, then what is the use-case for `this.currentDecorations = decorationSet.map(tr.mapping, tr.doc)`?

Still begs the question why it does seem to work when deleting other nodes, even when I'm not explicitly deleting the decoration, the decoration they still get somehow gets removed no?

**Comment by marijnh** [comment]
> then what is the use-case for this.currentDecorations = decorationSet.map(tr.mapping, tr.doc)?

That maps the positions of the decorations through the changes, as the docs explain, so that they conceptually stay in the same place in the document even when content is inserted or deleted.

> Still begs the question why it does seem to work when deleting other nodes, even when I'm not explicitly deleting the decoration, the decoration still get somehow gets removed no? Isn't that... odd?

I'm not really sure what you mean by that.

**Comment by Zubnix** [comment]
> > Still begs the question why it does seem to work when deleting other nodes, even when I'm not explicitly deleting the decoration, the decoration still get somehow gets removed no? Isn't that... odd?
> 
> I'm not really sure what you mean by that.

If I delete the node with text `second nested paragraph` it's decoration get's removed (even though I'm not removing any decorations from the decorationset). If I delete the text `first nested paragraphe (select me and press delete twice)` it's decoration remains.

**Comment by marijnh** [comment]
As I said two comments up, if you map a decoration set through a deletion, decorations inside the deleted range won't be in the mapped set.

**Comment by Zubnix** [comment]
> As I said two comments up, if you map a decoration set through a deletion, decorations inside the deleted range won't be in the mapped set.

I'm sorry, I'm not really sure what you mean by that. Are you refering to what you said here?:
>You can't really select decorations, but if you select across them and delete, mapping through that deletion will indeed remove the decoration from the set.

If so, I'm describing something else (forget about selecting anything). 

I've created a recording to make clear what I mean.

https://gfycat.com/terrificgreenbinturong
https://gfycat.com/anothersilkyduiker

I'm sorry if this feels like we're talking next to eachother, I'd really like to figure out what I'm doing wrong.

**Comment by marijnh** [comment]
Ah, you're asking why the widget behaves differently when backspacing out the second paragraph? That seems to be an artifact of how the key bindings work. Backspace in an empty textblock will _join_ it with the block before it, if there is such a block, deleting the (conceptual) `</p><p>` tokens that separate the blocks. Backspace in a block that has no other block before it, on the other hand, will just delete the empty block (`<p></p>`). The former covers the position where the decoration lives, the latter doesn't.
