### ISSUE TITLE
Transform.deleteRange/delete unexpected behaviour when from > to

### ISSUE THREAD

**Issue by mamsoudi** [ProseMirror/prosemirror#1202]
### Issue details
I was trying to remove an inline node, where I accidentally passed in the wrong positions, in a way that `from` was greater than `to`.

![marks](https://user-images.githubusercontent.com/8385009/132493874-7fe3c1f4-96d8-4c8b-95a8-f1fc59412c22.gif)

On the third list, there's a paragraph, with an inline node inside called `markHolder`. In a plugin's `appendTransaction` I attempt to remove or add this inline node, so in case the paragraph is empty, it'll still hold the previous marks, through mapping steps.
What I did, was, accidentally passing wrong values to `transaction.delete/deleteRange`.
Say if `markHolder` was at 8 instead of doing:
```
transaction.deleteRange(
  $pos.start() + markHolder.pos,
  $pos.start() + markHolder.pos + markHolder.node.nodeSize
)
```

I was doing:
```
transaction.deleteRange(
  $pos.start() + markHolder.pos,
  $pos.start() + markHolder.node.nodeSize
)
```

Which results to having greater values for `from` compare to `to`, not considering the starting position of the markHolder when merging two `listItems`. I think something magical happens inside of `delete/deleteRange` where if `from` is greater than `to` it instead adds content. So I was thinking perhaps there should be an error thrown in case `to < from`.

The reason it keeps adding content while I press `s` continuously is because it fails to remove the `markHolder` and `delete/deleteRange` keeps on adding instead of removing.

### Steps to reproduce

> I'll try to add one

### ProseMirror version

```prosemirror-transform: 1.3.2```

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Other

**Comment by marijnh** [comment]
This library does not try to validate arguments (since doing that properly would require a horrible amount of extra checks all over the code). So my position is that this is a problem that should be fixed on the caller side, and not something the library can take responsibility for.
