### ISSUE TITLE
Pasting HTML content: works on laptop but drops links on mobile 

### ISSUE THREAD

**Issue by taigit** [ProseMirror/prosemirror#1206]
### Steps to reproduce

In the demo editor on the home page of ProseMirror.net , if I paste HTML content with anchor links (eg: the paragraph below the demo editor) then the anchor links are preserved as long as I’m working on my laptop and Chrome browser.

But, if I do the same paste on my mobile phone (android 10 and chrome browser), then the anchor link url information is missing.

As for the source of the HTML, I tried several sources and tried to find “clean” sources. I tried

1. wikipedia, 
2. the paragraph below the demo editor on the home page 
3. I even tried the text “see more examples.” that sits inside the demo editor itself – they all failed.

I tried the Trix browser and that failed too. But when I tried the Quill editor then the paste preserved the html anchor link (using the HTML content that comes from inside the editor “see more examples.” ).

Preliminary discussion about this bug was at
https://discuss.prosemirror.net/t/pasting-html-content-works-on-laptop-but-drops-links-on-mobile/4051

### ProseMirror version

ProseMirror.net home page editor demo

### Affected platforms

Android 10 (Samsung mobile phone) on the Chrome browser 

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ x] Other

**Comment by taigit** [comment]
> The easiest way to get the HTML would be to set up a page with a contenteditable element, and have a "paste" event handler on that that takes event.dataTransfer.getData("text/plain") and puts it somewhere on the page where you can see it.

Ok, I got it setup.  I copied the text from the paragraph below the demo editor on the PM home page.  When I pasted the HTML, I got:

> unambiguous content like Markdown or XML, and classical WYSIWYG editors.

Inside the contenteditable area after the paste, the text has the right color  (2 words are blue)  but they are not active url links...

All of this is on my laptop.

I tried the same pasted text in my version of prosemirror editor.  After the paste, those link words are blue and hoovering over them causes them to be underlined.  Moreover, when I save the content, the result is HTML links that can be used.  Thus, pasting HTML links works in prosemirror on my laptop.

**Comment by marijnh** [comment]
So did you get the _HTML_ that was pasted on mobile?

**Comment by taigit** [comment]
It's interesting what happened on mobile:

First, I'm using standard google keyboard  Gboard.

If I copy "classical WYSIWYG editors." which has an html link in it and then: put my cursor in the paste area, get the blue dot, select the blue dot, and do a paste, then it works!   I get html content with a working link.

Just for the record, I get this:

```
Plain text:

classical WYSIWYG editors.



html format:

classical WYSIWYG editors.



html raw text:

<span style="color: rgb(0, 0, 0); font-family: &quot;Source Sans Pro&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">classical<span> </span></span><a href="https://en.wikipedia.org/wiki/WYSIWYG" style="text-decoration: none; color: rgb(0, 117, 255); font-family: &quot;Source Sans Pro&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">WYSIWYG</a><span style="color: rgb(0, 0, 0); font-family: &quot;Source Sans Pro&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>editors.</span>
```

Failing case:

On the other hand, if I copy "classical WYSIWYG editors." and the go the paste area, put my cursor in the area, notice that Gboard shows me a text snippet that I just copied in the "text guessing area of the keyboard" , and I select that text snippet, then: no paste event is triggered so my code does not show any text.   Nevertheless, the text is inserted in the paste area.  But it's just plain text and not html text.

Conclusion: 

So, on mobile phones there are multiple ways to do a "paste" operation and they are not the same operation (even though they appear to be the same from the user's point of view).  Using the proper paste operation on mobile results in full HTML content being inserted into ProseMirror.  Using Google keyboard's alternative paste-like operation, only inserts plain text.

Thus, seems to be not a bug, is that correct?  Or can you pick up the Gboard paste-like operation also?

**Comment by marijnh** [comment]
No, the text insertion via the keyboard will happen as a composition operation, and insert plain text. So indeed, this isn't something that ProseMirror could do anything about.
