### ISSUE TITLE
Dropping a draggable element within the editor sometimes creates a duplicate

### ISSUE THREAD

**Issue by thatsjonsense** [ProseMirror/prosemirror#1208]
### Issue details

Sometimes when dragging a block element (like an image) and dropping it within the editor, it makes a copy rather than pasting.

I can reproduce this consistently in our app by dragging outside the `contentDOM` portion of a NodeView into the portion rendered by the NodeView itself. As long as I drag within the contentDOM I'm fine, but once I drag into the outer portion of the NodeView (in our case just some padding), it turns into a copy rather than a move.

https://www.loom.com/share/0a72183afc2348239ee44dc95ff57bc8

I'm able to prevent this locally by adding my own `onDrop` handler and preventing default, but that's not ideal behavior because I'd expect to be able to drag onto the margins and have it lock to the nearest content. The drop part of this is working perfectly, except that it's just failing to remove the original.

### Steps to reproduce

Here's a basic CodeSandbox showing the issue: https://codesandbox.io/s/prosemirror-node-view-example-dragging-u1bgi?file=/src/index.js

It doesn't reproduce it consistently, but it only takes a few drags of the image toward the edges of the red border for a duplicate to happen.

I'm worried this CSB is actually too simple and may be showing a different bug than the one I'm encountering locally, because the cursor behavior is different and I'm not using a NodeView for the dropped element. Happy to adapt it if needed.

### ProseMirror version

prosemirror-commands
1.1.10
prosemirror-keymap
1.1.4
prosemirror-model
1.14.3
prosemirror-state
1.3.4
prosemirror-view
1.20.1

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by kapouer** [comment]
Hi,
i just had a variant of that bug.

In my scenario i have to check that the node passed as argument to `nodeView#update(node)` has the same attributes (i have a key attribute that identifies the node itself):

```
update(node) {
	const { attrs } = node;
	if (attrs.url != this.node.attrs.url) return; // HERE
	const dom = this.dom;
	this.node.attrs = attrs;
}
```

**Comment by kapouer** [comment]
EDIT: actually the nodeView#update method receives a *paragraph* node instead of the expected type.

**Comment by marijnh** [comment]
Yes, it is. See the [docs](https://prosemirror.net/docs/ref/#view.NodeView.update) for `update`.

**Comment by eric-burel** [comment]
@marijnh the `update` documentation seems to concern node views. However in my app I am using a web component (via Lit) instead to customize the node. @thatsjonsense is your initial issue, that didn't use a NodeView, solved?

I have a similar issue, and I feel like this is because `view.posAtCoords` is sometimes pointing to a neighbor character instead of the dragged element during `dragstart`. I see the [default handler](https://github.com/ProseMirror/prosemirror-view/blob/master/src/input.ts#L624) rely on the previous `mousedown` event to get the mouse position and then the position within the text. I suspect this position is not always correct for atomic elements like images. 

Example of a minimal custom handler that I use:
```ts
        dragstart: (view, event) => {
          // we bypass prosemirror default handler to preserve the custom data tied to those events, instead of text/plain
          if (hasSomeCustomData(event)) {
            // I will use this position during drop to remove the moved element
            this.initialPosition = view.posAtCoords({ left: event.clientX, top: event.clientY })?.pos || 0
            return true // skip prose-mirror handler
          }
        },
```

If I use the default handler, it's even weirder, the drag is "one step late" as I've mentioned [on the forum](https://discuss.prosemirror.net/t/drag-and-drop-of-an-atomic-element-is-one-step-late-building-a-minimal-repro/5405).

**Comment by onx2** [comment]
I'm having a similar issue and for anyone experiencing duplication on drop be sure to check the width of the editor. If you use width or max width and drop anything outside of that it will end up duplicating it. 


Dropping in the margin will cause a duplication. I don't know why exactly but attaching a drop listener to the surrounding div to prevent default solves the issue for me. Another solution is to use padding to get your preferred width but in my specific situation I wasn't able to do this, at least not after a quick attempt.

 (duplicates)  (works here)      (duplicates)
--------------------------------------------
|     margin |     editor     |     margin |
|     margin |     editor     |     margin |
|     margin |     editor     |     margin |
|     margin |     editor     |     margin |
--------------------------------------------
