### ISSUE TITLE
Cutting or deleting the entire contents of a node containing multiple paragraphs removes the node itself

### ISSUE THREAD

**Issue by AtlasLilian** [ProseMirror/prosemirror#1209]
### Issue details

When cutting or deleting the entire contents of a node that contains multiple paragraphs, the node itself is also removed. This is **inconsistent** with the behaviour for when there is only a single paragraph in the node. In this case, the parent node remains after cut / delete of the paragraph.

### Steps to reproduce
Will use `blockquote` as an example
1. Start a block quote with ">" followed by a space
2. Type any text
3. Press enter to create a new paragraph
4. Type any text
5. Select the two paragraphs
6. Press "Backspace"
The content is deleted, but so is the `blockquote` itself.

However, if you only include **one** paragraph in the `blockquote`, select it and delete it, the blockquote remains.

### ProseMirror version

Whatever version is used in the editor on the main page of the Prosemirror Site (https://prosemirror.net/)
Also present in our codebase though:
"prosemirror-collab": "^1.2.2",
"prosemirror-commands": "^1.1.4",
"prosemirror-dropcursor": "^1.3.2",
"prosemirror-history": "^1.1.3",
"prosemirror-inputrules": "^1.1.3",
"prosemirror-keymap": "1.1.4",
"prosemirror-markdown": "^1.4.2",
"prosemirror-model": "1.11.0",
"prosemirror-schema-list": "^1.1.4",
"prosemirror-state": "1.3.3",
"prosemirror-transform": "1.2.8",
"prosemirror-utils": "^1.0.0-0",
"prosemirror-view": "1.15.4",

### Affected platforms

Only tested in Chrome, probably true on other browsers

- [-] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://user-images.githubusercontent.com/91585445/135207485-75e75ab6-901a-47b8-84b4-ad64ef11845f.mov

**Comment by marijnh** [comment]
Attached patch should address this.
