### ISSUE TITLE
Menu overlaps content if editor is narrow

### ISSUE THREAD

**Issue by rexxars** [ProseMirror/prosemirror#121]
If you have enough menu elements and the screen size/editor size is small enough, the menu wraps to multiple lines. This makes it overlap the actual document, as seen below (the red lines right below the menu bar being the spell checker kicking in on the text that is overlapped by the menu):

![prose-menu-bug](https://cloud.githubusercontent.com/assets/48200/12236792/03a0c73c-b87c-11e5-9f94-48f3c312fb80.png)

**Comment by marijnh** [comment]
This is true. I wrote a nice solution that makes the content automatically get positioned depending on the bar height, but that was problematic too: it'd cause things to jump around on the screen, and tooltips to get mispositioned.

I'm not really sure what a good solution would look like. One option would be to simply clip the menubar, and make icons that stick out unusable. That's not great. Another would be to have it overlay the content and only change its taken-up space when the cursor moves below it. That's also somewhat awkward not obvious to the user. Any other ideas?

**Comment by marijnh** [comment]
I've fixed this in the following way:

 - The menubar now pushes the content down exactly as much as it needs to not to cover it (using regular css flow)

 - It is given a `min-height` of its maximum height so far to make sure that when it shrinks, it doesn't cause content to jump up and down

 - I've changed the icon margins to be narrowed and not overflow the editor width so quickly
