### ISSUE TITLE
Proposal:  allow users to disable `liftOutOfList` 

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1212]
Currently, the [`liftListItem`](https://github.com/ProseMirror/prosemirror-schema-list/blob/38867345f6d97d6793655ed77c16f1a7b18f6846/src/schema-list.js#L173) command function will lift a list item out of the list if there is not an outer list. This behavior causes the user to be unable to revert to the initial state by sinking the list item after lifting it. Most editors (like Google Docs and Word) won't do this when lifting list items:

https://user-images.githubusercontent.com/24715727/136151338-cd8fa56d-42dc-4f2e-b714-d623d4c17a85.mov

Therefore, we want to disable `liftOutOfList` when using `liftListItem`. I propose adding a new optional parameter to disable it:

```diff
- export function liftListItem(itemType) {
+ export function liftListItem(itemType, liftOut = true) {
```

**Comment by marijnh** [comment]
I think this is best done in your own code by wrapping the command in another function that checks whether the selection is in a nested list item and only calls `listListItem` when that's the case.

**Comment by ocavue** [comment]
Sounds good to me. Closing this issue.
