### ISSUE TITLE
Package version confusion on skypack.dev

### ISSUE THREAD

**Issue by abingham** [ProseMirror/prosemirror#1219]
Summary: Installing [prosemirror-inputrules@1.1.3 from skypack.dev](https://cdn.skypack.dev/-/prosemirror-inputrules@v1.1.3-Q81xYMZU5okdRF49AjYe/dist=es2019,mode=imports/optimized/prosemirror-inputrules.js) results in dependencies on multiple versions of prosemirror-transform.

I'm using [heritage](https://github.com/nestarz/heritage) to install prosemirror. Heritage is pulling its packages from skypack.dev. When I install prosemirror-inputrules@1.1.3, I end up with two versions of prosemirror-transform installed: 1.3.3 and 1.3.2. This seems to be because pm-inputrules@1.1.3 directly requires [prosemirror-state@1.3.4](https://cdn.skypack.dev/-/prosemirror-state@v1.3.4-VDZSfZg19RtsX2tM1mcd/dist=es2019,mode=imports/optimized/prosemirror-state.js) and prosemirror-transform@1.3.2, and prosemirror-state@1.3.4 transitively requires prosemirror-transform@1.3.3. 

I'm not sure if this is the intended state of things, but I thought it was questionable enough that I'd report it.

**Comment by marijnh** [comment]
I'm aware that skypack is terrible about this, but I don't think it's something that we can or should fix on our side.
