### ISSUE TITLE
Markdown demo has "source format markdown not defined" error

### ISSUE THREAD

**Issue by hubgit** [ProseMirror/prosemirror#122]
[The Markdown demo](http://prosemirror.net/demo_markdown.html) is currently not working: switching to the "WYSIWYM" mode throws a "source format markdown not defined" error and the input area is blank.

I see the same thing in both Chrome and Firefox.

**Comment by marijnh** [comment]
Fixed now. Some build had gone wrong (probably I ctrl-c-ed it), and my `dist/markdown/from_markdown.js` was 0 bytes. Rebuilding solved the problem.
