### ISSUE TITLE
The prosemirror-view library handle paste image from local directory not support safari

### ISSUE THREAD

**Issue by lmf** [ProseMirror/prosemirror#1223]
You can test it with official demo: https://prosemirror.net/examples/upload/

When copy a image from local directory will run capturePaste, but it not work on safari

Here is the code: 
```javascript
function capturePaste(view, e) {
  if (!view.dom.parentNode) return
  let plainText = view.shiftKey || view.state.selection.$from.parent.type.spec.code
  let target = view.dom.parentNode.appendChild(document.createElement(plainText ? "textarea" : "div"))
  if (!plainText) target.contentEditable = "true"
  target.style.cssText = "position: fixed; left: -10000px; top: 10px"
  target.focus()
  setTimeout(() => {
    view.focus()
    if (target.parentNode) target.parentNode.removeChild(target)
    if (plainText) doPaste(view, target.value, null, e)
    else doPaste(view, target.textContent, target.innerHTML, e)
  }, 50)
}
```

**Comment by marijnh** [comment]
It seems like pasting from a local directory will add a file, rather than HTML text, to the clipboard, which the demo you're linking has no code to handle, so I'm not sure what you are expecting to happen. With a custom `handlePaste` prop, you should be able to intercept the paste event without `capturePaste` even running.

**Comment by marijnh** [comment]
Also, don't spam duplicate issues. (https://github.com/ProseMirror/prosemirror/issues/1221)

**Comment by lmf** [comment]
You can read the default process logic of paste a file  in prosemirror/src/input.js.

When paste a image file `doPaste` will return false, so `capturePaste` will run, on the chrome `capturePaste` can intercept the paste event and insert image into temp div，and after setTimeout can read `target.innerHTML` is a `<img src=${base64} />` then past it to `doPaste`, but on safari `target.innerHTML` is empty, Can you understand it, it's so simple, you just test it with chrome and safari.

@marijnh 

 ```javascript
function doPaste(view, text, html, e) {
  let slice = parseFromClipboard(view, text, html, view.shiftKey, view.state.selection.$from)
  if (view.someProp("handlePaste", f => f(view, e, slice || Slice.empty))) return true
  if (!slice) return false

  let singleNode = sliceSingleNode(slice)
  let tr = singleNode ? view.state.tr.replaceSelectionWith(singleNode, view.shiftKey) : view.state.tr.replaceSelection(slice)
  view.dispatch(tr.scrollIntoView().setMeta("paste", true).setMeta("uiEvent", "paste"))
  return true
}

editHandlers.paste = (view, e) => {
  let data = brokenClipboardAPI ? null : e.clipboardData
  if (data && doPaste(view, data.getData("text/plain"), data.getData("text/html"), e)) e.preventDefault()
  else capturePaste(view, e)
}
```

**Comment by marijnh** [comment]
I know what the code is doing, I wrote it after all. Maybe instead of pasting code from the project, you could describe what your actual issue is—what are you expecting to happen? What kind of setup of ProseMirror are you using?

**Comment by lmf** [comment]
I paste a image file on chrome is ok, but on safari not work, this is where the problem and I want to compatible with safari
