### ISSUE TITLE
Passing in `doc` on ProseMirror `EditorState.create({...})`

### ISSUE THREAD

**Issue by c4lliope** [ProseMirror/prosemirror#1224]
Hello, @marijnh and colleagues,
I'm eager to get an application up and running which will combine both ProseMirror and CodeMirror,
into an XML editing program which users can choose their level of experience in.

I am running into a problem with this code:
```
import EditorState } from "prosemirror-state"
import { schema } from "prosemirror-schema-basic"
this.model = EditorState.create({ schema, doc: "'hello'"})
```

However it appears that the `doc` param isn't recognized, or needs a more complex `Node` object representing a parsed block of text.

How can I pass in a block of text to my Prosemirror editor on or quickly after initialization?

Curious and much obliged for your help,
Grace

**Comment by c4lliope** [comment]
I am developing an ElectronJS application using [electron-webpack](https://github.com/electron-userland/electron-webpack), and the source can be found here:
https://github.com/assembleapp/pagemaker, branch `prose`.

Clone code and reproduce error using:
```
git clone https://github.com/assembleapp/pagemaker
cd pagemaker
git checkout origin/prose -b prose
yarn
yarn go
# open console in running program
```

I see:
```
Uncaught TypeError: Cannot read property 'schema' of undefined
```

likely because there is no `schema` defined on my plain String I passed as the `doc` param.

You can drop line 45, `src/renderer/playground.js` - the `doc` param - and the error is cleaned up.

**Comment by marijnh** [comment]
The docs tell you the types of things, and mention that the [`doc` option](https://prosemirror.net/docs/ref/#state.EditorState^create^config.doc) should be a `Node`, not a string. If you just want to edit strings and don't want to think about the structure of the document, maybe just using CodeMirror, without ProseMirror, is what you need. In any case, this is a bug tracker, and not the place for questions.

**Comment by c4lliope** [comment]
@marijnh - apologies, where can I go for questions? I'll need to ask how to make a `Node`.

**Comment by c4lliope** [comment]
Ah, I see. I shall ask on https://discuss.prosemirror.net/ soon. Peace!
