### ISSUE TITLE
Can't use without build tools

### ISSUE THREAD

**Issue by DellCliff** [ProseMirror/prosemirror#1225]
As the title says, I can't use the editor without build tools. There is no CDN hosted file that I could easily include in one line in the browser and use the editor. Please publish readily usable binaries.

**Comment by marijnh** [comment]
That's true. But no, we won't publish 'usable binaries'. There's not really such a thing and the JS world has moved on from global variables and UMD modules, so if you want to use modern libraries, you too, will have to move on and use tools.

**Comment by DellCliff** [comment]
Real user friendly /s
There are still plenty of projects that can't move to a newer, modern system. Producing a UMD or AMD module won't hurt you.
