### ISSUE TITLE
Null reference exception when accessing nextSibling of dom in rm

### ISSUE THREAD

**Issue by igandrews** [ProseMirror/prosemirror#1226]
The error is:
`Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')TypeError: Cannot read properties of null (reading 'nextSibling')`

I'm sorry I don't have a way to reproduce this yet though I am trying to gather info/steps to do so. However from the callstack and reading the code I think I can see where the problem is happening. The code I'm using is minified but the exception is within [rm](https://github.com/ProseMirror/prosemirror-view/blob/75c930281c4c45c214df750dd367c17efc315b8f/src/viewdesc.js#L1072) as being called by [renderDescs](https://github.com/ProseMirror/prosemirror-view/blob/75c930281c4c45c214df750dd367c17efc315b8f/src/viewdesc.js#L954) being called by [updateChildren](https://github.com/ProseMirror/prosemirror-view/blob/75c930281c4c45c214df750dd367c17efc315b8f/src/viewdesc.js#L689). So basically for the exception to happen renderDescs has to be calling rm with a null dom. There are 2 places in renderDescs calling rm. The [later one](https://github.com/ProseMirror/prosemirror-view/blob/75c930281c4c45c214df750dd367c17efc315b8f/src/viewdesc.js#L971) is protected and wouldn't call it with null. However the [other call](https://github.com/ProseMirror/prosemirror-view/blob/75c930281c4c45c214df750dd367c17efc315b8f/src/viewdesc.js#L959) to it could. That code looks like this:
```
while (childDOM != dom) { 
   dom = rm(dom); 
   written = true 
}
```

So if rm were to return null (because the nextSibling of the dom passed to it was null - i.e. it had no sibling) that would set dom to null and the loop would continue and throw on the next iteration. It seems like it could be as simple as:
`while (dom && childDOM != dom)`

That would protect the code though I'm not sure why it's getting to that pt and the [subsequent line](https://github.com/ProseMirror/prosemirror-view/blob/75c930281c4c45c214df750dd367c17efc315b8f/src/viewdesc.js#L960) (`dom = dom.nextSibling`) would need to change too. Obviously it thinks the element should be in the tree and it's removing the other elements in the parent but it's never finding the element from the desc. I can say this was reported by a member of our JP group so likely they were using IME composition if that matters.

**Comment by marijnh** [comment]
This can only happen if something is seriously corrupted about the view desc tree (such as having two objects pointing to the same DOM node), so just guarding those calls isn't the solution here. Any direction on when it happens and how to reproduce it would be very useful.

**Comment by igandrews** [comment]
Ok thx. Am trying to find out from the person who hit the issue what steps they were taking so I can try to repro. Will add more when I get it.

**Comment by igandrews** [comment]
Hmm. I was able to reproduce it myself but nothing consistent. I'm in Chrome on the Mac (though the op was in Windows using Chrome) and I was using IME and changing marks while in a composition which in theory is going to have the editor clear its composition state. I am going to guess it's something about how prosemirror is manipulating the dom based on the marks but since the browser never really ends its composition things are in a bad state. I suspect gathering info after the fact isn't going to help much but I'll dump what I see in this particular manifestation of the exception:

This is how the editor looked atm (so the caret has underline and strikethrough marks):
![image](https://user-images.githubusercontent.com/17983788/146629732-2e7abb94-5fc4-4e4d-9bfc-4aca292eb932.png)

The renderDescs is in the process of handling the underline element (as the childDom):
![image](https://user-images.githubusercontent.com/17983788/146629802-7a652c0e-bd58-415a-a11e-355f770c68ba.png)

Since o here is the dom variable in non-minified code that started as the firstChild of the paragraph:
![image](https://user-images.githubusercontent.com/17983788/146629856-3412244e-b05b-463d-8666-db80977d5628.png)

At this point in the exception if I look at the element tree I see:
![image](https://user-images.githubusercontent.com/17983788/146629892-b0a18a17-f4cd-41f1-893a-46e0b44fb4f7.png)

The loop in renderDescs is currently on item index 2 in the array. That array looks like:
![image](https://user-images.githubusercontent.com/17983788/146629973-cffa99a0-513f-4960-80d2-27718b41256d.png)

If I look at the members of the array I can see that the dom of items 1 and 2 are both the same u element. Item 0 is the leading text. Item 3 was an em (so I may have hit italics while typing around and it has a child text element from what i see of that array entry) but that's not in the tree - guessing because the rm killed off the element in search of the underline again but it was already past it? Entry 4 is another text node also not in the tree likely for the same reason. BTW just to show that I'm not guessing 1 and 2 are the same u element:
![image](https://user-images.githubusercontent.com/17983788/146630216-9f787bd7-72e6-4283-93cb-1c616dc8b62c.png)

Going to leave my computer in this state for now but likely will kill it before you read this but I can try to repro again. I may modify the view's js locally to break into the debugger before doing anything should any entry of the array's dom match another.

**Comment by igandrews** [comment]
If I had to guess I'd say since prosemirror isn't really forcing the browser to end its composition things just end up getting into a bad state. Maybe they are holding elements that were removed or something. I know that the browsers are not particularly nice or consistent about ending composition. I know some browsers will end immediately when say a blur is triggered which may be why codemirror does that when it tries to clear its composition state but prosemirror doesn't do that and I'm pretty sure safari isn't very respectful of that and doesn't end the composition anyway. I had toyed with the idea of trying to end the current composition (using blur perhaps) before I change any marks/dom if a composition is in progress and if the composition doesn't end then just abort/skip the operation but I haven't gone that far yet.

**Comment by igandrews** [comment]
Going to kill the process but will dump a few more details. The triggering action in this case is via the mutation observer. The change(s) are just 2 records - a childList that is adding 1 text character and characterData where the oldValue is "" and the target.nodeValue is that single character that was added. The composing of the editor is true. Again though it's hard to discern much of the problem from this as it may have been in a bad state even prior to this transaction. 

The previous editorState was:
```json
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "attrs": {
          "align": "l",
          "indent": 0
        },
        "content": [
          {
            "type": "text",
            "text": "マリの魔のりまのり"
          },
          {
            "type": "text",
            "marks": [
              {
                "type": "em"
              }
            ],
            "text": "まのりママの"
          },
          {
            "type": "text",
            "text": "の"
          }
        ]
      }
    ]
  },
  "selection": {
    "type": "text",
    "anchor": 10,
    "head": 10
  },
  "storedMarks": [
    {
      "type": "underline"
    },
    {
      "type": "strikeThrough"
    }
  ]
}
```

The new editorState that is being applied here is:
```json
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "attrs": {
          "align": "l",
          "indent": 0
        },
        "content": [
          {
            "type": "text",
            "text": "マリの魔のりまのり"
          },
          {
            "type": "text",
            "marks": [
              {
                "type": "underline"
              },
              {
                "type": "strikeThrough"
              }
            ],
            "text": "ま"
          },
          {
            "type": "text",
            "marks": [
              {
                "type": "em"
              }
            ],
            "text": "まのりママの"
          },
          {
            "type": "text",
            "text": "の"
          }
        ]
      }
    ]
  },
  "selection": {
    "type": "text",
    "anchor": 11,
    "head": 11
  }
}
```

The transaction for which just contains a replace and the transaction was:
```json
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "attrs": {
          "align": "l",
          "indent": 0
        },
        "content": [
          {
            "type": "text",
            "text": "マリの魔のりまのり"
          },
          {
            "type": "text",
            "marks": [
              {
                "type": "underline"
              },
              {
                "type": "strikeThrough"
              }
            ],
            "text": "ま"
          },
          {
            "type": "text",
            "marks": [
              {
                "type": "em"
              }
            ],
            "text": "まのりママの"
          },
          {
            "type": "text",
            "text": "の"
          }
        ]
      }
    ]
  },
  "steps": [
    {
      "stepType": "replace",
      "from": 10,
      "to": 10,
      "slice": {
        "content": [
          {
            "type": "text",
            "marks": [
              {
                "type": "underline"
              },
              {
                "type": "strikeThrough"
              }
            ],
            "text": "ま"
          }
        ]
      }
    }
  ],
  "docs": [
    {
      "type": "doc",
      "content": [
        {
          "type": "paragraph",
          "attrs": {
            "align": "l",
            "indent": 0
          },
          "content": [
            {
              "type": "text",
              "text": "マリの魔のりまのり"
            },
            {
              "type": "text",
              "marks": [
                {
                  "type": "em"
                }
              ],
              "text": "まのりママの"
            },
            {
              "type": "text",
              "text": "の"
            }
          ]
        }
      ]
    }
  ],
  "mapping": {
    "maps": [
      {
        "ranges": [
          10,
          0,
          1
        ],
        "inverted": false
      }
    ],
    "from": 0,
    "to": 1
  },
  "time": 1639803452056,
  "curSelection": {
    "type": "text",
    "anchor": 11,
    "head": 11
  },
  "curSelectionFor": 1,
  "storedMarks": null,
  "updated": 5,
  "meta": {}
}
```

**Comment by marijnh** [comment]
Thanks for the detailed information. Can the issue be reproduced on https://prosemirror.net (and if so, using which steps with which IME)? I have some theories of where the problem might be, but it's hard to confirm them without being able to reproduce the issue myself (toggling on marks during composition didn't cause the issue for me).

**Comment by igandrews** [comment]
I hadn't been able to but actually just got it to happen:
![image](https://user-images.githubusercontent.com/17983788/146804267-d77d0a0e-f49c-4c4a-968f-84dfbf7bcdee.png)

Of course now I have to see if I can get this into reproducible steps. I appreciate you taking the time to look into this. Will post again as soon as I can get you some steps.

**Comment by igandrews** [comment]
Ok I think i have consistent steps to repro with the prosemirror.net page. Note in this case I'm using Chrome (v96.0.4664.93) in Mac (12.0.1) but I doubt that matters. I have a few different IME keyboards set up but for this I'm just using Japanese - Kana:
![image](https://user-images.githubusercontent.com/17983788/146805720-ffba2de4-1ebb-4fd1-9947-e4d89e2ec40e.png)

Steps:
- Navigate to prosemirror.net
- Click into the editor on the page
- Enable Japanese - Kana
![image](https://user-images.githubusercontent.com/17983788/146805948-1704c2b5-d4ca-4b84-9130-f114e59af8c5.png)

- Press Ctrl-A (select all default content)
- Press Delete
- Type A
- Press B(old) then press I(talic) in the toolbar with mouse
- Type A
- Press B(old) then press I(talic) in the toolbar with mouse
- Type A
- Press B(old) then press I(talic) in the toolbar with mouse
- Type A
- Press B(old) then press I(talic) in the toolbar with mouse
- Click with the mouse to put the caret after the 2nd character
![image](https://user-images.githubusercontent.com/17983788/146806264-33d99914-346e-4b67-95ca-aa7c308ef855.png)

- Type A
- Press B(old) _only_ in the toolbar with the mouse
- Type A

That seems to consistently lead to the exception for me.

**Comment by marijnh** [comment]
Thanks! I can reproduce this. Investigating.

**Comment by marijnh** [comment]
Could you see if attached patch solves this for you?

**Comment by igandrews** [comment]
Yes that seems to address the issue. I can't say for every scenario but it certainly fixes the above one and I did further testing and couldn't reproduce the issue with our code with additional manual testing. I really appreciate you looking at and addressing the issue so quickly. Hope you have a wonderful holiday.
