### ISSUE TITLE
How can I resolve `view` and `schema` in `clipboardTextParser`?

### ISSUE THREAD

**Issue by percy507** [ProseMirror/prosemirror#1227]
### Hi,

As the description of [clipboardTextParser](https://prosemirror.net/docs/ref/#view.EditorProps.clipboardTextParser),  this method should return a `Slice` object. But I found if I want to create a slice with the paste text, I need to create a Node first which rely on the schema of the context. 

After some research, I still can't find a way to resolve schema in `clipboardTextParser` unless pass `view` to `clipboardTextParser`.

> By the way, I use `clipboardTextParser` in a Plugin.
>
> Use `window.editorView` seems ok, but it is not graceful.

![image](https://user-images.githubusercontent.com/18365078/146632655-0e48b13a-5d3b-478c-bc80-a552eaf9e25a.png)

**Comment by jljorgenson18** [comment]
You should be able to do `$context.doc.type.schema` (https://prosemirror.net/docs/ref/#model.NodeType.schema)

Since this is a bug tracker, you may want to ask questions like this in the discussion forum https://discuss.prosemirror.net/

**Comment by percy507** [comment]
> You should be able to do `$context.doc.type.schema`

@jljorgenson18 Thanks for the hint. 

But if I want to resolve the instance of EditorView, how can I do that?

![image](https://user-images.githubusercontent.com/18365078/146659595-ce581de3-08e1-4b74-9a95-5f7ce1916c42.png)

**Comment by marijnh** [comment]
You can't get at the `view` instance in that prop, unless you somehow arrange for your clipboard parser to have access to the view it was added to through another channel (say, closing over a function that can retrieve it).

**Comment by percy507** [comment]
@marijnh Thanks. That's it. 👍 

Here is the code.

```ts
// editor.ts
class MyEditor {
  pmView;

  constructor() {
    ...
    this.pmView = new EditorView(rootDOM, {
      state: EditorState.create({
        ...
        plugins: [
          myPastePlugin(() => {
            const that = this;
            return that.pmView;
          })
        ]
      })
    })
    ...
  }
}

// my-paste-plugin.ts
export const myPastePlugin = (getView: () => EditorView) => {
  return new Plugin({
    ...
    props: {
      clipboardTextParser(text, $context, plain) {
        const view = getView();
        const { schema } = view.state;
        const serializer = DOMSerializer.fromSchema(schema);
        const parser: DOMParser =
          view.someProp('clipboardParser') ||
          view.someProp('domParser') ||
          DOMParser.fromSchema(schema);
        ...
      }
    }
  })
}
```
