### ISSUE TITLE
textBetween behavior is unintuitive when passed the `end` and `start` of respective nodes.

### ISSUE THREAD

**Issue by lukesmurray** [ProseMirror/prosemirror#1228]
When text between spans a block separator, it does not return the block separator.

[Reproduction](https://glitch.com/edit/#!/grateful-clumsy-mastodon).

```
0     123     4    567 
   <p>foo</p>   <p>bar</p>
```

Given a document with the previous positions and content I would expect `doc.textBetween(3, 5, "separator")` to return `"separator"` instead it returns an empty string.

**Comment by marijnh** [comment]
This behavior is intentional, but I guess the docs did suggest it would behave differently. Attached patch adjusts the doc comment.
