### ISSUE TITLE
Can't access discuss page

### ISSUE THREAD

**Issue by marclave** [ProseMirror/prosemirror#1229]
I tried on multiple devices and browsers and networks, and I keep getting this error when I go to https://discuss.prosemirror.net/

![image](https://user-images.githubusercontent.com/6176314/147072006-a5796a72-4e5d-47b6-bd66-e4640fadcd96.png)

**Comment by marijnh** [comment]
Ugh. I upgraded this morning, and that appears to have broken stuff — which I didn't notice because, I suppose, my browser was still using a cached version of the broken file. Looking into this.

**Comment by marijnh** [comment]
Well, it seems to be back up. For some reason that I'm still not clear on nginx was truncating all long http responses after I upgraded it, which broke a lot of stuff.
