### ISSUE TITLE
Extra text is removed when a key is pressed while selection starts between marks

### ISSUE THREAD

**Issue by ght901** [ProseMirror/prosemirror#1230]
I've noticed some strange behavior that happens when text is replaced and the selection starts between two sections of marked text and continues past the marked text. 
The behavior is reproducible on both Chrome and Safari on the basic demo. It is not reproducible on Firefox.

Reproduction Steps:
- Clear all text from the editor
- Enter the text `This is a test.`
- Bold all text
- Select the word `test`, remove the bolding and add italics
- Select the text `test.`
- Hit a character key
- In addition to the selected text being replaced, the marked text before the selection will be replaced with the same character

![f1fvQRI](https://user-images.githubusercontent.com/83425721/147626782-32f96f13-9fd6-4a87-b4f5-0cf35c64ec9d.gif)

**Comment by marijnh** [comment]
Attached patch should resolve this.
