### ISSUE TITLE
Text Selection via cursor not working with manually inserted line breaks

### ISSUE THREAD

**Issue by VFritsch** [ProseMirror/prosemirror#1231]
Hi,

we are using the prosemirror editor in combination with a custom built toolbar and we found a very specific problem without a solution for it.

As soon as we add manual line breaks inside the editor, the text selection via the cursor stops working or works rather unreliably.
This seems to only effect cursor selection and not the text selection via keyboard.

If we add/type in text without manual line breaks, the text selection works as intended.

I have added an example to hopefully demonstrate my problem a bit clearer.

![Animation](https://user-images.githubusercontent.com/91722484/147643135-4c09c258-dd26-4763-999a-3af9c7d66ebb.gif)

**Comment by marijnh** [comment]
I can't reproduce this. What browser are you using? And can you provide a simple script that just sets up this situation using a plain ProseMirror instance?

**Comment by VFritsch** [comment]
You can close this issue. We found the cause of the problem to be connected to the wrapper element in which the ProseMirror was embedded.

Thank you for your time.
