### ISSUE TITLE
Prosemirrors Domserializer escapes `&` characters in URLs

### ISSUE THREAD

**Issue by floriankrueger** [ProseMirror/prosemirror#1233]
I'm trying to deliver contents of a prosemirror document as HTML via API and came across this weird behavior when trying to serialize a link that contains ampersand characters:

Expected:

```html
<p>
  <a href="https://blog.example.com/great-blog-post/?utm_source=test&utm_medium=cypress">a link</a>
</p>
```

Actual:

```html
<p>
  <a href="https://blog.example.com/great-blog-post/?utm_source=test&amp;utm_medium=cypress">a link</a>
</p>
```

Usually, this doesn't seem to be an issue since browsers tend to correct that but when delivered via API my consumer struggles to render the links correctly due to this.

Reproduction: https://glitch.com/edit/#!/third-humorous-decade

**Comment by marijnh** [comment]
That's not ProseMirror, that's being done by the browser's `innerHTML`.

**Comment by benasher44** [comment]
Which part is being done by the browser's `innerHTML`, exactly?

**Comment by marijnh** [comment]
The HTML escaping part.

**Comment by floriankrueger** [comment]
Hi @marijnh I wanted to quickly loop back on this. I did read the HTML specification again and could confirm that this is actually valid HTML that is generated here. Sorry for bugging you with this. Will forward this information to the API consumer so they can adjust their code to accept the HTML including character references in attributes.

Thank you for your work on Prosemirror 💙
