### ISSUE TITLE
ProseMirror-trailingBreak probably not needed with gapcursor

### ISSUE THREAD

**Issue by thet** [ProseMirror/prosemirror#1241]
There is a ``<br class="ProseMirror-trailingBreak">`` added to inline content (e.g. a inline image) if they are a leaf node (If I got that correctly).

As far as I understand from the following comment, this is due to usability reasons, so that a editor can continue writing where it wouldn't be possible otherwise:
https://discuss.prosemirror.net/t/parser-adds-br-tag-to-every-paragraph/1539/6

With the prosemirror-gapcursor extenstion (or the @tiptap/extension-gapcursor in our case) this seems not to be necessary.
Also, our designer complains.

Instead of hiding this via CSS I'd like to turn the trailing break element off.
If this is not an option, can it be turned off when gapcursor is active on the leaf node?

**Comment by thet** [comment]
For reference, the trailingbreak is set here: https://github.com/ProseMirror/prosemirror-view/blob/089aa9bd8f261d8181782bc5f8c46c5dc5e11a5f/src/viewdesc.js#L1271

**Comment by marijnh** [comment]
Is this `<br>` causing you any actual problems?

**Comment by thet** [comment]
I agreed with the designer that we just try to set it ``display: none`` if it is really causing any problems. We did foresee some usability problems, also the problem with users trying to delete the break and deleting the image instead.
I'm watching the issue and will bring it up again if it really hurts us.
Thanks so far for everything!

**Comment by alessiostalla** [comment]
Does it have to be a `<br>`? What if we want the content after the node to continue on the same line?

**Comment by marijnh** [comment]
The `<br>` is added to block nodes. Block nodes get their own vertical space.

**Comment by alessiostalla** [comment]
Oh, I see. I was using a span tag as a block node to avoid the "no mixing of inline and block nodes" rule, and it would only break the line when empty. I've refactored the schema to avoid using a block node.

**Comment by Siubaak** [comment]
I encounter a problem with the trailing break after a image as well.
