### ISSUE TITLE
How to get all styles of the selected text in the current editor (Font background color and font color)  ,thanks

### ISSUE THREAD

**Issue by 596121109** [ProseMirror/prosemirror#1242]
How to get all styles of the selected text in the current editor (Font background color and font color)

,thanks

**Comment by 596121109** [comment]
![微信图片_20220217114339](https://user-images.githubusercontent.com/16631844/154425753-d9e6891b-2148-4be3-b869-ae86a5db86f2.png)

**Comment by marijnh** [comment]
Questions go on the [forum](https://discuss.prosemirror.net), not the bug tracker, but I see you already cross-posted there. So also, don't cross-post.
