### ISSUE TITLE
prosemirror-model broken by upstream change to orderedmap

### ISSUE THREAD

**Issue by muteor** [ProseMirror/prosemirror#1243]
It seems that this upstream commit (https://github.com/marijnh/orderedmap/commit/94955f08e43e4115fbfa68c9376d02fcfe6763a3) broke the typings inside prosemirror-model.

The introduction of the types files in that commit means TS is now parsing the types for orderedmap, so while the breakage came from upstream its really an upstream fix for types that should have been exported before.

The error:

```
../../node_modules/@types/prosemirror-model/index.d.ts:1147:40 - error TS2709: Cannot use namespace 'OrderedMap' as a type.
1147     nodes: { [name in N]: NodeSpec } | OrderedMap<NodeSpec>;
```

For my project I patched it with:

```
declare type OrderedMapType<T = any> = typeof OrderedMap;
...
nodes: { [name in N]: NodeSpec } | OrderedMapType<NodeSpec>
```

**Comment by tarangpandya** [comment]
We also started getting this issue in our build. Unfortunately we can not make anymore build. Can someone please fix it?

**Comment by marijnh** [comment]
See https://github.com/marijnh/orderedmap/issues/9
