### ISSUE TITLE
Programmably insert emoji, then press Enter key will split the emoji character

### ISSUE THREAD

**Issue by percy507** [ProseMirror/prosemirror#1244]
Hi @marijnh ,

I am trying to build a emoji plugin.

Programmably insert a emoji and set the cursor behind it, then press Enter key, the emoji character will be splited into two unknown chars just like the below picture showing.

After some test, it seems not only the emoji, some CJK chars also have the same problem. (eg: `𠮷`)  I guess that any char which contains two UTF-16 code units will have the same problem. 😂

> Here is a demo: https://glitch.com/edit/#!/rich-glossy-mouth?path=index.js%3A14%3A0

![2022-02-19 05 46 11](https://user-images.githubusercontent.com/18365078/154767367-5dd16e88-d2ff-48c4-ba3a-4adfd48dde2c.gif)

**Comment by marijnh** [comment]
Are you sure you're putting the cursor _after_ the newly inserted character, not in the middle of it?

**Comment by percy507** [comment]
Ah...My bad. I ignore the length of emoji is 2, not 1.  Thanks for the hint.

![image](https://user-images.githubusercontent.com/18365078/154799811-ddc1656c-b009-4561-a10a-be58f6dd2442.png)
