### ISSUE TITLE
IME Composition breaks when typing before/after an hr.

### ISSUE THREAD

**Issue by igandrews** [ProseMirror/prosemirror#1246]
Steps:

- Open prosemirror.net in the browser and click in the prosemirror editor on the page
- Select all (e.g. ctrl+a) and delete
- Enable Japanse ime. 
![image](https://user-images.githubusercontent.com/17983788/155400789-bfdc9757-4602-48e1-8595-3945e862b0f7.png)

- Use the Insert->Horizontal Rule to add a divider
- Click below the hr such that the cursor is shown below it. 
![image](https://user-images.githubusercontent.com/17983788/155400924-c893faae-dc5d-4306-a2f2-5d6ea0d1b6f1.png)

- Type `kaka`

The expected results are:
![image](https://user-images.githubusercontent.com/17983788/155401108-694d761e-7654-4a11-951b-8627bf9b3ea0.png)

The actual results depend on the browser. In Chrome (Version 98.0.4758.102 (Official Build) (64-bit)) the first k is committed and the a starts a new composition:
![image](https://user-images.githubusercontent.com/17983788/155401351-06796306-d30c-4f71-b65a-a1ea01e09e22.png)

In Firefox (97.0.1 (64-bit)) the composition breaks and characters typed after the initial k are not visible:
![image](https://user-images.githubusercontent.com/17983788/155401633-ede232d2-f5df-4fee-b31a-f6f5722e992a.png)

There's similar issues on other platforms/browsers. If there's any other info I can provide pls let me know.

**Comment by marijnh** [comment]
The problem was that there wasn't an inline context to type in yet when the gap cursor is active, so ProseMirror would mangle the DOM to fix it up _after_ the composition started, aborting it again. Attached patch should help.
