### ISSUE TITLE
Maybe it’s a bug for Order List parse? 

### ISSUE THREAD

**Issue by jcold** [ProseMirror/prosemirror#1247]
Source HTML
```
<ul>
  <li>abc</li>
  <li>
    xxxx
    <ul>
      <li>girl</li>
      <li>
        <ol>
          <li>你好</li>
          <li>中国 </li>
        </ol>
      </li>
      <li>women</li>
    </ul>
    human
  </li>
  <li>def</li>
</ul>
```

copy HTML result content , then paste  it to prosemirror editor, found parse incorrect, and other online HTML editor is right. 

https://codepen.io/jcold/pen/Xwdbqy
https://prosemirror.net/
https://html5-editor.net/

**Comment by marijnh** [comment]
It might help if you describe _what_, precisely is unexpected about ProseMirror's parse.

**Comment by jcold** [comment]
Use example bullet_list schema, DOMParse output
```
<ul>
  <li><p>abc</p></li>
  <li>
    <p>xxxx</p>
    <ul>
      <li><p>girl</p></li>
      <li>
        <p>你好</p>
        <ol>
          <li><p>中国</p></li>
        </ol>
      </li>
      <li><p>women</p></li>
    </ul>
    <p>human</p>
  </li>
  <li><p>def</p></li>
</ul>

```

`你好` lift to parent node.

**Comment by marijnh** [comment]
It seems that you're using a schema that requires a paragraph at the start of every list item. That will have this effect.

**Comment by jcold** [comment]
Awesome, as you said, I solved my problem, thank you very much for your speed and patience.
