### ISSUE TITLE
Defining property impacting pasting of node, and pasting into node

### ISSUE THREAD

**Issue by mmackeyatl** [ProseMirror/prosemirror#1248]
Hi,

I’ve noticed the `defining` property seeming to be determining two behaviours:
1. What happens when pasting content **of** that node type elsewhere in the doc.
2. What happens when pasting content **into** a node of that type.

In particular, we’re seeing a case where when we copy text from a document using cmd+a (so openStart is set to 0), when we try to paste this text into a non-defining node, it removes the node.
Setting the node to be defining fixes this, however it also gives us the undesired behaviour of when we copy text out of this node, it copies the node too.

I was wondering if this is intended behaviour? And whether it could be separated out into two different spec options?

I've attached some recordings that will hopefully help demonstrate this. 

Thanks

Case when node is non-defining:
https://user-images.githubusercontent.com/98142180/156479502-388ebf76-ba2b-4d4a-943a-800da710e2e8.mov

Case when node is defining: 
https://user-images.githubusercontent.com/98142180/156479522-4018a6c8-da2f-4cc7-8ed4-1a03a7ef6f36.mov

**Comment by marijnh** [comment]
I'm not too keen on making this more granular. That node kind of looks like the behavior with defining: true would align with what most users expect?

**Comment by mmackeyatl** [comment]
We have some cases we'd like to distinguish between the two cases. Such as when users may expect a node to persist when pasting new content into it, but also when only copying the text within it (rather than the whole node) that the node would not persist.

**Comment by marijnh** [comment]
Do the attached patches look like they would work for you?

**Comment by mmackeyatl** [comment]
Yes, thank you! This is exactly what we needed.

**Comment by marijnh** [comment]
Tagged prosemirror-transform 1.4.0 with this feature.
