### ISSUE TITLE
NodeView.setSelection not called when selection is changed via a transaction

### ISSUE THREAD

**Issue by abingham** [ProseMirror/prosemirror#1249]
The setup for this is perhaps a bit complicated. I have a nodeview for `code_block` nodes which renders a CodeMirror-6 editor. As this CodeMirror is edited, it translates its own transactions into ProseMirror transactions, calculates the new PM state from them, and updates a redux store with the new state. This new state is then "updated" into Prosemirror, which notifies the nodeview (i.e. CodeMirror) which renders itself appropriately. This all works insofar as textual changes initiated in CodeMirror flow properly through redux and are properly represented in both the PM and CM models.

However, selections do not seem to be propagated correctly. When a state containing a new selection is 'updated' into the ProseMirror, I expected ProseMirror to call `setSelection` on the nodeview, but that is not happening. I've verified that the new state does indeed have an updated selection, so it seems like, in principle, it should trigger a selection update in the nodeview.

After a little digging, it appears it looks like the problem might lie in `prosemirror-view/src/selection.js:selectionToDOM()`. This calls `editorOwnsSelection()`, aborting if this returns false, which it seems to do when the CodeMirror has the focus. When this aborts, subsequent `view.docView.setSelection()` calls are skipped. I'm not 100% sure if this is the source of the problem I'm seeing, but I'm certain that this aborting occurs (at least, I've seen it happen in a debugger).

So I guess the main question is this: should I expect `setSelection()` to be called on my nodeview when I call `updateState()` on an `EditorView` with a state that has an updated selection?

If I *can* expect that, what might I be doing wrong to cause this to not work?

If I *can't* expect that, how should I go about updating the selection in my nodeviews? It's important that I be able to rely on state updates coming from completely outside of ProseMirror/CodeMirror, hence the reliance on redux; we have other components that need to update the editor contents, possibly including the selection.

**Comment by marijnh** [comment]
> should I expect setSelection() to be called on my nodeview when I call updateState() on an EditorView with a state that has an updated selection?

Only if the editor owns the selection (i.e. has focus) _and_ the selection is inside the node that the node view manages.

**Comment by abingham** [comment]
Thanks, I managed to get this sorted out.
