### ISSUE TITLE
IME composing is not working when the cursor is in `th` tag

### ISSUE THREAD

**Issue by MH4GF** [ProseMirror/prosemirror#1251]
Glitch remix: https://glitch.com/edit/#!/shy-tremendous-dove

For the convenience of making the width of the button 100% with CSS only, I have added a button in `th` cell with `Decoration.widget` .

In this case, when typing Japanese, composing abruptly terminates only for the first character, and Japanese conversion becomes impossible.

I know that this occurs under the following conditions, but we do not know the more fundamental cause.

- It occurs when there is a button with `position: absolute` and inline text in the `th` element
- It doesn't happen if there is a child element such as svg inside the button.
- Occurs in Chrome and Vivaldi, but not in Firefox and Safari

Perhaps it is a bug in chromium, but if you know anything about it, please let me know.

**Comment by marijnh** [comment]
This is the browser placing the new text in the wrong element, which causes ProseMirror to have to move the content and selection after composition starts, which will disrupt the composition. Putting a zero-with space before and after the button seems to help, and is probably the best way to solve this.

```javascript
  div.appendChild(document.createTextNode("\u200b"))
  div.appendChild(button);
  div.appendChild(document.createTextNode("\u200b"))
```
