### ISSUE TITLE
Android enter in middle of nested node deletes remaining content

### ISSUE THREAD

**Issue by jordoh** [ProseMirror/prosemirror#1252]
# Issue details

This is somewhat similar to #1150, but does not require the word suggestion underline to be present (though it typically is present). When the cursor is not at the end of a nested DOM node, pressing enter deletes the remainder of the node's content and leaves the cursor in place.

# Steps to reproduce

https://glitch.com/edit/#!/walnut-organic-anglerfish

Render a node view (or generate via schema `toDOM`) that adds an additional nested DOM node:

```
class ParagraphView {
  constructor(node) {
    this.dom = document.createElement("p");
    this.contentDOM = document.createElement("p");
    this.dom.appendChild(this.contentDOM);
  }
}
```
1. Place cursor in the middle of a paragraph.
2. Press enter

Expected result:
Paragraph gets split, placing cursor at start of a new paragraph comprised of the remainder of the content after the cursor.

Actual result:
Cursor stays in place and remainder of the paragraph is deleted.

# Additional details

This is observed on the latest prosemirror-view, but given how relevant https://github.com/ProseMirror/prosemirror-view/commit/cc0934ed0735cc8f0fb31d90f46b0368c2b83a09 seemed, I tried going back to prosemirror-view 1.23.3 and still observed the same behavior.

# Affected platforms

Android 12 Chrome with GBoard

# Screencast

https://user-images.githubusercontent.com/450345/158435868-e6e88dc8-5574-4b69-8464-e3720192c032.mov

**Comment by marijnh** [comment]
Thanks for the reproduction instructions! The glitch link has stopped working, once again, but I could get this to happen using your `ParagraphView` class. Attached patch should work around this.

**Comment by jordoh** [comment]
Thanks @marijnh - I can confirm that fixes the issue. Much appreciated.
