### ISSUE TITLE
End key behaviour inconsistent

### ISSUE THREAD

**Issue by ght901** [ProseMirror/prosemirror#1253]
At some point the behaviour of the end key changed. Previously the end key would move the cursor to the end of the current line. Now it moves the cursor to the end of the current paragraph.
I'm assuming this change was unintended as shift+end still only selects up to the end of the current line.

**Comment by marijnh** [comment]
ProseMirror does not handle the end key in a custom way, so what you're seeing is the native behavior of your browser.

**Comment by ght901** [comment]
I don't believe it's native browser behaviour that I'm seeing as the behaviour is different on older versions. I've done more testing and believe the change happened in version 1.2.0 or prosemirror-commands, presumably the changes to pcBaseKeymap.
I can make the changes to get the previous End behaviour back myself but I do still think the inconsistency between Shift+End and End is a bug.

**Comment by marijnh** [comment]
Ah, you are right, that was changed recently in https://github.com/ProseMirror/prosemirror-commands/pull/13 . Does dropping the Home/End bindings again while keeping the macOS ctrl-a/e ones seem like a reasonable solution?

**Comment by ght901** [comment]
That seems reasonable to me.

**Comment by marijnh** [comment]
Done in attached patch.
