### ISSUE TITLE
Getting TypeError: Cannot read properties of null (reading 'matchesNode')

### ISSUE THREAD

**Issue by alex-mironov** [ProseMirror/prosemirror#1254]
For some reason, I'm getting an Unhandled Runtime Error:
`TypeError: Cannot read properties of null (reading 'matchesNode')`
on attempt to update the state `editorView.updateState(editorState);`.
![SCR-20220316-ksy](https://user-images.githubusercontent.com/2544767/158620317-ab93d85f-d257-440f-9016-0271270ccb27.png)
Not sure what exactly goes wrong but `docView ` is null. I was thinking if I can somehow check if `docView` exists. But from what I can see `EditorView` interface doesn't expose this property.
![SCR-20220316-kv6](https://user-images.githubusercontent.com/2544767/158620733-6cde4e55-6999-4b0e-b228-cfe5939a89c9.png)
Would appreciate any help.

**Comment by marijnh** [comment]
This will happen if you try to use an editor view after calling `.destroy()` on it.

**Comment by alex-mironov** [comment]
Thank you, @marijnh, is there a way to check if the view has been destroyed? Or should I manage this state myself in react component?

**Comment by marijnh** [comment]
There's no exported way to check for this, no, so I guess you'll have to keep a flag externally.
