### ISSUE TITLE
Two spaces inserted instead of one when pressing space at the end of a link when using ime.

### ISSUE THREAD

**Issue by igandrews** [ProseMirror/prosemirror#1255]
Steps:
* Open Chrome (in my case chrome v99.0.4844.82 for windows)  and browse to [prosemirror.net](https://prosemirror.net/)
* Put the caret after "examples" but before the "." e.g. 
![image](https://user-images.githubusercontent.com/17983788/159312139-6ec039a2-0ad8-4884-b057-fe4f8da1eae7.png)
* Enable japanese ime for hiragana. e.g. 
![image](https://user-images.githubusercontent.com/17983788/159311409-87c19a2a-0c98-436e-953b-6cea1de6ec23.png)
* press space

Result:
2 wide spaces are inserted. I've shift-left arrow'd here to select the 2nd one just to show the result more clearly. 
![image](https://user-images.githubusercontent.com/17983788/159311630-198ff492-3daf-4779-9b95-27b0b487a033.png)

When I try the same steps with a vanilla contentEditable div I just get the 1 wide space.

**Comment by marijnh** [comment]
This appears to be fixed by the move to `EditContext`.
