### ISSUE TITLE
Marks are applied to already confirmed text while typing in a new composition before existing text.

### ISSUE THREAD

**Issue by igandrews** [ProseMirror/prosemirror#1256]
The steps here are for Safari on mac but a similar issue happens in Chrome on Windows & Mac with an additional problem.

* Open the browser and navigate to prosemirror.net
* Select all the text and delete so the editor is empty
* Enable hiragana keyboard e.g. 
![image](https://user-images.githubusercontent.com/17983788/159579690-a4d79829-9667-45f1-9e8d-02a29b9edbba.png)
or 
![image](https://user-images.githubusercontent.com/17983788/159579730-af13ea16-9864-4f10-998f-eb409835fd1c.png)
* Type aaa and press enter to confirm/end the composition
* Put the caret at the beginning of the text
* Press the Bold button in the toolbar
* Type aaa

Results:
After first a everything seems ok. After 2nd a the first 4 characters (i.e. 2 in composition and 2 after composition) seem bold and if you had committed here it would be that way. 
![image](https://user-images.githubusercontent.com/17983788/159738093-4b72b829-d490-4761-b4e8-41c6a12de18c.png)
After 3rd a all 6 characters are bold.　
![image](https://user-images.githubusercontent.com/17983788/159738245-94ccb732-30ff-4bd0-bee2-d464cc6b09a6.png)

In Chrome (windows or mac) the behavior is a little different/worst. After 2nd a the first 3 characters are bold and it appears like the composition is in positions 1&2 instead of 0&1 based on the underline. After the 3rd a the first 2 are bold, the 3 is not and then next 3 are bold and it appears like the last 3 are the composition and the caret is between the 4th and 5th characters instead of the 3rd and 4th:
![image](https://user-images.githubusercontent.com/17983788/159737379-a1ecb069-3777-4194-ba69-d6889122d769.png)

**Comment by monologueH** [comment]
i have the same problem https://github.com/ProseMirror/prosemirror/issues/1408

**Comment by marijnh** [comment]
Attached patch should fix this issue.
