### ISSUE TITLE
`parseDOM()` get incorrect attributes if the nested DOM nodes have the same styles.

### ISSUE THREAD

**Issue by zunsthy** [ProseMirror/prosemirror#1258]
## Issue details

The nested DOM nodes have the same styles, like `color: xxx`, and some of them will lose "color" attributes.

original DOM string:
```html
<span style="color:red">aaa<span style="color:blue">bbb</span>ccc</span>
```

after `toDOM()`:
```html
<span style="color: red">aaa</span><span style="color: blue">bbb</span>ccc
```

## Steps to reproduce

[Basic example](https://prosemirror.net/examples/basic/) glitch pages:
https://glitch.com/edit/#!/remix/prosemirror-demo-basic

Add color schema in app.js:
```js
const mySchema = new Schema({
  nodes: addListNodes(schema.spec.nodes, "paragraph block*", "block"),
  marks: schema.spec.marks.append({
    color: {
      attrs: { color: {} },
      parseDOM: [{ style: 'color', getAttrs(color) { return { color } } }],
      toDOM(node) { return ['span', { style: `color: ${node.attrs.color}` }] },
    },
  })
});
```

Change input DOM string in index.html: 
```html
<div style="display: none" id="content">
  <span style="color:red">red<span style="color:blue">blue</span>red</span>
</div>
```

<img width="167" alt="image" src="https://user-images.githubusercontent.com/5395262/160581102-2a9f14ea-533a-48e2-ac3b-6495397e12c1.png">

## Expected

![image](https://user-images.githubusercontent.com/5395262/160581387-b281ef59-f608-4877-bedc-ae138272051b.png)

**Comment by marijnh** [comment]
Have you tried setting [`excludes: ""`](https://prosemirror.net/docs/ref/#model.MarkSpec.excludes) in the mark's spec?

**Comment by zunsthy** [comment]
> Have you tried setting [`excludes: ""`](https://prosemirror.net/docs/ref/#model.MarkSpec.excludes) in the mark's spec?

It works !

Thank you ~

**Comment by zunsthy** [comment]
@marijnh
`span > span` is parent-child relation. Why is it affected by `excludes`?

**Comment by marijnh** [comment]
See the [guide](https://prosemirror.net/docs/guide/#doc.structure) on how marks work.

**Comment by xiaody** [comment]
> See the [guide](https://prosemirror.net/docs/guide/#doc.structure) on how marks work.

Hi @marijnh 

This behavior looks really confusing to me, even after read the guide, which didn't say much about the parsing process. Let's add some ids to the input HTML.

```html
<span id=parent style="color:red">
  <span id=child1>red</span>
  <span id=child2 style="color:blue">blue</span>
  <span id=child3>red</span>
</span>
```

As a user, I would expect `excludes` only affects what marks `child2` would get.
Since `child1` could get the mark(color:red) correctly, prosemirror must have implemented some inheriting logic when parsing the DOM. So why does `child2` somehow interrupt the inheriting logic and prevent the sibling `child3` from getting the mark(color:red)?

**Comment by marijnh** [comment]
That _is_ a product of the way parsing works. It'll keep a set of marks as it processes a sequence of sibling nodes, and if two instances of a mark can't coexist, adding the mark for the inner span will drop the mark for the outer span from that set.

**Comment by zunsthy** [comment]
> That _is_ a product of the way parsing works. It'll keep a set of marks as it processes a sequence of sibling nodes, and if two instances of a mark can't coexist, adding the mark for the inner span will drop the mark for the outer span from that set.

There are some problems on operating marks, if `excludes=''` is set.
as example,

Parse `<span style="color:red">red<span style="color:blue">blue</span>red</span>`
returns this structure: ``` 
node1 [MarkRed]
node2 [MarkRed, MarkBlue]
node3 [MarkRed]
```

1. need to merge all marks if i want to get the color of "node2"
2. need to clean previous marks if i want to set other color of "node2"

But i don't know what marks need to merge or clean because of `exclude=''` in every mark schema.

Is there any method or config for keeping expected html info and resulting no-confusing marks set?
```
node1 [MarkRed]
node2 [MarkBlue]
node3 [MarkRed]
```

**Comment by zunsthy** [comment]
i try to add a stack for recording the marks operating. it can pass test.
https://github.com/ProseMirror/prosemirror-model/compare/master...zunsthy:feature/stack_marks?expand=1

**Comment by marijnh** [comment]
There's already `activeMarks` and `pendingMarks`, adding _another_ collection of marks to the process seems excessive. It's likely that the way marks are tracked could be improved to address this use case, but I'm not sure when I'll have time to dig into that.

**Comment by zunsthy** [comment]
@marijnh version 1.22.3 resolve it ?

**Comment by marijnh** [comment]
Probably, as this looks like the same issue as [this](https://discuss.prosemirror.net/t/how-to-parse-nested-mark-attributes/6596).
