### ISSUE TITLE
Unexpected backspace/delete key handling in nested lists

### ISSUE THREAD

**Issue by Kirkkt** [ProseMirror/prosemirror#1259]
Hi team ProseMirror,

We are Pitch are building our next-gen text editor using ProseMirror and it has been great. So first of all big kudos!!

However, we encountered some unexpected behaviors when pressing backspace/delete in nested lists.

Steps to repro:

1. go to https://prosemirror.net/
2. create some nested lists, like this one:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/10977790/161533015-181c9a89-eecf-4366-bdad-d1c5bc896e0c.png">

3. (see below)

### Issue 1: press delete or backspace on range selection, all bullet points stay
<img width="210" alt="image" src="https://user-images.githubusercontent.com/10977790/161533137-4ac497d2-bd7f-4953-89b8-6c448be303f0.png">

Expected: these 2 lines get removed, together with the bullet points

Actual: all bullet points stay

<img width="428" alt="image" src="https://user-images.githubusercontent.com/10977790/161533245-d69991f3-539c-4114-858e-cfcd57e1ea03.png">

### Issue 2: press delete or backspace on range selection, some bullet points stay
This is (I think) basically the same thing as issue 1, but more confusing for everyday users

<img width="435" alt="image" src="https://user-images.githubusercontent.com/10977790/161533474-f98807d0-a332-46e3-84f2-b7829259659a.png">

Expected: these 3 lines get removed, together with the bullet points

Actual: 1 bullet point stays

<img width="370" alt="image" src="https://user-images.githubusercontent.com/10977790/161533599-53d20d9a-b1b7-44a0-b207-3ba384c8cc12.png">

### Issue 3: put cursor at the end of a line and press delete, if the "join next line" op will break the scheme, the delete doesn't happen, and a chunk of list is selected below

<img width="447" alt="image" src="https://user-images.githubusercontent.com/10977790/161533803-977b365e-e9a1-46a5-92fc-1611be55dc4c.png">

Expected: well this is a bit hard to say, an everyday user might expect the list structure to be re-adjusted to allow this deletion, and I (who has played with ProseMirror for a few weeks) might expect at least nothing happens because it can be categorized as an "illegal" operation.

Actual: no deletion happens, and 4 lines below are selected

<img width="764" alt="image" src="https://user-images.githubusercontent.com/10977790/161534153-435cf41e-c1fb-4688-938f-ffdfdd455757.png">

### Issue 4: put cursor at the start of a line and press backspace, if the "join to prev line" op will break the scheme, the delete doesn't happen, and a chunk of list is selected below

<img width="320" alt="image" src="https://user-images.githubusercontent.com/10977790/161534303-634733d5-68d3-4afa-a56d-94b7f9a9d121.png">

Expected: similar to issue 3

Actual: no deletion happens, and the line above is selected

<img width="369" alt="image" src="https://user-images.githubusercontent.com/10977790/161534402-d1751a1a-0078-43a2-a30a-e1bdce19fee7.png">

I'm very satisfied and impressed by the richness and simplicity of ProseMirror, but list handling seems to have missed some love. Would you kindly take a look? Thank you very much.

**Comment by marijnh** [comment]
Because there are nested list items outside of the deleted range, which cannot exist without parent nodes, those list items must be preserved in order to satisfy the document shape prescribed by the schema. You could try add custom deletion logic that behaves differently, and bind it to the delete and backspace keys, but as for core library logic, this is expected behavior.

**Comment by Kirkkt** [comment]
Hi @marijnh thanks for the explanation.

I will add a custom delete/backspace command as you suggested, but there is still something I don't quite get:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/10977790/161550481-9197450b-9b1f-4534-85f4-2e978e135e87.png">

After you press backspace/delete you get:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/10977790/161550533-cfe83b88-aba0-4a14-be8e-ecc76476182f.png">

In this case, the second bullet point should be removed, right? It also conforms to the "no children without parent" rule and should satisfy the schema.

But here's something interesting: if you only partially select the second item, it works nicely:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/10977790/161550808-1b0adc2e-8f3b-4b93-93db-6aff5598906e.png">

After you press backspace/delete you get:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/10977790/161550853-4595a90a-c1df-45df-943a-fcdc2a93880e.png">

Is this a bug?

**Comment by marijnh** [comment]
That does seem surprising. Attached patch makes the two cases behave more consistently.
