### ISSUE TITLE
Bullet point stays after range-select-and-delete

### ISSUE THREAD

**Issue by Kirkkt** [ProseMirror/prosemirror#1260]
This is not the same but similar to https://github.com/ProseMirror/prosemirror/issues/1259#issuecomment-1087539617

If I range-select the first line partially and press delete/backspace, it works nicely

<details>
<summary>happy path - before</summary>

<img width="214" alt="image" src="https://user-images.githubusercontent.com/10977790/161985623-9b1d6ab6-80bc-4782-8f45-1004a99601c5.png">

</details>

<details>
<summary>happy path - after</summary>
<img width="168" alt="image" src="https://user-images.githubusercontent.com/10977790/161985803-a7bed8a1-0237-4361-a191-e43e3b64d716.png">

</details>

But if I range-select the entire first line and press delete/backspace, the first bullet point stays.

<details>
<summary>bug - before</summary>
<img width="274" alt="image" src="https://user-images.githubusercontent.com/10977790/161986210-1097326d-6e4f-4c4b-8892-246d09d00095.png">

</details>

<details>
<summary>bug - after</summary>
<img width="184" alt="image" src="https://user-images.githubusercontent.com/10977790/161986239-305a73c5-b78d-4929-8d7c-1a568da5a0cd.png">

</details>

It's a bit inconsistent with my expectation. Thanks and keep up the great work!

**Comment by Kirkkt** [comment]
Follow-up:

I noticed something quite interesting:

These two deletions result in empty bullet point being left hanging around:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/10977790/162288159-901de5ac-a2eb-4868-9da9-e29665239b43.png">

<img width="256" alt="image" src="https://user-images.githubusercontent.com/10977790/162288188-3cbc2fc7-ccc2-4880-9da9-d495d41b882d.png">

But if the selection is not extended to the entire line, everything is fine.

**Comment by marijnh** [comment]
Looks like I lost track of this. But indeed, that was buggy behavior. Attached patch should help.
