### ISSUE TITLE
prosemirror-state: Get name of created `PluginKey`

### ISSUE THREAD

**Issue by MikeYermolayev** [ProseMirror/prosemirror#1264]
Hello,

This is not a bug but rather a question.

When you create PluginKey it makes provided name unique and stores it in `key` property which is not documented as public one.

If `key` property is intended for private usage only what is the correct way to get generated plugin's key name?
Or should it be added to docs if it's supposed to be a public property?

Thank you

**Comment by marijnh** [comment]
It's not part of the public interface, but can be useful when debugging because it determines the property name used for this plugin in a state.

Please use the [forum](https://discuss.prosemirror.net) instead of the bug tracker for questions next time.
