### ISSUE TITLE
Plugins in DirectEditorProps should be marked as optional

### ISSUE THREAD

**Issue by cmlenz** [ProseMirror/prosemirror#1265]
The recently updated typings for `prosemirror-view` added the `plugins` field to the `DirectEditorProps` type, and did not mark that field optional, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59986.

That broke a lot of my code, so I checked the documentation and found that indeed the field is not declared as optional: https://prosemirror.net/docs/ref/#view.DirectEditorProps.plugins

But according to the implementation, the view will fallback to an empty array if the passed `plugins` is omitted: https://github.com/ProseMirror/prosemirror-view/blob/3c63b50e78b38707f7374dbf8c4d15074fb3e816/src/index.js#L33

I think the documentation should be clarified that the field is actually optional.

**Comment by marijnh** [comment]
Submit a PR to definitelytyped. I don't maintain these type definitions.

**Comment by marijnh** [comment]
Oh, right, the doc comment also gets it wrong. Attached patch should fix that.
