### ISSUE TITLE
Decoration issue with non-leaf inline nodes

### ISSUE THREAD

**Issue by thatsjonsense** [ProseMirror/prosemirror#1267]
We're running into the error `TypeError: Cannot read properties of undefined (reading 'nodeType')` when using a combination of node decorations and the [footnote example](https://prosemirror.net/examples/footnote/). The error comes from [this line](https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L502), and the problem seems to be that WidgetDesc is getting passed a node decoration:

![image](https://user-images.githubusercontent.com/2216153/166627568-d419a6c2-921e-4ee7-add4-add32df73df0.png)

This decoration is created via code that looks like:
```
decorations.push(
  Decoration.node(pos, pos + node.nodeSize, {
    class: `node-${node.type.name}`,
  })
)
...
return DecorationSet.create(doc, decorations)
```

Looking back up the tree, it's getting here because the `iterDeco` function is calling `onWidget` with something that is clearly not a widget (from !== to, no dom property):

![image](https://user-images.githubusercontent.com/2216153/166627651-9b076efc-87e9-4151-bd7a-89536d005410.png)

I'm having trouble understanding the code for iterDeco to know how this is supposed to work. Is there anything here that should prevent a non-widget deco from getting passed to onWidget? Should there perhaps be a guard for the decoration type here?

I did notice [this commit](https://github.com/ProseMirror/prosemirror-view/commit/5a0d0d4c28734652b6e8cdd5f5f774b8c9cf5627) which addressed a related problem. It sounds like there were issues with inline decorations on non-leaf inline nodes. Our problem is with _node_ decorations on non-leaf inline nodes. 

Sorry I can't provide more concrete repro steps. The error only happens with one very specific user's document, and we haven't been able to figure out why this particular doc is affected when the decorations work fine otherwise.

**Comment by marijnh** [comment]
Without a way to reproduce this, I don't think I can figure out what's causing this.

**Comment by andrey-skl** [comment]
@marijnh Hi! I faced the same issue, and I created a codesandbox that reproduces it. Could you please take a look?
https://codesandbox.io/s/laughing-rhodes-3p57nn?file=/src/editor/index.jsx

Note that error is gone once I change the end position of decoration (change 8 to another number), so it does not get to the edge of inline node:
<img width="1328" alt="Screenshot 2023-09-11 at 18 10 11" src="https://github.com/ProseMirror/prosemirror/assets/4318513/7bb97300-21e7-495e-b583-771b55ac1433">

**Comment by marijnh** [comment]
Thanks. That helped narrow it down. Attached patch should help.

**Comment by andrey-skl** [comment]
@marijnh Thank you, that was lightning-fast!
