### ISSUE TITLE
Copy/Paste HTML with Bullets and styled marks breaks

### ISSUE THREAD

**Issue by bdbch** [ProseMirror/prosemirror#1269]
Hey ProseMirror team. I received this issue in our Tiptap repository talking about a broken paste functionality when you partially copy a list containing specific marks for styling. The paste just breaks when the mark is copied too - if the mark is excluded from the selection everything works fine.

I think the whole issue is better explained with a video here:
https://github.com/ueberdosis/tiptap/issues/2783

I currently tested it with different font sizes or a bold mark.

**Comment by marijnh** [comment]
The HTML Google Docs produces there (once you strip off the styles and ids) comes down to

```html
<ul>
  <li>
    <p>
      <span>Bullet #1</span>
    </p>
  </li>
  <li>
    <p>
      <span>Bullet #2</span>
    </p>
  </li>
</ul>
<span>Nested </span> <span>Bullet</span> <span>#3 </span>
```

So ProseMirror's parsing of that seems reasonable, and isn't something that calls for a fix on our end.
