### ISSUE TITLE
`prosemirror-schema-list` should depend on `prosemirror-state`

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1274]
`prosemirror-schema-list` [imports](https://github.com/prosemirror/prosemirror-schema-list/blob/41f4a5e94b24921b422691febaccf3486b4960a5/src/schema-list.ts#L4) `Selection` from `prosemirror-state` and calls [`Selection.near`](https://github.com/prosemirror/prosemirror-schema-list/blob/41f4a5e94b24921b422691febaccf3486b4960a5/src/schema-list.ts#L144), so `prosemirror-state` should be added to `dependencies` in `prosemirror-schema-list`'s package.json.

**Comment by marijnh** [comment]
Indeed! Added in attached patch.
