### ISSUE TITLE
[docs] Transform.doc should be ProseMirror Node instead of DOMNode

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1275]
![CleanShot 2022-05-21 at 04 07 20](https://user-images.githubusercontent.com/24715727/169603309-eaef85fd-5b3e-4d0f-826d-6633694afd14.png)

**Comment by marijnh** [comment]
This patch should help: https://github.com/ProseMirror/website/commit/5801275ba16e7ad0d375552f4f157321b9885ef1
