### ISSUE TITLE
Inserting an emoji at the end of a paragraph throughs an error

### ISSUE THREAD

**Issue by luisateixeira** [ProseMirror/prosemirror#1276]
Inserting an emoji at the end of a paragraph throughs an error and emoji is removed from content. This happens if we insert the emoji using  Emoji & Symbols right-click context menu in any paragraph except the last one.

Tested in: Chrome 102.0.5005.61  in MacOS Mojave
Can be reproduced in the demo editor at https://prosemirror.net/

![Screen Recording 2022-05-27 at 11 45 AM](https://user-images.githubusercontent.com/1533325/170687095-35690f85-394c-4fef-9c91-31fca4b11b3e.gif)

**Comment by marijnh** [comment]
That context menu entry doesn't seem to be a standard Chrome feature. Is it coming from a plugin?

**Comment by luisateixeira** [comment]
Hi @marijnh . Forgot to mention that  I'm testing on a mac (already updated bug report description). Mac supports a keyboard shortcut to display the Emoji menu  and Chrome makes this option available through the browser's context menu.

**Comment by marijnh** [comment]
Ah, I see. Attached patch fixes the crash. (The feature still behaves weirdly, in that it joins the two paragraphs around the emoji, rather than just inserting it in the top paragraph, but that's not ProseMirror's fault.)
