### ISSUE TITLE
declares 'Command' locally, but it is not exported.

### ISSUE THREAD

**Issue by gopal-augment** [ProseMirror/prosemirror#1277]
_import { Command } from 'prosemirror-commands';
           ~~~~~~~
node_modules/prosemirror-commands/dist/index.d.ts:2:10
'Command' is declared here.
node_modules/ngx-editor/lib/commands/Link.d.ts:2:10 - error TS2459: Module '"../../../prosemirror-commands/dist"' declares 'Command' locally, but it is not exported._



facing the above issue for angular 9.1.15.

**Comment by marijnh** [comment]
Import it from prosemirror-state instead.

**Comment by gopal-augment** [comment]
This happened from the latest version of _prosemirror_

**Comment by gopal-augment** [comment]
> Import it from prosemirror-state instead.

This happened from the latest version of _prosemirror_. The same code was working fine before the latest version. @marijnh

**Comment by marijnh** [comment]
There is no package named 'prosemirror'. There's prosemirror-commands, which does not export `Command`, and prosemirror-state, which does. The 3rd party types apparently put `Command` in another package than the current types. You're going to have to adjust your code.
