### ISSUE TITLE
Typescript compile failed prosemirror-model@1.8.0 

### ISSUE THREAD

**Issue by zunsthy** [ProseMirror/prosemirror#1283]
### Problem Information

Using the latest version prosemirror dependencies in my project and TS compiler wiil throw errors.

Error TS7030 and TS7023 from prosemirror-model@1.8.0 

> ./node_modules/prosemirror-model/src/from_dom.ts(211,3): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/from_dom.ts(228,3): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/from_dom.ts(366,3): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/from_dom.ts(739,3): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/from_dom.ts(812,10): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/from_dom.ts(817,43): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/from_dom.ts(829,10): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/schema.ts(294,34): error TS7030: Not all code paths return a value.
> ./node_modules/prosemirror-model/src/schema.ts(601,3): error TS7023: 'nodeFromJSON' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

### Steps to Reproduce 

```bash
# clone project 
git clone --depth=1 https://github.com/ProseMirror/prosemirror-model.git
cd prosemirror-model

# install deps
npm i

# exec tsc 
echo '{"compilerOptions":{"outDir":"dist","rootDir":"src"},"include":["src"]}' > tsconfig.json
npx tsc --noEmit --target es6 --allowSyntheticDefaultImports --noImplicitReturns
```

**Comment by zunsthy** [comment]
@marijnh this throw errors in other dependent projects. the method shouldn't use return type impictly.

"src/schema.ts" Line 601 
```ts
nodeFromJSON(json: any): Node 
```

**Comment by marijnh** [comment]
I don't see how that can throw errors in other projects, since those will be using the .d.ts file. Attached patch adds the type here, since indeed TypeScript seems to be oddly unable to infer it.
