### ISSUE TITLE
Can't compile without unwanted tsconfig flag: allowSyntheticDefaultImports (OrderedList import bug)

### ISSUE THREAD

**Issue by jpduckwo** [ProseMirror/prosemirror#1284]
This seems to be related to the way prosemirror-schema-list is importing from OrderedList or the way OrderedList is exporting.

I'm running an angular v14 project that has the following dependencies:

```
        "prosemirror-schema-list": "1.2.0",
```
 When compiling using the tsconfig:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

**Gives:**

```
Error: node_modules/prosemirror-model/dist/index.d.ts:1:8 - error TS1259: Module '"dev/ng14test1/node_modules/orderedmap/dist/index-cjs"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import OrderedMap from 'orderedmap';
         ~~~~~~~~~~

  node_modules/orderedmap/dist/index-cjs.d.ts:31:1
    31 export = OrderedMap
       ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.


Error: node_modules/prosemirror-schema-list/dist/index.d.ts:2:8 - error TS1259: Module '"dev/ng14test1/node_modules/orderedmap/dist/index-cjs"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

2 import OrderedMap from 'orderedmap';
         ~~~~~~~~~~

  node_modules/orderedmap/dist/index-cjs.d.ts:31:1
    31 export = OrderedMap
       ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.


Error: node_modules/prosemirror-state/dist/index.d.ts:3:41 - error TS2307: Cannot find module 'prosemirror-view' or its corresponding type declarations.

3 import { EditorProps, EditorView } from 'prosemirror-view';
```

It works if `allowSyntheticDefaultImports: true` is added to the compilerOptions. However it think it should support typescript compiling without this flag.

### To reproduce:

`npx --package=@angular/cli@v14 -- ng new ng14test1`
`cd ng14test1`
`npm install prosemirror-schema-list prosemirrror-view`
add `import * as pm from 'prosemirror-schema-list';` to src/app/app.component.ts
run `npm start`

### Environment
```
➜  ng14test1 (master) npm -v                                                                             ✭
8.5.5
➜  ng14test1 (master) node -v                                                                            ✭
v16.15.0
➜  ng14test1 (master)
```

**Comment by marijnh** [comment]
Yeah, this is a mess. The person who published the original 3rd-party types for orderedmap, for some reason, went with the `export =` syntax in the type declarations, causing all code depending on that to use `import x = require(...)` syntax, which breaks if the dependency switches to regular ES `export` declarations. I've made several attempts to upgrade orderedmap without breaking users' build setups (see https://github.com/marijnh/orderedmap/issues/11), but with no luck. This flag is a kludge to try and paper over that weird historic artifact, but I guess it's not working very well.

So I guess we'll bite the bullet and move orderedmap to 2.0.0, fixing the declarations. I'm sure this will also break someone's setup, but at this point they'll just have to upgrade.

**Comment by jpduckwo** [comment]
Thanks Marijn, that makes sense, I agree what you've done is the only way forward now
