### ISSUE TITLE
Some internal types maybe should be public

### ISSUE THREAD

**Issue by percy507** [ProseMirror/prosemirror#1285]
Hi @marijnh,

Should below internal types be public?

- [SelectionRange's constructor](https://github.com/ProseMirror/prosemirror-state/blob/master/src/selection.ts#L209)

  - use case: [prosemirror-table's CellSelection](https://github.com/ProseMirror/prosemirror-tables/blob/master/src/cellselection.js#L42)

- [Fragment's content](https://github.com/ProseMirror/prosemirror-model/blob/master/src/fragment.ts#L18)

  - use case: for counting the cells in table

  ```ts
  export function countCells(state: EditorState) {
    const { table } = selectedRect(state);
    let cellCount = 0;
    for (let n = 0; n < table.childCount; n++) {
      cellCount += table.content.content[n].childCount;
    }
    return cellCount;
  }
  ```

- [EditorView's domObserver](https://github.com/ProseMirror/prosemirror-view/blob/master/src/index.ts#L55)

  - use case: for preventing flush DOM immediately on CellSelection of table
  - How about add a property `jsonID?: string` for [Selection](https://github.com/prosemirror/prosemirror-state/blob/master/src/selection.ts#L9)? It's very useful for identify the type of a selection.

  ```ts
  contextmenu: (view, e) => {
    const composedPaths = e.composedPath();
    e.preventDefault();
    e.stopPropagation();
    // prevent flush DOM immediately on CellSelection of table
    if (view.state.selection.jsonID === 'cell') view.domObserver.flushingSoon = 1;
    setTimeout(() => {
      // showContextMenu()
      view.domObserver.flushingSoon = -1;
    }, 10);
    return true;
  }
  ```

**Comment by marijnh** [comment]
> [SelectionRange's constructor](https://github.com/ProseMirror/prosemirror-state/blob/master/src/selection.ts#L209)

Agreed, that makes sense.

> [Fragment's content](https://github.com/ProseMirror/prosemirror-model/blob/master/src/fragment.ts#L18)

Use the `child`/`maybeChild` methods.

> [EditorView's domObserver](https://github.com/ProseMirror/prosemirror-view/blob/master/src/index.ts#L55)

That's intentionally private. I'm not sure why you need this for CellSelection. Could you elaborate?

> How about add a property jsonID?: string for [Selection](https://github.com/prosemirror/prosemirror-state/blob/master/src/selection.ts#L9)? It's very useful for identify the type of a selection.

Doesn't `instanceof` cover that?

**Comment by percy507** [comment]
> That's intentionally private. I'm not sure why you need this for CellSelection. Could you elaborate?

I want show a contextmenu when select table cells, then I can merge the cells or apply attrs for the cells. If I don't do the thing as ablove code showing through `view.domObserver.flushingSoon`, then the cellselection will disappear immediately after trigger a contextmenu event.

> Doesn't `instanceof` cover that?

Of course, `instanceof` works, but use the hidden `jsonID`property maybe more convenient in some case.

**Comment by marijnh** [comment]
Is the issue that opening the context menu changes the DOM selection, which causes ProseMirror to clear its own selection? If so, could that be worked around by restoring the previous ProseMirror selection?

**Comment by percy507** [comment]
I am not sure, restoring the CellSelection seems not easy😂. But it's ok to keep it internal, I can use `@ts-ignore` ignore it.
