### ISSUE TITLE
Unable to select table cells

### ISSUE THREAD

**Issue by anton-liubushkin** [ProseMirror/prosemirror#1286]
I encountered a problem after updating prosemirror-state from 1.3.4 to 1.4.0.

When I try to select cells in a table, an error appears: Cannot call a class constructor without [new]

<img width="384" alt="Screen Shot 2022-06-16 at 3 15 36 PM" src="https://user-images.githubusercontent.com/5649032/174067567-989f0db8-f850-422c-b652-7d169211dc70.png">

**Comment by DioNNiS** [comment]
+1

**Comment by amursky** [comment]
I have the same issue.

**Comment by marijnh** [comment]
The ES modules distributed by ProseMirror now use ES6 `class` syntax. This means you can't subclass them from ES5-compiled `function` classes. You'll have to either not compile your own code down, or make sure you compile the ProseMirror libraries down, or use the CommonJS modules in the ProseMirror packages, which are still ES5.
