### ISSUE TITLE
Empty `DecorationSet` breaks in `prosemirror-view@^1.24.0`

### ISSUE THREAD

**Issue by nfantone** [ProseMirror/prosemirror#1287]
Versions `1.23.13` and earlier of `prosemirror-view`, before the migration to TS, contained [this check](https://github.com/ProseMirror/prosemirror-view/blob/1.23.13/src/decoration.js#L234) in the `DecorationSet` constructor which allowed instantiating empty sets. Versions `^1.24.0` did [away with that](https://github.com/ProseMirror/prosemirror-view/blob/master/src/decoration.ts#L276), breaking existing plugins that depended on it, [such as `prosemirror-invisibles`](https://github.com/guardian/prosemirror-invisibles/blob/master/src/ts/index.ts#L22).

Unsure if `prosemirror` is following strict semantic versioning, but this was a breaking API change published as a minor bump. Was there a reason for this? Could it possibly be reverted?

Many thanks!

**Comment by marijnh** [comment]
That constructor was never public, so I don't consider changing its signature to be a breaking change. Use `DecorationSet.empty`.
