### ISSUE TITLE
posAtCoords returning position after node, not before

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#1288]
Looks like there were some recent changes that appeared to have been introduced after the Typescript refactor. I need to create a repro case but we are seeing a bit of a fallout on posAtCoords after upgrading. We have a plugin for handling contextmenu events

```ts
                contextmenu(view, event: MouseEvent) {
                    let contextPos = view.posAtCoords({ left: event.clientX, top: event.clientY });
```

However, the position that is returning seems to now be "after" the node that was clicked and not before. Previously, posAtCoords was returning the position right before the corresponding node.

I'm not sure what changed but we are seeing this consistently across pretty much all of our node types.

This is happening on Chrome with  prosemirror-view 1.26.2. I haven't tried on Firefox or Safari yet.

**Comment by jljorgenson18** [comment]
Here is a repro case. Just need to add an image and right click on it https://glitch.com/edit/#!/dark-icy-beryl?path=index.js%3A18%3A17

**Comment by jljorgenson18** [comment]
I'm not sure but it seems like the problem might be that "offset" in posAtCoords is now initialized with 0, which means that this condition https://github.com/ProseMirror/prosemirror-view/commit/75cc0064497f2a95a7532721d26b66d179b5676f#diff-8711f18f44af6275714f55277ddd18fb124ab348b03cd4b86a4fdb253b205330R299 will be hit more frequently.

If this was how posAtCoords was always intended (considering you technically often are closer to the position being returned), then I could see that making sense and we could just try to use "inside" in combination with "pos." Still, it seems a bit funky that "inside" can point to a position before "pos" and the logic becomes a bit convoluted as you need special case -1 with a min function.

**Comment by marijnh** [comment]
Clicking on the left half of the image yields the position before it, clicking on the right half the position after. This is intended behavior. Read the [docs](https://prosemirror.net/docs/ref/#view.EditorView.posAtCoords) on what inside means—it's perfectly reasonable for it to be before `pos`. Does that clear this up?

**Comment by jljorgenson18** [comment]
Yes that was my initial reading of the posAtCoords, but that does not seem to be how it worked up until the Typescript refactor. If this is how it should work going forward, then we can adjust our code and use "inside" a lot more. I primarily just wanted to clarify and see if the change was intentional.
