### ISSUE TITLE
Widget decoration causes node duplication when typing dead-letters

### ISSUE THREAD

**Issue by tommoor** [ProseMirror/prosemirror#1289]
### Bug

I have a widget decoration that is only rendered next to empty paragraphs, when a character is typed the decoration is removed. (For context, It acts as a button to insert content into empty lines). 

When typing a diacritic using a dead-letter it results in duplication of the line below. Something about the DOM diffing is not accounting for this case perhaps?

### Reproduction

- Open remix: https://elegant-periwinkle-thursday.glitch.me/
- Insert a new line at the top and see the widget appear
- Type a dead letter as the first character in the empty paragraph (On macOS you can use `Option`+`I`)
- The line below duplicates

A video of the above behavior, note that typing the dead-letter in a position other than the first character in the paragraph does not reproduce:

https://user-images.githubusercontent.com/380914/175768119-fcd0518a-3dea-4bf5-915c-b2c4f64a2a57.mp4

**Comment by marijnh** [comment]
Which browser does this happen in?

**Comment by marijnh** [comment]
Oh, right, I can reproduce it now. Continued typing before, and didn't notice, due to the layout shifting, that the duplicated paragraph immediately vanished again.
