### ISSUE TITLE
Make marks more consistent?

### ISSUE THREAD

**Issue by rexxars** [ProseMirror/prosemirror#129]
I'm trying to persist ProseMirror documents to a database, and I'm having a bit of trouble because  `marks` can be either a string or an object (in the case of links, for instance).

Is there any specific reason why you decided not to have all marks as objects? This would make it easier to parse in stricter languages as well, I would assume.

**Comment by marijnh** [comment]
This is just in the JSON serialization format (to make it somewhat smaller and easier to read for humans). You may consider a string `"foo"` to be equivalent to the object `{"_": "foo"}`

**Comment by rexxars** [comment]
Is there any chance this could be changed to be more consistent? I suppose I could write my own serialization format, or convert them before persisting and changing them back before loading them into ProseMirror, but it just seems like it would be easier if they were consistent in the first place.

**Comment by marijnh** [comment]
Could you describe why, exactly, the current format is causing problems for you?

**Comment by rexxars** [comment]
It's mostly about strict types. My particular case right now is persisting the document in elasticsearch, but there are more than one case where I can see it being cumbersome:

* I'm trying to persist this in ElasticSearch, which encounters an array of strings and infers a type based on it. Later on it encounters an object in the array, which makes the indexing fail. To work around this, I'd have to explicitly tell ElasticSearch to not index marks.

* Making a schema based on the document structure would be harder. Consider for instance creating a GraphQL API that can query a document structure. `marks` couldn't be defined to be `string` or `object`, and polymorphism isn't supported

*  Validating a posted document structure through something like JSONSchema would be harder, as you'd have to add special cases for this field

* In strictly typed languages such as Java, reading the data as JSON is harder: `org.json.JSONArray` exposes methods such as `getString()` and `getJSONObject()`. In this case, you'd probably have to try and get it as a string, perhaps wrapping it in a try/catch and instead trying to parse it as a JSON object.

**Comment by alerque** [comment]
I would add that having a consistent type of "object" here gives a place on which to hang other meta data on about the mark down the road and either extend ProseMirror or just persist in storage independently from it.

**Comment by rexxars** [comment]
It'd be nice if the `_` property actually had a name, as well. I realize that this kind of "bloats" the document format a little, but it makes it much more consistent and workable.

**Comment by marijnh** [comment]
I figured most schema definition languages would provide some equivalent of [`anyOf`](http://json-schema.org/latest/json-schema-validation.html#anchor85), but I guess that if tools aren't handling this well, that is an issue.

I made this decision based on the fact that step (change) objects, which are being sent around all the time during collaborative editing, will often end up containing a lot of these.  `{"name": "strong"}` is a bit more data than `"strong"`, but I guess that's still not a huge overhead.

Is the aggressive omission of properties that contain only default/empty data also going to cause problems for you? (Because not doing that *would* cause a lot of overhead.)

**Comment by rexxars** [comment]
I'm not sure if I understand what you mean by "aggressive omission", do you have any example of which properties you are talking about?

In general, the only two things that cause problems for us right now is properties having different data types (string vs objects in marks) and the name `_` being used as a property name. Simply changing all marks to follow the pattern of `{ type: "strong" }` and `{ type: "link", href: "http://github.com" }` for instance makes our lives a whole lot better :)

**Comment by marijnh** [comment]
Nodes without attributes, marks, or content won't get `attrs`, `marks`, or `content` properties. Similarly, in step object JSON, everything that can be defaulted is left off. (Also, those define a different structure for each step type, which again doesn't fit the naive 'a property always means the same thing' model.)

**Comment by rexxars** [comment]
Leaving empty/default value properties out causes no problems for us. I have yet to look in to the step type and what the structure of that would look like, but I doubt we'd be persisting this or using it in a way that it'd cause problems for us.

**Comment by marijnh** [comment]
Attached patch makes the representation for a mark always an object. Attribute-less marks are now something like `{"_": "strong"}`. The underscore was kept to distinguish the name field from a potential attribute called `name`.

**Comment by kiejo** [comment]
I just tried upgrading to the latest development version of ProseMirror and noticed that this change makes loading ¨old¨ documents that contain marks fail.
Even though I like the new consistent behavior, I am wondering if it would be possible to keep the string handling in ```markFromJSON``` for backwards compatibility. Or is there another preferred/suggested way of upgrading to the new version?

**Comment by marijnh** [comment]
I've made release 0.2.0 accept the old data. The next release won't anymore, so be sure to round-trip your JSON through 0.2.0 at least once before upgrading.

**Comment by kiejo** [comment]
Ok, thanks a lot!
