### ISSUE TITLE
TypeScript: Type handleDOMEvents does not match

### ISSUE THREAD

**Issue by MH4GF** [ProseMirror/prosemirror#1294]
An error message is displayed indicating a type mismatch, even though `handleDOMEvents` is satisfied.
https://prosemirror.net/docs/ref/#view.EditorProps.handleDOMEvents

```typescript
const myPlugin = new Plugin({
  props: {
    // Type '{ mousedown: (_view: EditorView, _event: MouseEvent) => true; }' is not assignable to type '{ [x: string]: ((view: EditorView, event: Event) => boolean | void) | undefined; fullscreenchange?: ((view: EditorView, event: Event) => boolean | void) | undefined; ... 98 more ...; wheel?: ((view: EditorView, event: WheelEvent) => boolean | void) | undefined; }'.
    //  Property 'mousedown' is incompatible with index signature.
    //  Type '(_view: EditorView, _event: MouseEvent) => true' is not assignable to type '(view: EditorView, event: Event) => boolean | void'.
    //    Types of parameters '_event' and 'event' are incompatible.
    //      Type 'Event' is missing the following properties from type 'MouseEvent': altKey, button, buttons, clientX, and 21 more.ts(2322)
    handleDOMEvents: {
      mousedown: (_view, _event) => {
        return true;
      },
    },
  },
});
```

demo: https://github.com/MH4GF/prosemirror-handle-dom-events-bug-demo

Perhaps this discussion is relevant:
https://github.com/ProseMirror/prosemirror-view/pull/129#issuecomment-1153864095

**Comment by marijnh** [comment]
The problem seems to be that function types with more specific argument types are *not* subtypes of functions with less specific argument types (i.e. `(e: MouseEvent) => void` isn't a subtype of `(e: Event) => void`, because it accepts a smaller range of arguments). I've changed the type of unknown event objects to `any` to avoid this problem.

**Comment by MH4GF** [comment]
I have confirmed that it works in my environment. Thanks for the job!
