### ISSUE TITLE
Toggling link mark duplicates next typed full-angle character

### ISSUE THREAD

**Issue by hamflx** [ProseMirror/prosemirror#1296]
reproduction link: <https://prickly-gamy-grandiflora.glitch.me/>, <https://glitch.com/edit/#!/prickly-gamy-grandiflora?path=index.js%3A21%3A0>

1. Focus the cursor to the end of the editor
2. Type a full-angle character "，"
3. It will appear twice: "，，"

**Comment by marijnh** [comment]
Which browser are you using and how are you typing the character?

**Comment by marijnh** [comment]
Odd. On my Windows 7 virtual machine, win+; does nothing, but typing a comma with Microsoft Pinyin IME just inserts a single full-width comma, and doesn't show any problem.

**Comment by hamflx** [comment]
I have tried Chro**mium** 77.0.3865.0 x64 with no problems.

**Comment by hamflx** [comment]
Chrome 94.0.4606.54 x64: problem
Chrome 89.0.4389.90 x64: problem
Chro**mium** 87.0.4280.0 x64: problem
**Chromium 86.0.4240.183 x64: problem**, download link: <https://chromium.cypress.io/win64/stable/86.0.4240.183>
Chro**mium** 85.0.4183.0 x64: no problem
Chrome 81.0.4044.129 x64: no problem

**Comment by marijnh** [comment]
I was testing with a Chrome 103 as well. Tried a while to do this repeatedly to see if I could get it to happen, but still no luck.

**Comment by hamflx** [comment]
Would you please use win10 to test it? It seems to be a bug only on win10, and I have not reproduced the problem with win7.

**Comment by hamflx** [comment]
I can provide an installed Win10 cloud virtual machine. I can email you the rdp address for it if you don't mind.

**Comment by hamflx** [comment]
You can also use this bt download link to download the official installation image of Win10 (but it is in Chinese):

```plaintext
magnet:?xt=urn:btih:740bc41e5f9d30fe054c50393a2a216c79659539&dn=zh-cn_windows_10_consumer_editions_version_21h2_updated_june_2022_x64_dvd_469593c1.iso&xl=6004480000
```

**Comment by marijnh** [comment]
I've managed to set up a Win10 VM, and found out what was happening there (indeed straightforward to reproduce on that OS). Attached patch should help.

**Comment by hamflx** [comment]
Thanks for your job.

But there is still a problem here, if there is still text after the cursor, the cursor may move forward one character after the full-width character is typed.

For example, before typing is:

![image](https://user-images.githubusercontent.com/13356747/177916334-4fc19731-d724-4e2e-a9be-7fc5f2681915.png)

After typing a full-width character:

![image](https://user-images.githubusercontent.com/13356747/177916377-0ad5bbd8-f8c6-4039-806b-9a996361b8d3.png)

**Comment by marijnh** [comment]
Does attached patch improve the situation for you?

**Comment by hamflx** [comment]
The problem still exists. Most of the time there is a problem, occasionally there is no problem when hitting the if statement.

![image](https://user-images.githubusercontent.com/13356747/185914748-8bcb001e-1240-4f34-ba9a-cb29feb460c8.png)
