### ISSUE TITLE
Possible to add a blockquote inside a list Item?

### ISSUE THREAD

**Issue by KyleMit** [ProseMirror/prosemirror#1297]
Issue is visible in the [basic demo](https://prosemirror.net/examples/basic/) - ([example glitch](https://glitch.com/~prosemirror-basic-example-remix))

If you are editing a list item, the quote menu button disappears

![image](https://user-images.githubusercontent.com/4307307/177579739-cb00798b-8f46-4c28-b1ad-02b304b742db.png)

Here's the relevant callstack:

* [**prosemirror-example-setup** / `menu.ts`](https://github.com/ProseMirror/prosemirror-example-setup/blob/master/src/menu.ts#L198)
* [**prosemirror-menu** / `menu.ts`](https://github.com/ProseMirror/prosemirror-menu/blob/master/src/menu.ts#L56)
* [**prosemirror-commands** / `commands.ts`](https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.ts#L456)
* [**prosemirror-transform** / `structure.ts`](https://github.com/ProseMirror/prosemirror-transform/blob/master/src/structure.ts#L63)

```ts
// menu.ts
/// Given a schema, look for default mark and node types in it and
/// return an object with relevant menu items relating to those marks.
export function buildMenuItems(schema: Schema): MenuItemResult {
    // ...
    r.wrapBlockQuote = wrapItem(node, {
        title: "Wrap in block quote",
        icon: icons.blockquote
    })

/// Build a menu item for wrapping the selection in a given node type.
/// Adds `run` and `select` properties to the ones present in
/// `options`. `options.attrs` may be an object that provides
/// attributes for the wrapping node.
export function wrapItem(nodeType: NodeType, options: Partial<MenuItemSpec> & {attrs?: Attrs | null}) {
    let passedOptions: MenuItemSpec = {
      // ...
      select(state) {
        return wrapIn(nodeType, options.attrs)(state)
      }

// menu.ts
/// An icon or label that, when clicked, executes a command.
export class MenuItem implements MenuElement {
    // ...
    function update(state: EditorState) {
      if (spec.select) {
        let selected = spec.select(state)
        dom!.style.display = selected ? "" : "none"


// command.ts
/// Wrap the selection in a node of the given type with the given attributes.
export function wrapIn(nodeType: NodeType, attrs: Attrs | null = null): Command {
    return function(state, dispatch) {
        let {$from, $to} = state.selection
        let range = $from.blockRange($to),
            wrapping = range && findWrapping(range, nodeType, attrs)
        if (!wrapping) return false

           
// structure.ts         
/// Try to find a valid way to wrap the content in the given range in a
/// node of the given type. May introduce extra nodes around and inside
/// the wrapper node, if necessary. Returns null if no valid wrapping
/// could be found. When `innerRange` is given, that range's content is
/// used as the content to fit into the wrapping, instead of the
/// content of `range`.
function findWrapping(range, nodeType, attrs = null, innerRange = range) {
    let around = findWrappingOutside(range, nodeType);
    let inner = around && findWrappingInside(innerRange, nodeType);
```

My understanding is that this is failing at `findWrapping` which is there to:

> Try to find a valid way to wrap the content in the given range in a node of the given type

Meaning there is no valid way to blockquote inside a list item.

### For two possible solutions

1. I think it'd probably look weird to add inline, but don't really care if users want to do that.  But even if I force the menu item to be visible, it'll still run into the same problem applying the blockquote because it can't find a way to do that.

2. Another option is to enter a newline and add the blockquote in a paragraph child of the list item.  Users can manually do this now (entering the newline themselves), but is there any way to preserve the blockquote toggle and apply the newline transform prior to inserting the blockquote.

Any thoughts or advice on how I might best proceed?

Thanks Kindly

**Comment by marijnh** [comment]
This depends on the schema. It's common for schemas to require the first block in a list item to be a plain paragraph, in which case you won't be able to wrap it in a quote. But if you allow any block there the button should become available.
