### ISSUE TITLE
liftListItem lifts items out from the same level into the new list

### ISSUE THREAD

**Issue by MRJCrunch** [ProseMirror/prosemirror#1306]
I still reproduce the issue https://github.com/ProseMirror/prosemirror/issues/793

It is the record from the https://prosemirror.net/examples/basic/

https://user-images.githubusercontent.com/17198997/187721126-882a15b3-b034-4af8-9910-33ef6045b116.mov

<img width="200" alt="image" src="https://user-images.githubusercontent.com/17198997/187721416-3ba6af8f-3de0-47ec-a7cd-f789fd2b1966.png">

I use `"prosemirror-schema-list": "1.2.0"`

**Comment by marijnh** [comment]
Are you sure you're running `liftListItem` here? Because that menu item in example-setup is simply bound to `lift`.

**Comment by MRJCrunch** [comment]
Yes, in my project I use `liftListItem` and result is the same

**Comment by marijnh** [comment]
Can you submit a test case that can be added to test/test-commands.ts in the prosemirror-schema-list repository that demonstrates this issue? I tried to create one from your screencast, but the command behaved as intended there.

**Comment by MRJCrunch** [comment]
I've created a test case here: https://github.com/ProseMirror/prosemirror-schema-list/pull/9

So from my point of view lifting the list from this state
![image](https://user-images.githubusercontent.com/17198997/189051686-62fbd1d9-b164-47d2-81b8-2458c57d713f.png)

```html
<ol>
  <li>
    <p>a</p>
    <ol>
      <li>
        <p>b</p>     <!-- lift this node -->
        <ol>
          <li>
            <p>c</p>
          </li>
        </ol>
      </li>
      <li>
        <p>d</p>
      </li>
    </ol>
  </li>
  <li>
    <p>e</p>
  </li>
</ol>
```

should work like this
![image](https://user-images.githubusercontent.com/17198997/189052105-418024f9-f1b7-43d6-92fc-aae4329177f8.png)

```html
<ol>
  <li>
    <p>a</p>
  </li>
  <li>
    <p>b</p>
    <ol>
      <li>
        <p>c</p>
      </li>
      <li>
        <p>d</p>
      </li>
    </ol>
  </li>
  <li>
    <p>e</p>
  </li>
</ol>
```

but it works like this
![image](https://user-images.githubusercontent.com/17198997/189052936-1c957619-41e6-406b-8ffd-a5d7c083e70a.png)

```html
<ol>
  <li>
    <p>a</p>
  </li>
  <li>
    <p>b</p>
    <ol>
      <li>
        <p>c</p>
      </li>
    </ol>
    <ol>
      <li>
        <p>d</p>
      </li>
    </ol>
  </li>
  <li>
    <p>e</p>
  </li>
</ol>

```

**Comment by marijnh** [comment]
Thanks, that clarified it. Attached patch should help.

**Comment by Benbinbin** [comment]
But it seems [the check condition](https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.ts#L212) using the `canJoin` method only consider if these two lists children can match

so it can cause the unexpected join behavior, like join the ordered list and the bullet list

![Image](https://github.com/user-attachments/assets/1a661542-46f4-443c-b87f-a5fb904904a4)

maybe we should also check the list type before and after the join pos

```diff
- if (canJoin(tr.doc, after)) tr.join(after)
+ const $checkPos = tr.doc.resolve(after);
+ if($checkPos.nodeBefore && $checkPos.nodeBefore.type.name === $checkPos.nodeAfter.type.name && canJoin(tr.doc, after)) tr.join(after)
```

**Comment by marijnh** [comment]
Attached patch adds a check like that.
