### ISSUE TITLE
InvalidStateError: extend() requires a Range to be added to the Selection

### ISSUE THREAD

**Issue by dannymickleburgh-qz** [ProseMirror/prosemirror#1308]
Hi ProseMirror team, we've been seeing quite a few `InvalidStateError: extend() requires a Range to be added to the Selection` errors in Rollbar. This seems to only be affecting Safari 15.6.* on desktop. We've tried everything to recreate but have not had any success. I don't believe it is adversely affecting our users. 

This occurs in `./node_modules/prosemirror-view/dist/index.js893:14 in [anonymous]` in our build. I'm assuming prosemirror-view or prosemirror-state could be the culprits but I don't see an explicit RangeError thrown for `extend() requires a Range to be added to the Selection`.

Also, here is a list of our current versions for context:
```
├─ @types/prosemirror-commands@1.0.3
├─ @types/prosemirror-history@1.0.1
├─ @types/prosemirror-keymap@1.0.3
├─ @types/prosemirror-model@1.7.4
├─ @types/prosemirror-state@1.2.5
├─ @types/prosemirror-transform@1.1.1
├─ @types/prosemirror-view@1.15.1
├─ prosemirror-commands@1.1.7
├─ prosemirror-history@1.0.4
├─ prosemirror-keymap@1.1.4
├─ prosemirror-model@1.7.0
├─ prosemirror-state@1.3.4
├─ prosemirror-transform@1.1.3
└─ prosemirror-view@1.9.10
```

Any help would be greatly appreciated!

**Comment by marijnh** [comment]
See also https://github.com/codemirror/dev/issues/940 . This sounds like a recent regression in Safari where `Selection.collapse` can somehow leave the selection without ranges in it. I haven't managed to reproduce it yet to properly figure out what might be happening, though.

**Comment by marijnh** [comment]
We figured out the root of the CodeMirror issue, and I've applied the same patch here.
