### ISSUE TITLE
Delete key seems to remove some of following nodes

### ISSUE THREAD

**Issue by bdbch** [ProseMirror/prosemirror#1309]
Hey! We received an issue over at Tiptap about the delete key removing nodes on the next line. As far as I could reproduce this it's effecting lists and block quotes.

https://user-images.githubusercontent.com/6538827/189520995-5172c11c-973e-4f6c-8d5e-6c4d304d31c4.mp4

Here is a video showcasing, that putting the cursor on an empty line before a list or blockquote and pressing the delete key will in fact remove the list item or blockquote on the next line. This does not happen with headlines or code blocks. So far I didn't test any further elements.

Do you have any idea how to avoid this behaviour? You can test it yourself on the basic example page:
https://prosemirror.net/examples/basic/

**Comment by marijnh** [comment]
That's intentional behavior of the `joinForward` command. Pressing delete if the node ahead can be unwrapped will first unwrap it, pressing it again when there's nothing left to unwrap will join the textblocks.

**Comment by rfgamaral** [comment]
> That's intentional behavior of the `joinForward` command. Pressing delete if the node ahead can be unwrapped will first unwrap it, pressing it again when there's nothing left to unwrap will join the textblocks.

Is it possible to override this behaviour, and have pressing `delete` skip the unwrapping, and go straight to "join the text blocks"?

**Comment by marijnh** [comment]
You could implement another command to bind to Delete, possibly just implementing specific joining of textblocks and leaving the default command as a fallback with a lower precedence.
