### ISSUE TITLE
Safari selection and caret issue inside Shadow dom

### ISSUE THREAD

**Issue by roman-kulakov** [ProseMirror/prosemirror#1310]
I have several issues while using prosemirror on Safari inside shadow dom.

1. Impossible to change caret position and type smth

Steps to reproduce:
- type text
- move caret to the middle of the text
- type smth

ER: new text types in the new position
AR: only one letter types in the new position and then caret jumps to the end of the text.

2. Impossible to make text bold/italic

Steps to reproduce:
- select text in the editor
- press bold or italic

ER: text becomes bold or italic
AR: nothing happens

Repo: [repo](https://glitch.com/edit/#!/courageous-stealth-marquess)
Safari desktop version: 15.5

I am aware of those 2 issues:
#476 
[Safari's Selection is broken in shadow roots](https://github.com/codemirror/dev/issues/414)

Not sure if this duplication or not, but it would be good to understand where we stand here. As I understand there is a possible solution that could be ported from `codemirror`.

**Comment by marijnh** [comment]
Yes, this sounds like #476. The hack used in CodeMirror could probably be applied in ProseMirror, but would involve a bunch of restructuring, and I haven't gotten around to it yet. Closing this as duplicate.
