### ISSUE TITLE
 Incorrect undo behaviour for Chineses Characters [Need Help] Thx very much! 

### ISSUE THREAD

**Issue by Matrixbirds** [ProseMirror/prosemirror#1311]
### What’s the bug you are facing?
When inputing a Chinese word, the user first spell them in English letters, and then select the Chinese word with the help of input method, as the gif shows. But after inputing a Chinese word, when the user hit undo(Command/Ctrl+Z), the inputed content is reverted to the English letters, while we expect it to be empty.

### How can we reproduce the bug on our side?
Use offical prosemirror [demo ](https://prosemirror.net/).

### Reproduce steps 
GIF of prose mirror
![82dca2e42bee9a402b31332201921e3644c1f882](https://user-images.githubusercontent.com/9990676/191192424-395fa88e-1d32-42e4-b380-76c5932b818b.gif)
This behaviour is sensitive to the speed of inputing. If the use input it quickly, the undo is correct. But if the user input slowly, the undo is not correct.

### What did you expect to happen?
GIF of code mirror in MacOS Safari
![safari-editor-undo-ime-mp4](https://user-images.githubusercontent.com/9990676/191187000-fc30fddf-f29a-4236-a621-bf27e7af005d.gif)
But it works as smooth well in safari environments when typing same Chinese word in codemirror.

Is there a way to implement the same behaviour in ProseMirror?

### Anything to add? (optional)
During my research, I found that when the editor transaction step contain “你好”, there is a logic in `Branch#addTransform` method that will call `steps[i].invert(transform.docs[I])`. This line will invert “你好” to “nihao” as the previous `state.doc` instead of empty state.

**Comment by marijnh** [comment]
Which IME on which platform are you using for this? IBus "Chinese - Pinyin" on Firefox Linux doesn't show this.

**Comment by Matrixbirds** [comment]
> Which IME on which platform are you using for this? IBus "Chinese - Pinyin" on Firefox Linux doesn't show this.

I m using 「Pinyin - Simplified」on MacOS.
