### ISSUE TITLE
Highlighting a part of the editor

### ISSUE THREAD

**Issue by mfissehaye** [ProseMirror/prosemirror#1316]
I want to be able to highlight the content of the editor when the state of a variable changes. For example I want to define a variable that holds the value of the index of the word that I want to highlight. When that value changes I want to update the contents of the editor to highlight that specific word. That's all I want. I looked around the documentation but it is a bit difficult to understand. I appreciate any hints.

**Comment by marijnh** [comment]
Styling of inline content is done with [inline decorations](https://prosemirror.net/docs/ref/#view.Decoration^inline), styling of individual nodes with [node decorations](https://prosemirror.net/docs/ref/#view.Decoration^node). You'll have to set up a plugin to manage your decorations, and dispatch transactions to update it.

Questions are better asked on the [forum](https://discuss.prosemirror.net). This here is where we track bugs.
