### ISSUE TITLE
Variable named "chrome" raise issue in Chrome

### ISSUE THREAD

**Issue by eric-burel** [ProseMirror/prosemirror#1318]
"chrome" is already a global variable in Chrome browser, therefore the following line of code is problematic in `prosemirror-view` code: https://github.com/ProseMirror/prosemirror-view/blob/master/src/browser.ts#L15

You'll get "variable chrome is already instanciated" since it exists in Chrome.

Locally, renaming it `chrome2` for instance fixes everything.

During development, an Eslint configuration could help prevent this issue, that can happen with other name such as "document", "name" etc. that are all globals, for instance:
```
        "no-restricted-globals": ["error", {
            name: "chrome",
            message: "'chrome' variable is already defined by Chrome, use another name like 'isChrome'"
        }]
```

Until then I will probably have to find a way to minify `prosemirror-view` so the variable is renamed in my bundle.

**Comment by marijnh** [comment]
Modules can create local variables with the same name as locals. I can run this code just fine in Chrome. What kind of code is your bundler spitting out?

**Comment by eric-burel** [comment]
We have a rollup config that bundle in an index.js. So as far as I understand this "index.js" should be loaded as an ESM module instead of a script to fix the bug? Will try tomorrow and let you know.

**Comment by eric-burel** [comment]
After a check, we indeed need to use `type="module"` on the `<script>` tag for our file to be loaded as an ESM. Then this issue disappear. Thanks for your feedback!
