### ISSUE TITLE
RangeError when pasting text at the end of a code block when its the last node in the document

### ISSUE THREAD

**Issue by fletchertyler914** [ProseMirror/prosemirror#1319]
### Issue: 
When using CodeMirror in a ProseMirror instance, there is an issue when pasting text if the text length is longer than the original document length in the proseMirror view state. This is easy to reproduce when the CodeMirror node is the last node in the ProseMirror document and you paste in any text length at the end of the code block.

### Example:
1. Go to the [CodeMirror example page](https://prosemirror.net/examples/codemirror/)
<img width="736" alt="Screen Shot 2022-10-04 at 1 12 56 PM" src="https://user-images.githubusercontent.com/3344498/193894436-6b2d6627-7d6d-4bd1-a2db-c9d3dd580453.png">

2. Delete the last block of text below the code block (so the codeblock is the last node)
<img width="735" alt="Screen Shot 2022-10-04 at 1 13 48 PM" src="https://user-images.githubusercontent.com/3344498/193894574-50aa3ed4-53d9-4d97-b0ea-c6fc05ad1c0b.png">

3. Copy/Paste some text at the end of the code block
<img width="738" alt="Screen Shot 2022-10-04 at 1 14 25 PM" src="https://user-images.githubusercontent.com/3344498/193894695-3a31b9d7-43a6-4df5-91b3-a859c898e0b1.png">
<img width="492" alt="Screen Shot 2022-10-04 at 1 21 44 PM" src="https://user-images.githubusercontent.com/3344498/193895997-1cfe865a-62dd-48e1-b14d-cd51e6e3e423.png">

You will notice 2 things happening:
1. The text value is duplicated
2. The `RangeError` occurs because the offset is out of bounds with the original document.

For # 2 above, I believe the issue is coming from this function in the `forwardUpdate` call:
```
let selection = TextSelection.create(this.view.state.doc, offset + main.from, offset + main.to)
```

If we remove the logic for creating the new selection, this no longer throws the `RangeError`, but I believe we miss dispatching updates for when the selection (only) changes and the document is *not* updated.

Let me know if you need any more info and I will keep digging into a fix as well.

**Comment by marijnh** [comment]
This was a mistake in the example, which created the new selection using the old doc. Attached patch changes that.
