### ISSUE TITLE
Support controls overlaid on selected nodes

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#132]
For example, it'd be nice for nodes like images to have a little control to change its attributes when you select it.

Main difficulty is one of CSS -- if I overlay these over the document, they'll get mispositioned when content changes. If I want to put them _inside_ the nodes, I can't do that for inline nodes (which can't be relatively positioned) and would have to add ugly hacks like extra inline-block nodes).

It may even be nice to support overlay controls on all nodes, not just selected ones. If you're showing say, a video node, an always-present little edit icon in a corner would be easy to discover and use.

**Comment by bZichett** [comment]
I like this idea.  I think something close to it's purpose was implemented a few months back but decided against and removed by Marijn (Correct me if I'm wrong!) where there was an option to show a context menu floated to the right of the currently selected block/node (that is, where the caret is located) .  I thought this solution was pretty great.

As per your request, it seems the only difference is in the positioning of the "overlay"?

**Comment by marijnh** [comment]
These would be node-specific controls, visible when selecting a node, rather than an always-present general menu.

**Comment by bZichett** [comment]
Updated my previous comment with corrections / more information (didn't think you'd answer that quick)

In that past solution, it wasn't always present.  At least it was only always present if your caret was somewhere in the confines of a text block, and that "right-aligned floated context menu" acted on that text block only.  (Perhaps this is clearer, since I wasn't referring to the general menu)

**Comment by marijnh** [comment]
We'll want to formulate this as a more general 'node decoration' feature -- there a bunch of use cases that require the ability to override the way a given node is rendered (selected nodes, widgets, ad-hoc styling), and they'll all need to somehow interface with the update algorithm, so it would be good to solve that with a single feature, rather than a bunch of separate hacks.

**Comment by marijnh** [comment]
I think custom node views cover this pretty well.
