### ISSUE TITLE
`EditorState.filterTransaction` is unexpectedly exported in the document

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1320]
Open https://prosemirror.net/docs/ref/#state.EditorState.filterTransaction

<img width="1077" alt="CleanShot 2022-10-17 at 16 29 37@2x" src="https://user-images.githubusercontent.com/24715727/196128787-b69ebeb2-6ce4-43a9-8d8b-3ddf8b53a1dc.png">

This method is marked as [internal](https://github.com/prosemirror/prosemirror-state/blob/3f9311ec2fc6f0803c1dbe59dfd2297f731dbd5c/src/state.ts#L122) so I guess the document website shouldn't show it.

**Comment by marijnh** [comment]
This was fixed in 3f9311ec2fc6f0803c1d . I've tagged a new version to force the docs to update.
