### ISSUE TITLE
`splitBlock` splits 1 character before caret position

### ISSUE THREAD

**Issue by schristiansson** [ProseMirror/prosemirror#1321]
How to reproduce:
1. Create a function that utilizes the `splitBlock` function
2. Place caret somewhere in the text and execute the function
3. Done

Issue found on Chrome Version 106.0.5249.119 (Official Build) (arm64)

![splitBlock](https://user-images.githubusercontent.com/114254828/196186070-14e0cd85-27e1-444d-b2d2-67ea27b99007.gif)

Possible fix update [this row](https://github.com/ProseMirror/prosemirror-commands/blob/9a187ecec867a44826d130c9d85d05598a8dbaf2/src/commands.ts#L317) to `tr.split(tr.mapping.map($from.pos + 1), 1, types)`

**Comment by marijnh** [comment]
`splitBlock` is the main command bound to Enter in almost every ProseMirror setup, everywhere, and as you can see on https://prosemirror.net, it does not in normal circumstances split in the wrong position. So you're going to have to provide more information on how/when this issue occurs.

**Comment by schristiansson** [comment]
Thank you, [marijnh](https://github.com/marijnh). Issue seems to be our implementation (Using tiptap above prosemirror) tries to splitBlock for some reason. I will have to investigate further. Thank you for you reply and sorry for wasting your time.
