### ISSUE TITLE
Android: extra paragraph added instead of character when all text was selected and character was typed

### ISSUE THREAD

**Issue by DontGiveAFck** [ProseMirror/prosemirror#1323]
Steps to reproduce:
1. Open Editor with 2 lines of text on Android Chrome
2. Select all text
3. tap on keyboad and write character.

Expected result: typed character was added to the first paragraph
Actual result: character wasn't added, empty paragraph was added, caret was moved to second paragraph.

[video](https://vimeo.com/763721246/c588a9b392)

**Comment by danziv** [comment]
I am having the same problem on Android devices.
