### ISSUE TITLE
Extract built-in event handlers into reusable commands

### ISSUE THREAD

**Issue by snnsnn** [ProseMirror/prosemirror#1328]
Hi, I would like to use built-in event handlers for custom key events, for example moving cursor left using `Mod+K` (achieve the same effect as `LeftArrow`) and extending selection to left with `Mod+Shift+K` (achieve the same effect as `Mod+LeftArrow`). Basically I want to bind a command to multiple keymaps. Is there a way you can expose built-in keyboard event handlers as commands?

My aim is to have vim like editing experience, not needing to lift your fingers from the keyboard to reach arrow keys. I believe some of the functionality is native to browser via content editable but could not be sure since `prosemirror-view` explicitly handles few cases.

**Comment by marijnh** [comment]
ProseMirror lets the browser's native behavior happen for these kinds of keys (basically, anything not bound in your keymap), and the browser does not generally impose a script interface to them.
