### ISSUE TITLE
Editor loses focus when navigating cursor after the end of document using spacebar

### ISSUE THREAD

**Issue by thecodrr** [ProseMirror/prosemirror#1331]
## Demo

Here's a demo of the issue:

https://user-images.githubusercontent.com/7473959/200007950-f36d49a7-592f-4b4d-b576-6c12f5ce79f8.mp4

## Details:

On Android keyboards have the feature that allows navigating the cursor using Spacebar. You swipe left or right and the cursor follows accordingly. Prosemirror unfortunately loses the focus when the cursor is swiped after the end of the note. You can see this behavior in the demo above.

This does not happen with any other editor (I tested on TinyMCE).

**Device info:**
OS: Android 11
Keyboard: OpenBoard
Browser: Brave

**Comment by thecodrr** [comment]
@marijnh sorry for the ping but just wanted to bring this to your attention.

**Comment by marijnh** [comment]
This happens with plain contentEditable elements as well. I guess the virtual keyboard moves the selection out of the editor into the content after it when you do this.
