### ISSUE TITLE
Copy text with leading and trailing `<br>` and paste it into ProseMirror will remove the line break wrongly 

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1332]
## Steps to reproduce 

1. Copy `AAA\nBBB` from VSCode. This step writes the following content (after simplify) into clipboard: 
   ```js
   {
      'text/plain': 'AAA\nBBB',
      'text/html': `<div><div>AAA</div><div>BBB</div></div>`,
    }
   ```
2. Paste it into ProseMirror
3. Copy `\n\nCCC\nDDD\n\n` from VSCode. This step writes the following content into clipboard: 
   ```js
   {
      'text/plain': '\n\nCCC\nDDD\n\n',
      'text/html': `<div><br><br><div>CCC</div><div>DDD</div><br><br></div>`,
    }
   ```
4. Paste it into ProseMirror

## Expected behavior

The pasted content in ProseMirror should be something like this:

```
AAA
BBB

CCC
DDD
```

## Actual behavior 

The newline between `CCC` and `DDD` is gone. The pasted content is like this:

```
AAA
BBB

CCCDDD
```
 

## Video

https://user-images.githubusercontent.com/24715727/201604868-8d43591d-2126-4bd7-ab4d-2b69a179fb9e.mp4

## Addition context 

I guess this bug is related to these part of code: 
https://github.com/prosemirror/prosemirror-view/blob/13f733299866d40a9f6f75e9165b13ae3cdae9c1/src/clipboard.ts#L83-L87

**Comment by marijnh** [comment]
The issue had nothing to do with `<br>` nodes (there are no such nodes at the point where the line break went missing), but was related to how the DOM parser handles nested unrecognized block elements. Attached patch should help.

**Comment by ocavue** [comment]
Thank you for your quick fix
