### ISSUE TITLE
The selected text in the current editor has been canceled

### ISSUE THREAD

**Issue by WuYunlong** [ProseMirror/prosemirror#1338]
When I add a hyperlink

The selected text in the current editor has been canceled, and I want to continue to display it as selected.

https://user-images.githubusercontent.com/3301446/203467050-02e66a4f-91c5-4e14-a1b1-a9b697651b77.mp4

**Comment by marijnh** [comment]
The editor selection is the browser's native selection, and if the cursor is in some text field in a dialog, it's not in the editor, so you won't see a selection range there. You could use a decoration to indicate where the selection is if you really want to, but this isn't something the library is going to do by default.
