### ISSUE TITLE
safari doesn't support auto scroll while dragging

### ISSUE THREAD

**Issue by percy507** [ProseMirror/prosemirror#1339]
Hi @marijnh,

Recently I find a problem in safari, it does't support auto scroll while dragging. (https://discussions.apple.com/thread/252081922) Chrome supports, but not smooth enough.

Then I write some script to fix this. Here are demos. (safari browser v15.0)

- **safari, before using the script**
  - ![2022-11-25 11 05 53](https://user-images.githubusercontent.com/18365078/203899105-3da712e1-86d3-4c9f-808c-684ea18ff62c.gif)
- **safari, after using the script**
  - ![2022-11-25 11 34 53](https://user-images.githubusercontent.com/18365078/203899165-1bf6797b-bad7-4d95-9830-4a10a9790b61.gif)

If you want, I can make a PR and insert the script into [here](https://github.com/ProseMirror/prosemirror-view/blob/master/src/input.ts#L41).

**Comment by marijnh** [comment]
Sure, I'd be interested in taking a look at a PR.

**Comment by percy507** [comment]
Here is it. https://github.com/ProseMirror/prosemirror-view/pull/148

**Comment by marijnh** [comment]
I've decided to not include this in the core library (but one could create a plugin that adds it).

**Comment by percy507** [comment]
Release a package just now🥳. https://github.com/percy507/auto-scroll-while-dragging
