### ISSUE TITLE
InputRule and history undo

### ISSUE THREAD

**Issue by PRR24** [ProseMirror/prosemirror#1341]
Please provide a (simple) means to detach transformations done by an InputRule from other transformations in the history, so that the InputRule's transformation could be undone without undoing anything else at the same time.

For example, after entering "...", ellipsis rule will transform/autocorrect these dots to ellipsis. But if ellipsis cannot be used at that location, there is no easy way to undo the transformation without undoing dot-entering altogether. The same applies also to more complex rules, like unwanted auto-linking etc.

Thank you.

**Comment by marijnh** [comment]
Did you see the [`undoInputRule`](https://prosemirror.net/docs/ref/#inputrules.undoInputRule) command?

**Comment by PRR24** [comment]
Thank you. It is not a perfect solution, but after digging around I think I understand why it is implemented this way.
