### ISSUE TITLE
facilitate deep-linking

### ISSUE THREAD

**Issue by KiaraGrouwstra** [ProseMirror/prosemirror#1344]
i am currently using markdown documents in nextcloud, which uses prosemirror both for editing and previews.
being familiar with github, i am used to seeing the headers from markdown documents used to facilitate deep-linking, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/3059397/207631706-f8d294c3-4306-4ab1-9866-88f710fcd890.png)

i feel it would be nice if prosemirror(-view?) were to offer a similar feature.

**Comment by bZichett** [comment]
This appears less an issue and more likely could start a conversation here https://discuss.prosemirror.net/

**Comment by marijnh** [comment]
This sounds outside of the scope for the core ProseMirror packages, which do not do any kind of previews.
