### ISSUE TITLE
Incorrect marks when pasting HTML with nested list

### ISSUE THREAD

**Issue by john-edwardson** [ProseMirror/prosemirror#1347]
We've encountered an issue when pasting in nested lists from Google Docs where nested list items have styles that conflict with parent items.  For a minimal repro, consider this HTML:
```
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <meta charset="utf-8" />
    <ul>
      <li style="font-style: italic">
        Italics
        <ul>
          <li style="font-style: normal; font-weight: 400">Normal</li>
          <li style="font-style: normal; font-weight: 700">Bold</li>
          <li style="font-style: italic; font-weight: 400">Italics</li>
        </ul>
      </li>
      <li style="font-weight: 700">
        Bold
        <ul>
          <li style="font-style: normal; font-weight: 400;">Normal</li>
          <li style="font-style: normal; font-weight: 700">Bold</li>
          <li style="font-style: italic; font-weight: 400">Italics</li>
        </ul>
      </li>
    </ul>
  </body>
</html>
``` 

When I open this as an HTML file in the browser it looks like this:
![image](https://user-images.githubusercontent.com/65559268/213047003-3527a3ea-2829-4ec4-85c4-288b77267c7e.png)

When I paste this into prosemirror I get this:
![image](https://user-images.githubusercontent.com/65559268/213047553-e84a2ecc-a86c-4be0-b92b-1c95da12480f.png)

As you can see, the styles from the parent list item are taking precedence over the styles from the children.  I would expect the child styles to take precedence, as it does when I view the HTML file in a browser

**Comment by marijnh** [comment]
Attached patches should help with this.
