### ISSUE TITLE
After ts migration, posFromCoords in a node that lacks a contentDOM now biases towards the node's end instead of the start

### ISSUE THREAD

**Issue by sarahriouslydt** [ProseMirror/prosemirror#1348]
I've been migrating our version of prosemirror-view from 1.23.4 to 1.29.1 and ran into a logic change that was difficult to pin down.

We have draggable nodes and the previous behaviour was when one node was dragged onto another (e.g node B was dragged over node A), node B would be inserted before node A, but now it's inserted after.
This seems specifically to affect the case where the node we're dragging over (node A) lacks a contentDOM, so prosemirror tries to find a safe pos to insert the node A slice.

I did some digging and found the root cause: the `posFromCaret` function now calls `view.docView.posFromDOM` with a [default bias of 1](https://github.com/ProseMirror/prosemirror-view/blame/master/src/domcoords.ts#L227):
```typescript
  return outside > -1 ? outside : view.docView.posFromDOM(node, offset, 1)
```
Prior to the typescript migration [no bias was provided](https://github.com/ProseMirror/prosemirror-view/blob/1.23.4/src/domcoords.js#L210):
```typescript
  return outside > -1 ? outside : view.docView.posFromDOM(node, offset)
```

This changes the behaviour of `localPosFromDOM` if [no contentDOM is present](https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.ts#L219). Before a default value of `this.posAtStart` would be returned but now it defaults to `this.posAtEnd`, causing the observed behaviour. 
```typescript
    return (atEnd == null ? bias > 0 : atEnd) ? this.posAtEnd : this.posAtStart
```

This is a super minor issue in the scheme of things but I wanted to raise it as it's a small logical change that may not have been intended. 

I can try and provide a demo if needed but I hope that explanation is sufficient.

**Comment by marijnh** [comment]
Is the node you're dropping something on an inline or a block node?

**Comment by marijnh** [comment]
More specifically, would behavior where the chosen position depends on where the drop happens relative to the center of the node (vertically for block nodes, horizontally for inline nodes) work for you?

**Comment by sarahriouslydt** [comment]
Hey! Sorry, should have clarified - these are block nodes. 
> More specifically, would behavior where the chosen position depends on where the drop happens relative to the center of the node (vertically for block nodes, horizontally for inline nodes) work for you?

That would be fantastic and an improvement over how it works for us currently 🎉

**Comment by marijnh** [comment]
Attached patch implements that behavior.

**Comment by marijnh** [comment]
Does attached patch help for you?

**Comment by jljorgenson18** [comment]
@marijnh I'll try first thing on Monday but conceptually I think it makes sense.
