### ISSUE TITLE
Unexpected behaviour of ProseMirror with Polyglot Extension

### ISSUE THREAD

**Issue by Salman2301** [ProseMirror/prosemirror#1358]
## Issue details
When used with Polyglot extension the editor failed to load.

#### Steps to reproduce
- Install the [Polyglot Extension](https://chrome.google.com/webstore/detail/polyglot/hdbcnodefcbojlkaobiahghecgjoiicb)
- Go to the example from the following article:
   https://prosemirror.net/examples/basic/
- The editor didn't load properly.

ProseMirror version
latest

Affected platforms
Chrome

Screenshots / Screencast (Optional)
![Screenshot 2023-02-27 at 7 57 13 PM](https://user-images.githubusercontent.com/40920317/221589949-371a8a17-11f4-4d46-9348-99bd2280852e.png)

**Comment by marijnh** [comment]
I'd report this with the developers of the plugin, since I feel this is their bug (specifically, they probably need to respect the translate=no attribute). I don't currently have the time to debug problems caused by other software.
