### ISSUE TITLE
dropCursor doesn't appear when dragging a node that can appear at most once

### ISSUE THREAD

**Issue by jiegillet** [ProseMirror/prosemirror#1359]
Hello! 
First of all, thank you so much for working on prosemirror, it is a real pleasure to use.

In our editor, we have a node that can only appear at most once.
The node, when it exists, can be dragged and dropped, but the `dropcursor` element does not appear.

It happens [at this point](https://github.com/ProseMirror/prosemirror-dropcursor/blob/626e24ca1851f3adb83f1d28ad750d79c42ad468/src/dropcursor.ts#L133), where the plugin calls `dropPoint` that eventually calls `this.contentMatchAt(from).matchFragment(replacement, start, end)` [on this line](https://github.com/ProseMirror/prosemirror-model/blob/9201015c268947c34fa31be26b8b7aa5a0cf9776/src/node.ts#L273), which doesn't match because the editor (rightfully) thinks that the node is already in use somewhere else.

The cursor should appear since it is legal to move the node.

[Here is a test project](https://glitch.com/edit/#!/daily-jealous-fig?path=index.js%3A24%3A0) that illustrates the situation.
In case it gets deleted, the modification from the standard project are
```js
const {nodes, marks} = require("prosemirror-schema-basic")

const myNodes = { 
  ...nodes,
  /// The top level document, the document can contain at most one unique_horizontal_rule
  doc: {
    content: "block* unique_horizontal_rule? block*"
  },
  /// A horizontal rule that can only appear once
  unique_horizontal_rule: {
    parseDOM: [{tag: "uniquehr"}],
    toDOM() { return ["hr", { style: "background-color: red;"}] }
  },
}

const schema = new Schema({nodes: myNodes, marks})
```

in `index.js` and

```html
  <h3>Hello ProseMirror</h3>
  
  <p>The horizontal rule below is a normal one, it can be dragged around with the dropcursor</p>
  
  <hr>
  
  <p>The horizontal rule below is one that can only be in the document once, it can be dragged around, but the dropcursor doesn't appear</p>

  <uniquehr></uniquehr>
```
in `index.html`.

**Comment by marijnh** [comment]
Attached patch should improve this.

**Comment by jiegillet** [comment]
Thank you, that fixed it nicely :)
