### ISSUE TITLE
`joinTextblockBackward` doesn't work in a nested blockquote

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1360]
I'm testing [joinTextblockBackward](https://prosemirror.net/docs/ref/#commands.joinTextblockBackward). I found that it doesn't work as expected when inside a nested block. 

## Steps to reproduce:

1. Add the following test case to this test suit: https://github.com/prosemirror/prosemirror-commands/blob/40d42d53a584c0ae31938f5915c39845b70346f4/test/test-commands.ts#L107

```ts
describe("joinTextblockBackward", () => {
  // This is the existing test case 
  it("can join if first block is wrapped", () =>
     apply(doc(blockquote(p("hi")), p("<a>there")), joinTextblockBackward, doc(blockquote(p("hi<a>there")))))

  // This is the new test case 
  it("can join if inside a nested block", () =>
     apply(doc(blockquote(blockquote(p("hi")), p("<a>there"))), joinTextblockBackward, doc(blockquote(blockquote(p("hi<a>there"))))))
})
```

2. Run the test.

## Expected behavior 

Test should pass. These two test cases should have similar behavior, i.e. the gap between `hi` and `there` should be removed. 

## Actual behavior 

Test failed. `joinTextblockBackward` did nothing, because of the if condition `step.slice.size >= afterPos - beforePos` at [here](https://github.com/prosemirror/prosemirror-commands/blob/40d42d53a584c0ae31938f5915c39845b70346f4/src/commands.ts#L110).

**Comment by marijnh** [comment]
Attached patch should fix this.

**Comment by ocavue** [comment]
Thank your for the quick fix. The patch works well.
