### ISSUE TITLE
posAtCoords / dropcursor in shadow root will jump to block end on Chrome 

### ISSUE THREAD

**Issue by eric-burel** [ProseMirror/prosemirror#1367]
The editor is rendered within a web component shadow root.

On the screenshot you can see that if the dragged text is between 2 lines, the cursor (yellow) will jump at the end of the block.

This happens only on Chrome (Chromium 111.0.5563.64 (Build officiel) snap (64 bits) on Ubuntu) not Firefox.
This doesn't happen in Prosemirror demo (https://glitch.com/edit/#!/remix/prosemirror-demo-basic) hence the strong suspicion that it comes from the Shadow Root.

This is visible while drag and dropping, however the root issue seems to be in "prosemirror-view" `posAtCoords` method, which returns a position at the end of the block. If I hover text and not blank space, the cursor is back to normal, leading to visual jumps during drag and unreliable drag and drop experience.

![image](https://user-images.githubusercontent.com/7983005/230389015-15dd39ab-e79b-46da-9b11-25bbabd5b53d.png)

I've managed to build a repro: https://insidious-therapeutic-point.glitch.me/
- highlight a small piece of text (on one line)
- move around, you'll notice the cursor jump on Chrome, not on Firefox
![image](https://user-images.githubusercontent.com/7983005/230398959-cf5ae801-c031-4825-ba32-c3fbc419f30b.png)

**Comment by marijnh** [comment]
Chrome's `caretRangeFromPoint` is broken in shadow roots, and the editor's own replacement implementation didn't handle this situation well. Attached patch should help.

**Comment by eric-burel** [comment]
Thanks for the fast response!
