### ISSUE TITLE
Paste from Google Docs sets wrong mark 

### ISSUE THREAD

**Issue by Mr3zee** [ProseMirror/prosemirror#1376]
Hi! 
While working with the editor, found the following bug:

Steps to reproduce:
- Create Google Docs empty document
- Toggle Bullet list
- Toggle on *Italic*
- Type 'Hello' text
- Press Shift+Enter
- Toggle off *Italic*
- Type 'World' text
- Select text starting from the start of the 'Hello' text left-to-right to the end of the 'World' text
- Copy text
- Paste into the editor on prosemirror.net

Expected result: Bulleted list is passed with two rows: first row has *Italic* mark, second row does not
Actual result:  Both rows have *Italic* mark

**Comment by katepol** [comment]
@marijnh still having issues with this, please see the screencast.
There are 2 cases:
1) when copy lines (as in issue description) -> the second line gets strong mark
2) when copy all document (cmd+A) -> the second line is italic.

https://github.com/ProseMirror/prosemirror/assets/484436/2eb159ca-d4ce-4e85-bab0-d5c7feb7ab85

**Comment by marijnh** [comment]
I cannot reproduce either of those behaviors. For me, both when selecting text and when doing ctrl-a, the pasted content has "World" in regular, non-bold, non-italic font.

**Comment by katepol** [comment]
What browser do you use? My recording was for Chrome, Version 114.0.5735.133 (Official Build) (arm64)
By the way, Safari Version 16.5.1 (18615.2.9.11.7) I get everything bold, may be related to https://github.com/ProseMirror/prosemirror/issues/459

**Comment by marijnh** [comment]
Ah, right, the expanded parse rules haven't been added to prosemirror-markdown. Attached patch adds them.
