### ISSUE TITLE
inputRules triggered with a delay + incorrect start/end when applied in reverse

### ISSUE THREAD

**Issue by eric-burel** [ProseMirror/prosemirror#1377]
Here is a glitch reproducing the issue:
https://glitch.com/edit/#!/vintage-mixolydian-clam

1) Check the browser console logs
2) Add a star somewhere in the text
3) Add a star **before** 
4) Click somewhere else and add a letter

[Capture vidéo du 23-05-2023 16:16:41.webm](https://github.com/ProseMirror/prosemirror/assets/7983005/030d3b58-e4de-413c-a0f4-2d85bc97a6ba)

You'll see that the rule is triggered, but its "start" and "end" matches the cursor position, not the match position.

Adding a start then a star after is not a problem

Instead, I would have expected:
1) Ideally, the match to be triggered when adding a star before (this might not be feasible)
2) The "start" and "end" value to match the position of the matching content, not the cursor content (this is the most annoying part)

`match.index` seems to be relative to the current node so I don't think it can be used either, it won't be the right "start" value when there are multiple nodes in the document

**Comment by marijnh** [comment]
Glitch.com is, unfortunately, a broken mess. Could you put your script on some other sandbox service?

**Comment by marijnh** [comment]
Your RegExp doesn't end in `$`, which is a requirement noted in [the docs](https://prosemirror.net/docs/ref/#inputrules.InputRule.constructor). Also, there is no promise about `match.index` being anything in particular. Possibly you're expecting input rules to work in a way that they don't actually work.

**Comment by eric-burel** [comment]
Ah ok, I did read about th `$` ([here for googlers](https://prosemirror.net/docs/ref/#inputrules.InputRule) but didn't understand it was regex.

Adding the "$" will change the behaviour so that the inputrules is not triggered at all when written in reverse.
But that's not a blocker.
