### ISSUE TITLE
<BR> causes problems when trying to exit list

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#138]
If starting a document with contents such as 

```
<p><br></p>
```
The BR-element is pushed further and further down as the document progresses, although the BR is barely noticeable to the user, it does cause problems when trying to exist lists as the Enter(30) rule counts the size of the list item as being 1.

Quick fix: Make sure not to start documents with an extra BR-element, and make sure to remove these later on if they are added accidentally.

**Comment by marijnh** [comment]
Is there anything you expect me to do about this? It sounds like a very reasonable fallout of ProseMirror's behavior rules, and random ignorable BRs may be something people do in HTML, but I don't think there's a reason for them in ProseMirror documents.

**Comment by johanneswilm** [comment]
Hmm, I guess you are right.
