### ISSUE TITLE
Unable to cut with Shift+Delete when all text is selected.

### ISSUE THREAD

**Issue by gg-kialo** [ProseMirror/prosemirror#1381]
When I select all text (`Ctrl+A`) in the textbox (e.g. the example on <https://prosemirror.net/>), I am then unable to cut text with the `Shift+Delete` key combo. If I select some subset of the text then I am able to cut the text.

OS: Ubuntu 23.04
Browser: Firefox (114,115), Chromium 113
(and other linux users have reported the same issue to me)

**Comment by marijnh** [comment]
Attached patch seems to resolve that.
