### ISSUE TITLE
After deletion of expanded selection in list, list items remain and cannot be removed

### ISSUE THREAD

**Issue by Slapbox** [ProseMirror/prosemirror#1383]
It's possible to reproduce this issue with the [example editor](https://prosemirror.net/examples/basic/), starting with an initial state like this:

![image](https://github.com/ProseMirror/prosemirror/assets/6835891/40175eb6-38c3-4377-8fee-de043ef79c69)

https://github.com/ProseMirror/prosemirror/assets/6835891/29ec9f3e-bd80-453c-88f9-fd0f37648c27

**Comment by marijnh** [comment]
What would you expect the editor to do in this case? The list item still has another child, so it can't be deleted. The paragraph also can't be removed, since it would violate the schema constraints on what a list item can hold.

**Comment by Slapbox** [comment]
Thanks for your reply @marijnh. The most common behavior I've seen for editors in these cases is to lift the lists beneath the deleted list items up to the top level, or to the level where the selection started if it's not the top of the list.

But I guess that can't be achieved via a single transaction on a single node which may be against the ProseMirror way of doing things?

I noticed a number of odd behaviors and I wonder which of them are intentional design choices and which of them are bugs.

**Comment by marijnh** [comment]
The command that runs here (`joinBackwards`) knows nothing about lists or specific schemas and acts on arbitrary node structures in arbitrary schemas. As such, there's no hard-coded list logic in it and performing the behavior you are expecting (which doesn't sound all that obvious) is beyond it.
