### ISSUE TITLE
handlePaste does not work with SHIFT+INSERT

### ISSUE THREAD

**Issue by BertschMario** [ProseMirror/prosemirror#1384]
```
handlePaste: (view, event, slice) => {
        const fileUrls: string[] = [];
        slice.content.descendants((node) => node.type.name === 'image' && !fileUrls.push(node.attrs['src']));
        if (fileUrls.length === 0) return false;
        return true;
      },
```

The handlePaste event does only trigger on `CTRL+V` and `Rightclick=>Paste`, but `SHIFT+INSERT` does not trigger the event correctly.

**Comment by marijnh** [comment]
Which browser and OS is this on? It works fine on Chrome and Firefox Linux.

**Comment by BertschMario** [comment]
> Which browser and OS is this on? It works fine on Chrome and Firefox Linux.

Ohh, my mistake, I just saw that the event is being triggered, but no image is being inserted and therefore it can't be read. The insertion with `SHIFT+INSERT` doesn't work in the example either: https://prosemirror.net/examples/basic/
Tested on Ubuntu 22.04 => Chrome/Firefox & Windows => Chrome/Firefox
