### ISSUE TITLE
Caret doesn't move to new line in code block

### ISSUE THREAD

**Issue by dnsv** [ProseMirror/prosemirror#1388]
**Steps to reproduce:**
1. Open https://prosemirror.net/ in Firefox (I'm using v114.0.1). 
2. Either delete the existing content or go to a new line in the demo editor.
3. Write ``` and press enter. You're now in the code block.
4. Press enter again. 

**Expected behavior:**
The caret (cursor) moves to a new line.

**Actual behavior:**
The caret is still on the first line. The `<code>` element's height has grown to house 2 lines, just the caret stayed on the first one.

**Additional information:**
It works as expected in Safari. I didn't try other browsers.

**Comment by marijnh** [comment]
Seems the firefox bug that caused https://github.com/ProseMirror/prosemirror/issues/1128 is not entirely fixed after all. Attached patch brings back our workaround kludge for that.

**Comment by marijnh** [comment]
Filed [issue 1837920](https://bugzilla.mozilla.org/show_bug.cgi?id=1837920) on the Firefox bug tracker.
