### ISSUE TITLE
The prosemirror.net example is broken in IE mode on Edge.

### ISSUE THREAD

**Issue by ryu-0729** [ProseMirror/prosemirror#1390]
### Issue details
The ProseMirror editor in the prosemirror.net example is broken in IE mode on Edge.

It looks like the same thing has happened before.
https://github.com/ProseMirror/prosemirror/issues/1009

### Steps to reproduce

1. Go to [prosemirror.net](https://prosemirror.net/) with Edge
2. Start IE mode
3. Example ProseMirror editor is not working

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Edge/IE mode
- [x] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![IMG_2410](https://github.com/ProseMirror/prosemirror/assets/65229017/951669d2-2626-48dd-9954-37293dcf477a)

**Comment by marijnh** [comment]
The ProseMirror modules are no longer converted to ES3 syntax, and the website build process doesn't do this either. So this is expected. You'll have to do so in your own build process if you want to run stuff on IE11.

But IE11 support is going to be dropped in the near future, so unless you are planning to freeze your ProseMirror version it may not be something that's going to work anyway.
