### ISSUE TITLE
Save history in order to replay undo-related bugs

### ISSUE THREAD

**Issue by arnaud-secondlayer** [ProseMirror/prosemirror#1392]
I'm facing a bug related to undo (`Invalid content for node`), it's quite difficult to reproduce. I'm pretty sure it's in our code and not in ProseMirror.
I'd like to be able to export the history in order to be able to study the problem after it is reproduced.
Is there a solution to export the current history in order to replay it later?

**Comment by marijnh** [comment]
No, that doesn't exist as a public interface. You could try looking through the (private) data structures in the history state, but it's going to require some study to understand what they mean.
