### ISSUE TITLE
weird behavior of "code" feature on the prosemirror.net front page editor

### ISSUE THREAD

**Issue by vgu-natbraille** [ProseMirror/prosemirror#1403]
1. type 'a'
2. select 'Type/code' in menu bar
3. type 'enter'
4. type 'b'
5. place the cursor at the end of the first ('a') line
6. select 'Type/plain' in menu bar

content of the editor

```
a
b
```
7. type 'c'

the second line is now merged with the first line, displaying

```
ac b
```
(using firefox 102)

Is does not feel like an intended behavior, or I don't understand its rationale.

**Comment by marijnh** [comment]
Attached patch should help with this.

**Comment by vgu-natbraille** [comment]
seems good thanks !
