### ISSUE TITLE
Editor jumps to middle of list when focusing on long nested list

### ISSUE THREAD

**Issue by davatron5000** [ProseMirror/prosemirror#1405]
A customer of mine brought up a weird situation they had when editing content with a very long nested list that was causing a page jump. I was unable to stop Prosemirror from performing the jump. 

If there's a workaround for this I'd love to know. Thanks.

**Environment**

- Chrome 113+

**Steps to repro**

1. Go to https://prosemirror.net homepage.
2. In ProseMirror, create a paragraph of text and a long list (~25 items). List must contain at least one nested list item.
3. At the end of the paragraph above the long list, hit the `Delete` key (once or twice)

**Actual Results**

- List is selected (`.ProseMirror-selectednode`), but the entire browser viewport window jumps to middle of list height

**Expected Results**

- List is selected, but either no window jump or just a jump to the top of the list.

**Demo**

- https://github.com/ProseMirror/prosemirror/assets/42218/d9370860-112a-4174-93d7-e2e427e9c1ad

<details>
<summary>[Sample Text]</summary>

Extremely long list

- listItem
  - listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem
- listItem

**Comment by marijnh** [comment]
Attached patch should help with this.

**Comment by davatron5000** [comment]
Thanks so much, @marijnh 🎉
