### ISSUE TITLE
Pressing ArrowUp cannot move text cursor

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1406]
After upgrading prosemirror-view from 1.31.6 to 1.31.7, we found a bug with text cursor movement. If the cursor is right after an inline atom node, pressing ArrowUp cannot move the cursor anymore. 

Reproduction:

1. Open the following two links. They are the same code, but one is using prosemirror-view 1.31.6 and another is using 1.31.7 
   - https://codesandbox.io/p/sandbox/prosemirror-view-inline-atom-1-31-7-5mn8yy
   - https://codesandbox.io/p/sandbox/prosemirror-view-inline-atom-1-31-6-9fhr3k
2. Put the text cursor at the end of the yellow `InlineAtom` node
3. Press `ArrowUp`

Expected behavior: the text cursor moves up

https://github.com/ProseMirror/prosemirror/assets/24715727/ae475e49-f863-49f8-9966-2768fa6e4705

Actually behavior: in the 1.31.7 demo, the text cursor doesn't move 

https://github.com/ProseMirror/prosemirror/assets/24715727/bf805cc9-1874-4890-a6d0-92db8fb16ade

**Comment by marijnh** [comment]
This patch should help.

**Comment by ocavue** [comment]
Thank you!
