### ISSUE TITLE
textBetween ignores empty paragraphs

### ISSUE THREAD

**Issue by Septh** [ProseMirror/prosemirror#1419]
Given the following block node (shown here in a html-y way, but I am actually talking of PM nodes):

```html
<block>
  <p>1</p>
  <p></p>   // <-- note: empty paragraph
  <p>2</p>
</block>

```

Because the empty paragraph _is_ present is the block's contents, I would expect `block.textBetween(startOfBlock, endOBlock, "\n")` to return `"1\n\n2"` (somehow akin to what _`string.join()`_ does) but I'm getting `"1\n2"` instead. Is it intended behavior?

**Comment by marijnh** [comment]
I don't think that was intentional. Attached patch should improve it.
