### ISSUE TITLE
Pressing ArrowDown cannot move text cursor to the end of atom node

### ISSUE THREAD

**Issue by ocavue** [ProseMirror/prosemirror#1422]
After upgrading prosemirror-view from 1.31.6 to 1.32.0, we found a bug with text cursor movement. If the cursor is right after an inline atom node, pressing ArrowUp cannot move the cursor anymore.

Reproduction:

- Open the following two links. They are the same code, but one is using prosemirror-view 1.31.6 and another is using 1.32.0

  - https://codesandbox.io/p/sandbox/prosemirror-view-inline-atom-1-31-6-z828l4
  - https://codesandbox.io/p/sandbox/prosemirror-view-inline-atom-1-32-0-zlyv6h

- Put the text cursor at the start of the yellow InlineAtom node
- Press ArrowDown

Expected behavior (in the 1.31.6 demo): the text cursor moves to the end of the document (right side of the atom node)

https://github.com/ProseMirror/prosemirror/assets/24715727/a3df3c67-d3e6-42bc-b30a-01f15f3e5bb6

Actually behavior (in the 1.32.0 demo): the text cursor jumps to the end of the document and jumps back.

https://github.com/ProseMirror/prosemirror/assets/24715727/a34a4c01-75b9-46c0-9cfa-02a1b90aec7b

This issue seems to be related to https://github.com/ProseMirror/prosemirror/issues/1406

**Comment by marijnh** [comment]
Patch 2736542ea41dc174afbf948f745351c8bb0bcce9 seems to help with this.

**Comment by ocavue** [comment]
Thanks! prosemirror-view@1.32.1 looks good to me.
