### ISSUE TITLE
could the rebaseSteps function be exported?

### ISSUE THREAD

**Issue by neil-sigma** [ProseMirror/prosemirror#1426]
The [codeMirror collab API](https://codemirror.net/docs/ref/#collab) exposes a `rebaseUpdates` function which fits nicely into our current approach since we can manage the version number state ourselves.

Could the `rebaseSteps` function also be exported? I made a [branch for it here](https://github.com/ProseMirror/prosemirror-collab/compare/master...neil-sigma:prosemirror-collab:neil/export_rebaseSteps?expand=1). 

If not, why?

**Comment by marijnh** [comment]
What do you want to use it for?

**Comment by neil-sigma** [comment]
> What do you want to use it for?

Great question!

I'm an engineer at the startup Sigma Computing and I worked on the [Live Edit](https://help.sigmacomputing.com/hc/en-us/articles/9384868843027-Workbook-collaboration-with-Live-Edit) feature. Right now collaboratively editing text within a text box is a poor experience since it's last-writer wins.

If the `rebaseSteps` function was exposed we could easily fit the ProseMirror collaborative editing approach into our code.

**Comment by marijnh** [comment]
I'd say just copy it—it's just 14 lines. That allows you to tailor it to your requirements, and doesn't require me to put a hard-to-use internal function in the public, documented API.

**Comment by neil-sigma** [comment]
Fair enough, that's what I'm doing now. I was just curious why the codemirror collab API and prosemirror collab API aren't symmetrical

**Comment by marijnh** [comment]
Their OT implementations work very differently, making some stuff that's easy in CodeMirror a lot harder to do correctly in ProseMirror.

**Comment by neil-sigma** [comment]
> Their OT implementations work very differently, making some stuff that's easy in CodeMirror a lot harder to do correctly in ProseMirror.

Ah ok perfect this was what I was interested in. Could you give an example of something that's easier to get wrong in ProseMirror?
