### ISSUE TITLE
`prosemirror-schema-list` reference documentation cites incorrect usage of `addListNodes`

### ISSUE THREAD

**Issue by dslatkin** [ProseMirror/prosemirror#1427]
The reference manual page for `prosemirror-schema-list` gives [the following instructions](https://prosemirror.net/docs/ref/version/0.20.0.html#schema-list.addListNodes) for how to use `addListNodes` to merge schemas:

> Using this would look something like this:
> 
> ```js
> const mySchema = new Schema({
>   nodes: addListNodes(baseSchema.nodeSpec, "paragraph block*", "block"),
>   marks: baseSchema.markSpec
> })
> ```

but that doesn't work for me using up-to-date ProseMirror dependencies, I instead had to use `baseSchema.spec.nodes` and `baseSchema.spec.marks`. I tried to hunt down the text to suggest the change myself, but closest match I could find was in [`prosemirror-schema-list`'s README](https://github.com/ProseMirror/prosemirror-schema-list/tree/master/src) which which is _actually correct_, strangely enough.

**Comment by marijnh** [comment]
Where are you reading this? Because the [reference](https://prosemirror.net/docs/ref/#schema-list.addListNodes) also seems to be up to date.

**Comment by marijnh** [comment]
Ah, you have a `/version/0.20.0` in that URL. Remove that.
