### ISSUE TITLE
NVDA reads "blank" when line is a single custom node with no other content

### ISSUE THREAD

**Issue by krmayer** [ProseMirror/prosemirror#1428]
Hello!

We are trying remediate an a11y issue where a custom node does not properly announce if it is the only content on a line.

Possible workarounds:
- Adding a space (or any content anywhere on the line) in PM fixes the issue (see video below)
- contenteditable="true" fixes the issue, but introduces a host of other issues. We don't expect our users to be able to change the content of these custom nodes directly.

Our dependencies:
```
  prosemirror-model: 1.19.3
  prosemirror-state: 1.4.3
  prosemirror-view: 1.32.2
```

This repros in [Dinos in the document](https://prosemirror.net/examples/dino/):

[video](https://github.com/ProseMirror/prosemirror/assets/38448036/90596fb2-677b-4865-bc73-2e0bd6e370e3)

_Note the "blank" that reads out unless I insert content next to the dino._

NVDA settings we use for compliance testing:
<img width="795" alt="image" src="https://github.com/ProseMirror/prosemirror/assets/38448036/608729b4-6be6-4b6d-b87a-be410cba0abf">

**Comment by marijnh** [comment]
Does adding an `alt` or `aria-label` attribute help? The fact that the problem goes away when there is any text makes this sound like an NVDA bug. Finding workarounds for those can be tricky. Sometimes a `user-select: text` style can also affect stuff like this.

**Comment by krmayer** [comment]
Thanks for getting back to me so quickly. It's definitely possible that this is an NVDA issue! 

No success so far. For reference, I tried:
- alt / arial-label attributes
- "user-select: text" style applied to every and all components in the hierarchy for this node

One workaround I am exploring:
1. Detect the nodes in question using cursor position / pm-view state
2. Silence pm NVDA announcements entirely until another pm action occurs
3. Read relevant details using a separate announce region

A bit hacky but maybe the best we can do here.
