### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by mattberkowitz** [ProseMirror/prosemirror#143]
After getting the latest code I am no longer able to run the local demo.

Firstly, running `npm run demo` gives a module error, which I solved by running `npm install babel-core --save-dev`

After that `npm run demo` executes correctly. Navigating to http://localhost:8080 gives a console error "Uncaught SyntaxError: Unexpected token import" Which seems to indicate the transformer isn't converting the es6.

I've also tried updating the moduleserve package to 0.5.0 which is slightly newer to no avail.

I'll keep poking around and post solutions as I find them.

**Comment by marijnh** [comment]
I get the same problem when I reinstall babel-core (which indeed, was missing from package.json). The new version somehow doesn't find `.babelrc` when loaded in the way that the transform loads it, and thus doesn't do any actual transformation. I haven't been able to figure out why that is.

**Comment by mattberkowitz** [comment]
Ok, got it running. You need to:

`npm install babel-core`
`npm install babel-preset-es2015`

and make the change mentioned https://github.com/marijnh/moduleserve/issues/1

**Comment by marijnh** [comment]
Attached patch specifies the dependency and bumps the moduleserve version dep to 0.6.0. This fixes the issue for me. Could you verify?

**Comment by pboysen** [comment]
I spent all yesterday trying to fix the same thing.  I found that .babelrc must be in the source path or a parent.  I then had to install the presets as a module in the same directory as .babelrc.  It all depends on how your project is laid out.

**Comment by mattberkowitz** [comment]
@marijnh Works great!
