### ISSUE TITLE
navigator.platform deprecated

### ISSUE THREAD

**Issue by tg44** [ProseMirror/prosemirror#1434]
The docs; https://developer.mozilla.org/en-US/docs/web/api/navigator/platform

The code; https://github.com/ProseMirror/prosemirror-keymap/blob/master/src/keymap.ts#L5C1-L6C1

We should probably use something like; https://github.com/faisalman/ua-parser-js/blob/master/src/main/ua-parser.js#L769-L776

**Comment by marijnh** [comment]
I know, but until viable alternatives exist, or browsers actually start dropping it, we're going to have to continue to use it.
