### ISSUE TITLE
Question: is link editing supported?

### ISSUE THREAD

**Issue by c-antin** [ProseMirror/prosemirror#1439]
How does one edit a link (a tag with href)? Selecting the link text and clicking on the link button removes the link entirely (tested in Chrome).

Expected behavior: after selecting the link text and clicking on the link button, the link modal pops up and one can edit or remove the link.

**Comment by marijnh** [comment]
Clear and re-add the link. Or implement that modal yourself. Or load some extension that does that. This is out of scope for the ProseMirror core libs.
