### ISSUE TITLE
toggleMark will also toggle the whitespaces before except Firefox

### ISSUE THREAD

**Issue by Stardusten** [ProseMirror/prosemirror#1442]
In browser (Firefox), everything is fine:

![pmbug2](https://github.com/ProseMirror/prosemirror/assets/38722307/50855d0a-d9f8-45fb-9eee-a8677c722099)

But in Tauri, something strange happened, the whitespaces before will also be toggled to code:

![pmbug1](https://github.com/ProseMirror/prosemirror/assets/38722307/59f05a86-50a1-482b-88b4-a5268818c409)

**Comment by Stardusten** [comment]
I just tried Electron, and has the same problem.

**Comment by marijnh** [comment]
What, exactly, are you doing in that video? Pressing a keyboard shortcut to toggle code mark after pressing the space? Does this reproduce in Chrome?

**Comment by Stardusten** [comment]
> Does this reproduce in Chrome?

No, I tried the editor on ProseMirror's official website in Chrome, and everything seems fine. I will do some test to clarify this next.

**Comment by Stardusten** [comment]
I can reproduce this issue in Chrome Version 120.0.6099.71. I create a minimal reproduction repository for this: https://github.com/Stardusten/pm-test

Here are the core codes:

```vue
<script setup lang="ts">
import {EditorState} from "prosemirror-state";
import {EditorView} from "prosemirror-view";
import {Schema} from "prosemirror-model";
import {schema} from "prosemirror-schema-basic";
import {addListNodes} from "prosemirror-schema-list";
import {exampleSetup} from "prosemirror-example-setup";
import {onMounted} from "vue";

const mySchema = new Schema({
  nodes: addListNodes(schema.spec.nodes, "paragraph block*", "block"),
  marks: schema.spec.marks
})

onMounted(() => {
  new EditorView(document.querySelector("#editor"), {
    state: EditorState.create({
      schema: mySchema,
      plugins: exampleSetup({schema: mySchema})
    })
  })
})
</script>

<template>
  <div id="editor"></div>
</template>
```

**Comment by marijnh** [comment]
That repository (running `npm run dev`) gives me a weird mess of a page that isn't loading the ProseMirror style sheet. If I fix that, the problem goes away. So I think that's going to be your solution.

**Comment by Stardusten** [comment]
It works! Thanks a lot.
