### ISSUE TITLE
Discuss forum down, 500 error

### ISSUE THREAD

**Issue by philiprenich** [ProseMirror/prosemirror#1443]
I'm getting a 500 server error when trying to access https://discuss.prosemirror.net/

That's it, that's the bug :)

**Comment by marijnh** [comment]
Odd. It's working for me. There haven't been any recent upgrades. Does clearing local data/cookies for the domain change anything?

**Comment by coder5506** [comment]
Came here looking just for this.  I've been getting 500s for about 24-hours now: chrome, firefox, curl, windows, linux, US, and Canada.  Pretty sure something's up.

**Comment by marijnh** [comment]
I could reproduce now. Disk filled up. Should be better now.

**Comment by coder5506** [comment]
Confirm.  It's back.  Thanks!

**Comment by philiprenich** [comment]
Thank you! (now if I could only remember what forum post I was trying to access! 😅)
