### ISSUE TITLE
Copy a table from a Word document with a link in it

### ISSUE THREAD

**Issue by kbin24** [ProseMirror/prosemirror#1444]
Copy a table from a Word document with a link in it. But after copying it into TIptap, other text will be converted into links.
## Actual in Word Document
![企业微信截图_20240202135802](https://github.com/ProseMirror/prosemirror/assets/37393946/417b1033-27f5-4d76-9128-b3a96d1e52f5)

## In Tiptap
![12313123213](https://github.com/ProseMirror/prosemirror/assets/37393946/943b17a0-04f8-4566-a65c-4471bf6c94b0)

## Reproduction steps

1.  Add a table with links in a Word document
2. Copy Table into Tiptap (https://templates.tiptap.dev/NRmPrnCGJn)

**Comment by marijnh** [comment]
Note that this is not the Tiptap bug tracker. Does the same behavior reproduce when you paste into a plain ProseMirror editor? Can you show me the HTML that is being pasted (for example by setting up a dummy page with a paste event handler that logs `event.clipboardData.getData("text/html")').

**Comment by kbin24** [comment]
> Note that this is not the Tiptap bug tracker. Does the same behavior reproduce when you paste into a plain ProseMirror editor? Can you show me the HTML that is being pasted (for example by setting up a dummy page with a paste event handler that logs `event.clipboardData.getData("text/html")').

Sorry, this error only occurs in Tiptap at present, and is not a ProseMirror bug.
