### ISSUE TITLE
selections not working in Android / iOS

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#145]
On http://prosemirror.net/ , selecting text in Android and iOS flashes and immediately dismisses selection.

**Comment by marijnh** [comment]
Good point. I set up a system that ignores unexpected selection changes to protect against issues with browsers resetting the selection when the tab is focused, but it is indeed likely that this breaks all kinds of things on mobile. I'll rethink the approach.

**Comment by krasnoukhov** [comment]
@marijnh I'm interested in disabling this behavior for now, could you please point me in a right direction? I just couldn't figure out the code that does the thing. That would be much appreciated!

**Comment by marijnh** [comment]
Patch 925e6b5 should help (though I'm still debugging a bunch of other android issues, and haven't even tried on iOS yet).

**Comment by krasnoukhov** [comment]
Thanks for taking care of it! I can confirm that selections works much better on iOS now.
