### ISSUE TITLE
Bug: Duplication of First Character When Switching to Bold/Italic with IME Enabled

### ISSUE THREAD

**Issue by Stardusten** [ProseMirror/prosemirror#1450]
**Platform**
Arch Linux, fcitx5 IME, Chrome 122.0.6261.128

**Screenshots**
When I enable IME (Input Method Editor) and switch to bold/italic font, the first character always duplicates. This issue is demonstrated in the following videos:

[Screencast from 2024-03-18 09-45-04.webm](https://github.com/ProseMirror/prosemirror/assets/38722307/c95d00de-a101-4429-8135-bf240e108b07)

Everything seems fine on Firefox.

**Comment by marijnh** [comment]
Not sure whether to blame Chrome or the IME software, but when this happened, the reported cursor position wasn't actually adjacent to the inserted text, which threw off ProseMirror's composition handling. Attached patch should help.

**Comment by chenyuncai** [comment]
![image](https://github.com/user-attachments/assets/4d670b4f-4a5b-4b33-be93-cfc5b2784a29)
Chrome and edge appears, and firefox works fine。
