### ISSUE TITLE
Speckle Plugin from the guide is not working

### ISSUE THREAD

**Issue by gryzzly** [ProseMirror/prosemirror#1452]
Hey, I‘m following the guide https://prosemirror.net/docs/guide/ and trying to add the simple "specklePlugin". However, for some reason it is not working at all, no text gets yellow background.

I put the code here – https://codepen.io/gryzzly/pen/dyLZRLG?editors=1100 (the block with the red border is the ProseMirror container and can be typed into).

Am I doing something wrong? 

Thanks!

**Comment by marijnh** [comment]
When I try to use the plugin from the guide it works for me. The code seems to try to use a CDN to load ProseMirror, which often causes issues with duplicate modules, that may be the issue.

**Comment by gryzzly** [comment]
Sorry, I assumed for no reason that it will dynamically add speckles to the text and initialised without any content. Once I add some content to the initial state I can see the decorations applied. It’s iterating over the initial doc, and apply method demonstrates that it will maintain the marks in the expected places.
