### ISSUE TITLE
Bug: When typing at the beginning of a line (using Korean IME) with stored marks, composition is failing.

### ISSUE THREAD

**Issue by devunt** [ProseMirror/prosemirror#1458]
### Screen recording
https://github.com/ProseMirror/prosemirror/assets/337728/129245d7-b5dd-41af-95ec-44c291eb07a1

### Details
This seems most likely caused by https://github.com/ProseMirror/prosemirror-view/commit/a2af570ec12da0ac74cb98a3ca15c3b5b2411055.
Downgrading `prosemirror-view` to `1.33.2` solves the issue.

**Comment by marijnh** [comment]
Attached patch should help with this.
