### ISSUE TITLE
The order in which the handleTextInput and compositionend events are executed is affected by the input event

### ISSUE THREAD

**Issue by hhc-start** [ProseMirror/prosemirror#1459]
Same plugin structure, one listens for input events in handleDOMEvents (does nothing) and the other doesn't.
![WVV}@{(N6CCNXLY($ 1FIE0](https://github.com/ProseMirror/prosemirror/assets/81726452/3eaf9948-fd80-4e74-b263-5b939bf1e606)
Then make the IME input.
The order in which input event is not listened (textinput-compositionend-textinput)

![image](https://github.com/ProseMirror/prosemirror/assets/81726452/b61f3aa2-b009-461d-b6cf-740b2b79a920)

The order in which the input event is listened (textinput-textinput-compositionend):

![image](https://github.com/ProseMirror/prosemirror/assets/81726452/1ed5548a-66ca-4129-a617-41537e2a04cc)

This situation causes me to have a problem with the judgment of the end of the IME input, although there are solutions that can be solved in both cases, but there are still some doubts about the input listening affecting the order of events, I hope to answer it. Which should be the normal process.

**Comment by marijnh** [comment]
That seems to be a browser issue. ProseMirror cannot control the order in which DOM events come in.

**Comment by hhc-start** [comment]
Okay, it seems that I have to be compatible with both situations.
