### ISSUE TITLE
Can't define defaultParamHandler

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#146]
I defined a defaultParamHandler with
`defineDefaultParamHandler(widgetParamHandler)`
but it is ignored.  I think the problem is in the order of the handlers below.  I changed the order and it works for me.
```
     exec(pm, params) {
       let run = this.spec.run
       if (!this.params.length) return run.call(this.self, pm)
       if (params) return run.call(this.self, pm, ...params)
       let fromCx = contextParamHandler
       //let handler = fromCx || pm.options.commandParamHandler || defaultParamHandler
       let handler = defaultParamHandler || pm.options.commandParamHandler || fromCx
       if (!handler) return false
       handler(pm, this, params => {
          if (params) {
           if (fromCx) withParamHandler(fromCx, run.bind(this.self, pm, ...params))
           else run.call(this.self, pm, ...params)
         }
       })
     }
```

**Comment by marijnh** [comment]
Menus define and force their own param handlers, so that you get those nice integrated UIs when executing a command from the menus... but this whole paramhandler thing isn't really working out I think. It probably makes more sense to drop menu-specific param handlers and try to do everything through a single handler, maybe passing it a hint that allows it to be placed in the appropriate position if it wants to.

**Comment by marijnh** [comment]
(Or maybe even the integration of command parameters and UI elements is a bad idea and not flexible enough. If you have other ideas for how to approach this, do comment.)

**Comment by pboysen** [comment]
Decoupling the menu from commands might be a good idea and simplify the command structure.  Each menu item could include something like `command: "blockquote:wrap"` which takes care of many use cases. I found the `select:` coupling in command to be confusing and found in some cases I had to `select: { return true}` for the menu item to appear. 

From a UX perspective, I expect complaints by having items appear/disappear.  Enable/disable would be better so the menu stays static.

When modifying a node, the nodetype already defines the attributes. Could it be used to read/write the attributes during a replace? I do like your paramtype structure as in:
```
["text","number","range","email","url","date"].map(type =>
  paramTypes[type] = {
    render(param, value) {
      return elt("input", {
    	 type,
         placeholder: param.label,
         value,
         required: "required",
         autocomplete: "off"})
  },
  read(dom) {
    return dom.value
  }
})
```
I hope you keep it.  Maybe you could have a hook for readParams which we can override.

I am sure these ideas raise issues.  Glad to help in any way I can.  My latest build is at [ProseMirror Widgets](http://pboysen.github.io/)

**Comment by marijnh** [comment]
My recent changes should address this. They will probably create new problems, but the magic implicitness of the menu structure is gone, and your parameter prompt will always be called.
