### ISSUE TITLE
Redo on Android sets selection to the next position focused after a composition was ended, rather than to where the composition was ended

### ISSUE THREAD

**Issue by Nantris** [ProseMirror/prosemirror#1465]
In other words, after a composition if you tap a new area, then hit undo, and then redo - the redo will set the selection to the tapped area, even though technically the history stack should be only tracking content changes, not selections.

If this is unclear please let me know and I can try to explain with a screen recording.

**Comment by marijnh** [comment]
> though technically the history stack should be only tracking content changes, not selections

That is not how our history is defined. It does this intentionally (and not just on Android), because it is often what users expect.

**Comment by Nantris** [comment]
I wouldn't have expected this to be what most users expect, but I'm sure you've given this more thought than I. Closed as not a bug.

**Comment by Nantris** [comment]
I wouldn't have expected this to be what most users expect, but I'm sure you've given this more thought than I.

Have I just overlooked this on desktop forever? If so, on mobile it feels particularly strange to me.
