### ISSUE TITLE
Cannot click after tables with gapcursor in Firefox

### ISSUE THREAD

**Issue by laurenga** [ProseMirror/prosemirror#1466]
Found when using the demo at https://prosemirror-tables.netlify.app/

I removed the extra text in the example so that the table is the only thing. In Chrome, I find I can see the gapcursor when clicking above / below the table.

In Firefox (v126) the gapcursor never shows when using my mouse to click above / below the table. The only way I can access the area is by using the keyboard to navigate.

**Comment by marijnh** [comment]
I think attached patch should help with this.

**Comment by laurenga** [comment]
Thank you!
