### ISSUE TITLE
removeAttribute draggable on text node is causing issue.

### ISSUE THREAD

**Issue by JagadeepSai** [ProseMirror/prosemirror#1468]
Cause: Happens sometimes when selecting a text node at the start of the paragraph and then clicking anywhere else in the editor. 

Debugger result. 
From deselectNode of clearNodeSelection : 

```
function clearNodeSelection(view) {
  if (view.lastSelectedViewDesc) {
    if (view.lastSelectedViewDesc.parent) view.lastSelectedViewDesc.deselectNode();
    view.lastSelectedViewDesc = undefined;
  }
}

```

```
{
    key: "deselectNode",
    value: function deselectNode() {
      if (this.nodeDOM.nodeType == 1) this.nodeDOM.classList.remove("ProseMirror-selectednode");
      if (this.contentDOM || !this.node.type.spec.draggable) this.dom.removeAttribute("draggable");
    }
  }
```

In the above this.node.type.spec.draggable is undefined. this.dom is #text and doesn't have removeAttribute

<img width="842" alt="Screenshot 2024-05-29 at 12 13 00" src="https://github.com/ProseMirror/prosemirror/assets/24809158/175b2fa9-a662-427a-8c1a-d7d6ac2955ee">
<img width="842" alt="Screenshot 2024-05-29 at 12 13 45" src="https://github.com/ProseMirror/prosemirror/assets/24809158/2b5d6fd6-4e58-46ef-81ad-34367f98cb44">

**Comment by marijnh** [comment]
Attached patch should help.
