### ISSUE TITLE
Bug: “instanceof DecorationSet” not behaving as expected in “prosemirror-view”

### ISSUE THREAD

**Issue by yuri2peter** [ProseMirror/prosemirror#1469]
The file `prosemirror-view@1.33.6/dist/index.cjs` uses `instanceof DecorationSet` to determine whether an object is of type `DecorationGroup`, which generally works well in most cases.

However, I encountered a situation in practical use where this `instanceof DecorationSet` check likely fails, ultimately leading to an error when using the emoji plugin in `tiptap`.

```
Cannot read properties of undefined (reading 'localsInner')
```

After debugging step by step, I confirmed that the exception occurs here:

![image](https://github.com/ProseMirror/prosemirror/assets/23306626/a20cd1b8-3069-4157-aae1-48a0ae8b90d6)
![image](https://github.com/ProseMirror/prosemirror/assets/23306626/e573d1ee-0515-413c-85ef-5879fea83435)

I suspect this is due to subtle differences in `constructor`:

![image](https://github.com/ProseMirror/prosemirror/assets/23306626/5e034bdc-d443-4b45-8b06-c1fbe1163557)

To ensure smooth operation of my project, I temporarily resolved this issue using the following code, which works well.
```
function isDecorationSet(obj) {
  if (!(obj instanceof Object)) { return false; }
  return ['add', 'addInner', 'eq', 'findInner', 'forChild', 'removeInner'].every(
    t => t in obj
  );
}
```

I apologize for not providing a complete reproducible demo (I'm not yet proficient with the related tools.) 
I hope this can assist developers facing similar issues.

**Comment by marijnh** [comment]
Could it be you are loading multiple copies of prosemirror-view, and that is the root of this issue? You don't want that situation anyway (it wastes a lot of bandwidth and script compilation), so the solution here is to fix your dependency tree or bundler.

**Comment by yuri2peter** [comment]
> Could it be you are loading multiple copies of prosemirror-view, and that is the root of this issue? You don't want that situation anyway (it wastes a lot of bandwidth and script compilation), so the solution here is to fix your dependency tree or bundler.

@marijnh "It shouldn't generate additional copies; I've locked its version in package.json."

**Comment by marijnh** [comment]
Well, the fact that we use the `instanceof` is intentional, and not something I consider a bug. If your `DecorationSet` instances are failing that check, you are somehow loading multiple instances of the library, and it's up to you to figure out why.
