### ISSUE TITLE
Setting a selected attribute value doesn't work

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#147]
The following didn't set the selected value when displaying a select attribute:  
```
paramTypes.select = {
  render(param, value) {
    let options = param.options.call ? param.options(this) : param.options
    return elt("select", null, options.map(o => elt("option", {value: o.value, selected: o == value}, o.label)))
  },
  read(dom) {
    return dom.value
  }
}
```
The problem is that the selected: field is ignored when rendered.  I had to add the if statement:
```
field = elt("select", {name}, (param.options.call ? param.options(pm) : param.options).map(o => elt("option", {value: o.value}, o.label)))
if (val) field.value = val
```

**Comment by marijnh** [comment]
I think the problem is that I'm setting `selected="false"`, which browsers will interpret as "the selected attribute is present and this option is selected". Does [this patch](https://github.com/ProseMirror/prosemirror/commit/457cd268564dd486454839dfdb7b6c05f8b25c08) help?

**Comment by pboysen** [comment]
That doesn't work but `selected: o.value == value ? "true" : null` does.
BTW, I refactored all the parameter handling and it works great except for #146.
