### ISSUE TITLE
Where do I download the editor? How do I set it up?

### ISSUE THREAD

**Issue by eldoy** [ProseMirror/prosemirror#1486]
Why isn't there a link to just download a per-built editor from the home page? I've spent 15 minutes just clicking on everything just to find a download link.

There's also no example that I can find on how to build the system. Couldn't this just also be on the home page?

https://stackoverflow.com/questions/49646053/building-and-running-prosemirror/65866825#65866825

**Comment by marijnh** [comment]
> Why isn't there a link to just download a per-built editor from the home page?

Because that's not how this software works. You cannot just drop it in and have an editor. It's just a library that can help you build an editor. As such, users are expected to know enough about npm and JS build tools to be able to use a set of npm packages.

**Comment by eldoy** [comment]
Sound like you got offended or something, just trying to help you with the UX.

Not sure why you insist on making everyone figure it out on their own instead of just providing a copy-paste recipe, so we can start playing with it immediately, that's weird. Those stackoverflow answers work 100% to get a basic editor working.
