### ISSUE TITLE
Missing trailingBreaks when Widget decorations are used

### ISSUE THREAD

**Issue by MathiasFavro** [ProseMirror/prosemirror#1487]
I believe trailingBreaks are no longer added to all expected locations when a transaction that modifies widget decorations is dispatched. I bisected down the changed behaviour to `prosemirror-view` version `1.31.0` and the commits do mention decorations. Debugging the in the client also lead to `updateChildren` but that is how far I got.

My simplified repro is a widget decoration to show placeholder text and a transaction to replace the content of a document:

```typescript
new Plugin({
	props: {
		decorations: function(state: ProseMirror.EditorState): ProseMirror.DecorationSet {
			let onlyEmptyParagraphs = true;

			state.doc.forEach(function(node: ProseMirror.ProsemirrorNode): void {
				if (node.type != schema.nodes.paragraph || node.content.size > 0)
					onlyEmptyParagraphs = false;
			});

			if (!onlyEmptyParagraphs)
				return DecorationSet.empty;

			let widget = Decoration.widget(0, function(): Element {
				let element = document.createElement("div");
				element.innerHTML = "Start writing your ideas here...";
				return element;
			});

			return DecorationSet.create(state.doc, [widget]);
		},
	},
});
```

To trigger the bug dispatch a transaction to replace the doc content with two nodes:
```typescript
state.tr.replaceWith(0, state.doc.content.size, [
	schema.nodes.code_block.create(),
	schema.nodes.paragraph.create(),
]);
```

Testing in Chrome:

Document with a single empty paragraph, before transaction:
<img width="672" alt="image" src="https://github.com/user-attachments/assets/89f0e2de-e704-4acc-ab11-bb06de33d483">

After transaction with prosemirror-view `1.30.2`: Both blocks have trailing break
<img width="456" alt="image" src="https://github.com/user-attachments/assets/f04f9e12-5ecf-44ea-afb1-e93763de4c2e">

After transaction with prosemirror-view `1.31.0`: Paragraph has no trailing break, leaving it collapsed.
<img width="454" alt="image" src="https://github.com/user-attachments/assets/ab7ce7ec-446c-4f09-9a54-d7ede6d44ed7">

The bug is not reproduced if the plugin is removed or modified to not branch, ie always return either the `DecorationSet` or `empty`, or if the transaction inserts two paragraphs. It also works as expected when the editor is loaded with the resulting document, so it appears limited to updating.

Thank you and have a good day.

**Comment by marijnh** [comment]
Thanks for the reproduction! Attached patch should help.
