### ISSUE TITLE
make NodeType.groups public

### ISSUE THREAD

**Issue by YousefED** [ProseMirror/prosemirror#1489]
I noticed NodeType.groups is marked as `internal`: https://github.com/ProseMirror/prosemirror-model/blob/a57531574336d00df43a68e3a2f69582b426033e/src/schema.ts#L62. 

I think it can be quite useful for consumers in case nodes are part of multiple groups. Makes sense to expose it so that types are properly exported? Or is there a specific reason it's marked as internal?

**Comment by marijnh** [comment]
What is the use case where you need to enumerate the groups a node is part of? The general idea behind groups is that they allow you query whether a node is part of a given group with `.is()`. I haven't run into a situation where I need to find a node's groups.

**Comment by YousefED** [comment]
That'd be my use-case indeed. Which `.is()` do you mean? I feel like I'm missing something obvious but I don't see it on Node or NodeSpec

**Comment by marijnh** [comment]
[`NodeType.is`](https://lezer.codemirror.net/docs/ref/#common.NodeType.is), which accepts both node names and group names.

**Comment by YousefED** [comment]
I think you're referring to the lezer docs. As far as I see from browsing Prosemirror source code / types / docs it's not available in prosemirror?

**Comment by marijnh** [comment]
Wow, indeed, I was somewhere else entirely—wrong `NodeType` class for this repository.

Would an `isInGroup(group: string) => boolean` method cover your use case?

**Comment by YousefED** [comment]
Ha I thought I was going crazy!

Yes your suggestion would be perfect 👍

**Comment by marijnh** [comment]
Done in attached patch.
