### ISSUE TITLE
Creating new block breaks typing on Android

### ISSUE THREAD

**Issue by hannesstruss** [ProseMirror/prosemirror#149]
On prosemirror.net, when moving the caret to the end of a block and pressing enter, typing in the new block is broken: First pressing Space doesn't work, then after a while the caret jumps to the beginning of the line and no typing works anymore.

Tested in Chrome 47.0.2526.83/Android 6.0.1.

Screencast: https://youtu.be/ziX7EviUnIM

Potentially related to #80 

cc @forresto

**Comment by forresto** [comment]
The jump changing "doesn't" might be related to https://github.com/ProseMirror/prosemirror/issues/96

**Comment by hannesstruss** [comment]
It doesn't seem to happen with keyboards that have autocorrect disabled.

**Comment by hannesstruss** [comment]
This seems to work a lot better on Chrome/Android now. Marshmallow webview still has problems: https://www.youtube.com/watch?v=A9sHjI5k7KM&feature=youtu.be

**Comment by hannesstruss** [comment]
I can't confirm 100%, but it seems to happen when autocorrect is enabled and I hit backspace. Sometimes, but not always, errors are logged:

![screen shot 2016-03-10 at 16 46 25](https://cloud.githubusercontent.com/assets/115381/13674964/d592fb98-e6df-11e5-9c98-d396442f8d79.png)

**Comment by hannesstruss** [comment]
This seems to be fixed now! 🙌
