### ISSUE TITLE
Deleting all content crashes editor with `docFormat` of "markdown"

### ISSUE THREAD

**Issue by zane** [ProseMirror/prosemirror#15]
## Repro Steps
1. Navigate to the [Markdown editing demo](http://prosemirror.net/demo_markdown.html)
1. Delete all the content
1. Check the "WYSIWYM" radio button
1. Enter some text
1. Check the "Markdown" radio button

## Expected Results
The markdown `textarea` shows the entered text.

## Actual Results
The markdown `textarea` is empty.

## Notes
The JavaScript console shows the error: `demo_markdown_built.js:3841 Uncaught TypeError: Cannot read property 'cmp' of undefined`

**Comment by marijnh** [comment]
There's an invariant that each document contains at least one valid cursor position, and the format conversion functions weren't enforcing this. Fixed in 92f8e1e2e7

**Comment by zane** [comment]
Awesome. Thanks!
