### ISSUE TITLE
Enter at the start of a non-paragraph textblock should (optionall) create a regular paragraph

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#152]
Similar to what is done at the end of a code block/header. Add a flag to the node type that controls this behavior.

**Comment by pboysen** [comment]
Is this related to the problem I am having with a [Choice List]( prosemirror-widgets/src/widgets/answertypes/choicelist.js)?  Because the node begins with a non-editable radiobutton, the focus needs to move to the next editable node when I add.

**Comment by marijnh** [comment]
@pboysen Probably not -- that doesn't sound like what I'm talking about.
