### ISSUE TITLE
History backToVersion() resets to 0 when version is current

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#156]
Essentially `pm.history.backToVersion(pm.history.getVersion())` seems to always set it to version 0. It does however seem to work when actually going backwards. Fixing this makes providing a cancel that runs `pm.history.backToVersion(saved_version)` work.

Tested with chrome 48.0.2564.82 with current master (https://github.com/ProseMirror/prosemirror/commit/daff791f46cc9ceaa42460a64314c1988f67ba18) and on demos on website.

From basic demo dev console:
```
> pm.history.getVersion()
Object {id: 1, version: 0}
> pm.history.getVersion()
Object {id: 7, version: 6}
> currentVersion = pm.history.getVersion()
Object {id: 7, version: 6}
> pm.history.backToVersion(currentVersion)
> pm.history.getVersion()
Object {id: 7, version: 0}
```

**Comment by wes-r** [comment]
Also - it would be preferable if backToVersion was moveToVersion as I may provide a version forward or backward. This handles the case where use goes to edit, hits undo of previously saved version, hits cancel (resulting in currentVersion being **less** than saved_version).

**Comment by marijnh** [comment]
Attached patch fixes this. Making it move forward isn't really an option, since the editor doesn't keep the information needed to do that (the redo history is discarded every time an edit is made).
