### ISSUE TITLE
Overloading 'insert' commands to update nodes is non-obvious in current menu style

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#157]
When you had just the image icon, it still sort of made sense to select an image and click it to change that image's attributes. But now that this functionality has moved to `Insert > Image' (which seems on the whole an improvement in discoverability), it is unlikely that users will figure out the update functionality.

One approach would be to also expose the same functionality using an overlay (#132) icon on the selected image.

**Comment by pboysen** [comment]
I think this is in the eye of the beholder.  It didn't make as much sense to me to click on something to insert and click on it again to modify but every user is different.  To overcome that, my [demo](http://pboysen.github.io) displays an edit icon when you hover.  Insert a short answer widget and then hover and click on the icon.  This isn't perfect, especially for an image but it was done with simple CSS and a handleClick.  You can probably find a better way.

**Comment by marijnh** [comment]
Since I'm gong to move UI concerns out of the core library, I'm closing this. Users will be responsible for their own menu structure, in which they can approach this problem in whichever way feels appropriate.
