### ISSUE TITLE
Dropdown menu unicode characters aren't widely supported

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#158]
The wide-flat triangles look good but seem to turn into a placeholder square on at least Macs. Maybe switch to a CSS triangle.

**Comment by forresto** [comment]
![screen shot 2016-01-31 at 10 53 02 am](https://cloud.githubusercontent.com/assets/395307/12703120/e8664428-c808-11e5-9bf5-a2c730495d54.png) (mac)

**Comment by marijnh** [comment]
The patches I pushed today fix this by using a CSS triangle instead.
