### ISSUE TITLE
Drag and Drop Images

### ISSUE THREAD

**Issue by wbw20** [ProseMirror/prosemirror#16]
Do you plan on supporting dragging and dropping of images into Prose Mirror in the future?

**Comment by marijnh** [comment]
Doesn't this already work? Or are you dragging an actual file? If so, that's not something that ProseMirror is going to be able to handle on its own (except by embedding the image as a data URL, which is usually not what you'd want), so this would have to be a plugin of some kind.

**Comment by wbw20** [comment]
Ah, I was testing with a local image from my desktop.  DnD works with images from google.
