### ISSUE TITLE
tooltipMenu shows both inlineItems and blockItems when whole block is selected

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#164]
I customized [inlineItems and blockItems](https://github.com/the-grid/ed/blob/39d6159794d9119dd627d59a6fd66cda5c580a02/src/menu/ed-menu.js#L22-L30), and there is overlap, so when I select the whole block I get: 

![screen shot 2016-01-31 at 10 35 48 pm](https://cloud.githubusercontent.com/assets/395307/12727570/918705be-c8eb-11e5-9bb2-f8e28ebc1ab6.png)

I'm assuming that PM concats those menus in that case, which makes sense, but I'd like to control which items show up in that situation.

https://github.com/the-grid/ed/issues/43

**Comment by forresto** [comment]
On this topic, it would be nice to define different options when caret in an empty block. I don't expect to be able to select a whole paragraph then "insert horizontal rule" to replace it. I'd expect to have "insert hr" option only on a blank line.

**Comment by marijnh** [comment]
Attached patch might help there. But note that it was preceeded by some patches that very much changed the way menus are defined and configured, so you won't be able to use it without some work.
