### ISSUE TITLE
demo 0.2.0 from npm does not not work

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#165]
First I noticed that there is no demo folder (but on github src that seems fixed already), I copied folder from the sources, then I run the `npm run demo` again, now the demo site loaded, but with an error:

`Uncaught SyntaxError: Unexpected token import`

on mac, and with latest chrome

**Comment by forresto** [comment]
Demo is excluded from npm: https://github.com/ProseMirror/prosemirror/blob/master/.npmignore

You probably want to check out the repo, `npm install` and `npm run demo`

**Comment by rsaccon** [comment]
ok, thanks, missed that. So all is fine, gonna close this.
