### ISSUE TITLE
SelectionChange event listener get stuck in endless loop

### ISSUE THREAD

**Issue by willdunning** [ProseMirror/prosemirror#168]
Calling `ProseMirror.selection` inside of a `ProseMirror.selectionChange` event handler causes an infinite loop. Using an UpdateScheduler I can work around this issue, but it would it be possible to just pass the selection object as an argument to the `ProseMirror.selectionChange` event?

**Comment by marijnh** [comment]
Oh, that's bad. Attached patch should help.
