### ISSUE TITLE
Link rendering inconsistency with `docFormat` set to "markdown"

### ISSUE THREAD

**Issue by zane** [ProseMirror/prosemirror#17]
## Repro Steps
1. Navigate to the [Markdown editing demo](http://prosemirror.net/demo_markdown.html)
1. Click the "WYSIWYM" radio button to toggle to WYSIWYM view
1. Select the word "comment" (any undecorated text would do)
![select a word](https://monosnap.com/file/2qGypkCXDjqb9qzkcocO1IEvLXDXnB.png)
1. Click the button for creating a hyperlink
1. Enter in "Google" for the title and "http://www.google.com" for the URL
![fill out the form](https://monosnap.com/file/m5klzKaeyvOmmN2oWJAcD6HnFupmoW.png)
1. Note that the selected text is now a hyperlink
![selected text is hyperlinked](https://monosnap.com/file/AbgBLBL7rGBHUHgonO4upo8hXYZtkC.png)
1. Click the "Markdown" radio button to toggle to markdown view
1. Click the "WYSIWYM" radio button to toggle to WYSIWYM view

## Expected Results
The selected text would be as it appeared before briefly toggling to markdown view.
![selected text is hyperlinked](https://monosnap.com/file/AbgBLBL7rGBHUHgonO4upo8hXYZtkC.png)

## Actual Results
The selected text is no longer hyperlinked, and is instead rendered as `[selected text](http://www.google.com Google)`
![selected text is rendered as raw markdown](https://monosnap.com/file/zcQE6VhXbKeEoPNUcfFt298TJ1tyIo.png)

**Comment by marijnh** [comment]
I was doing quoting of link targets incorrectly in the Markdown serializer. Should be better now.

**Comment by zane** [comment]
Thanks for the quick turnaround!
