### ISSUE TITLE
Recognize enter-like dom changes (on Chrome Android)

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#175]
Chrome Android does not fire key events that allow us to detect or capture enter presses. This means that we aren't able to apply ProseMirror's various keybindings for Enter.

We could set up applyDOMChange to recognize changes that look like they originated from an enter press (textblock split, no further input), and apply the enter bindings in that case.

**Comment by forresto** [comment]
This has a side-effect with my [Media div node type](https://github.com/the-grid/ed/blob/caa8ca786e3fd4e03d0e6e1ca1cf57de430e4c81/src/schema/media.js)... apparently Android injects a div on enter, which PM parses (?) and turns into a Media div.

**Comment by marijnh** [comment]
Unconditionally parsing `<div>` tags a media elements isn't a good idea in general -- if someone pastes or drags some arbitrary HTML into your editor, there are likely to be `<div>` elements in it, which will cause the same confusion. Add an attribute that explicitly marks your node type, and have your parser return `false` when it doesn't find the attribute.

**Comment by forresto** [comment]
Thanks for that advice; it fixed that predicted pasting-random-div issue.

**Comment by marijnh** [comment]
Attached patch tries to implement this. It looks for split blocks, with no text between the split, which seems like a good heuristic. Do test.
