### ISSUE TITLE
Node selections can't be cut

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#176]
Node selections should be able to be cut and pasted. This will cover similar user experience terrain as #127.

**Comment by marijnh** [comment]
Right. The problem is that the browser doesn't consider the editable content to be focused when we have a node selection. So I guess we'll have to set some kind of dummy selection in that case after all. I'll look into it.

**Comment by marijnh** [comment]
That patch should help, and also provides a more elegant way to deal with browsers randomly resetting a cursor when a contentEditable element is focused but has no selection.

**Comment by ericandrewlewis** [comment]
This works well, I think we can close this ticket.
