### ISSUE TITLE
LaTeX and Table Support

### ISSUE THREAD

**Issue by Immortalin** [ProseMirror/prosemirror#18]
It would be really great if prosemirror can be used to edit scientific documents a la overleaf.

**Comment by marijnh** [comment]
Table support is [planned](https://github.com/prosemirror/prosemirror/tree/master/Plan.md), and you could define a LaTeX output format if you are so inclined.

**Comment by ForbesLindesay** [comment]
It would be great to have some kind of equation editor.  I would imagine that would be something to implement as a plugin though.

**Comment by RoyiAvital** [comment]
Math is a must :-).

Something like [Madoko](https://www.madoko.net/) would be amazing.

**Comment by arekkas** [comment]
I believe what @Immortalin was getting at is not LaTeX as an output format but rather inline math formulas. However, this should be possible by adjusting the [dino demo](http://prosemirror.net/demo_dino.js) with something like `<p><span contenteditable="false">$3>1$</span></p>` as inline formula editing is a completely different scope.

**Comment by Immortalin** [comment]
@arekkas that's exactly what I meant

**Comment by Immortalin** [comment]
@marijnh see this: https://github.com/asselinpaul/medium-editor-handsontable/blob/master/README.md

**Comment by ericandrewlewis** [comment]
@pboysen has implemented an inline math node type which is a wrapper around [MathJax](https://www.mathjax.org/), see [his demo](http://pboysen.github.io/). I'm not sure if it supports all of LaTeX, as I'm not too familiar with that standard.

**Comment by pboysen** [comment]
I have found equations that didn't work but my assumption is that it is a MathJax problem.

**Comment by RoyiAvital** [comment]
@pboysen, Could you please share those equations?  
Could you check them on StackEdit?

Thank You.

**Comment by pboysen** [comment]
Sorry, I don't remember the equations.  I was pulling them from examples on MathJax and other web sources.

**Comment by arekkas** [comment]
By the way, nice example. Looks posh. So looking forward to use PM for my projects.

**Comment by RoyiAvital** [comment]
MathJax even supports \begin{align} enviorment, so it should be pretty good.

**Comment by saulpalv** [comment]
https://benrbray.com/prosemirror-math/
