### ISSUE TITLE
In the latest git release, setNodeType erases all content

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#185]
To see,

- go to [prosemirror-widgets](http://pboysen.github.io)
- Insert > Question > MultipleChoice
- Click below settings icon and enter some text
- Click next to radiobutton, enter some text and press Enter
- Click on settings icon and save.
All the content will be replaced with a new node

Code is [here](https://github.com/pboysen/prosemirror-widgets/blob/master/src/widgets/questions/multiplechoice.js).

I would like to derive from insert, but I need to have the already selected node of the type I am updating to just update the attributes.  Not sure if you want that in your code.

**Comment by marijnh** [comment]
I didn't install prosemirror-widgets, but if I make a simple `setNodeType` call on a demo, I don't see this happen.

    pm.tr.setNodeType(pm.selection.anchor.shorten(), pm.schema.nodes.heading, {level: 3}).apply()

That makes my current paragraph a heading, without erasing its content.

**Comment by pboysen** [comment]
I didn't expect you to install it, just observe its behavior.  It may be in the complexity of node being changed since it includes some mixed children types. I will look for a simpler example.

**Comment by pboysen** [comment]
Turned out to be a bug in my create code.
