### ISSUE TITLE
MenuCommandSpec - Icon Class

### ISSUE THREAD

**Issue by paulsputer** [ProseMirror/prosemirror#189]
Is it possible to define a class for the icon display of a MenuCommand?  It would be useful to reference icons from FontAwesome to save the need of generating an svg, i.e.

`menu { display: { type:"icon", text:"", class:"fa fa-header"} }`

I noticed http://prosemirror.net/ref.html#MenuCommandSpec provides a class attribute but I get an error about the space if I put something like `fa fa-header`.  Am I missing something or is there a design reason for this?

**Comment by paulsputer** [comment]
Sleeping on this I think allowing HTML in the text field would probably result in fewer changes and be more useful than a class field.

`menu { display: { type:"icon", text:"<i class='fa fa-header'></i>"} }`

**Comment by marijnh** [comment]
You can put a single class name in there, not multiple ones.

I am not really interested in allowing raw HTML in my API, since that makes script injection vulnerabilities a lot more likely.

**Comment by paulsputer** [comment]
Ok, thanks @marijnh.  Would support for multiple class names be a desirable PR?

**Comment by marijnh** [comment]
Did you notice that you can put a `render` method on your `display` object, and just take full control over the command's representation? It sounds like that may be what you are looking for.

**Comment by paulsputer** [comment]
Ah I saw one for `DropDown` but didn't notice `MenuCommand` had one too, I thought it would have been a bit odd.  Yes that will do the job, perfect.  Thanks!
