### ISSUE TITLE
Switching to markdown and back changes the text

### ISSUE THREAD

**Issue by ameliusg** [ProseMirror/prosemirror#19]
This is not a serious bug (AFAIAC), just something I found while trying out the demo.
The video below best describes the issue.
https://www.youtube.com/watch?v=UL4W1u9sPE4

Note that the selection includes a leading space.

**Comment by jeremiak** [comment]
We're having the same issue, as reported in 18f/federalist#201. If we select text (including a leading space) and click the italic button in the menubar, prosemirror renders the text with italics, but the underlying markdown isn't correct in the same manner as shown in @ameliusg's video.

**Comment by krasnoukhov** [comment]
Just ran into the same issue but with trailing space.

**Comment by ericandrewlewis** [comment]
ProseMirror uses [markdown-it](https://github.com/markdown-it/markdown-it) for markdown parsing. markdown-it is an implementation of [CommonMark spec](http://spec.commonmark.org/), and this behavior is true to the spec. 

This exact behavior ("a * foo bar*" not converting to emphasis) is [the subject of example 323 in CommonMark spec](http://spec.commonmark.org/0.24/#example-323).

Suggest close here.

**Comment by patternseek** [comment]
@ericandrewlewis The problem then is the markdown that ProseMirror is generating doesn't match its internal model. The fix would seem to be to place the opening asterisk(s), after any initial whitespace, and the closing asterisk(s) before any trailing whitespace.

**Comment by patternseek** [comment]
We're having this issue frequently with end users. Any selection which the user makes bold or italic which starts or ends with one or more spaces generates invalid markdown (compared to ProseMirror's model). That is, if you export the Markdown and re-import it you don't get the same internal model, you get asterisks in your text.

**Comment by marijnh** [comment]
Moved here: https://github.com/ProseMirror/prosemirror-markdown/issues/1
