### ISSUE TITLE
Prompt pull request

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#192]
Just checking to see if I messed up the pull request or you saw something wrong with it.

let type = this.paramTypes[param.type], value = type.read.call(this.pm, dom), bad
if (`type`.validate)
    bad = `type`.validate(`dom`)
else if (!value && param.default == null)

I don't think I want to write a validate function for each param of a certain type.

**Comment by marijnh** [comment]
You closed it, so I assumed you reconsided.

I do think allowing validation on individual parameters is useful, but I'm okay with also supporting a general validation method on the type (which is run first).

**Comment by pboysen** [comment]
Sorry, that was a mistake on my part.  I will reissue.

**Comment by pboysen** [comment]
Sorry but I have struggle for hours to get Git and Eclipse to cherry-pick a commit into a branch.  For now, if you would add
```
      if (param.validate)
        bad = param.validate(value)
      else if (type.validate)
          bad = type.validate(dom)
```
to params I would appreciate it.  I think params.validate is more specific than type validation so I listed params first.  That allows you to use both in a project.  Is that ok?

**Comment by marijnh** [comment]
I've pushed attached patch, which allows parameter types to provide a type-specific validate function, which will be called on the field's DOM node.
