### ISSUE TITLE
Site: Fonts broken via HTTPS

### ISSUE THREAD

**Issue by matiaskorhonen** [ProseMirror/prosemirror#197]
The fonts on the site are broken when the site is served over HTTPS:

![screen shot 2016-02-16 at 09 51 28](https://cloud.githubusercontent.com/assets/43314/13070176/1a7071f0-d493-11e5-8b4a-ebf35c0428b7.png)

Google also seems to prefer the HTTPS version, so this is the view that many first time visitors see if they Google for “prosemirror”…

<img width="815" alt="2016-02-16 09-54-37 3luqw" src="https://cloud.githubusercontent.com/assets/43314/13070196/57d9468e-d493-11e5-816e-9d3b087107a1.png">

**Comment by marijnh** [comment]
Fixed via https://github.com/ProseMirror/website/pull/22
