### ISSUE TITLE
Make cursor-motion code aware of multi-word UTF16 code points

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#2]
They are currently treated as a single character, making by-character deletion flaky

**Comment by marijnh** [comment]
The same actually goes for extending characters -- if you have a combining accent character, for example, it should be deleted along with its base characters.

**Comment by ericandrewlewis** [comment]
A fix for extended characters is in #52. Feedback appreciated! :smile: 

@marijnh can you give an example of a multi-word UTF16 code point?

**Comment by marijnh** [comment]
So any Unicode characters in the 'astral planes' (above code 0xffff) will take up two characters in a JS string (UTF-16 encoding). Until JS gets real Unicode support, we're unlikely to even be able to figure out which of these are word characters (I'm not aware of any script in these planes that has lower/uppercase letters, which is currently our main heuristic). So the main issue, for now, is to be able to figure out that two halves of a character pair, for example an emoji, belong together. The extending char regexp from CodeMirror already recognizes the second half of such a pair as an extending character, so your patch seems to have mostly solved this problem.

I've added a pair of tests (80e474c), and am closing this.
