### ISSUE TITLE
Nesting lists

### ISSUE THREAD

**Issue by salzhrani** [ProseMirror/prosemirror#20]
It is currently possible and I was wondering If it is possible to allow the creation of a nesting as in [this](http://www.w3.org/wiki/HTML_lists#Nesting_lists) example?

**Comment by marijnh** [comment]
I don't understand the question.

**Comment by salzhrani** [comment]
Is it possible to create a list like the following ?

<ol>
  <li>Chapter One
    <ol>
      <li>Section One</li>
      <li>Section Two </li>
      <li>Section Three </li>
    </ol>
  </li>
  <li>Chapter Two</li>
  <li>Chapter Three  </li>
</ol>

When I tried I could only accomplish the following

<ol>
  <li>Chapter One</li>
    <li><ol>
      <li>Section One</li>
      <li>Section Two </li>
      <li>Section Three </li>
    </ol>
  </li>
  <li>Chapter Two</li>
  <li>Chapter Three  </li>
</ol>

**Comment by marijnh** [comment]
Ah, yes, you can. Create a list, type something, press enter, and then backspace to move back into the previous list item, and then create the inner list.

Though there is currently a bug where you can't escape out from the inner list into the outer list with enter or backspace. But that'll be fixed soon. See #21
