### ISSUE TITLE
HTML tag like text not properly escaped in Markdown output

### ISSUE THREAD

**Issue by will-hart** [ProseMirror/prosemirror#207]
The markdown parser does not properly handle text that looks like HTML tags - e.g. loading in `<sometext>` causes ProseMirror to fail to render with an error:

    Uncaught Error: Token type `html_block` not supported by Markdown parser

It looks like the editor is not escaping the `<` and `>`. To reproduce - set up an editor for markdown and type in `<test>` the output from `getContent()` will be unchanged - `<test>` Reload the editor using this as the content and you get the above error.

**Comment by marijnh** [comment]
The default schema does not support inline HTML, so there's no node type to build for such tokens. You could build your own nodes for HTML tags and blocks, and wire them up to these tokens. (Or you could wait until someone gets around to doing more work on a Markdown-specific schema.)

**Comment by will-hart** [comment]
Hi @marijnh, it's not to do with interpreting inline HTML in this case. If somebody happens to type something that *looks* like an HTML tag but isn't (i.e. some speculative fiction uses these kinds of things as an alternative to quotation marks) then ProseMirror breaks. 

For instance compare the behaviour of square brackets... type `[test]` and you get `\[test\]`. I believe this should also happen with `<` and `>`

**Comment by marijnh** [comment]
You're right, the Markdown parser should be configured to not look for inline HTML at all. See attached patch.

**Comment by will-hart** [comment]
:+1: Possibly the fastest patch for a github issue of all time? :smile:

**Comment by sielay** [comment]
Actually that made impossible to use BR when converting in/to markdown even, if that's supported by Schema. Can we put it as option in to/from markdown rather than hardcoded thing?

**Comment by sielay** [comment]
Ok. I found way around. It's still tricky. \s\s\r\n is still supported for `hardbreaks` in markdown. Unfortunately editors tempt to truncate line endings, but I sorted out by simple pre-processing. You may ignore previous comment.

**Comment by sielay** [comment]
But (last word) @marijnh as far as I remember markdown by default support HTML embedding and any embedded HTML should be just passed through without escaping. That is also how GitHub does it. Can't we just allow HTML (may be optional) and pass it through `parseHTML`? Most use case people would need is usage of `class` attribute.

**Comment by marijnh** [comment]
The idea is that, when working with the built-in content model of ProseMirror, inline HTML is meaningless and thus can not be parsed. Using `parseHTML` on inline HTML seems like it would create quite a lossy mess. You could implement it (I think the public API is powerful enough to do so), but it doesn't seem like a good default.

**Comment by sielay** [comment]
Then as alternative (as markup is bit lose format) would be to add markdown-it extension that gives attribute support. That is quite widely used standard extension, but would have to be done on PM level (AFAIK)

**Comment by marijnh** [comment]
You can extend the way ProseMirror parses Markdown, and though I haven't tried, I expect the attribute extension adds a new token type, which you could make your ProseMirror markdown converter hook into.
