### ISSUE TITLE
Commands with "derive" are not showing up in the menu

### ISSUE THREAD

**Issue by will-hart** [ProseMirror/prosemirror#208]
I have this simple command (its an example, so no run method) which shows up in the menu bar: 

````
MathsInline.register('command', 'insert', {
  label: 'Maths - Inline',
  menu: {
    group: 'insert', 
    rank: 70, 
    display: {
      type: 'label', 
      label: 'Maths - Inline'
    }
  }
});
```

However if I derive it from the `insert` command it no longer shows up. Am I missing something? 

```
MathsInline.register('command', 'insert', {
  derive: {
    params: [
      {
        attr: 'maths',
        label: 'Maths',
        type: 'text',
        prefill: function doPrefill(pm) {
          const { node } = pm.selection;
          if (node && node.type === this) {
            return node.attrs.maths;
          }
        }
      }
    ]
  },
  label: 'Maths - Inline',
  menu: {
    group: 'insert',
    rank: 70,
    display: {
      type: 'label',
      label: 'Maths - Inline'
    }
  }
});
```

I'm using react-prosemirror with ProseMirror from the master branch. The command exists as it can be called from a click handler.

**Comment by marijnh** [comment]
Interesting. Most of the elements in the default menu are also defined using `derive`, so this isn't something that always happens. Could you dig a little deeper to figure out where yours goes wrong? You can inspect `pm.commands["NODE_NAME:insert"].params` to see whether it has a `menu` property, for example.

**Comment by will-hart** [comment]
The result of `console.log(pm.commands["mathsinline:insert"].params)` with the `derive` section included:

![capture](https://cloud.githubusercontent.com/assets/391950/13251883/c0f5c628-da2a-11e5-92a1-4d08d1404854.PNG)

If I remove `derive` and add `run: () => console.log('run')` instead it shows in the menu but the result of `console.log(pm.commands["mathsinline:insert"].params)` is:

    []

Both of them have a menu object in `pm.commands["mathsinline:insert"].spec" that looks like:

![capture2](https://cloud.githubusercontent.com/assets/391950/13252021/e06906ea-da2b-11e5-908a-0bd9ad88cb6c.PNG)

**Comment by marijnh** [comment]
Could it be that the derived `select` method is always returning false?

**Comment by will-hart** [comment]
Ah, could be. When I `pm.commands["mathsinline:insert"].spec.select()` it has an error:

    Uncaught TypeError: Cannot read property 'doc' of undefined

The default select function is: 

    function(pm) {
      return pm.doc.path(pm.selection.from.path).type.canContainType(this);
    }

Is this a problem with the way I'm parsing or serialising the type? I'm using markdown not HTML.

**Comment by marijnh** [comment]
You can't call it like that, you have to call `pm.commands["mathsinline:insert"].select(INSTANCE)` (no `.spec`, and pass an editor instance)

**Comment by will-hart** [comment]
Oh right yeah, I'm clearly making this up as I go :)  If I `log`pm.commands["mathsinline:insert"].select(pm)` I get `false`. Looking at my type schema I have:

    get contains() { return null; }

Removing this doesn't help.

Let me try switching to HTML instead of Markdown and see if that makes a difference.

**Comment by marijnh** [comment]
`contains` determines what your node can contain. The relevant property is `kind` (and `kinds`), which should match the `contains` of the possible parent nodes.

**Comment by will-hart** [comment]
Ok, I'm not sure I understand what's going on to be honest but I'm using `react-prosemirror` which is on 0.3.0 and doesn't have `NodeKind` exported yet. I can get the menu to work if I explicitly specify kind in my schema type as a string:

    get kind() { return 'inline'; }

![working](https://cloud.githubusercontent.com/assets/391950/13254319/c2eb3db0-da38-11e5-8525-d7c0038986d7.gif)

I'll revisit when the next `ProseMirror` release comes out and `react-prosemirror` lets me use some of the shiny new bug fixes and features :)

**Comment by marijnh** [comment]
Yeah I just revised how this works today. The docs on the site explain how things work in the current release.

**Comment by will-hart** [comment]
OK, thanks for all your help!
