### ISSUE TITLE
Strange disparity between change tracking & undo / redo

### ISSUE THREAD

**Issue by Lewiscowles1986** [ProseMirror/prosemirror#209]
So when trying out your change tracking demo I noticed 

- clicking revert seems to remove the item reverted to
- undo / redo are still very much in-play making things more confusing
- history is destroyed (rather than add a new item saying reverted to XYZ, the revision merely disappears)

It's a fantastic idea, and I'm very happy to have others besides TinyMCE involved, but right now it's confusing, promotes flawed thinking, such as erasure of history, and I think the above issues should be addressed in the demo.

**Comment by marijnh** [comment]
This is how that particular demo works, to keep its complexity in bounds. If you want to design another approach, you're welcome to.

**Comment by Lewiscowles1986** [comment]
I'll stick to TinyMCE; all this would need to work correctly would be to refresh the page and use localStorage. The reason I wrote to you is because it looks silly; it's your product, past raising an issue, there does not seem to be a compelling reason for me to contribute. Thank you for your time

**Comment by ericandrewlewis** [comment]
@Lewiscowles1986 I can't speak for Marijn but I believe he wrote the demos as inspirational ideas of what is possible with ProseMirror. Although the code could be useful to look at, they don't represent canonical feature implementations. 

Others will have to pick up these tasks outside of the demo pages, as they're non-trivial. We (the NYT) are interested in a track changes implementation for ProseMirror, but have yet to start the process.

Also, I don't think the change tracking demo is silly. It's quite impressive to me that a rudimentary implementation of it can be accomplished with so little code, hence the power of ProseMirror's document model.

**Comment by Lewiscowles1986** [comment]
Nor am I suggesting they should, or that the front-end is a reasonable place to fit revision control; but it is given as an example of ProseMirror, and it is an unfortunate state of affairs that copy-pasta is used a lot on the internet, which means many people would be stuck with a broken revision system where revisions and undo/redo interfere with one another.

Far from suggesting the entire system is changed or re-written, perhaps disabling undo/redo on that demo would be enough to mitigate for the people who are not as technical as us, but as a contributor has indicated a lack of interest in the area it's a moot point anyway.

I do hope that you talk to someone at NYT who suggests not using front-end for a revision system; it's an area I have spent a lot of time getting perfect in my own software; and I do get incredibly passionate about making a clear UI for such systems to avoid problems that lead to disconnect between user-expectation, and interaction outcomes.
