### ISSUE TITLE
Serialization to markdown fails when two marks start or end in the same position

### ISSUE THREAD

**Issue by katemihalikova** [ProseMirror/prosemirror#216]
### Steps to reproduce
**Bold text:**
![image](https://cloud.githubusercontent.com/assets/7225023/13292315/8999e83e-db1b-11e5-9588-838db2e7b37e.png)
**Link/code added to one of the words:**
![image](https://cloud.githubusercontent.com/assets/7225023/13292447/11d8bd56-db1c-11e5-9250-e3ed59227994.png)
![image](https://cloud.githubusercontent.com/assets/7225023/13292546/7dd34da0-db1c-11e5-83bc-0f1412fa26ac.png)
![image](https://cloud.githubusercontent.com/assets/7225023/13292522/6900a6de-db1c-11e5-82f6-a659e14c896e.png)
**The markdown output contains mixed marks:**
![image](https://cloud.githubusercontent.com/assets/7225023/13292463/2584c0fc-db1c-11e5-955c-1c1198c9ca03.png) 
![image](https://cloud.githubusercontent.com/assets/7225023/13292555/85530976-db1c-11e5-8fd7-d8de2dd17807.png)
![image](https://cloud.githubusercontent.com/assets/7225023/13292595/a5a99a5a-db1c-11e5-9fe5-4decfa17a65c.png)

### Version
Detected in v0.3.0 and v0.4.0, using Windows Chrome 48. Most recent commit is the v0.4.0 now.

**Comment by ericandrewlewis** [comment]
Thanks for the bug report @katemihalikova! I was able to reproduce this as well.

We'll need to look into how the document is being transformed to Markdown, and whether it's a bug in PM or something to do with [markdown-it](https://markdown-it.github.io/), our Markdown utility library.

**Comment by marijnh** [comment]
It's almost certainly our serializer — markdown-it has been very solid so far. If someone knows of a Markdown-generation library (the escaping is non-trivial), I'd gladly switch to that. If it doesn't exist, we'll just have to continue shaping up ours.

**Comment by asteadman** [comment]
I've observed this behavior but was unable to pin down the source until now. Looking at the code for `renderInline(parent)` in [to_markdown.js](/ProseMirror/prosemirror/blob/572f9118fcbd772ba5f8274c2c5464e143724bd2/src/markdown/to_markdown.js#L126) there appear to be a couple of issues.

Firstly, i'm not sure why the check for a code mark gets special treatment, but I think the `.type == "code"` checks are wrong (.type is not a string?). I think these checks should use the truthy `.isCode` ?

The more general problem seems to be that the stack is always traversed from `k=0` to `stack.length-1`, even when flushing the stack /w [`progress(null)`](/ProseMirror/prosemirror/blob/572f9118fcbd772ba5f8274c2c5464e143724bd2/src/markdown/to_markdown.js#L153), where as the stack should presumably be traversed in the reverse direction when flushing?

**Comment by ericandrewlewis** [comment]
> the stack should presumably be traversed in the reverse direction when flushing

I was diagnosing this at the same time. Yep, that's the problem.

**Comment by asteadman** [comment]
Can you comment on the `.type == "code"` checks? I believe changing them to `.type.isCode` would inadvertently fix the 3rd test case, but i'm not sure why it's there at all. Is the code mark special for some reason? AFAICT, these checks currently never evaluate true, so the whole if statement and corresponding conditional block could presumably be removed.

**Comment by ericandrewlewis** [comment]
> I believe changing them to .type.isCode would inadvertently fix the 3rd test case

#235 fixes the first and third test cases. It seems the second text case will be trickier to fix.

> AFAICT, these checks currently never evaluate true

Yes, good find. Can you open up a separate issue and perhaps a pull request with the change?

**Comment by ericandrewlewis** [comment]
> If someone knows of a Markdown-generation library (the escaping is non-trivial), I'd gladly switch to that. 

I think what we're looking for is a library that supports an abstract syntax tree data type for Markdown (which we can transform our document model into), which also supports converting the AST to Markdown. This would be very desirable given the second test case originally shared on this issue. 

Briefly Googled around for this today. commonmark.js already has an AST representation, and [is discussing adding AST → Markdown support](https://github.com/jgm/commonmark.js/issues/83).

**Comment by marijnh** [comment]
Attached patches, along with b43d167, should address this issue.
