### ISSUE TITLE
Scrolling parent div

### ISSUE THREAD

**Issue by ameliusg** [ProseMirror/prosemirror#217]
Hi,

A small feature request. When moving the caret up or down using the arrow keys or page-up and page-down, then when the caret reaches the end-point (for example, top of the editor contents), then the containing div should scroll (like it would normally when there was no editor component in it).

Another possibility would be to emit an event when this situation happens, then the programmer can decide how to handle this.

I hope this explanation is clear.

Thanks in advance.

**Comment by ericandrewlewis** [comment]
I think scrolling the parent document when a user reaches the end of a ProseMirror document may be unexpected behavior. At that point, we would be defining how the parent document should work, which shouldn't be the responsibility of the editor.

I'm going to suggest closing this, but thanks for opening this and feel free to open further feature requests.

**Comment by marijnh** [comment]
I'm okay with leaving this open and at some point implementing the solution where an event is fired when scrolling past the end of the editor. I've done things like this (moving focus out of editor when arrowing past its start/end) in several projects with CodeMirror. The current API doesn't make it easy to do that with ProseMirror.

**Comment by marijnh** [comment]
A possible approach would be to have a prop `handleLeaveBlock` that's called when the cursor leaves a block, which can choose to do something that overrides the default behavior. That'd also be useful for managing cursor motion on the boundaries of custom node views.

**Comment by marijnh** [comment]
You can implement something like this with key handlers that check whether the cursor is at the [end](http://prosemirror.net/docs/ref/#view.EditorView.endOfTextblock) of the last/first textblock in the document, and respond accordingly. I've decided against adding specialized events/props for it.
