### ISSUE TITLE
A hook for transforming pasted content as a ProseMirror document

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#221]
Use cases:

 - custom cleanup

 - adjusting section levels to the context that we're pasting into

 - autolinking and other transformations (#201)

The main thing blocking this is that my representation of pasted content is awkward (a full document including all the wrapping nodes needed to root the pasted fragment in a top-level node), and I need to resolve some things before I can change this.

**Comment by mattberkowitz** [comment]
For cleanup purposes later this also should resolve #90
