### ISSUE TITLE
Code blocks exit when hitting enter after the last character

### ISSUE THREAD

**Issue by will-hart** [ProseMirror/prosemirror#222]
In v0.4.0, when you are in a fenced code block - e.g. one set up by \`\`\`, if your cursor is at the very end of the section and you hit `enter`, the cursor is placed below the fenced code block in normal paragraph font. 

This behaviour is different from blockquotes for instance, where you have to hit enter twice to leave the quote block. It makes it quite hard to add new content to a code block.

**Workaround** hit space, move the cursor back one character and then start typing again

**Comment by will-hart** [comment]
Additionally, you can't use the down arrow to navigate through a code block. if you scroll to the bottom of the code block with the arrow keys it moves the cursor back up to the top.

**Comment by marijnh** [comment]
(Try to open separate issue for separate problems.)

The first point: You can ctrl-enter to add a newline at the end of the code block. I don't think requiring hitting enter twice is a good idea -- users will also want to put blank lines in their code blocks.

The second: This bug existed at some point, but I fixed it and can no longer reproduce it with the current code. Have you tried with 0.4.0?

**Comment by will-hart** [comment]
Re Ctrl+Enter, fair point about blank lines. However speaking for myself I find the current behaviour a bit non-intuitive - I had assumed it would behave the same way as other blocks i.e. the blockquote and would never have thought of Ctrl+Enter! (I may be alone in this)

Re other end of code block behaviour: I'm using 0.4.0, however I can't reproduce the issue in the demos. I've found other strange behaviours though so I'll raise a new issue.

**Comment by marijnh** [comment]
A code block isn't a wrapping block like blockquote, it is a type of textblock (like paragraph), which you do exit/split by pressing enter.

**Comment by will-hart** [comment]
Ok fair enough, cheers.

**Comment by ianstormtaylor** [comment]
Please reconsider! This is also confusing to me, and makes using the code blocks really cumbersome to use. I don't think I've interacted with code blocks anywhere else on the web that don't add a new line when pressing enter. 

I think the ideal goal would be for code blocks to feel as much like a code editor as possible (in terms of user experience at least), and having to learn a new syntax for creating new lines at the end of a block is a big barrier to that. Is there another way to do this?

Any chance of reconsidering?

**Comment by marijnh** [comment]
How do you propose people add blank lines to their code in the above model? They'd still have to learn ctrl-enter, so it seems it wouldn't really improve the situation. If you had another model in mind, do elaborate.

**Comment by ianstormtaylor** [comment]
I think that hitting enter inside a code block should always result in a `\n` being inserted, no matter if currently on a blank line or not. When I'm typing inside of a code block (in the code writing mentality) that's the thing I assume will happen, regardless of what the current line I'm on looks like.

Anything other than that has consistently caused me headaches (lately when using Dropbox Paper's code blocks, which are slightly better, but still have the double-enter painpoint).

Honestly, although I don't know the exact implementation, I think the ideal from a user experience is for code blocks to always be self-contained, and for it to always be possible to click out into the area underneath a code block to re-enter "paragraph mental space". 

In the case of already having text below the code block, this is already handled automatically. The case I don't really know about is when the code block is technically the last thing in the document. At that point, it seems like there would need to be some workaround to make it possible to still move the cursor to a paragraph below it.

Granted that will probably make that code harder, but from a user experience point of view I'm almost completely certain that `enter` always resulting in `\n` is the ideal.

**Comment by marijnh** [comment]
> The case I don't really know about is when the code block is technically the last thing in the document.

Neither do I. Hence the current behavior. You can add your own keybindings that implement alternative behavior if you feel so inclined.
