### ISSUE TITLE
iOS - Heading formatting lost upon index change

### ISSUE THREAD

**Issue by nickvelloff** [ProseMirror/prosemirror#224]
iPhone 6s Plus, iOS 9.2.1, PM version 0.4.0

![ed-bug-lose-heading](https://cloud.githubusercontent.com/assets/885369/13341287/3ce4f8e0-dbec-11e5-94ad-fcf436258344.gif)

**Comment by marijnh** [comment]
That's not just on iOS, that happens on desktop as well. The logic is that you're joining two textblocks, and the resulting block will inherit the type of the first one. I'll look into adding a special case if the first block is empty, and use the type from the second in that case.

**Comment by marijnh** [comment]
Attached patch addresses this.

**Comment by nickvelloff** [comment]
Excellent thanks! :+1:
