### ISSUE TITLE
Cursor jumps with keyboard navigation through fenced code blocks

### ISSUE THREAD

**Issue by will-hart** [ProseMirror/prosemirror#226]
> Initially reported in #222 but breaking out into its own issue.

I've come across a few odd behaviours with keyboard navigation through fenced code blocks. On the online demos if I'm at the end of the previous line and press the down arrow only, it jumps to the end of the code block then back up to the previous position, see below:

![down_arrow_navigation](https://cloud.githubusercontent.com/assets/391950/13350062/9c759290-dc75-11e5-9bc4-742bbb3fcf66.gif)

From what I can tell this only occurs when:
1) The line above is longer than the code block line
2) The code block is only one line long

A similar issue is visible in the dinos demo if you have two blank lines at the bottom of a code block. Pressing only the down arrow you can see the cursor navigate down the two new lines and then at the next press jumps down very quickly then back up to the top of the code block:

![down_arrow_demo](https://cloud.githubusercontent.com/assets/391950/13350327/4ae4138c-dc77-11e5-9fba-b303f64edf94.gif)

I've spotted other issues locally with 0.4.0 which I'm unable to reproduce using the online demos so it could be related to react-prosemirror. If I hit only the right arrow at the end of a code block the cursor jumps back to the start.

![right_arrow_navigation](https://cloud.githubusercontent.com/assets/391950/13350059/99eaf01a-dc75-11e5-8dba-5191f46d7901.gif)

**Comment by marijnh** [comment]
Which browser are you using? I just followed your instructions with Chrome and Firefox, but couldn't get this to happen.

**Comment by will-hart** [comment]
Weird! The dino demo gifs were on Firefox 44.0.2 on Win 10. I can't replicate on Chrome 48.0.2564.116. I've Ctrl+F5 refreshed Firefox and run in private mode etc but still get the same result.

The last gif is from react-prosemirror 0.2.0 running in electron 0.36.8 (chromium).

**Comment by marijnh** [comment]
Does this still happen? Some problems in the way code blocks were rendered were fixed last month, this might have been related to those.

**Comment by frederik** [comment]
We've had similar issues in Firefox 38.8.0 where the cursor would jump to the beginning of a paragraph when the cursor was placed after the last char of the paragraph. I can't reproduce this in Firefox 45.0.2.

**Comment by marijnh** [comment]
Going to assume this is fixed
