### ISSUE TITLE
Rename transform to transformation

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#230]
We use the term transform to refer to a change to a document. I think the word "transformation" might be a better fit for this.

**Comment by marijnh** [comment]
I've seen _transform_ used as a noun (for example in mathematics), and I like the brevity. What do you consider problematic about it?

**Comment by ericandrewlewis** [comment]
> What do you consider problematic about it?

I'm interested in an API that is easy to on-board new developers, hence using a more generally used term (which is just my experience). If developers don't have familiarity with the term in mathematics, they're probably still familiar with the general term transformation.

There's also [some interesting discussion](http://english.stackexchange.com/a/5456) about the use of transformation and transform in mathematics.

**Comment by marijnh** [comment]
Ehh, well, since I'm going to be landing a chunk of highly backwards-incompatibly stuff anyway, I guess I could throw this in as well.

**Comment by marijnh** [comment]
I started making this change, but the resulting level of verbosity greatly offended my senses. This kind of aesthetic stuff is subjective, but as main maintainer I'm going to make the decision that the slight improvement in readability is not worth the added noise.

**Comment by ericandrewlewis** [comment]
Sounds like a good trade-off, thanks for consideration
