### ISSUE TITLE
Copying & pasting a node into an empty paragraph should keep the copied node's type

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#231]
For example I have the following document:
### Header
- item 1
- item 2

Currently, if I copy a header and paste it into an empty paragraph somewhere else in the document, the header gets turned into a paragraph. Similarly, when I select the bullet list items and paste them into an empty paragraph, the first item loses its bullet style. Try copying items 1 and 2 into a ProseMirror instance to see what I mean.
I think it would be a more user friendly default behavior to keep the copied node's type if it is pasted into an empty paragraph, as the user has not made a conscious decision about the formatting yet.
If it is pasted into the middle of a paragraph or into an existing other node type, I think the current behavior fits well, as the user has already made a conscious decision about the formatting.

**Comment by marijnh** [comment]
So I guess when two distinct textblock types get joined (which is what happens when you paste into an existing textblock or backspace at the start of one), _if_ the first one is empty, the resulting block should get the type of the second. I recently special-cased this for backspace, but it might be a good idea to make it a property of the general replace algorithm. (Which I'm in the process of rewriting anyway in #187)

**Comment by kiejo** [comment]
Making this a property of the general replace algorithm sounds like a good idea, especially if there's already another special case for this behavior.

**Comment by kiejo** [comment]
I saw that there were many commits concerning the copy/paste behavior and thought I would update this issue based on the current master:
* Copying and pasting a heading into an empty paragraph is now working as expected
* Copying and pasting a bullet list into an empty paragraph does not keep the node type as expected

**Comment by marijnh** [comment]
How are you copying the bullet list?

**Comment by kiejo** [comment]
With a bullet list like the following:
* a
* b

Start the selection before the ¨a¨ and end after the ¨b¨. In that case I would expect a copy and paste to result in the same structure when pasting in an empty paragraph.
It might be possible that this is an edge case as the selection actually starts at the start of a paragraph inside the list item. But performing the copy/paste like it is currently done feels really strange.

**Comment by marijnh** [comment]
Here you end up selecting (conceptually) `</p></li><li><p>b`, and if you paste that into a an empty paragraph, it'll have the effect of first closing that paragraph and then inserting a list item. It may be useful to have more heuristics for when to drop 'empty' context around a paste, but this is subtle stuff and hard to get right.

**Comment by kiejo** [comment]
Ok, that makes sense.
Besides handling such a heuristic at paste time, I think it could be an even better idea to handle these heuristics at copy time as this would improve interoperability with other tools. For example when copying and pasting from ProseMirror to Google Docs.

Copying the list in the same way from this GitHub issue results in a complete list structure: `<ul><li>a</li><li>b</li></ul>`. So it looks like this is the default behavior for copying webpage HTML (at least in Chrome, I didn't check other browsers). Google Docs behaves the same way and probably uses a custom copy/paste handling mechanism like ProseMirror.

I think in the special case of starting the selection inside a list item it might be a good heuristic to copy a complete list structure into the clipboard.

**Comment by marijnh** [comment]
That might make sense. Opened #373 for that.

**Comment by kiejo** [comment]
I just checked out the latest master and there still seem to be a few issues with the current copy/paste behavior of lists.
I think the best way to handle the copying and pasting of a partial list would look like the following:

Copying and pasting the following selection
![lis_selected](https://cloud.githubusercontent.com/assets/152507/15891204/cdb0b49e-2d73-11e6-9edf-6178f3304d0d.png)
should result in the following content:
![lis_result](https://cloud.githubusercontent.com/assets/152507/15891260/02a015fa-2d74-11e6-929d-461a13d04ffc.png)

I think this is the result that most users would expect as it is the result that most resembles the copied source.

Doing this inside ProseMirror currently results in the following, which I think is rather unexpected for users:
![lis_res_curr](https://cloud.githubusercontent.com/assets/152507/15891563/75545402-2d75-11e6-9630-c1e64a61f7de.png)

I think a good solution might be to copy not only the `lis` (which is now done in the current master), but an additional wrapping `ul`.

There are two other interesting cases:
* Copying only part of the content of a single list item. I think this should result in copying only the selection without a wrapping `li`. This is how ProseMirror already handles this case.
* Copying the complete content of a single list item. I think this should result in copying the content wrapped in a `li` wrapped in a `ul`. (This one is harder to decide, but this is the way it is handled when copying from a website).

All of the behaviors I described correspond to the way copying content from a website in Chrome is handled.

Something else I noticed, is that pasting a `ul` into an empty paragraph does not replace the paragraph, but inserts the list below the paragraph. What I would actually expect is to replace the empty paragraph with the list.

Would be great to have a way to define this behavior in ProseMirror (either custom or as the default if it is generalizable).

**Comment by marijnh** [comment]
I see what you mean. After some more work on the way pasted HTML is parsed, I think I've gotten a little closer to what you describe. I agree that pasting text from a list item should not create a list item. For now, I also think that if you copy the whole text in a list item, you still shouldn't get a list item on paste (you covered the paragraph, not the list item). I do think working to find a more or less generalized algorithm that works with arbitrary schemas is preferable to special-casing this, but that does make it somewhat tricky to get right.

**Comment by kiejo** [comment]
Awesome, I just checked out the current master and it is working much better now! I don't have a strong opinion on copying the whole text of a single list item and think that both approaches should work well for users :)

I just found another edge case with nested list items that I hadn't thought of before.
Copying and pasting the following selection:
![li_nest_sel](https://cloud.githubusercontent.com/assets/152507/15936062/dc209c82-2e69-11e6-8cc9-eec43a15e51b.png)
should result in the following content:
![li_nested_paste_exp](https://cloud.githubusercontent.com/assets/152507/15936135/22460346-2e6a-11e6-918b-5c52adc3330d.png)
Currently the following gets pasted:
![li_nested_paste](https://cloud.githubusercontent.com/assets/152507/15936097/0206947e-2e6a-11e6-806a-ca04d70a6bf9.png)
