### ISSUE TITLE
SVG icons not working in Firefox with <base>

### ISSUE THREAD

**Issue by katemihalikova** [ProseMirror/prosemirror#232]
### Steps to reproduce
Angular SPA app should have `<base href="/">` in place which breaks SVG `<use href="#pm-icon-...">` in Firefox. According to [this StackOverflow question](http://stackoverflow.com/questions/27306759/svg-symbols-not-being-displayed-in-firefox), Firefox prepends `base href` value to the `use href` which leads to a request to `/` url, where the symbolss are not found. Chrome does not do this. Without `base` tag, Firefox works just fine, too.

**Firefox without `<base href="/">`:**
![image](https://cloud.githubusercontent.com/assets/7225023/13429008/5ab7bd14-dfbe-11e5-9c1f-3c909116a1e6.png)
**Firefox with `<base href="/">`:**
![image](https://cloud.githubusercontent.com/assets/7225023/13429040/78d8cd10-dfbe-11e5-9471-b27ff16b1c41.png)

### Version
Detected in v0.4.0, using Windows, Firefox 44 and Chrome 48.

**Comment by katemihalikova** [comment]
Seems like Chrome also started to do this recently.
![image](https://cloud.githubusercontent.com/assets/7225023/13989645/9e523d9c-f111-11e5-8445-9fef7b2d76a3.png)

**Comment by marijnh** [comment]
Ugh. (Both on Angular's weird requirement and on the standard including this footgun.) A quick web search doesn't turn up any easy solution. Links to relevant resources very welcome.

**Comment by darobin** [comment]
The same issue affects the `history` module that is used with React (https://github.com/mjackson/history/issues/246). For `history` there is another way of specifying the base; I'm afraid the only workaround here is to do the same for Angular.

**Comment by darobin** [comment]
Note that it's not clear to me that the standard is the cause here. These are situations in which both the SVG and its source are defined in the same document, which has the same `base`. That `base` applies to one and not the other is, IMHO, a browser bug.

**Comment by katemihalikova** [comment]
@marijnh This fix is not enough as Angular changes URL when navigating but `baseURL` contains URL of the first page.

1. Loaded URL `http://example.com/items`
2. ProseMirror loads and `baseURL` is `http://example.com/items`
3. Via angular, navigated to `http://example.com/items/5` where ProseMirror editor is placed (URL changed via History API so ProseMirror does not reload)
4. ProseMirror icons are not loaded properly

![image](https://cloud.githubusercontent.com/assets/7225023/13989645/9e523d9c-f111-11e5-8445-9fef7b2d76a3.png)

---

5. Loaded URL `http://example.com/items/5` where ProseMirror editor is placed
6. ProseMirror loads and `baseURL` is `http://example.com/items/5`
7. ProseMirror icons are loaded properly

![image](https://cloud.githubusercontent.com/assets/7225023/13429008/5ab7bd14-dfbe-11e5-9c1f-3c909116a1e6.png)

**Comment by marijnh** [comment]
Ugh. Attached patch seems to help (at least in Chrome)

**Comment by katemihalikova** [comment]
Thanks, seems ok now.
