### ISSUE TITLE
iOS - Double-tap spacebar does not insert period (.)

### ISSUE THREAD

**Issue by nickvelloff** [ProseMirror/prosemirror#234]
This makes editing on iOS particularly cumbersome because without it you have multiple clicks just to insert a period. 
Likely related to https://github.com/ProseMirror/prosemirror/issues/25

**Comment by marijnh** [comment]
I guess CodeMirror gets actual space key events, which it `preventDefault`s, thus suppressing this default behavior. Chrome Android, by generating composition events, gets around this (though it causes other issues).

The only way around this that I can think of would be a special-cased space binding. You could implement it like this:

```javascript
var lastSpace = 0, myCommands = {
  "doubleSpacePeriod": {
    keys: ["Space(1)"],
    run: function(pm) {
      var now = Date.now()
      if (now - lastSpace < 200) {
        lastSpace = 0
        var sel = pm.selection
        if (sel.empty && sel.head.offset > 0)
          return pm.tr.replaceWith(sel.head.move(-1), sel.head, pm.schema.text(". ", pm.activeMarks())).apply()
        return false
      } else {
        lastSpace = now
        return false
      }
    }
  }
}
```

And then pass `commands: CommandSet.default.update(myCommands)` as an option to your ProseMirror instance to enable it in an editor.

**Comment by nickvelloff** [comment]
@marijnh thanks! cc @forresto

**Comment by forresto** [comment]
We could put that in our app, but @marijnh should the fix be upstream in ProseMirror? iOS sniffing is :cry:, but maybe has to be done a couple places.

**Comment by marijnh** [comment]
Does this behavior also occur with a real keyboard on iOS? Because if not, enabling it across the board is also problematic.

**Comment by ericandrewlewis** [comment]
> Does this behavior also occur with a real keyboard on iOS?

Is a "real" keyboard a bluetooth connected keyboard?

**Comment by forresto** [comment]
Double-space with my bluetooth keyboard + ipad does make a `.` in the Notes app, but not in ProseMirror. Less of an issue with keyboard, because it has dedicated <kbd>.</kbd> key. I think it should be consistent and work as it does in Notes.

**Comment by marijnh** [comment]
I think the best home for something like this would be a `src/platform` module with platform-specific extensions in specific files (`platform/ios.js`) that you can enable on demand. Thoughts?

**Comment by ericandrewlewis** [comment]
The iOS shortcut is a setting which a user can enable or disable, so enforcing this behavior on all iOS devices might be a surprise for users.

**Comment by forresto** [comment]
@ericandrewlewis The shortcut is on by default, and smaller screen keyboards hide the <kbd>.</kbd>, so it will probably affect more people to not hack it back in.

![iOS 9](https://theoverspill.files.wordpress.com/2015/09/keyboardbefore-after.png?w=584&h=372)

@marijnh Making this kind of fix optional to enable sounds good.

**Comment by nickvelloff** [comment]
@marijnh Did we land on a decision if this is going to be enabled upstream or we need to do it at the app level?

**Comment by marijnh** [comment]
For now, keep doing it at the app level. Below is a version of the command that works with the current API. I'm not interested in including platform-specific files in the distribution, or defining an automatic way to load those, at this point.

```javascript
let lastSpace = 0

export const commands = {
  doubleSpacePeriod: {
    keys: ["Space(1)"],
    run: function(pm) {
      var now = Date.now()
      if (now - lastSpace < 200) {
        lastSpace = 0
        var sel = pm.selection
        if (!sel.empty) return false
        let before = pm.doc.resolve(sel.head).nodeBefore
        if (!before.isText || before.text.charAt(before.text.length - 1) != " ") return false
        return pm.tr.replaceWith(sel.head - 1, sel.head, pm.schema.text(". ", before.marks)).apply()
      } else {
        lastSpace = now
        return false
      }
    }
  }
}
```

You could also consider just defining input rule that converts double spaces (which shouldn't occur in almost all types of prose) to `". "`.

**Comment by nickvelloff** [comment]
To be clear I’m not asking for a specific approach. I’m perfectly happy working with an approach you prefer. TBH I just need it working whatever I have to do in the short term. I’ll try this right now and report back.

**Comment by nickvelloff** [comment]
@marijnh This worked well enough to release for us. Really appreciate the help. 🙇

**Comment by forresto** [comment]
Reworked as InputRule for PM 0.8.x: https://github.com/the-grid/ed/blob/f9e9eb05e9711efa3d9a7c6feb8a910068446437/src/inputrules/ios-double-space.js
