### ISSUE TITLE
Serialization to markdown has invalid test for mark type

### ISSUE THREAD

**Issue by asteadman** [ProseMirror/prosemirror#236]
Comparison of node.marks[x].type to the string "code" is (presumably?) always false in [to_markdown.js](/ProseMirror/prosemirror/blob/572f9118fcbd772ba5f8274c2c5464e143724bd2/src/markdown/to_markdown.js#L126). The type of node.marks[x].type is a class derived from the class `MarkType`, which does not implement a `toString` method. As a result, the comparison devolves into `"[object Object]"=="code"`, which is always false. Therefore this is dead code and can be removed. see also #216 .

```js
if (stack.length && stack[stack.length - 1].type == "code" &&
          (!marks.length || marks[marks.length - 1].type != "code")) {
        this.text("`", false)
        stack.pop()
      }
```

**Comment by marijnh** [comment]
Fixed in b43d167e12d
