### ISSUE TITLE
add an event to let user know about and scan through incoming transforms from collaborators

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#239]
It would be good to also be able to scan through changes that come from remote users. I am using the below code for that, but a lot of this is copying what is in the receive function of the collaborative mode, and there may be other better places to put this. Any specific reason why there is no such event so far? 

       let steps = [diff].map(j => Step.fromJSON(fidusSchema, j))
        let docs = []
        let doc = this.pm.mod.collab.versionDoc
        docs.push(doc)
        let maps = steps.map(step => {
            let result = step.apply(doc)
            doc = result.doc
            docs.push(doc)
            return result.map
        })

        let unconfirmedMaps = this.pm.mod.collab.unconfirmedMaps
        let unconfirmedSteps = this.pm.mod.collab.unconfirmedSteps
        maps = maps.concat(unconfirmedMaps)
        unconfirmedSteps.forEach(function(step) {
            // We add pseudo steps for all the unconfirmed steps so that the
            // unconfirmed maps will be applied when handling the transform
            steps.push({
                type: 'unconfirmed'
            })
            // We add real docs
            let result = step.apply(doc)
            doc = result.doc
            docs.push(doc)
        })
        let transform = {
            steps,
            maps,
            docs
        }
        
        this.pm.mod.collab.receive(steps)

        this.pm.signal("remoteTransform", transform)

**Comment by marijnh** [comment]
If you add an event to the `collab` module that fires whenever new changes are accepted, passing the new steps to listeners, I'd merge that. You'll probably also want to pass the array of maps that `receive` returns, to make it easier for client code to do something with it (an existing use case is [found](https://github.com/ProseMirror/website/blob/6a34e93/src/demo/collab/client/collab.js#L78) in the collab editing demo, where there's a call to highlight new text embedded directly in the code that receives these from the network.

**Comment by marijnh** [comment]
Added in #255
