### ISSUE TITLE
Tests fail on Microsoft Edge Browser

### ISSUE THREAD

**Issue by jarrodh** [ProseMirror/prosemirror#24]
Using the latest preview of Windows 10 build 10532 and commit 7ae0a0a, four tests fail:
- selection_read: TypeError: Argument not optional
- selection_set: TypeError: Argument not optional
- selection_coords_cornercases: Failure: expected 0:14, got 0:0
- selection_coords_round_trip: Failure: expected 1/1:2, got 1/1:0

Right now the Edge browser is by far in the minority but who knows. Also support the Edge browser enables writing Universal Apps for Windows 10 that can be installed locally.

I am happy to help as much as possible but need some guidance.

**Comment by marijnh** [comment]
I will support Edge at some point, but right now I don't even have a test VM for it yet. You could try to figure out which function is raising the `Argument not optional` error, since that's probably an easy fix.
