### ISSUE TITLE
option-right requires two presses to take effect

### ISSUE THREAD

**Issue by ianstormtaylor** [ProseMirror/prosemirror#242]
Just noticed this while editing, if you `option-left` to navigate to the left by one word at a time, everything works like a native editor. But if you `option-right` to navigate to the right, it takes two presses to skip each word instead of one.

Here's a GIF that shows it:

![](http://g.recordit.co/LEVJglQaxs.gif)

You can't see the keys being pressed, but the reason moving to the right is slower is because I'm pressing it twice each time to get it to take effect.

**Comment by ericandrewlewis** [comment]
There are commands that expect the user to press `alt+right` and then another key to wrap the current selection. e.g. `alt+right` then `*` wraps the selection in a bullet list (see the [code](https://github.com/ProseMirror/prosemirror/blob/f168d1bfdeb8a32b7ad43f933f27b8674db4d3d1/src/edit/schema_commands.js#L181-L193)).

We should find another key binding for these commands.

**Comment by marijnh** [comment]
> We should find another key binding for these commands.

Agreed. Suggestions (preferably with precedents) welcome.

**Comment by ericandrewlewis** [comment]
TinyMCE places all custom shortcuts under what they call an [access](https://github.com/tinymce/tinymce/blob/e35d1deba514c006e803e57407312345f4f2047c/js/tinymce/classes/Shortcuts.js#L19) modifier, which is `control+alt` on Mac and `shift+alt` on Windows. 

The default shortcuts they register are 

`access+1` Change selection to heading 1
`access+1` Change selection to heading 1
`access+1` Change selection to heading 1
`access+1` Change selection to heading 1
`access+1` Change selection to heading 1

**Comment by marijnh** [comment]
Cmd/Ctrl-1 through 6 for heading is widely used, and I've made those the defaults in ProseMirror. Cmd/Ctrl-0 for paragraph seems easier to remember than ...-7, so I think I'll also stick with that.

**Comment by ianstormtaylor** [comment]
Sublime Text does a similar thing, but it uses an alpha key combination, specifically `Cmd-K` and puts lots of the selection-text-editing features behind it. For example:

- `Cmd+K, Cmd-U` will turn the selected text to uppercase.
- `Cmd+K, Cmd-L` will turn the selected text to lowercase.
- `Cmd+K, Cmd-2`, code fold 2 levels.
- `Cmd+K, Cmd-3`, code fold 3 levels.
- `Cmd+K, Cmd-J`, unfold code.
- ...

So alpha/numeral keys could be an option to put them behind.

**Comment by ericandrewlewis** [comment]
`Command-[1-9]` in most Mac browsers (Chrome, FF, Safari) switches to the 1-9th browser tab.

What should our approach to OS and browser shortcuts be?

I think the editor should make use a shortcut when they make sense for an editor (e.g. copy text, emphasize text, etc) and avoid collision with OS or browser shortcuts.

TinyMCE seems to have found that their access modifiers are safe for editor-specific custom shortcuts. They previously tried various ones and found collisions:

* `Command/Ctrl` collided with browser tab switching so they switched to `Command/Ctrl+Alt` ([commit](https://github.com/tinymce/tinymce/commit/f857512ea2b32c4f55768d1a5ee58ea601db365c))
* `Command/Ctrl+Alt` collided with `AltGr+[1-9]` on Windows so they switched to `Command/Shift` ([commit](https://github.com/tinymce/tinymce/commit/09176952c98b359aa777ed1c6ce9a0233b7a1cc0))
* `Command+Shift` collided with the Mac screenshot shortcuts (`Command+Shift+[3-4]`) so they changed they switched the Mac shortcut to `Control+Alt`, creating the idea of the access modifier, `Control+Alt` on Mac and `Ctrl+Shift` on Windows. ([commit](https://github.com/tinymce/tinymce/commit/7de8b6ce3578b063154148c840642d9fd8e7c503), [commit](https://github.com/tinymce/tinymce/commit/2d39d19a37082726b2b223fa3e3e7b2c29c7f2b1))

**Comment by ianstormtaylor** [comment]
@ericandrewlewis nice research, I like that idea of "access modifier" a lot.

**Comment by marijnh** [comment]
I'm not a fan of putting things behind two-stroke keybindings, since they tend to be cumbersome to enter.

I've settled on Mod-Shift (which is Ctrl-Shift on non-Mac, Mod-Shift on Mac) as modifiers for number-based shortcuts for now. If Mod-Shift-number already has a meaning on Mac, do let me know.

See patch e45e7d1, which moves the paragraph/heading keybindings to Shift-Ctrl/Cmd-N to avoid conflicting with tab-changing keybindings, removes the Alt-Left/Right bindings, and generally tries to make the default bindings less surprising.

The goal is to step on the toes of platform bindings as little as possible, but this is an iterative process (since I don't use all platforms and am not aware of all possible bindings people use).

Patch 9fc231a makes sure Alt-Left/Right are treated as cursor motion bindings on Mac, so that they play well with node selections.

This resolves the issue that spawned this thread, and some of the concerns raised below. If you find something discussed here needs more attention, open a new issue.

**Comment by ianstormtaylor** [comment]
Nice, thanks for doing this!

`Mod-Shift-3` and `Mod-Shift-4` are the OS-wide Mac bindings for taking screenshots. See @ericandrewlewis's mention above ^

**Comment by marijnh** [comment]
Argh. I read that as ctrl-shift before. That's too bad. Then I guess we will end up with an even more obscure combo. Any issue with Ctrl-Shift- on Mac? That would at least have the advantage of being the same on both platforms.

**Comment by ianstormtaylor** [comment]
Hmm, not that I know of, but not totally sure.

**Comment by marijnh** [comment]
(Safe-modifier-key discussion continued in #242)
