### ISSUE TITLE
list menu items do not appear only when first list item selected

### ISSUE THREAD

**Issue by ianstormtaylor** [ProseMirror/prosemirror#243]
Here's a GIF that explains it:

![](http://g.recordit.co/aWuUhBcuKG.gif)

The list item options in the menu appear for all subsequent list items, but do not appear for the first item in the list. This makes the menu change when switching between items, for a non-obvious reason. 

Is there any way to disable this? I'd like to keep the menu the same everywhere, for consistency's sake for the user.

**Comment by marijnh** [comment]
What did you want to do with the list-wrapping command at that point? See #70 for context.

**Comment by ianstormtaylor** [comment]
My preference would be to have the menu item visible, even it it's in a disabled state. I wonder if it might actually be better to have the default menu styles set `display: none` on disabled menu items, instead of removing them from the menu altogether. That would make it easier to have the behavior be an option.

For context: I think the default tooltip menu behavior where it changes a bunch depending on what you have selected, or which node you're cursor's inside, is very confusing for end users. In many cases, the reasons for certain items being visible/invisible is not going to be clear to them, resulting in frustration when they can't find the button they know to exist. I think it's more clear to show the options, but to have them be disabled.

(Notice in that GIF that not only do the list buttons disappear, but then `Insert..` dropdown also disappears by different logic.)

I'm going to explore this in a custom menu though, since it seems like the defaults aren't built to function this way.

**Comment by pboysen** [comment]
@ianstormtaylor If you check out the MenuCommandSpec docs, a select option allows you to control whether it disappears or is disabled.

**Comment by ianstormtaylor** [comment]
@pboysen sweet, thanks!

**Comment by marijnh** [comment]
As @pboysen indicated, you can control this. I don't render all menu items always because that'd complicate rendering the right amount of separators. In some situations, showing grayed-out icons is a good idea. But it does cause problems when you have a lot of context-sensitive icons, which will only occur in specific situations -- you'll have a huge, mostly grayed out, menu all of the time.
