### ISSUE TITLE
option-left in a list item unindents it, instead of jumping across words

### ISSUE THREAD

**Issue by ianstormtaylor** [ProseMirror/prosemirror#244]
Here's an example GIF:

![](http://g.recordit.co/VOwbqC7Zqg.gif)

Navigating to the right with `option-right` works (save for the issue of https://github.com/ProseMirror/prosemirror/issues/242), but trying to go in the reverse direction with `option-left` unindents the list item instead.

**Comment by kiejo** [comment]
This is due to the fact that by default the ```option-left``` hotkey is bound to the ```lift``` command.
You can disable the ```option-arrow``` hotkeys using the following code:
```javascript
import {CommandSet} from 'prosemirror/dist/edit';
const baseCommands = CommandSet.default.update({
  lift: {keys: null}, // bound to option-left
  joinUp: {keys: null}, // bound to option-up
  joinDown: {keys: null}, // bound to option-down
});
```

You can then pass these commands to your ProseMirror instance:
```javascript
const pm = new ProseMirror({
  commands: baseCommands,
  ...
})
```

As a side node for all non-Mac users: The ```option-arrow``` keys are used to jump over words on OSX. On Windows and Linux this is done using ```ctrl-arrow```.
Maybe it would be a good idea to use different default hotkeys for the join commands as this might be an issue for many Mac users. I didn't know about this until recently when one of our users complained about it.

**Comment by marijnh** [comment]
I wasn't away Option-Left on Mac also skips words. How is it different from Cmd-Left?

**Comment by ianstormtaylor** [comment]
Hey, sorry for delay. @kiejo good call! Didn't realize that it was because of that overlap, thanks!

@marijnh good question. Quick testing in Sublime Text on my Mac:

- `ctrl`:
  - `up/down/left/right` handles window/space management at the OS-level—unimportant.
- `option`:
  - `left/right` moves to the **left/right** by **one word** at a time.
  - `up/down` moves to the **start/end** of a **line**. If already there, they move up/down line by line, keeping the cursor at the start/end when moving to the next line (as opposed to keeping it at a fixed number of characters in).
- `cmd`:
  - `left/right` move to to the **start/end** of the **current line** only. (In Sublime text `cmd-left` will respect indentation such that pressing it once will move to the start of non-indent characters on the line, and pressing it again will move to the actual start of the line.)
  - `up/down` move to the **start/end** of the **file**.
 Cmd-Left/Right moves to the start/end of the current line. And Option-Left/Right moves left/right by one word.
- `ctrl+option`:
  - `left/right` moves to the **left/right** by **one case-respecting word** at a time. So if you're cursor was at the start of a variable like `|my_app_instance`, it would take three jumps to cross it: `my|_app_instance`, `my_app|_instance`, `my_app_instance|`. 
  - `up/down` seems to scroll the viewing window—unimportant.
- `ctrl+cmd`:
  - `left/right` nothing.
  - `up/down` moves the current line of text (or multiple lines if the selection spans multiple lines) above or below the adjacent lines of text.

**Comment by ericandrewlewis** [comment]
Testing in Sublime may expose Sublime-only bindings.

Here is Apple's [list](https://support.apple.com/en-gb/HT201236) of keyboard shortcuts. We should probably respect all those, and perhaps do an audit at some point to make them all work as expected. Right now they don't. e.g. you can press `ctrl+D` on a mac to delete a char to the right of the insertion point, which will delete the character in the DOM but not in the document model.

`Tab` and `Shift+Tab` are used in TextEdit (OS X's built-in text editor) for indenting and unindenting list items. `Cmd+[` and `Cmd+]` are used in Google Docs on OS X.

**Comment by marijnh** [comment]
> Right now they don't. e.g. you can press ctrl+D on a mac to delete a char to the right of the insertion point, which will delete the character in the DOM but not in the document model.

Ctrl-D _is_ bound to `deleteCharAfter` on Mac, though they might be something else going wrong (I don't test on Mac much).

**Comment by marijnh** [comment]
Has anyone been able to find a full list of the keys the various (or even just one) browser bind when in a contentEditable field?

Attached patch removes the Alt-Left and Alt-Right bindings from the default keymap, since they are likely to confuse or conflict with other keys. Unindenting is now done with Ctrl/Cmd-[, as in Google Docs and various code editors.

**Comment by ericandrewlewis** [comment]
> Has anyone been able to find a full list of the keys the various (or even just one) browser bind when in a contentEditable field?

I started [this document](https://docs.google.com/spreadsheets/d/12iEbCdv07RegN8_yRdD9UDUpXIDDf7r4ikN2Fa1gDIo/edit) to outline keyboard shortcuts defined by the OS (in both its "Finder" and "Document" modes) and the browser split into sheets based on modifier combinations. If anyone would like to contribute feel free (I can add you as an editor), I intend to keep it open for public use.

It seems that at least on Mac OS X, `Control+Alt/Option` is the modifier plane that has no OS or Chrome shortcut bindings.

**Comment by marijnh** [comment]
> It seems that at least on Mac OS X, Control+Alt/Option is the modifier plane that has no OS or Chrome shortcut bindings.

You mean in the number key range? It does seem to have a lot of bindings for other keys, so as a general 'we use this prefix for out shortcuts' combo, it also isn't ideal.

**Comment by ericandrewlewis** [comment]
> It does seem to have a lot of bindings for other keys

You might be looking at [`Command+Alt/Option`](https://docs.google.com/spreadsheets/d/12iEbCdv07RegN8_yRdD9UDUpXIDDf7r4ikN2Fa1gDIo/edit#gid=236198291). [`Control+Alt/Option`](https://docs.google.com/spreadsheets/d/12iEbCdv07RegN8_yRdD9UDUpXIDDf7r4ikN2Fa1gDIo/edit#gid=818902169) has no default OS or Chrome bindings I could find.

**Comment by marijnh** [comment]
Thanks for putting together that list. I *think* (though I was confused every time I drew any conclusion before, so maybe I'm still missing something) that Ctrl-Shift-number is safe on both Windows and OS X, so that we can use that as a relatively easy-to-use (they are usually above each other) binding across platforms.

Patch b850fbe implements this.
