### ISSUE TITLE
History.BackToVersion() does not work for initial version.

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#245]
Tested with latest master (e43e63a05f18c52d84b611fd5e5aa252173bb514) so version 0.4

If you get an initial version the lastId will be undefined which then prevents the `backToVersion()` from working correctly. This prevents saving initial version when editing and being able to roll back to it.

From developer console:
```
>> pm.history.getVersion()
Object {lastID: undefined, version: 0}
( Make an edit in the editor to bump version )
>> pm.history.getVersion()
Object {lastID: 1, version: 1}
>> pm.history.backToVersion({lastID: undefined, version: 0})
false
>> pm.history.getVersion()
Object {lastID: 1, version: 1}
```

**Comment by marijnh** [comment]
Attached a not-perfect-but-better-than-it-used-to-be fix.

**Comment by wes-r** [comment]
Old fix no longer works with latest history changes

```
>> pm.history.getVersion()
3
( Make an edit in the editor)
>> pm.history.getVersion()
6
>> pm.history.backToVersion(3)
false
( Make another edit in the editor)
>> pm.history.getVersion()
8
>> pm.history.backToVersion(6)
true
```

**Comment by marijnh** [comment]
Woops. I mostly took this case into consideration when rewriting the history, but missed a piece. Also, there still wasn't a test for this. Both should be fixed with attached patch.
