### ISSUE TITLE
Changing editor content within the "focus" event may cause JS exception

### ISSUE THREAD

**Issue by jacwright** [ProseMirror/prosemirror#246]
* ProseMirror 0.4.0
 * Chrome  48.0.2564.116
 * OSX 10.10.5

### Use Case
I have "placeholder" text that will be put into the pm editor when it is empty and not focused. When the editor receives focus it will remove the placeholder text.

### Action

 * Set a listener to the "focus" event for a ProseMirror instance that deletes the content when focused.
```js
pm.on('focus', function() {
  pm.setContent('', 'html');
});
```
 * Type some content into the editor.
 * Click outside the editor so it does not have focus.
 * Click on the text in the editor.

### Actual
When the `mouseup` event triggers its `event.target` equals the element that was clicked on *before* the editor was emptied, causing JavaScript errors later in `pathFromDOM`. Stack trace is roughly:

 * `Uncaught TypeError: Cannot read property 'getAttribute' of null`
 * `dompos.js` - `pathFromDOM(pm, node)`
 * `dompos.js` - `handleNodeClick(pm, type, event, direct)`
 * `input.js` - `up()`

This occurs because the `pathFromDOM` assumes the node is still in the editor and doesn't check if `parentNode` is `null`.

### Expected

No errors should occur when clicking into the editor, even if the content changes on focus.

The `mouseup` event handler should use the `event` object (and target) from that event rather than using the `mousedown` event target.

**Comment by ericandrewlewis** [comment]
We're also looking into placeholder text with an empty headline block ("Enter headline" placeholder) and empty paragraph block ("Enter body text" placeholder). 

My first thought was that a block has complete control over its DOM rendering layer via the `serializeDOM` node type method. So if you create your own node type extending a default node type (e.g. `class HeadingWithPlaceholder extends Heading`) you could add rendering-layer logic to output the placeholder text when the node has no content, and as soon as it has content don't display the placeholder text. 

The goal here seems to be displaying to the user placeholder text, so modifying the actual document on editor focus seems semantically awkward.

@mattberkowitz might have some thoughts too.

**Comment by jacwright** [comment]
Having a more official way to display placeholder text (that isn't selectable) would be really great.

This may be semantically awkward, but making the code more robust to handle non-happy paths would be a good thing too.

**Comment by mattberkowitz** [comment]
I tried a few ways to implement this.

First in `serializeDOM` I added a `data-placeholder` and tried the following css:

```
[data-placeholder]:empty::after {
  content: attr(data-placeholder)
  /*some styeling*/
}
```

That didn't work out. Turns out an empty `Textblock` isn't actually empty ProseMirror adds `<br pm-ignore="trailing-break">` that gets added by https://github.com/ProseMirror/prosemirror/blob/master/src/edit/draw.js#L83-L94 which in turn is called by the redraw loop

Ok so `:empty` is out. Then I tried also adding

```
if(node.textContent.length === 0) elt.classList.add('empty')
```

in serializeDOM then doing

```
[data-placeholder].empty::after {
  content: attr(data-placeholder)
  /*some styeling*/
}
```

Nothing there either, the entire block doesn't get redrawn when typing only the internal bits, it seems.

What I settled on (for now) was adding a `[data-placeholder]` to empty `Textblocks` in the `serializeDOM` method, then clearing it out once text gets added via the `transform` event.

```
import { defineOption } from "prosemirror/dist/edit"
import { Pos } from "prosemirror/dist/model"
defineOption("clearPlaceholder", true, function(pm, value) {
	function onTextInput() {
		let node = pm.doc.pathNodes(pm.selection.head.path).pop()
		if(node.isTextblock && node.textContent && node.attrs.placeholder) {
			let pos = new Pos(pm.selection.head.shorten().path, pm.selection.head.path[pm.selection.head.path.length - 1])
			let attrs = node.attrs
			delete attrs.placeholder
			pm.tr.setNodeType(pos, node.type, attrs).apply()
		}
	}
	if(value) {
		pm.on('textInput', onTextInput)
	} else {
		pm.off('textInput', onTextInput)
	}
})
```

It's not perfect. If you enter text, then remove it the placeholder won't come back, but for now it will do.

**Comment by jacwright** [comment]
I do have this working as you can see here without the above additions to prosemirror.

![placeholder](https://cloud.githubusercontent.com/assets/120294/13550412/9245f128-e2da-11e5-98e8-f0cb21fbabfa.gif)

But it throws an error in the console every time I click on the placeholder.

**Comment by mitar** [comment]
@ericandrewlewis, have you made the code which would provide a placeholder for headline block and paragraph block? I have found discussion [here](https://discuss.prosemirror.net/t/how-to-input-like-placeholder-behavior/705/13) but it is only for the whole document.
