### ISSUE TITLE
Allow tooltips to receive a "bounding box" element for calculating the tooltip position near edges

### ISSUE THREAD

**Issue by bjoernm** [ProseMirror/prosemirror#249]
Currently, `window` is being used to get the boundaries for calculating the correct position of tooltips near the window edges. For example, instead of hiding part of tooltips when they would be rendered outside the window, they are placed correctly inside.

However, there are some cases when you want to set different boundaries than `window`. Would if be possible for [tooltip.js](https://github.com/ProseMirror/prosemirror/blob/49809edafad9835c0f8eb7beba52019a04e7ed05/src/ui/tooltip.js) to take an argument that acts as the "bounding box" instead of `window`?

An example for the current calculation I am talking about can be seen [here](https://github.com/ProseMirror/prosemirror/blob/49809edafad9835c0f8eb7beba52019a04e7ed05/src/ui/tooltip.js#L83).

**Comment by marijnh** [comment]
That would make sense. To keep call to `open` convenient, it might make sense to specify a box-retrieving callback to the constructor of `Tooltip`. You could make the second argument be either a string or an options object, in which case the direction is taken from `options.direction`, and a `boundingBox` option is also recognized, stored in the object, and later consulted when determining the space in which the tooltip may appear. Want to submit such a PR?

**Comment by kiejo** [comment]
I think I'll have a go at this one.

**Comment by marijnh** [comment]
Fixed via #258
