### ISSUE TITLE
iOS keyboard stays stuck in uppercase when typing

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#25]
Similar to https://github.com/codemirror/CodeMirror/issues/3403 -- probably the fact that we redraw the DOM when a key event happens prevents the keyboard from figuring out it is no longer at the start of a sentence.

**Comment by tgecho** [comment]
I don't know if this is useful additional information, but the cursor also seems to get a bit stuck in position as well as all caps. In case its not apparent enough, the second half is me trying to click to move to the end of the "blockquotes" line, but the cursor stays stuck in place until I close and reopen the keyboard.

![prosemirroriosstuck](https://cloud.githubusercontent.com/assets/49615/12664474/b933f2d4-c5fd-11e5-8f74-80c61c6bc2cf.gif)

**Comment by nickvelloff** [comment]
@marijnh This one is a hard blocker to our iOS release. I think the ☝️ referenced issues and this are all related, so a fix on this _could_ close a lot of iOS issues.

**Comment by marijnh** [comment]
The relevant bug seems to be that mobile Safari has some sticky piece of state that determines whether its keyboard is in default-uppercase or default-lowercase mode. It updates this when the user manually sets a selection or types, but it just keeps the existing state when a script manipulates the selection. Thus, if ProseMirror intercepts a `keypress` event, updates the document, and sets a new selection, you'll be stuck with the case-state from before that insertion.

(I wanted to report this issue to Apple, but their [issue tracker](https://bugreport.apple.com/) requires an Apple ID login, and with my Apple ID, it just keeps redirecting back to the login form on successful login. Amateurs. If someone who _does_ have access to the bug tracker want to report this, that'd be helpful. Ask me if you need more details.)

One workaround I found was to blur and then focus the editor whenever I update the selection. However, initializing the virtual keyboard is somehow expensive (?), so this was very slow.

Instead, attached patch makes it so that `keypress` events are let through when on iOS. This will cause ProseMirror to parse the updated DOM and get the input from there, and has the side effect of making Safari notice that the selection changed, so that it updates its default-case state. This is not a full solution -- when you move the cursor with ProseMirror's `setTextSelection` method, for example, you'll still have the issue of the old state persisting. But it's a lot better than the old situation.

Please test.

**Comment by nickvelloff** [comment]
I'll test and have Apple issue tracker ready to submit. Please send me the report just as you would submit it. Thanks.

**Comment by marijnh** [comment]
I don't know what their form looks like, but you could describe it something like this:

> The iOS virtual keyboard detects whether a capital letter makes sense in the current context (start of sentence) and automatically switches 'shift' on or off based on this. However, it only does this in some circumstances (user input, user cursor positioning). When moving the selection programmatically (through the methods on the `Selection` object), the current default-case state simply persists. In some kind of applications (such as an editor that handles handles keypress events itself), this will lead to unexpected default-case and poor usability.

**Comment by nickvelloff** [comment]
@marijnh this issue is working much better at this stage. I think it is a reasonable merge and hot fix release IMHO. Thanks so much for unblocking us 🙇

**Comment by nickvelloff** [comment]
@marijnh Started a bug report and ran into something I'm not clear on a suitable answer.
Specifically, "Detailed steps to reproduce". I'm not familiar enough with the internals to give a very simple/reproducible set of steps.

No hurry I can submit the bug any time.

**Comment by marijnh** [comment]
You could point at [this gist](https://gist.github.com/marijnh/980fdd07315d7875d88950b6df62e04b), which contains a minimal HTML page that demonstrates the issue.

**Comment by nickvelloff** [comment]
Bug has been submitted to Apple. Thanks @marijnh 
<img width="564" alt="screenshot 2016-04-16 23 58 42" src="https://cloud.githubusercontent.com/assets/885369/14585595/37acc46e-042f-11e6-8581-f18e605254e4.png">

**Comment by nickvelloff** [comment]
My steps to reproduce were not completely correct. 
They were updated with better instructions.

**Comment by marijnh** [comment]
Patch eee5c4c solves this for typing. For remaining issues with the same root cause, issue #310 is open.

**Comment by nickvelloff** [comment]
thanks @marijnh !
