### ISSUE TITLE
Hard to delete a paragraph between two locked nodes

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#250]
It's hard to delete a paragraph between two locked nodes.

Here's [a screencast of the user behavior](https://www.youtube.com/watch?v=4zFg-m_ZWgc&feature=youtu.be).

Clicking delete while inside of an empty paragraph with a locked node above causes the node above to be deleted. As a user, I might expect the empty paragraph to be deleted, and then the locked node above selected.

**Comment by marijnh** [comment]
I guess you mean content-less nodes when you say locked?

Maybe a better behavior would be, on backspace in an empty paragraph below a content-less, selectable block, to delete the paragraph and select the block?

**Comment by ericandrewlewis** [comment]
> I guess you mean content-less nodes when you say locked?

Yes

> Maybe a better behavior would be, on backspace in an empty paragraph below a content-less, selectable block, to delete the paragraph and select the block?

That'd be great. 

Can I try my hand at a patch? Seems like we'll want to modify the behavior of the `joinBackward` command?

**Comment by marijnh** [comment]
> Can I try my hand at a patch?

Of course! I think you just need to expand the check for `before.type.contains == null` to do something special when before is selectable (when it isn't, we should probably keep the old behavior -- I can't think of a sane new selection if we delete the paragraph in this case).

**Comment by marijnh** [comment]
Fixed via #251
