### ISSUE TITLE
Can't navigate after making node selection in group of contentless nodes

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#253]
If a user makes a node selection in the middle of a group of contentless nodes, keyboard navigation scrolls the window rather than changing the node selection up and down.

![stuck-navigation-in-middle-of-contentless-nodes](https://cloud.githubusercontent.com/assets/1087646/13616515/31aaaa8c-e548-11e5-9313-561289e3dfe6.gif)

**Comment by ericandrewlewis** [comment]
Can reproduce in OSX Chrome and Safari. Can't reproduce in FF.

Seems to have to do with the fact that when a node selection in the middle is set, a selection is non-existent(all nodes are unset in `window.getSelection()`), and the keypress event is not caught by the input handler.

**Comment by mattberkowitz** [comment]
I think this has some ties to #252. I assume the reason for that hanging cursor is, in part, because there has to be some cursor inside the contenteditable in order for it to catch key/paste events

**Comment by mattberkowitz** [comment]
One solution I've used before is to put the cursor into some offscreen element which can capture the events. It's not an elegant solution by any means, but it worked

**Comment by marijnh** [comment]
This is pretty much the same issue as #252 -- the browser makes up some kind of selection because it feels it isn't allowed to set the selection on the non-editable selected node.
