### ISSUE TITLE
Keyboard shortcuts aren't discoverable

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#263]
It's hard to tell what keyboard shortcuts exist past what the user will expect from any text editor (cut and paste, etc.).

**Comment by marijnh** [comment]
There's tooltips on the menu items, and they list bindings, if any, but beyond that, the only way I know of discovering keys some kind of help functionality, which I don't think belongs in core. The key bindings can be inspected, so one could build a key help display of some kind without duplicating information.

**Comment by ericandrewlewis** [comment]
Cool — closing this out, might create a help module.
