### ISSUE TITLE
Offset 1 out of range error thrown

### ISSUE THREAD

**Issue by ameliusg** [ProseMirror/prosemirror#266]
After doing some typing with a nested list structure, an error "Offset 1 our of range" is thrown. See the image and video (in the zip file). I recorded the keystrokes in a log file.

![out_1813](https://cloud.githubusercontent.com/assets/10962361/13813955/9d52b6a2-eb84-11e5-9c05-6efe5a7c3823.gif)

[bugreport.zip](https://github.com/ProseMirror/prosemirror/files/176046/bugreport.zip)

**Comment by kiejo** [comment]
Using the latest version from master, there still seems to be a bug when working with bullet lists. The new error that is now thrown is "Position X out of range" from model/node.js (```resolvePos``` function).

Here's what I've found so far:
* The error is not thrown immediately after a key press, but with some delay after you have stopped typing.
* After the error was thrown once, it continues being consistently thrown every time you type something and then stop typing for about half a second. The error is not thrown while you are typing, you need to pause.
* If you exit the list item after the error was thrown by hitting enter twice, a "Cannot read property 'resolve' of null" error is thrown (transform/ancestor.js:32).
* Creating many list items very fast leads to a "Failed to find node at X" error, which seems to be the same issue as #279 (this one is relatively easy to reproduce, as long as you go fast enough)

I managed to reliably reproduce the error by typing the following in the editor:
* asdf asdf asdf asdf asdf
  * asdf asdf asdf asdf asdf
* asdf asdf asdf asdf asdf
* asdf asdf asdf asdf asdf
* asdf asdf asdf asdf asdf
* asdf asd

The error "Position 66 out of range" is thrown after typing the last "d". The total number of characters seems to be important. Using less text for each list item causes the error to be thrown after creating more bullet items than in this example. Using copy & paste causes other errors, so you have to type it by hand to reproduce the error.

**Comment by marijnh** [comment]
I was able to reproduce this now. It seems the history compression algorithm is mapping selections incorrectly. I'm not sure if we need to keep this feature (compression) at all, with the linear positions, so I'm going to hold off debuggin this until I've decided whether to scrap it or not. I hope to get to that next week.

**Comment by marijnh** [comment]
Attached patch rewrites the history compression algorithm. As such, it is likely to have fixed this. (I can't reproduce it anymore.) Could you see if you can still cause this to happen?

**Comment by kiejo** [comment]
I just checked and can't reproduce it anymore. Your patch fixed this, thanks!
