### ISSUE TITLE
Use self-documenting varname for seralizer

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#267]
When defining serialization functions the code [uses the ambiguous variable name](https://github.com/ProseMirror/prosemirror/blob/e6679d27c8dd129decb41a19c0b2045ecd80c2d8/src/format/to_dom.js#L175) `s` short for "serializer," the DOM Serializer object.

I think we should use `serializer` here so that developers not intimately familiar with the internals will have a better clue as to what that variable does.

**Comment by marijnh** [comment]
The state object is no longer passed to serializer methods, so this is moot now.
