### ISSUE TITLE
Tooltip menu does not disappear when expanded

### ISSUE THREAD

**Issue by salzhrani** [ProseMirror/prosemirror#27]
When text is selected and a dialog is visible ( Link dialog for example) , it does not disappear on deselection.

**Comment by marijnh** [comment]
It does for me. Can you describe what you are doing, with which code, on which browser, in more detail?

**Comment by salzhrani** [comment]
I am on chrome Version 45.0.2454.85 on mac os. and I tried the [basic demo](http://prosemirror.net/demo_basic.html) page. when I selected some text and hit the link menu item and the dialog shows up, then I click anywhere on the text... the selection disappears but the menu remains
