### ISSUE TITLE
ProseMirror sets content in the wrong editor

### ISSUE THREAD

**Issue by jacwright** [ProseMirror/prosemirror#270]
I have a page with several "sections" which can be removed and added from the DOM. These sections have a prosemirror editor inside them.

When they are removed and later added back, their pm editor's `setContent` method will set the content of the next prosemirror instance on the page. The `pm.content` property still points to the right element, but `pm.setContent` setting the contents of another editor on the page.

**Comment by marijnh** [comment]
This seems rather unlikely, and a quick test shows that it doesn't happen if I create two editors in a test setup. You're most likely getting your own editor instances confused. Feel free to reopen if you can add a minimal test case that shows the issue.
