### ISSUE TITLE
Support info strings on fenced code blocks

### ISSUE THREAD

**Issue by sawyerh** [ProseMirror/prosemirror#272]
Currently this Markdown:

![image](https://cloud.githubusercontent.com/assets/371943/13929184/42da4c6e-ef6f-11e5-9921-68f4348f82ce.png)

loses the info string when it's converted to WYSIWYM. According to the CommonMark Spec (see [example 100](http://spec.commonmark.org/0.23/#example-100)), the `code` HTML element should receive a class of `language-ruby`.

**Comment by marijnh** [comment]
Yes, such an attribute will be part of a Markdown-specific schema that I will at some point in the future work on. There's a bunch of other Markdown quirks, such as 'tight' lists, that the default schema doesn't implement.

**Comment by marijnh** [comment]
The new schema in https://github.com/ProseMirror/prosemirror-markdown has a `params` attribute for this purpose.

**Comment by KyleAMathews** [comment]
@marijnh are we supposed to use the `default` param for setting the code block language? https://github.com/ProseMirror/prosemirror-markdown/blob/master/src/schema.js#L43

In my testing a code block like:

    ```javascript
    var i;
    ```

gets parsed and then serialized back to:

    var i;

Losing the language part. I'm writing my own parser and I'm passing in the language as the `default` param but that's not helping.

Is the language being stored inside Prosemirror's doc structure just not being serialized back to markdown correctly?

**Comment by marijnh** [comment]
>  are we supposed to use the default param for setting the code block language? 

The _attribute_ is called `params`, and its default value is the empty string. So you're supposed to use the `params` attribute to store the string after the triple backticks.

The Markdown parser was apparently not reading these anymore. Attached patch should help.

**Comment by KyleAMathews** [comment]
Oh! Just using `params` made things work! Thanks!

I'm writing a custom parser based on Remark so easy fix.
