### ISSUE TITLE
Copy & paste does not work inside the editor

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#277]
Trying to copy and paste content inside the editor does not do anything and no errors are thrown. I could reproduce this using the latest version from master, so it is probably related to the new linear positions system.

Example to reproduce:
1. Write some text inside the editor, e.g. ```hello```
2. Select and copy the text
3. Move cursor somewhere in the document and try to paste
-> Nothing happens

**Comment by marijnh** [comment]
Yes, this was a refactoring mistake introduced by the linear position changes. Attached patches solve it for me.
