### ISSUE TITLE
Pasting external content throws uncaught errors

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#278]
Copying text from an external source and trying to paste it inside the error, throws uncaught errors. The copied text is successfully inserted into the document, but depending on where the content is pasted, it throws different errors and sometimes causes the cursor to be incorrectly positioned.

I could reproduce this using the latest version from master, so it is probably related to the new linear positions system.

Errors I've encountered:
* Index X out of range
* Cannot read property 'nodeSize' of undefined
* Position X out of range

**Comment by marijnh** [comment]
I think this is fixed by 38c3c48 (though I could only get the first error to occur). Could you see if it you can still reproduce it with current master?

**Comment by kiejo** [comment]
Great, I can confirm this is fixed with current master!
