### ISSUE TITLE
Does not work image resizer on Chrome

### ISSUE THREAD

**Issue by sergeykaul** [ProseMirror/prosemirror#28]
OS Fedora 21, Google Chrome version 44.0.2403.155 (64-bit). How to reproduce: open http://prosemirror.net/demo_basic.html and click the smile image to activate image resizer. It does not activate. (Firefox - OK)

**Comment by marijnh** [comment]
Image resizing is not implemented. This is know and by design, but once document schemas work, I do intend to implement a size attribute on images and a widget that allows you to resize image elements.

**Comment by forresto** [comment]
The image resizing in Firefox is actually something I'd like to suppress:

![screen shot 2015-12-02 at 11 03 07 am](https://cloud.githubusercontent.com/assets/395307/11535992/673cb95c-98e4-11e5-9753-6c6794558311.png)

**Comment by marijnh** [comment]
Are you still getting it with the latest code? This is something that I believe I fixed recently (by setting the image to be non-editable in its render method).

**Comment by forresto** [comment]
In ff with master the resize controls show up when the image is clicked, but don't work to resize the image. Inspect element shows `_moz_resizing="true"` on the `img`.

**Comment by marijnh** [comment]
If I click on an image in Firefox with the current code, I select the image node as a ProseMirror node selection. As such, I believe this is fixed.
