### ISSUE TITLE
Writing a bullet point followed by a paragrpah with text throws "Cannot read property 'replace' of null" error

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#280]
I've tested this using the version from master. Typing the following content in the editor throws the uncaught error "Cannot read property 'replace' of null" in transform/step.js:132.

Content to type:
```
* asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf
asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf
```
The list item contains 10 "asdf"s. The paragraph contains 19 "asdf"s. The important thing seems to be the total number of characters. For example writing the same structure with 15 "asdf"s in the list item and 14 "asdf"s in the paragraph, throws the same error.

**Comment by kiejo** [comment]
I just found another very similar issue that is probably caused by the same underlying problem. Writing a nested list item followed by a paragraph of text throws the uncaught "Cannot read property 'resolve' of null" error in transform/join:14. In both cases ```doc``` is unexpectedly null.

Content to type:
```
* asdf asdf asdf asdf asdf asdf asdf
  * asdf asdf asdf asdf asdf asdf asdf  
asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asd
```
The second list item needs to be nested, which can be achieved using the ProseMirror menu using the wrap menu item (Ctrl+Shift+8). As with the other error, the total number of characters seems to be the important thing here.

**Comment by marijnh** [comment]
Do you have a stack trace? I wasn't able to reproduce this.

**Comment by kiejo** [comment]
This only seems to be reproducible if the content is typed out by hand. Copying and pasting parts of the text does not lead to the error.

Here's a stack trace (unfortunately without sourcemaps):
![stacktrace](https://cloud.githubusercontent.com/assets/152507/14101470/0ac4e5d8-f595-11e5-9bd6-8cbed8230932.png)

This is probably related to #266 as it originates from the history compression algorithm. It also makes sense now, that you have to type it by hand to get the error.

**Comment by marijnh** [comment]
Thanks, that gave me enough to find the problem. Attached patch should solve it.
