### ISSUE TITLE
Linear document positions breaks ActiveMarks() and command.active()

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#281]
Just updated to the head (142a969859de69515503836ca203fd9abb724966) and my toolbar stopped working :(. Looks like `activeMarks()` is not returning the correct set for cursor. It does however return correct set when there's a selection.

Possibly due to same issue, `command.active()` is no longer returning correctly.

**To Reproduce**
* Write "hello world, how are you?"
* Bold "world"
* Set cursor within "world"
* run `pm.activeMarks()`

**Actual result:** empty array
**Expected result:** an array of size one, containing the strong mark.

**Comment by wes-r** [comment]
https://github.com/ProseMirror/prosemirror/blob/cf15a2ef4e8d64cca0eb993e61826898f5d69f0e/src/model/node.js#L212
`let leaf = index ? top.child(index - 1) : index < top.childCount ? top.child(index) : null`
In the case I'm looking at, the line above is the culprit. `index - 1` is suspect and what happens in the case of `index == 0`?

**Comment by marijnh** [comment]
Indeed, that line was broken (though not in the case of index == 0 -- that was handled properly by the second clause). Attached patch helps.
