### ISSUE TITLE
Firefox: ⌘-A select all not working

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#282]
On http://prosemirror.net/, focus editable and press ⌘-A. Selection flashes and caret ends up at end of editable.

Expected: editable is all selected

**Comment by marijnh** [comment]
I think this is fixed in 0.5.0 (the demo is on an older version) and in master. Could you check?

**Comment by marijnh** [comment]
(I've just updated the demo pages to the current code.)

**Comment by forresto** [comment]
I'm seeing same bug on prosemirror.net and our own app with 0.5.1.

**Comment by marijnh** [comment]
I booted my Mac, but could not reproduce the issue on current prosemirror.net (which runs yesterday's git code)

**Comment by marijnh** [comment]
Oh, I missed the part where it says 'Firefox' in the issue title. I _can_ reproduce in Firefox. Will look into it.

**Comment by marijnh** [comment]
Attached patch should help.
