### ISSUE TITLE
Clicking on an inline node that is the last element of a paragraph throws uncaught error

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#283]
I have an inline node that renders a span with some text based on its attributes. Clicking on such an inline node works correctly as long as it is followed by some text in the same paragraph. If its the last child of the paragraph, clicking on it throws a "Cannot read property 'type' of null" error in edit/input.js:219.
I could not reproduce this error with an image inline node.

There seems to be a problem with the `posBeforeFromDOM` method as it returns a position where apparently no node can be found: https://github.com/ProseMirror/prosemirror/blob/a0a348390dc39a23143f29282ff8692d1eed03a2/src/edit/input.js#L218

I think this might be related to #268.

**Comment by marijnh** [comment]
Does this happen in Chrome as well? Could you show me the precise HTML that this node renders as? (I can't reproduce it by changing the way `Image` is rendered.)

**Comment by kiejo** [comment]
Yes, this happens in Chrome. By trying to break it down into a simpler example, this is the node I came up with:
```javascript
import {Inline} from 'prosemirror/dist/model';
import {elt} from 'prosemirror/dist/dom'

class Test extends Inline { }

Test.prototype.serializeDOM = (node, s) => {
  return elt('span', {
    'data-type': 'test'
  }, [
    elt('span', {class: 'prefix'}, '@'),
    elt('span', {}, 'Hello'),
  ]);
};

Test.register('command', 'insert', {
  derive: true,
  keys: ['Mod-Shift-K'],
});
```

This results in the following HTML:
![inline_click](https://cloud.githubusercontent.com/assets/152507/14134638/f72cfb86-f658-11e5-857a-ba1abd74878c.png)

Something interesting I noticed when creating the example, is that using `s.elt` instead of `elt` throws the error `Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.` in `format/to_dom.js:30`.

**Comment by marijnh** [comment]
The inner `<span>` triggered it. Attached patch seems to help.
