### ISSUE TITLE
Support `inclusiveLeft` and `inclusiveRight` properties for mark types

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#285]
Which determine whether new text inserted at their start or end gets the mark.

See https://discuss.prosemirror.net/t/controlling-inclusive-left-right-of-marktypes/267/3

**Comment by kiejo** [comment]
I will try to do this one. My approach would be to put the main logic of this into the `marksAt` method of the `Node` class. Is this the right approach or is there a better way? Just want to be sure before I start implementing something.

**Comment by marijnh** [comment]
Yes, that's what I would have tried as well.

**Comment by marijnh** [comment]
Fixed via #287
