### ISSUE TITLE
Frequently changing the cursor position while typing throws uncaught error

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#286]
Frequently changing the cursor position while typing throws the error `Resolving a position in an outdated DOM structure`.
The easiest way I found to reproduce this is the following: Create two paragraphs and move the cursor up and down (using the arrow keys) fast while typing something.

Here's a stack trace:
![outdated_dom](https://cloud.githubusercontent.com/assets/152507/14151805/15c4be42-f6b0-11e5-82ac-819def342608.png)

**Comment by marijnh** [comment]
I think attached patch will help (and address a few other problems of the same class -- an event firing while our DOM hasn't been updated yet). Could you verify that it fixes your issue?

**Comment by kiejo** [comment]
Nice, I can confirm that this fixes the issue for me!
