### ISSUE TITLE
Strange drag and drop behavior

### ISSUE THREAD

**Issue by sergeykaul** [ProseMirror/prosemirror#29]
OS Fedora 21, Google Chrome and Firefox. How to reproduce: open http://prosemirror.net/demo_basic.html . Select any text that is outside of the editor, drag it to the editor area and drop. Repeat this step again. The first insertion is disappeared

**Comment by tgecho** [comment]
I can't reproduce this on Fedora (22), OS X or Windows. I tried dragging text from inside the page and also from other applications.

Does it happen in any other browsers/OS combinations? Do you have any extensions that might be messing with something?

**Comment by sergeykaul** [comment]
Thank you for the comment. I have checked this issue right now. You are right - this issue is not reproduced now
