### ISSUE TITLE
Certain auto input rules throw uncaught error when pressing undo

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#291]
I tested this on the latest master (rewritten history module). I have the following `InputRule`, which turns `"---"` into a `HorizontalRule`:
```javascript
HorizontalRule.register('autoInput', 'insert', new InputRule(
  /^---$/,
  '-',
  function(pm, match, pos) {
    var $pos = pm.doc.resolve(pos);
    var matchLength = match[0].length;

    // Do some sanity checks (e.g. position in top level paragraph)

    // Insert HR
    var targetPos = pos - matchLength;
    pm.tr.delete(targetPos, pos) // Delete the matched characters (three dashes)
         .setBlockType(targetPos, targetPos + 1, this) // Change parent paragraph into a HorizontalRule
         .apply(pm.apply.scroll)
  }
));
```
I disabled the default `emDash` rule using ```removeInputRule(pm, autoInputRules.emDash)```.  

Typing `---` in an empty document and then pressing `Cmd/Ctrl-Z` throws the error `Position 3 out of range`. Here's a stack trace:
![undo_input_rule](https://cloud.githubusercontent.com/assets/152507/14387746/185eb9b2-fdab-11e5-9a28-7b7d3f647587.png)

**Comment by marijnh** [comment]
```javascript
   pm.tr.delete(targetPos, pos) // Delete the matched characters (three dashes)
         .setBlockType(targetPos, targetPos + 1, this) // Change parent paragraph into a HorizontalRule
         .apply(pm.apply.scroll)
```

This is rather illegal. `setBlockType` is for changing text blocks, using it to go from a textblock to a contentless block will create a step that can't be inverted, and thus break the history.

You can use `pm.tr.replace(targetPos - 1, pos + 1, this.create()).apply(pm.apply.scroll)` instead.

I've pushed a patch to raise a meaningful error when this happens.

**Comment by supunkavinda** [comment]
Just a note for future readers, I had to use `replaceWith` instead of `replace`, and `scrollIntoView` instead of `apply`.

```
pm.tr.replaceWith(targetPos - 1, pos + 1, this.create()).scrollIntoView()
```
