### ISSUE TITLE
Pressing Ctrl-Enter / Ctrl-Backspace results in a JS error

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#293]
Tried this with latest (f96c90bf9adb5c5b19de05d2dc949d18bd9ed86c) and on [demo page](http://prosemirror.net/demo/basic.html).

With the editor in focus (can edit), click `CTRL-ENTER`. This results in a JS error and a newline which seems to have an invalid node/pos as it makes selections not work and more js errors.

From demo page:
![screen shot 2016-04-09 at 11 10 28 am](https://cloud.githubusercontent.com/assets/1568246/14404421/df77926a-fe43-11e5-93e2-fcecf273caad.png)

Locally (with latest master):
![screen shot 2016-04-09 at 11 10 38 am](https://cloud.githubusercontent.com/assets/1568246/14404420/df77575a-fe43-11e5-9eba-5575475e5b47.png)

Also just found `CTRL-BACKSPACE` also causes similar error.

**Comment by marijnh** [comment]
Which browser? I can't reproduce this in Chrome so far.

**Comment by wes-r** [comment]
Chrome on Mac: Version 49.0.2623.87 (64-bit)
Safari on Mac: Version 9.0.2 (11601.3.9)

Can't seem to get it to reproduce on firefox.

**Comment by marijnh** [comment]
What does Ctrl-Enter do on Mac? ProseMirror so far only binds Cmd-Enter.

**Comment by wes-r** [comment]
I'm not sure... but it errors for me inside ProseMirror

**Comment by wes-r** [comment]
In google docs it does nothing, in TextEdit it creates a newline

**Comment by wes-r** [comment]
An easy work around maybe for me to just capture those key combos and do nothing.

**Comment by marijnh** [comment]
Agreed. Attached patches do pretty much that (though they do also make Ctrl-Backspace equivalent to Cmd-Backspace in the default bindings)

**Comment by marijnh** [comment]
(I closed already, but do test and let me know if it doesn't work yet. It should be straightforward, but I didn't actually run this on a Mac)

**Comment by wes-r** [comment]
Confirmed! No more errors and Ctrl-Enter behaves like Shift-Enter.

Thanks for the quick fix!
