### ISSUE TITLE
Undoing a nested bullet list behaves incorrectly when the collab module is active

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#294]
This is probably related to #292. Here's the `demo.js` I used:
```javascript
var ProseMirror = require("../dist/edit/main").ProseMirror
require("../dist/inputrules/autoinput")
require("../dist/collab")

var pm = window.pm = new ProseMirror({
  place: document.querySelector(".full"),
  autoInput: true,
  collab: {version: 0}
})
```
Here's a recording of what goes wrong when undoing nested bullet lists. In contrast to https://github.com/ProseMirror/prosemirror/issues/292#issuecomment-207495781 you have to break out of the lists (press `Enter` three times) before pressing undo multiple times to see an incorrect behavior. This only happens if the `collab` module is used.
![bullets](https://cloud.githubusercontent.com/assets/152507/14409028/57c82af0-ff0b-11e5-8e80-a95b0386a88d.gif)

**Comment by marijnh** [comment]
Thanks for reporting that! These kind of edge case issues are hard to find (maybe I should bring back the fuzzer). Fixed in efeb4d8
