### ISSUE TITLE
Paste is broken on iOS

### ISSUE THREAD

**Issue by krasnoukhov** [ProseMirror/prosemirror#295]
Platform: Safari on iOS 9.3
Version: master

The issue is really simple to reproduce. After selecting some text and pressing copy or cut, standard iOS menu does not have paste option.

Here is the video: https://monosnap.com/file/t5g2WcGdHT2XKu4WVs339XHXKnjzdX

Maybe I'm missing something? Thanks

**Comment by marijnh** [comment]
Could you check whether attached patch helps? It'll lead to a degraded form of copy/paste when `clipboardData` is broken, but that's still better than no copy/paste at all.

**Comment by krasnoukhov** [comment]
Yeah, that works. Thanks!
