### ISSUE TITLE
arrow key jump when moving leftward onto an inline span node

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#298]
How to reproduce:

A. Define an inline node type such as
```
class Citation extends Inline {}

Citation.prototype.serializeDOM = (node, serializer) => {
    let dom = serializer.renderAs(node, "span", {
        class: 'citation'
      })
    dom.innerHTML = 'CITATION'
    return dom
}
```

B. Add a few of these nodes to a document.

C. use the left arrow key to move toward one of these elements.

D. As the caret is reaching the right-hand side of the inline node...

Observed behavior: The caret jumps 8 characters further to the right within the same paragraph.

Expected behavior: The inline node should be selected.

**Comment by marijnh** [comment]
Try with `return serializer.elt("span", {class: "citation"}, "CITATION")`. What you're doing there will mark the node as a container of other nodes, but then you overwrite its content, confusing the DOM structure.

**Comment by johanneswilm** [comment]
Yes, that worked thanks!

**Comment by johanneswilm** [comment]
Yes, that worked thanks!
