### ISSUE TITLE
syntax highlighting for code blocks?

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#3]
Would a plugin to edit code within the ProseMirror flow be possible? (For example after typing <code>```</code> .) 

I'm working on an editor with arbitrary media overlays (audio, video, maps, code), but ProseMirror's architecture seems much more sane than what I've hacked with Scribe.

**Comment by marijnh** [comment]
No, this is not something that is easy to do (or even realistic). We might be able to get syntax highlighting based on CodeMirror modes to work for code blocks, but a full CodeMirror instance is much more problematic.

**Comment by forresto** [comment]
What about a generic overlay system that would be synced by position but not in the editable DOM?

**Comment by marijnh** [comment]
Something like that (see also the 'cards' concept in [content-kit](http://madhatted.com/2015/7/31/announcing-content-kit-and-mobiledoc) ) might eventually be something we'd want to integrate. But I think ProseMirror's place in such a system should be that of a sub-component in a bigger multi-content-style system, not the multi-content-system itself.

**Comment by pwFoo** [comment]
syntax highlighting for code blocks would be a great extension / plugin.

**Comment by friksa** [comment]
+1 for syntax highlighting for code blocks

**Comment by forresto** [comment]
https://github.com/the-grid/ed fits the 'cards' concept in content-kit and implements an iframe-hosted CodeMirror widget.
