### ISSUE TITLE
IE 10: Object doesn't support property or method 'register' 

### ISSUE THREAD

**Issue by MichalZalecki** [ProseMirror/prosemirror#300]
Hi there!

I faced a problem with prosemirror running on IE 10 (Windows 7, Windows 8). I'm building project with webpack and actually I'm using also [react-prosemirror](https://github.com/tgecho/react-prosemirror) which is basically responsible for mounting and unmounting editor.

It was the problem with `0.5.1` and still continue in `0.6.0`.

Error `Object doesn't support property or method 'register' ` was throwed on:

```
Paragraph.register("parseDOM", "p", {parse: "block"})
```
https://github.com/ProseMirror/prosemirror/blob/master/src/format/from_dom.js#L336

Everything is fine on Firefox, Chrome, Safari and IE 11 (Windows 7 and Windows 8.1) and IE 12 and IE 13 (Windows 10).

**Comment by marijnh** [comment]
That's a Babel limitation. See [this issue](https://phabricator.babeljs.io/T2450). A plugin like [this one](https://www.npmjs.com/package/babel-plugin-proto-to-assign) will probably help.

But for now, IE10 isn't in the set of browsers I support, so other things are likely to break.

**Comment by MichalZalecki** [comment]
Thanks for the answer. I'm using Babel 6 so I have to use [babel-plugin-transform-proto-to-assign](https://www.npmjs.com/package/babel-plugin-transform-proto-to-assign). Unfortunately it didn't changed anything.

**Comment by borriglione** [comment]
Same problem here. I use the pre-compiled ES5 dist-version from npm-package

**Comment by marijnh** [comment]
Inherited static methods seem to be problematic in general -- TypeScript also doesn't support them, nor does the Bublé compiler. The plan is to stop relying on them (probably in 0.8.0). See #305

**Comment by marijnh** [comment]
The code on the current master branch no longer relies on static methods being inherited by subclasses, so we've sidestepped this issue (which also exists in Bublé-compiled output).
