### ISSUE TITLE
Android Chrome: uncaught errors with autocomplete keyboard

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#304]
1. Open http://prosemirror.net/ on device and inspect with chrome://inspect
2. Type `Hello.` with on-screen keyboard
3. On pressing `.` the cursor jumps to the start of the next paragraph and these errors show in console:

```
Uncaught RangeError: Failed to find node at 216
Uncaught TypeError: Cannot read property 'nodeSize' of undefined
```

**Comment by marijnh** [comment]
The website demo wasn't using the current git code. I've updated it and can no longer reproduce this issue.
