### ISSUE TITLE
Collaborative protocol risks applying changes twice

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#307]
(when on unreliable communication channel).

Discussion on [the forum](https://discuss.prosemirror.net/t/how-to-handle-edge-case-with-collab-module/288).

**Comment by marijnh** [comment]
Attached patch should help. See the [new collab guide](https://github.com/ProseMirror/website/blob/master/pages/guide/collab.md) for an overview. In short, you now send along a client id when sending steps to the server, and ignore the return value. The server tracks the client id for each steps, and sends along an array of client ids when it sends new steps. The client then uses these to determine which steps were its own, and which come from peers.

**Comment by marijnh** [comment]
(Testing and comments would be great.)

**Comment by kiejo** [comment]
I just tested this with our setup and can confirm that it fixes the duplicate syncing issues for us. The edge cases that I was able to reproduce do not lead to any duplicate steps anymore :)
