### ISSUE TITLE
List item marker disappears after typing on Mobile Safari

### ISSUE THREAD

**Issue by krasnoukhov** [ProseMirror/prosemirror#308]
Platform: Safari on iOS 9.3
How to reproduce:

1. Create a list
2. Tap return to create a new item
3. Start typing, marker disappears

This is relevant for both types of lists.

Screencast: https://monosnap.com/file/1ozIrW2YXBliZk9K5LSbP5JqlT3Y6S

**Comment by krasnoukhov** [comment]
I still can reproduce that, even with a patch 😢

**Comment by marijnh** [comment]
Oh, that's too bad. I could reproduce it before, but the patch fixed it for me. Will take another look.

**Comment by marijnh** [comment]
With the Safari in iOS 9.3.1 the problem is really gone. Are you, by any chance, using XHTML in your page? That might mess up the test for list item nodes. Could you add a `console.log` in the `if` inside the `iosHacks` function that my patch added, and see whether it actually runs when you are typing into a list item?

**Comment by krasnoukhov** [comment]
I can confirm that the hack is running but the problem is not gone for me. Can you update demo site with a new code? I'm wondering if there's something with my integration then

**Comment by marijnh** [comment]
I've updated the website code to use the current git revision. Let me know if the issue still occurs for you there.

If so, could you try replacing `iosHacks` with this code, and see if anything changes?

```javascript
function iosHacks(dom) {
  if (dom.nodeName == "UL" || dom.nodeName == "OL") {
    dom.style.listStyle = "square"
    setTimeout(function() { dom.style.listStyle = "" }, 100)
  }
}
```

**Comment by krasnoukhov** [comment]
Thanks! I wasn't able to reproduce this on a website, so I started investigating and just found out what the cause is.

The thing is that I have `list-style: inherit !important` rule in app CSS, so the `dom.style.listStyle = "square"` basically does not update visual representation, since that rule has lower priority.

Here is how it can be fixed:

```javascript
function iosHacks(dom) {
  if (dom.nodeName == "UL" || dom.nodeName == "OL") {
    let cssText = dom.style.cssText
    dom.style.cssText = "list-style: square !important;"
    window.getComputedStyle(dom).listStyle
    dom.style.cssText = cssText
  }
}
```

Having `!important` there would beat any external rules, which is desired behavior in order to get repainting actually work. Please let me know what you think!

**Comment by marijnh** [comment]
Using `cssText` has the disadvantage of clearing all other inline styles that might be present on the node. Could you verify that attached alternative approach works for you?

**Comment by krasnoukhov** [comment]
Thanks for looking into this again, but I tried suggested approach first and it didn't work. Please see screencast of the behavior I see using `setProperty`: http://take.ms/xWtOnF

I know that switching `cssText` is quite suboptimal option, but that's the only way I was able to make it work consistently. Maybe `cssText` can be temporarily extended with `list-style` rule in order to not lose other styles? And besides that it's set back to original value anyway, so it should be fine in any case, no?

**Comment by marijnh** [comment]
The screencast looks like the property isn't being reset after the kludge. Sorry to keep asking you to test stuff (don't have my iPad with me), but could you see if replacing `dom.style.listStyle = ""` with `dom.style.removeProperty("list-style")` fixes that?

**Comment by krasnoukhov** [comment]
No problem, it's my best interest to get it finally working. I tried using `removeProperty` before, but it didn't work. I tried that approach again, and unfortunately it behaves the same as direct property assignment, so it does not clear the previously set value. That seems like a another Mobile Safari bug. So, unfortunately, only setting `cssText` works when `!important` is involved. Do you think you can explore this approach? I think it would be possible to use that not losing any styles at the same time.

**Comment by marijnh** [comment]
Well, that's unfortunate. Any chance you can remove the `!important` in your styles and just increase the precedence of your rule?

**Comment by krasnoukhov** [comment]
I'm afraid It's not possible for our case since we integrate prosemirror into pretty messed up project in terms of CSS and we want to keep markdown styles consistent between integration points. I was thinking that prosemirror should try to do that anyway since there's a chance somebody else will report this and and it may not be possible to not use `!important` for them as well. Don't you agree?

**Comment by marijnh** [comment]
Yes, I guess we're just going to have to do this the crude way then. It'll be even more likely to cause needless relayouts, abut oh well. I hope Apple gets their act together eventually and fixes this. See if patch 6e18b48 solves the problem for you.

**Comment by krasnoukhov** [comment]
Yeah it works! Thank you so much 💚
