### ISSUE TITLE
Prevent nested Lists

### ISSUE THREAD

**Issue by StephanHoyer** [ProseMirror/prosemirror#31]
First thanks for this great piece of software.

Is it somehow possible to prevent list nesting?

I have the usecase where users shouldn't be able to do this.

I just look into the `command.js` module but can't figure out a way to prevent wrapping another `bullet_list`.

**Comment by marijnh** [comment]
You'll have to wait for further developments on the schema langauge / API. Right now, it isn't possible, but this is definitely planned for the future.

**Comment by marijnh** [comment]
With the new (as of yet undocumented) Schema API, you can now specify the way node types may nest. You could, for example, set `list_item` nodes to only contain `paragraph` nodes, and thus ensure that lists won't nest. The commands/menu items all understand the schema rules and will disable themselves when not applicable.

You can expect basic documentation of this to appear within a month or so. Reading though `src/model/schema.js` might be enlightening if you want to use it sooner.

Closing this issue now.

**Comment by StephanHoyer** [comment]
Thanks for the effort on this. I just tried to get my head around it but I don't got far understanding how this can be accomplished. Can you please give me another hint or two?

**Comment by marijnh** [comment]
Look at [`NodeType.contains`](http://prosemirror.net/doc/manual.html#NodeType.contains) and [`kind`](http://prosemirror.net/doc/manual.html#NodeType.kind).

**Comment by pboysen** [comment]
Maybe this will help.  I have a multiplechoice question which has a list choices.  The first is just a paragraph but the remainder are decorated with a radiobutton.  Because choice extends Paragraph, you can insert an mc question into a choice. And as marijn says, if you want to extend from another nodetype, provide and contains function.

```
export class Choice extends Paragraph {
	static get kind() { return "." }

	create(attrs, content, marks) {
		if (attrs.value > 0) content = [this.schema.node("radiobutton",attrs)]
		return super.create(attrs, content, marks)
	}
}

Choice.attributes = {
	name: new Attribute(),
	value: new Attribute()
}

export class MultipleChoice extends Block {
	static get contains() { return "choice"}
}

MultipleChoice.attributes = {
	name: new Attribute()
}
```
