### ISSUE TITLE
Predictive input gets out of sync on Mobile Safari

### ISSUE THREAD

**Issue by krasnoukhov** [ProseMirror/prosemirror#310]
Platform: Safari on iOS 9.3
How to reproduce:
1. Type some text
2. Tap backspace
3. Predictive input does not reflect changes

Note: it seems that only typing space resets its state.

Screencast: https://monosnap.com/file/VTfsDdPHLplRotIVeUlQvgzg9HqDdo

**Comment by marijnh** [comment]
Related to #25. Hard to fix in a general way until Apple fixes the bug on their side, or someone finds a kludge to reset the keyboard without disrupting the user experience. We can try to find individual workarounds for specific commands (for example, in the case of backspace we can assume the the browser's default behavior is going to do the right thing if there's text before the cursor)

**Comment by krasnoukhov** [comment]
I'm wondering if we should report this to Apple as well. @marijnh what do you think?

**Comment by krasnoukhov** [comment]
Seems like this is fixed along with #390. Thanks @marijnh!
