### ISSUE TITLE
Native toolbar overlaps prosemirror menubar on Mobile Safari

### ISSUE THREAD

**Issue by krasnoukhov** [ProseMirror/prosemirror#312]
Platform: Safari on iOS 9.3
How to reproduce:

1. Select some text on a first line

Not sure if this is prosemirror problem, but maybe you have some suggestions how to address that?

Screenshot: http://take.ms/8RqYA

**Comment by marijnh** [comment]
Duplicate of #7

**Comment by krasnoukhov** [comment]
Oops, sorry!
