### ISSUE TITLE
creating empty marked range includes remaining part of block node.

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#313]
Try this:

pm.markRange(24,24,{removeWhenEmpty:false,className:'test'})

Expected behavior:
An empty span is created with the class "test" at position 24.

Observed behavior:
A span with the class "test" is created and it starts at position 24 and goes until the end of the block node it is in. If all characters within the span are deleted, the span is automatically removed as well (not respecting 'removeWhenEmpty')

First reported by @momenifi .

**Comment by marijnh** [comment]
Attached patch fixes the first problem. I can not reproduce the issue where `removeWhenEmpty` doesn't work. Could you provide a more precise description of what you're deleting and how?

**Comment by johanneswilm** [comment]
Ok, this may be me having misunderstood how tge feature was supposed to work.

Take this example:

This is [a sentence.]|

Marked range = [...], caret = |

If the user hits backspace until the "a" is gone, I had expected this:

This is []|

But instead I get:

This is |

If this is how it is supposed to work, that is fine. The important part is being able to place an empty marked range.

**Comment by marijnh** [comment]
That's not how they are supposed to work -- but that's also not what they do when I test them -- my mark is still active, i.e. it's `from` and `to` are not null.

**Comment by johanneswilm** [comment]
> Attached patch fixes the first problem.

Hmm, here it actually looks differently right now with the patch applied. The marked range exists with from and to having values (the same), but there is no empty span with the desired class in the DOM. I will test a little more...

**Comment by johanneswilm** [comment]
Yes, same conclusion after testing. If to and from have different values, there is at least one span with the desired className. If they are the same, there is no span at all. The patch, from my reading of it also seems to say that if from and to have the same value, don't draw it at all. If I'm not mistaken, this used to work in PM =< 0.5.1 .

**Comment by johanneswilm** [comment]
> That's not how they are supposed to work -- but that's also not what they do when I test them -- my mark is still active, i.e. it's `from` and `to` are not null.

@marijnh Indeed, as far as the JavaScript goes, you are right. But in the DOM, there is no empty span in that place any more. That's what I am in need of.

**Comment by marijnh** [comment]
Yes, an empty range will not create an empty span. That's by design.

**Comment by johanneswilm** [comment]
Ok, and what is the reasoning? If I want to mark a part of the document using a css class (in our case to show where coeditors currently have their selection using a border and background-color), why should it matter how much content it contains?

Also, isn't it inconsistent that the marked region still exists in JS, but is gone in the DOM, just because the width happens to be zero?

At least I think there should be a note in the documentation warning that marked regions with a width of zero will not be rendered.

**Comment by marijnh** [comment]
A marked range marks a piece of _content_ (optionally with a class). It does not at all represent a DOM node -- it might result in multiple spans, or, as you saw, no spans at if there is no content to mark.

**Comment by johanneswilm** [comment]
Yes, multiple spans is fine. But no spans is a bit weird. What is one supposed to use the class for if it's not to either figure out at what coordinates in the DOM the range is or to style it?
