### ISSUE TITLE
`npm run demo` currently broken in npm prosemirror install

### ISSUE THREAD

**Issue by lhl** [ProseMirror/prosemirror#317]
The [documentation tells users](http://prosemirror.net/guide/basics.html#creating_an_editor) to install ProseMirror via npm - building (`npm run dist`) works fine, however trying to run the demo fails - the `demo` folder is just missing from the npm package?

The bower package includes the demo folder and `npm run demo` works as expected.

**Comment by marijnh** [comment]
Yes, those instructions are for the git repository, not the NPM distributed package. The demo isn't part of the distribution. I've updated the README to mention this in 8102437
