### ISSUE TITLE
trying to place an empty markRange inside an empty container gives rangeerror

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#318]
Given this content

```
<p></p>
```

Where the position inside the paragraph is 1, trying to do pm.markRange(1,1,{removeWhenEmpty: false,className:'test'})

Gives this error: Uncaught RangeError: Index 0 out of range for <>

Seems not to happen when there is no className

**Comment by marijnh** [comment]
Given that content, the position inside the paragraph is 1, not 2.

**Comment by johanneswilm** [comment]
@marijnh yes, sorry, that was confusing. I just tried to pick a random number for the example. It seems to happen no matter what the number is. Also in larger documents. And it seems not to happen if there is no className.

**Comment by marijnh** [comment]
Thanks. Attached patch should help.
