### ISSUE TITLE
Headings created via autoInput break select and active methods of commands

### ISSUE THREAD

**Issue by tjunnone** [ProseMirror/prosemirror#320]
Headings inserted via the autoInput module do not work correctly with the select() or active() methods of the 'heading:make_' commands.

Example steps to reproduce on the basic demo page:
- Type "foo", select "Heading 1" from the menubar to make it a heading
- Observe that the "Heading 1" entry option is now correctly removed from the menu bar for the "foo" line (select of command 'heading:make1' returns false)
- Type "# bar", autoinsert changes "bar" to a heading
- Observe that the "Heading 1" entry option (or any other option) is not removed as expected from the menu bar for the "bar" line (select of command 'heading:make1' returns true)
- The effect appears permanent, no movement of cursor or selection will make select() or active() of command 'heading:make1' return the expected values

Also tested local 0.6.1 version in addition to the demo page, both show the problem using Chrome 50.

**Comment by marijnh** [comment]
I think attached patch will help.

**Comment by tjunnone** [comment]
Verified with master, looks good. Thanks Marijn!
