### ISSUE TITLE
coordsAtPos giving incorrect values

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#322]
In at least these two situations, the coordinates do not seem correct. The below have come up as issues while trying to find the coordinates of empty ranges.

1. After the last letter within a blocknode containing severel lines of text. The coordinates given make it appear as if the pos is as high as the entire block (crossing several lines), and as if it's to the right of the block element.

2. At soft linebreaks. There is an issue with browsers in general, that they don't differentiate between before and after the line break (we are dealing with that), so PM won't be able to deal with this entirely by itself. However, currently coordsAtPos given back values that make it appear as if it is spanning both lines in height. getClientRects() should give give two different rects, and it would be preferable if one would simply chose one rather than trying to combine both with getBoundingClientRect(). Or alternatively allow for some way to return more than one set of coordinates.

**Comment by marijnh** [comment]
Attached patches seem to help.
