### ISSUE TITLE
Codeblock menu entry throws TypeError

### ISSUE THREAD

**Issue by tjunnone** [ProseMirror/prosemirror#323]
Using the Basic demo at http://prosemirror.net/demo/basic.html:

- At the bottom of the document, type "line1"
- Hit Ctrl or Shift-Enter to start a new line in the same paragraph
- Type "line2"
- Select both lines
- From the _Type..._ menu select "Code"

Outcome:
JS error "Uncaught TypeError: Cannot read property 'openLeft' of null" and no change to the text.

Expected:
A single Codeblock containing the two lines

The example paragraph of the basic demo containing the inline image has a similar problem.

Tested with Chrome 50.

**Comment by marijnh** [comment]
Thanks for noticing those. With attached patch things work again for me.
