### ISSUE TITLE
Unlink menu in demo does not unlink

### ISSUE THREAD

**Issue by tjunnone** [ProseMirror/prosemirror#324]
- At http://prosemirror.net/demo/basic.html position the cursor somewhere in the "link" text
- Observe that the link menu item highlights and changes to "Unlink" as expected
- Pressing unlink does nothing, I would however expect it to remove the link the cursor is positioned in
- (If you select a range of characters, unlink does work, but this seems like unnecessary additional work)

Using Chrome 50, also tested with local version 0.6.1

**Comment by marijnh** [comment]
It works like strong and emphasis. If you put your cursor in an emphasized word and press the emphasis button, do you expect the word to lose emphasis? What happens is that the current set of styles loses the emphasis/link style, and typing creates text without that style.

This can be changed with custom commands, but for now the default is staying the way it is.
