### ISSUE TITLE
Cut and paste are broken in IE11

### ISSUE THREAD

**Issue by linus** [ProseMirror/prosemirror#325]
Internet Explorer has a different way of interacting with the clipboard. AFAIK this is the case in all versions of IE, with the possible exception of Edge.

Since the event doesn't have a `clipboardData` property, the default behaviour is not prevented, so the text gets pasted (or cut, respectively) anyway - it's just not added to ProseMirror's document, which makes all later interaction with the text very confusing.

A proposed patch would be to, in the absence of `e.clipboardData`, detect the presence of `window.clipboardData`, and if present, marshall that through to the `fromClipboard`/`toClipboard` handlers, matching the interface of the other browsers. I have a workaround for pasting and I would be happy to submit a pull request.

Tested on IE 11.0.9600.18283, Windows 8.1. ProseMirror 0.6.1 and master.

**Comment by marijnh** [comment]
So it turns out that IE (any version) does _not_ fire `input` events for contenteditable containers. So our general fallback strategy for changes we can't handle -- notice the `input` event and compare the DOM -- doesn't work on IE. It has a sort of half-hearted `textinput` event but that doesn't fire on cut or on spell correct and probably in a lot of other situations.

Edge fixes this, it seems.

This might end up meaning that IE support for ProseMirror will be Edge-only, since fighting broken Microsoft browsers is a stage of my life I kind of want to move on from. (So that I have time to fight broken Apple browsers).

**Comment by linus** [comment]
I'm sure you're right, but this quick-fix hooking into the cut and paste events and storing data on the window, falling back to window.clipboardData, seems to work quite ok. What are your thoughts?

https://github.com/ProseMirror/prosemirror/commit/c33468d3b371d9dccc41d315937ad31335cadfa1

**Comment by marijnh** [comment]
Why did you use a global on the `window` object instead of a module-local variable for the placeholder?

**Comment by marijnh** [comment]
(Also, didn't Microsoft _invent_ this API? [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData) suggests that it's supported it since 5.0)

**Comment by marijnh** [comment]
On closer look, what is the reason to have a wrapper at all? Attached patch seems to make copy/paste work on IE11

**Comment by linus** [comment]
The code I linked was just a quickfix for trying it out. It needs to be improved in more ways than one, including for drag and drop.
The reason for needing the wrapper is the different API - other browsers support various data types, mimetypes such as `text/html` etc, whereas `window.clipboardData` (or IE's `DataTransfer` object, really) only supports "Text" or "URL".
Your patch makes IE throw errors whenever `setData("text/html", data)` or `getData("text/plain")` etc are called, because the data types are not supported.
These errors ("Invalid argument") makes the event not prevented, so the text is actually cut and apsted in the contenteditable -- but not in ProseMirror's internal document. So if you cut and paste some text, and then edit the document, strange things will happen.
Again, if you think it a good idea I could whip up some solution, it would have to be a simple DataTransfer implementation I think, which could work with drag and drop as well (same problem really, anywhere `fromClipboard`/`toClipboard` is called).

**Comment by marijnh** [comment]
From what I can see, the API is already almost entirely compatible -- if we just translate the MIME strings we should be ok, no?

**Comment by linus** [comment]
Well, almost. ProseMirror uses both text/plain and text/html, right? IE only supports "Text". So whenever ProseMirror does something like [this](https://github.com/ProseMirror/prosemirror/blob/master/src/edit/input.js#L362):

    dataTransfer.setData("text/html", html)
    dataTransfer.setData("text/plain", toText(slice.content))

That would be two calls to `setData("Text", ...)`, right? So when pasting/dropping, the formatting would be lost. Whereas, another solution could retain the markup.

I'm sure there are other solutions, though.

**Comment by marijnh** [comment]
Oh, ugh, I read HTML instead of URL. Yeah, that's bad. In that case, I think this is going to be awfully kludgey and I'm not sure it's a big improvement.

We'll want to allow copying and pasting HTML from and to external pages and programs, so we'll need to let the events though, and then schedule `handlers.input` to be ran after a short timeout. (Just make sure it doesn't happen on Edge, where it'll already run due to a working `input` event.)

**Comment by linus** [comment]
OK so if I understand you correctly we would just not handle those events, let the browser deal with it, and then let ProseMirror pick up the pieces? Sounds good, I like it.
So, basically, instead of `if(!e.clipboardData) return` there would be something like `if(!e.clipboardData) handleInputSoon()`?

**Comment by marijnh** [comment]
Yes. I can't find a good way to feature-detect working input events, so we'll probably want to add a browser sniffing entry to `src/dom/index.js` for IE < Edge, and only run that `handleInputSoon` on that platform.

**Comment by linus** [comment]
AFAICT, Edge does not support the ClipboardAPI at all, [it's listed](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/clipboardapi) as "under consideration". Do I understand you correctly that it works anyway, because it fires input events when cutting/pasting?
If so, I guess you are right.

**Comment by marijnh** [comment]
Yes, the input event should prevent most of the issues. Though you get better support with a working clipboard API and it's somewhat disappointing that they haven't implemented this yet.

**Comment by johanneswilm** [comment]
We are trying to make sure the beforeinput/input events really all cases. That is currently not yet the case. 

The clipboard api people had the idea that paste and cut should be forced in contenteditable=true environments.

**Comment by linus** [comment]
I've been working on this but I can't seem to get @marijnh:s solution to work. Forgive my rudimentary findings but I am not versed enough in the editor internals.

I added something like this in `handlers.paste`:

```
if (!e.clipboardData) {
  setTimeout(() => {
    handlers.input(pm)
  }, 100)
  return
}
```

With various timeouts for the function. It seems as if pasting inbetween text works, but pasting at the end of a line always fails (it gets to `findDiff` in `readDOMChange` which fails to find a start).
If I e.g. mark all the text and paste with some text, it always fails -- the `findIndex` function will throw a `RangeError´ because the position is invalid.

If anybody has some pointers to what I may be doing wrong or what goes awry, I would be grateful -- otherwise I think I will keep working on my initial workaround (to mimic a simple Clipboard API. Perhaps only storing html and if copying from the editor fails, it's not a big deal for my use case).

**Comment by linus** [comment]
It's not always when pasting at the end of the line, and not only. It seems to work way better without attaching the debugger, so I'm guessing it's something timing related. When testing without debugging, it seems to work something like 80% of the time.

**Comment by marijnh** [comment]
I'm getting good results with patch ae9167f. I wasn't able to reproduce the behavior of getting an error though, so maybe your IE11 is behaving somewhat differently from the one I'm testing on.

**Comment by linus** [comment]
Great, thanks. It looks good. We will try this out. I think IE11 can behave differently depending on document mode, and perhaps other (security?) settings.

**Comment by marijnh** [comment]
So I guess this is mostly solved. Do open new issues if you run into additional problems.
