### ISSUE TITLE
link:unset not working when there's no selection

### ISSUE THREAD

**Issue by sawyerh** [ProseMirror/prosemirror#326]
According to the docs, calling `execCommand('link:unset')` should work when there's no selection but a `link` in the active marks.

> Removes all links for the selected content, or, **_if there is no selection, from the active marks_**. Will only select itself when there is a link in the selection or active marks.

This doesn't seem to work in Chrome 50 or Safari 9.1 and can be seen on the demo here: http://prosemirror.net/demo/basic.html

![unlink](https://cloud.githubusercontent.com/assets/371943/14988870/c99f0444-1123-11e6-9e29-dd3f986ff765.gif)

I've also confirmed this locally using ProseMirror 0.6.1 and calling `activeMarks()` does show a `LinkMark` is present.

**Comment by marijnh** [comment]
If you start typing after disabling the link style, you get non-linked text. If you move the cursor around, the set of active marks is reset.

**Comment by sawyerh** [comment]
Ah okay, I see. In that case, I wrote a bit of code to get the desired user experience. It could probably be refactored a bit, but it works...

![unset](https://cloud.githubusercontent.com/assets/371943/15058759/19231298-12ec-11e6-8040-3b570924c7d4.gif)

```js
pm_unsetLinkUnderCursor() {
  var selection = this.pm.selection;

  if(selection.anchor === selection.head){
    var newSelection = {
      anchor: selection.anchor,
      head: selection.head
    };

    Object.getOwnPropertyNames(newSelection).map((key) => {
      var pos = newSelection[key]
        , mark
        , lastMark;

      while(mark = this.pm_posHasMark(pos, "link")){
        // Handle case when two links are directly next to each other:
        if(lastMark && mark.attrs.href !== lastMark.attrs.href)
          break;

        lastMark = mark;
        newSelection[key] = pos;
        pos = key === 'anchor' ? (newSelection[key] - 1) : (newSelection[key] + 1);
      }

      if(key === 'anchor' && pos > 0)
        newSelection[key]--;
    });

    this.pm.setTextSelection(newSelection.anchor, newSelection.head);
  }

  this.pm.execCommand('link:unset');
}

pm_posHasMark(pos, markName) {
  var marks = this.pm.doc.marksAt(pos);
  return marks.reduce((found, m) => found || (m.type.name == markName && m), null);
}
```
