### ISSUE TITLE
Unexpected paste behavior when text is selected

### ISSUE THREAD

**Issue by sawyerh** [ProseMirror/prosemirror#327]
The paste behavior of ProseMirror is different than most text editors when you paste over a text selection. Tested in Chrome 50 on PM 0.6.1. Also tested on the [online demo](http://prosemirror.net/demo/basic.html). 

When you paste, you'd expect the selection to become unselected and the cursor placed at the end of the pasted text. Here's a quick example of what I mean:

![copy-paste-correct](https://cloud.githubusercontent.com/assets/371943/14989287/04a972da-1125-11e6-9fdd-3217caefddd5.gif)

ProseMirror on the other hand pastes the text but the selection remains selected:

![copy-paste-wrong](https://cloud.githubusercontent.com/assets/371943/14989356/61f785da-1125-11e6-8825-c40c5bfe9ba7.gif)

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch should help.
