### ISSUE TITLE
Starting a line with "1." or similar creates an ordered list unintentionally in Markdown

### ISSUE THREAD

**Issue by patternseek** [ProseMirror/prosemirror#329]
Hi,

When writing in the editor if you start a line with a number and a period or closing bracket the markdown generated creates an ordered list. This means it's not possible to have something along the lines of:

1\. Something
Something outside the list item.
2\. Something else

as it creates two ordered lists both starting with "1." once the content is reloaded from markdown.

AFAIUI the right way to save this content would be to escape period or closing brackets following numerals at the beginning of a new line in the generated markdown.

Thanks :)

**Comment by marijnh** [comment]
This is a limitation of markdown (where ordered lists can't indicate what number they should start with), not something ProseMirror can help.

**Comment by patternseek** [comment]
That's not really the issue I'm trying to raise just a side effect. My point is that entering text shouldn't create a styled element. In this case entering the text "1.", rather than clicking the ordered list button, creates a list element but really it should be serialised as "1\.". It's as if typing *Hello* in the editor generated bold text, which it doesn't because it gets escaped.

**Comment by marijnh** [comment]
If you don't want this behavior, don't enable the `autoInput` addon, or enable it with this specific rule disabled.

**Comment by patternseek** [comment]
Ah I see, sorry I didn't know it existed. :)

I've tried disabling it but I'm still seeing the same behaviour. My editor is initialised like this:

```
            this.editor =  new window.ProseMirror({
                place: this.$.editor,
                menuBar: {
                    float: true,
                },
                docFormat: "markdown",
                schema: mySchema,
                doc: "",
                autoInput: false
            });
```

Am I missing something obvious?

**Comment by marijnh** [comment]
Probably you failed to rebuild properly or something, because that code looks correct.

**Comment by patternseek** [comment]
Actually as far as I can tell I don't even have the autoInput code in my bundle. This is the editor bundle I'm using: http://slight.overtops.org/ttmp/editor-bundle.js

**Comment by marijnh** [comment]
That behavior is implemented in the autoInput addon, and if I disable that I don't get it. Not sure what's going on on your side, but I don't think ProseMirror is responsible.

**Comment by patternseek** [comment]
Note that this is only on serialise/deserialise to/from markdown, it's not something that happens immediately in the editor. 

I've uploaded (to my hosting, for some reason github is just timing out trying to attach the file here) a fairly minimal repro case. I've included the bundle and the source file it's built from (using ProseMirror 0.6.1) and an index file demoing the behaviour. The repro is here: 

http://slight.overtops.org/ttmp/lists%20repro.zip

If you type: 
```
1. Something
2. Something

```
then click the link below then you'll see the behaviour I'm talking about.

**Comment by marijnh** [comment]
Ahh, now I get what you are referring to. I assumed this was about the auto-list creation in the editor itself, but you're talking about not properly escaping markdown output. Attached patch should help.

**Comment by patternseek** [comment]
Great thanks, I'll give that a go tomorrow. Sorry, reading back I see that my initial description wasn't very clear.

**Comment by patternseek** [comment]
That's fixed it, thanks!
