### ISSUE TITLE
Problem with setContent()

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#33]
Setting the content with the ProseMirrorr constructor works fine:

    var editor = new ProseMirror({
      place: myElement,
      docFormat: myFormat,
      doc: myContent
    });

but this fails for me:

    var editor = new ProseMirror({
      place: myElement
    });
    editor.setContent({
      format: myFormat,
      value: myContent
    });

**Comment by tgecho** [comment]
The signature is actually [`setContent(value: Any, format?: string)`](http://prosemirror.net/doc/manual.html#edit), so you should pass the parameters directly rather than in an object. Try this instead:
```
var editor = new ProseMirror({
  place: myElement
});
editor.setContent(myContent, myFormat);
```

**Comment by rsaccon** [comment]
Ah, great, thanks!
