### ISSUE TITLE
Cannot move cursor past Figures

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#332]
I've got an image figure with `get contains() { return null }`. When this figure is at the bottom of my editor, I can use my cursors to get to it and have it highlighted but another down or right arrow only flashes the selection. I believe this is due to there not being another node after the figure and the figure cannot contain anything.

Figure at bottom of editor with cursor just above it:
![screen shot 2016-05-06 at 3 58 13 pm](https://cloud.githubusercontent.com/assets/1568246/15084727/70342f56-13a3-11e6-97ca-ff546e1da4c8.png)

Hitting Down Arrow:
![screen shot 2016-05-06 at 3 58 29 pm](https://cloud.githubusercontent.com/assets/1568246/15084728/70415e9c-13a3-11e6-9276-deb894886136.png)

Hitting **down arrow** again does nothing while hitting **right arrow** flashes the selection of the figure but then remains on it.

**Comment by marijnh** [comment]
Yes, there's no valid cursor position below the figure, so you can't move past it. That's intentional -- your text editor probably also doesn't create empty lines when you try to move past the last line. You should be able to press enter while  it's selected to create a paragraph after it.

**Comment by wes-r** [comment]
It doesn't create empty lines but it does allow me to get past the image and then enter/htiting letters would create the text.

Right now, I can get the figure highlighted but hitting enter replaces it :(

**Comment by marijnh** [comment]
What kind of node is your figure? (Block or inline?) Can you show the whole definition?

**Comment by wes-r** [comment]
Block.

It's also unclear to me what the "right" solution here is. I'm planning to go with hitting down creates a new line that the user can then delete if they don't want. Same thing for the case where the image is up at the top.

```javascript

export class ImageFigure extends Block {
  get attrs() { return {
      src: new Attribute,
      caption: new Attribute,
      align: new Attribute,
      wrapText: new Attribute,
      width: new Attribute,
      height: new Attribute,
      originalImageWidth: new Attribute,
    }
  }
  get draggable() { return true }
  get contains() { return null }
  get kind () { return NodeKindWikiBlock }
}

ImageFigure.register('parseDOM', 'figure', {
  parse: function (dom, state) {
    let $figure = $(dom)
    let $img = $figure.children('img')

    let src = $img.attr('src')
    let caption = $figure.children('figcaption').text()
    let wrapText = $figure.hasClass('wrap')
    let align = $figure.attr('class').replace(" wrap", "");
    let width = $figure.css("width")
    let height = $img.attr('height') || ""
    // Get it if it was set, otherwise should be ok to be blank
    let originalImageWidth = $figure.css('max-width').replace('px', '')

    if (!src) return false
    state.insert(this, {
      src, caption, align, wrapText, width, height, originalImageWidth
    })
  }
})

ImageFigure.prototype.serializeDOM = node => {
  let {src, caption, align, wrapText, width, height, originalImageWidth} = node.attrs
  if (!src) return

  let children = []
  let figureStyle = `width: ${width};`
  if (height) { // custom
    children.push(elt('img', {src, width, height}))
  } else {
    children.push(elt('img', {src}))
    // Non custom sizes should never exceed the origanl image width.
    // This makes the figcaption not expand beyond the figure and
    // prevents the figure from taking up more space than the image.
    // Note: Custom should not have this as the width is explicit in px.
    figureStyle += ` max-width: ${originalImageWidth}px;`
  }

  // Optionally add a figcaption
  if (caption) children.push(elt('figcaption', {}, caption))

  return elt('figure', {
    class: align + (wrapText ? " wrap" : ""),
    style: figureStyle,
    "data-type": "image",
  }, children)
}

ImageFigure.register("command", 'insert', {
  label: "Insert Image Figure",
  run(pm, src, caption, align, wrapText, width, height, originalImageWidth) {
    return pm.tr.replaceSelection(this.create({
      src, caption, align, wrapText, width, height, originalImageWidth
    })).apply()
  },
  params: [
    {name: "Image URL", type: "text"},
    {name: "Caption text", type: "text", default: ""},
    {name: "Alignment", type: "text", default: ""},
    {name: "Wrap text", type: "bool", default: false},
    {name: "Image Width", type: "text"},
    {name: "Image Height", type: "text"},
    {name: "Original Image Width", type: "text"},
  ],
  select(pm) {
    return pm.doc.path(pm.selection.from.path).type.canContainType(this)
  }
})
```

**Comment by wes-r** [comment]
Another thought just occurred to me, what if I made it an `inline` but then used CSS to treat it as a block. Maybe that would give me the right/better editing experience and still keep figures standing on their own.

**Comment by wes-r** [comment]
Ah, you are correct that with the figure highlighted, hitting enter does not replace it but instead inserts a new line.

I think this issue boils down to **Block Nodes** that `get contains() { null }`.

I've been able to duplicate my issue using **HorizontalRules** on the [demo page](http://prosemirror.net/demo/basic.html). There are two cases we should look at:

1. When the HorizontalRule is the very last node in the editor (at the bottom). In order to write text below it, you must have it highlighted and hit enter. This is counter intuitive as most word processors will replace highlighted content when you enter text (or hit enter). We can see this in action when we have the HorizontalRule highlighted and instead of hitting enter we hit a letter like "a" which will replace the highlighted HorizontalRule with the letter "a" as expected.

2. When the HorizontalRule is the very first node in the editor (at the top). Here the highlight and enter trick still works but is even more un-intuitive (I was shocked that this works!).

**Solutions**
A bad solution would be to auto create newlines in these edge cases. With a highlighted HorizontalRule at the top hitting up would insert a blank line above. Same thing for when it is at the bottom. This would at least provide the user an easy way to get above and below but magically creating newlines is less than ideal and it does not provide the user an easy way to delete the newline (how do you delete a top most new line that sits just above a HorizontalRule for instance).

A better solution would be to provide special cursor placements before and after the HorizontalRule. With a highlighted HorizontalRule at the very top, hitting up would give you a cursor just before the horizontalRule (at it's left edge). From there, hitting any text would create a new line and bump the HorizontalRule down. Same thing for at bottom but on the right side. This cursor would also aid in deleting the new line just above the HorizontalRule (backspace should delete the previous content).

**Comment by marijnh** [comment]
As you say, automatically creating newlines isn't a very good approach. Having a special type of selection means that every piece of code that deals with selections has to know about this exceptional type, which I think is too high a price to pay in terms of complexity.

'Intuitive' is a highly subjective term. I think pressing enter in an attempt to create space is something a user is likely to try. I am not aware of a good precedent here -- LibreOffice just completely screws this up (as usual), Google Docs just stops cursor motion when you are below a non-inline image at the top of the document (or above one at the end).

**Comment by wes-r** [comment]
I'm not familiar with another editor where having an image highlighted and hitting enter results in a new line. This is definitely not discoverable when the image is at the top (where hitting enter creates a new line above!).

Why can't leaf nodes have start and end tokens like non leaf nodes? I don't know the code, but my hope is that the complexity can be isolated to the leaf node. The special handling would be how to handle editing at the start & end tokens. Normally you'd be creating content within the node but instead, here, you'd create content around the node.

**Comment by marijnh** [comment]
How would having start and end tokens help at all here?

**Comment by wes-r** [comment]
Was assuming that meant they'd provide a cursor location.

**Comment by marijnh** [comment]
It'd only mean that there'd be a position _inside_ of the node, which would be meaningless (since nothing can actually be there), and add problematic boundary cases all of the place.

**Comment by marijnh** [comment]
Going to close this as there's no clear way forward. (Feel free to continue the discussion.)
