### ISSUE TITLE
Copy and paste issues from Google-Docs (And potentially other formats?)

### ISSUE THREAD

**Issue by bZichett** [ProseMirror/prosemirror#335]
On copying and pasting, whatever Google Docs is dumping into the clipboard seems to be breaking ProseMirror's bulleted list nodes in at least 2 ways.  I'm having trouble determining if if it's Google not following specification or if the issue is with ProseMirror.  Note that I haven't tested many other formats, so the following may to apply to others as well.

---

**Case 1:**

![Case 1](http://i.imgur.com/dhZ0KBq.png)

_Copying all three bullets..._

![Paste 1](http://i.imgur.com/x8eSejF.png)

The only issue is the parent bullet is being converted into a header

---

**Case 2:**

![Case 2](http://i.imgur.com/L9rfn4p.png)

_Copying all but the root bullet..._

![Paste 2](http://i.imgur.com/5dPhFTS.png)

A similar issue as Case 1 above occurs, in addition to the losing of content and wrecking of the bullet layout, which is much more critical.  

---

I'm using Google Chrome Version 50.0.2661.86 (64-bit) and the demo at https://prosemirror.net/demo/basic.html

If anyone has ever checked Google Docs method for rendering bulleted lists, they employ an interesting solution which seems to not even use HTML ul's.  They just indent li's an appropriate amount.  I assume this has something to do with occlusion culling and they're special solution to collaborative editing.  I would think that on exporting to the clipboard they convert it to a UL/LI browser specification, but I guess it's possible something is going wrong there and not with ProseMirror.

**Comment by marijnh** [comment]
Attached patch should make things somewhat better. A full solution would require #342 , for which I'll make time later.
