### ISSUE TITLE
Integration into another project should be simpler

### ISSUE THREAD

**Issue by friksa** [ProseMirror/prosemirror#337]
If I use npm --save install prosemirror, I should be able to include js and css files and be able to use the documentation to integrate prosemirror into my project.

Currently, this project is focused on development only and requires a dedicated web server to do package magic when loading the js modules.  That does not allow me to use it on my own server or simply develop inside web storm by selecting an html file and selecting debug in browser.  This is how many javascript developers go about integrating other components.

Thanks!
Frik

**Comment by marijnh** [comment]
The way to integrate this, as is explained in the [documentation](http://prosemirror.net/guide/basics.html), is to install it from NPM and use a bundler. Since the editor consists of multiple modules, and you won't need all of them, distributing as a single .js file is not really helpful, so I'm not planning to do that in the near future.

**Comment by friksa** [comment]
I am saying that using a bundler is not simple enough.  This is not how most successful project do it.  As a kickstarter backer I thought my input would be worth more.

**Comment by andreypopp** [comment]
Using a bundler is just:
```
browserify input.js -o output.js
```
This is the example with [browserify](http://browserify.org).

Also using a bundler is a standard way to consume third-party JS code found in npm (the most used package manager for JS code).

**Comment by marijnh** [comment]
First, I'm not sure how you expected me to know you're a backer. Are you with gatherworks?

Second, I explained the reasoning behind our distribution style. If you have concrete suggestions on improving things, I'm interested, but including three versions of the code in our distribution (ES6, CommonJS modules, and a giant bundle file) seems a bit much. As @andreypopp noted, bundling really isn't hard, and most projects are doing it anyway.

**Comment by friksa** [comment]
I have done a lot of development before and used a lot of projects.  I have never had to use browserify myself.  It is always part of the build scripts and I simply include js and css files.

Given that it is so simple, it should be in the build script so that stupid developers like me can just include js and css and be up and running.  Every hurdle reduces the probability of success.  In my experience, you want someone to get up and running as fast as possible and only learn your documentation instead of other stuff such as bundlers.

I am not proposing including extra js,css files.  I am proposing a build script change to generate them.

I am just trying to help.  Every hour that a developer like me has to spend trying to learn browserify is an hour less spent on learning prosemirror.

**Comment by friksa** [comment]
Even though GatherWorks crowd-funded this project, we have been wasting hours to get it to integrate into our existing ExtJs project... no luck.  We will probably use the Medium editor project since we got that working immediately.  That is unfortunate.

**Comment by andreypopp** [comment]
@friksa 

```
% npm install prosemirror browserify 
% cat <<EOF > index.js                                                                                                                                             
window.ProseMirror = require('prosemirror');
// require more ProseMirror modules here if needed for your app
EOF
% ./node_modules/.bin/browserify ./index.js > prosemirror.js
```
Then you can include `prosemirror.js` in your HTML page and use `window.ProseMirror`

**Comment by friksa** [comment]
Thanks so much @andreypopp - that should do it!

**Comment by AlexeiAndreev** [comment]
FWIW I've been getting up to speed on React, Redux, and a lot of other libraries and this is the first one where I had to manually run a bundler.
