### ISSUE TITLE
Uncaught error when using heading input rule ("# ") at the start of a non empty line

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#338]
I tested this using the latest master and it seems to be a regression:

1. Write something in a paragraph
2. Go to the beginning of the line and type `#` followed by a space
3. `Uncaught Error: Parent at depth 1 not fully covered`

The expected result would be to turn the paragraph into a heading. Using other input rules like `* ` or `1. ` works fine.

**Comment by marijnh** [comment]
Attached patch should help.
