### ISSUE TITLE
Using the collab module over a custom server connection

### ISSUE THREAD

**Issue by friksa** [ProseMirror/prosemirror#339]
http://prosemirror.net/guide/collab.html
When using the collab module, there is an issue when parsing the json received over the network.  It gives you a raw javascript object that is not of type Step.  When you call collab.receive(steps, clientIDs), you get an error: Uncaught TypeError: step.apply is not a function

You can recreate the issue with this code:
````
function send() {
  var o = collab.sendableSteps();

  var steps=JSON.parse(JSON.stringify(o.steps));
  collab.receive(steps, [1234]); //fake clientID to force processing
}
````

This is a proposed solution on StackOverflow:
http://stackoverflow.com/questions/5873624/parse-json-string-into-a-particular-object-prototype-in-javascript

Thanks!
Frik

**Comment by kiejo** [comment]
Step instances have a `toJSON` method and there is a `Step.fromJSON` method which you should use in this case. The following code should fix your problem:
```javascript
var sendable = collab.sendableSteps();

var steps = sendable.steps.map(s => s.toJSON())
collab.receive(steps.map(s => Step.fromJSON(schema, s)), [1234]);
```

As you can see you also need to provide a schema in the `fromJSON` method.

**Comment by marijnh** [comment]
Indeed, JSON can't encode class instances, which is why JSON-serializeable classes in ProseMirror have `toJSON` and static `fromJSON` methods.

**Comment by friksa** [comment]
Thanks!  I was able to get it working.  I am listing my solution for EcmaScript 5 for those that are still using plain Javascript.

My browserify module looks as follows:
````
ProseMirror = require("../dist/edit").ProseMirror;
require('../dist/menu/menubar');
require('../dist/collab');
ProseMirrorStep = require('../dist/transform/step').Step;
ProseMirrorSchema = require('../dist/model/defaultschema').defaultSchema;
````

The "test" send function works as follows for me:
````
function send() {
  var o = collab.sendableSteps();

  var steps=[];
  for (var i=0; i<o.steps.length; i++) {
    var s=JSON.stringify(o.steps[i].toJSON());
    var ss=JSON.parse(s);
    steps.push(ProseMirrorStep.fromJSON(ProseMirrorSchema, ss));
  }
  collab.receive(steps, [1234]); //fake clientID to force processing
}
````
