### ISSUE TITLE
RangeError during a paste event leaves ProseMirror in an unrecoverable inconsistent state

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#341]
I discovered this problem through Issue #340. Following the steps described in the issue, pasting content results in an `Uncaught RangeError: Can't create default content for heading` error. In case of such an error I would normally have expected no content to be inserted into the editor. What happens instead, is that the originally copied HTML gets inserted into the DOM, which leaves ProseMirror in an unrecoverable inconsistent state.
This is what the DOM looks like after pasting the content into an empty ProseMirror editor:
![pm_dom](https://cloud.githubusercontent.com/assets/152507/15175242/ad48f762-1765-11e6-9be1-639b822a4580.png)

Trying to further edit the content logically leads to many errors and unexpected behavior. I would suggest ignoring all pasted content, which could not be turned into a ProseMirror node, ensuring a consistent editor state.

**Comment by marijnh** [comment]
Can you provide the HTML that ended up being pasted into the editor? (By, for example, `console.log`-ing the value of `html` in `fromClipboard` in src/edit/input.js)

**Comment by marijnh** [comment]
Ah, you've already reported the original bug as #340. The editor breaking when it's broken is kind of hard to get around, so I'm just going to continue fixing actual bugs, rather than trying to come up with strategies to be invulnerable to bugs.

**Comment by kiejo** [comment]
I'm not sure how hard it would be to implement error handling in this case, but I thought it would be feasible to handle this error in a sane way as it is thrown by ProseMirror. I thought that the reason the original HTML gets inserted, is because the default browser behavior isn't blocked as a result of the thrown error. Wouldn't it be possible to always prevent the default browser paste behavior regardless of success/failure?

The problem with this kind of bug is that it doesn't give the user any feedback on the fact that something went wrong and they can continue editing the document. This can lead to data loss from a user's perspective as the content that is displayed in the editor never makes it to the server and is gone with the next page refresh.
Preventing the possibility of this happening at all would be really helpful.

**Comment by marijnh** [comment]
If I insert a `throw "oops"` statement into `fromClipboard`, what happens is that the paste handler crashes, the paste goes through, and the resulting `input` handler then reads the DOM and resynchronizes the document. Possibly in your case the editor because unresponsive because the `input` handler would try to parse the DOM and crash _again_, for the same reason the original crash happened.

**Comment by kiejo** [comment]
Thanks for clearing that up. I just had a look at the `handlers.paste` function in `input.js` and moved the `e.preventDefault` call before the `fromClipboard` call, which successfully prevents a pasted DOM structure from ending up in the editor in the case of an uncaught error in `fromClipboard`:
```javascript
handlers.paste = (pm, e) => {
  if (!hasFocus(pm)) return
  if (!e.clipboardData) return
  e.preventDefault()
  let sel = pm.selection
  let slice = fromClipboard(pm, e.clipboardData, pm.input.shiftKey)
  if (slice) {
    let tr = pm.tr.replace(sel.from, sel.to, slice)
    tr.apply({scrollIntoView: true, selection: findSelectionNear(tr.doc, tr.map(sel.to))})
  }
}
```

Is there a reason we would not want to prevent the default paste behavior once we decide that we want to handle the paste event ourselves (regardless of error or success)? I think that integrating this change would help increase the editor stability/reliability: In case of an uncaught error, the editor state would not get corrupted and the user would know that something went wrong as nothing got inserted into the editor. The console would still show the uncaught error just like before which is important for debugging.

I would be happy to create a pull request for this if there aren't any other use cases which would require the default paste to go through.

**Comment by marijnh** [comment]
`fromClipboard` can return `null` (couldn't read data through clipboard API), in which case it seems prudent to let the default behavior happen and try to work with that. How does the editor state get corrupted in the case of an error in `fromClipboard`? Nothing has been mutated yet at that point, so the handler should just be aborted without side effects.

**Comment by kiejo** [comment]
Ah ok, having the `input` handler as a fallback makes sense. I didn't get that when I read your other comment. I'm not sure how the DOM syncing works, but after debugging this a little more, I can say that no error is thrown inside the `input` handler.

The best way to reproduce this issue now is the following:
1. Return `null` in `fromClipboard`
2. Paste the content from the same [Google Doc](https://docs.google.com/document/d/1ddW_VRaOyzsM5MZUeVgq416byoq9I614Oqdvxy9nuuw) which caused #340 
3. The pasted DOM structure ends up being rendered as the ProseMirror content which leaves the editor in an incosistent state

I now tested this with the latest version from master and used the default schema. None of these steps throw any errors.

**Comment by marijnh** [comment]
That was another bug. See attached patch. Still nothing to do with preventDefault (I mean, can suppress it by preventDefaulting events, but then, we could suppress most problems in the editor by ignoring input, just that it wouldn't be an editor anymore)

**Comment by kiejo** [comment]
Great! I definitely agree that `preventDefault` didn't fix anything in this case, but only realized that after understanding that the `input` handler gets called after a failed `fromClipboard`.
Thanks for the fast fix :)
