### ISSUE TITLE
Parse pasted content without context

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#342]
Currently `fromDOM` wraps the parsed content in a full document. For the default schema, this is mostly fine, but if you have one that, for example, requires section nodes around all text, you'll get bad results when pasting simple text content.

Add an option to `fromDOM` that makes it parse content without wrapping it in a parent node.

**Comment by johanneswilm** [comment]
Are there any work arounds that we can use for now?

Trying to turn the content declaration from:

```
doc: {type: Doc, content: "title subtitle authors abstract keywords body"}
```

to

```
doc: {type: Doc, content: "block* title? subtitle? authors? abstract? keywords? body?"}
```

to allow for the paste filter to create a simple Doc(Paragraph(...)) to handle its paste content doesn't seem to have the desired effect.

**Comment by marijnh** [comment]
Attached patch should improve the situation quite a bit (though I haven't tested it heavily yet). Please take a look.

**Comment by johanneswilm** [comment]
Yes, pasting works now. thanks!

**Comment by johanneswilm** [comment]
@marijnh Looking at this again, there are situations when it doesn't work, when just the first block element is pasted. The following is not the best formatted HTML, but it's nevertheless fairly common on the web and currently only the first element (the title) shows up in the document after paste (and the first element always loses its blocktype, so the title becomes part of the last regular paragraph). This shows when trying to paste from arbitrary web pages or from MsWord.

```
<!doctype html>
<html>
<body>
<h1>Title</h1>
This is the first paragraph
<p>second par</p>
</body>
</html>

**Comment by johanneswilm** [comment]
The bug seems to show up whenever inline and block nodes are siblings. A work around for now is to walk through the paste content and put block elements around inline nodes that have block element siblings.

**Comment by marijnh** [comment]
Yeah, note the patch message and the fact that I left this open. I'm still working on a more solid approach, but wanted to have a stopgap fix when releasing 0.7.0.

**Comment by johanneswilm** [comment]
Sure. I just wanted to give some feedback as to where it currently fails.

**Comment by marijnh** [comment]
The new approach is now on the master branch and will be part of 0.8.0, It should cover the issues you raised here.
