### ISSUE TITLE
API entry file to all useful modules

### ISSUE THREAD

**Issue by theefer** [ProseMirror/prosemirror#343]
Currently, there doesn't seem to be an entry file that exposes all the APIs one might need when working with a ProseMirror instance. The closest thing seems to be `src/edit/index.js`, but that doesn't expose any of the models, which make it impossible to provide a custom `Schema` or instantiate a `Doc` out of `Nodes` to pass into PM as initial `doc`.

Would it make sense to add a `src/index.js` file that would export all the useful public APIs?

That would be particularly useful to generate a single ES5 bundle (eg CJS or UMD) that can be imported in contexts where ES6 modules are not supported. I've been creating such a bundle with a simple browserify+babelify command.

I'm happy to contribute such a file if you think this is a valid idea. Otherwise, can you advise on an alternative solution?

**Comment by marijnh** [comment]
Andrey showed an easy way to create such a bundle in [another issue](https://github.com/ProseMirror/prosemirror/issues/337#issuecomment-218185616). The idea of the split into modules is that you might not always need all of them (this goes especially for the addons), and thus I feel it'd be a bit crude to distribute a huge file with all code in the project. I might eventually revisit this, but for now, users will just have to do their own bundling.
