### ISSUE TITLE
Android Firefox and Standard Browser: Selections not working

### ISSUE THREAD

**Issue by Knorrke** [ProseMirror/prosemirror#348]
Selecting text and adding marks doesn't work on Android 4.2 using Firefox (46.0.1) or Android Standard Browser. ProseMirror doesn't seem to recognize that text is being selected. It doesn't open the tooltipmenu either.

Works fine on Chrome, though.

**Comment by marijnh** [comment]
For now, Chrome is the only browser I'm supporting on Android. Both Firefox and the standard browser are a complete mess when it comes to firing input-related events.

**Comment by marijnh** [comment]
Things seem to be much better now on Firefox. The standard browser is deprecated and I am not intending to support it or test on it.
