### ISSUE TITLE
The key property of a mark's name in JSON representation is an underscore

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#350]
The JSON representation of a mark looks like 

```json
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "marks": [
            {
              "_": "em"
            },
            {
              "_": "strong"
            }
          ],
          "text": "Hi"
        }
      ]
    }
  ]
}
```

So the name property is represented as `_`, and [previously](https://github.com/ProseMirror/prosemirror/commit/43e50235dc1265031235233cfb9e48c7deb1d1bf) was `_name`. Why not name this property `type` or `name`?

**Comment by ericandrewlewis** [comment]
Related: #129

**Comment by marijnh** [comment]
Because, as I explained in #129, the property namespace is shared with the marks attributes, and someone is likely to define an attribute called `name` at some point.
