### ISSUE TITLE
defineOption not exported in 0.7

### ISSUE THREAD

**Issue by pboysen** [ProseMirror/prosemirror#361]
I upgraded to 0.7 and the following no longer works:
import {defineOption} from "prosemirror/dist/edit"
defineOption("commandParamPrompt", WidgetParamPrompt)

It is not edit/index.js nor is an exportable function in options.js

**Comment by marijnh** [comment]
You've checked out the current master branch. Get the code from github or check out the 0.7.0 tag and you'll get the 0.7.0 API.
