### ISSUE TITLE
Support for Google Realtime API

### ISSUE THREAD

**Issue by friksa** [ProseMirror/prosemirror#366]
It will be nice to have the collaborative feature be compatible with Google's Realtime API:
https://developers.google.com/google-apps/realtime/overview#what_does_the_realtime_api_do_for_me

**Comment by marijnh** [comment]
If you have a concrete proposal on what would be needed to have this and what it would bring, feel free to write it up. However, single-sentence issues that suggest we adjust to some random 3rd party system aren't something I'm going to put time into.
