### ISSUE TITLE
The WYSIWYG mode may refer this

### ISSUE THREAD

**Issue by jackycute** [ProseMirror/prosemirror#37]
Wow, this project is very cool!
I like it very much!

But the WYSIWYG mode won't able to convert back to markdown.
And I saw something familiar on the net.
http://typora.io/
Maybe can give you some ideas.

Support you and Thank you!

**Comment by marijnh** [comment]
Nice.

**Comment by iliaznk** [comment]
[This](https://github.com/bevacqua/woofmark) one also converts things to and from Markdown. But the author seems to have stopped developing it.
