### ISSUE TITLE
Allow "Enter" to be the trigger of an input rule

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#374]
I have the use case that I would like to trigger an input rule when the user presses `Enter` after a matched regex.

My concrete use case is to automatically recognize links when typed in. I want them to be either recognized when pressing `Space` (which is already working) or when pressing `Enter`. I think this is currently not possible or at least I don't know how to achieve this.
This is currently not a high priority, but would be nice if it doesn't involve too much work.

**Comment by marijnh** [comment]
URLs are tricky, since they don't have a clear end. You could of course add an `Enter` key binding to handle this, but you'd still have the same issue when the user moves the cursor away from the link in some other way.

**Comment by kiejo** [comment]
I don't know how we could handle other cursor movements, but handling the specific use case of pressing `Space` or `Enter` directly behind a URL would be good enough in our case.

I hadn't thought of a custom key binding in this case as the logic is so closely related to our `InputRule` and I thought this could be a common use case for `InputRules`. But solving this using a custom key binding isn't much of an issue either.

**Comment by marijnh** [comment]
This fits poorly with the conceptual framing of input rules (they match a given text _string_, and enter doesn't really add anything to a textblock's textual representation).

(You could write an input rule that turns everything that's a valid URL into a link, even before space is pressed, but that might be annoying when the user doesn't want it to happen.)
