### ISSUE TITLE
Support a way for nodes to control their own display updates

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#378]
So that if you render a MathML or code editor inside your document, changes to it won't necessarily lead to a full reinitialization of the editor.

When a node is being updated, in `redraw` in `edit/draw.js`, it could first check for a `redraw` method on the node type, and if that's present, call that, passing it the DOM node, the old node, and the updated node. This method could then, for example, call `setValue` on an empbedded CodeMirror.

Note that this doesn't completely solve the problem of ever needing to redraw such nodes. DOM changes  from composition or input events on their boundaries would still lead to a situation where we aren't sure whether their DOM still makes sense, and would, in the current approach, require a full redraw of the node.

**Comment by ericandrewlewis** [comment]
This solution works great for rendering a React component, which would want the DOM node.

**Comment by marijnh** [comment]
If you're tracking this, you're probably interested in [this RFC](https://discuss.prosemirror.net/t/rfc-node-views-to-manage-the-representation-of-nodes/463)

**Comment by marijnh** [comment]
This is implemented as [node views](http://prosemirror.net/ref.html#view.NodeView) in 0.14.0
