### ISSUE TITLE
addActiveMark() loses previously set marks

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#379]
The new `addActiveMark()` code untoggles previously selected marks. Tested with **Version 0.8**.

Steps to reproduce:
* Click Bold
* Type "should be bold"
* Click Italics
* Type "should be bold and italic"

Expected:
**should be bold** _**should be bold and italic**_

Actual:
**should be bold** _should be bold and italic_

**Comment by marijnh** [comment]
Indeed, and there was a similar bug in `removeActiveMark`. Attached patch should fix it, and I've brought out a 0.8.1 with the fix.
