### ISSUE TITLE
npm run demo fails

### ISSUE THREAD

**Issue by kgaree** [ProseMirror/prosemirror#38]
> prosemirror@0.0.1 demo /var/www/html/author/components/prosemirror
> watchify -d --outfile demo/demo-built.js -t babelify demo/demo.js

sh: 1: watchify: not found

npm ERR! prosemirror@0.0.1 demo: `watchify -d --outfile demo/demo-built.js -t babelify demo/demo.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the prosemirror@0.0.1 demo script.
npm ERR! This is most likely a problem with the prosemirror package,
npm ERR! not with npm itself.

**Comment by kgaree** [comment]
*sudo* npm install

**Comment by mightyiam** [comment]
One should not have to `sudo npm install` for development.

**Comment by marijnh** [comment]
Nope, it works just fine without sudo (I don't have watchify installed globally myself)

**Comment by kgaree** [comment]
I had to run sudo to resolve

**Comment by ptgolden** [comment]
It's likely you had to use sudo because you did not have sufficient privileges to make changes in your working directory (`/var/www/html/author/components/prosemirror`).
