### ISSUE TITLE
Simplify InputRule constructor API

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#380]
```javascript
new InputRule(match: RegExp, filter: ?string, handler: union<string, fn(pm: ProseMirror, match: [string], pos: number)>)
```

I would like to propose simplifying this API to remove the convenience `string` option to `handler:`. Given ES6 this is really concise via `() => "mystring"` and we can remove the complexity from the API and implementation.

**Oops:** Actually upon jumping into [the code](https://github.com/ProseMirror/prosemirror/blob/master/src/inputrules/inputrules.js#L84-L89) I see the implementation for a string parameter is more sophisticated than I assumed:

```javascript
let start = $pos.pos - (match[1] || match[0]).length
let marks = this.pm.doc.marksAt($pos.pos)
this.pm.tr.delete(start, $pos.pos)
          .insert(start, this.pm.schema.text(rule.handler, marks))
          .apply()
```

Despite this I think I'd still like to see the API simplified, and perhaps instead a utility function could be provided that generates string replacements, e.g.

```javascript
const { replaceWith } = require('inputrules/utils');
new InputRule(/^h1.$/, '.', replaceWith("# "));
```

In my example I don't want `inputrules/utils` to imply it necessarily comes from ProseMirror, it could just as easily be provided by an external.

My motivation is about trying to decompose and simplify ProseMirror APIs (to make it more stable) and promote plug-ability.

**Comment by marijnh** [comment]
I think having the option to pass a function here makes this interface plenty flexible. Needing to import and call (and know about) a helper function to implement the most obvious, trivial type of input rule doesn't seem like a win, so I'm going to say no to this.
