### ISSUE TITLE
Markdown classes are not exported properly

### ISSUE THREAD

**Issue by thomasWajs** [ProseMirror/prosemirror#382]
In the new release 0.8, the classes

- `MarkdownSerializer` and `MarkdownSerializerState` from markdown/to_markdown.js
- `MarkdownParser` from markdown/from_markdown.js

Are not set in the exports object. They appears as undefined when imported.

The `defaultMarkdownSerializer `and `defaultMarkdownParser `objects are correctly exported however.

**Comment by marijnh** [comment]
Attached patch solves this. I've brought out 0.8.1 with this fix.
