### ISSUE TITLE
TransformPasted doesn't preserve line breaks when pasting text from <textarea>'s

### ISSUE THREAD

**Issue by bZichett** [ProseMirror/prosemirror#383]
Reproduce by finding a textarea which has line breaks such as the following text and paste into ProseMirror. 

Test 1
Test 2
Test 3
Test 4

Note: It **won't** work copying from this post since its rendering as HTML.   You can simply copy the text of your reply here are GitHub when it's in textarea form though.

ProseMirror renders: "Test 1 Test 2 Test 3 Test 4"

This type of format is frequently seen in textarea's.  

My brother ran into this issue when copying text from Google Tasks into ProseMirror, and was bothered by the fact he had to separate each line.

I tried my best to probe the slice from transformPasted{...} listeners for any character I could convert into a line break but it seems there are no \n, &#10; or &#13; to be found in either transformPasted or transformPastedText, only trailing spaces.

**Comment by marijnh** [comment]
What kind of document structure were you expecting to get?

**Comment by bZichett** [comment]
One that preserves the breaks when pasting from a textarea.

These two images should much better convince you of the issue!

![Text area](http://i.imgur.com/4P38ij0.png)


![ProseMirror](http://i.imgur.com/YEmTbKZ.png)

**Comment by marijnh** [comment]
Yes, but what does preserving line breaks mean? As hard_break nodes? As paragraph boundaries?

**Comment by bZichett** [comment]
@marijnh Well, it is indeterminate, since the text is coming from textarea field, where there is no distinction between hard breaks and paragraphs.  But the current behavior would be much improved if either hard breaks or new paragraphs are used.  

If I had to voice an opinion for a solution: when I'm typing in a textarea, I usually press enter twice to start a new paragraph and once for a line break.

**Comment by marijnh** [comment]
Attached patch fixes a bug where not even the existing mechanism that separated paragraphs on blank lines was working, and also inserts hard breaks on single newlines. That should work for any schema that knows how to parse `<p>` and `<br>` tags.

**Comment by bZichett** [comment]
Excellent =)  

Thank you!
