### ISSUE TITLE
List icons can fail to be disabled (w.r.t schema)

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#384]
Version 0.8.1: List items don't properly return false in their `select()` call.

* In **schema-basic/index.js** make blockquotes only take paragraphs: `blockquote: {type: BlockQuote, content: "paragraph+", group: "block"},`.
* Run demo
* Create a blockquote
* Notice list icons are still available
* Clicking a list icon will result in a js error (`/../src/transform/structure:93 Uncaught TypeError: Cannot read property 'length' of null`)

**Comment by marijnh** [comment]
Yeah, that was still some pretty fragile code. Attached patch should help.
