### ISSUE TITLE
schema-basic Doc doesn't have toDOM

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#385]
This means that calling pm.doc.toDOM() fails with "Failed to override NodeType.toDOM."

Fix is to make your own top-level Doc:
``` js
import { Doc } from 'prosemirror/dist/schema-basic'

class EdDoc extends Doc {
  toDOM () { return ['div', 0] }
}
```

Should schema-basic Doc toDOM be defined out of the box?

**Comment by marijnh** [comment]
Yes, you want `doc.content.toDOM()`, since serializing the top level document _as a node_ isn't something that's defined. The [docs](http://prosemirror.net/ref.html#Node.toDOM) talk about this.

**Comment by forresto** [comment]
I see... node vs fragment.
