### ISSUE TITLE
Issue with hard_break when using unwrapped text nodes

### ISSUE THREAD

**Issue by theefer** [ProseMirror/prosemirror#394]
Given the following Schema:

``` js
const schema = new Schema({
  nodes: {
    doc: {type: Doc, content: "inline<_>*"},
    text: {type: Text, group: "inline"},
    hard_break: {type: HardBreak, group: "inline"}
  },

  marks: {
    strong: StrongMark,
  }
})
```

It's now possible to edit the content (since https://github.com/ProseMirror/prosemirror/commit/0c7aff3753257ea3bbb544cd0d6a4856b4488c80) but pressing Enter to create a hard_break gives the following error: 

```
Uncaught TypeError: Cannot read property 'defaultContentType' of undefined
commands.splitBlock @ commands.js:357
(anonymous function) @ commands.js:56
handle @ input.js:101
dispatchKey @ input.js:106
handlers.keydown @ input.js:174
(anonymous function) @ input.js:65
```

Note: this is a followup issue to https://github.com/ProseMirror/prosemirror/issues/344#issuecomment-223942488

**Comment by marijnh** [comment]
Right, that was another bad assumption in the code. Attached patch should fix it.
