### ISSUE TITLE
Read only option

### ISSUE THREAD

**Issue by SamyPesse** [ProseMirror/prosemirror#396]
Prosemirror doesn't look like to have a `readOnly` option to disable editing. It could be useful to prevent modification while still displaying the editor.

This option could be implementing by toggling the `contenteditable` attribute.

**Comment by marijnh** [comment]
If you simply toggle `contentEditable`, ProseMirror's key handlers will still be updating your document for a lot of keys. See [this discussion](https://discuss.prosemirror.net/t/what-does-a-read-only-editor-even-mean/221) and [this event handler](http://prosemirror.net/ref.html#ProseMirror.on.filterTransform)

**Comment by tamlyn** [comment]
Note to future web travellers passing by this place: the [editable](http://prosemirror.net/docs/ref/#view.EditorProps.editable) prop might be what you're looking for.

**Comment by A1vinSmith** [comment]
```
    const disabled = this.disabled;
    this.view = new EditorView(el, {
      state: this.state,
      dispatchTransaction: this.dispatch,
      nodeViews: this.nodeViews,
      attributes,
      editable() {
        return !disabled;
      },
    });
```

**Comment by porkopek** [comment]
If you make `editable:false`, the contenteditable attribute is set to false, not allowing you to select text with the keyboard. If you want to allow selecting text with the cursors you must create a plugin like 

```js
     new Plugin({
        key: new PluginKey('readonly'),
        filterTransaction: transaction => {
          // Allow selections but prevent any other changes
          return transaction.docChanged === false;
        },
      }),
      
  ```
