### ISSUE TITLE
Plugin integration API and LifeCycle

### ISSUE THREAD

**Issue by mitermayer** [ProseMirror/prosemirror#398]
Would be great to have a bit more resources on plugin development. Upon reading the documentation and a bit of the source code I still had some doubts on the Plugin Integration API and how we are supposed to develop them. 

* Are we supposed to extend the `Plugin` class from  `src/edit/plugin.js' 
* How does the plugin lifecyle currently works (when does detach happen?, when we create plugins via attach? when to use configure?) 
* On `Plugin` class there is a `config` method that returns a `new Plugin`, I assume that is to create a plugin that have some options

I was hoping to have a bit more documentation around Plugin Integration, a demo with different options of sample plugins would be great as well. The goal should be make it easy to understand:

* How can we develop plugins for prosemirror
* How can we wire them to prosemirror

**Comment by marijnh** [comment]
We'll write [a guide about that](https://github.com/ProseMirror/website/issues/28) at some point. For now, I hope it helps to know that a `Plugin` instance is just an interface for attaching your custom state class to and editor, and allowing users to pass in options. There's no automatic 'lifecycle' happening -- plugins passed to the `plugins` option are attached when the editor intializes. You can manually detach them again or attach others at any point. The class you associate with your plugin value should not inherit from `Plugin`. See also [the API docs](http://prosemirror.net/ref.html#Plugin)
