### ISSUE TITLE
replaceSelection & inheritMarks uses marks at "from" but not within replacement

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#399]
Steps:
* Type: "hello **world**"
* Select the word "**world**"
* Run `pm.tr.typeText("new world").apply()` (which calls `replaceSelection()` with `inheritMarks` set to `true`).

Expected: "hello **new world**"
Actual "hello new world"

Thoughts on how to best handle this? Seems like we'd always want the marks to the right of `selection.from` and not on `selection.from` itself.

**Comment by marijnh** [comment]
I am not convinced the behavior you described is obviously preferable to the current behavior. Having a simple mechanism (marks before cursor) might be preferable to a more complicated heuristic that the user will have a harder time predicting.

**Comment by wes-r** [comment]
Hmmm... I agree a complicated mechanism is less than ideal. Unfortunately most marks are not inclusiveLeft and links are not inclusiveRight. I think what would be useful is to get the marks WITHIN the selection. Some heuristic like "grab all marks within selection" would work.

For now I'm going to go with `from + 1` as my position to check.

**Comment by marijnh** [comment]
What if the selection is a long piece of text with various marks applied to pieces of it?

**Comment by wes-r** [comment]
It's unclear to me what the best answer there is. What would a user expect? The union? The intersection?

I don't currently have a use case that hits this yet. My current use case is in spell correction. User types "Hello **woorld**" and selects "woorld" and chooses the replacement of "world". They'd expect to get "hello **world**" and not "hello world". Same issue when spell correcting links.

**Comment by marijnh** [comment]
Spell correction doesn't go through ProseMirror's mark-assignment logic (the new text is read from the DOM), so there this wouldn't have any effect either way.

**Comment by wes-r** [comment]
I'm implementing my own custom Spell Checker since the browser one doesn't play nicely with ProseMirror (especially in Safari).

**Comment by marijnh** [comment]
Then you're generating the replace yourself, and it is not the same as simply typing. You could write your own logic to decide what kind of marks to apply to the replacement.

**Comment by wes-r** [comment]
True, I went with `pm.tr.typeText` for simplicity but I could go with `pm.tr.replaceWith`.

The "bug" is still present however in the case of highlighting **world** and typing in a replacement as the `insertText()` function also uses the left side for marks.

**Comment by wes-r** [comment]
Just tested within google docs and os x pages. They both seem to use the first character to determine marks. If you highlight a single word with multiple marks and type you will only get the marks of the first character.

**Comment by marijnh** [comment]
Implemented in attached commits.
