### ISSUE TITLE
Editing existing link

### ISSUE THREAD

**Issue by q42jaap** [ProseMirror/prosemirror#40]
In the demo's, you cannot edit the url, only toggle it off and then re-add the url. For a user this is not very friendly.

**Comment by blambeau** [comment]
+1 it would be great to reopen the Tooltip form when clicking the link

**Comment by marijnh** [comment]
This is a UI issue that I'm going to leave up to the ecosystem (menu primitives will be moved out of the core lib in the near future, and defining your own controls to modify a link should be straightforward).
