### ISSUE TITLE
Copying a single image from a web page and pasting it into the editor does not work

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#401]
I tested this using Chrome and Firefox:
1. Go to http://prosemirror.net
2. Right click on the logo and choose "Copy image"
3. Focus a paragraph inside the editor and press `Ctrl+V`
4. Nothing happens and no errors are thrown

In this case I would expect the image to be pasted into the editor.
The HTML that ends up in the clipboard looks like this:
```HTML
<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="http://prosemirror.net/img/logo.png"/>
```

Copying and pasting images as part of a larger selection from a web page does work.

**Comment by marijnh** [comment]
That was a bug in the way the DOM parser handled leaf nodes. Attached patch should help.
