### ISSUE TITLE
Handling a paste event which contains the type "Files"

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#402]
I'm currently looking for a way to handle a paste event which only contains the type `Files`. The following `DataTransfer` object is created when for example copying an image from the Snipping Tool in Windows or when selecting and copying a single image from Word:
![datatransfer](https://cloud.githubusercontent.com/assets/152507/16655617/6eddb49a-445b-11e6-85ac-9b33635249f2.png)

The same `Files` type is also available when copying and pasting an image in Chrome using "Copy image" only that an additional type `text/html` is available, too.

It would be very helpful to have the possibility to hook into such a paste event similar to what is possible with the `transformPastedText` and `transformPastedHTML` events.
I would suggest adding a `transformPastedFile` subscription which would take a `Blob` as its argument (obtained from `dataTransfer.items[0].getAsFile()`).
In that context it would be important to have the option of choosing which subscription to fire, based on the available types from the paste event. For example being able to choose to either use the `text/html` or the `Files` type if both are available.
I originally tested this using Chrome and just noticed that the `Files` type is not available in Firefox. I'm not sure about other browsers, but nevertheless, this would still be very useful in Chrome.

**Comment by mitermayer** [comment]
I am also facing the same problem right now

**Comment by marijnh** [comment]
We could extend the code that handles paste and drop to also look for files, and when it sees them, try to insert them as document content. I think we can use `File.type` to recognize HTML content, and for other files, maybe simply see if they are non-binary (I use `/[\x00-\x08\x0e-\x1f]{2}/` to guess binary file content in CodeMirror, which has worked well so far), and insert them as plain text when they do.

Anyone want to work on this?

**Comment by kiejo** [comment]
For my specific use case I hadn't thought about inserting files directly as document content. I would prefer not to interpret the file content on the client and instead upload the file to the backend where it gets processed.
Depending on the file type I want to treat pasted/dropped files in different ways. Here are a few examples:
* Images: Create a standard image node, but do some image processing in the backend (e.g. resizing)
* HTML: Render the file as an attachment node with an inline preview using syntax highlighting
* TXT: Render the file as an attachment node with an inline preview of the text
* PDF: Render the file as an attachment with an inline preview of the PDF content

For `drop` events I can already do this and having the possibility to handle paste events of type `Files` in the same or a similar way would be ideal for my use case. Exposing the event in a more generic way would still allow the library user to implement the custom client side handling you described.

**Comment by kiejo** [comment]
I haven't tried it yet, but the newly introduced `domPaste` event should allow us to handle the `Files` type in a custom way :)

**Comment by marijnh** [comment]
Since 0.12.0, handling raw dom events is done with the [`handleDOMEvent`](http://prosemirror.net/ref.html#view.EditorProps.handleDOMEvent) prop. Since there's not really any scaffolding needed for loading a file in whichever way you want and then inserting some custom node into the document, I think this is sufficient to address this use case without further paste-specific logic.

**Comment by mangelozzi** [comment]
For anyone else with the same issue, you use the `paste` key of `handleDOMEvents` type of plugin `props`, e.g.

```ts
    return new Plugin({
        props: {
            handleDOMEvents: {
                paste(view: EditorView, event: ClipboardEvent): boolean | undefined {
                    const files = event.clipboardData?.files;
                    if (files && files.length >= 1) {
                        event.preventDefault();
                        for (const file of Array.from(files)) {
                            handleFile(file);  // <- do stuff here
                        }
                    }
                    return undefined;
                },
            },

        },
    });
```
