### ISSUE TITLE
Extended keymap on mac is not working

### ISSUE THREAD

**Issue by SamyPesse** [ProseMirror/prosemirror#403]
The code at https://github.com/ProseMirror/prosemirror/blob/master/src/commands/index.js#L578 is not working (For example `baseKeymap.lookup("Mod-Backspace")` returns `undefined`).

**Comment by SamyPesse** [comment]
More details,

I've added some logs:


![screen shot 2016-07-13 at 13 14 03](https://cloud.githubusercontent.com/assets/845425/16801565/cbeaaed2-48fb-11e6-9c30-daffa6b5ac2e.png)

And output:

![screen shot 2016-07-13 at 13 14 33](https://cloud.githubusercontent.com/assets/845425/16801564/cbc68c32-48fb-11e6-98a3-098d9fa985ea.png)

**Comment by marijnh** [comment]
`lookup` expects normalized key names. So either pass it `"Cmd-Backspace"`, or call `Keymap.normalizeKeyName` on your key name first.

**Comment by SamyPesse** [comment]
@marijnh This is not my code, this is Prsemirror code base ([src/commands/index.js](https://github.com/ProseMirror/prosemirror/blob/master/src/commands/index.js))

**Comment by marijnh** [comment]
Oh, I see what you mean now. See attached patch.

**Comment by SamyPesse** [comment]
Thanks 👍
