### ISSUE TITLE
Not use copyObj to create dynamic exports

### ISSUE THREAD

**Issue by mitermayer** [ProseMirror/prosemirror#405]
Hi @marijnh ,

Would be great if we could have explicit exports instead of dynamic generating. Found this problem when trying to automate type definitions generation for proseMirror based on master commits (https://discuss.prosemirror.net/t/type-definitions/97/11?u=mitermayer).

The file `src/menu/index.js` has the following

```
 1 const {copyObj} = require("../util/obj")
 2 
 3 copyObj(require("./menu"), exports)
 4 exports.menuBar = require("./menubar").menuBar
 5 exports.tooltipMenu = require("./tooltipmenu").tooltipMenu
```

Ideally would be great if we could manually list all the exports.

**Comment by marijnh** [comment]
Done.
