### ISSUE TITLE
expose class Subscription

### ISSUE THREAD

**Issue by mitermayer** [ProseMirror/prosemirror#409]
Hi @marijnh,

I understand the Subscription comes from another project. But would be great if we could through prosemirror create and dispatch custom events to avoid having to implement subscribers or implicitly requiring 'subscription' package.

I was thinking something on the line of

```
const {Subscription ... } = require("subscription")

class ProseMirror {
    ...
    pm.Subscription = Subscription;
    ...
}
```

then we could:

```
   mySubscription = new pm.Subscription;
```

**Comment by marijnh** [comment]
I disagree, if you want to use something from the `subscription` package, it makes sense to import it. If you really really don't want to, you could access `pm.on.change.constructor`.
