### ISSUE TITLE
extending the document model

### ISSUE THREAD

**Issue by salzhrani** [ProseMirror/prosemirror#41]
With the recent updates in master how does one go about adding new node types ?

**Comment by marijnh** [comment]
You don't yet -- the implementation is not complete. Give it some more time
(I'm leaving for a conference tomorrow, can't work on ProseMirror full time
this week)

**Comment by salzhrani** [comment]
No problem

**Comment by marijnh** [comment]
(This now exists, and is [documented](http://prosemirror.net/doc/manual.html#NodeType).
