### ISSUE TITLE
can't set selection during setDoc

### ISSUE THREAD

**Issue by episodeyang** [ProseMirror/prosemirror#410]
I have serialized the selection as: 
```javascript
{from : <number>, to: <number>}
```
but if I pass this as a second parameter to pm.setDoc(doc, selection), the cursor is still set to the beginning of the container.

What is the correct way to serialize selection and pass it in during setDoc?

Thanks in advance!
Ge

**Comment by marijnh** [comment]
As you observed, you are passing a serialized value, not an actual `Selection` instance, as described in the API docs. So that does not work. Deserialize it first.

**Comment by episodeyang** [comment]
Hi, I tried to desexualize it first with Selection and textselection. What
is the standard way to serialize and desexualize selections? Looked through
source and documentation couldnt find it.

Thanks!
Ge

**Comment by marijnh** [comment]
There is no built-in way.
