### ISSUE TITLE
drop cursor doesn't show up in the right place when inside css transform

### ISSUE THREAD

**Issue by nickclaw** [ProseMirror/prosemirror#412]
You can replicate this by running this following line in the the dino demo.

```
document.querySelector('article').style.transform = 'scale(.5)';
```

and then trying to drag/drop the dinosaurs. Tested in Chrome.

**Comment by marijnh** [comment]
Unfortunately, transforms have the side effect of making JavaScript-based positioning pretty much impossible. This isn't something we can help, I believe.

**Comment by nickclaw** [comment]
That's what I thought at first, but when you drop the dino, it actually lands where your mouse was. Leading me to think there might be a chance it could place the cursor correctly too.

**Comment by nickclaw** [comment]
In my code, I intercept drops on the input, parse my custom dataTransfer type and use something along the lines of the following code to place it:

```js
const pos = pm.posAtCoords({ top: evt.pageY, left: evt.pageX });
const ref = pm.doc.resolve(pos);
const sel = new TextSelection(ref);
pm.tr
    .setSelection(sel)
    .insert(pos, schema.nodes.custom.create({ ...}))
    .apply();
```

so it looks like it is possible to get the right document position. I couldn't figure out why the dropTarget positioning in the dragover handler of edit/input.js doesn't work the same way.

**Comment by nickclaw** [comment]
Here's a solution I just found. It reverses transforms from outside the editor by comparing the client size of the editor to the bounding rectangle size and reversing the transform. Would have you have any interest in accepting this a PR.

```diff
if (pos == null) return
   let coords = pm.coordsAtPos(pos)
   let rect = pm.wrapper.getBoundingClientRect()
+  let scaleX = pm.wrapper.clientWidth / rect.width;
+  let scaleY = pm.wrapper.clientHeight / rect.height;
   coords.top -= rect.top
   coords.right -= rect.left
   coords.bottom -= rect.top
   coords.left -= rect.left
   target.style.left = (coords.left - 1) + "px"
   target.style.top = coords.top + "px"
+  target.style.transform = 'scale(' + scaleX + ', ' + scaleY + ')';
+  target.style.transformOrigin = -coords.left + 'px ' + -coords.top + 'px';
   target.style.height = (coords.bottom - coords.top) + "px"
 }
```

**Comment by marijnh** [comment]
The drop cursor is now gone from the core library, and the new drop cursor [module](https://github.com/prosemirror/prosemirror-dropcursor) uses decorations, which don't use positioning like this, to show a cursor.
