### ISSUE TITLE
selection from/to order

### ISSUE THREAD

**Issue by episodeyang** [ProseMirror/prosemirror#413]
I noticed that if I get the selection from `doc.selection.from` and `doc.selection.to`, the from is always smaller than to. 

If my selection is the opposite, passing such a `new TextSelection(selection)` back to the editor would result in the selection to be reverted. 

Is there a way to preserve the head and tail order of the selection?

You can reproduce the problem here:  http://www.episodeyang.com/react-prosemirror

1. press <kbd>shift</kbd> at the end of the line
2. press <kbd>left-arrow</kbd>
3. press <kbd>left-arrow</kbd> again, and the selection disappears and reappears. 

Thanks!
Ge

**Comment by marijnh** [comment]
You want `selection.head` and `selection.anchor`.

**Comment by episodeyang** [comment]
Thanks! Was using it wrong.

Ge
