### ISSUE TITLE
Plugins cached map should be done per Prosemirror Instance instead of globally

### ISSUE THREAD

**Issue by mitermayer** [ProseMirror/prosemirror#415]
Hi @marijnh,

I am trying to write tests for prosemirror plugins

```
let pm;
class MyPlugin {
   constructor(pm) {
      ....
      this.name = 'MyPlugin';
      ....
   }
}
beforeEach(() => {
    pm = new ProseMirror({
     ....
     plugins: [
        new Plugin(MyPlugin)
     ]
   })
});

afterEach(() => {
    pm = null;
});
```

That seemed fine at first since i could access `pm.plugin.MyPlugin` and do my assertions on it. However any test after the first one will fail since the next iteration the plugin will be defined as  `pm.plugin.MyPlugin_2` with the `_X` after each subsequent test.

this is caused by the file `src/edit/plugin.js`:

```
  1 const pluginProps = Object.create(null)
  2
  3 // Each plugin gets assigned a unique property name, so that its state
  4 // can be stored in the editor's `plugin` object.
  5 function registerProp(name = "plugin") {
  6   for (let i = 1;; i++) {
  7     let prop = name + (i > 1 ? "_" + i : "")
  8     if (!(prop in pluginProps)) return pluginProps[prop] = prop
  9   }
 10 }
```

Would be great if `pluginProps` could be tracked by each new ProseMirror instance instead of a global mapping.

**Comment by marijnh** [comment]
To access a plugin's state, you should go through that plugin object's `get` method. The docs don't promise the `plugins` object even exists, it's not an exported piece of API.

**Comment by mitermayer** [comment]
@marijnh I understand. But that also raises another point which is the possibility of memory leak as we never clean the `pluginProps`. 

The use case of using prosemirror for viewing and editing comments on a single page app where content is loaded asynchrnous could lead to `pluginProps` becoming a memory leak. Since each prosemirror instace would add it's plugin references to the `pluginProps`.

**Comment by marijnh** [comment]
It'll only add a string to that table. Unless you are creating a ridiculous amount of plugins, the memory cost is negligible
