### ISSUE TITLE
Wrong selection when dragging block node of size 1

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#416]
Not sure of the full extent of the error conditions but I have an imageFigure node of nodeSize 1. If I have two of these figures next to each other and try and drag the bottom one, the first one will get selected. This only happens when the previous selection was below both of them.

```
<ImageFigure>
<ImageFigure>
... content ...
<previous selection / cursor position>
```

I've isolated it to `selectionFromDom` (https://github.com/ProseMirror/prosemirror/blob/e47d1275e949d7d3963455b3f0ca13cef58f006f/src/edit/selection.js#L363) where the bias is getting set to `-1`. In this error case, anchor and head are equal (since nodeSize is 1) and oldHead is greater than new head. Not sure if the logic here is the culprit or if the logic in `findFrom` is the culprit.

**Comment by marijnh** [comment]
I tried to reproduce this with HR nodes (which are also size-1 block-level nodes), but couldn't get anything like what you describe to happen. But I am not really sure where `selectionFromDOM` even comes in when dragging is happening. Could you describe in a little more detail what you're doing?

**Comment by wes-r** [comment]
I was able to reproduce this with HR!

Two HRs are right on top of each other and cursor is below both of them:
![screen shot 2016-07-25 at 9 24 51 am](https://cloud.githubusercontent.com/assets/1568246/17102911/b3fed17a-5249-11e6-8bb2-6d2114bd496a.png)

Click and drag (single action!) on bottom HR, notice top HR gets selected:
![screen shot 2016-07-25 at 9 24 58 am](https://cloud.githubusercontent.com/assets/1568246/17102912/b3ffe4ac-5249-11e6-9379-a753f27682a2.png)

Playing with this, it looks like sometimes just clicking on bottom HR causes the error (no need to try and drag).

**Comment by marijnh** [comment]
Which browser is this in?

**Comment by wes-r** [comment]
On a mac - Chrome version 51.0.2704.106 (64-bit)

**Comment by marijnh** [comment]
I see what you mean now. That's indeed an undesriable effect of the bias trick I use to try and ensure selection never gets 'stuck' where it stays in one place as you repeatedly press an arrow key. Attached patch adds a special case for when you click a selectable node.

**Comment by wes-r** [comment]
@marijnh I believe this is happening again can you re-open? Tried with latest (0.10.0).

**Comment by marijnh** [comment]
I can't reproduce this with 0.10.0

**Comment by wes-r** [comment]
Hmm seems like it breaks with my imageFigure's but not the HRs, don't know the difference yet.
