### ISSUE TITLE
Simpler approach to drawing partially decorated text nodes causes issue with marked ranges

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#417]
My latest merge with upstream introduced a new bug around mark ranges where the text either disappears or flashes with nearby edits.

I believe I've isolated this bug to https://github.com/ProseMirror/prosemirror/commit/5df676f368f1dc00aaeb8e506216596d9101b378

To reproduce:
1. Run latest demo
2. Type "hello world"
3. Highlight "world"
4. run `pm.markRange(pm.selection.from, pm.selection.to, {className: "foobar"})`
5. Move cursor to end of line (just after "world").
6. Hit enter.
7. Notice the word "world" either flashes or disappears completely.

**Comment by marijnh** [comment]
Thanks for noticing that. Attached patch should address it.
