### ISSUE TITLE
IE/Edge script 65535 error

### ISSUE THREAD

**Issue by kennyhk** [ProseMirror/prosemirror#418]
i am using webpack and babel with prosemirror on my project,  IE and Edge will throw script 65535 error when try to call the "requestAnimationFrame" on "util/dom.js" : 

```
function requestAnimationFrame(f) {
  if (reqFrame) return reqFrame(f)  // <-- IE/Edge throw script 65535 error
  else return setTimeout(f, 10)
}
```

i dont know what is the reason, but  i have a solution to fix it : 
```
function requestAnimationFrame(f) {
    if (reqFrame) return reqFrame.apply(window, [f]);  // <-- working on IE/Edge !
    else return setTimeout(f, 10);
}
```

**Comment by marijnh** [comment]
Thanks. Attached patch should do the same thing.

**Comment by kennyhk** [comment]
hello, please don't forget the "cancelAnimationFrame" also has same problem, thank you!
