### ISSUE TITLE
ProseMirror Constructor undefined 

### ISSUE THREAD

**Issue by kgaree** [ProseMirror/prosemirror#42]
I would like to load ProseMirror into a Polymer element. after loading browserified prosemirror bundle into my component. The Constructor reference is undefined.
The error returned is:
Uncaught ReferenceError: ProseMirror is not defined

Code:
var editor = new ProseMirror({
          place: this.$.editor,
          doc: "Hello!",
          docFormat: "text"
        })

**Comment by arekkas** [comment]
How is ProseMirror defined? Via require or...?

**Comment by ehd** [comment]
I'm sure the public interface is going to change soon, but for now: [demo.js](https://github.com/ProseMirror/prosemirror/blob/ba918324090e1ed43080ddff2fc09c60b84e956c/demo/demo.js#L1-L4) shows how to require the current version of prosemirror. Just build the project, replace `src` with `dist` for the imports and it should work.

**Comment by kgaree** [comment]
Browserify packaging error. Browserify by default wraps the js in an anonymous function making internal Constructors, functions and variables inaccessible to methods "outside" of browserified bundle. I was able to access ProseMirror constructor from Polymer by exposing the run function as shown in example below. Problem I have now is issue #47
```
var ProseMirror = require("./edit/main").ProseMirror
require("./menu/menubar");

var APP = {
    run: function(param1) {
      console.log("run " + param1);
        var editor = new ProseMirror({
          place: param1,
          menuBar: { float: true },
          doc: "Hello!",
          docFormat: "text"
        })
    }
};

module.exports = APP;
```
