### ISSUE TITLE
Placing an inline node at the end of a line prevents putting the cursor at the end of the line by clicking

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#420]
With the following example content, clicking at the end of the line selects the image and triggers a `clickOn`. This prevents me from for example creating a new empty paragraph below the existing one by using the mouse and pressing `Enter`.
![inline_node_click](https://cloud.githubusercontent.com/assets/152507/17129298/7fad9586-5312-11e6-811a-53af9f82f358.png)

I would suggest not triggering a `clickOn` event and simply putting the cursor behind the inline node. This seems to be a regression as I did not have this problem with earlier versions of ProseMirror (e.g. 0.7.0).

**Comment by marijnh** [comment]
I'm not seeing this problem on the master branch. If I have an image node as the last node in a textblock, clicking after it consistently puts the cursor after it.

**Comment by kiejo** [comment]
I'm sorry I tested this with 0.8.3 and you are right that this works fine on the master branch :) Great!

**Comment by kiejo** [comment]
I can confirm this is now working for image nodes :)
But I just found another case where the `clickOn` gets triggered when clicking at the end of the line. I have a `Paragraph` containing a single inline node, which is rendered with the following DOM structure:

![node_dom](https://cloud.githubusercontent.com/assets/152507/17254863/db0a473e-55b6-11e6-9ed3-f4cdeb249453.png)

(In this case I want to handle the `clickOn` event when the node is clicked to overwrite the default href click behavior.)

**Comment by kiejo** [comment]
I just noticed that this issue is closed, but I am still experiencing the problem I described in my last comment with inline nodes that are not images. Would be really great to have a fix or a workaround for this as I have multiple nodes using the described DOM structure. I assume that the incorrect selection and `clickOn` behavior is caused by the same issue.

**Comment by marijnh** [comment]
Yeah, I still had the email starred to look into it, but I'll reopen the issue as well.

**Comment by marijnh** [comment]
Patches 0d2968494 and 806d13fff031a make this go away even for nodes with children.
