### ISSUE TITLE
0.9 release has missing modules

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#421]
after updating to 0.9 via npm things seem to be broken (for me at least). After adapting my sources for 0.9, I get errors like:

`Module not found: Error: Cannot resolve module 'prosemirror/dist/commands-list' in ...`

and when I take a look at `node_modules/prosemirror/`, the `package.json` looks fine, but in `/src` and `/dist` some modules present at the current master branch are missing.

and I have deleted the whole `node_modules/prosemirror/` and npm-installed it again.

**Comment by marijnh** [comment]
Commands-list doesn't exist in 0.9.0, so it not being in the package is
expected. Note that this release doesn't correspond to the current master
branch.

**Comment by rsaccon** [comment]
ok, thanks, then I messed up, gonna close it
