### ISSUE TITLE
example usage of history plugin

### ISSUE THREAD

**Issue by episodeyang** [ProseMirror/prosemirror#422]
Hi Marijn,

In your example you had the following usage for the historyPlugin:

```
import {historyPlugin} from 'prosemirror/dist/edit/history'
```

However it seems historyPlugin does not exist and when I do

```
import {History} from 'prosemirror/dist/edit/history';
```

and pass it into options.plugins = [History], I get an error, saying that the plugin does not have an attach method.

What is the correct way to use the history plugin?

Thanks!
Ge

**Comment by marijnh** [comment]
Which example are you referring to?

**Comment by episodeyang** [comment]
Hey! I am referring to this one:
https://github.com/ProseMirror/website/blob/master/src/demo/basic.js

**Comment by episodeyang** [comment]
and it takes me to this:

https://github.com/ProseMirror/prosemirror/blob/master/src/example-setup/index.js#L5

**Comment by marijnh** [comment]
You appear to be mixing versions. That all works, on the _master_ branch. If you're using 0.9.0 you have to look at the demo.js from that release.
