### ISSUE TITLE
SVG uncaught error: Cannot assign to read only property 'className'

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#423]
0.9.0

On first menu render, I'm getting this uncaught error:

> Cannot assign to read only property 'className' of object '#<SVGSVGElement>'

from https://github.com/ProseMirror/prosemirror/blob/62f0864cb784ff515219c440a5f48b5ada72e4e0/src/menu/icons.js#L38-L39 ... should that be `collection.classList.add(...)`?

**Comment by marijnh** [comment]
This seems to work on the browser's I'm testing with. Why would an `<svg>` element have a writable `classList` but no writable `className`?

**Comment by forresto** [comment]
> For an SVG element, className is not a string, but an instance of SVGAnimatedString.

So `svg.className.baseVal = ...` or `svg.setAttribute("class", ...)` or `svg.classList.add(...)` or...

**Comment by marijnh** [comment]
Ugh, I wasn't even trying to set `className`, that should be `id` instead. Attached patch fixes this.
