### ISSUE TITLE
Cannot enter '<>' at the beginning of line

### ISSUE THREAD

**Issue by efdi** [ProseMirror/prosemirror#424]
Tested on 0.6, 0.7, 0.8 and 0.9 in Chrome both on MacOs and Windows

1. Go to new line
2. Enter '<'
3. Enter '>'
4. First symbol disappears ('<')

**Comment by jacobsmith** [comment]
Confirmed on latest demo (presumably 0.10, but I don't know for sure)

**Comment by marijnh** [comment]
This was fixed by 085592e5d65c746b713cce2eb7bfce710aa4c2cf, which is part of 0.10.0
