### ISSUE TITLE
The clickOn event is not fired for inline nodes in 0.9.0

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#425]
Putting an inline node inside a `Paragraph` (e.g. `Image`) and clicking on it fires the `clickOn` event only for the `Paragraph` node and its parents. Instead, the event should first be fired for the clicked inline node.
This seems to be a regression as this was not the case in 0.8.3.

**Comment by marijnh** [comment]
You're right, I broke this while fixing #416. Attached patch should restore it.

**Comment by kiejo** [comment]
Thanks, this fixes the issue, but unfortunately brings back #420.
