### ISSUE TITLE
0.9.0 tag and one more commit not in master

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#426]
* tag https://github.com/ProseMirror/prosemirror/commit/97af10a5633c9c4a3d12e966ee3296c1acef6e9d
* https://github.com/ProseMirror/prosemirror/commit/5e75617d55f884e4c9af5ef13a8328c87837090f

master: https://github.com/ProseMirror/prosemirror/commits/master

**Comment by marijnh** [comment]
Yes, this is the case, I know.
