### ISSUE TITLE
Pasting text into an empty table cell throws error

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#427]
Pasting text into an empty table cell throws the error `Invalid content for node table_row`. Pasting the same text into a non-empty table cell works fine.
This is probably related to #397.

**Comment by tzuhsiulin** [comment]
I think that problem may be caused by insertRange. The method will calculate position to placed data. But when you paste text into a empty table cell will get table_row then replace step will throws error. Because table_row can't placed paragraph.

**Comment by marijnh** [comment]
This is another symptom of the problem that's causing #397. I added a note there.
