### ISSUE TITLE
Pressing enter in an empty paragraph inside a table cell throws error

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#428]
Pressing `Enter` inside an empty paragraph inside a table cell throws the error `Invalid content for node table_row`:

![cell_err](https://cloud.githubusercontent.com/assets/152507/17338603/567c2610-58e8-11e6-8ae6-a48c51f7d588.png)
The error is only thrown the first time `Enter` is pressed. Pressing `Enter` again in the same paragraph does not throw an error and splits it as expected.

This is the DOM structure _before_ pressing `Enter` for the first time:
![dom_before](https://cloud.githubusercontent.com/assets/152507/17338538/0f141c4c-58e8-11e6-80e6-d2540a9026a7.png)
And this is the DOM structure _after_ pressing `Enter` for the first time:
![dom_after](https://cloud.githubusercontent.com/assets/152507/17338546/1bbb5406-58e8-11e6-8611-276b8028e5fb.png)

This might also be related to #427 as pasting into a paragraph where `Enter` was pressed before does work while pasting it into a fresh empty paragraph does not work.

**Comment by marijnh** [comment]
Could you see if patch 9bf1f8fb295b41 (which currently only exists on the linear branch) helps?

**Comment by kiejo** [comment]
Yes, the patch fixes the issue! Would be great to have this patch on the master branch.

**Comment by marijnh** [comment]
Great. Added as 11e8834
