### ISSUE TITLE
Tabbing out of a ProseMirror editor while the cursor is visible doesn't hide the cursor

### ISSUE THREAD

**Issue by trevonromanuik** [ProseMirror/prosemirror#430]
If you focus on a ProseMirror editor then tab away from it while the cursor is visible, the cursor stays visible even though the focus has been lost. This is reproducible in the demos in Chrome 52.0.2743.116 (64-bit).

**Comment by marijnh** [comment]
This appears to be Chrome's normal behavior for contenteditable elements. If you create a plain contenteditable div and tab out of it (when the cursor is visible, in terms of its blink cycle), you get the exact same effect.

**Comment by trevonromanuik** [comment]
Oh I assumed that ProseMirror's cursor was an element controlled by ProseMirror like it is in CodeMirror. I'll close this as a non-issue, although it is weird behaviour that Chrome should probably fix.
