### ISSUE TITLE
Disable inline table editing and resizing controls in Firefox

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#432]
Firefox provides additional UI controls to edit tables when they are contenteditable, which looks like this:
![table_controls_ff](https://cloud.githubusercontent.com/assets/152507/17691598/bed4c2e6-6395-11e6-87c7-a8fdab78ec43.png)

Using these controls does not play well with ProseMirror (e.g. inserting a row does not insert a row in the document model, resizing the table does not do anything).

It is possible to disable these controls with this code:
```javascript
document.execCommand('enableObjectResizing', false, 'false');
document.execCommand('enableInlineTableEditing', false, 'false');
```
More information: https://developer.mozilla.org/en/docs/Web/API/Document/execCommand

I am currently calling these methods inside my code outside of ProseMirror. We could also think about directly putting these function calls in the ProseMirror code.

**Comment by marijnh** [comment]
The stupid thing (and I really wonder what the people who came up with `execCommand` in general were thinking) is that this appears to be a _global_, per window setting, with no way to apply it only to our editable element. So I can see this interacting badly with other elements in the page, and I'd feel somewhat bad about just adding these lines to our library init code.

A quick search doesn't however, find any saner alternatives. Do you happen to know of any?

**Comment by kiejo** [comment]
Unfortunately I did not find any alternatives and I agree that putting these lines in our library code is less than ideal. Maybe this is something we should put somewhere in the documentation? As soon as you know about this issue, it is rather easy to decide if one wants to use `execCommand` to work around it or not.

**Comment by marijnh** [comment]
Noted in the docs in https://github.com/ProseMirror/prosemirror-schema-table/commit/57c170f2c39e2e7b75d6d72bf766409cf867ffc4
