### ISSUE TITLE
Ability to know if HTML content can be parsed by the schema

### ISSUE THREAD

**Issue by mitermayer** [ProseMirror/prosemirror#434]
Hi Marjin,

Is there a way to know if a certain shape of HTML content can't be parsed by a certain schema? The use case is being able to detect unsupported types of documents and being able to action upon them. 

Would be great if we could have something similar to parseDOM but that would only return a boolean.

thanks

**Comment by marijnh** [comment]
How would you use this? Are you interested only in the outer wrapping tag of the HTML content, or in any of its child elements? I think the most reasonable way to do this would be to allow wildcard parsers that run on any nodes that's not recognized by another selector (and which must return a piece of document just like the other parsers)

**Comment by marijnh** [comment]
Closing, but feel free to add further information.
