### ISSUE TITLE
Jumpy drop target for block nodes

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#435]
While dragging a block level node, the drop target can jump awkwardly.

Here I'm dragging the horizontal rule over the word "styling" and the cursor correctly appears to the left of this block.
![screen shot 2016-08-22 at 7 25 54 pm](https://cloud.githubusercontent.com/assets/1568246/17875190/557493f4-689e-11e6-829e-9623f2833127.png)

Here I'm dragging it over the word "from" and the cursor appears in the next block!
![screen shot 2016-08-22 at 7 25 38 pm](https://cloud.githubusercontent.com/assets/1568246/17875189/55741e10-689e-11e6-89e8-55adde1e7607.png)

https://github.com/ProseMirror/prosemirror/blob/master/src/edit/input.js#L499 is definitely the culprit. Looks like your determining if the drop target is above or below midpoint of the node. Not sure why but for me this created some instances where dragging up would cause the cursor to jump from bottom paragraph, to top, and back to bottom (even though I'm only dragging upward and would expect it to jump once from bottom to top).

Changing this line to `let bias = d == $pos.depth ? 0 : $pos.pos <= $pos.end(d + 1) ? -1 : 1` yielded much smoother and more predictable drop targets.

**Comment by kapouer** [comment]
Less jumpy with your change, but now it isn't possible to drop at the end of the last line.

**Comment by marijnh** [comment]
Yeah, using the node-size halfpoint to determine this is a really bad idea. We should probably be doing something with comparing actual screen coordinates to the cursor position. Both places that call `dropPos` have access to the DOM, so we could change it to take a whole editor and get screen coordinates to determine bias.

**Comment by wes-r** [comment]
@marijnh That would possibly alleviate another issue I ran into which is `elementFromPoint()` does not take into account margins. So for example, dragging an `hr` in the basic demo and hovering over the paragraph margins will result in the drop target being the `ProseMirror-content` (parent div) which can be seen by the drop cursor being at the top. I worked around this by using paddings instead of margins.

**Comment by wes-r** [comment]
@kapouer changing the `<=` to `<` in my example code will allow dragging at the end of the last line, but you'll need to drag it to the very end of the line.

**Comment by kapouer** [comment]
Hello, it's less jumpy since version 0.12...

**Comment by marijnh** [comment]
The built-in drop cursor was removed in favor of a new approach, so I'm closing this
