### ISSUE TITLE
Tooltip Menu icons don't show up in IE11

### ISSUE THREAD

**Issue by trevonromanuik** [ProseMirror/prosemirror#439]
In IE v11.545.10586.0, highlighting text causes the tooltip menu to appear but the icons do not appear.

**Comment by jacobsmith** [comment]
Just as a heads up, I doubt that will be addressed as I believe the tooltip menu is no longer going to be maintained after the next release ( https://github.com/ProseMirror/prosemirror/issues/452#issuecomment-245700391 ).

**Comment by marijnh** [comment]
Indeed. Closing this.
