### ISSUE TITLE
Paste is not sanitized in IE

### ISSUE THREAD

**Issue by arekkas** [ProseMirror/prosemirror#44]
I believe this to be due to missing oninput events in IE. Afaik you need to do something like a reocurring cleanup (setTimeout) to catch these.

![paste](https://cloud.githubusercontent.com/assets/3372410/10469042/debfd62a-7202-11e5-9cb9-a0dd4253be78.PNG)

**Comment by marijnh** [comment]
Which IE version is this? Recent ones all have decent support the paste event, I think. Work on supporting IE<11 hasn't started yet.

**Comment by arekkas** [comment]
IE 11 / Windows 10. Microsoft Edge should work though as it supports most of the HTML5 stuff.

**Comment by arekkas** [comment]
By the way, I believe that forcing people to use a modern browser instead of hacking around an awful lot is okay as < IE11 has a combined market share of somewhere [around 2%](http://www.w3schools.com/browsers/browsers_explorer.asp). In one year or so everybody is going to use Edge anyways as IE's death has already been [decided](http://www.theverge.com/2015/3/17/8230631/microsoft-is-killing-off-the-internet-explorer-brand)

**Comment by ureimers** [comment]
In big companies browser adoption is very slow. There are different reasons for that but thing is that if one has a customer with a lot of employees and the company's default browser is IE10, then she won't be able to use ProseMirror in any projects for that company even if there's great potential to do so.
In the private sector the bar for supported browsers might be set much higher but there are a lot of companies that are still forced to use older browsers.

**Comment by arekkas** [comment]
In that case, that company has to decide to invest some resources into making ProseMirror IE10 compatible ;)

**Comment by arekkas** [comment]
...also some things are simply not possible in IE due to missing editing events. There are multiple cumberstone steps neccessary to cover for these cases by frequent polling or similar bad patterns. This does not only reduce code quality, it also reduces user experience and increases code complexity. All of this for supporting legacy software. If people are forced to use outdated software by their company then sure this sucks. But if the company is really driven on adopting new technology, they have to upgrade the platforms as well. That's simply how it is.

These amongst others are the reasons why I deem IE support as secondary. And would actually not care about fixing IE.

**Comment by marijnh** [comment]
IE9+ might actually end up being realistic (it has ES5 and a sane selection API), but this is not a priority for me at the moment.

**Comment by marijnh** [comment]
I believe the solution to issue #325 will also help here.
