### ISSUE TITLE
Unmaintained Makefile

### ISSUE THREAD

**Issue by johanssj** [ProseMirror/prosemirror#444]
Looks like the Makefile has been orphaned given dist/demo/test build stuff happens via npm run scripts. Guessing product was originally build with Makefile in the dim dark past. Suggest either

1) the Makefile be removed altogether as "make demo" breaks since devDependencies don't include browserify and babelify (understand all done via moduleserve now), or

2) the Makefile and package.json devDependencies be updated.

I'd be happy to fix the Makefile bits but possibly a futile effort maintaining two different build regimes. Guidance/comments? btw. Thanks for the postcard.

**Comment by marijnh** [comment]
(The makefile will be gone in the next release.)

**Comment by johanssj** [comment]
Ok, no worries.  Thanks.
