### ISSUE TITLE
"Cannot read property 'nodeSize' of undefined" when crossing image boundaries?

### ISSUE THREAD

**Issue by emanchado** [ProseMirror/prosemirror#447]
I'm not sure where the problem lies exactly, but it seems related to creating marks that surround images. See a reduced test case in https://gist.github.com/emanchado/5dda9db4bb23614cc2b7bc0f8c762bc8, and note the comment on bug.js about the value for the `limit` variable.

I tried with 0.10.0 and with latest master from GitHub. Browsers I used: Vivaldi 1.3.551.38 (that uses Blink, like Chrome), and Firefox 48.0, both under Linux.

The error I get is:
```
bug_bundle.js:4421 Uncaught TypeError: Cannot read property 'nodeSize' of undefined
nodesBetween @ bug_bundle.js:4421
nodesBetween @ bug_bundle.js:5897
nodesBetween @ bug_bundle.js:4424
nodesBetween @ bug_bundle.js:5897
Transform.addMark @ bug_bundle.js:8676
(anonymous function) @ bug_bundle.js:21
```

Removing the image from `bug.html` seems to work nicely, that's why I guess that it has to do with the image boundary.

**Comment by marijnh** [comment]
This was a data corruption bug in the DOM parser. Patch 69b6b53 should help.
