### ISSUE TITLE
Image resizing should be disabled

### ISSUE THREAD

**Issue by arekkas** [ProseMirror/prosemirror#45]
... not only because it adds width and height (or worse style) attributes but also is buggy when dragging arround.

![prose dnd resize](https://cloud.githubusercontent.com/assets/3372410/10470265/065d8944-720c-11e5-8746-85b4ccf747ba.gif)

I believe this is disabled by something similar like

```js
document.execCommand("enableObjectResizing", false, "false");
document.execCommand("enableInlineTableEditing", false, "false");
```

or by listening on the resize event:

```js
image.attachEvent("onresizestart", function(e) { e.returnValue = false; }, false);
```

*Disclaimer: these snippets are copied from the web.*

**Comment by mightyiam** [comment]
Here's [my experience with it](http://stackoverflow.com/a/27580189/359072).

What we ended up doing in WYMeditor is replacing the default native selection of images with text-like selection of the image node. But now I'm working on a custom image resize UI.

**Comment by marijnh** [comment]
Is this an IE thing? I will look into it.

(My plan is also to have my own custom image selection and resize UI -- in document schemas that enable it.)

**Comment by arekkas** [comment]
Nope, FireFox.

**Comment by marijnh** [comment]
Clicks on images are captured now, and they are set non-editable. I can no longer reproduce this issue on Firefox.
