### ISSUE TITLE
 tooltipMenu closes when the page is edited collaboratively 

### ISSUE THREAD

**Issue by wizzard0** [ProseMirror/prosemirror#452]
if you have tooltipmenu in collaborative setting, and other user changes the document while menu is open - menu will close. 

When the other user is typing constantly, it becomes practically impossible to use the tooltip menu.

**Comment by marijnh** [comment]
I'm going to stop maintaining the tooltip menu, and it'll be gone in the next release, so you'll have to figure out a way around this yourself.
