### ISSUE TITLE
Version in package.json

### ISSUE THREAD

**Issue by jtblin** [ProseMirror/prosemirror#454]
Any reason the version is not updated in package.json? Changelog says current master is `0.10.1` which is also the published npm version but package.json is stuck at 0.8.1.

**Comment by marijnh** [comment]
The thing that `master` on github points at is an unfortunate in-between state -- 0.9 and 0.10 have diverged from it. It'll be dropped entirely for 0.11, at which point the code will live in per-module repositories.

Sorry about the confusion. I've been racing to get 0.11 out, but it's complicated.

**Comment by jtblin** [comment]
Thanks for the explanation.
