### ISSUE TITLE
How to get HTML out of editor?

### ISSUE THREAD

**Issue by ilearnio** [ProseMirror/prosemirror#455]
In the documentation I could only find a way to retrieve content out of editor using `pm.doc.toJSON()` method, also I found that there is a getter `pm.doc.textContent` which returns raw text but is there any way to retrieve HTML?

**Comment by ilearnio** [comment]
I'm pretty cool with JSON tho, unless there is some server-side (Node) transpiler to HTML

**Comment by bZichett** [comment]
You can try outputting the contents of a Doc type using toDOM() and then getting the outerHTML.  This should work whether node is a Doc or a Node. You should probably split up the methods 

``` javascript

node.toDOM().outerHTML

		var container = document.createElement('div')
		var fragment = node.content.toDOM()
	}
}
```

**Comment by ilearnio** [comment]
Thanks for response @bZichett . I was able to fetch HTML from Doc like so:

```js
function getHTML() {
  const el = document.createElement('_')
  el.appendChild(pm.doc.content.toDOM())
  return el.innerHTML
}
```

But there is no `node` property in `pm` object (which is an instance of `ProseMirror`), i.e when I do `pm.node.toDOM().outerHTML` it gives me `TypeError: Cannot read property 'toDOM' of undefined`

**Comment by marijnh** [comment]
This is a request for help, for which the bug tracker is _not_ intended.

As for your last question, no one suggested doing `pm.node`. The document is in `pm.doc`.

**Comment by ilearnio** [comment]
@marijnh You are right, it's a question. But I would suggest implementing a method for getting HTML from editor, eventually this is what people are using wysiwygs for

**Comment by pdiveris** [comment]
I think implementing a toHTML() in the core would defy the logic behind ProseMirror as HTML is susceptible to interpretations by browsers, and PM aims to be a deterministic text editor. If you are happy with what you get in your DIV why not write a function that simply returns the innerHTML yourself?
