### ISSUE TITLE
sometimes setNodeSelection does not do anything

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#456]
I have a case where i need to call `pm.setNodeSelection(blockPos)` when user do a mousedown on a specific part of a block.
It works well, however, in certain situations, the node is not selected even while the correct selection operation is created. One situation in which i can reproduce it is when the editor did not have focus before the `mousedown` event. Another one is when i click several (three actually) blocks one after another and the last one doesn't get selected.
I tracked down the problem to:
https://github.com/ProseMirror/prosemirror-view/blob/b6ce1b50b3d906eb16db8b7987760c9c01f9437e/src/selection.js#L97
The early return statement prevents the code outside the `hasFocus` condition to run.

**Comment by marijnh** [comment]
Can you still reproduce this with 0.11.0? The patch you link to is in `prosemirror-view`, which didn't exist before 0.11.0 — but the `pm.setNodeSelection` call you show isn't something you can do with the current code anymore.

**Comment by kapouer** [comment]
Yes i was working on that problem just before 0.11 was released, so it's a 0.10 bug thing for now.
The fixed link is then: https://github.com/ProseMirror/prosemirror/blob/91e3b52308a7643737d2093dae78411f60b5b68e/src/edit/selection.js#L100

**Comment by marijnh** [comment]
I've been trying to reproduce something like this in 0.11, but failed to. If you can, a precise set of reproduction steps would be appreciated. Until then, I'm closing this.
