### ISSUE TITLE
How to add text-align to Node?

### ISSUE THREAD

**Issue by Rastopyr** [ProseMirror/prosemirror#461]
I read some examples and try search solution on discuss forum, but not succeed.

My task is toggle text align of text(paragraph and heading) by selected Node.

Thanks for advance

**Comment by marijnh** [comment]
Add an attribute to your node type that can store the alignment information, make it render and parse in a way that preserves that (and makes it display with the correct alignment), and add the commands, key bindings, and menu items that let the user control this attribute.

**Comment by Rastopyr** [comment]
Ok, i try did this, but for node applying only attributes specified in markes/nodes from schema. And any examples from discuss not allowed me add new type mark/node.

Can you please show link or code example with worked example.
