### ISSUE TITLE
Cannot remove three of the same character with backspace on iOS

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#463]
[![https://gyazo.com/cdf94c5f2e3592323f337161dc689ddf](https://i.gyazo.com/cdf94c5f2e3592323f337161dc689ddf.gif)](https://gyazo.com/cdf94c5f2e3592323f337161dc689ddf)
ref: http://prosemirror.net/demo/basic.html

Does not reproduce in Android Chrome.

**Comment by zacharydenton** [comment]
I can reproduce this issue by opening Chrome dev tools, enabling the device toolbar, and setting the device to iPhone 6.

**Comment by marijnh** [comment]
Attached patch should fix this.
