### ISSUE TITLE
"Wrap in ordered list" should merge node with adjacent ordered lists

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#465]
[![https://gyazo.com/c5a74af6e5542457b05d2ea94686b784](https://i.gyazo.com/c5a74af6e5542457b05d2ea94686b784.gif)](https://gyazo.com/c5a74af6e5542457b05d2ea94686b784)
ref: http://prosemirror.net/demo/basic.html
reproduced on Mac Chrome, iOS Safari, and Android Chrome

**Comment by marijnh** [comment]
I don't think it obviously should. We could define an alternative command that has this behavior, but wrapping in a list is just that, _wrapping_.
