### ISSUE TITLE
Collab ReceiveAction unexpectedly ignores own results

### ISSUE THREAD

**Issue by ThariqS** [ProseMirror/prosemirror#467]
A breaking change (as far as I can tell) of the new stateful implementation of collab is that all diffs with your own clientID will simply skipped and attempt to be confirmed.

This is hurtful when clientIDs are not unique session ids but instead tied to user accounts, which seems to be a common use case, because that allows tracking of diffs per user.

If the clientId is a userid, that means when other sessions on the same window will ignore actions from each other and when replaying old diffs, changes by the user will be ignored.

Ideally, only unconfirmed steps will be ignored in the transformation, regardless of clientId.

**Comment by marijnh** [comment]
> This is hurtful when clientIDs are not unique session ids but instead tied to user accounts,

clientIDs _must_ be unique session ids, or the whole communication protocol doesn't work at all. You could make them user IDs concatenated with a unique id, but you definitely can't just use the user id.
