### ISSUE TITLE
Add a command to "toggle" list items

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#468]
Add a command to "toggle" list items for parity with classic editors (e.g. Google Docs). 

Google Docs UX:
[![https://gyazo.com/1df74bfcecc082e1843b7be7c99483a1](https://i.gyazo.com/1df74bfcecc082e1843b7be7c99483a1.gif)](https://gyazo.com/1df74bfcecc082e1843b7be7c99483a1)
ref: https://discuss.prosemirror.net/t/auto-changing-active-marks-styles/275
rel: #465

**Comment by marijnh** [comment]
In the presence of nesting lists (as in the prosemirror-schema-list module), these don't really make a lot of sense. But for other schema types, they shouldn't be hard to implement. I'm not going to add them to the core distribution but it'd be wonderful if someone wrote them and published them on NPM.
