### ISSUE TITLE
ProseMirror-content pseudoselector `:before` fails to show when text is empty

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#469]
Removing all the text leaves behind a `<p pm-container="true" pm-offset="0" pm-size="2">` which prevents the aria-label from appearing.

[![https://gyazo.com/fb0e8cc49a06dbade6d42df5b8192276](https://i.gyazo.com/fb0e8cc49a06dbade6d42df5b8192276.gif)](https://gyazo.com/fb0e8cc49a06dbade6d42df5b8192276)
rel: https://github.com/ProseMirror/prosemirror/issues/246

**Comment by marijnh** [comment]
I'm not terrible familiar with aria tag behavior. How did you expect the label to appear?

**Comment by owjsub** [comment]
This CSS lets the `aria-label` be used as a placeholder label: 
```
.ProseMirror-content[contenteditable=true]:empty:before {
  content: attr(aria-label);
}
```
In the gif above, you'll see that `aria-label` does not appear until I manually removed the `<p pm-container="true" pm-offset="0" pm-size="2">`.

**Comment by marijnh** [comment]
I don't think `aria-label` is intended to be used as a placeholder like that. It'll cause the label to show up in a regular display, which I don't think users will expect or want.

**Comment by owjsub** [comment]
Right, instead of using `aria-label`, I could add a `placeholder` attribute to the ProseMirror content div after the editor is initialized with `view.content.setAttribute("placeholder", "Hello World")` and use the following:
```
.ProseMirror-content[contenteditable=true]:empty:before {
  content: attr(placeholder);
}
```
ref: https://codepen.io/flesler/pen/AEIFc

Regardless, the pseudoselector `:before` will fail to show due to `<p pm-container="true" pm-offset="0" pm-size="2">`

**Comment by marijnh** [comment]
Oh, _now_ I understand what you are talking about. Yes, that's how the document model works. You can't have a completely empty document, you get a single empty paragraph. I don't consider that a bug in ProseMirror, just a limitation of the technique you're trying to apply here.
