### ISSUE TITLE
menubar require _edit.defineOption not a function

### ISSUE THREAD

**Issue by kgaree** [ProseMirror/prosemirror#47]
Uncaught TypeError: (0 , _edit.defineOption) is not a function when including menubar as outlined in [manual](http://prosemirror.net/doc/manual.htm) > Bundling... 
```
var ProseMirror = require("./edit/main").ProseMirror
require("./menu/menubar");

var editor = new ProseMirror({
          place: param1,
          menuBar: { float: true },
          doc: "Hello!",
          docFormat: "text"
      })
```

**Comment by arekkas** [comment]
Did you require ProseMirror before the menubar? Why is the path to menubar *relative*? Does not look like a bug but rather wrong linking.

**Comment by kgaree** [comment]
@arekkas: yes, require ProseMirror prior to menubar. Updated issue comment. relative linking from dist directory, class paths are correct, there is no issue bundling via browserify. This works...
```
var ProseMirror = require("./edit/main").ProseMirror

var editor = new ProseMirror({
          place: param1,
          doc: "Hello!",
          docFormat: "text"
      })
```

**Comment by marijnh** [comment]
I can't really explain that. Are you using an up-to-date version of Babel (if you installed it yourself)? The exports all looks fine. `../edit` in `menubar.js` will resolve to `src/edit/index.js`, which exports `defineOption` from `./options`, which does indeed export it.

**Comment by ericandrewlewis** [comment]
Hi @kgaree, perhaps you could share the bare minimum example of how your app is setup in a Github repo?
