### ISSUE TITLE
Validate content against schema before paste

### ISSUE THREAD

**Issue by theefer** [ProseMirror/prosemirror#473]
It seems that ProseMirror doesn't validate pasted content against the schema after the paste event. For example, when copy pasting HTML, I am able to paste an `<img>` element into a PM instance even though the schema doesn't allow images. As soon as I edit the content, the image gets removed, presumably because it's detected as violating the schema.

Is this a bug or expected behaviour? If the latter, would it be possibly to run some validation in the `transformPaste` hook? Or re-validating the document right after the paste event?

Besides avoiding confusion for the user, this is also an issue in terms of security, as it is possible to execute arbitrary scripts by simply pasting what looks like normal content.

For example: `<img src="x" onerror="console.log('owned')">`.

**Comment by marijnh** [comment]
Which browser does this happen in?

**Comment by theefer** [comment]
I have reproduced it both in Chrome 53 and FF 49.

**Comment by marijnh** [comment]
I just tested in Chrome 52, and things seem to be working as intended: the paste event is handled, its HTML clipboard content parsed using the schema, and the resulting (ProseMirror document fragment, no HTML left) is inserted into the document, which is then rendered. Are you using release 0.11 or something older?

**Comment by theefer** [comment]
I'm using 0.10.1. Sorry I should I mentioned the version upfront. Would it be something fixed in 0.11?

**Comment by marijnh** [comment]
I wasn't aware that this was broken in 0.10.1 either -- the approach is the same there, but something might be malfunctioning. Want to do some debugging to see why the paste handler (in edit/input.js) isn't handling the event?

**Comment by theefer** [comment]
Ah, I think I found something. It only happens when all the pasted content is an image (or perhaps exclusively content that isn't supported by the schema?) and nothing else, such as the following doc:

https://jsbin.com/pemelipoco/edit?html,output

This causes a RangeError to be thrown in the resolve static method of ResolvedPos, because `pos` is equal to `doc.content.size + 1`. I'm afraid I can't easily give a clean stack trace because I'm running a bundled version of PM, but essentially it's

```
ResolvedPos.resolve 
ResolvedPos.resolveCached 
ResolvedPos.resolve 
Node.slice
parseDOMInContext (return statement)
fromClipboard
```

**Comment by theefer** [comment]
There are actually two separate issues in this.

The first one, which I described above, is that content violating the schema can make it into the editor DOM due to a RangeError exception being thrown, seemingly a bug in the sanitisation process happening as part of the handling of the paste event.

The second one is that regardless of whether invalid content makes it into the editor DOM, the pasted HTML is being evaluated and opens the door to an XSS attack whereby some arbitrary scripts can be executed on the page containing in the editor if some malicious content is pasted in. This is caused by the way `readHTML` turns a String of HTML into a DOM Node, by injecting the HTML into the `innerHTML` of a detached node. Unfortunately that method allows execution of scripts contained in the HTML string in some cases.

A safer method would be to use a [DOMParser](https://developer.mozilla.org/en/docs/Web/API/DOMParser) instead.

I've created a reduced example to highlight what I'm talking about and the difference: http://jsbin.com/popasexapi/edit?js,console

Would it help if I tried to come up with a patch for the second issue, by replacing the use of `document.createElement` with a `DOMParser` based method?

**Comment by marijnh** [comment]
I believe DOMParser is unable to parse raw, say, `<td>` nodes, and will always wrap the content in a bunch of stuff like `<html>` and `<body>`. It might be possible to make something work no top of this, with a bunch of hacks, but it's definitely not easy.

Can you give an example of a script injection that could be pulled off in this way? Note that the HTML is only inserted into a detached node, so no events will fire on it. The resulting DOM structure will be parsed into a ProseMirror document but never inserted into the document.

**Comment by theefer** [comment]
If you look at the JSBin example above, it shows how load/error event handlers on an `img` tag can fire arbitrary JS when inserted even into a detached node.

You're right that the DOMParser will generate a whole document out of the input, so it's not as easy to use as `createElement`. Although conversely, setting `innerHTML` also goes through some browser logic that rejigs some of the input.

For example:

``` js
var s= '<html><head><title>x</title></head><body><p>a<b>c</b></p></body></html>'
var x = document.createElement('div')
x.innerHTML = s
console.log(x.innerHTML) // "<title>x</title><p>a<b>c</b></p>"
```

**Comment by marijnh** [comment]
Oh, that's surprising (and terrible). I guess we will really have to figure out a way to avoid innerHTML then.

**Comment by marijnh** [comment]
Could you take a look at attached patch? Using innerHTML in a document instance that isn't the main document seems to disable pre-fetching of images and firing of events much like using a DOMParser would, without requiring us to deal with the make-this-a-full-HTML-doc behavior of DOMParser.

**Comment by marijnh** [comment]
Oh, I attached it wrong. I meant [this patch](https://github.com/ProseMirror/prosemirror-view/commit/0f9d341d30175bab77670ef8016c8b25079b56d6)

**Comment by theefer** [comment]
Cool thanks will take a look ASAP
