### ISSUE TITLE
History plugin will create change groups that are bigger than expected

### ISSUE THREAD

**Issue by laszbalo** [ProseMirror/prosemirror#474]
I was following the guide, copy-pasted the following example:

``` javascript
/* ... same imports as before ... */
var history = require("prosemirror-history")

var view = new EditorView(document.body, {
  state: EditorState.create({schema: schema,
                             plugins: [history.history]}),
  onAction: function(action) {
    view.updateState(view.state.applyAction(action))
  },
  // (This'll get less ugly soon)
  handleKeyDown: function(view, event) {
    if (event.ctrlKey && event.keyCode == 90)
      return history.undo(view.state, view.props.onAction)
  }
})
```

Typed in the string "hello". Selected substring "lo" at the end. Typed in "x".
Therefore new string is "helx". Upon pressing Ctrl+Z combo, Prosemirror deletes all the text.
[DEMO](http://output.jsbin.com/pihahelove)

Also, if content editable is empty and by pressing Ctrl+Z, it throws the following error:

> Uncaught TypeError: Cannot read property 'transform' of null
> 
> ``` javascript
>     function histAction(state, redo, histOptions) {
> ...
>       var selection = Selection.fromJSON(pop.transform.doc, pop.selection)
> ...
>     }
> ```

Has anyone else experienced these same issues? Thanks in advance.

Prosemirror version:

``` json
    "prosemirror-history": "^0.11.1",
    "prosemirror-keymap": "^0.11.1",
    "prosemirror-schema-basic": "^0.11.1",
    "prosemirror-state": "^0.11.1",
    "prosemirror-view": "^0.11.2"
```

Chrome for Linux version:
54.0.2840.59 (64-bit)

**Comment by laszbalo** [comment]
Just checked the demo on prosemirror.net and the history feature does not work either. Same result with Firefox 49.0.

**Comment by marijnh** [comment]
Strange. It works for me, Firefox 47 and Chrome 52 (Linux). Any specific change you're making? (I tested typing something, undoing, and redoing it back.)

**Comment by laszbalo** [comment]
Very strange indeed. Nothing fancy really, when I tested the demo on prosemirror.net's home page, tried exactly the same thing you did, but after typing in something, I was not able to undo it with either "Ctrl+Z" or "Right Click->Undo"(the "Undo" option is grayed out in the contextual menu). In addition to Chrome and Firfox, Chromium, version 55.0.2883.11 Ubuntu 16.04 (64-bit), did the same thing.

In the case of the jsbin demo that I have created by copy pasting the example from the guide, I typed in something, selected the last few characters with "Shift + ←", deleted them by pressing one arbitrary character key (at that stage of tutorial I was not aware of how to enable backspace yet, I knew it will come later). When I was about to undo, "Undo" options was grayed out in the contextual menu, just like above. Pressing "Ctrl+Z" did not delete the last character  and recovered the characters at the end that I previously selected, but deleted all characters inside the editor.

I will record my screen tomorrow and share the results here, just in case.

**Comment by marijnh** [comment]
> When I was about to undo, "Undo" options was grayed out in the contextual menu

The context menu won't work, since that's the browser's undo, which is useless. Unfortunately, browsers don't allow client code to hook into that or disable it.

You want ProseMirror's undo, i.e. the `undo` command from the `prosemirror-history` package.

**Comment by laszbalo** [comment]
I see what you mean. So, for example, in the prosemirror.net' demo, the call to bind("Mod-Z", undo) in the buildKeymap function, tells prosemirror that it should handle the 'Ctrl+Z' combo by calling the undo command, instead of having the browser to handle it.

In the jsbin demo, the handleKeyDown function actually calls the history.undo() which, in turn, causes the entire text to be deleted.(or the above exception if I press Ctrl+Z when editor is empty)

So in both cases, at least the 'Ctrl+Z' key combination should work, since both codebases have already set up to use the undo command.

**Comment by marijnh** [comment]
Okay, I see what you mean now in the demo. That's due to the way the history implementation groups edits -- everything that's adjacent to each other ends up in a single event. You'll get better results if you type something, type something else at the start again, and then undo.

This behavior isn't ideal, but I haven't gotten around to improving it yet. I've renamed this issue and will keep it open.

**Comment by marijnh** [comment]
I ended up putting a fix for this into 0.12.0. The website has been updated to that version as well. I think that should solve your problem.

**Comment by laszbalo** [comment]
Thanks for the fix. This new change group size makes the undo/redo actions much more intuitive.

However I am still experiencing the same problems with the 'Ctrl+Z' key binding. This is how it looks like on my end:

![anim](https://cloud.githubusercontent.com/assets/1551034/19603387/d72624ec-97a8-11e6-9f26-0e57708fe2d3.gif)

**Comment by marijnh** [comment]
There is a working group working on standardizing events for 'editing intentions', which I think would cover undo. Once that happens (but don't hold your breath), hooking into context-menu undo should be easy. Until then, yes, ProseMirror's technique confuses the browser's editing code too much to get anything useful out of the built-in undo.

I can reproduce the error you get when I press ctrl-z before making any change. I fixed that in https://github.com/ProseMirror/prosemirror-history/commit/685a1a459c91044c8eee3275f1c12331627ef2b2 . But when I make a change and undo, the change is undone, whereas in your recording that isn't happening. That's very puzzling. Does it still occur if you apply the patch I linked?

**Comment by laszbalo** [comment]
I can live with it, I guess, I will just show the users a message on contextmenu event to use Ctrl+Z.

Probably I ran into this #471. British keyboard, Hungarian keyboard layout. In my case the positions of the key K and the key Z are swapped. On the above picture, when it says Ctrl+z, it means the "logical" z. In order to get that, I am actually hitting the "physical" key Y on my keyboard. I tried prosemirror-keymap version 0.12.0, but when I press "Ctrl+Z" (logical) the keyName function inside handleKeyDown returns 'y'. On the other hand, when I press the logical "z"/physical "y" key, keyName returns 'z'.

By the way, I believe, that in the guide where the keymap plugin is described, the keynames should be uppercase lettters.

**Comment by marijnh** [comment]
Were you able to get things to work with 0.12? Can this be closed?

**Comment by laszbalo** [comment]
The latest version fixed the change group issue. But the keyboard layout issue still persists. At the moment, I have a 'Mod-y' mapping to handle undo. I guess, it should go under a separate issue. Thanks for your help, I am closing this for now.
