### ISSUE TITLE
Prosemirror in iOS webview is not working

### ISSUE THREAD

**Issue by bhushaan** [ProseMirror/prosemirror#475]
I am using react-native to build an iOS app and want to integrate prose mirror inside it. So for that I am trying to use prose mirror with WebView. Webview accepts the html document to render so i wrote the normal html document and I am able to run it on browser but the same page fails to render inside the webview. You can access the trial code here ( I have deployed it on the heroku ) : https://prose-mirror.herokuapp.com/ which works on browsers but not inside WebView.

I checked the react native logs and do not see any error.  Any help is appreciated.

**Comment by marijnh** [comment]
I can't test in a non-browser WebView. If you have a specific stack trace or error for me to look into, let me know, but without that, there's not much I can do with this.

**Comment by bradleyayers** [comment]
@bhushaan what version of ProseMirror are you using? I'm successfully using 0.10 in a `WKWebView` without issue.

**Comment by owjsub** [comment]
0.11 also works in a `WKWebView`. I haven't tried 0.12 yet.

**Comment by bhushaan** [comment]
I updated the react-native to latest version and it worked.
