### ISSUE TITLE
setNodeType type argument cannot be omitted if attrs argument is given after

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#478]
https://github.com/ProseMirror/prosemirror-transform/blob/5b1e35495131eb5486f4449ee0bce32cd9a0992f/src/structure.js#L131
```
tr.setNodeType(pos, {myattr: "myval"})
```
would set type to be the object instead of default `node.type`.
It's easy to workaround but somehow i find the documentation misleading.

**Comment by marijnh** [comment]
You were expecting the function to figure out that the argument you pass is supposed to be an attribute set even though you're passing it in the position of the type parameter? I don't think there are many JS interfaces that work that way. ProseMirror certainly doesn't -- parameters are positional, always.
