### ISSUE TITLE
Excessive undo/redo causes JS error

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#479]
Browser: Chrome 54.0.2840.71
OS: Mac OS X 10.11.6

If you hit the undo/redo buttons in basic demo or use the hotkeys you will get the following error once the undo/redo stack is empty:
> bundle_basic.js:1801 Uncaught TypeError: Cannot read property 'transform' of null(…)
> histAction @ bundle_basic.js:1801
> undo @ bundle_basic.js:1860
> (anonymous function) @ bundle_basic.js:2335

This is also probably the cause of `Mod-y` opening the history tab in chrome.

**Comment by marijnh** [comment]
Could it be that this is already fixed in https://github.com/ProseMirror/prosemirror-history/commit/685a1a459c91044c8eee3275f1c12331627ef2b2 ?

**Comment by wes-r** [comment]
Looks like that's probably the fix! Closing, and I'll re-open if it still exists after switching to the latest version of the history plugin.
