### ISSUE TITLE
Heading and code block input rules throw uncaught error in basic demo editor

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#480]
Steps to reproduce:

1. Go to http://prosemirror.net/demo/basic.html
2. Type "# " at the start of a paragraph
3. An uncaught error `Gap is not a flat range` is thrown

It looks like the error is caused by the transforms that are generated in `textblockTypeInputRule`.

**Comment by kiejo** [comment]
Oh, I just saw this commit https://github.com/ProseMirror/prosemirror-transform/commit/175ad378da3279e4a0bc96aa8652df8574869332, which might have fixed the issue. But I'm not sure as I can't test it at the moment.

**Comment by marijnh** [comment]
I verified that this was the same bug, and the patch you linked fixes it.
