### ISSUE TITLE
International keyboard layout

### ISSUE THREAD

**Issue by laszbalo** [ProseMirror/prosemirror#483]
Already explained it as part of a different issue #474. But just to summarize it, I am using Hungarian keyboard layout, with a British laptop. Among other things, the Y and Z keys are swapped.

Any time I press the key Y on my laptop, the operating system seamlessly converts it into character Z, and vice versa. 

Not sure what is the proper terminology here, but let me call the tactile keys on the laptop "physical" keys, and the ones which the physical keys are mapped to by the OS, "logical" keys.

In the case of Prosemirror v 0.12.1, when I hit

the physical Y key / logical Z key, this is the keybaord event which gets generated:
```javascript
{
  code: "KeyY",
  key: "z",
  keyCode: 90,
  which: 90
}
```
Ctrl+ physical Y key / logical Z key:
1.
```javascript
{
  code: "ControlLeft",
  key: "Control",
  keyCode: 17,
  which: 17
}
```
2.
```javascript
{
  code: "KeyY",
  key: "y", // NOTE: this is different from above
  keyCode: 90,
  which: 90
}
```

Only keyCode property seems to be consistent in my case, because the key property differs based on whether the Ctrl modifier was pressed or not.
Therefore got rid of the key property from w3-keyname' keyName function.
```javascript
function keyName(event) {
  return (event.shiftKey ? shift : base)[event.keyCode] || "Unidentified"
}
```
Changed my mapping from 'Mod-y' to 'Mod-z', and Ctrl+logical Z seems to be working fine. (tested with Hungarian and US keyboard layout)

Is there any particular reason why keyName function uses the key property?

**Comment by marijnh** [comment]
Which browser is this, and does the behavior occur in other browsers too? My understanding is that `event.key` is supposed to give us the actual (mapped) key, not the physical key (that's what `.code` is for), but in this case it seems that when ctrl is held, it doesn't. That might be a browser bug.

> Is there any particular reason why keyName function uses the key property?

keyCode mapping is somewhat messy and I didn't want to make up my own naming scheme for keys when there is a standard one.

**Comment by laszbalo** [comment]
The key property behaves as I described above in the following browsers:

Chrome for Linux 54.0.2840.71 (64-bit)
Chromium Version 55.0.2883.11 Ubuntu 16.04 (64-bit)
Opera for Linux 41.0.2353.46

It has the expected mapped value in Firefox for Ubuntu 49.0.2, though.

However, not using the key property works both in Blink-based browsers and in Firefox. (tested each browser with Hungarian and US keyboard layout)

Unfortunately I could not test it with any MS browser, neither with Safari.

By not using the key property, would you need to add extra keyboard mappings on top of what is already there in w3-keyname?

**Comment by marijnh** [comment]
Hm, that does seem to suggest a Chrome bug. I'll try to put some more time into this soon, to test what IE does. See also [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=585241) with similar lack of response.

**Comment by laszbalo** [comment]
Thank you for your help. I have found similar issues on the Chromium issue tracker, too.
Based on [this](https://bugs.chromium.org/p/chromium/issues/detail?id=633838), I believe they are aware of it.

**Comment by marijnh** [comment]
I've released a new version of `w3c-keyname` with [this patch](https://github.com/marijnh/w3c-keyname/commit/a8d1819f9c2c757628de7cc79e35013306c7e906). Could you check whether it solves your problem?

**Comment by laszbalo** [comment]
Yes, it had. Now it works across all browsers above. Thank you very much for your help.
