### ISSUE TITLE
Documentation for StateField.applyAction is erroneous

### ISSUE THREAD

**Issue by thomasWajs** [ProseMirror/prosemirror#488]
The documentation for [StateField.applyAction](http://prosemirror.net/ref.html#state.StateField.applyAction) specify the following parameters :
`applyAction(state: EditorState, action: Action) → T`

But when looking at the source code it seems that the parameters should rather be something like : 
`applyAction(action: Action, pluginState: T, state: EditorState) → T`

**Comment by marijnh** [comment]
You're right. This has already been fixed in the sources, and I'll put out a new release this week, at which point I'll rebuild the online docs.
