### ISSUE TITLE
On Mac, metaKey-Mouseclick for node selection has wrong key bindings

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#490]
On Mac, the keybindings don't get set to use `command` instead of `ctrl` for the metaKey-Mouseclick for node selection. Unfortunately on mac, ctrl-Click by default opens the context menu.

I looked at [the](https://github.com/ProseMirror/prosemirror-view/blob/master/src/input.js#L47) [code](https://github.com/ProseMirror/prosemirror-view/blob/master/src/capturekeys.js#L157), but could not figure out myself why it is failing

I tested with prosemiror 0.12 and with lastest safari and chrome browser

Also it would be great if the click modifier key could be customized, like the other key bindings typically used to bind to commands or menu actions

**Comment by marijnh** [comment]
I didn't get your entire description, but attached patch moves node selection to cmd-click on OS X, which seems like a good idea.

Being able to override this might be a good idea in the future, but I didn't implement that yet.

**Comment by marijnh** [comment]
Uh, I meant [this patch](https://github.com/ProseMirror/prosemirror-view/commit/9c8550278cc630e2a784b3823ff0a98195e19bd6) but attached it wrong
