### ISSUE TITLE
Dragging and dropping a selection leaves original copies behind

### ISSUE THREAD

**Issue by Chipairon** [ProseMirror/prosemirror#491]
How to reproduce:

1. In the demo editor (http://prosemirror.net/demo/basic.html), select a bunch of text.
2. Drag the selection to another location.
3. Drop the selection.

Observed behavior:

a. The selected text is copied to the destination (OK)
b. The original text selected is still on its original location. (**Should have been removed**).
c. In dev console, appears the exception `bundle_basic.js:11645 Uncaught TypeError: node.hasAttribute is not a function(…)` while dragging.

Observed in Google Chrome Version 54.0.2840.71 (64-bit) for Ubuntu and Firefox (X11; Ubuntu; Linux x86_64; rv:49.0)

Moving individual dinos in the dinos demo (http://prosemirror.net/demo/dino.html) is even weirder: the original gets removed sometimes and others it is not.

**Comment by marijnh** [comment]
Does attached patch solve the problem?

**Comment by marijnh** [comment]
Oh, and by that I mean patch https://github.com/ProseMirror/prosemirror-view/commit/6ddfc3d3309734313e34c7ad04af93eac92a43fb

**Comment by Chipairon** [comment]
It does solve the problem for the text selections :+1: 

The dinos keep missbehaving if doing the motion in one unique mouse click: click dino (holding click), drag, drop.
It works well if the dino is first selected (clicking on it), and then after wards "moving" by drag and drop (doing a second click to drag).. I hope to make sense :P 

A selection involving text and dino (a couple of letters before and after the image) is drag/dropped well to another paragraph. If moved in the same paragraph, nothing happens on drop.

**Comment by marijnh** [comment]
That was just a matter of adding the `draggable` flag to the dino node definition in the demo.
