### ISSUE TITLE
Missing f() function in updateDOMForProps()

### ISSUE THREAD

**Issue by darobin** [ProseMirror/prosemirror#492]
In `updateDOMForProps()`, for both the `label` and `class` options it calls `someProp()`. The second argument is a function that seems to expect to get a function `f` itself, but as can be seen in `someProp()` does not. See:

https://github.com/ProseMirror/prosemirror-view/blob/master/src/index.js#L115-L118

This causes the view to blow up if you try to set either of those options on it.

**Comment by marijnh** [comment]
What are you setting the props to?

**Comment by darobin** [comment]
Literally anything will trigger this issue: `someProps()` calls the function it is given with a string, not a function. Eg.

```
  class:      'rich-textarea',
  label:      'Rich text editor',
```

**Comment by marijnh** [comment]
The props are documented as taking functions that take a state and return a string.

**Comment by darobin** [comment]
Sorry, my bad, it didn't seem immediately obvious from staring at the docs.
