### ISSUE TITLE
Exporting moveForward and moveBackward

### ISSUE THREAD

**Issue by darobin** [ProseMirror/prosemirror#493]
`command` has useful functions `moveForward()` and `moveBackward()` that are used for forward and backward deletion, notably of words. I was wondering if it would make sense to export them. My use case is that I would like to select the current word that my (empty) selection is currently in, and those look like they would do the job.

I'm happy to provide a PR if you think it's a good idea.

**Comment by marijnh** [comment]
Yes, I guess those could be exported. If you create a PR, could you add a doc comment above them as well? Maybe include a note that they don't work reliably with many non-European scripts yet.

**Comment by marijnh** [comment]
This was done in https://github.com/ProseMirror/prosemirror-commands/commit/355e57e8421805a9ab3c411cc469ddb6054f7c08
