### ISSUE TITLE
exception in eventBelongsToView

### ISSUE THREAD

**Issue by ameliusg** [ProseMirror/prosemirror#495]
I'm getting an `Error` exception in the `eventBelongsToView` function when (accidentally) dragging a piece of selected text, in Chrome.

I think the code does not correctly check for a `TEXT_NODE` node, which does not have the `hasAttribute` function:

```
function eventBelongsToView(view, event) {
...
    if (!node || node.nodeType == 11 || (node.hasAttribute("tabindex") && node.getAttribute("tabindex") >= 0)
...
}
```

What seems to fix it is this:

```
function eventBelongsToView(view, event) {
...
    if (!node || node.nodeType == 11 || (node.hasAttribute && node.hasAttribute("tabindex") && node.getAttribute("tabindex") >= 0)
...
}
```

**Comment by marijnh** [comment]
This has already been fixed by [this patch](https://github.com/ProseMirror/prosemirror-view/commit/6ddfc3d3309734313e34c7ad04af93eac92a43fb)
