### ISSUE TITLE
Backward selection is broken

### ISSUE THREAD

**Issue by thomasWajs** [ProseMirror/prosemirror#496]
When making a selection ( with the mouse or shift + left arrow ) in the direction of the beggining of the document, into the same paragraph, if the selection grows bigger than one character, then the selection is cancelled (and the cursor stays at its current position ).

There is no issue with forward selection.

I would say this came along with the 0.14 release, but I'm not quite sure.

**Comment by marijnh** [comment]
> I would say this came along with the 0.14 release, but I'm not quite sure.

Yes, it did. I published prosemirror-view 0.14.2 a few hours ago which addresses this.
