### ISSUE TITLE
Backspace at beginning of content with empty paragraphs acts as forward-delete

### ISSUE THREAD

**Issue by rafbm** [ProseMirror/prosemirror#498]
When the cursor is at beginning of content and there are empty paragraphs, hitting Backspace will forward-delete the empty paragraphs, rather than noop.

Latest ProseMirror version. Very easy to reproduce on http://prosemirror.net/

![backspace](https://cloud.githubusercontent.com/assets/166943/20717361/39977e4e-b623-11e6-87a0-ffaff8229469.gif)

In this video, I hit Enter 4 times, then Backspace 4 times. The first 2 Backspaces work as expected, however the 2 last ones behave similar to Delete (or Fn+Backspace on Mac). They should have been noops.

**Comment by marijnh** [comment]
Yes, this is intentional, since there is no other way to delete such a paragraph when it's followed by a table or horizontal rule or similar. Is this causing issues for you?

**Comment by rafbm** [comment]
Can’t say it’s a major issue, but it’s definitely unexpected. We build [an email client](https://missiveapp.com/), and it’s easy to picture a situation where you want to start over your first sentence. You hold Backspace to delete it all, but holding it just a bit too long will delete some new lines that you expected to remain before your signature. See this example (sorry for the GIF artifact at the end, can’t fix it):

![backspace-2](https://cloud.githubusercontent.com/assets/166943/20719961/87eeb64a-b62b-11e6-87af-cd74eda56b96.gif)

You are right about the horizontal rule limitation, I just tested it:

![screen shot 2016-11-29 at 12 08 15](https://cloud.githubusercontent.com/assets/166943/20720291/996878ba-b62c-11e6-9304-9e16831ef1c9.png)

But it such a situation, shouldn’t Fn+Backspace (forward delete) be the way to delete the first empty paragraph, given your cursor is at the start? Deleting the horizontal rule is unexpected to me.

**Comment by marijnh** [comment]
Oh, indeed, press-and-holding backspace is a somewhat problematic situation.

> But in such a situation, shouldn’t Fn+Backspace (forward delete) be the way to delete the first empty paragraph, given your cursor is at the start?

What delete does, when at the end of a normal paragraph, is join the next paragraph with it. It never deletes the paragraph you are in, but rather acts on the thing coming after. As such, deleting the leaf block after seems perfectly sensible behavior.

**Comment by marijnh** [comment]
I've [reverted](https://github.com/ProseMirror/prosemirror-commands/commit/e52e717a34851d41b945593a7c27527314444504) the patch that introduced this behavior.
