### ISSUE TITLE
prosemirror-view 0.14.2 possible decoration issues

### ISSUE THREAD

**Issue by jonsutherland** [ProseMirror/prosemirror#499]
I'm trying to narrow down the issue but seems like changes introduced in 0.14 for decorations rendering somehow broke my NodeType decorations created with the static Decoration.node.

I only have one of these decorations added at a time and everything seems to be okay when viewing the browser DOM.  The class attribute appears on the correct node in the browser DOM.

The issue seems to be when I return a DecorationSet with the previous decorator removed and the new one added.  The new node gets the class attribute but the previous node doesn't lose it, despite the decorator not being in my set.  I've tried doing remove on the previous decoration set and also returning DecorationSet.create with only my new decorator added but the attribute doesn't get removed.

Seems like a bug in the new render optimizations was introduced in prosemirror-view commits between 0.13.2 and 0.14.0.

When I role back the view module to 0.13.2 my decorations look the same (same code) but the class attributes are removed as before when the decorations are removed/gone.

**Comment by marijnh** [comment]
Could you provide me with a more precise description of the steps you're taking? I tried to reproduce this, but couldn't. Ideally, you could try to add a failing test to `prosemirror-view/test/test-draw-decoration.js`.

**Comment by jonsutherland** [comment]
Absolutely.  Basically I have a custom action type that I send on action that has a transform to my decorator plugin via `view.props.onAction({type: 'foo'}).  I don't send an explicit command to remove the previous decoration,  As I'm re-adding my node, I search through the prev decorations with `DecorationSet` find method.  I find the previous single node decoration previously added (if it exists) and then remove it.  I find by using a custom 'type' option that I passed in with the node decoration.  Then I immediately after I add a new node decorator for the new range and return the new set.

I'll try to find where things are going wrong for me and add a test case.

Thanks

**Comment by jonsutherland** [comment]
OK forgive me for how messy this test patch is.  I will clean it up after I get some comments from you and if it's even worth keeping.  But I just did the bare minimum to demonstrate the problem I'm seeing.  

I added an ugly h1 around my content to show that it's a problem with depth it appears.  I could be doing something horribly wrong (with how I'm applying the state) but the test case at least shows the issue and it's representative of what I'm doing in my project.

The test case doesn't make a lot of logical sense but what I'm basically doing is sending my custom action every time the selection changes and I set the decorator to the first p, then the second.  The class 'cls' sticks around on my first node. 

The problem didn't appear until I added a level of depth with the surrounding h1.

[test-draw-node-deco.patch.zip](https://github.com/ProseMirror/prosemirror/files/623245/test-draw-node-deco.patch.zip)

**Comment by marijnh** [comment]
Patch https://github.com/ProseMirror/prosemirror-view/commit/d51fcbfccacbb07b375ad08ed0484258060e2570 should solve this. It was a mutating-shared-data bug in the way the old and new states are compared..

**Comment by rafbm** [comment]
Thanks so much! I had noticed a bug with my decorations too and ProseMirror/prosemirror-view@d51fcbf did fix it.

**Comment by jonsutherland** [comment]
Yes, thank you very much marijnh.  I forgot to say that the patch fixed things for me as well.

I also have the added benefit that I know how the test framework works now :)
