### ISSUE TITLE
Exceptions thrown when editing line containing decorations

### ISSUE THREAD

**Issue by rafbm** [ProseMirror/prosemirror#502]
To reproduce, I run the Lint demo and comment out the `mouseout` listener so that decorations remain drawn while I edit:

```javascript
// note.addEventListener("mouseout", event => {
//   if (!note.contains(event.relatedTarget)) clearProb(view, prob)
// })
```

An exception is thrown when the line containing the decoration is a blockquote and you Backspace at the beginning of the line to lift the blockquote:

![](https://d17oy1vhnax1f7.cloudfront.net/items/3l0z19422q1L0y2M303i/Screen%20Recording%202016-12-02%20at%2007.05%20AM.gif)

A different exception is thrown in “iOS mode” (edit `view/src/browser.js` to have `result.ios = true`) when typing a space at the beginning of a line that contains a decoration:

![](https://d17oy1vhnax1f7.cloudfront.net/items/1h0G0m2x2R2g2F1v2O3n/Screen%20Recording%202016-12-02%20at%2007.08%20AM.gif)

**Comment by rafbm** [comment]
Correction: the second exception described happens when you type _any character_ (not just Space) at beginning of a line that contains a decoration.

**Comment by marijnh** [comment]
Attached patch should help.
