### ISSUE TITLE
A NodeView's contentDOM property is ignored

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#503]
The [NodeView docs say](http://prosemirror.net/ref.html#view) that the NodeView interface supports a property contentDOM:

> The DOM node that should hold the node's content. Only meaningful if the node view also defines a dom property and if its node type is not a leaf node type. When this is present, ProseMirror will take care of rendering the node's children into it. When it is not present, the node view itself is responsible for rendering (or deciding not to render) its child nodes.

I've created a nodeView which is not a leaf, has a `dom` property and a `contentDOM` property which both contain DOM nodes. 

The rendering logic hits a TypeError primarily because a `CustomNodeViewDesc`'s contentDOM property is `undefined`.

**Comment by ericandrewlewis** [comment]
It works if I change [this line](https://github.com/ProseMirror/prosemirror-view/blob/741677580d91780e216cfaa33bca0c0dd6d41c6f/src/viewdesc.js#L378) from

```js
let dom = spec && spec.dom, contentDOM
```

to

```js
let dom = spec && spec.dom, contentDOM = spec && spec.contentDOM
```

**Comment by marijnh** [comment]
Thanks for noticing that! I've applied your patch in e47c3b6
