### ISSUE TITLE
Toggling marks duplicates next typed character

### ISSUE THREAD

**Issue by rafbm** [ProseMirror/prosemirror#504]
Following up on https://github.com/ProseMirror/prosemirror/issues/390#issuecomment-265439621. Latest fixes sure helped a lot! Thanks.

A new bug I’m seeing is when you enable or disable marks such as **bold** (either with `Cmd+B` or by clicking toolbar buttons), the next character you type will be inserted twice, once with the previous marks and once with the new ones:

![bold](https://cloud.githubusercontent.com/assets/166943/20974100/2132c5e2-bc69-11e6-9dbe-6c22f3b77ce9.gif)

**Comment by marijnh** [comment]
I think this has already been fixed by 1c5d9294f9fc2b787 and related patches. Could you verify? (You'll need to update prosemirror-state as well)

**Comment by rafbm** [comment]
Yes! All good with latest revision of all repos. 🤘
