### ISSUE TITLE
New drop-cursor plugin should use dropPos()

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#508]
First, I love that this is a plugin now!

With the new drop-cursor plugin, dragging leaf nodes will show a drop cursor in-between text blocks, even though the dragged node cannot and will not be placed there.

The old code use to call https://github.com/ProseMirror/prosemirror-view/blob/master/src/input.js#L404 to first get the `pos` of the actual drop location before calling `posAtCoords`.

**Comment by kapouer** [comment]
This probably explains why i'm seeing
```
TypeError: null is not an object (evaluating 'view.posAtCoords({left: event.clientX, top: event.clientY}).pos')
```
when doing a drag and drop in the prosemirror demo.

**Comment by marijnh** [comment]
@kapouer No, that's probably not related. What are you doing when this happens, and in which browser?

**Comment by marijnh** [comment]
So there are several issues with supporting this. There was, also in the old code, the problem that we can only get at the dragged content when it comes from inside the editor. This is probably some kind of security method, but dragover events don't have a working `dataTransfer`, so in the case of stuff dragged from the outside, we don't appear to be able to find out what's being dragged.

For content that comes from inside the editor, there's currently still no way, in a plugin, to know what's being dragged. I could expose that, though it feels a little like too much API surface, but then the next question is how the view and the drop cursor plugin would agree on where the drop will happen. Other plugins might even be overriding that.

So supporting this would require some ugly insight into the view's internals, _and_ still wouldn't be reliable. Thus, I opted to not have it for the time being.

**Comment by wes-r** [comment]
@marijnh I've seen the same error, it may at least get resolved with this fix.

Reproduction:
* Basic demo
* Start dragging some text
* Drag to bottom of editor and then out of editor
* See `Uncaught TypeError: Cannot read property 'pos' of null` error in console

Browser: Chrome 54.0.2840.98

**Comment by kapouer** [comment]
Using chromium 55.0.2883.75 or firefox 45.55.1 (from debian/sid) here, same way.

**Comment by marijnh** [comment]
Hm, no luck reproducing this. Which text are you dragging? Does the error happen on leaving the editor or on drop? Can you give me a stack trace?

**Comment by kapouer** [comment]
Drag outside by going above the bottom yellow tooltip ?

**Comment by wes-r** [comment]
Happens on leaving editor, not on drop.

Must be a problem with `posAtCoords` when coords are outside of editor.

The error (as @kapouer mentioned) is at this line in the drop-cursor plugin:
`view.posAtCoords({ left: event.clientX, top: event.clientY }).pos;`

**Comment by marijnh** [comment]
Right, doing that a few times caused it to happen. Attached patch should address it.

**Comment by marijnh** [comment]
With [fca45677d46](https://github.com/ProseMirror/prosemirror-dropcursor/commit/fca45677d4627b307200baa1614a16a62ef85059) this should be better.
