### ISSUE TITLE
Decorations & Node Views

### ISSUE THREAD

**Issue by ThariqS** [ProseMirror/prosemirror#510]
I'm currently unable to get NodeViews and decorations to work. Creating decorations on nodes doesn't update them, (even though the decoration set created is valid) and updating them in other ways doesn't seem to pass in the decorations as well.

Maybe this is because on this line: https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L570 it only passes innerDeco? For a node of size 1, is innerDeco ever going to be defined, or will all the node decorations be considered outer decorations and so no decorations will ever be passed into the view.

**Comment by marijnh** [comment]
Could you show a minimal version of the code you're writing, or add a failing test in prosemirror-view/test/test-draw-decoration.js? Decorations generally not working is not the case, since I'm using them in a bunch of different ways and there are tests for them.

**Comment by ThariqS** [comment]
I'm also using decorations in other places, the particular failing case is that node views do not receive a list of decorations. I haven't seen this working in any of the demos either.

The code is in a bunch of files but basically, I'm making a decoration like this and adding it to a decoration set: 
`const deco = Decoration.node(node.index , node.index + 1, {class: 'newclass'});`

In my nodeview, the update function logs decorations:
```
update(node, decorations) {
    console.log('decorations', decorations);
    console.log(decorations.find());
  }
```

This array is _always_ empty, regardless of decorations being applied. However, the `newclass` class is applied to the wrapper div. 

My Nodeview has a NodeSize of 1, so there's no way to create an 'inner' decoration. My hunch is that all decorations on Node Views are registered as outer decorations and never get passed into the nodeview.

**Comment by marijnh** [comment]
Yes, outer decorations (which node decorations are, at the level of the decorated node) are not passed to node views, but handled outside of them, and will result in the node being redrawn. What did you intend to do with it?

**Comment by ThariqS** [comment]
Ah, I was misunderstanding the point of passing decorations into nodeviews then. I guess you're intending it only to be used to style content of children within them?

I think while a class name being applied is fine for text and things like that, sometimes you want to decorate in a more careful fashion for node views. For example, if you want to cross something out, in text you can just apply a class that does a strike though, but doing that for a nodeview can look very weird. Allowing the view to decorate itself appropriately would be ideal.

**Comment by marijnh** [comment]
> Ah, I was misunderstanding the point of passing decorations into nodeviews then. I guess you're intending it only to be used to style content of children within them?

Right. But I just noticed even that doesn't really work at the moment, since the initial constructor _doesn't_ get them.

Making it fully possible for custom node views to work with decorations would involve exposing a lot of extra API surface to client code, and I'm not sure this is worth it.

But just passing them the outer array of node decorations and letting them inspect the options for those might be simple enough. What problem were you trying to solve with a decoration here?

**Comment by ThariqS** [comment]
I was more investigating it to figure out how to do some things and whether I could use decorations for them:
1) Passing in information that is required for the component but should not be in the document (in my opinion). For example, when giving an image a figure number, it should know what # image it is, but that in my opinion should not be something in the document itself but rather calculated on render.
2) Doing custom stylings for diffs, like I said, a cross-out looks good in text, but you have to apply the style more carefully when working with a nodeview.

**Comment by marijnh** [comment]
I've implemented what I proposed (see attached patch) -- node views now have access to their _outer_ decorations. [This test](https://github.com/ProseMirror/prosemirror-view/blob/master/test/test-nodeview.js#L78) is (crudely) doing the thing you describe, using decorations to pass information.

(Closing, but feel free to add comments if something isn't working right.)
