### ISSUE TITLE
Typing directly behind an inline node at the end of a paragraph does not insert any characters

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#513]
I tested this in Chrome 54 on Linux. I could not reproduce the issue in Firefox.

I have the following DOM structure:
![screenshot from 2016-12-13 15-57-40](https://cloud.githubusercontent.com/assets/152507/21145114/586cc98e-c14d-11e6-86e7-625f3f9ca5e6.png)
It is rendered like this:
![screenshot from 2016-12-13 15-58-06](https://cloud.githubusercontent.com/assets/152507/21145131/63c148a0-c14d-11e6-9188-1eaf83ab331e.png)

When I press for example `Space` or `a` I can see the character flashing, but it immediately disappears and the DOM stays the same.
As soon as the inline node is followed by some text or another node, typing behind it works fine.

**Comment by marijnh** [comment]
Err, that's https://github.com/ProseMirror/prosemirror-view/commit/bfbe2f8fe2690d964b2bf234b9500607e60fb52e and https://github.com/ProseMirror/prosemirror-view/commit/ced6a6200d05195996177df8984903c49dd18113

**Comment by kiejo** [comment]
I think the two commits are what introduced the issue as I can reproduce it with the current master, but I could not reproduce it with prosemirror-view 0.15.2.

**Comment by marijnh** [comment]
If I open up the demo and insert an image at the end of a paragraph, typing seems to still work fine

**Comment by kiejo** [comment]
You're right, using an image at the end of a paragraph works fine. I further simplified my node and reduced it to the following:
```javascript
{
  inline: true,
  group: 'inline',
  toDOM(node) {
    return ['span', 'test'];
  }
}
```

As soon as I replace the `span` with an `img` node, everything works fine. It looks like using a `span` is what causes the issue.
It also causes the whole node to get selected when clicking behind the node (which is an issue we had in a very early version of ProseMirror).

**Comment by marijnh** [comment]
Probably the cursor is landing in the wrong place and the text falls between the cracks. I'll look into this later

**Comment by marijnh** [comment]
Could you retry with the current prosemirror-view code?

**Comment by kiejo** [comment]
Nice, typing behind the node now works!
But I noticed a few other issues with the cursor behavior around this kind of node. I'll open a different issue for these.
