### ISSUE TITLE
Unexpected cursor behavior around inline span leaf nodes

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#514]
I tested this in Chrome 54 on Linux with the current master. I could only reproduce one of the issues in Firefox. I suspect that #513 is somehow related to this whole issue.

To reproduce this I changed the `toDOM` method of the `image` node in the demo to the following:
```javascript
toDOM(node) { return ["span", {style: 'style: background-color: #90EE90; color: black'}, 'text'] }
```
Given the following DOM structure:
![screenshot from 2016-12-14 09-24-08](https://cloud.githubusercontent.com/assets/152507/21174913/13b33efc-c1e0-11e6-9c0e-1216c98148ae.png)
Which gets rendered like this:
![screenshot from 2016-12-14 09-27-21](https://cloud.githubusercontent.com/assets/152507/21174908/0e23b85e-c1e0-11e6-8c5e-808559739758.png)

I noticed the following issues:

* Place the cursor behind the green leaf node and press `Pos1` -> Cursor jumps to the start of the document instead of to the start of the line
* Place the cursor somewhere in the word "hello" and press `DownArrow` -> Cursor jumps to the end of the line instead of to the paragraph below
* Place the cursor behind the green leaf node and press `RightArrow` -> Cursor does not move instead of moving to the start of the paragraph below
* Place the cursor at the start of the last paragraph and press `LeftArrow` -> Cursor jumps before the green leaf node instead of behind it (also reproducible in Firefox, but additionally the cursor disappears)
* Place the cursor directly before the green leaf node and type something -> Cursor stays at the same position while text is correctly inserted
* Place the cursor directly before the green leaf node and press `Backspace` -> Cursor stays at the same position while text is correctly deleted

**Comment by marijnh** [comment]
I think I've fixed the 1st and 2nd issue by putting a BR node after the uneditable node (https://github.com/ProseMirror/prosemirror-view/commit/0971429bd55266807e566d02f8ec3b096961283a).

I'm not seeing the 3rd, 5th, and 6th issue on Firefox 52 Linux. Though I do see an issue where the cursor is sometimes invisible when placed before the uneditable node. Interestingly, the same issue occurs in Chrome.

I can reproduce the 4th issue. No idea how to fix it.

It seems that

 1. having inline islands of uneditable content is really poorly supported, and confuses the browser's cursor-handling code, but

 2. leaving the rendered representation of leaf nodes editable is also really messy, since being 100% sure the cursor doesn't end up in them and the user doesn't type or make some other edit inside of them is hard

I guess I'll keep researching and hopefully I can get a better handle of the problem at some point.

**Comment by kiejo** [comment]
> I think I've fixed the 1st and 2nd issue

I can confirm that the first two issues are fixed in the latest master :)

> I'm not seeing the 3rd, 5th, and 6th issue on Firefox 52 Linux.

I could only reproduce these issues on Chrome. Firefox is working fine except for the 4th issue. Have you tried reproducing these issues in Chrome?

> leaving the rendered representation of leaf nodes editable is also really messy

Hopefully we'll find another way around theses issues as I agree that this option would be messy and catching 100% of the cases will be very hard.

**Comment by marijnh** [comment]
Ah, I had misread in which browser you were testing. 5 and 6 happen for me on Chrome. 3 still doesn't.

**Comment by marijnh** [comment]
I could suppress 5 and 6 by setting the span to `display: inline-block`. But that can be inconvenient (and have an effect on the way the node is rendered), so it's not ideal.

**Comment by kiejo** [comment]
Your patch seems to have fixed issue 3!
So to sum it up:

* 4 happens in both Chrome and Firefox
* 5 and 6 happen in Chrome

**Comment by kiejo** [comment]
> I could suppress 5 and 6 by setting the span to display: inline-block.

Nice, this solves the problem for the use cases that we have! If there's no other way around this, we could add it to the documentation. Of course finding a real fix would be much nicer.

**Comment by marijnh** [comment]
That last attached patch automatically sets inline leaf nodes to have `display: inline-block` to work around this error-prone behavior. That's rather ugly, but likely better than the frozen-cursor behavior.

**Comment by adrianheine** [comment]
Since you can reproduce this in a plain contenteditable setup, could you open a bug in chrome's bug tracker?

**Comment by keelii** [comment]
@adrianheine yes~ I just open a issue to chrome.

[Cursor can not move down When a inline-block element placed in a contenteditable element](https://bugs.chromium.org/p/chromium/issues/detail?id=896108&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by kcwijaya** [comment]
@keelii  were you able to find a solution to this?
