### ISSUE TITLE
Pressing CMD+~ should allow switching between open browser windows on macOS

### ISSUE THREAD

**Issue by bjoernm** [ProseMirror/prosemirror#515]
On macOS, pressing CMD+~ normally switches between open windows of the same applications.

On the Prosemirror homepage, pressing CDM+` toggles the code font, as expected: [ref](https://github.com/ProseMirror/prosemirror-example-setup/blob/master/src/keymap.js#L51)

However, pressing CDM+~ has the same effect and toggles the code font the same way as CMD+` does. This prevents the normal behavior of switching the application windows.

**Comment by marijnh** [comment]
I can't get Cmd-~ to do anything on my Mac. You do this by pressing Cmd-Shift-\`, right? The issue might be that I have a German keyboard mapped to a US one, but I can _type_ tildes just fine. Cmd-~ doesn't switch windows and in fact doesn't produce a keydown event at all.

On Linux, Ctrl-~ is correctly mapped to the `"~"` key name, and doesn't toggle code font, so whatever is going on, I can't reproduce the issue there either.

**Comment by bjoernm** [comment]
Thank you for the quick answer, that resolved the issue. It was actually a modified US keyboard layout on a German keyboard that was causing the problem.
