### ISSUE TITLE
Maximum call stack size exceeded in coordsAtPos (caused by Bublé upgrade)

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#516]
I'm getting the following error on the latest master:
```
Uncaught RangeError: Maximum call stack size exceeded
coordsAtPos@index.js?7a51:182
```

It looks like line 168 in `view/index.js`:
```javascript
coordsAtPos(pos) { return coordsAtPos(this, pos) }
```
gets compiled to:
```javascript
EditorView.prototype.coordsAtPos = function coordsAtPos (pos) { return coordsAtPos(this, pos) };
```

This leads to an endless recursion, which causes the call stack size error.

I saw that the Bublé dependency was upgraded, which is the source of the error. With the older Bublé version, the same line got compiled to:
```javascript
EditorView.prototype.coordsAtPos = function coordsAtPos$1 (pos) { return coordsAtPos(this, pos) };
```
This works fine as we don't have the endless recursion.

**Comment by marijnh** [comment]
I've already fixed [the regression](https://gitlab.com/Rich-Harris/buble/issues/166) in Bublé, but I've pushed a [patch](https://github.com/ProseMirror/prosemirror-view/commit/5397784533aee47a706e0649a6cbb653732b0570) to work around this in the meantime.
