### ISSUE TITLE
ProseMirror should keep marks of backspace delete character.

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#517]
By default, ProseMirror should set active marks to be that of a backspace deleted character.

Many editors don't do this and I always find it annoying. If I start writing **foo** and realize I want to type "bar", I will backspace delete "foo" and then type "bar", but then **bold** is no longer enabled.

**Comment by wes-r** [comment]
Additionally, when highlighting text we currently treat active marks as the union of the marks within the selection. Deleting this selection should cause the active marks to remain. This solves the problem of highlighting the "**foo**" from the above example and trying to type "**bar**" (but currently getting "bar" without bold).

**Comment by marijnh** [comment]
The new [transaction system](https://discuss.prosemirror.net/t/discussion-the-limits-of-actions-and-reducers/551/12?u=marijn) made this relatively easy to implement. See attached patches.
