### ISSUE TITLE
Constant re-renderering with Grammarly

### ISSUE THREAD

**Issue by frederik** [ProseMirror/prosemirror#520]
There are currently some issues when using Grammarly. As it seems to become more and more popular, it might be favorable if ProseMirror worked with Grammarly.

**Actual behavior**

On ProseMirror 0.15 and up the Grammarly plugin seems to trigger a constant re-rendering (or style re-calculation) even if the cursor is still (see gif below) (before 0.15 it would not activate at all).

![prosemirror_grammarly_flicker](https://cloud.githubusercontent.com/assets/3445/21522479/2158c32a-cd06-11e6-83d9-a14c0cc48cdd.gif)

**Expected behavior**
I'd expect the Grammarly decorations either to be deactivated completely or work as in other forms.

I am unsure whether this is actually a bug in Grammarly itself but it is odd that it feels it needs to re-render so often. I'd be happy to contact the Grammarly team as well if we have some indicators as of why this is happening.

**How to reproduce**
Install the Plugin from grammarly.com (in either browser), go to prosemirror.net and set the focus within the text field.

**Environment**

ProseMirror on web-site (I suppose > 0.15)
Occurs with the latest Chrome on Mac Version 55.0.2883.95 (64-bit), Safari Version 10.0.1 (12602.2.14.0.7), and Firefox 50.1.0 when the browser plugin from www.grammarly.com (for each browser respectively) is installed.

p.s.: The Grammarly team is aware that it currently does not work with ProseMirror (see https://github.com/grammarly/contenteditable). They are probably open to changes if those should be needed.

**Comment by marijnh** [comment]
This is how ProseMirror responds to something messing with its DOM -- it assumes something is being edited, re-parses the modified part of the DOM, and then restores it to its current understanding of the document.

So yes, the problem here is Grammaly assuming it has permission to mess with our DOM.

**Comment by marijnh** [comment]
It might be worth looking into hard-coding exceptions for the kind of DOM changes that popular software like Grammarly makes. In any case, I'm going to leave this open, as it is an issue I'm sure people will continue to run into.

> p.s: Congratulations. ProseMirror is still at 25 fps even with all the interference ;)

Nice! Incremental updating works.

**Comment by frederik** [comment]
Grammarly has now changed the way (at least the Chrome plugin) works. It now only adds a button on the bottom of the editable container, not adding markup to the text itself but opening a modal dialogue. I need to confirm with other browsers but it's looking promising.

**Comment by frederik** [comment]
I ended up disabling Grammarly directly on the content editable using

```
view.dom.setAttribute('data-gramm', 'false');
```

This works although it is sad, that our users will now not be able to use Grammarly.

**Comment by marijnh** [comment]
I'm going to close this, despite it not being solved, since the problem clearly lies with other software, and there doesn't seem to be much ProseMirror can do about it.
