### ISSUE TITLE
error when click on widget decoration at end of line 

### ISSUE THREAD

**Issue by liucougar** [ProseMirror/prosemirror#521]
create a widget decoration at end of a line: `<span class="myclass"></span>`
the css is: `.myclass:before{content:"A";}`
click on the widget in editor, the following error is thrown:
`targetNode is null` @254 in file view/src/input:
`this.mightDrag = (targetNode.type.spec.draggable || targetNode == view.state.selection.node) ? {node: targetNode, pos: targetPos} : null`

**Comment by marijnh** [comment]
Should be fixed now (though note that cursor behavior around :before/:after content tends to be quite broken in browsers, so the resulting user experience might still not be great).
