### ISSUE TITLE
view.focus() causes unwanted scroll to top of view.content

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#523]
Tested in Chrome 55

Calling `view.focus()` will cause the window to scroll to top of `view.content`. I believe this was introduced in 0.17.0 with https://github.com/ProseMirror/prosemirror-view/commit/78829d5b32292423251e6559b6c508effcb261ee. Previously selections were made before the `content.focus()` call, which meant the browser would ensure the current selection is in view (and no scroll would be needed).

To Reproduce:

1. Go to http://prosemirror.net/demo/basic.html
2. Enter a bunch of new lines at bottom so that page scrolls and top of content is hidden
3. Insert a new link at bottom (should trigger a `view.focus()`) - Alternatively enter `view.focus()` in dev console.
4. See browser scroll to top of container.

**Comment by marijnh** [comment]
I did an experiment with not setting a  selection at all when the was a node selection, which prompted that change, but that didn't really work, so I should have reverted this too. Done in attached patch.
