### ISSUE TITLE
Odd bug with positions after inserting new node

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#524]
Tested in chrome 55

Cursor position after inserting a **heading 1** on first line:
![screen shot 2017-01-07 at 2 53 32 pm](https://cloud.githubusercontent.com/assets/1568246/21744721/24700a56-d4e9-11e6-9090-490fe09ada14.png)

The positions of the cursor on both empty lines are 1 (equal!). I believe this was introduced with 0.17 (not positive though).

To reproduce:
* Go to http://prosemirror.net/demo/basic.html
* Add two new empty lines at top
* Place cursor on top line and set type to heading 1
* Notice the cursor moved to line below (and not line of heading 1)
* In console check `view.state.selection.head` on both lines and see position is 1 for both lines!

Any typing on either of these lines seems to resolve the issue. Additionally, it seems like an empty line with an empty line below is required to trigger the bug, although I definitely ran into the same issue when trying to do a `replaceWith`, that for some reason a `timeout` on my dispatch resolved.

**Comment by marijnh** [comment]
The selection drawing code ended up incorrectly concluding that the DOM selection was already up to date in this case. Attached patch fixes that.
