### ISSUE TITLE
handler function never given text node

### ISSUE THREAD

**Issue by bloff** [ProseMirror/prosemirror#525]
I have upgraded my project to prosemirror v17 from v15, and came to the following problem.

I have a document containing the text:

> first-word **bold-word** third-word

Which serializes to the following JSON:

```
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "text": "first-word "
        },
        {
          "type": "text",
          "marks": [
            {
              "type": "strong"
            }
          ],
          "text": "bold-word"
        },
        {
          "type": "text",
          "text": " third-word"
        }
      ]
    }
  ]
}
```

I have installed a handleClickOn prop. Here is the problem: whenever I click any of the words, the *node* argument given to the handler function is the parent node (of type "paragraph"), instead of the corresponding text node (i.e. the leaves).

In v15, I would get the text node instead, and I was relying on this behavior (I defined a special node-type, called 'wikilink', and wanted to control what happens when that gets clicked). I suspected this to be a bug, but maybe I should be doing something else to get the actual leaf that was clicked?

**Comment by bloff** [comment]
I've realized that, as a workaround, I can get the child node by calling `node.nodeAt(pos - nodePos)` where `pos`, `node` and `nodePos` are the handler's 2nd to 4th arguments.

**Comment by bloff** [comment]
Another issue which may be related: within the `handleClickOn(view, pos, node, nodePos, event direct)` handler prop, at some point I store the `pos` variable. Then sometime later, before changing the document in any way, I do: `state.doc.resolve(pos)`.

I get an exception `text-buffer.js:871 Uncaught RangeError: Position 292 out of range`

This is highly unintuitive.

Sorry if I'm piling up weird bugs, should I be doing this on the forum?

**Comment by marijnh** [comment]
The handlers being called with text nodes was a bug in 0.15. The paragraph node is the first 'real' containing node, since text nodes aren't stable things (they contain arbitrary sequences of text with the same style, but they don't have an identity in the document).

Could you create a demo of the out of range issue and open a new issue? That error occurs when you try to resolve a position that's either nonsense (negative, not a number, etc) or higher than `doc.content.size`. If it is valid for a document at one time, it remains valid for that document at all times.

**Comment by bloff** [comment]
The problem was on my side: I was referring to a "state" that was not the current version (and its content.size was indeed too small).

Sorry, not used to working with persistent data structures.

**Comment by styts** [comment]
Thanks, @bloff for pointing out how to get the target node with `node.nodeAt(pos - nodePos - 1)`, I think this should be mentioned in the docs. Likely users want the direct text node and not the paragraph surrounding it.
