### ISSUE TITLE
Unable to run tests for prosemirror-schema-list

### ISSUE THREAD

**Issue by theefer** [ProseMirror/prosemirror#526]
The `test/test-commands` file in the `prosemirror-schema-list` repo requires `"prosemirror-model/test/build"`, however the `prosemirror-model` npm package doesn't include the `test` directory.

Presumably I might be able to work around this issue by npm linking a git clone of the `prosemirror-model` repository. Is that intended behaviour though?

**Comment by marijnh** [comment]
That's a good point. I should probably factor the reusable utilities used by the tests into a separate package to work around it. (But ugh, even more packages.)

**Comment by marijnh** [comment]
Done in https://github.com/prosemirror/prosemirror-test-builder
