### ISSUE TITLE
Exception thrown when joining list items with a simplified list schema.

### ISSUE THREAD

**Issue by theefer** [ProseMirror/prosemirror#527]
As part of our content model, we use a simplified list schema with a `list_item` content definition of `"paragraph (ordered_list|bullet_list)?"` (i.e. lists can only include text paragraph and optionally another sublist, no other blocks).

With that schema, trying to join two list items by pressing `Backspace` (resp. `Delete`) at the beginning (resp. end) of a list item causes errors to be thrown in the `clearNonMatching` transform, which attempts to delete some nodes. The error thrown is a `TransformError` with `"Invalid content for node list_item"`, which happens when attempting to step through the `ReplaceStep` (with an empty slice).

My understanding is that the `clearNonMatching` should result in a no-op in that case, and the subsequent `join` transform should join up the two list items. However even commenting out the `clearNonMatching` transform results in another error thrown by the `join` transform.

Any help on how to solve this would be very appreciated!

See also related fix for splitting items in that schema submitted at https://github.com/ProseMirror/prosemirror-schema-list/pull/1.

**Comment by marijnh** [comment]
I can't reproduce this with the current code. Could you test whether it's still happening?
