### ISSUE TITLE
Backspace in empty code block throws error

### ISSUE THREAD

**Issue by emilschutte** [ProseMirror/prosemirror#528]
Thanks for ProseMirror, it's been great to work with.

I'm getting an error when hitting backspace in an empty code block.  You can see it on the basic demo on the website:

![prosemirror-backspace-800px](https://cloud.githubusercontent.com/assets/649549/21914584/13ce064a-d8e9-11e6-8f6c-3cc135f207f4.gif)

It seems like the \<code\> element is getting removed and ProseMirror is holding a reference to it that it tries to use when setting the selection.

Can you offer any tips on the best approach to fixing this?

Thanks!

(Chrome 55.0.2883.95 Mac, ProseMirror 0.17.1)

**Comment by marijnh** [comment]
This was an untested corner case that ended up exposing a number of mistakes in the code. Attached patch fixes them. I'll do a patch release later today.

**Comment by emilschutte** [comment]
Awesome, thank you!
