### ISSUE TITLE
Document NodeType constructor

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#529]
The [constructor for NodeType](https://github.com/ProseMirror/prosemirror-model/blob/master/src/schema.js#L51) currently doesn't have a getdocs type comment. It would be useful to have this to support automated tooling.

**Comment by marijnh** [comment]
This is intentional -- you're not supposed to ever call it directly. The `Schema` constructor will create your node and mark type instances for you.
