### ISSUE TITLE
InputRules getdocs description on same line as type

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#530]
In https://github.com/ProseMirror/prosemirror-inputrules/blob/master/src/rules.js#L3 the description starts immediately after the type (as opposed to being on the next line).

It's not clear from https://github.com/marijnh/getdocs whether this is valid or not, but at least for consistency it would be great to move the description down to the next line.

**Comment by marijnh** [comment]
It's valid, and I do it in a bunch of places when the description and type are short. It's like brace-less one-liners, some people don't like them, but _I_ do.

**Comment by bradleyayers** [comment]
Thanks for the clarification 👍
