### ISSUE TITLE
dropcursor: failed condition Cannot read property 'pos' of null

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#531]
This is on chrome, when i drag a Node somewhat "away from the text editor":
https://github.com/ProseMirror/prosemirror-dropcursor/blob/master/src/dropcursor.js#L39
pos is null so it fails.

**Comment by kapouer** [comment]
Maybe there is a deeper issue at hand here, since i don't actually see a dropcursor on the prosemirror website demo.

**Comment by marijnh** [comment]
That was not a very deep issue -- I had forgotten a pair of parentheses.

**Comment by kapouer** [comment]
Sorry for my approximative english: i meant further, not deeper, see
https://github.com/ProseMirror/prosemirror/issues/533
