### ISSUE TITLE
NodeView update not called when decorations are updated

### ISSUE THREAD

**Issue by ThariqS** [ProseMirror/prosemirror#534]
The new decoration functionality works well as fixed in #510 , but the update function per nodeview doesn't seem to be called when new decorations are added to that node. Instead it's only called when the node is otherwise updated or selected.

This makes it hard to use decorations reliably for nodeviews because the decorations are out of sync.

**Comment by marijnh** [comment]
Are you sure you're adding the decorations correctly? I added a test (in attached patch) for this which seems to be passing.

**Comment by ThariqS** [comment]
Yes, when I click on the node or otherwise update it, the update function fires with the proper decorations. Otherwise it never fires. Also, the wrapping dom element is properly styled with the decoration class names. I am also using decoration nodes.

**Comment by ThariqS** [comment]
Ohh reading that test, the way decorations need to be applied seems to be changed in 0.17? It needs to do an update meta decorations like `view.dispatch(view.state.tr.setMeta("updateDecorations", {add, remove}))`?

My bad, will try it and fix. The 0.17 change did have a bigger surface area than I was expecting.

**Comment by marijnh** [comment]
Plugins can compute or track decorations any way they want -- the plugin I'm using to test decorations expects messages like that, but you're not using that, so you'll need to do something else.

**Comment by ThariqS** [comment]
Ah okay. I'm currently creating a decoration set from scratch on every transformation, instead of adding or removing to the same set. Will try that and see if it works.

**Comment by ThariqS** [comment]
Okay, I need to look over the way that decorations are done. My current approach is to create a new decoration set on each transformation and not explicitly call add or remove. Is add/remove the thing that fires the nodeview decorations update?

**Comment by ThariqS** [comment]
From reading the code, it seems like the update function is only fired if the node is marked as dirty or has a different markup. It seems like nodes are only marked as dirty due to dom mutations which a decoration will not fire and markups do not take decorations into account. 

Maybe there's something about the test environment that causes it to mark the node as dirty?

**Comment by marijnh** [comment]
Which code are you reading, precisely? And no, the test environment isn't marking nodes dirty.

**Comment by ThariqS** [comment]
It turns out I wasn't making use of the initial decorations passed with the nodeview function, once I do that everything works! Sorry about the confusion.
