### ISSUE TITLE
viewDecorations returns undocumented DecorationGroup

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#536]
`viewDecorations` returns a `DecorationGroup`, but that class is not documented, is that intentional?

A `// ::-` would be useful on `DecorationGroup`. 

https://github.com/ProseMirror/prosemirror-view/blob/master/src/decoration.js#L626

**Comment by marijnh** [comment]
Note that this type isn't public, so it shouldn't appear in the docs. But a comment is a good idea.

**Comment by bradleyayers** [comment]
Ah, good point — I hadn't noticed it wasn't exported from index.
