### ISSUE TITLE
coordsAtPos documented as taking a ProseMirror

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#537]
I believe this should be an `EditorView` instead? https://github.com/ProseMirror/prosemirror-view/blob/master/src/domcoords.js#L130

**Comment by marijnh** [comment]
Same for `endOfTextblockVertical`. I guess having a real typechecker look at these would be nice. (If I had time, I'd write a getdocs-to-flow converter, but alas, I don't.)

**Comment by bradleyayers** [comment]
I've written a getdocs-to-typescript, which is how I found these 😄

**Comment by marijnh** [comment]
Really? That's great. Does it produce code that we can feed to the TS compiler to get useful type errors yet?

**Comment by bradleyayers** [comment]
At the moment it just generates companion .d.ts declaration files for a directory of .js files. The goal was to be able to (as a consumer of ProseMirror) have type declarations to make day-to-day dev and upgrades easier. It wasn't a goal to type check ProseMirror's code itself.

The workflow at the moment is still quite clunky — clone each prosemirror-foo repo, run the compiler, and wire up imports between files. At the moment I'm spiking upgrading from 0.10 to 0.17.

There's still some rough edges to smooth out.

**Comment by adrianheine** [comment]
Nice! I doubt it's of much use now, but I did something quite similar with flow and typescript as target: https://github.com/adrianheine/prosemirror/tree/frain
