### ISSUE TITLE
no width and height attributes in Image default schema

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#54]
I am talking about Image definition in model/defaultscheme.js

    Image.attributes = {
      src: new Attribute,
      title: new Attribute(""),
      alt: new Attribute("")
    }

Is there a reason those attributes are omitted ? 

what I want to do is some simple manipulation of certain elements as shown in the linter example (where an `alt` attribute gets added to `img` tags). So for having access to the `width` and `height`, do  I have to extend myself the schema as shown in the dino example ?

**Comment by marijnh** [comment]
Yes, there is a reason -- they aren't in Markdown, and people might want to keep width/height out of their documents.

The idea is for schema extensions to add these properties, along with serializer/parser hooks, and the UI elements needed to let users manipulate them. I intend to include such an extension in the distribution, but haven't gotten around to it yet (I'm currently designing the way UI elements and schema extensions interact)

**Comment by forresto** [comment]
I'd argue that editing the image would go against WYSIWYM editing & responsive design.

**Comment by marijnh** [comment]
I am not going to prescribe a one-size-fits all interface and document node for images. The default scheme won't have resizeable images, but it should be easy to get them. Now that we have node selection, the next step is to allow nodes to decorate themselves with additional controls when selected, which could be used to provide resize handles on images.

**Comment by forresto** [comment]
That will be very helpful.

**Comment by marijnh** [comment]
The issue for supporting UI decoration on nodes is #132. The default schema is going to remain minimal, with the idea that users will almost always define their own schema, and hopefully someone will publish a module that makes resizeable images easy.
