### ISSUE TITLE
Cannot use ⌘+` as key in keymap

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#540]
Keymap's `handleKeyDown` doesn't seem to fire for ⌘+` (backtick). I can see events firing for backtick with no ⌘ and I can see events firing for ⌘ and things like ⌘B.

Tried this in Chrome V55 on a mac.

**Comment by marijnh** [comment]
That appears to be an issue with Browsers on OS X, more than with ProseMirror. There's simply no key events fired for this, at least that's what I found [the last time](https://github.com/ProseMirror/prosemirror/issues/515) I looked into this.

**Comment by wes-r** [comment]
Relevant discussion: https://discuss.prosemirror.net/t/mod-key-binding-does-not-work-in-chrome-and-firefox-on-mac/561
