### ISSUE TITLE
Long contiguous lines in Firefox don't wrap

### ISSUE THREAD

**Issue by KaySackey** [ProseMirror/prosemirror#542]
If you enter a very long line into a Prosemirror instance, the default CSS will not force the text to wrap.

It technically *should*, but FF has a long history of bugs when it comes to implementing pre-wrap.

Example: Enteirng 
```vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv```

into the demo box in Firefox will result in that single line exceeding the box bound. It's not the same in Chrome/Safari.

The solution seems to be adding word-wrap: break-word to the Prosemirror CSS class as so

```
.ProseMirror {
    white-space: pre-wrap;
    word-wrap: break-word;
}
```

It may be useful to do that by default, so people using the default styles as a guide don't get bitten.

This solution was [suggested by Mozilla devs.](https://hacks.mozilla.org/2009/06/word-wrap/)

**Comment by marijnh** [comment]
Confirmed. I had a similar workaround in CodeMirror. Attached patch adds the CSS property.
