### ISSUE TITLE
Very broken interactions on IE11

### ISSUE THREAD

**Issue by davidye** [ProseMirror/prosemirror#544]
I'm playing with the base editor at prosemirror.net and I'm seeing very strange interactions on IE11 and windows.

Hitting enter will always insert new line at the very top of the window - no matter where cursor is. Double clicking doesn't seem to select properly, etc.

Looking at the console I see: SCRIPT438: Object doesn't support property or method 'contains' at this line:

https://github.com/ProseMirror/prosemirror-view/blob/ba912cca5a5e04f77c0bb4a886494892c12669d7/src/viewdesc.js#L201

I'm not sure if this is the only problem?

**Comment by thomasWajs** [comment]
We're experiencing the same issue here.

Selection with the cursor doesn't work either, only one character or none at all are selected while dragging the mouse.

**Comment by marijnh** [comment]
The error mentioned should  be addressed with attached patches. I'm still seeing other flaky behavior, which I'm looking into.

**Comment by marijnh** [comment]
> Selection with the cursor doesn't work either, only one character or none at all are selected while dragging the mouse.

That's another issue -- see [this thread](https://discuss.prosemirror.net/t/drag-select-does-not-work-in-ie-11/590/8). Try to open new issues, rather than adding notes to different issues, if you want me to be able to track things.

**Comment by thomasWajs** [comment]
Sorry, I thought they were related because 

> Double clicking doesn't seem to select properly, etc.

Also, I don't check on the discussion group for bug reports, because well,

> Welcome to discuss.ProseMirror
> For bug reports, use the issue tracker instead.

**Comment by marijnh** [comment]
Yeah, I wasn't saying you should have known about that thread, or scolding you. Just remarking that I _know_ I'll forget about things when they are buried in a comment on some issue.

**Comment by kbrownlees** [comment]
Any chance of getting the change to -menu released (https://github.com/ProseMirror/prosemirror-menu/commit/109cd68d32bfdd5fddc04359dd15c6c7b80a126a)?

**Comment by marijnh** [comment]
Done (0.17.1)
