### ISSUE TITLE
possible problem with createHTMLDocument and IE11 on windows 7

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#548]
Hi,

some (latest) version of IE11 for windows 7 can crash when
`document.implementation.createHTMLDocument` is called several times.
For example
https://github.com/ProseMirror/prosemirror-view/blob/6cdf4c50ac6d24b985aa3411eb203ee38959ba1c/src/clipboard.js#L145
calls it.
I tried to address the problem in https://github.com/kapouer/create-html-document-polyfill (browser tests will be available soon). I think it's worth knowing this :)

**Comment by marijnh** [comment]
> can crash when document.implementation.createHTMLDocument is called several times.

ProseMirror will only call it once and cache the result. Does that help? Did you see the problem occur with ProseMirror?

**Comment by kapouer** [comment]
There are actually two bugs:
- createHTMLDocument (and createDocumentFragment too) throws an exception, even the first time it's called
- createHTMLDocument crashes to whole page when called repeatedly

I suppose the best to do is *nothing* right now, and just add that knowledge for a later bug report.

**Comment by marijnh** [comment]
Ughhh. Is this the browser all IE7 users are getting when the upgrade now? We could fall back to the (less secure) alternative of using the main (non-detached) document when `createHTMLDocument` throws.

**Comment by kapouer** [comment]
That's somewhat what my polyfill do at
https://github.com/kapouer/create-html-document-polyfill/blob/master/index.js#L15
luckily, on that browser, cloning `document` works and gives a detached clone.
However, on IE10, doing the same will make access to some cloned document properties throw an error,
so the "fix" is only valid where it's needed.

**Comment by marijnh** [comment]
Closing this until the issue is observed in the wild
