### ISSUE TITLE
Editing blocked when starting with a headline

### ISSUE THREAD

**Issue by splitbrain** [ProseMirror/prosemirror#549]
When the editor contains nothing but a headline, there is no way to add additional text outside the headline. Trying to hit enter will do nothing, because the headline does not accept paragraphs obviously. The only way around it is to remove the headline formatting, create a new paragraph and then reapply the headline formatting.

Steps to reproduce:

1. go to http://prosemirror.net/demo/basic.html
2. delete all text except the first line with the headline
3. try to enter a new paragraph

I guess what is needed is some way to specify allowed "follow up" nodes which cancel the current node and add a new node?

**Comment by marijnh** [comment]
I can't reproduce this. Which browser and browser version are you using?

**Comment by splitbrain** [comment]
Hmm that's very weird. I can not reproduce it today either. Must have been something wrong in my browser (I had the problem in my local instance, then verified it on the demo). Today it works again.
