### ISSUE TITLE
Floating tooltip position

### ISSUE THREAD

**Issue by salzhrani** [ProseMirror/prosemirror#55]
if the selection happens in some edges of the editable div the floating tooltip appears on the other side.

To reproduce go to (prosemirror)[http://prosemirror.net/] page and select the most bottom left word "control", the tooltip menu would appear in the far right side of the div.

**Comment by marijnh** [comment]
Ugggh. Good catch. `getBoundingClientRect` returns some insane results for wrapped inline nodes. I'm already handling a bunch of special cases, I'll look into this later and add another one.
