### ISSUE TITLE
Editing text with decorations fails in IE 11 (Object doesn't support property or method 'contains')

### ISSUE THREAD

**Issue by frederik** [ProseMirror/prosemirror#550]
There seems to be an issue with Text nodes in IE 11, since they do not have a contains property. This crashes here: https://github.com/ProseMirror/prosemirror-view/blob/ee3876125c20e481016447a62224625cb6ae066d/src/viewdesc.js#L201

The issue occurred when there was DOM that contained a decoration (e.g. a span followed by some more text). It also happens in the [basic demo](http://prosemirror.net/demo/basic.html)

Changing the if to

```if (first && desc.nodeDOM && (!desc.nodeDOM.contains || !desc.nodeDOM.contains(dom)))```

has worked for me in this place, though I see there are other positions where a check of a text node with contains may occur. My workaround was to add a polyfill, which makes the code work in IE 11 as well.

```
<html>

<body>
    <script>

    // polyfill from https://github.com/Financial-Times/polyfill-service/pull/183/commits/556b52d8a554fec6f96a32eee4a83aa3d54c1d40#diff-1a1cf82953677933a1881d0d7efe9b34
    delete HTMLElement.prototype.contains;

    Node.prototype.contains = function contains(node) {
        if (!(0 in arguments)) {
            throw new TypeError('1 argument is required');
        }

        do {
            if (this === node) {
                return true;
            }
        } while (node = node && node.parentNode);

        return false;
    };

    var div = document.createElement("div");
    var innerDiv = document.createElement("div");
    var text = document.createTextNode("test");
    innerDiv.appendChild(text);
    div.appendChild(innerDiv);

    console.log("div in div ", div.contains(innerDiv));
    console.log("text in div", innerDiv.contains(text));
    console.log("anything in text", text.contains(innerDiv));
</script>
</body>

</html>
```

I'd be happy to attempt a fix / do more exhaustive testing since I am testing IE 11 compatibility anyways.

Environment: Win 7 & IE 11 ([VM available](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/))
Version: prosemirror-view 0.17.0

**Comment by marijnh** [comment]
I assume patch ee3876125c20e4 already handles this
