### ISSUE TITLE
More specific schema error messages

### ISSUE THREAD

**Issue by ThariqS** [ProseMirror/prosemirror#551]
Occasionally, our docs get in states where the schema is not compatible with the doc. Usually this happens if we change the schema but don't migrate the documents properly.

The error thrown when a document doesnt work with a schema is: ` Cannot read property 'create' of undefined`. It would be extremely helpful if it gave a little more info, like what node or mark type created the error, would save debugging time a lot for me at least.

**Comment by marijnh** [comment]
Good point. See https://github.com/ProseMirror/prosemirror-model/commit/fd5fbda63aff9b5f93ee07b8352ae45226d17acc
