### ISSUE TITLE
Table As Responsive Divs Support

### ISSUE THREAD

**Issue by speedily** [ProseMirror/prosemirror#554]
Hello,
Tables might be old, so  keeping responsive divs with settings like colored borders, respond to show rest in new line/as scrollable component, etc to make tables is best for the future. 

Currently table support is very bad, however a number of editors like TinyMce, Telerik KendoUI editor, Simditor etc have tried putting tables support. I think the best inspiration would be Adobe Dreamweaver/Muse.

**Comment by marijnh** [comment]
I'm sorry, this is too broad and vague to make a useful issue report.

**Comment by leeoniya** [comment]
probably means styling table/tr/td as .table/.tr/.td and using media queries to alter `display: table`.

**Comment by speedily** [comment]
yes @leeoniya is right,
I want @marijnh to add support for creating/editing/etc of HTML Tables in Prosemirror and have given examples of other HTML/JS based WYSIWYG editors that support tables from which @marijnh  can take inspiration while adding the table plugin/support in Prosemirror.

Also per **2016 web design trends** having responsive tables(achieved by divs) support in Prosemirror would be better.
