### ISSUE TITLE
Lost selection after clicking a toggleMark menu item

### ISSUE THREAD

**Issue by davidye** [ProseMirror/prosemirror#555]
When I click the bold menu item (which issues a toggleMark command and then focuses the editor), I lose selection of the text upon refocus. Looks like it worked fine in prosemirror-view v0.17.3 but was broken in v0.17.4.

**Comment by marijnh** [comment]
The demo on http://prosemirror.net doesn't seem to have this problem (at least not in Chrome, you didn't mention which browser you're testing). Are you using the menu items from prosemirror-menu, or a custom implementation?

**Comment by davidye** [comment]
Ah wasn't sure which version of prosemirror-view the website was on. This is happening in chrome. I'm using a custom react based menu implementation.

What worked (prior to 0.17.4) was dispatching a toggleMark() command onClick of my react menu item. The click would cause the editor to lose focus. And then I immediately dispatch a view.focus() and the selection is restored. In 0.17.4 and after, selection is lost on click, and .focus() restores cursor position (but no selection) to the previous selection head.

I'm trying to understand reading the code but what does prosemirror-menu do differently to restore focus on click?

**Comment by davidye** [comment]
Ok so the answer is that I need to e.preventDefault() onMouseDown to not lose focus.

It does seem like some behavior did change though wrt selection not being restored on view.focus().

**Comment by marijnh** [comment]
I ran a test with a button whose click handler was simply `() => view.focus()`, and clicking that seemed to keep the editor selection as it was before I clicked. If you can reproduce an issue with this in prosemirror-view 0.17.7, please open a new issue with an example of how to reproduce it.
