### ISSUE TITLE
No build on node 4

### ISSUE THREAD

**Issue by mihailik** [ProseMirror/prosemirror#557]
Trying to build in Cloud9, fails with:

```
mihailik:~/workspace (master) $ npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> prosemirror@0.0.0 install /home/ubuntu/workspace
> bin/pm clone

/home/ubuntu/workspace/bin/pm.js:13
let origDir = process.cwd()
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Linux 4.8.2-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.6.1/bin/npm" "install"
```

Would be great to break free from complex dependencies, especially considering lots of budget constrained developers can't afford Apple hardware.

Also see: https://github.com/ProseMirror/prosemirror/issues/556

### Update

Cloud9 (which uses node 4 by default) can apparently be updated with node 6: https://community.c9.io/t/how-to-update-node-js/1273/2
```
nvm install 6
```

That said, the issue is still 100% valid: prosemirror does not build on node 4. It means difficulty to use it on non-cutting edge systems, or systems locked for security reasons.

### Update 2

Besides, even with node 6 there is still friction outside of MacOS bubble, getting this warning:

```
Cloning into 'example-setup'...
Cloning into 'markdown'...
Cloning into 'dropcursor'...
Cloning into 'website'...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by herkulano** [comment]
@mihailik regarding `npm WARN` those are normal warnings for that optional dependency, as it's an OSX only module. Everything will work fine without it in other OSes.

you can use the flag `npm i --no-optional` to skip them

**Comment by mihailik** [comment]
This project may get a wider adoption, if artificial affinity with MacOS is eased.

No, it doesn't work on another OSes, see #556 Nor does it work in Cloud9 without couple honest good kicks over the sides :-)  I ended up editing `moduleserve/index.js` replacing `localhost` with `0.0.0.0`.

It's a neat powerful editor though, and may become mainstream if developers are able to use it with less hassle.

👍

**Comment by adrianheine** [comment]
Neither @marijnh nor I use Mac OS X for our daily work.

**Comment by marijnh** [comment]
Indeed, the references to Mac puzzle me. Node 6 runs fine on all platforms that support node. This repository requires node 6 for development (the pre-built libraries should run on earlier node versions as well). In general, there doesn't seem to be much reason to still be running a node <6.

**Comment by mihailik** [comment]
If references to Mac puzzle you, the creator of the project -- imagine how puzzling they are to passers-by.

Here's the quote from the issue text above:

    Besides, even with node 6 there is still friction outside of MacOS bubble, getting this warning:

    Cloning into 'example-setup'...
    Cloning into 'markdown'...
    Cloning into 'dropcursor'...
    Cloning into 'website'...
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Here's the key piece:

<b>Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"}<b>

**Comment by mihailik** [comment]
@marijnh according to **[your advice 16 days ago](https://discuss.prosemirror.net/t/table-demo/584/5)**, node is a **requirement** for running the full demo:

> No, that's not one of the demos on the website. If you clone and `npm install` that [repository](https://github.com/prosemirror/prosemirror), you can run `npm run demo` to start the demo server on port 8080.

Having hard dependency on node 6, OS and no pre-built libraries makes ProseMirror difficult to integrate into a project. Please consider it a constructive feedback: day-in day-out developers naturally have a blind spot for platform affinity issues.

I suggest you make a plan long-term compatibilty strategy, and seek PRs for it.

That way you focus on core features, and bothersome folks like me can help you instead of moaning :-)

**Comment by marijnh** [comment]
> Having hard dependency on node 6, on architecture/OS and hosting no pre-built libraries

We have no dependency on any OS, and NPM has pre-build libraries. If you're not willing to put in the time to figure out what you're doing, stop opening nonsensical issues here

**Comment by marijnh** [comment]
On closer look, when you're going on about Mac OS, I guess you mean the fact that the development setup in the prosemirror/prosemirror repo use some Unix-isms. That is true, but you don't need to even use that repository to use the library, since the actual library code is in the various prosemirror-* modules that live (pre-built) on NPM.
