### ISSUE TITLE
Add HTML Table Support/Plugin in ProseMirror

### ISSUE THREAD

**Issue by speedily** [ProseMirror/prosemirror#558]
I want @marijnh to add support/plugin for creating/editing/etc of HTML Tables in Prosemirror and have given examples of other HTML/JS based WYSIWYG editors that support tables in [link](https://github.com/ProseMirror/prosemirror/issues/554) from which @marijnh can take inspiration while adding the table plugin/support in Prosemirror.

Also per latest web design trends having responsive tables(achieved by divs) support in Prosemirror would be better.

**Comment by leeoniya** [comment]
> Also per latest web design trends having responsive tables(achieved by divs) support in Prosemirror would be better

it would be worse. a `table` is always *semantically*  a table. you can alter the way it's presentationally displayed on mobile using media queries and css, which is exactly how it should work.

**Comment by marijnh** [comment]
> I want @marijnh to add support/plugin for creating/editing/etc of HTML Tables in Prosemirror and have given examples of other HTML/JS based WYSIWYG editors that support tables in link from which @marijnh can take inspiration while adding the table plugin/support in Prosemirror.

And I'm not going to do that.

On the bright side, the project is modular enough that if you want such a thing, you can implement it yourself (as a separate project). Good luck!
