### ISSUE TITLE
coordsAtPos(from, to) option?

### ISSUE THREAD

**Issue by jbsulli** [ProseMirror/prosemirror#559]
What I want to do is make a context menu that would float just below selected text. So it would contain bold/italic/underline/link that could be applied to the selection. To do this, I would need the rectangle coords for the selection. I initially thought using coordsAtPos() to check the start and end positions would work; however, you don't get the proper width if the selection spans multiple lines but the start and end locations happen to be right over each other. I could get the coordsAtPos() value for every position between the start and end... but that seems like it will be slow and inefficient.

Looking at the source for coordsAtPos(), I might be able to figure it out and do a pull request. It could definitely get fun with the start and end locations being nested differently and separated by multiple nodes.

**Comment by marijnh** [comment]
You could call `window.getSelection().getRangeAt(0).getClientRects()` to get the rectangles that make up the selection, and then do some calculation on those. I hesitate to add this feature to the editor API, since it can just as easily be done without going through the editor.

**Comment by jbsulli** [comment]
Damn! That works for me! Thank you so much. Should be easy going from here.
