### ISSUE TITLE
Exponential escaping mechanism for Markdown

### ISSUE THREAD

**Issue by deevus** [ProseMirror/prosemirror#562]
It sounds like a feature, but it's a bug :1st_place_medal: 

# Repro

http://prosemirror.net/demo/markdown.html

Type this into the Markdown editor 

```
`~`
```

Switch between WYSIWYG and Markdown mode

# Result

![image](https://cloud.githubusercontent.com/assets/856194/23006947/07caab56-f459-11e6-8984-25fe706ff391.png)

**Comment by marijnh** [comment]
Moved to https://github.com/ProseMirror/prosemirror-markdown/issues/3
