### ISSUE TITLE
IE11 weird scrolling bug

### ISSUE THREAD

**Issue by davidye** [ProseMirror/prosemirror#563]
If I open editor in IE11 on prosemirror.net and create a long document such that the browser window scrolls and then start clicking around rapidly near the bottom, the window scrolls randomly up. It should be pretty easy to repo as it happens fairly consistently. Works just fine in Chrome.

**Comment by marijnh** [comment]
Apparently calling `.focus()` directly after a triple-click makes IE frantically scroll to some completely meaningless position. Attached patch avoids the `focus` call when not necessary.
