### ISSUE TITLE
Flickering in dropcursor plugin

### ISSUE THREAD

**Issue by herkulano** [ProseMirror/prosemirror#566]
When the mouse is in between to elements the cursor starts flickering. 
This happens consistently in all modern browsers.

[Video of bug](https://www.dropbox.com/s/cvbu7jw0dcqhyp6/ProseMirror-Firefox.mp4?dl=0)

**Comment by marijnh** [comment]
Attached patch seems to solve this -- adding a widget broke something which then caused the next query for what the cursor coords corresponded to to return a nonsense position, which removed the widget, which restarted the cycle
