### ISSUE TITLE
Duplication of elements when using dropcursor

### ISSUE THREAD

**Issue by herkulano** [ProseMirror/prosemirror#567]
When using the dropcursor plugin sometimes the element gets duplicated. 
This is not a consistent behaviour as it only happens sometimes. 

Browsers: Chrome, Safari and Firefox.

[Video of the bug](https://www.dropbox.com/s/cvbu7jw0dcqhyp6/ProseMirror-Firefox.mp4?dl=0)

![screenshot 2017-02-21 19 14 48](https://cloud.githubusercontent.com/assets/125300/23176683/d045fa24-f86c-11e6-890c-f80553bf316b.png)

**Comment by marijnh** [comment]
The dropcursor plugin doesn't handle dropping, it only shows the cursor, so it probably isn't related to this. (Though it could theoretically be, through the way the styling it adds influence drop positions, I don't think that's very likely.)

Is there any pattern to when this happens? I guess the blue node in your video is a node selection? I just spent five minutes dragging selected paragraphs around in the demos (in Chrome), but they never did duplicate.

**Comment by herkulano** [comment]
It only happens with the dropcursor plugin. It never happened to me, in several browsers, with the core drag and drop. 

The core drag and drop is working fine, performance and reliability wise. It's only when you add the dropcursor plugin that it starts randomly duplicating elements and slowing down. 

I haven't noticed any pattern to the duplication, although it happens more often if you move the mouse more while dragging.

**Comment by marijnh** [comment]
Do I understand correctly that it only happens on drop, not during dragging? Is there anything else that might be generating editor transactions during the dragging?

**Comment by marijnh** [comment]
Hm, no, generating transactions during dragging also doesn't seem to trigger this.

**Comment by herkulano** [comment]
> Do I understand correctly that it only happens on drop, not during dragging?

@marijnh correct, it's only on drop, in my tests it never happened on drag.

**Comment by marijnh** [comment]
Are you still seeing this with 0.20.0? I still haven't managed to reproduce it.

**Comment by herkulano** [comment]
It was happening before 0.18.0. I no longer see it.

**Comment by marijnh** [comment]
Great, closing
