### ISSUE TITLE
prosemirror-commands.exitCode

### ISSUE THREAD

**Issue by jbsulli** [ProseMirror/prosemirror#568]
Does this function needs to be updated? It doesn't seem to do anything for my setup. I've largely just copied the [nodeview demo](http://prosemirror.net/demo/nodeview.html) and `Mod-Enter` doesn't seem to do anything there either. 

`$head` seems like it should be `$from`? However, in my case `$head.parent` seems to always be the `doc` so it fails the `$head.parent.type.spec.code` check. The `code_block` can be found by looking at `state.selection.node`.

**Comment by marijnh** [comment]
It's only active when the cursor is in a code block, and it's working fine for me. You seem to be testing it when you have the whole code block selected? That's not what it's for.

**Comment by jbsulli** [comment]
I thought it would make a new paragraph after the javascript code block if you hit `Ctrl-Enter` from here:
![capture](https://cloud.githubusercontent.com/assets/3790122/23222330/5762bf78-f8dc-11e6-960b-601eeac46a5b.PNG).
Seems like ProseMirror always has the entire code block selected while the cursor is inside?

**Comment by marijnh** [comment]
Ah, I didn't notice you were trying to do that in the nodeview demo. There, the embedded CodeMirror handles keys pressed when the code block is focused, so ProseMirror's keymap doesn't take any effect at that point. You'll have to bind the key inside of CodeMirror.

**Comment by jbsulli** [comment]
Right, I set that up but the code block node is always selected. So binding to the exitCode function doesn't work.

Should I be passing all selection changes in CodeMirror back to ProseMirror?

**Comment by marijnh** [comment]
That's not necessary, but if the selection is a node selection, you'll have to write a different command to perform this action.
