### ISSUE TITLE
Dropcursor plugin is slow

### ISSUE THREAD

**Issue by herkulano** [ProseMirror/prosemirror#569]
The cursor is really slow while dragging an element. The cursor changes are so slow that after the mouse has stopped moving the changes are still trying to catch up, you can see this in the inspector in the videos.

This is happening in Chrome, Safari and Edge.
In Firefox it works as expected. The cursor in ProseMirror is keeping up with the mouse movements and there's barely any noticeable delay between the mouse and the cursor.

Videos showing this behaviour:
[Chrome with ProseMirror Dino Demo](https://www.dropbox.com/s/01pnol1zzwnzb5d/ProseMirror-Dino-Demo.mp4?dl=0)
[Chrome](https://www.dropbox.com/s/z99o0c7l6juydqq/ProseMirror-DropCursor.mp4?dl=0)
[Edge](https://www.dropbox.com/s/z3jwevqf7ri4rtw/ProseMirror-Edge.mp4?dl=0)
[Firefox](https://www.dropbox.com/s/cvbu7jw0dcqhyp6/ProseMirror-Firefox.mp4?dl=0)

**Comment by marijnh** [comment]
I still haven't been able to reproduce this. Does anyone else want to try?

**Comment by herkulano** [comment]
I've run it on Browserstack with a Windows 10 VM and Chrome 56, and have the same issues of performance and random duplication.

[Video of the demo running on browserstack](https://www.dropbox.com/s/1ojhl0a0p4h9mru/ProseMirror-Browserstack-DInoDemo.mp4?dl=0)

**Comment by rsaccon** [comment]
I also see the issues of random duplications (on mac with latest chrome)

**Comment by marijnh** [comment]
I think I managed to reproduce this, but only on Windows + Edge (windows + Chrome was fine), and only using 0.17.x, not the current code. I'm going to release 0.18 soon (tomorrow, I hope), at which point I'd be grateful if you could test again.

**Comment by marijnh** [comment]
I've released 0.18.0, and updated the demos on the website. In my win10 VM, where I could see some delay before when dragging, things seem to be much better now.

**Comment by herkulano** [comment]
Tested in Firefox (MacOS), Edge (Win10), Chrome (MacOS), Safari (MacOS).

It's working well in 0.18.0. Performance was good, no duplication, no flickering. 💯

**Comment by marijnh** [comment]
Great to hear! I unfortunately still don't know exactly what caused this, but I guess I fixed it for some other reason.
