### ISSUE TITLE
pm.getContent("html") produces type error

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/prosemirror#57]
```
Uncaught TypeError: Cannot read property 'document' of undefined(…)
toHTML	@	dom.js:18
convertTo	@	index.js:6
getContent	@	main.js:99
(anonymous function)	@	VM739:2
InjectedScript._evaluateOn	@	VM738:875
InjectedScript._evaluateAndWrap	@	VM738:808
InjectedScript.evaluate	@	VM738:664
```

This is because `document` is not passed to `convertTo()` since [`1a4c78a9`](https://github.com/ProseMirror/prosemirror/commit/1a4c78a9#diff-6d57d9a3919bd91bada750125b91289fL81).

**Comment by marijnh** [comment]
Thanks. I fixed `toDOM` to default to `window.document`, but forgot to do the same thing in `toHTML`.

**Comment by ericandrewlewis** [comment]
Getting a related error too:

```
Uncaught TypeError: Cannot read property 'path' of undefined(…)
renderNodesInto	@	dom.js:73
renderNodes	@	dom.js:60
toDOM	@	dom.js:12
toHTML	@	dom.js:19
convertTo	@	index.js:6
getContent	@	main.js:102
(anonymous function)	@	VM134:2
InjectedScript._evaluateOn	@	VM133:875
InjectedScript._evaluateAndWrap	@	VM133:808
InjectedScript.evaluate	@	VM133:664
```
I think this is because `convertTo()` also expects the document passed as `arg`, [removed here](https://github.com/ProseMirror/prosemirror/commit/1a4c78a9#diff-6d57d9a3919bd91bada750125b91289fL81).

**Comment by marijnh** [comment]
Should be better with bf10066
