### ISSUE TITLE
Undo produces incorrect output during collaboration

### ISSUE THREAD

**Issue by hanrelan** [ProseMirror/prosemirror#572]
If two users are typing at the same time (even if they're typing in different parts of the document), and then one of the user hits Ctrl-Z to undo, the undo is not properly applied. You're left with some of the letters that were typing by that user still visible.
To reproduce: 
1) Load up the collab example: https://prosemirror.net/demo/collab.html#edit-Example
2) Have two people typing two different sentences at the same time - it can be in separate parts of the doc.
3) Have one of those people hit Ctrl-Z
4) The output that's produced is wrong

This reproduces 100% of the time during simultaneous typing. The problem does not occur if User A types, then B types, then A types etc.

**Comment by marijnh** [comment]
Thanks for reporting that. I was able to reproduce it an ran into a rather stupid bug in the way history handled remote steps. Attached patch should fix it.

**Comment by hanrelan** [comment]
We aren't able to replicate this anymore in the collab demo on your website. However we noticed there that the collaboration blocks for a long time while you are typing and then only resolves at the end, so there aren't many (any?) simultaneous edits happening/being rebased.

When we pulled this change into our codebase which allows my simultaneous editing and does more rebasing, we're still seeing the same bug with undo. Not sure how to replicate this for you though, if there's a history or something I can dump happy to do that.

**Comment by marijnh** [comment]
> However we noticed there that the collaboration blocks for a long time while you are typing and then only resolves at the end

It does? There's a constant long-polling request that'll resolve remote updates immediately when they come in, so I don't quite see what you mean by this.

>  Not sure how to replicate this for you though

If you can observe the sequence of events and then write a failing test in `prosemirror-collab/test/test-collab.js`, that'd be ideal. Failing that, if you can just precisely describe the events, preferably reduced to a minimal reproducing case, that'd already be useful.
