### ISSUE TITLE
Can't type zero when using collab?

### ISSUE THREAD

**Issue by mikeb-celtx** [ProseMirror/prosemirror#573]
When serializing and deserializing nodes, as during collab, the !content check in the TextNode constructor fails. This causes any text step that has as its text 0 (zero) to fail during deserialization.

Appears to have been introduced in #256

**Comment by marijnh** [comment]
The collab demo on the website doesn't appear to have any problem with zeroes, and looking at the code, I also can't see how the `!content` check could cause problems (the string `"0"` is still truthy).

Can you write a simple program (say, creating a problematic fragment and serializing/deserializing it through JSON) that demonstrates the issue?

**Comment by mikeb-celtx** [comment]
It appears that in 0.18.0 this isn't a problem anymore. I'm not sure whether it was something I was doing in my own code that was causing the issue or not, but as it appears to be resolved, I'll close this issue and apologize for wasting your headspace!
