### ISSUE TITLE
Dragging text jumps to wrong positions

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#575]
Browser: Chrome v55
OS: Mac v10.11.6

When dragging some text, if you hover over the whitespace between lines, you can sometimes get the drop cursor (and drop target, although I have seen cases where these two are not the same) to jump around, sometimes a few words off within the correct line and other times at the end of the paragraph you are hovering over. 

Steps to reproduce:
* http://prosemirror.net/demo/basic.html
* Boost the `line-height` to make it easier to trigger the bug ("2" is pretty reliable).
* Drag some text around and slowly move it around the whitespace between text.
* BUG: Drop cursor jumps to undesired locations.

Cursor jumps a few words off:
![screen shot 2017-02-26 at 2 46 14 pm](https://cloud.githubusercontent.com/assets/1568246/23343032/9d87e588-fc32-11e6-9c45-94217dc00da7.png)

Cursor jumps to end of paragraph:
![screen shot 2017-02-26 at 2 46 25 pm](https://cloud.githubusercontent.com/assets/1568246/23343031/9d872e40-fc32-11e6-90bc-2f216eae1017.png)

**Comment by marijnh** [comment]
[This patch](https://github.com/ProseMirror/prosemirror-view/commit/4276038c1d64bc9e500fbe999b8b4d7bee0d39be) makes this behave much better.
