### ISSUE TITLE
On Android it's possible to type text without updating prosemirror's model

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#576]
### I've tested in:
ProseMirror versions: 0.10, 0.17, 0.18
Android 7.0, Google Chrome Mobile 56.0.2924 (Webkit 537.36)

### The problem:
Start typing in empty editor content area and then call `view.state.doc.toJSON()`. Content of a paragraph node will be empty.

![screen shot 2017-02-28 at 4 32 47 pm](https://cloud.githubusercontent.com/assets/200119/23437506/8d0156c2-fe62-11e6-8547-c1cb8488e0d5.png)

![screen shot 2017-02-28 at 4 33 46 pm](https://cloud.githubusercontent.com/assets/200119/23437573/b17e5108-fe62-11e6-92f6-6aaeaa3144dc.png)

Once you've pressed "space" `view.state.doc.toJSON()` starts to return content which is before space:

![screen shot 2017-02-28 at 4 34 02 pm](https://cloud.githubusercontent.com/assets/200119/23437634/dfc96822-fe62-11e6-900d-a32030de56c6.png)

But if you continue typing it won't have new text until you press space again.

![screen shot 2017-02-28 at 4 34 26 pm](https://cloud.githubusercontent.com/assets/200119/23437664/fd09cdbe-fe62-11e6-915b-4986d33c6ceb.png)

### Related Issues:
https://github.com/ProseMirror/prosemirror/issues/543

**Comment by marijnh** [comment]
This is exactly #543, yes
