### ISSUE TITLE
Table Throws Exception on Backspace

### ISSUE THREAD

**Issue by jordandh** [ProseMirror/prosemirror#578]
**Bug**
An exception is thrown when backspace is pressed at the beginning of a table row. 

**Occurred With**
ProseMirror 0.18.0
Chrome 56.0.2924.87 on MacOS 10.12.3
Firefox 51.0.1 on MacOS 10.12.3

**Steps to Reproduce**
This bug can be reproduced in the demo (npm run demo). Place the cursor at the beginning of a row where that row is not the first row. Press the backspace key and an exception is thrown.
In Firefox the page navigates back so I found it easier to debug in Chrome since the backspace key no longer navigates back.

**Expected Behavior**
No exception is thrown and the cursor moves to the end of the preceding row and possibly removes the current row if it is empty.

**Comment by marijnh** [comment]
Attached patch should help with this.

**Comment by jordandh** [comment]
Works great! Thanks @marijnh
