### ISSUE TITLE
Copying paragraph in Firefox adds extra newlines when pasted

### ISSUE THREAD

**Issue by 0b10011** [ProseMirror/prosemirror#580]
In Firefox, when a paragraph of text exceeds ~74 characters, Firefox will wrap it with `\n` (unless it contains other elements, such as `<br>`). ProseMirror preserves whitespace due to [`preserveWhitespace: true` in `clipboard.js`](https://github.com/ProseMirror/prosemirror-view/blob/05a497ea2e4ed35afa13ebb97e9c6f6bc6fbab03/src/clipboard.js#L67) and displays it as-is due to [`white-space: pre-wrap` in `editor.css`](https://github.com/ProseMirror/prosemirror-view/blob/cb92eac6f79869b2e9810719eb931c9a384d199b/style/prosemirror.css#L7). I'm guessing it is this way intentionally, so I didn't open a PR to blindly change that.

Can be tested with this ([jsfiddle](https://jsfiddle.net/0b10011/6dc9skq0/)):

```html
<!DOCTYPE html>
<style type="text/css">#wrapper { -webkit-user-select: all; -moz-user-select: all; }</style>
<script>
document.addEventListener("paste", event => { console.log(event.clipboardData.getData("text/html")) })
</script>
<div id="wrapper">
<p>With console open, click, copy, and paste. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum venenatis diam vitae bibendum. Donec sed ex ac augue ornare bibendum. Proin et massa quis neque viverra posuere eget a ante. Duis scelerisque turpis efficitur tempus tristique. Integer lacus arcu, tristique at gravida mattis, hendrerit et libero.</p>
<p>Maecenas cursus magna id sodales facilisis.<br>Quisque pulvinar venenatis scelerisque.<br>Donec viverra,<br>enim a laoreet volutpat,<br>dui dolor congue nunc,<br>et semper velit mi a lacus.</p>
<p>Suspendisse vestibulum, odio in tincidunt ornare, risus ipsum facilisis lectus, quis vestibulum velit augue at elit. Duis magna tellus, lacinia in tellus ut, rutrum molestie ex. Quisque porttitor molestie massa, maximus commodo augue congue nec. Maecenas egestas, magna vel vehicula vestibulum, urna metus rhoncus libero, sit amet tempus enim lorem eget nunc. Etiam ut suscipit turpis, eget fermentum turpis. Nam mattis eros urna. Cras ac nunc id sapien molestie lacinia. Nulla placerat neque at urna aliquam tristique.</p>
</div>
```

This results in the following html:

```html
<div id="wrapper">
<p>With console open, click, copy, and paste. Lorem ipsum dolor sit 
amet, consectetur adipiscing elit. Curabitur rutrum venenatis diam vitae
 bibendum. Donec sed ex ac augue ornare bibendum. Proin et massa quis 
neque viverra posuere eget a ante. Duis scelerisque turpis efficitur 
tempus tristique. Integer lacus arcu, tristique at gravida mattis, 
hendrerit et libero.</p>
<p>Maecenas cursus magna id sodales facilisis.<br>Quisque pulvinar venenatis scelerisque.<br>Donec viverra,<br>enim a laoreet volutpat,<br>dui dolor congue nunc,<br>et semper velit mi a lacus.</p>
<p>Suspendisse vestibulum, odio in tincidunt ornare, risus ipsum 
facilisis lectus, quis vestibulum velit augue at elit. Duis magna 
tellus, lacinia in tellus ut, rutrum molestie ex. Quisque porttitor 
molestie massa, maximus commodo augue congue nec. Maecenas egestas, 
magna vel vehicula vestibulum, urna metus rhoncus libero, sit amet 
tempus enim lorem eget nunc. Etiam ut suscipit turpis, eget fermentum 
turpis. Nam mattis eros urna. Cras ac nunc id sapien molestie lacinia. 
Nulla placerat neque at urna aliquam tristique.</p>
</div>
```

When this is pasted into [ProseMirror](http://prosemirror.net/) and copied back out, it results in:

```text
With console open, click, copy, and paste. Lorem ipsum dolor sit 
amet, consectetur adipiscing elit. Curabitur rutrum venenatis diam vitae
 bibendum. Donec sed ex ac augue ornare bibendum. Proin et massa quis 
neque viverra posuere eget a ante. Duis scelerisque turpis efficitur 
tempus tristique. Integer lacus arcu, tristique at gravida mattis, 
hendrerit et libero.

Maecenas cursus magna id sodales facilisis.Quisque pulvinar venenatis scelerisque.Donec viverra,
enim a laoreet volutpat,dui dolor congue nunc,et semper velit mi a lacus.

Suspendisse vestibulum, odio in tincidunt ornare, risus ipsum 
facilisis lectus, quis vestibulum velit augue at elit. Duis magna 
tellus, lacinia in tellus ut, rutrum molestie ex. Quisque porttitor 
molestie massa, maximus commodo augue congue nec. Maecenas egestas, 
magna vel vehicula vestibulum, urna metus rhoncus libero, sit amet 
tempus enim lorem eget nunc. Etiam ut suscipit turpis, eget fermentum 
turpis. Nam mattis eros urna. Cras ac nunc id sapien molestie lacinia. 
Nulla placerat neque at urna aliquam tristique.
```

The expected result would be:

```
With console open, click, copy, and paste. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur rutrum venenatis diam vitae bibendum. Donec sed ex ac augue ornare bibendum. Proin et massa quis neque viverra posuere eget a ante. Duis scelerisque turpis efficitur tempus tristique. Integer lacus arcu, tristique at gravida mattis, hendrerit et libero.

Maecenas cursus magna id sodales facilisis.
Quisque pulvinar venenatis scelerisque.
Donec viverra,
enim a laoreet volutpat,
dui dolor congue nunc,
et semper velit mi a lacus.

Suspendisse vestibulum, odio in tincidunt ornare, risus ipsum facilisis lectus, quis vestibulum velit augue at elit. Duis magna tellus, lacinia in tellus ut, rutrum molestie ex. Quisque porttitor molestie massa, maximus commodo augue congue nec. Maecenas egestas, magna vel vehicula vestibulum, urna metus rhoncus libero, sit amet tempus enim lorem eget nunc. Etiam ut suscipit turpis, eget fermentum turpis. Nam mattis eros urna. Cras ac nunc id sapien molestie lacinia. Nulla placerat neque at urna aliquam tristique.
```

**Comment by 0b10011** [comment]
First comment updated to match reality.

Upon further investigation, it looks like this is due to white-space being preserved in the source, and displayed as-is in the editor, which I don't quite understand. If `white-space: pre` or similar was in the clipboard's HTML, this could make sense (or, rather, if the `\n` was replaced with `<br>`). But with how it is now, content copied from the same page in two different browsers will appear differently just because of how the white-space is handled by that browser in the source (even though both browsers handle whitespace the same way when displaying it).

**Comment by marijnh** [comment]
I'm setting white-space to pre-wrap to prevent adjacent spaces from being collapsed. The fact that it displays newlines in the content as line breaks is an unintended side effect. I'm still not quite sure whether newlines in rich text content make sense and what they should mean. In code blocks they are used as line breaks, which makes sense, but in non-code content, maybe they should be normalized to spaces.

**Comment by 0b10011** [comment]
For display alone, I think normalizing to `<br>` makes the most sense. When displaying in the editor, `<br>` could be output as `\n` within code blocks. (Unless the difference is necessary?)

For pasting, I think white space should be handled the same way the browser would handle it. That way, the user copies `foo bar` and pastes `foo bar`, even if in the *source*, it's `<p>foo    \n\t\t  bar</p>`. Since the user isn't copying from source; they're copying it as it's displayed.

I'm not sure how much information different browsers passes around in the copied HTML, but I think what makes the most sense is to use `style` attributes where available, otherwise fallback to default browser handling. That is, normalize `<p>foo \n\tbar</p>` into `foo bar`, but normalize `<pre>foo \n\tbar</pre>` and `<p style="white-space: pre">foo \n\tbar</pre>` into `foo <br>\tbar`.

But there might be edge cases I'm not thinking of?

**Comment by 0b10011** [comment]
Also, not mentioned specifically in the first comment, is the fact that copying the paragraph with `<br>`s *out* of ProseMirror and pasting into a textarea (github comment box) results in one line of text. So `<p>foo<br>bar</p>` copied when displayed, pasted into ProseMirror, copied from ProseMirror, and pasted into a textarea results in `foobar` instead of the expected `foo\nbar`. So it might be worth adding `\n` before or after any `<br>` that is inserted?

**Comment by marijnh** [comment]
I think attached patch takes care of this. It makes normalizing newlines to spaces the default, except when you explicitly opt into fully preserving whitespace, for example for code blocks. Does it work for you?
