### ISSUE TITLE
Command to toggle off multiple list items

### ISSUE THREAD

**Issue by jchappypig** [ProseMirror/prosemirror#581]
Hi Marijn,

We are upgrading to use the latest prosemirror at the moment. We found that the lift list item command that 0.18.0 has can only lift the sublist items. 

It would be great that if prosemirror-list package provides command to toggle off multiple list items which works on first level list items too.

Desired behaviours on lift list items:
- when I have a list that contains sub lists, and when I select sub list items, they should be all pulled to the higher level list
- when I have a list that contains sub lists, and when I select top level list items, they should become non list items; those on sub lists are pulled to the higher level list
- when I have a list without sublist,  the selected list items should become non list items

It would be even better if we have command to toggle the lists as well (try not to be greedy)

Desired behaviours on toggle:
- when my selection includes list and non list items, non list items or list item with other list type will become part of the expected list type

**Comment by marijnh** [comment]
Attached patch extends the behavior of the `liftListItem` command to, when the selected items are not inside an outer list, simply try to move their content out of the list entirely. I think this covers your first three cases.

As for the toggle behavior, I am not entirely sure how that would work with nested lists, and I don't consider researching it a priority (in general, I prefer to focus on the core library, as opposed to tweaking user interface), so I invite the community to experiment in that space and write custom commands for actions like this.
