### ISSUE TITLE
Character sometimes inserted after cursor when between em and emstrong

### ISSUE THREAD

**Issue by 0b10011** [ProseMirror/prosemirror#584]
1. Open [markdown demo](https://prosemirror.net/examples/markdown/)
2. Switch to WYSIWYM view
3. Select "choice" and make it italic as well
3. Click between `o` and `i` in `choice` to place cursor there
5. Disable bold (clicking the "B" button or Ctrl-B)
6. Press and hold "z" (any letter seems to do the same)

Expected result (`|` is the cursor):

    ...***cho**zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|**ice***...

Actual result (cursor in wrong place):

    ...***cho**zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|z**ice***...

I tested it on my (~6 year old) laptop (Ubuntu 16.04) and it seems to only pop up in Firefox (v52). But, the result isn't always the same. For example, sometimes the character will repeat after the cursor more than once.

It seems to only happen when bold is disabled (doesn't happen when disabling italics instead).

Tested similar setup in a plain `div[contenteditable=true]` and the issue *wasn't* present there.

Additionally, after the character gets placed after the cursor, if you move the cursor to the bold boundary again and hold down a key, that character also gets inserted once after the cursor. So it looks like it's some sort of interaction between the barrier of em/strong (maybe other marks as well?).

**Comment by marijnh** [comment]
Thanks for noticing that. It was a bug in the way I tracked which nodes needed to be redrawn (what you were seeing were extra, bogus text nodes being left in the document after the inserted text)
