### ISSUE TITLE
entering text after non-leaf inline node with custom view inserts new text as child of that node

### ISSUE THREAD

**Issue by dlants** [ProseMirror/prosemirror#585]
I am trying to get inline math editing working on ProseMirror. To accomplish this, I made a new node type. This is an inline node that has 0 or 1 text content, which is meant to hold the latex representation of the math:

```
mqSpec : NodeSpec = {
  inline: true,
  group: "inline",
  content: "text*",
  selectable: true,
  toDOM: () => {
    return ["span", {"mathquill": true}, 0]
  },
  parseDOM: [{tag: "span[mathquill]"}]
}
```

I also added a custom nodeView, which hooks up a http://mathquill.com/ editor, and syncs the value of the MathQuill editor and the content text node.

Things seem to work fine during general operation, but I seem to have hit a snag when ProseMirror uses the domchange mechanism to parse the node view. My previous issue is documented here https://discuss.prosemirror.net/t/understanding-the-interaction-between-parsedom-domchange-and-nodeview/678/6?u=denis and (I believe) was resolved here, with the addition of `this.node.content` https://github.com/ProseMirror/prosemirror-view/commit/8b323c0b5dced986d54f6bd3984d2c07e58dcb3d

The current issue happens in similar circumstances. For example, with this starting state:

```
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "mq"
          }
        ]
      }
    ]
  },
  "selection": {
    "head": 3,
    "anchor": 3
  }
}
```

pressing `space` results in this state:

```
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "mq",
            "content": [
              {
                "type": "text",
                "text": " "
              }
            ]
          }
        ]
      }
    ]
  },
  "selection": {
    "head": 4,
    "anchor": 4
  }
}
```

I expect the text to be inserted into the paragraph, rather than into the node.

**Comment by dlants** [comment]
My understanding is that this is related to what is happening here:

https://github.com/ProseMirror/prosemirror-model/blob/master/src/from_dom.js#L440

In particular, once the `mq` node is added, using `addElementByRule` https://github.com/ProseMirror/prosemirror-model/blob/master/src/from_dom.js#L401 `this.top` changes from `paragraph` to the just-added `mq` node, which I think causes the following text node to be inserted as a child there.

**Comment by dlants** [comment]
I think I narrowed it down to this:

https://github.com/ProseMirror/prosemirror-model/blob/master/src/from_dom.js#L416

I think here we need to sync and step out of the node.

**Comment by marijnh** [comment]
Does [this patch](https://github.com/ProseMirror/prosemirror-model/commit/3e8a5192a454b32d9284f6f11c9c7d81f8c9e44e) help here?

**Comment by dlants** [comment]
confirmed fixed.
