### ISSUE TITLE
endOfTextBlockHorizontal sometimes fails

### ISSUE THREAD

**Issue by dlants** [ProseMirror/prosemirror#586]
I'm using keymap and baseKeymap in a fairly standard setup,  in chrome 56.0.2924.87

I'm finding that sometimes, after I type a backspace character, I get the following DOM structure:

<img width="424" alt="screen shot 2017-03-13 at 5 03 02 pm" src="https://cloud.githubusercontent.com/assets/1186977/23880142/f5b85b38-080e-11e7-89dc-78f21a7ceae4.png">

in `endOfTextblockHorizontal`, sel points at the new empty node:

```
sel.anchorNode
"&#65279;"
```

any ideas about what might be happening here would be super appreciated.

**Comment by marijnh** [comment]
Are you using the current master branch (rather than release 0.18)? Is this DOM structure causing any problems?

**Comment by dlants** [comment]
I am using master for the view and model modules, 0.18 for the rest.

This is affecting the "move selection left" part of the code in the endOfTextBlockHorizontal check. The cursor remains in the empty span, which means the backspace key is handled as if it was at the end of a text block, and fails to delete the "d" character.

**Comment by marijnh** [comment]
I can reproduce this. Will look into it later.

**Comment by marijnh** [comment]
Could you see if attached patch helps?

**Comment by dlants** [comment]
Yep,  working properly on 7684bd6
