### ISSUE TITLE
Broken in Shadow DOM

### ISSUE THREAD

**Issue by bedeoverend** [ProseMirror/prosemirror#588]
Using a trimmed down version of the basic setup, the editor seems to break pretty heavily if it's created _within_ Shadow DOM. There's a lot of errors being thrown, most seem to be triggered during selection. See [here](https://www.webpackbin.com/bins/-KfJf9PBT5FPFZG7gVrs) for demo of it happening - ensure the log is open, and it shows the errors being thrown. Also can't seem to backspace?

Browser: Chrome 56, Mac
Module Versions: All version 0.18.0

HTML Code:
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <style>
      .host {
       border: solid thin blue; 
      }
    </style>
  </head>
  <body>
    <div class="host"></div>
    <script src="index.js"></script>
  </body>
</html>
```

JS Code:
```js
const {EditorState} = require("prosemirror-state")
const {EditorView} = require("prosemirror-view")
const {DOMParser} = require("prosemirror-model")
const {schema} = require("prosemirror-schema-basic")

let host = document.querySelector('.host'),
    editor;

host.attachShadow({ mode: 'open' });
host.shadowRoot.innerHTML = '<div class="editor"></div>';

editor = host.shadowRoot.querySelector('.editor');

window.view = new EditorView(editor, {
  state: EditorState.create({
    doc: DOMParser.fromSchema(schema).parse(editor)
  })
});
```

**Comment by marijnh** [comment]
Does attached patch help? I couldn't see any issues with backspace, but I did notice the editor refusing to update its selection because it believed it wasn't focused. That should be fixed with this patch.

**Comment by marijnh** [comment]
Err, I meant patch https://github.com/ProseMirror/prosemirror-view/commit/5dfbaab165494b6dbdc785530775506fa1e42d32

**Comment by bedeoverend** [comment]
Hmm...patch doesn't seem to change anything for me, though I imagine probably still good to have in there. It looks like there are only issues when the cursor is at the end of the text string. For example, if I type 'Hello World' and the cursor is at the end, backspace and any arrow keys don't work. But if I click to somewhere in the middle I can use backspace / keys.

Looks like it's in `skipIgnoredNodesLeft` - where it's getting the selection, the `anchorNode` is `null`.

It's also coming up in `skipIgnoredNodesRight`, again because `anchorNode` is `null`.

I'm also getting errors in `withFlushedState` where it's trying to get a range that doesn't exist (`0 is not a valid index`) - but I'm assuming that's because things get confused after that first error? This error definitely only happens after the first one to do with the `anchorNode`.

**Comment by marijnh** [comment]
Could you try upgrading to version 0.19.0 (which I just released) and testing again? Maybe I had some other fix locally, and that's why I didn't see the problems.

**Comment by bedeoverend** [comment]
Ok so that seems to have fixed 99% of the issues - but seems like selection isn't working...so it seems to think any selection in Shadow DOM is empty. I've created another [`bin` to demonstrate](https://www.webpackbin.com/bins/-KfNq9nRyJpZxLmnzfX-) - I've just adding a plugin that just logs if selection is empty or not at every transaction. Running the same code on an editor that's in Light DOM works fine, but in Shadow the selection is always empty.

**Comment by bedeoverend** [comment]
Looks like it's https://bugs.chromium.org/p/chromium/issues/detail?id=447523 that's causing the problem. Essentially means that [`domSel.isCollapsed`](https://github.com/ProseMirror/prosemirror-view/blob/master/src/selection.js#L70) always returns true. A potential workaround would be checking that it's collapsed, and then also checking its ranges are collapsed - `domSel.isCollapsed && (domSel.rangeCount === 0 || domSel.getRangeAt(0).collapsed))`.

With that workaround, selections seem to work, though there're some issues around focusing I believe...will continue investigating.

@bradleyayers - I noticed you'd run into Shadow DOM issues with Prosemirror, did this come up at all, did you have any solutions?

**Comment by bedeoverend** [comment]
I've made a PR - that also fixes the focus issue I was having (same problem, just happening elsewhere). Let me know if you'd like me to change anything

**Comment by marijnh** [comment]
Thanks for digging into that! I assume you are aware of #476, which still kind of ruins attempts to use ProseMirror in a shadow dom on Safari?

**Comment by bedeoverend** [comment]
@marijnh no worries - thanks for ProseMirror 😃 Yeah I'm aware of that one, we're still using v0 Shadow DOM so don't run into the issue on Safari, but even the v1 Polyfills [don't support it](https://github.com/webcomponents/shadydom/issues/113) yet. I'm looking at ways to get around it - potentially a partial polyfill for that part of the spec, but won't be looking into it for awhile yet.

**Comment by bedeoverend** [comment]
@marijnh so looks like this is still broken - I mustn't have tested properly after this landed in a tagged release. Looks like [this commit](https://github.com/ProseMirror/prosemirror-view/commit/1d6df3e3c36f4dc42ee949d48c1bb7ab28e49541) broke it, as I don't think there's a `chrome` prop in the `browser` object?

**Comment by marijnh** [comment]
Ah, apologies. Does patch https://github.com/ProseMirror/prosemirror-view/commit/931e286714a00a39aa311f4af1d556ab9f7afb34 help?

**Comment by bedeoverend** [comment]
Awesome - that'll do it, thanks @marijnh and no worries 😃
