### ISSUE TITLE
Losing text when putting cursor on link inside word

### ISSUE THREAD

**Issue by rafbm** [ProseMirror/prosemirror#589]
A GIF is worth a thousand words:

![bug](https://cloud.githubusercontent.com/assets/166943/24052669/b25b3724-0b0c-11e7-8911-f2249b863e71.gif)

I can reproduce on current [prosemirror.net](http://prosemirror.net/):

1. Add a mark (eg. bold) to some word
2. Add a link on _a part of_ the same word
3. Write text after that link
4. Move cursor with ◀️ until you get inside the link
5. BUG: Text you just wrote is gone

**Comment by rafbm** [comment]
Also when typing text before a mark that is inside a link, keystrokes are weirdly applied:

![bug-2](https://cloud.githubusercontent.com/assets/166943/24053973/0a5d7f78-0b11-11e7-8867-97aaca450cbe.gif)

1. Apply on link on a word
2. Add a mark (eg. bold) on _a part of_ this link
3. Type “test” before the mark
4. BUG: “ttetestesttest” will be inserted

Mixing non-link marks (eg. bold + italic) does not seem to cause issues. A link must be involved.

**Comment by rafbm** [comment]
I think ProseMirror/prosemirror-schema-basic@a082ec26 (Make links the lowest-predecence mark) caused this. I can fix the issues above in my code by removing `link` from `spec.marks` then re-appending it further. If I append it after `em`, the issues are fixed with `em` but still present with `strong`. If I append it after `strong`, all fixed.

**Comment by inukshuk** [comment]
Possibly related to this, I noticed text being lost in relation to adding/removing marks in the example editor on the website.

Using Chromium 57.0.2987.110 on Linux:

1. Start a new paragraph at the end of the content.
2. Click on 'Bold'
3. Type 'abc'
4. Click on 'Italic'
5. Type 'def'
6. Click on 'Bold' again
7. Type 'ghi'
8. Click on 'Italic' again
9. BUG: 'ghi' is removed (the line reads 'abcdef' at this point)

And worse on Firefox 52.0 on Linux:

1. Start a new paragraph at the end of the content.
2. Click on 'Bold'
3. Type 'abc'
4. BUG: 'b' and 'c' and so on are added and removed right away.

**Comment by marijnh** [comment]
Attached patches should reduce the symptoms on Chrome. The Firefox issue @inukshuk mentioned is still broken, and there generally are some serious holes in the way I'm handling DOM changes. I'll spend more time on this next week.

**Comment by marijnh** [comment]
I added https://github.com/ProseMirror/prosemirror-view/commit/3f6deac5502b8110ea962db50cc6f49f6d7244d5 , which cleans up the mess I made in the previous patches and also makes the Firefox case work. The result is released as prosemirror-view 0.19.1
