### ISSUE TITLE
scrollIntoView() does not work correctly for empty lines

### ISSUE THREAD

**Issue by ameliusg** [ProseMirror/prosemirror#59]
When typing "ENTER" a couple of times in a row, the view starts scrolling unpredictably. There is probably a bug in scrollIntoView().

**Comment by ameliusg** [comment]
After digging a little into this, it seems that the function coordsAtPos() returns an empty rectangle for paragraphs that contain a single <BR /> element. The comments in the code suggest that this might be the case but the code doesn't provide a solution for the situation when there is a single <BR /> element in the paragraph.

**Comment by marijnh** [comment]
I can't reproduce this on Chrome 45 Linux. Which page are you testing in?

**Comment by ameliusg** [comment]
Instructions to reproduce:
1. Visit http://prosemirror.net/
2. Place the caret before the heading text "Control your Content".
3. Hit enter.
4. Hit arrow-up (the caret is now on an empty line).
5. Hit enter N times, so that the caret runs past the bottom of the screen.

You will notice that the caret is not visible anymore (it really ran off the screen). Furthermore, the scrollbar (which is visible on my version of Chrome/Linux) is still at the top. Pressing any letter, for example "x", will fix all this.

Tested on Chrome Version 40.0.2214.115 (64-bit) Linux.

**Comment by marijnh** [comment]
Could you try with Chrome 45? I still can't reproduce this when following your instructions precisely.

**Comment by ameliusg** [comment]
Yes, it seems to be fixed in Chrome 44.
However, I just tested with Firefox 42.0 (I just downloaded the newest version), and the bug appears there still...

**Comment by marijnh** [comment]
Attached patch seems to help.
