### ISSUE TITLE
domFromPos returns widget

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#592]
domFromPos(view, myNodePos) -> myNode
// add a decoration widget at myNodePos
domFromPos(view, myNodePos) -> myWidget

Is this the way it's supposed to work ?

**Comment by marijnh** [comment]
What `domFromPos` are we talking about? This is not a public function, and in fact it hasn't existed at all in the way you're calling it for a bunch of releases.

**Comment by kapouer** [comment]
I'm talking about `ViewDesc.prototype.domFromPos`. I know this is not public API, but i needed to use it and i figured its behavior w.r.t. widgets was worth reporting to you (hence the question).

**Comment by marijnh** [comment]
Can you set up a self-contained demo that shows the issue? Looking over the code, I can't see anything suspicious, and your description is a little confusing, in that it claims nodes or widgets are returned, whereas this method returns a {node, offset} object.

**Comment by kapouer** [comment]
I'll try to setup a self contained demo, in between here's the function i'm using - sorry for the confusion.
```
function getDomNodeFromPos(view, pos) {
  var fromPos = view.docView.domFromPos(pos);
  if (!fromPos) return;
  var dom = fromPos.node;
  var offset = fromPos.offset;
  if (dom.nodeType == 1 && offset < dom.childNodes.length) {
    dom = dom.childNodes.item(offset);
  }
  return dom;
}
```

**Comment by marijnh** [comment]
Closing this until further details come in.
