### ISSUE TITLE
new 0.19 selection problems

### ISSUE THREAD

**Issue by jonsutherland** [ProseMirror/prosemirror#594]
I have a schema defined where I have a custom parent node containing my own custom child nodes containing text* content.

I notice problems in 0.19 when I have my schema toDOM defined as this for the parent:

  toDOM: function (node) {
    return ["div", {
      id: node.attrs.id,
      class: node.attrs.class
    },  ["span", {}, 0]];
  }

When I just have something like below things function normally:

  toDOM: function (node) {
    return ["div", {
      id: node.attrs.id,
      class: node.attrs.class
    }, 0];
  }

Seems that any amount of nesting of spans is causing issue with the new selection behaviour introduced in 0.19.

Is this something supported?  I noticed I can work around it if use schema node specs more literally to define that nesting but that isn't ideal.

Thanks very much.

**Comment by marijnh** [comment]
This is supported. The default code blocks render as `<pre><code>...</code></pre>` for example. Could you describe in a bit more detail what goes wrong and, ideally, provide a minimal demo file that makes it easy to reproduce the problem?

**Comment by jonsutherland** [comment]
Yes, before I prepare a minimal demo I'll describe the issue a little better.

My schema kind of looks like an element with 2 inner text elements.  When you would type in the first text element and hit enter at end of line, I let the regular keymap handle this and create the second element, insert it, and then move selection to it.  

This appears to work like regular, from the perspective of the internal selection as far as I can tell.  The selection looks okay when I check view.state.selection.$head.pos. But the cursor is appearing at the end of the previous element (where it was before I hit enter). 

I know things are mostly okay since PM will do everything normally otherwise, I add a decoration to this blank line (element) when selection is on it, and I can see it displaying as if the cursor was there, except the cursor is still blinking on the previous line.  When I use the arrow-right to move it to the spot it's supposed to be, it does and things work normal.

I'll come up with a minimal demo to demonstrate this as soon as possible.  Thanks!

**Comment by jonsutherland** [comment]
OK, I've attached a version of prosemirror/demo/demo.js that demonstrates the issue clearly.

When you load the demo, Hit CTRL-A select all and delete your content...  You're left with my parent element with only the first child as I expect. 

Type a few characters, hit enter.  You can see the next element is created in the DOM but the selection is left on the previous element.  It doesn't select the second child as I expect, it's still on the first element/child.
[demo.zip](https://github.com/ProseMirror/prosemirror/files/855103/demo.zip)
  

That's what my issue boils down to there.  

Thanks again.

**Comment by jonsutherland** [comment]
I'll add I thought it had something to do with nesting of spans or extra content in the toDOM function but it turned out it I could replicate the problem in the simple example I provided.

**Comment by jonsutherland** [comment]
Sorry to save messing with the zip I should have just posted... basically I modified the schema as follows (my appologies for the terrible formatting):

`const demoSchema = new Schema({`
`  nodes: {`
`    doc: {`
`      content: 'par+'`
`    },`
`    parent: {`
`      group: 'par',`
`      content: 'el_one{1}el_two?',`
`      toDOM: function () {`
`        return ["div", {}, 0]`
`      }`
`    },`
`    el_one: {`
`      content: 'inline*',`
`      toDOM: function () {`
`        return ["span", {}, 0]`
`      }`
`    },`
`    el_two: {`
`      content: 'inline*',`
`      toDOM: function () {`
`        return ["span", {}, 0]`
`      }`
`    },`
`    text: {`
`      group: 'inline'`
`    }`
`  },`
`  marks: schema.spec.marks`
`})`

**Comment by marijnh** [comment]
You're rendering block elements as inline DOM nodes. That's not supported. Or, alternatively, if you intended these to be inline elements, that's not supported either, unless you render them using a custom node view.

**Comment by jonsutherland** [comment]
Okay, I understand regarding the inline DOM nodes.  

But I guess my problem is unrelated to that.  If I change the children elements to both be DIV in the last posted example, the issue goes away.  Though in my real world app in development I still have a problem with selection and I think I've narrowed it down further to an extra parent DIV like I originally mentioned.  

The symptoms are similar to the last example.  However, when I change the previous schema and add an extra parent DIV you can see the issue in demo.js.  If you clear the content and are left when the single parent element and type some content in the el_one, then hit enter, Selection is left on the previous line in el_one (el_two is created as expected).  It appears the editor thinks the selection is in the right spot on the next line in el_two, but it isn't.

I've attempted to set selection myself in my enter key handler but if I set selection to the correct spot the cursor is on the previous line.

The updated demo schema follows.

Again, let me know If what I'm attempting in this example schema isn't supported.  Thank you

`const demoSchema = new Schema({`
`  nodes: {`
`    doc: {`
`      content: 'par+'`
`    },`
`    parent: {`
`      group: 'par',`
`      content: 'el_one{1}el_two?',`
`      toDOM: function () {`
`        return ["div", {}, ["div", {}, 0]]`
`      }`
`    },`
`    el_one: {`
`      content: 'inline*',`
`      toDOM: function () {`
`        return ["div", {}, 0]`
`      }`
`    },`
`    el_two: {`
`      content: 'inline*',`
`      toDOM: function () {`
`        return ["div", {}, 0]`
`      }`
`    },`
`    text: {`
`      group: 'inline'`
`    }`
`  },`
`  marks: schema.spec.marks`
`})`
