### ISSUE TITLE
handleDOMEvents doesn't capture all events

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#597]
I've got a plugin that sets up several event handlers using `handleDOMEvents`. It looks like only the ones defined in https://github.com/ProseMirror/prosemirror-view/blob/master/src/input.js get registered. Specifically, https://github.com/ProseMirror/prosemirror-view/blob/master/src/input.js#L25 only seems to `addEventListener` for the handlers defined in input.js. This prevents `touchstart`, `touchmove` and `touchend` from being registered when defined in my `handleDOMEvents` object.

**Comment by marijnh** [comment]
The `ensureListeners` function should take care of that. I know it works, at least in _some_ cases. Do you have a minimal example that fails?

**Comment by wes-r** [comment]
Looks like `!handlers.hasOwnProperty(type)` in the `if` within `ensureListeners` is preventing the listeners from being added. I believe this will always return false since we're looping over `type in handlers`, so `type` will always be a property on `handlers`.

Here's a minimal plugin that fails to print out touch events. (using chrome dev tools, toggle "device toolbar" to test as a phone or tablet).
```
  let plugin = new Plugin({
    props: {
      handleDOMEvents: {
        touchmove(view, event) { return console.log("touchmove") },
        touchstart(view, event) { return console.log("touchmove") },
        dragstart(view, event) { return console.log("dragstart") },
        dragend(view, event) { return console.log("dragend") },
      },
    }
  })
```

**Comment by marijnh** [comment]
You're entirely right. Attached patch should help.
