### ISSUE TITLE
Handle non-breaking space

### ISSUE THREAD

**Issue by normanzb** [ProseMirror/prosemirror#598]
It turns out in latest webkit-based browser such as Chrome (57.0.2987.11, at the moment of writing), if white-space on contentEditable is set to anything doesn't preserve tabs and spaces, the browser will inserts non-breaking space 0xA0 instead of 0x20 after typing space after '#'.

Which causes regex match broken here:
https://github.com/ProseMirror/prosemirror-inputrules/blob/master/src/util.js#L96

Maybe its better to use \s (which includes all whitespaces such as tab) rather than space?

**Comment by marijnh** [comment]
This is a somewhat tricky issue because I'd like people to be able to represent documents with non-breaking spaces in them, so just normalizing those to spaces wholesale seems like a bad idea.

The editor's stylesheet sets its content to `white-space: pre-wrap`. Why are you overriding that?

**Comment by normanzb** [comment]
It seems reasonable to keep it as is after 2nd thought

**Comment by bedeoverend** [comment]
I'm getting this same issue for the bullet / ordered list input rules. I can't use ProseMirror's default stylesheet for a bunch of reasons.

@marijnh in the inputrules, could we change the RegExp rules to test for regular space char and a nbsp? For example, for an bullet list, I'm using this rule `/^\s*([-+*])( |\u00a0)$/` which is working well.

**Comment by jacwright** [comment]
This allows documents to have non-breaking spaces and allows the input rules to work correctly.

**Comment by marijnh** [comment]
What is the reason for _not_ setting the editor's `white-space` CSS property? Having your documents become a random jumble of regular spaces and non-breaking spaces seems really undesirable.

**Comment by jacwright** [comment]
I personally have no reason, but you said above:

> I'd like people to be able to represent documents with non-breaking spaces in them

I thought this would be an easy first-commit to get started contributing.

**Comment by marijnh** [comment]
That's definitely a good enough reason. I've merged your pull request.
