### ISSUE TITLE
Lift list command does not move nested list item out of parent list item in latest version.

### ISSUE THREAD

**Issue by jpuri** [ProseMirror/prosemirror#599]
Hey @marijnh,

I recently moved to the latest version of the library. I am now facing an issue with liftList command which worked perfect before:

Here is my nested list (created using sinkListItem command):

![screen shot 2017-03-28 at 2 24 05 pm](https://cloud.githubusercontent.com/assets/2182307/24396987/9af55056-13c2-11e7-8e81-b95130152532.png)

After executing liftListItem command:
![screen shot 2017-03-28 at 2 24 25 pm](https://cloud.githubusercontent.com/assets/2182307/24397065/d37a47d8-13c2-11e7-9d6a-bfe11d4d72b6.png)

As you can notice child list item is not lifted outside parent list item.

**Comment by marijnh** [comment]
It still works for me, and there's a bunch of tests that exercise it. You're going to have to provide a more specific description of what you're doing (preferably a test case, as in prosemirror-schema-list/test/test-commands.js for example)

**Comment by jpuri** [comment]
Thanks for your quick response @marijnh. I could not run test cases in prosemirror-schema-list repo, its giving some dependency issue. But this is what I have in my repo:

```
        const { editorView } = editor(doc(ol(li(p('text'), ol(li(p('te{<>}xt')))), li(p('text')))));

        sendKeyToPm(editorView, 'Shift-Tab');

        expect(editorView.state.doc).to.deep.equal(doc(ol(li(p('text'), li(p('te{<>}xt'))), li(p('text')))));
```

If I add a `-1` to liftTarget it works well:
```
dispatch(tr.lift(range, liftTarget(range)! - 1).scrollIntoView())
```

I am not sure where are things going wrong.

**Comment by marijnh** [comment]
This is, except for the text string being different, exactly [this test case](https://github.com/ProseMirror/prosemirror-schema-list/blob/master/test/test-commands.js#L61), which passes.

**Comment by jpuri** [comment]
It worked after I changed list schema from 

```
export const listItem: NodeSpec = {
  group: 'block',
  content: 'paragraph block*',
  parseDOM: [{ tag: 'li' }],
  toDOM() {
    return ['li', 0];
  }
};
```

to:
```
export const listItem: NodeSpec = {
  content: 'paragraph block*',
  parseDOM: [{ tag: 'li' }],
  toDOM() {
    return ['li', 0];
  }
};
```

Looks like previously it was block so liftTarget found it as the target. Looks like wrong schema at our end may be.

**Comment by jpuri** [comment]
Hey @marijnh,

I am closing the issue thanks again for your quick help as always :)

**Comment by marijnh** [comment]
> Looks like previously it was block so liftTarget found it as the target. Looks like wrong schema at our end may be.

Yes, that's what happened. Glad to hear you solved it.
