### ISSUE TITLE
Consider joining forces with quilljs?

### ISSUE THREAD

**Issue by butsjoh** [ProseMirror/prosemirror#6]
Hey,

I did some research on different rich text editors a while a go and it seems what you are trying to achieve is already being done by other people as well :) Just wanted to have your opinion on why you think your direction is different (or maybe the same) and maybe you could team up with them. The editor i am referring to is https://github.com/quilljs/quill. It is implementing the ottypes spec (https://github.com/ottypes) which is also used by the popular sharejs (http://sharejs.org/) which aims at collaborative editing. Seems they are doing good things but it lacks proper integration between the two (https://github.com/share/ShareJS/issues/1). Again i am not saying your implementation is bad, just wanted to point you to this resource and see what you are thinking about it.

**Comment by marijnh** [comment]
I am well aware of Quill. It is not taking the approach that I'm trying to take with ProseMirror, both in terms of document model (for which they use a stream of styled tokens, which is how to do things with sharejs, but not what I'm going for), and in terms of implementation (the DOM _is_ the way they store the document).

So while the end goal is similar, these are two different approaches to reaching that goal, and merging does not make any sense.
