### ISSUE TITLE
Empty paragraph issue on android.

### ISSUE THREAD

**Issue by ViktorMarosvary** [ProseMirror/prosemirror#60]
To reproduce the issue:
Start a new paragraph by pressing enter on the end of a line.
Type a word.
When you press space, the cursor moves to the beginning of the paragraph.

Android 4.4.2 Chrome version 46.0.2490.76 also same issue with this android's stock browser.
I could also reproduce this on Android 4.2.2 in chrome, but at that version the stock browser seems to be working fine.

**Comment by icflorescu** [comment]
Reproduced on Chrome 46.0.2490.76 / Android 5.0.2.

**Comment by marijnh** [comment]
This should be addressed by the changes in 5f2489ff0183edaa...5b19b8b5ca
