### ISSUE TITLE
Override .ProseMirror class(es)

### ISSUE THREAD

**Issue by bedeoverend** [ProseMirror/prosemirror#600]
Currently, the `.ProseMirror` class is added [by default](https://prosemirror.net/docs/ref/#view.EditorProps.attributes) (but not removable?), along with other classes e.g. `ProseMirror-focused` depending on state. It'd be great if we could disable these - I believe they're only used for styling?

I'm not relying on ProseMirror styles, and would prefer to add classes as needed on my own, rather than ProseMirrors. Is there a way to stop these classes from being applied? If not, is it something ProseMirror would consider as a feature?

**Comment by marijnh** [comment]
If you don't define any styles for a class, it is not having any effect, and I fail to see how removing it would make any difference.

**Comment by bedeoverend** [comment]
It's not a breaking bug, more just cleanliness for end users. My use case is making custom elements which are used by 3rd parties - ideally, we shouldn't apply any classes to those custom element; that should be completely up to the consumer of the custom element. By adding classes, we're then interfering with their DOM, which we'd ideally like to keep to a minimum.

This was just to see if ProseMirror would accept a PR, and if so what kind of interface - I understand it's not at all a high priority.

**Comment by marijnh** [comment]
No, I don't think this is a significant enough use case to add a feature for.

**Comment by mitar** [comment]
@bedeoverend Have you found any workaround for this? I would also love to be able to control class names. It is just esthetics (no other class names  have are CamelCase).

**Comment by bedeoverend** [comment]
@mitar unfortunately no, I just ended up leaving the classes as is, though we don't use them at all.

**Comment by marijnh** [comment]
I don't feel this is a big enough issue to add another configuration parameter for. Just add another class and ignore the default one if you need to.
