### ISSUE TITLE
Plugins - HandleDOMEvents editorProps are not bound to the plugin instance

### ISSUE THREAD

**Issue by ThariqS** [ProseMirror/prosemirror#601]
In this line, all the editor props of a plugin are iterated through and if it's a function, it is bound to the plugin instance: https://github.com/ProseMirror/prosemirror-state/blob/master/src/plugin.js#L63

However, in the case of handleDOMEvents, the functions are inside the handleDOMEvents object, so that they are not bound to the plugin instance, which makes it hard to utilize handleDOMEvents within a plugin.

**Comment by marijnh** [comment]
> which makes it hard to utilize handleDOMEvents within a plugin.

Not really -- just close over the plugin instance.

That being said, a patch that adds an exception for `handleDOMEvents` and, if found, replaces it with a copy that has its methods bound, would be accepted.
