### ISSUE TITLE
view.focus() changes the selection in Firefox

### ISSUE THREAD

**Issue by torifat** [ProseMirror/prosemirror#602]
![kapture 2017-03-29 at 15 52 44](https://cloud.githubusercontent.com/assets/208544/24439110/dad1fd8e-1497-11e7-80c7-a8db78894027.gif)

Here when I pressed `<enter>`, it didn't remove `Like` but inserted a newline in front of it. In **Chrome**, it behaves as expected.

We are facing a similar issue. We have something like this:

```js
view.dispatch(state.tr.insert($from.pos, state.schema.text(href, [mark])));
console.log(view.state.selection.$from.pos, view.state.selection.$to.pos);
view.focus();
console.log(view.state.selection.$from.pos, view.state.selection.$to.pos);
```

So, in **Firefox** after the `view.focus()` it returns different value.

```
> 27 27
> 1 1
```

**Comment by torifat** [comment]
If I get rid of https://github.com/ProseMirror/prosemirror-view/blob/master/src/selection.js#L176 then it works.

**Comment by johanneswilm** [comment]
@marijnh Is it possible that recent Chrome versions have adopted the Firefox behaviour? It seems that view.focus() now leads to a selection of 1 1, no matter what it previously was.

**Comment by marijnh** [comment]
Which Chrome version are you testing with? I'm not seeing this with 58

**Comment by johanneswilm** [comment]
Chrome version 59.0.3071.115

Basically, the selection of the editor is updated to `(1,1)` whenever running `view.focus()`.

**Comment by marijnh** [comment]
I don't have 59 installed, but 60 also doesn't show the issue. Do you see the problem on http://prosemirror.net ?

**Comment by mhuebert** [comment]
I'm not sure if the is precisely the same issue, or if I don't understand how `.focus` is supposed to work, but across all browsers I've tried (including Chrome 59.0.3071.115 and 60.0.3112.78, Safari, and Firefox), using prosemirror-view master, I am unable to set a selection and focus the editor at the same time without the cursor being moved to position zero.

Example:

```js
pmView.focus()
pmView.dispatch(tr.setSelection(selection))
// Desired behaviour: cursor moves to the given position
// Actual behaviour: cursor moves to position 0
// (switching the order of the two lines doesn't make a difference)
```

The closest I can get to the desired behaviour is setting a timeout on the selection dispatch, in which case I observe the cursor first jumping to 0, then back to where I set the selection:

```js
pmView.focus()
setTimeout(function(){pmView.dispatch(tr.setSelection(selection))}, 10)
```

This is always being applied to a 'fresh' ProseMirror view which has not previously had focus.

**Comment by johanneswilm** [comment]
Hmm, the issues seems not to be there if I do `window.getSelection().removeAllRanges()` before `view.focus()`. It may just be PM being confused abotu whether it had or didn't have the selection already before the event. So I guess there are ways for me around this.

**Comment by marijnh** [comment]
> Hmm, the issues seems not to be there if I do window.getSelection().removeAllRanges() before view.focus()

But if you don't, is there a reliable way to reproduce the issue?

@mhuebert Could you open a separate issue? That is definitely not the same thing.

**Comment by johanneswilm** [comment]
> But if you don't, is there a reliable way to reproduce the issue?

If you place an `<input type=text>` element in a widget, and you add an eventListener to that input element for keydown. If the function of associated with that event listener is calling `view.focus()`, then this happens in all the cases I could find. It is not happening in Firefox due to issue #678 . I guess it is because `hasFocusAndSelection()` tells it that the selection is inside the prosemirror instance. 

I isolated the widget with stopEvent like this:

    deco = Decoration.widget(pos, dom, {
        side: 1,
        stopEvent: event => true
    })


I also saw your advise to switch to a contenteditable element instead. However, I had filed the issue before your response on that, and I am still looking at how to best make sure to avoid richtext input in such a contenteditable element (there is a "plaintext-only" type, but AFAIK it is not yet implemented in all browsers).

**Comment by konradk-sparkbit** [comment]
it seems that [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=921444) has been solved so the [hack](https://github.com/ProseMirror/prosemirror-view/blob/99c8c8e1d1bafcd3bd7930c92a3e50c8db849ad3/src/selection.js#L177) could be updated (e.g. by taking the version into account). disclaimer: i haven’t tested this one.
