### ISSUE TITLE
Inserting hr Into an Empty Document and then Hitting Enter Causes the Cursor to Move Above the hr

### ISSUE THREAD

**Issue by jordandh** [ProseMirror/prosemirror#603]
**Bug**
Inserting an hr into an empty document and then hitting enter causes the cursor to move above the hr instead of below it.

**Step to Reproduce**
Goto http://prosemirror.net/ and clear out the sample editor.
Insert an hr.
Hit the enter key.

**Expected Behavior**
The cursor should appear below the hr.

**Comment by marijnh** [comment]
Why is that the expected behavior?

**Comment by jordandh** [comment]
Because if an hr is inserted when there is content in the document and then enter is hit the cursor appears below the hr. So there is different behavior for the two cases.

I suppose the expected behavior could be either but I would expect it to be the same for both cases.

**Comment by marijnh** [comment]
There's an exception in the `createParagraphNear` command when a block at the start of the document is selected to make it possible to put a paragraph in front of that. You can choose not to bind that command to Enter if you want.

Attached patch makes it only insert in front when you've selected a block node that's the first node in the document but not also the last.
