### ISSUE TITLE
`posAtCoords` uses non standard `caretRangeFromPoint`

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#604]
device: iPhone 6
iOS: v10.2.1
Safari: v10

I'm presently working with touch events and when I develop in chrome using its device mocking, `posAtCoords` works, however using a real device it fails (returns `null`). It appears that `caretRangeFromPoint` is the culprit. Mozilla recommends not to use this as it is non standard (see [doc](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint)).

If I instead setup `posAtCoords` to utilize `posFromCaret` it works.

I'm not sure of the history of this code, but perhaps we should always use `posFromCaret` to eliminate discrepancies between browsers that support or don't support either `caretRangeFromPoint` or `caretPositionFromPoint`?

Additionally, I'm not 100% certain what is going on with `caretRangeFromPoint` on the device. My app has an "edit" mode that hides the normal div and reveals the PM div. When not in edit mode, `caretRangeFromPoint` works, but when in edit mode it doesn't... ¯\\_(ツ)_/¯

**Comment by marijnh** [comment]
> Mozilla recommends not to use this as it is non standard

It's feature detected, so it's only used on platforms that have it.

> If I instead setup posAtCoords to utilize posFromCaret it works.

That makes no sense -- `posFromCaret` is only called _when_ `caretRangeFromPoint` or `caretPositionFromPoint` was called.

**Comment by wes-r** [comment]
While you do do feature detection, my point is that this will yield varying behavior depending on the browser. If you've got a working solution for browsers that do not support these features, why not use that for everything? The mozilla doc also states:
> There may also be large incompatibilities between implementations and the behavior may change in the future.

And I am running into an issue where in some cases it works and in another case it doesn't.

OOH! Discovery! I debugged a bit more why it stops working for me in my "edit" mode. During editing my image figures get `-webkit-user-select: none;` to prevent selection. This is the culprit that makes `caretRangeFromPoint` not work on iOS. Looks like this is a known issue - see [fixed chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=263813) and [open webkit bug](https://bugs.webkit.org/show_bug.cgi?id=119711). Just tested in Safari on my mac (not iOS) and it also has this issue.

To Reproduce:
* Open safari and visit https://prosemirror.net/
* Run (via console): `view.root.caretRangeFromPoint(30, 200)` -> should work
* Add `-webkit-user-select: none;` to the body
* Run command again in console -> should return null

> That makes no sense -- posFromCaret is only called when caretRangeFromPoint or caretPositionFromPoint was called.

Woops! I meant `posFromElement`. In my copy of prosemirror-view, I've temporarily prevented the feature detection causing it to fall back to `posFromElement` which works beautifully.

**Comment by marijnh** [comment]
Attached patch should help with this.

> why not use that for everything? 

Because it's slow and in some cases not as accurate as the browser's native algorithm.
