### ISSUE TITLE
IE11 EmptyTextNode doesn't have the "contains" method

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#605]
**Browser:** IE11 / 11.0.9600.17416 / 11.0.14
It's not an issue for Chrome, Edge

**ProseMirror packages versions:** 0.19 and 0.19.1 (all latest version as for today)

Error occurs here: https://github.com/ProseMirror/prosemirror-model/blob/c39bc8c23f7a49820af7c0ea72853c816cae596c/src/from_dom.js#L551. And there is `findAround` method which uses contains as well.

Gif showing how to reproduce:

![ie11-contains-issue](https://cloud.githubusercontent.com/assets/200119/24481866/17299f70-1539-11e7-9689-61f9037b13ed.gif)

The problem is that EmptyTextNode doesn't have the contains method in IE11. You can verify that by running in IE11's console:
```js
document.createTextNode("").contains
```

**Comment by marijnh** [comment]
Thanks for reporting! Patch https://github.com/ProseMirror/prosemirror-model/commit/cd4bae251d94cafb74f7bca7356eeadfe6b3db7d should help

**Comment by d4rkr00t** [comment]
Cool, thanks!
