### ISSUE TITLE
Text with a mark is disappearing when typing (Firefox 46.0.1)

### ISSUE THREAD

**Issue by jspn500** [ProseMirror/prosemirror#606]
Hey @marijnh, please have a look at the screenshot below.

![oy4uwpg0q2](https://cloud.githubusercontent.com/assets/26512812/24537534/8291b90a-162e-11e7-9d90-95db0499b2fd.gif)

Thanks.

**Comment by marijnh** [comment]
I can reproduce this with 0.19, but not with the current code. Please test again when 0.20 is out, to see if that also fixes it for you.

**Comment by jspn500** [comment]
Will do, thanks.

**Comment by marijnh** [comment]
0.20.0 is out, let me know if you still see this.
