### ISSUE TITLE
Cannot delete text with a mark

### ISSUE THREAD

**Issue by jspn500** [ProseMirror/prosemirror#608]
Hey @marijnh, I've found that version 0.19.1 has introduced the following problem:

Toggle a mark, write some text, untoggle the mark, your cursor is on the boundary of the mark. Try to delete it with backspace. It doesn't delete the marked text in Firefox 46.0.1 and IE Edge/11.

I cannot reproduce it on prosemirror.net, because apparently it is running on 0.19.

It would be nice if you could have a look.
Thanks

**Comment by marijnh** [comment]
Does attached patch work for you?

**Comment by torifat** [comment]
I have tried the patch. It's working fine in Firefox 👍 Couldn't check in IE because `moduleserve/load.js` is throwing some error there.

**Comment by marijnh** [comment]
IE unfortunately doesn't really handle moduleserve, no. Closing this on the assumption that the problem was the same there. If someone wants to build a bundle to make sure, let me know what the effect was.

**Comment by torifat** [comment]
^ I have just updated my comment 😄

**Comment by jspn500** [comment]
Thanks a lot for the quick fix, @marijnh
