### ISSUE TITLE
Input rule still working after setting code: true

### ISSUE THREAD

**Issue by jchappypig** [ProseMirror/prosemirror#611]
Hi Marijn,

It seems like input rule still be applied while we set the node to be a code node. The input rule was disabled on 0.10.0 if it's a code node. Is there any reason we don't have that convention anymore? or it's a bug.

Cheers,
Huanhuan

**Comment by marijnh** [comment]
That logic was dropped when I rewrote input rules for 0.11, since it seemed too special-case. Is this creating problems for you?

**Comment by jchappypig** [comment]
Ah. that's fine then if that is not a desirable behavior for prosemirror. We can add logic for customized behavior like this.  Thank you, Marijn. I will close this.
