### ISSUE TITLE
Codeblock removes new lines | 0.20 | Chrome

### ISSUE THREAD

**Issue by jspn500** [ProseMirror/prosemirror#612]
Hey @marijnh, I've spotted a new bug.

Version: **0.20**
Browser: **Chrome, FF**
Description: 
1) create a code block with ```
2) type a text and hit enter
3) type something else. It will remove the new line.

![codeblock_bug](https://cloud.githubusercontent.com/assets/26512812/24692262/82563f24-1a1b-11e7-9417-9dcbc881fa3e.gif)

Thanks

**Comment by marijnh** [comment]
Already fixed in 0.20.1
