### ISSUE TITLE
hasFocusAndSelection (prosemirror-view) can fail in Shadow DOM in Chrome 57

### ISSUE THREAD

**Issue by bedeoverend** [ProseMirror/prosemirror#614]
So I'll intermittently get: `Uncaught TypeError: Cannot read property 'nodeType' of null` when working with an editor inside Shadow DOM. Error originates from [this line](https://github.com/ProseMirror/prosemirror-view/blob/master/src/selection.js#L285)

It looks like the root issue is that when getting the selection inside of a Shadow Root, it can sometimes have `rangeCount > 0` but have an `anchorNode === null`. Looks like even when the shadow root blurs, the `range` isn't removed from the selection.

I've done a demo of it happening here [bin here](https://www.webpackbin.com/bins/-KhL241e0RmTJNmpL202). To see it happening, do the following:

- Make sure the log is open (see top toolbar of webpack bin) 
- Click on the editor text to focus it (bordered in red)
- Click outside of the editor

You should see:
1. prosemirror-view throw an error as described above
2. It logging that it has a `rangeCount` of 1, but no `anchorNode`

Browser: Chrome 57
Prosemirror:
- view: 0.20.2
- state: 0.20
- schema-basic: 0.20
- model: 0.20

**Comment by marijnh** [comment]
Oh, interesting. webpackbin is crashing on load for me, and I can't interact with it.

Does changing that line to  check for `.anchorNode` instead of `.rangeCount` work around the issue?

**Comment by marijnh** [comment]
Oh, you already proposed that patch. Yeah, that should work.

**Comment by bedeoverend** [comment]
@marijnh ah sorry, Webpackbin is great _when_ it works...only cloud `bin` thing I've found that works so well with modules.

Anyway - yeah have updated that PR to just check for `anchorNode` instead of `rangeCount`
