### ISSUE TITLE
Non-clickable contenteditable=false node in Safari

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#615]
Version: 0.20
OS: 10.11.6
Safari: 10.0

If you have a `contenteditable=false` node at position 0, it will not respond to click events. The `mouseup` event does not seem to fire on `view.root`. Commenting out https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L509 makes it clickable again.

**Comment by wes-r** [comment]
@marijnh If you need help reproducing let me know! I'm also not really sure where to begin looking into the code for where this might be getting caused.

**Comment by marijnh** [comment]
Inserting a horizontal rule at the start of a document seems like it would satisfy your description, but if I do that, clicking to focus it works fine, also on Safari.

**Comment by wes-r** [comment]
Hmmm I'll have to try and create an example setup for you. I just did some reverting and found that this broke for me when I went from 0.19 to 0.20.

**Comment by wes-r** [comment]
Alright well I don't have an isolated reproduction yet but it appears that this started happing in 0.20.0 AND only happens in safari/iOS when the node has `user-select: none` and is at the top of the document. Very weird! The `handleClickOn` event never fires in this case, but normal javascript listeners still do.

**Comment by wes-r** [comment]
OK looks like the root cause is our good friend `posAtCoords()` again. For some reason the combination of:
* `contenteditable=false`
* `user-select: none`
* being first element in doc
* Safari / iOS

makes `document.caretRangeFromPoint()` not return the correct dom node. For me it is returning a div outside of my editor.

Adding `if (pos == null && node) pos = posFromElement(view, elt, coords)` above https://github.com/ProseMirror/prosemirror-view/blob/master/src/domcoords.js#L189 fixes it for me, would this be a reasonable solution?  Basically if by caret didn't work, we should try by element!

**Comment by marijnh** [comment]
Does attached patch help?

**Comment by wes-r** [comment]
I believe it will, thank you!
