### ISSUE TITLE
Pasting inside code block is broken | IE 11/Edge

### ISSUE THREAD

**Issue by jspn500** [ProseMirror/prosemirror#617]
Hey @marijnh, I know how painful this issue is, but we found that all our tests related to paste event inside code block are failing in v.22, IE Edge and IE 11. 

Currently we're using v0.19.2 and it is working fine. I assume it is related to changes made in this commit: [https://github.com/ProseMirror/prosemirror-view/commit/1a0b7fd38ee7b5380495a3445a7ae90be86b9039](url)

For testing we use `editorView.dispatchEvent(event)`, where event is a custom paste event with clipboardData property.

I would be grateful if you could have a look. Thanks!

**Comment by marijnh** [comment]
I hadn't properly considered the plain-text-paste case in the previous fixes. Should be better now. The fix is released as 0.20.3

**Comment by marijnh** [comment]
Oh, and relevant patch: https://github.com/ProseMirror/prosemirror-view/commit/abeb84d548cb44161d7843cd4a1ae72b74b2d164

**Comment by jspn500** [comment]
Just tested, didn't help. It stopped working from version 0.20. I'll try to track what exactly broke IE and let you know later today.

**Comment by jspn500** [comment]
Seems like our tests fail before the setTimeout statement in "capturePaste" function, which makes paste even asynchronous. If I put a debugger inside, target.value is still empty after 50ms.  

I also tested with 0.20.3 but used your previous solution with "fromClipboard" from 0.19.1 and it makes our tests pass (maybe breaks something else that we don't have tests for yet). 

I hope it helps to find the right approach.

**Comment by marijnh** [comment]
Could the failure be an artifact of your testing approach? Pasting into code blocks works well for me when I do it manually in Edge now.

**Comment by jspn500** [comment]
`setTimeout()` will run asynchronously after finishing current execution block. It execution depends on the number of awaiting tasks in the call stack (queue of tasks) and runs when the current stack is cleared and after n milliseconds have passed. 

In the following example, the output is `1,3,2`:
```
console.log('1');
setTimeout(function () {
  console.log('2');
});
console.log('3');
```

Now consider our test scenario: 
1) our test dispatches paste event 
2) `setTimeout(function () { ... doPaste () ...}, 50)` inside `prosemirror-view` -> `capturePaste` function fires
3) our test checks the actual and expected result by comparing `editorView.state.doc`

It fails because of the same reason we have 1,3,2 in the previous example.

If I test pasting manually in the browser, it works well. If I put `setTimeout` inside tests to delay `expect`, it would make our tests incredibly slow, because we run them in 7 browsers for each build. 

It would be awesome if you could come up with a solution without `setTimeout` so we could have tests for it. 

Another option that I consider is using your previous approach from 0.19.2 without setTimeout, but for us it would mean patching the `prosemirror-view` each release, which I'd rather avoid doing. Thanks a lot!

**Comment by marijnh** [comment]
> It would be awesome if you could come up with a solution without setTimeout so we could have tests for it.

We need to let the native paste behavior happen, and then inspect the result. This happens asynchronously at some point shortly after the `paste` event fires. I don't believe there's a way to make this synchronous.

**Comment by jspn500** [comment]
I agree that in current approach with fake textarea its not going to be synchronous. 

However, In 0.19.2 you had different approach (`fromClipboard` method) that used to work without setTimeout. I thought maybe there is a way to combine those two in order to get rid of asynchrony?

**Comment by marijnh** [comment]
I don't really want to complicate my code just to make a given test setup easier, sorry.

**Comment by jspn500** [comment]
Fair enough. Is there a chance you could provide us with a callback/trigger an event when the `doPaste` fires? So I could hook into this from the test?
