### ISSUE TITLE
Impossible to type some characters

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#619]
Trying to type this character: ∂ doesn't work in the end of the paragraph.

How to reproduce:
* Go to https://prosemirror.net
* Press alt+d (on mac)
* If cursor is at the end of the paragraph you won't get any character appeared in the editor.
* if cursor isn't at the end of the paragraph you will get ∂ character.

Tested in: latest Chrome, latest Firefox, latest Safari.

![kapture 2017-04-13 at 13 39 40](https://cloud.githubusercontent.com/assets/200119/24989333/2acb89b4-204f-11e7-80d3-e207c4d68ab0.gif)

It isn't something critical, but just FYI. :)

**Comment by wes-r** [comment]
Can confirm! Oddly enough all other alt-characters seem to work at end of paragraph, it is specifically `alt-d` that fails in this case.

**Comment by marijnh** [comment]
I somehow, probably by taking information from some other outdated keymap, was under the assumption that alt-d was an alternate binding for delete on OS X, but indeed, that doesn't seem to be the case. Attached patch removes the code to prevent alt-d at the end of a paragraph.

**Comment by d4rkr00t** [comment]
Awesome! Thanks 👍
