### ISSUE TITLE
Consider updating Selection documentation re: instantiating the superclass

### ISSUE THREAD

**Issue by emilschutte** [ProseMirror/prosemirror#621]
It looks like since https://github.com/ProseMirror/prosemirror-state/commit/94591cdec8b18e7b20272e336830aa5b13c7df8c#diff-b6c9a2c2a15c4a4c9f48852103abbee7 the Selection superclass lost `eq`, making it unsafe to use directly.  In our case, we had some old code that was doing `new Selection(...)` to select the whole document.  That's now handled by `AllSelection`, but it might be good to put a note in the docs warning people not to instantiate Selection directly anymore.  The docs for `eq` also refer to a default implementation that AFAICT doesn't exist anymore.  I'm happy to take a stab at any of this if you like.

**Comment by marijnh** [comment]
Thanks for pointing that out. Does attached patch address your concerns?

**Comment by emilschutte** [comment]
Yep!  Thanks for the quick reply.
