### ISSUE TITLE
Error when adding a new footnote

### ISSUE THREAD

**Issue by frederik** [ProseMirror/prosemirror#622]
When adding a new Footnote (e.g. the content is Fragment.empty) an error is thrown using the current implementation of the footnote example (reproducible on the website demo).

1. Create a new footnote
2. Type anything

```
prosemirror.js:137 Uncaught TypeError: Cannot read property 'size' of undefined
    at t.ViewDesc.parseRange (prosemirror.js:137)
    at parseBetween (prosemirror.js:119)
    at readDOMChange (prosemirror.js:119)
    at DOMChange.finish (prosemirror.js:119)
    at prosemirror.js:119
```

I am assuming this is new since ProseMirror 0.20

**Comment by marijnh** [comment]
Patch https://github.com/ProseMirror/prosemirror-view/commit/f902ef20403f5f1d89d4a3966f7b370bf845b811 should help with that

**Comment by frederik** [comment]
Thanks. Working in 0.21
