### ISSUE TITLE
Backspace in footnote NodeView clears the footnote

### ISSUE THREAD

**Issue by frederik** [ProseMirror/prosemirror#623]
When setting the cursor at the first position (0) in any existing footnote and then hitting backspace, the footnote is cleared, the text is added in front of the footnote and the footnote is then empty.

Expected behavior would be that nothing happens.

This is reproducible in the footnote demo on the website (probably even before 0.20)

**Comment by marijnh** [comment]
You're backspacing out the separation between the footnote and the outer text. You can bind a backspace handler in the inner editor that prevents this from happening, if you want.

**Comment by frederik** [comment]
Thanks. That worked for us. Would you like a pull request on the demo or resolve this as won't fix?

**Comment by marijnh** [comment]
A pull request would be wonderful. Did you also handle delete at the end, ctrl-backspace, etc?

**Comment by frederik** [comment]
I do handle Delete/Ctrl-Backspace when in last position. If you have any more suggestions, I am open to that.

**Comment by marijnh** [comment]
Solved by https://github.com/ProseMirror/website/pull/58
