### ISSUE TITLE
Deleting decorated text throws uncaught error in Firefox under certain circumstances

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#624]
I can reproduce the following issue in Firefox 52.0.2 on Linux.

I'm using a very simple schema:
```javascript
const textSchema = new Schema({
  nodes: {
    doc: {content: 'text*'},
    text: {
      group: 'inline',
      toDOM(node) { return node.text },
    },
  },
})
```

The document contains only the text "Untitled" with an inline decoration from start to end. The DOM looks like this:
![ff_bug_1](https://cloud.githubusercontent.com/assets/152507/25267401/eb998580-2674-11e7-8380-dd82f82f3c17.png)

Selecting the whole text (put cursor at the end and press `Shift+Pos1`) and then pressing `Backspace` results in the following uncaught error:
![ff_bug_2](https://cloud.githubusercontent.com/assets/152507/25267446/1c2687b6-2675-11e7-94a0-f54ea7b55ad1.png)

I can also trigger this error with the text "Untitled Page" where both words are decorated. The DOM looks like this:
![ff_bug_3](https://cloud.githubusercontent.com/assets/152507/25267525/6672f5ca-2675-11e7-9c05-411d1c66c951.png)
Selecting either the whole text `"Untitled Page"` or just `" Page"` (with the leading space) and pressing `Backspace` results in the same error.

**Comment by marijnh** [comment]
I can't reproduce this. Can you provide complete example code?

**Comment by kiejo** [comment]
Sure, I'll try to set up a minimum example with the complete code!

**Comment by kiejo** [comment]
Here is the complete example code to reproduce the error in Firefox. I replaced the content of the `demo/demo.js` file of the main repo with the following code:

```javascript
const {Schema, DOMParser} = require("prosemirror-model")
const {EditorView, Decoration, DecorationSet} = require("prosemirror-view")
const {EditorState} = require("prosemirror-state")

const textSchema = new Schema({
  nodes: {
    doc: {content: 'text*'},
    text: {
      group: 'inline',
      toDOM(node) { return node.text },
    },
  },
})

let state = EditorState.create({
  schema: textSchema,
  doc: textSchema.nodes.doc.create(null, textSchema.text('Hello World'))
})

let view = window.view = new EditorView(document.querySelector(".full"), {
  state,

  decorations(editorState) {
    const text = editorState.doc.textContent

    const decos = []
    const wordRegex = /(\s*)([^\s]+)/g // Get all words separated by whitespace
    let match
    while ((match = wordRegex.exec(text)) != null) {
      const start = match.index + match[1].length // Add matched leading whitespace length
      decos.push(Decoration.inline(start, start + match[2].length, {class: 'tag'}))
    }

    return DecorationSet.create(editorState.doc, decos)
  },
})
```
This code creates an inline decoration around each word of the doc.

**Comment by marijnh** [comment]
Thanks, I can reproduce it now (I was doing ctrl-a instead of shift-home to select before, which didn't trigger this). Attached patch seems to fix it.

**Comment by kiejo** [comment]
Thanks for fixing this so fast!
