### ISSUE TITLE
Pasting only HTML table doesn't work properly

### ISSUE THREAD

**Issue by jezell** [ProseMirror/prosemirror#625]
If pasting an HTML table:

`<table><tbody><tr><td>b</td><td>c</td><td>d</td></tr><tr><td>1</td><td>2</td><td>3</td></tr><tr><td>a</td><td>c</td><td>b</td></tr></tbody></table>`

Result is that the first cell is inserted as paragraph instead of cell. However, if an empty paragraph or other content appears before table in pasted data:

`<p></p><table><tbody><tr><td>b</td><td>c</td><td>d</td></tr><tr><td>1</td><td>2</td><td>3</td></tr><tr><td>a</td><td>c</td><td>b</td></tr></tbody></table>`

Then the content is pasted properly.

Steps to reproduce:

1. Insert table
2. Select only table
3. Cut or copy table
4. Paste

**Comment by jezell** [comment]
Note, this appears to be due to openLeft and openRight values on slice (they are both initialized to 3 in this case). This is pretty hacky but it makes it paste properly:

```
  transformPasted: function(slice) {
            let openRight = slice.openRight;
            let openLeft = slice.openLeft;
            if(slice.content.size > 0 && slice.content.child(0).type.name == "table") {
                openLeft = 1;
                openRight = 1;
            }
            return new Slice(slice.content, openLeft, openRight);
        },

```

**Comment by marijnh** [comment]
(Just wanted to acknowledge this problem. I'm not sure what the solution would look like yet, and it may be some time before I can put work into it.)

**Comment by marijnh** [comment]
The issue came up in another context as well, so I've tried to attack it. Attached patch should help with this -- but it depends on changes in the model module as well. I'll try to do a 0.21 release soon.
