### ISSUE TITLE
caret stays before transform with prosemirror-view@0.20.4 and a text plugin

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#626]
Hi,
i have a simple plugin that inserts hard breaks when pressing Enter, unless two consecutives hard breaks are typed, in which case they are deleted and default behavior (insert paragraph) happens.
(https://github.com/kapouer/pagecut/blob/master/src/break-plugin.js).
In prosemirror-view 0.20.4, the plugin places caret *before* transformations, so pressing enter inserts a hard break but the caret stays before it. Reverting to 0.20.3 restores the expected behavior, all other things being equal.

**Comment by marijnh** [comment]
I think attached patch should help with this (I could reproduce your issue and this fixed it).

**Comment by kapouer** [comment]
works here too !
