### ISSUE TITLE
Tapping 'return' key should autocapitalize on iOS

### ISSUE THREAD

**Issue by owjsub** [ProseMirror/prosemirror#627]
In a [vanilla contenteditable](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_global_contenteditable) on iOS, tapping the keyboard 'return' key will capitalize the next character entered. But this is not working in ProseMirror 0.20.4 on iOS.

Repro Steps:
1. Open the ProseMirror Demo on iOS Safari
2. Enter some text
3. Press 'return' on the keyboard
4. Enter some text (observe the first character is not capitalized)

Additional Notes:
- This issue does **not** repro in ProseMirror on Android.
- Related to #25
- Related to issue in CKEditor: https://dev.ckeditor.com/ticket/12142

**Comment by marijnh** [comment]
Yeah, this is #310, which was prematurely closed. It is, at its root, a Mobile Safari bug, and one that's really difficult to work around.
