### ISSUE TITLE
Draggable Nodes should get html5 attribute "draggable=true"

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#628]
Chrome v58.0.3029.81

From https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable:
> By default, only text selections, images, and links can be dragged.

Ran into an issue today where I had a div that wasn't draggable. Turns out only some elements are draggable by default, otherwise they need `draggable=true` or an `ondragstart` event bound to the element. To address this, I propose ProseMirror adding this attribute for nodes that are marked with `draggable: true`. This attribute would then not be output when serializing.

**Comment by marijnh** [comment]
ProseMirror swaps in the draggable attribute when you start to actually drag, and it definitely does register a dragstart handler. Could you be more specific about the issue you're encountering?

**Comment by wes-r** [comment]
I have roughly the following draggable node:
```
<figure>
  <div class="placeholder">
  </div>
</figure>
```

Where placeholder is a 300x300 gray div. The bug is that I cannot drag this thing! To work around the issue I've essentially implemented my proposed solution but only for my figure nodes. So I manually add "draggable=true" to them and manually remove that attribute when saving.

**Comment by marijnh** [comment]
Is this still an issue? If so, can you provide me with a self-contained script that helps reproduce it?
