### ISSUE TITLE
Do something intelligent with selection on undo/redo

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#63]
We may want to reset to the selection that existed when the action was originally done. Right now it just maps the current selection to the updated document, which is solid, but not what users expect.

**Comment by ericandrewlewis** [comment]
Investigating how other editors work to add workflow examples to the discussion:

Google Docs restores selection on undo/redo if a modifying action was made on the selection. [See video](https://www.youtube.com/watch?v=Wp9qN3iNsqk&feature=youtu.be)

**Comment by ericandrewlewis** [comment]
When undoing a text deletion, it makes sense to set selection to the previously deleted text. The user is stepping back in time through the drafting of the document, and wants to continue from just before the deletion took place. So why not place them in that context, and let them decide where to go from there?

I think this logic makes sense for other transforms: reverting a node-type change from Paragraph to Heading 1, set selection to the entire paragraph. Are there other transforms where this might be awkward?

**Comment by ericandrewlewis** [comment]
Does this make sense?

**Comment by marijnh** [comment]
I think a more reasonable behavior (which CodeMirror and most text editors that I'm aware of implement) is to store the selection right before the start of a history event (a set of changes that are batched together to be undone together), and reset to that when the event is undone. The question then is what the corresponding redo event gets as its 'selection before'. You could take the selection that was active when undo was activated, which is also what CodeMirror does.

Of course, this selection would then have to be rebased along with the changes in the history event, adding a bit more complexity to an already complex module, but I think that should fit quite well in the remapping pipeline as it currently is.

**Comment by ericandrewlewis** [comment]
That all sounds great.

Do you have any preferences on how this should be implemented in branch history, or lessons learned from CodeMirror's history implementation?

To take the approach CodeMirror does, we could add selection events in history branches, along-side step events.

I notice CodeMirror stores every selection change in history. I'm not sure how that granularity is useful. Would having one selection between each pair of step events be enough?

**Comment by marijnh** [comment]
CodeMirror has selection undo. I don't think we want that, so we can just store one selection per event, as an extra field (which is much easier).

**Comment by ericandrewlewis** [comment]
Let's outline scenarios for expected behavior.

Here's the simple one:

1. Given document "abc"
2. Select "bc"
3. Delete the selection
4. Undo
5. Selection should return to "bc"

What would the scenario be for returning a selection after a redo event?

**Comment by marijnh** [comment]
I would be okay with undo storing the selection that was active when the undo started in the redoable event. It'd be consistent, and usually match what people want (redoing directly after undoing would get you back to your old state)

**Comment by ericandrewlewis** [comment]
What do you think of [this approach](https://github.com/ericandrewlewis/prosemirror/commit/60f8a6fe7298232c8e4f4124d891a48b161be6d1)? 

Making `event` a bit more decorated object, which stores both steps and selection state.

Currently sorta works for undo. If we like this approach I'll tidy it up.

**Comment by marijnh** [comment]
Looks like the right direction.

You'll have to map selections through the remapping in `popEvent` though. Otherwise, if there were changes that weren't added to the history, you'll end up with a potentially invalid selection. (Write lots of tests.)

And the compression worker will have to be made aware of the new format, and do something with selections as well.

Also, feel free to have the `"transform"` event pass the old selection to handlers, to avoid the need for the `selectionBeforeTransform` kludge. It seems the new selection would work well as an argument to `newEvent`.

**Comment by ericandrewlewis** [comment]
Thanks for the feedback! I've opened up #233 with a working prototype with that in mind.

I figure I should put tests in the existing `[test-history.js](https://github.com/ProseMirror/prosemirror/blob/master/src/test/browser/test-history.js)`. However it looks like `npm run test` doesn't run these tests. Anything I should know about how these tests are run?

**Comment by marijnh** [comment]
Done in #233. Thanks, Eric!
