### ISSUE TITLE
IE11 only supports setData("text", data)

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#632]
https://github.com/ProseMirror/prosemirror-view/blob/26cfaa17e485f9c549f8d31466d32b7a9ecdd4b3/src/input.js#L392 will yield an error in IE11 due to IE11 foolishly only supporting the "text" format.

This is low priority for me as I've implemented my own handlers and essentially wrap my setData/getData to use "text" for IE.

**Comment by marijnh** [comment]
`brokenClipboardAPI` should be true on IE, so that that statement is never reached. Are you spoofing a user agent by any chance?

**Comment by wes-r** [comment]
Ah looks like it was only my code that had a path to some `setData` code.

Closing.
