### ISSUE TITLE
Weird selection behavior

### ISSUE THREAD

**Issue by torifat** [ProseMirror/prosemirror#634]
![kapture 2017-05-05 at 17 54 56](https://cloud.githubusercontent.com/assets/208544/25737612/21a9c5a2-31bc-11e7-8675-c1502452b4a4.gif)

For some reason this is not happening with `emphasis` 😕

We have some other marks in our editor. And, it's happening with those too.

**Comment by marijnh** [comment]
Could you describe what you're doing, precisely? Trying to guess reproducing steps from a screencast isn't a hobby of mine.

**Comment by torifat** [comment]
Steps:

* type `ant bat cat`
* make `ant` code
* make `bat` code
* make `cat` code
* select `ant bat cat`
* bold
* now when you toggle bold again the selection changes and only select the first word

Doc:

`p(text('ant', [code]), text(' '), text('bat', [code]), text(' '), text('cet', [code]))`

**Comment by marijnh** [comment]
Which browser? I'm not getting the issue in Firefox or Chrome on Linux.

**Comment by torifat** [comment]
I could reproduce it in `Chrome Version 58.0.3029.96 (64-bit)` but not in Firefox or Safari.

**Comment by torifat** [comment]
You have to select `ant bat cat` though, not `ctrl/command+a`. Apparently manually selecting from beginning to end and select all produces different selection.

**Comment by marijnh** [comment]
Still no luck in Chrome 57.

**Comment by torifat** [comment]
It is working in `Chrome Version 59.0.3071.115 (64-bit)`
