### ISSUE TITLE
Weird behaviour of inclusive=false marks

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#636]
I slightly modified prosemirror-schema-basic so code is inclusive=false and the issues is the same for links as well.

How to reproduce:
* Put cursor after link mark
* Press backspace once
* Start typing

Results:
You will get first character as a part of a link mark and all following characters are not a part of the mark.

What I expected:
None of the characters will be a part of the mark.

Tested:
OSX: Chrome 58.0.3029.96, Safari 10.1, FireFox 53.0 

![inclusive_false](https://cloud.githubusercontent.com/assets/200119/25785539/c2258e24-33c6-11e7-91e7-b4fa9a1fc75d.gif)

**Comment by marijnh** [comment]
Attached patches address this
