### ISSUE TITLE
Backspace in nested list broken.

### ISSUE THREAD

**Issue by jpuri** [ProseMirror/prosemirror#637]
Prose-mirror command version: `"prosemirror-commands": "^0.20.0"`.

Cursor is lost when hitting backspace in beginning of a list item in nested lists.

![list_issue](https://cloud.githubusercontent.com/assets/2182307/25790940/80969124-33da-11e7-9c94-354ad5b08304.gif)

**Comment by marijnh** [comment]
Which browser?

**Comment by jpuri** [comment]
We faced it in chrome.

**Comment by marijnh** [comment]
What I see when this happens is a node selection on the list item before the current one. Could it be that you didn't include the css that styles node selections?

**Comment by marijnh** [comment]
I did some tweaking on backspace behavior (see [here](https://discuss.prosemirror.net/t/suitable-backspace-command-for-lists-with-restricted-schema/891) and #687). I'm going to close this until further info comes in, but feel free to comment/reopen.

**Comment by jpuri** [comment]
Thanks Marijn I will try out this patch.

**Comment by hamflx** [comment]
The issue still seems to exist: <https://github.com/ueberdosis/tiptap/issues/2829>
