### ISSUE TITLE
`posAtCoords` (and thus event handlers) throws with coordinates outside of main editor area

### ISSUE THREAD

**Issue by adrianheine** [ProseMirror/prosemirror#638]
This is a regression introduced in ProseMirror/prosemirror-view@4276038c1d64bc9e500fbe999b8b4d7bee0d39be (i. e. `0.19.0`).

Use case
----
Decorations that are positioned outside the editor's rectangle (toolbars, for example). Example DOM:
* `.ProseMirror`
  * Paragraph
  * `.ProseMirror-widget`
  * Paragraph

Description
----
Clicks on such decorations are handled by `mousedown` and `contextmenu` in `src/input.js`. Both try to find a position with `posAtCoords`, which calls `posFromCaret`. In `posFromCaret`'s loop, `cur` (`.ProseMirror-widget`) is checked against `.ProseMirror`, which passes. Then, `nearestDesc` is called on `cur`. The `ViewDesc` it returns will be the one for the root node. If that is a block element (always?), for left outside positions the `desc`'s `docBefore` property is retrieved, which calls a method on `this.parent`. For the root node's `ViewDesc`, `this.parent` is null.

**Comment by marijnh** [comment]
Does attached patch prevent the issue for you?

**Comment by adrianheine** [comment]
Yes, thanks, that's what I came up with, too :)
