### ISSUE TITLE
Not all xml tagnames are allowed in ProseMirror schemas

### ISSUE THREAD

**Issue by vandenoever** [ProseMirror/prosemirror#641]
ProseMirror parses node type names in schemas 'content' property with the JavaScript RegEx `\w` which is `[A-Za-z0-9_]`. XML allows many more characters in tags [1]. The characters '.' and '-' are used in XML tags quite often. It would be convenient if the lexical space for those names would be the same as the one for the tags themselves.

[1] https://www.w3.org/TR/2004/REC-xml11-20040204/#NT-Name

**Comment by marijnh** [comment]
Where exactly does it parse XML tags?

**Comment by vandenoever** [comment]
I have nuanced the claim in the description: s/tags/type names.

Not the tags themselves, but the names that can be used for the tags. Suppose you want a schema with tag `<one-two>`. A convenient schema definition would be:
```
nodes = {
   "one-two": { ... },
   doc: { content: "one-two*" }
}
```
The 'one-two' in the example is not the tagname, but the name for the type in the schema. A workaround is to use a name like oneTwo.

It would be convenient if the lexical space for those names would be the same as the one for the tags themselves.

https://github.com/ProseMirror/prosemirror-model/blob/master/src/content.js#L89

**Comment by marijnh** [comment]
ProseMirror is not really XML-based, and it should be easy enough to generate `\w+`-style names for your XML elements, so no, I don't want to complicate the naming scheme for this use case.
