### ISSUE TITLE
Can't delete empty code block under a list / beginning of doc

### ISSUE THREAD

**Issue by mhuebert** [ProseMirror/prosemirror#642]
Under a bullet list, it doesn't seem possible to delete a code block - the empty block remains, and the cursor jumps upwards.

Example from the ProseMirror demo:

https://youtu.be/jugNl-2M09E

Further:
- The same thing happens with a code block under a table. 
- If a code block is at the beginning of a document, it can't be deleted.

I would expect the code block to behave like a blockquote -- if it is empty, backspace should simply delete it.

\*maybe related - an empty paragraph under a table has the same behaviour. Pressing backspace in the paragraph selects the table, instead of deleting the paragraph.

**Comment by marijnh** [comment]
This seems to have been fixed in the current code.
