### ISSUE TITLE
Parsing XML Node with Tables in Edge Fails

### ISSUE THREAD

**Issue by jordandh** [ProseMirror/prosemirror#646]
**Version:** Prosemirror 0.21.0
**Browser:** MS Edge 40.15063.0.0

**Issue**
Parsing an xml node containing a table with the DomParser throws an error in Edge.

**Expected Behavior**
The xml node is parsed correctly without throwing an exception.

**Demo**
https://plnkr.co/edit/4SE2Lqv9mBvH4mYuM6vq

From what I can tell the code throwing the exception is the table schema. The getAttrs functions use  dom.children to get the column length. The children property does not exist on xml nodes in Edge. The best solution may be using the childNodes property instead of the children property. However, childNodes includes all child nodes, including non-element nodes like text and comment nodes. So that could fail to determine the correct number of columns without extra checks.

**Comment by marijnh** [comment]
The schema-tables module is being deprecated, so I'm going to close this.
