### ISSUE TITLE
NodeView gets reconstructed

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#647]
While working with codeblocks using CodeMirror, I noticed my codeblock's NodeView sometimes getting reconstructed while I'm editing the document. This causes a very ugly flash as CodeMirror has to be refreshed to draw the code.

The triggers for the reconstruction are a bit weird. Seems like mostly it only happens when I enter multiple new lines ABOVE the code block. It'll also then happen again if I click anywhere to move my cursor.

I'm not sure if this is happening in http://prosemirror.net/examples/codemirror/ as I do not see any flashing.

**Comment by wes-r** [comment]
I don't know this code but my guess my issue has to do with https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L928

Looks like `children[i]` is always

**Comment by marijnh** [comment]
The incremental redrawing algorithm uses some heuristics to figure out which node in the new document corresponds to which node in the old, and since it needs to be fast, and perfect diffing is NP-hard, it's not perfect. If you can give me a minimal test that causes this issue, I can see if it can be improved.

**Comment by wes-r** [comment]
Hmmm I don't think it is the node diffing that is the issue.

Debugging in: https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L926
I've added some print outs and the times that this function returns `false` are when `this.top.children` doesn't any have my `CustomNodeViewDesc` to diff with.

Why would this be? Any pointers for me to further the debugging on this?

And again this doesn't happen while I'm typing OR if I type, hit enter, type, hit enter, etc. It mostly happens when I add two new blank lines. Maybe something to do with the special `BRHackViewDesc` I'm seeing for these empty lines?

**Comment by marijnh** [comment]
> Maybe something to do with the special BRHackViewDesc I'm seeing for these empty lines?

Probably not. It would really help if you can reduce this to a simple test script.

**Comment by wes-r** [comment]
OK I found a bit more of what triggers the bug and I can reproduce it with: http://prosemirror.net/examples/codemirror/

To reproduce:
* Go to http://prosemirror.net/examples/codemirror/
* Add a blank newline at bottom of the document (this is needed!)
* Add more code to the code block (just makes visually seeing the flashes easier)
* Insert blank newlines anywhere above the code block
* Observe that the code block flashes (as it has to get reconstructed / redrawn).

**Comment by marijnh** [comment]
> Add a blank newline at bottom of the document (this is needed!)

Ah, that gives it away -- your added blank line gets matched to the blank line at the bottom of the document, discarding (and then recreating) anything before it, including your custom view.

I recently learned that virtual DOM implementations mostly start with a scan from the end of the node to recognize all nodes that didn't change at the end, and make sure they don't touch those. It might be worthwhile to add such a strategy to ProseMirror.

But do note that node views reinitializing is not something that will ever be guaranteed not to happen. As I said, the diffing is a heuristic process.

**Comment by wes-r** [comment]
Since this is presently expected behavior, I'll go ahead and close this. You can re-open if you want to use it as motivation / book keeping on reworking the diffing to use a bottom up approach (which sounds like it would solve most of my flashing problems).

> But do note that node views reinitializing is not something that will ever be guaranteed not to happen. As I said, the diffing is a heuristic process.

I'm OK with occasional flashes but certainly the fewer the better!

**Comment by marijnh** [comment]
Yeah, definitely keeping this open as a reminder.

**Comment by marijnh** [comment]
Attached patch should resolve this case
