### ISSUE TITLE
NodeView update() with the wrong node is called instead of destroy() for undo command

### ISSUE THREAD

**Issue by 1999** [ProseMirror/prosemirror#648]
We found a problem using NodeViews and Cmd+Z undo command.
Instead of calling destroy() of the NodeView update() is called with a wrong node.

## Our schema

 * doc: prosemirror-schema-basic's doc
 * paragraph: prosemirror-schema-basic's paragraph
 * mediaGroup: block, can have media+ nodes
 * media: inline

We also have a NodeView for mediaGroup nodes.
Reproduce steps:

1) add text line to the document, for example "sfsdfsdfsdfsdf", hit enter (second paragraph is created)
2) add media node into the document on the second line with `view.dispatch(tr.replaceWith(...))`, i.e. replace paragraph with the media node. Prosemirror handles this by wrapping the media node with the mediaGroup and NodeView is created.
3) add one more line of text under the mediaGroup
4) Cmd+Z - removes the line paragraph from step 3
5) Cmd+Z - we expect to have mediaGroup NodeView to be destroyed here. Instead NodeView object's update() function is called instead for node of different type (paragraph). State document is doc(paragraph, paragraph).

**Comment by marijnh** [comment]
> Instead of calling destroy() of the NodeView update() is called with a wrong node.

This is how `update` is supposed to work -- your update method must decline to update when it's passed a node it can't handle, by returning false.

**Comment by 1999** [comment]
> and should return true if it was able to update to that node, and false otherwise

Probably that's not the best description of this function in this case. I definitely was not expecting this object to get update() call for another type of node.
