### ISSUE TITLE
Broken documentation link for collab

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#649]
On https://prosemirror.net/docs/guides/collab/ there's a hyperlink to more information on rebase:

>  it'll have to rebase its local changes on top

It links to https://prosemirror.net/docs/guides/collab/transform.html#rebasing, but that page does not exist.

**Comment by bradleyayers** [comment]
I suspect it should link to http://prosemirror.net/docs/guides/transform/#rebasing

**Comment by marijnh** [comment]
Indeed. See attached patch.
