### ISSUE TITLE
Wrong getdocs signature in prosemirror-collab

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#650]
https://github.com/ProseMirror/prosemirror-collab/blob/master/src/collab.js#L11

```
// : (Transform, [Rebaseable], [Step]) → [Rebaseable]
// Undo a given set of steps, apply a set of other steps, and then
// redo them.
function rebaseSteps(steps, over, transform) {
```

I think `Transform` should be the type of the last argument?

**Comment by marijnh** [comment]
Right, looks like I changed the argument order without updating the comment. Should be better now.
