### ISSUE TITLE
Single-colon getdocs comments

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#652]
Scattered across various packages there are getdocs comments that use a single colon. The docs on https://www.npmjs.com/package/getdocs only define the behaviour for double colons, so I'm not sure how single colons should be interpreted.

Random guess — private API?

**Comment by marijnh** [comment]
Yes, they show the type of things without actually adding them to the docs (since, as you noticed, getdocs ignores them)
