### ISSUE TITLE
Optional unions renderer ambiguously

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#653]
The getdocs type: `?union<number, string>` is rendered as `?number | string`, which might be misinterpreted as "an optional number, or string".

Occurs in https://prosemirror.net/docs/ref/#collab `config.clientID`

**Comment by marijnh** [comment]
That is somewhat awkward, but logically means the same -- i.e. 'null or (number or string)' and 'null or number or string' denote the same set of values.

**Comment by bradleyayers** [comment]
Ahh of course :smile:
