### ISSUE TITLE
prosemirror-schema-list uses non-public NodeRange API

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#656]
In a few places the non public constructor for NodeRange is used:

- https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.js#L77
- https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.js#L79
- https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.js#L154

We're using these as reference implementations for our own commands, but found that we're using private APIs.

Ideally prosemirror-schema-list would switch to using a the `ResolvedPos.nodeRange` API, or the NodeRange constructor would be promoted to public API.

relates to #609

**Comment by marijnh** [comment]
Good point. Attached patch exports the NodeRange constructor.
