### ISSUE TITLE
PluginSpec.props declared as ?EditorProps, but isn't really.

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#658]
The declaration of PluginSpec.props is as follows:

```
// PluginSpec:: Object
// A plugin spec provides a definition for a plugin.
//
//   props:: ?EditorProps
//   The [view props](#view.EditorProps) added by this plugin.
//   Note that the
//   [`dispatchTransaction`](#view.EditorProps.dispatchTransaction)
//   and [`state`](#view.EditorProps.state) props can't be defined
//   by plugins, only by the main props object. Props that are
//   functions will be bound to have the plugin instance as their
//   `this` binding.
```

The problem here is that natural language is used to describe the type of `props`, rather than the getdocs. This causes problems when trying to automatically translate to TypeScript definitions.

**Comment by marijnh** [comment]
Is the issue that you won't get an error when you try to put a `dispatchTransaction` or `state` into a plugin's `props` spec? If so, that doesn't seem like a big problem.

**Comment by bradleyayers** [comment]
No the issue is that `state` and `dispatchTransaction` are non-optional in `EditorProps`, and in turn are non-optional for `PluginSpec.props`. So you get an error when you *don't* provide them.

**Comment by marijnh** [comment]
Ah, I get it. Would making the props passed directly to the editor a separate sub-interface of `EditorProps`, which defines these additional fields, work for you?

**Comment by bradleyayers** [comment]
That would be perfect :)

**Comment by marijnh** [comment]
Take a look at attached patch.

**Comment by marijnh** [comment]
(Note that it does require upgrading getdocs to 0.6.0 since `extends` syntax didn't exist yet)

**Comment by bradleyayers** [comment]
Looks good! I'd have probably called it `EditorViewProps`, but I'm not too concerned about the name.
