### ISSUE TITLE
setNodeType with new attributes on existing node fails to re-render

### ISSUE THREAD

**Issue by jonsutherland** [ProseMirror/prosemirror#659]
Hi,

I've run into a problem a few times with the most recent code that when you call tr.setNodeType and pass new or change existing node attributes, the node does not re-render in the browser DOM. 

Looking at the PM document and the nodes or the internal state shows that these attributes have indeed updated and are the correct values, however my toDOM for existing nodes does not get called.  Only for brand new nodes in the document.

Is this a known issue or am I doing something wrong?  Seems that trying replace (which appears to do the same thing) I get the same results.

Thank you

**Comment by marijnh** [comment]
Could you provide a piece of example code that demonstrates the issue? I don't see it happen when I use `setNodeType`.

**Comment by jonsutherland** [comment]
Yes I meant to write back that I discovered it seems to be related to when I do this in a transaction I create and return from appendTransaction.  I don't know if that makes any difference, but I will get that sample ASAP.  Thanks

**Comment by jonsutherland** [comment]
When I wrote a simple example I cannot reproduce so the issue is in my code. 

Sorry I'll do the example before I file any more bugs!  Closing

**Comment by jonsutherland** [comment]
If anyone else stumbles on this, my issue turned out to be modifying existing node attrs rather than say using computeAttrs or Object.create / Object.assign to generate a new object for the node attributes before calling setNodeType.  Doh!
