### ISSUE TITLE
Pageup/pagedown sometimes cause a disorienting two-jump scroll

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#66]
Haven't investigated why yet.

Reproduceable on Chrome in the demo in the repository. Focusing the editor and pressing pagedown will scroll down and then slightly scroll up again (sometimes). Same for pageup, once there is room for scrolling up.

**Comment by marijnh** [comment]
I suspect this is related to the floating menu's scroll-cursor-into-view hack.

**Comment by ericandrewlewis** [comment]
Couldn't reproduce this in Chrome 46 or FF 41 on a Mac by clicking in the textarea and then hitting pagedown/pageup (FN+DOWN/FN+UP on a Mac). 

Is there another way I should attempt?

**Comment by marijnh** [comment]
I can't reproduce this anymore either 😕. It appears that d4e41ea accidentally fixed it (I'm not sure why). So that's good.
