### ISSUE TITLE
Want setting option to allow empty text content for custom inline text input node 

### ISSUE THREAD

**Issue by evanzeng** [ProseMirror/prosemirror#662]
I want to define an inline text input field in the editor. I add a node type in the schema as following:
```
inline_field: {
  content: 'text*',
  inline: true,
  group: 'inline',
  selectable: false,
  attrs: {
    id: '',
    name: ''
  },
  toDOM: node => [
    'inlinefield',
    node.attrs,
    0
  ],
  parseDOM: [{
    tag: 'inlinefield',
    getAttrs: dom => {
      return {
        id: dom.getAttribute('id'),
        name: dom.getAttribute('name')
      }
    }
  }]
},
```
But when I set the editor content as
```
<inlinefield id="fieldid" name="fieldname"></inlinefield>
```
 with the following style
```
inlinefield {
  &:before {
    content: '[';
    color: #0000FF;
    margin: 0 3px;
    padding: 0 3px;
  }
  min-width: 15px;
  &:after {
    content: ']';
    color: #0000FF;
    margin: 0 3px;
    padding: 0 3px;
  }
}
```
I get the following effect:
![image](https://user-images.githubusercontent.com/872641/27173275-b7a47d2e-51ea-11e7-8632-e7b24fb461bb.png)

but I can not put the caret in the field. If I set the editor content as
```
<inlinefield id="fieldid" name="fieldname">abc</inlinefield>
```
I get:
![image](https://user-images.githubusercontent.com/872641/27173511-8c15d27e-51eb-11e7-97f3-2157663cfb42.png)

Now I can edit the text in the field, but when I delete all text, the field is also deleted.

Is it possible to provide a setting option to allow empty text content for such custom inline text input node?

Thanks!

**Comment by marijnh** [comment]
What you are seeing is a limitation of browser's `contentEditable` behavior, not something that ProseMirror can help. This is why it is recommended to render inline nodes with content using node views -- the default rendering won't be very useful.
