### ISSUE TITLE
When multiple editors exist, only the last initiated instance works

### ISSUE THREAD

**Issue by erquhart** [ProseMirror/prosemirror#663]
**Summary:**
This bug surfaced when we upgraded the editor (read: all prosemirror packages) in [netlify-cms](https://github.com/netlify/netlify-cms) from ^0.16.0 to ^0.17.0. When multiple editors are on the page, only the last one works. If I re-initialize any of them from within the view (we have a switch that does that as a side effect), it starts working.

**Expected:**
Multiple editors on the same page should still work.

**Actual:**
When typing in any editor except the last to be instantiated, text immediately disappears.

**Research:**
I traced the bug to a line in [prosemirror-model](https://github.com/ProseMirror/prosemirror-model/blob/52bb8cd09545d06822dec487d4993fe4d73d6c2c/src/content.js#L153) where `matchesType` expects the `type` object it receives to be in the `nodeTypes` array. For the last initiated editor, the object is in the array. For all others, it's not.

In my testing, the type we're looking for is the `text` node, which is always present in `nodeTypes` array. An ostensibly identical NodeType is always present in the array, but at some very deep, probably prototypal level, there's a mismatch. I diffed the non-matching objects 50 levels deep, there's no observable difference in the string representations. Lodash's `isEqual` also catches the dissimilarity.

Non-string based diffing did reveal the `Schema` and `ContentExpr` nested in the nodeTypes being compared as distinct, and many of their properties being distinct, such as the various types within the `Schema` and specifically the `getAttrs` method.

**Steps to reproduce:**
* Open the CMS [deploy preview](https://deploy-preview-254--cms-demo.netlify.com/#/collections/posts/entries/new) (just submit the login form blank).
* Type in the three body fields.
* You can toggle the Markdown switch on a non-working editor to get it working (this removes the editor and reinstantiates it).

Also, there's sourcemapping, so you can hit <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>p</kbd> in the Sources panel of Chrome's dev tools and search for "content" to open the prosemirror-model content.js script where I traced the bug to. Break on line 154 to observe the inequality issue described above.

I'm still chasing this down, but wanted to know if anything came to mind for anyone. Thanks for reading!

**Comment by erquhart** [comment]
Here's the spot where we instantiate the `EditorView` (from the PR represented in the deploy preview linked in the OP, also note that plugins were removed for troubleshooting): https://github.com/KyleAMathews/netlify-cms/blob/95db4eb1a0bd723c0757ddbb1366e0d2a90cdf16/src/components/Widgets/MarkdownControl/VisualEditor/index.js#L113

**Comment by erquhart** [comment]
Hmm actually, it looks like this started before the update. Disregard, I'll reopen if it proves to be Prosemirror related.

**Comment by groege** [comment]
@erquhart 
How did you solve the problem?
I've spent hours now to get multiple editors working (though i am using milkdown, which depends on prosemirror)
Hope you can help, thanks :)
