### ISSUE TITLE
cannot insert new line by pressing ⏎ key

### ISSUE THREAD

**Issue by hex13** [ProseMirror/prosemirror#664]
Chrome 59, OSX El Capitan
but checked on Firefox and it's the same.
After clicking return key, this doesn't insert new line (well, sometimes it does, but it's like 1% of trying).

```html
<!doctype html>
<meta charset=utf8>
<link rel=stylesheet href="node_modules/prosemirror-view/style/prosemirror.css">
<style>
 .ProseMirror { background: silver;height:400px;}
</style>
<body>
    <script src="bundle.js"></script>
</body>
</html>
```

```javascript

var EditorState = require("prosemirror-state").EditorState
var EditorView = require("prosemirror-view").EditorView
var schema = require("prosemirror-schema-basic").schema

var view = new EditorView(document.body, {
  state:  EditorState.create({schema: schema}),
});

```
I can paste code from clipboard where there are lines and new lines appear, but not when I write using keyboard.

**Comment by marijnh** [comment]
Yes, the base editor doesn't bind any keys, and thus, by design, doesn't  support things like enter or cross-paragraph backspacing. See the [basic guide](http://prosemirror.net/docs/guides/basics/) for an example of binding keys.
