### ISSUE TITLE
parser confuses elements with the same tag

### ISSUE THREAD

**Issue by vandenoever** [ProseMirror/prosemirror#665]
The parsing algorithm in ProseMirror could be more precise. When an element can be parsed by more than one parseDOM rule, it could take into account nesting rules to distinguish between the elements.

Here is an example with two types of `<p>` element. One may contain only text, the other may contain text or an inline block. The type of the parent determines which type of element is allowed. ProseMirror chooses the first one that parses and calls a wrapping function to make it fit inside the current context.

The code below parses a document `<div><p>hello</p></div>` as `<div><p><block><p>hello</p></block></div>`. It parses the `<p>` element as `p_1` even though the context, `div`, only allows `p_2`. Then it makes the `p_1` fit, by wrapping it in `p_2` and `block`.

```js
const model = require("prosemirror-model")
const JSDOM = require("jsdom").JSDOM
const document = new JSDOM().window.document

const parser = model.DOMParser.fromSchema(new model.Schema({
  nodes: {
    doc: {
      content: "div"
    },
    div: {
      content: "p_2*"
    },
    p_1: { // paragraph that allows only text
      content: "text*",
      parseDOM: [{tag: "p"}]
    },
    p_2: { // paragraph that allows blocks and text
      content: "(block | text)*",
      parseDOM: [{tag: "p"}]
    },
    block: {
      content: "p_1",
      inline: true
    },
    text: {
      inline: true
    }
  }
}))

const div = document.createElement("div")
const p = document.createElement("p")
p.appendChild(document.createTextNode("hello"))
div.appendChild(p)

const doc = parser.parse(div)
console.log(JSON.stringify(doc.toJSON(), null, " "))
```

**Comment by marijnh** [comment]
This is how the parser works, intentionally. If you want to guide it based on context, you can use the [`context`](http://prosemirror.net/docs/ref/#model.ParseRule.context) field in your parse rules.
