### ISSUE TITLE
liftEmptyBlock behavior within an isolating parent

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#666]
When I press enter inside a blockquote which has an **isolating parent** (e.g. table_cell), it does not escape from the blockquote, instead it creates new paragraphs. 

I managed to fix it with the changes below, I hope it'll help to find the right approach:

https://github.com/eshvedai/prosemirror-commands/commit/bb19aa9dd9e8f17775674261a735d19b840c377c
https://github.com/eshvedai/prosemirror-transform/commit/110980fb3df9212b6d64efbf445c4dbfcb5cc627

**Comment by marijnh** [comment]
Thanks. Patch https://github.com/ProseMirror/prosemirror-transform/commit/ed3a4bd719eb7df3b1ed31b4b95af75afcd479ae should address that.
