### ISSUE TITLE
splitListItem does not split the list when cursor is at the end of the list item

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#667]
This behavior has been introduced in `0.22.1`. 
![splitlistitem](https://user-images.githubusercontent.com/26512812/27863291-ca184fca-61cc-11e7-9aff-d979b30457c0.gif)

Steps to reproduce:
1) create a list item with some text
2) put cursor at the end of the text
3) press Enter

Expected: it should create a new list item
Actual: it creates a new paragraph within the same list item

If that's expected, then it is a breaking change since `0.21.0` and should be documented I think.

**Comment by jchappypig** [comment]
It's more natural behaviour that when I hit enter, it would start a new list item. Google doc and dropbox paper are doing the same.

**Comment by marijnh** [comment]
Definitely not expected. I'll look into it later.

**Comment by eshvedai** [comment]
like I said before, one way to fix that would be to make the following change inside `canSplit` method
`let after = (typesAfter && typesAfter[i]) || node`

**Comment by marijnh** [comment]
That was indeed the problem, fixed in attached patch and released as prosemirror-transform 0.22.2

**Comment by marijnh** [comment]
Oh, I meant [this patch](https://github.com/ProseMirror/prosemirror-transform/commit/7d8a28d3fc6ec527360c1830e1c3ba575881dc8e)
