### ISSUE TITLE
Cmd-Alt- modifiers not working

### ISSUE THREAD

**Issue by jpuri** [ProseMirror/prosemirror#668]
We are on PM version `0.21.0`. Key modifiers `Cmd-Alt-` (MAC) and `Ctrl-Alt-` (windows) do not seems to be working. From reading the documentation it looks like they should work.

**Comment by marijnh** [comment]
Seems to work for me on Linux. Could you show what you are doing, precisely?

**Comment by jpuri** [comment]
Ah I see issue is I am writing command as `Cmd-Alt-1` and it does not works but when I write `Cmd-Alt-¡` it works. Seems that I need to write key to that is generated when `Alt` is pressed.

**Comment by marijnh** [comment]
Interesting. Could you see what your browser puts in the `key` property of the `keydown` event? If that's `"¡"`, I guess yes, this is expected behavior (though it does make it hard to bind `Alt-3` in a way that's portable across keyboard layouts).

**Comment by jpuri** [comment]
Yes its `"¡"`. I am also getting little concerned over binding to special characters - as they may not work across keyboards.

**Comment by marijnh** [comment]
Yeah, that's not great. There is the [`code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) property which, on first glance, sounds like it would help with this, but that one ignores keyboard layouts, so when someone sets up a qwerty keyboard as azerty, it'll produce very undesirably behavior by still treating the 'a' as a 'q'. It's hard to implement a general solution for this.

The good news is that you can probably write a custom `handleKeyDown` function which just looks at the raw `event.keyCode` to do what you want here, sidestepping the `keymap` module.

**Comment by Thinkscape** [comment]
Unfortunately, because of the dependency on `KeyboardEvent.key` we are stuck with workarounds like: https://bitbucket.org/atlassian/atlaskit/pull-requests/3370/fix-component-fixing-keyboard-shortcuts/diff#Lpackages/editor-core/test/browser/plugins/block-type/index.tsF381

**Comment by marijnh** [comment]
Hm, that's quite bad. I found that I had a workaround for this issue already when it comes to shift. Attached patch extends it to also kick in when alt or meta/cmd are held. Does that help with your problem?

**Comment by jpuri** [comment]
Hi Marijn,

This patch does seems to work well for us, thx. Would it be possible for you to make a release of `prosemirror-keymap` for us.

**Comment by marijnh** [comment]
Great. I've released prosemirror-keymap 0.22.1

**Comment by jpuri** [comment]
Thanks @marijnh 👍
