### ISSUE TITLE
NPM 5 fails to install the dev setup

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#670]
It was reported on gitter that tying to install this repository with NPM 5.0.4 and 5.1 crashes with 

    Unhandled rejection RangeError: Maximum call stack size exceeded
      | at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)

I haven't looked into it yet, but am not hugely surprised, given the trouble NPM 5 has been giving me. Recommended workaround for now is downgrading to NPM 4, at least when installing.

**Comment by derhuerst** [comment]
[`npm@5.2.0`, released a few hours ago, has a fix](https://github.com/npm/npm/releases/tag/v5.2.0) that sounds fitting:

> `9fe905c39` npm/npm#17652 Fix max callstack exceeded loops with trees with circular links.

**Comment by marijnh** [comment]
Indeed, I can reproduce this with 5.0.4 but no longer with 5.2.0. So I guess that fixed itself.
