### ISSUE TITLE
Copying and pasting text from an HTML page removes spaces around marks

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#671]
* I could reproduce the issue in Chrome 59 on Linux
* Chrome 56 on MacOS works fine
* Firefox 54 works fine
* Safari 10.0.3 on MacOS keeps the spaces, but completely removes the marks

Steps to reproduce in Chrome 59:
1. Select and copy the following text: ProseMirror tries to **bridge the gap** between [Markdown](http://commonmark.org/) text editing and classical _WYSIWYG_ editors.
2. Go to http://prosemirror.net
3. Paste the copied text into the editor

The spaces around the em, strong, and link marks are all gone:
![pm_paste_marks_bug](https://user-images.githubusercontent.com/152507/28056086-e1779326-661b-11e7-91e5-bc4c718ee3ad.png)

**Comment by kapouer** [comment]
This is what you see when you paste it into oo-write:
![capture du 2017-07-11 09-40-15](https://user-images.githubusercontent.com/131406/28056399-1e976dd4-661d-11e7-9c2b-e7f0a3796acf.png)

So the issue should be renamed to "non-breakable spaces are removed".

**Comment by marijnh** [comment]
Does attached patch help for you?

**Comment by kiejo** [comment]
Thanks, your patch fixes the issue!
