### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by klapparP** [ProseMirror/prosemirror#672]
Some properties and functions are missing a description.
These are the ones I've encountered so far:
- `clearNonMatching()` function of `Transform` in prosemirror-transform (mark.js)
- `defaultAttrs` and `contentExpr` properties of `NodeType` in prosemirror-model (schema.js)

Could you add some? Without it, typings can't be generated.

**Comment by marijnh** [comment]
These are not, at the moment, considered public, though I know some of the core modules do refer to them. What specific problem are you encountering when generating types?

**Comment by klapparP** [comment]
Types are generated based on the description. Without a description, these functions and properties can't be used with typescript without running into compiler errors.

I tried to write some custom commands and used the given commands implementation as a starting point.

**Comment by marijnh** [comment]
`defaultAttrs` and `contentExpr` are now no longer referenced from outside of their module.

Still considering what to do with `clearNonMatching`.

**Comment by marijnh** [comment]
`clearNonMatching` is now called `clearIncompatible` and is part of the documented API.
