### ISSUE TITLE
Inline decoration `style` bleeds across DOM nodes

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#676]
The [DOM patching that handles inline decoration `style` values](decorations) bleeds across DOM nodes.

```
  if (prev.style != cur.style) {
    let text = dom.style.cssText, found
    if (prev.style && (found = text.indexOf(prev.style)) > -1)
      text = text.slice(0, found) + text.slice(found + prev.style.length)
    dom.style.cssText = text + (cur.style || "")
  }
```

The problem appears to be a false assumption that `prev.style` should equal `dom.style.cssText`, however this cannot be guaranteed as some browsers (i.e. Chrome) will normalise the `cssText` by (for example) adding white-space formatting:

```
> prev.style
"background-color: rgba(248,79,119,0.25)"
> dom.style.cssText
"background-color: rgba(248, 79, 119, 0.25);"
```

I'm not sure why `dom.style` isn't being completely blown away. Is this to allow overlapping inline decorations to be merged? Some comments in the code would be super helpful here 😄.

Perhaps an alternative approach is to follow https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style#Setting_styles and work by syncing the properties on the https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration. This would mean that `style` on `OuterDecoLevel` should be an object rather than a string, but care would still need to be taken because this still goes through normalisation:

Tested in Chrome's console:
 
```
> dom.style.backgroundColor = 'rgba(248,79,119,0.25)'
"rgba(248,79,119,0.25)"
> dom.style.backgroundColor
"rgba(248, 79, 119, 0.25)"
```

Note that the read value differs from the written value.

Another option is just giving up on supporting `style` all together, and only support `class`.

**Comment by marijnh** [comment]
This function tries to apply only a diff from the old attributes added to the new one, leaving any attributes that weren't involved in the decorations alone. This is indeed a bit difficult to do for inline styles, which it treats as a set to add/remove properties from, but I would like to support them.

One option would indeed be to treat style like an object. We could even support string styles by parsing them into objects. I'll take a look.

**Comment by marijnh** [comment]
Attached patch should properly remove styles in such a situation. I didn't add a feature for specifying styles as an object, since I guess it's usually more convenient to specify them as strings.

**Comment by bradleyayers** [comment]
I'm a bit skeptical of the parsing into object approach, but I can't poke any serious holes in your code so fair enough! It's an interesting approach 😄.

I agree with not supporting *both* an object and string API — I don't have a good use case for needing both, and keeping the string API means we can keep backwards compatibility.

A short note about the docs: as a consumer I was *very* surprised that the string I provide for `style` would be mixed in with other styles — when providing a string I assumed the implementation would just be setting it directly to `.style`.  That said, the documentation *does* say it's *added*, so technically I just didn't RTFM. I think there's probably room in the docs to elaborate *why* it's added, as that's novel behaviour to me.

Thanks the quick fix! I'm toying around with just using classes (albeit dynamically generated ones via [typestyle](https://github.com/typestyle/typestyle)), as they allow for pseudo selectors like `:hover`, but being able to just set a `style` string is quite handy.
