### ISSUE TITLE
hasFocusAndSelection creates error in Firefox when switching from input type="text"

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#678]
When trying to move focus to the ProseMirror (`view.focus()`), it seems to run the check `hasFocusAndSelection()` [1]. As part of that check it checks the anchorNode for various attributes.

The problem is that if the selection previously was in an `<input type="text">` in Firefox, the returned selection contains (at times) an empty object as anchorNode and an error is thrown:

    Permission denied to access property "nodeType"

[1] https://github.com/ProseMirror/prosemirror-view/blob/5dbf517628f4ffab171ec693ed56d298d4e44b42/src/selection.js#L282

**Comment by marijnh** [comment]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1035749 , I guess. Adding an ugly try/catch seems like it's the only way around it, so I've done so in 4f58e40
