### ISSUE TITLE
joinBackward with tables

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#679]
Currently when the cursor below the row, pressing Backspace creates a new row with the nodes that were after the cursor:
![tables_demo1](https://user-images.githubusercontent.com/26512812/28758245-fa442d80-75d7-11e7-911f-8626d47c32cc.gif)

What I'd like to achieve is joining nodes after the cursor with the content of the last cell of the last row. 

What would be the best way to achieve this?

**Comment by marijnh** [comment]
> Currently when the cursor below the row, pressing Backspace creates a new row with the nodes that were after the cursor:

With the current version, it'll select the whole table instead.

To do something else, you'd write a special-cased command that matches the circumstances you're interested in, and wire that up to the backspace key before the more general commands.

(Please use the [forum](https://discuss.prosemirror.net/) for non-bug-report questions in the future.)
