### ISSUE TITLE
JavaScript objects do not keep order

### ISSUE THREAD

**Issue by mitar** [ProseMirror/prosemirror#681]
In Chrome this is true, but it is not really required by the standard:
* https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

I am reading [schema documentation](http://prosemirror.net/docs/guides/schema/) and it says there:

> If that is a group, the first type in the group (determined by the order in which the group's members appear in your nodes map) is used.

But the "nodes map" is an object. So which group member is first is not well defined.

**Comment by marijnh** [comment]
Note that that question is from 2011. For non-integer properties, all modern engines, along with all IE versions (which have always done this), iteration order is guaranteed to match definition order.

**Comment by mitar** [comment]
OK, here is a newer one: https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties

So now it depends what you use to iterate over. :-) 

Also: http://2ality.com/2015/10/property-traversal-order-es6.html

OK, so it seems this is OK.
