### ISSUE TITLE
Lists do not create new parent bullet points after being deleted once

### ISSUE THREAD

**Issue by Keats** [ProseMirror/prosemirror#682]
A bit hard to explain in words so as a gif:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/680355/28866458-f9c981e8-77ad-11e7-9017-20e6b4c7bd96.gif)

The first time I press Enter it does work as expected but if i delete them and try again, Enter will not create new bullets anymore. Backspace will do create a new bullet correctly though.
The keymap related to lists are:
```
  // Lists
  keys["Enter"] = splitListItem(schema.nodes.list_item);
  keys["Tab"] = sinkListItem(schema.nodes.list_item);
```
This can be reproduced on http://prosemirror.net/examples/markdown/ as well. On Chrome it works as shown in the gif but on Firefox it will never create a new parent bullet with Enter after creating a nested list.

**Edit**: I've tried to remove the spot where I wrote `?` by using `paragraph (ordered_list|bullet_list)?` for the content but backspace is now acting funky: https://discuss.prosemirror.net/t/ordered-bullet-lists-text-only/840/2 but I'm not sure whether it's a bug with my comprehension of content in schema or with the lists themselves

**Comment by marijnh** [comment]
Does attached patch improve this for you?

**Comment by Keats** [comment]
Works perfectly, thanks!

**Comment by marijnh** [comment]
Great!
