### ISSUE TITLE
Pasting some text from Google docs or Words adds additional br

### ISSUE THREAD

**Issue by srenault** [ProseMirror/prosemirror#683]
When I past some content from Google docs or Words, a new line is converted into:

<img width="332" alt="screen shot 2017-08-04 at 15 50 48" src="https://user-images.githubusercontent.com/1011289/28971578-bc2f0f44-792c-11e7-937b-5638377638bc.png">

As you can see, we have two `br` instead of one.
This can be easily reproduced by copy/paste this [content](https://docs.google.com/document/d/1gEmJafsJ3tHnUgRsjVPW5ysh0oQ-9F82iTuJGt2ch6U/edit?usp=sharing) into your [basic example](https://prosemirror.net/examples/basic/).
I tried to investigate the issue and identified that the additional `br` is created [here](https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L990).
If you guide me, I can try to propose a PR.

**Comment by marijnh** [comment]
The second `<br>` is part of the presentation layer, used to make the first one visible to the user, and not actually part of the document.

**Comment by srenault** [comment]
Yes, but the second `br` make the display buggy. We actually think we have two lines.

<img width="750" alt="screen shot 2017-08-05 at 10 34 30" src="https://user-images.githubusercontent.com/1011289/28994252-b37c2dda-79c9-11e7-9b97-2229b073db36.png">

Maybe I miss something. Thanks.

**Comment by marijnh** [comment]
What did you expect a paragraph with only a hard break to look like? The same as an empty one?

(It will look like an empty one, when rendered to uneditable HTML, but during editing, it is important to be able to place the cursor both before and after the existing hard break, so ProseMirror renders it like this.)

**Comment by srenault** [comment]
Yes I expect that the new line copied from Words or Google Docs be converted into an empty paragraph.
```html
<p>
 <br/>
</p>
```

**Comment by marijnh** [comment]
An empty paragraph is `<p></p>`, and is distinct from a paragraph with a hard break in it. Is the original `<br>` something you'd want to be ignored/dropped on paste?

**Comment by srenault** [comment]
Yep, I think so.

**Comment by marijnh** [comment]
You could get that effect with a `transformPasted` prop that drops trailing hard breaks. Or, alternatively, you could see if Google Docs/Word add any attribute to such hard breaks that can be used to target them for ignoring with a parse rule.

This is probably not something ProseMirror core will ever handle out-of-the-box, but I'm hoping someone will at some point set up a 'paste from word processors' plugin module that helps handle the weird markup that the various word processors put on the clipboard.

**Comment by srenault** [comment]
Okey thanks for your help!
