### ISSUE TITLE
chainCommands doesn't declare use of EditorView

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#685]
The internal implementation of `chainCommands` expects a third `view` parameter, but it's not documented in the type: 
https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L515

Is this intentional?

**Comment by marijnh** [comment]
That should be documented, I guess. Done in attached patch. The third optional parameter to commands is kind of a dirty hack to be able to support more imperative commands (which need to show a dialog near the editor, or do something in an asynchronous way, or access the DOM to figure out whether we're at the (bidi-aware) start or end of a textblock).

**Comment by marijnh** [comment]
Patch https://github.com/ProseMirror/prosemirror-commands/commit/5a8127e753748ad55842190bed02af696b6c99ce , that is.
