### ISSUE TITLE
Markdown serializer: should not emit open/close marks for empty (whitespace-only) nodes

### ISSUE THREAD

**Issue by mhuebert** [ProseMirror/prosemirror#686]
Minor bug related to the `expelEnclosingWhitespace` option. If a mark (like bold or italic) is applied to a region which contains only whitespace, eg. `"   "`, the whitespace will be properly expelled, but then the mark's tags are still emitted, wrapping nothing, so you can get something like `"  ****"` in the output. If this string is then re-parsed as markdown, those asterisks are escaped. This can be replicated on the [Markdown example](http://prosemirror.net/examples/markdown/).

So I think there should be a check to see if the entire node is whitespace, and if so, avoid emitting the marks. I'm not 100% sure how to make this change as I haven't fully grokked the loop inside `renderInline`, but it would be near here: https://github.com/ProseMirror/prosemirror-markdown/blob/master/src/to_markdown.js#L265

**Comment by marijnh** [comment]
Attached patch should help there.

**Comment by mhuebert** [comment]
Great, thanks!
