### ISSUE TITLE
Backspace broken on lists different from paragraph block*

### ISSUE THREAD

**Issue by Keats** [ProseMirror/prosemirror#687]
I'm not sure it's a bug as it's a different schema but the doc says:

> it should have a shape like "paragraph block*", a plain textblock type followed by zero or more arbitrary nodes. 

Using `paragraph (bullet_list|ordered_list)*` for `list_item`, the basic schema and this keymap before the default keymap:
```
  // Lists
  keys["Enter"] = splitListItem(schema.nodes.list_item);
  keys["Tab"] = sinkListItem(schema.nodes.list_item);
```

works perfectly with Enter but does crazy things with Backspace. "paragraph block*" works perfectly. 

Reading the docs I believe it should work out of the box as it still has a similar content shape, only more restricted but it seems like that `joinBackwards` command actually expects to have `paragraph` in the list of blocks and breaks if it's not there.

**Comment by Keats** [comment]
I just found https://discuss.prosemirror.net/t/suitable-backspace-command-for-lists-with-restricted-schema/891 which is the same issue I guess

**Comment by marijnh** [comment]
Attached patch should make this a little better — you'll still first get a nested list item and only then delete the item (which is arguably okay behavior), but the item is properly deleted and you get a cursor rather than a node selection.
