### ISSUE TITLE
Cursor selection highlight is removed while inputting link mark attributes which can be a bit confusing

### ISSUE THREAD

**Issue by bZichett** [ProseMirror/prosemirror#690]
When selecting text and inserting a link, the text highlight is removed:

![1](https://user-images.githubusercontent.com/7804797/29487231-f597a528-84c3-11e7-8714-f9dd9ff13ea1.png)

When completed, the text is rehilighted, and the mark is properly added.

![2](https://user-images.githubusercontent.com/7804797/29487232-f84bab98-84c3-11e7-8fce-901f0d58cce9.png)

What I'm proposing here is a UX/UI issue / improvement where the text remains highlighted giving better feedback to user.  

---

Prosemirror v0.22

**Comment by marijnh** [comment]
ProseMirror uses the regular DOM selection, of which there can be only one. So while you're inputting the link, and have your selection in the text field, you won't see your original selection. You can work around that with a decoration if you want, but the core library isn't going to take care of that.

**Comment by bZichett** [comment]
Thanks for getting back so quickly.  Will take a shot at using decorations and post my results.
