### ISSUE TITLE
[Discussion] Inconsistent concept of `Set` used in Mark API

### ISSUE THREAD

**Issue by ncphillips** [ProseMirror/prosemirror#691]
The Mark API uses two different definitions of a Set of Marks.

* `Mark#addToSet` does it's comparison based only on the `MarkType`
* `Mark#isInSet` does it's comparison based on the `MarkType` and all it's attributes.

This inconsistency causes confusion in locations such as [`Transform#addMark`](https://github.com/ProseMirror/prosemirror-transform/blob/master/src/mark.js#L16-L19), where the code reads:

```
let newSet = mark.addToSet(marks)

for (let i = 0; i < marks.length; i++) {
  if (!marks[i].isInSet(newSet)) {
```

At first glance this seems like this path would never be followed, but that is not the case.

There are at least a few ways this could be clarified:

1. Rename `Mark#addToSet(set)` to something like `Mark#addOrUpdateInSet(set)`.
2. Rename `Mark#isInSet(set)` to `Mark#isExactlyInSet(set)`.
3. Move addToSet behaviour from Mark to MarkType. e.g. `MarkType#addToSet(mark, set)`.

**Comment by marijnh** [comment]
What is the actual inconsistency here? A mark set is an array of marks. You can query if a given mark is in such a set with `isInSet`, and you can create a new set by adding a given mark, possibly removing conflicting marks, with `addToSet`. The terminology seems precise enough.

**Comment by ncphillips** [comment]
The inconsistency is that `isInSet` uses a strict comparison and `addToSet` does not, so there is two different equality definitions being used for one Set.

If they were the same, I would expect the implementation of `addToSet` to look something like this:

```
addToSet(set) {
  if(this.isInSet(set)) return set
  return [...set, this]
}
```

But because `addToSet` loosens the definition of equality, it actually performs two operations: it removes the old mark and then it adds the new mark. This makes the implementation more like:

```
addToSet(set) {
  if(this.isInSet(set)) return set
  let copy = set
  if (this.type.isInSet(set)) {
    copy = this.type.removeFromSet(set)
  }
  return [...copy, this]
}
```

As a new user of this project, this slight inconsistency of naming has caused me a bit of confusion when trying to work with the mark API.

**Comment by marijnh** [comment]
Adding doesn't use equality, it uses [exclusivity](http://prosemirror.net/docs/ref/#model.MarkSpec.excludes). I think you're trying to apply too literal a definiton of _set_ here. The adding isn't a set-theoretic add, it just computes a new set that happens to include the given mark.
