### ISSUE TITLE
Editing paragraph with new lines remove new lines

### ISSUE THREAD

**Issue by srenault** [ProseMirror/prosemirror#693]
Following this code: 

```javascript
const {EditorState} = require("prosemirror-state")
const {EditorView} = require("prosemirror-view")
const {DOMParser} = require("prosemirror-model")
const {schema} = require("prosemirror-schema-basic")
const {exampleSetup} = require("prosemirror-example-setup")
const {Node} = require('prosemirror-model');

const doc = Node.fromJSON(schema, {
  type: 'doc',
  content: [{
    type: 'paragraph',
    content: [{
      type: 'text',
      text: 'toto\ntata'
    }]
  }]
});

window.view = new EditorView(document.querySelector("#editor"), {
  state: EditorState.create({
    doc: doc,
    plugins: exampleSetup({schema})
  })
})
```
When I start to edit the inside the paragraph, all the new lines are removed:

![prosemirror-issue](https://user-images.githubusercontent.com/1011289/29977196-d84c812c-8f3c-11e7-84a7-7a8dfbe2ce72.gif)

Could you help me with that? Thanks!!

**Comment by marijnh** [comment]
The editor normalizes newlines to spaces in non-code textblocks, since for most content, they are treated as just another form of whitespace and only get in the way. Did you mean for these to be hard_breaks, or do you actually want significant newline characters in your text?

**Comment by srenault** [comment]
Yes, I expect new lines replaced by hard_breaks.

My use case is:
 - Inside a paragraph, I hit `CMD + enter` to add new line (`br` is present in the DOM).
 - On saving the content, the paragraph is serialized with `\n`.
 - On restoring the content, I expect to have `br` but it's not.

**Comment by marijnh** [comment]
> Yes, I expect new lines replaced by hard_breaks.

Then create the document with hard_break nodes, rather than newlines. I.e. 

```
content: [{
  type: 'text',
  text: 'toto'
}, {
  type: "hard_break"
}, {
  type: "text",
  text: "tata"
}]

**Comment by srenault** [comment]
Ok, I'll do that!

Thanks
