### ISSUE TITLE
Pasting list in editor converts first list item to paragraph.

### ISSUE THREAD

**Issue by jpuri** [ProseMirror/prosemirror#695]
prosemirror-view: 0.22.0

![list](https://user-images.githubusercontent.com/2182307/30051783-e9984040-9240-11e7-8ad1-63dc6c51d110.gif)

**Comment by marijnh** [comment]
So the video shows you moving the mouse but not much else. If I try to reproduce this, I can't -- selecting across some list items, copying, and then pasting them into an empty paragraph wraps all items in a list. Do you mind describing the steps you took? (I prefer text to video.) Does the problem also occur on http://prosemirror.net/examples/markdown/ ?

**Comment by jpuri** [comment]
Hi @marijnh,

Sorry for not being very clear at first place. This paste issue does not happen always but looks like when selection is not perfectly inside paragraph it creates trouble.

I could replicate it here: [http://prosemirror.net/examples/markdown/](http://prosemirror.net/examples/markdown/). I created a list and copied it and paste it at very beginning of a paragraph.

![list](https://user-images.githubusercontent.com/2182307/30055225-67babca4-924c-11e7-9992-d599018bffec.gif)

**Comment by marijnh** [comment]
What was happening is that you were pasting into an existing, non-empty paragraph, so the regular behavior of replacing the entire paragraph (which happens when it's empty) didn't kick in, and your initial content was simply inserted into the paragraph.

Attached patch further complicates the `replaceRange` algorithm to, when the insert point is at the start of a block, allow moving it out of that block.

**Comment by jpuri** [comment]
Hi Marijn,

Thanks a lot for this fast response. I added this patch to my code, but still its not 100% success. I am not sure but it appears as if issue has something to do with how I copy content to clipboard. It happens even if paragraph has no content.

![list](https://user-images.githubusercontent.com/2182307/30129538-d9273ea4-9363-11e7-9320-f43e86653d8e.gif)

If I copy list by `Cmd-A` from prose-mirror editor itself, its perfect and other copy seems to create trouble.

**Comment by jpuri** [comment]
That is true, I again checked and this exact issue is not in example markdown editor. Looks like trouble at our end.

Thanks again for helping out.
