### ISSUE TITLE
conflict-free collaborative editing

### ISSUE THREAD

**Issue by pgte** [ProseMirror/prosemirror#697]
First of all, congratulations for this project! The code base is super clear and the docs are very complete.

This is not an issue, it's more of a question:
I'm looking into embedding prose mirror in a collaborative editor that allows conflict-free editing without any central authority. I've seen that Prosemirror already provides some collaboration primitives, but, from what I've seen, it's not clear whether the model would support conflict-free Steps.

(Usually, to provide a conflict-free model, a sequence of edits is a conflict-free array, where each position on the array has a unique random ID. Each array position has an operation, and instead of an absolute array position, contains the ID of the left-most position at the time of creation.)

I would be interested to know if you think that the Prosemirror model could be applied to a conflict-free decentralised environment.

Thanks so much in advance!

**Comment by marijnh** [comment]
I'm not familiar with this style of collaborative editing, but if you can set up some way for the collaborating actors to agree on an ordering of the edits (steps, in ProseMirror jargon), this should be possible -- you may even be able to wire it up to the existing collab plugin (which does little more than tracking which steps haven't been shared yet and reordering those on top of other steps when new information comes in).

> This is not an issue, it's more of a question:

I'd prefer if you'd use the [forum](https://discuss.prosemirror.net/) for those in the future!
