### ISSUE TITLE
Code of conduct is missing

### ISSUE THREAD

**Issue by adrianheine** [ProseMirror/prosemirror#699]
ProseMirror doesn't have a Code of conduct, yet. Should we use https://www.contributor-covenant.org/, as CodeMirror does?

**Comment by marijnh** [comment]
It does link the contributor covenant from the website frontpage and footer. Mentioning it in the README files would be good -- should be possible to do relatively quickly with `pm mass-change` ;)

**Comment by marijnh** [comment]
Since no PR has come into existence, could you be a bit more specific about the places where you were expecting this to be referenced?

**Comment by adrianheine** [comment]
I was looking at this repo's `README.md` and `CONTRIBUTING.md`. I was fairly certain that if those don't mention a CoC, the project doesn't have one. I can do pull requests once we agree to something.

**Comment by marijnh** [comment]
I've pushed c2de37a (and similar commits in the various module repos). How does that look?

**Comment by adrianheine** [comment]
Thanks!
