### ISSUE TITLE
Prevent nested list items

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#70]
I think that it should not be possible to create a list item directly inside another list item like that:
![nested_list_items](https://cloud.githubusercontent.com/assets/152507/10967793/4bb03f92-83bd-11e5-8ae8-6ed0a5c93151.png)

Creating a bullet list inside a list item should of course still be allowed like that:
![nested_bullet_lists](https://cloud.githubusercontent.com/assets/152507/10967794/50ebf58c-83bd-11e5-8c6c-3776d75bcce4.png)

**Comment by marijnh** [comment]
This isn't something I want to prevent on the schema level, but maybe it is worthwhile to adjust the wrap-in-list command to perform a lift if the cursor is in the first block in a list item instead.

Are you sure no one will ever want to directly nest lists like that?

**Comment by kiejo** [comment]
I thought about this functionality and couldn't come up with any use case where someone might actually want to directly nest list items like that. I also don't know of any other editor where this is possible (I checked Google Docs, Word, Libre Office Writer, Quill, Etherpad).
If we still want to keep the possibility on the schema level, handling this on a command level is probably a good solution.
