### ISSUE TITLE
Left arrow not working on 'ff' character sequence in Chrome

### ISSUE THREAD

**Issue by jeromepl** [ProseMirror/prosemirror#700]
### Issue details

In Chrome, there seems to be an issue with the left arrow key when pressed with the cursor positioned after the character sequence `ff`. Pressing it once will not move the cursor.

### Steps to reproduce
( This can be reproduced in the live demo on [prosemirror.net](https://prosemirror.net/)'s home page)
- type anything ending with `ff`
- make sure the cursor is right after the characters `ff`
- press the left arrow key once: **The cursor does not move**
- press the left arrow key once more: The cursor is not in its correct position before the sequence `ff`

### Affected platforms

- [x] Chrome (Tested in version _60.0.3112.113_)
Works in Firefox _55.0.3_

**Comment by marijnh** [comment]
It seems that the browser renders the pair of characters as a ligature, and then doesn't render the cursor when it's inside the ligature. Attached patch adds a CSS rule to turn ligatures off entirely inside the editor, which is unfortunate, but better than this behavior.

**Comment by marijnh** [comment]
And by attached patch I mean https://github.com/ProseMirror/prosemirror-view/commit/6b3b2205e2f3029cb8e8e86c55a190a22491df31

**Comment by RichieAHB** [comment]
Just for anyone who comes here Chrome 69 is bringing this 🎉 

https://blog.chromium.org/2018/08/chrome-69-beta-av1-video-decoder-css.html

**Comment by marijnh** [comment]
Nice! (The linked article mentions mid-ligature text selection is supported in Chrome 69.)
