### ISSUE TITLE
keyboard input leads to "undefined curType" error

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#701]
### Issue details

curType undefined in https://github.com/ProseMirror/prosemirror-transform/blob/055c50e08df6b8626dadba88299e50a533c9d6f7/src/replace.js#L294

A user is first pasting some text into a document. Then he is pressing some key which is interpreted as an insertText operation. This somehow leads to an undefined curType in placeSlice. I cannot tell what key the user was typing or where the selection was at that time, but from the looks of the traceback, this seems to be internal to ProseMirror.

TypeError: curType is undefined, 9, placeSlice@https://app.fiduswriter.org/static/js/editor.es5.js:105921:9
replaceStep@https://app.fiduswriter.org/static/js/editor.es5.js:105638:16
[485]</Transform.prototype.replace@https://app.fiduswriter.org/static/js/editor.es5.js:105660:14
[485]</Transform.prototype.replaceRange@https://app.fiduswriter.org/static/js/editor.es5.js:106057:10
[485]</Transform.prototype.replaceRangeWith@https://app.fiduswriter.org/static/js/editor.es5.js:106083:10
replaceWith@https://app.fiduswriter.org/static/js/editor.es5.js:94338:7
replaceSelectionWith@https://app.fiduswriter.org/static/js/editor.es5.js:94855:5
insertText@https://app.fiduswriter.org/static/js/editor.es5.js:94875:14
[486]</editHandlers.keypress@https://app.fiduswriter.org/static/js/editor.es5.js:109051:23
loop/view.eventHandlers[event]@https://app.fiduswriter.org/static/js/editor.es5.js:108980:11

### Please specify which version of ProseMirror you're running

ProseMirror v[0.24]

### Affected platforms

- [ ] Chrome _(please specify version)_
- [X] Firefox _55_
- [ ] Internet Explore _(please specify version)_
- [ ] Other _(please specify which)_

**Comment by marijnh** [comment]
I wasn't able to reproduce this or see a way in which it would occur, but if you find more information, let me know.

**Comment by johanneswilm** [comment]
Ok. I don't think I will. The user in question is communicating with me and stated the above, but I cannot reproduce it myself. One thing to notice is that he is running Firefox on a slow computer where the paste handler is taking quite some time. It could be that he is typing while the paste handler is still working.

**Comment by marijnh** [comment]
I am pretty sure I found the issue (some code was still relying on a behavior that changed in 0.23.0) and fixed it in [this patch](https://github.com/ProseMirror/prosemirror-transform/commit/e055039d7e12b4599973e9f70f42b8be60eb86df). Do reopen if you run into the problem again.
