### ISSUE TITLE
Shift-Mod combos aren't registering with Shift intact on Safari

### ISSUE THREAD

**Issue by jon-celtx** [ProseMirror/prosemirror#703]
### Issue details

Shift-Mod-z registers as Mod-z on Safari since keymap commit 356f9dc20851c7f104c3127995b791326ff216a9 

### Steps to reproduce

On the latest 0.24 demo page at the front of prosemirror.net, type something... Hit CMD+Z to undo then SHIFT+CMD+Z to try to redo... it just undoes more.

### Please specify which version of ProseMirror you're running

ProseMirror v[  0.22 - 0.24  ]

### Affected platforms

- Safari Version 11.0 (13604.1.38.1.6)

**Comment by marijnh** [comment]
Seems to be a bug in Safari's implementation of KeyboardEvent.key (it's kind of amazing how wrong browsers can get a relatively straightforward standard). I've updated the w3c-keyname polyfill to detect and compensate for this in attached patch (and released the updated version to NPM), which seems to solve the problem.

**Comment by jon-celtx** [comment]
Thanks!
