### ISSUE TITLE
Cut text inside the editor doesn't seem to work as expected in IE11/EDGE

### ISSUE THREAD

**Issue by djeremh** [ProseMirror/prosemirror#704]
In IE11 on windows 7, if I cut text inside the editor (by contextmenu or keyboard shortcut), the text is added to the clipboard but not removed from the editor. Paste is working well.

In EDGE 14/15 on window 10,  when I try to copy or cut existing text in the editor, it doesn't seem to be added to the clipboard. When I try to paste, it seems to paste some other text copied in another app. Cut text is removed from the editor though.

This can be easily reproduced, directly in the demo on prosemirror.net: try to copy/cut and paste some part of the existing text.

I could reproduce the bug in v0.22 (which I use in my code) and it seems to be there in v0.24

This affect ie11/win7 (not tested in win10) and Edge14/15 on win10.

Thanks for your time and the awesome editor !

**Comment by marijnh** [comment]
Attached patches should help! It seems that since Edge 15, they actually implemented a working clipboard API, making copy-paste much less hacky and fragile.

**Comment by djeremh** [comment]
I will test this in the weekend.
Thanks for your reactivity!

**Comment by djeremh** [comment]
Tested and it's all good!

**Comment by marijnh** [comment]
Great!
