### ISSUE TITLE
Consider exposing prosemirror-view internal browser detection

### ISSUE THREAD

**Issue by 5id** [ProseMirror/prosemirror#705]
### Issue details
We used to consume prosemirror-view/dist/browser to ensure that we were using the same browser/os detection that PM was also using. This isn't necessarily a sustainable approach, and was broken in the latest release as the package moved to esModules.

The idea of pulling in another package to do browser detection seems unreliable and could cause some subtle bugs, so we've pulled in a copy of the browser.js into our repo manually for now, however we're somewhat concerned this will get out of date.

Is there any chance you would consider exposing the browser detection from prosemirror-view (or elsewhere)?

### Please specify which version of ProseMirror you're running
ProseMirror v0.23+

**Comment by marijnh** [comment]
> The idea of pulling in another package to do browser detection seems unreliable and could cause some subtle bugs,

What specific bugs are you expecting? I'd say that the way you'd be using the browser info is largely unrelated to what ProseMirror is doing with it (working around specific bugs and limitations), so I don't see the risk.

In the interest of keeping the module focused and not having the public interface cover crude internal kludges that will likely change or go away at some point, I'm very much against exporting these.

**Comment by 5id** [comment]
Cool, I'd agree with you

To answer your question, we're currently using it to determine which keymap is active. e.g. we have some custom behaviour depending on if it's mac/other. Specifically, we generate a help dialog showing the available shortcuts from this keymap. The concern/case we were cautious of, is if we use a library that recognises the browser differently to yours, we'd get a mismatch between shortcuts shown, vs the shortcut actually used.

**Comment by marijnh** [comment]
> we're currently using it to determine which keymap is active

That does make sense. I'm not sure what the best way to model platform-dependent keymaps is, but an obscure implicit browser check somewhere probably isn't it. Is this related to the baseKeymap exported by prosemirror-commands? That could probably export multiple keymaps, with a default one based on browser sniffing, so that client code has the option of doing the picking itself. Would that help?

**Comment by marijnh** [comment]
Attached patch implements the thing I proposed. Do comment if you run into further issues.
