### ISSUE TITLE
Testing prosemirror-view requires prosemirror-state to be linked

### ISSUE THREAD

**Issue by saranrapjs** [ProseMirror/prosemirror#707]
### Issue details / Steps to reproduce

When running prosemirror-view's tests (via `npm run test-server` and then loading the moduleserve webpage), there's a console error from moduleserve in the browser trying to include this testing utility:
https://github.com/ProseMirror/prosemirror-view/blob/bfb119b21b35db0b276461ad22339bf710ac2a10/test/view.js#L1

Because this utility doesn't seem to get packaged as part of the npm module, you're obliged to link the prosemirror-state repo locally in order to get tests running.

I'm not entirely sure what it'd take (or if it's possible) to bundle that test utility as part of the npm module, but it seems like that'd be the simple fix!
### Please specify which version of ProseMirror you're running

Latest `master` SHA of prosemirror-state/prosemirror-view. node version `v8.0.0`, npm version `5.4.2`.

**Comment by marijnh** [comment]
Good point. Attached patch fixes this in prosemirror-view. I noticed a few other packages have the same issue -- looking into that.
