### ISSUE TITLE
Deleting characters in a list causes odd behavior in Safari

### ISSUE THREAD

**Issue by mernen** [ProseMirror/prosemirror#708]
### Issue details

Deleting the last character in a list item (with either Backspace or forward-Delete) line causes erratic behavior:

* If it’s the only item in the list, nothing odd appears to happen;
* If it’s the last item, the entire item is deleted and the caret jumps to the first position in the following block (or the end of the previous list item if there are no other blocks);
* Otherwise, a newline is inserted after the caret

### Steps to reproduce

I’ll use a vertical line (|) to represent the caret.

1. Go to http://prosemirror.net on Safari (macOS or iOS)
2. Set the document to a three-item list of either kind, as follows:

> 1. x
> 2. y
> 3. z

3. Place the cursor at the end of the second line:

> 1. x
> 2. y|
> 3. z

4. Press Backspace (⌫)

**Expected:** the list item should simply be blank:

> 1. x
> 2. |
> 3. z

**Actual:** a new line is inserted in the same list item, after the current line:

> 1. x
> 2. |
>      
> 3. z

Inserting another character and deleting it again will produce more newlines.

### Please specify which version of ProseMirror you're running

Whatever version is on prosemirror.net home page and examples at the time of this report — presumably ProseMirror v1.0.

### Affected platforms

- [ ] Chrome _(please specify version)_
- [ ] Firefox _(please specify version)_
- [ ] Internet Explore _(please specify version)_
- [x] Other – Safari 11.0 (macOS Sierra 10.12.6, iOS 11.0.3 on iPad)

Latest Chrome, Firefox and Edge were tested, and do *not* have this problem.

### Screenshots / Screencast (Optional)

https://gfycat.com/gifs/detail/UnrealisticWeeklyDevilfish

**Comment by marijnh** [comment]
Ugh, it seems Safari transforms `<ol><li><p>x</p></li><li><p>y</p></li></ol>` to `<ol><br><li><p>y</p></li></ol>` when you delete the `x`. Which is positively weird, and makes it a little hard to restore the behavior we want.

Does attached patch work for you?

**Comment by adrianheine** [comment]
I suppose we can close this.
