### ISSUE TITLE
[IE11 - Win7] Some menu buttons alternate from normal to active+disable state at each keystroke

### ISSUE THREAD

**Issue by djeremh** [ProseMirror/prosemirror#711]
### Issue details

When I start typing anything in my editor, the state of some menu button (see scrennshots below) will alternates between normal and active+disable state on each keystroke. Selection with mouse or navigation with arrow keys will do the same.

### Steps to reproduce

This can be easily reproduce on the demo of prosemirror.net

Here I just load prosemirror.net, select the editor and press enter, everything is normal
![ie11-issue-normal-mode](https://user-images.githubusercontent.com/1216767/31683178-89394de0-b37c-11e7-8a3f-dec924e4dd7d.PNG)

Then I just type any letter
![ie11-issue-bug-mode](https://user-images.githubusercontent.com/1216767/31683177-891aaff2-b37c-11e7-942f-3199509d6720.PNG)

As I type, it will alternate between the two states at each keystroke.

### Please specify which version of ProseMirror you're running

ProseMirror v1.0

### Affected platforms

- [ ] IE11 on windows 7

**Comment by marijnh** [comment]
That appears to be [this IE11 issue](https://connect.microsoft.com/IE/feedback/details/878564/element-classlist-toggle-does-not-support-second-parameter). I've released a version 1.0.1 of prosemirror-menu that works around it. The website should be fixed now (might require a hard-refresh).

**Comment by djeremh** [comment]
It works, thanks for the quick fix ;)
