### ISSUE TITLE
Cursor can be drawn behind surrounding content on Firefox 

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#712]
When an inline element has a background color, Firefox will sometimes fail to draw the cursor when it is directly in front of the element (specifically, when moving it in front of the element from the left).

This can cause problems with cursor wrappers as well, as described in [this comment](https://github.com/ProseMirror/prosemirror/issues/583#issuecomment-337544629).

Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1409722

**Comment by biw** [comment]
As you mentioned in the firefox bug report @marijnh, it looks like this has been fixed, so this issue can be closed. correct?

**Comment by marijnh** [comment]
Good point. Closing.
