### ISSUE TITLE
Node.fromJSON doesn't take into account schema nested rules

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#714]
### Issue details

Our schema contains nodes with well defined restrictions of its content, e.g. listItem doesn't allow codeBlock node. We're using `Node.fromJSON(schema, doc);` to deserialize the document from JSON, which seems to ignore schema nested rules completely. As a result, its possible to deserialize JSON document with unsupported content and render it in the editor.

### Please specify which version of ProseMirror you're running

0.22

### Affected platforms

- [x] Chrome 61

### Screenshots / Screencast (Optional)
<img width="483" alt="screen shot 2017-10-26 at 5 22 51 pm" src="https://user-images.githubusercontent.com/26512812/32037716-5f86b95e-ba72-11e7-950a-174e241934b9.png">

### Input document
```
{"version":1,"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"1"}]}]},{"type":"listItem","content":[{"type":"codeBlock","attrs":{"language":null,"uniqueId":null},"content":[{"type":"text","text":"const x = 1;"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"3"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"4"}]}]}]}]}
```

### Output document
```
{"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"1"}]}]},{"type":"listItem","content":[{"type":"codeBlock","attrs":{"language":null,"uniqueId":null},"content":[{"type":"text","text":"const x = 1;"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"3"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"4"}]}]}]}]}
```

**Comment by marijnh** [comment]
This is intentional—JSON input is assumed to be properly formed. You can call [`check`](http://prosemirror.net/docs/ref/#model.Node.check) on the result if you want to explicitly verify the validity of the result.
