### ISSUE TITLE
Shift-Mod combos aren't registering with Shift intact on a Mac

### ISSUE THREAD

**Issue by davidka** [ProseMirror/prosemirror#715]
### Issue details

The shortcut for redo (CMD+SHIFT+Z) does not work properly on a Mac with Chrome and Firefox but with Safari it works (probably since [Shift-Mod combos aren't registering with Shift intact on Safari](https://github.com/ProseMirror/prosemirror/issues/703)

### Steps to reproduce

On the latest 1.0.0 demo page at the front of prosemirror.net, type something... Hit CMD+Z to undo then SHIFT+CMD+Z to try to redo... it just undoes more.

### Please specify which version of ProseMirror you're running

ProseMirror v1.0.0 

### Affected platforms

- [x] Chrome Version 62.0.3202.62 (Official Build) (64-bit)
- [x] Firefox 56.0.2 (64-bit)

**Comment by marijnh** [comment]
How are you specifying the key in your keymap?

**Comment by davidka** [comment]
With Shift-Mod-z

**Comment by marijnh** [comment]
Okay—the problem doesn't seem to occur on Chrome Linux, but I'll test with OS X later.

**Comment by davidka** [comment]
The problem also exists in the example on the start page of prosemirror.net.  At least on a mac

**Comment by marijnh** [comment]
I can reproduce this on Firefox / OS X, and also Chrome 62. Interestingly, Chrome had fixed it in 57, but apparently re-broke it (on OS X only) in 62 🙄.

I've released version 1.1.8 of w3c-keyname, which should address this.
