### ISSUE TITLE
list item can not be splited

### ISSUE THREAD

**Issue by ximing** [ProseMirror/prosemirror#716]
### Issue details
![oct-27-2017 21-04-44](https://user-images.githubusercontent.com/4659887/32105457-2b667854-baee-11e7-8f6b-82aeefdc56e1.gif)

### Steps to reproduce
1,visit http://prosemirror.net/examples/basic/
2, create a ordered list
3,create a bulleted list
4,back to ordered list ,pressing enter and then pressing backspace 
5, copy bulleted list to step4's  cursor positon 
6,move cursor to ordered list's first list-item and it can not be splited

### Please specify which version of ProseMirror you're running

ProseMirror v[1.0.0]

### Affected platforms

- [x] Chrome _(please specify version)_
- [x] Firefox _(please specify version)_

**Comment by ximing** [comment]
### select multiple  list item also can't be splited
![oct-27-2017 21-15-46](https://user-images.githubusercontent.com/4659887/32105917-d113eb50-baef-11e7-9e8a-23131ff7e536.gif)

This is a default behavior in google doc or other rich text editor(like quilljs，https://quilljs.com) ;
Are we deliberately designing it?

**Comment by marijnh** [comment]
The `splitListItem` command seems to work fine in this case. What exactly do you mean by 'can not be splitted'?

**Comment by amkgo** [comment]
@ximing 

Not related to this issue but want to know what kind of software do you use to capture the screen?

Thanks,
Andrew

**Comment by leeoniya** [comment]
@amkgo try any of:

https://www.rarst.net/software/licecap/
http://www.screentogif.com/
http://blog.bahraniapps.com/gifcam/
http://blog.bahraniapps.com/vclip/

**Comment by amkgo** [comment]
I've got ScreenToGif and it works great. 

Thanks.

**Comment by adrianheine** [comment]
Since there hasn't been any on-topic response for over a month, I think we can close this. @ximing please feel free to reopen if @marijnh's answer doesn't seem sufficient!
