### ISSUE TITLE
Inconsistent result when typing over formatted text

### ISSUE THREAD

**Issue by hubgit** [ProseMirror/prosemirror#717]
### Issue details

When typing over formatted text, the formatting should always be retained.

### Steps to reproduce

1. Open the demo editor at https://prosemirror.net/
1. Double-click a word to select it and apply bold formatting to the word.
1. Type a new word (formatting should be retained but is lost).
1. Double-click the new word to select it and apply bold formatting to the word.
1. Type a new word (formatting is retained in Chrome and Safari, lost in Firefox).

### Please specify which version of ProseMirror you're running

ProseMirror v1.0.1

### Affected platforms

- [x] Chrome 62
- [x] Firefox 57
- [x] Safari 11

### Screenshots / Screencast (Optional)

![prosemirror-bold](https://user-images.githubusercontent.com/14294/32220216-db64c03e-be28-11e7-84c4-27585bd601d7.gif)

**Comment by marijnh** [comment]
Attached patch should fix this (the issue came from a failure to fix some code for an incompatible change a few months ago). I've released prosemirror-state 1.0.1 with the fix.
