### ISSUE TITLE
A character is selected after removing selected text by entering new text

### ISSUE THREAD

**Issue by davidka** [ProseMirror/prosemirror#718]
### Issue details

![untitled 3](https://user-images.githubusercontent.com/1681446/32336052-8c1c6f3c-bfee-11e7-9a90-5634b8ea0817.gif)

### Steps to reproduce

* create a paragraph followed by a quote
* select text from the middle of the paragraph to the middle of the quote
* enter a character e.g. "o"
* enter further text

### Please specify which version of ProseMirror you're running

ProseMirror v1.0.0

### Affected platforms

- [x] Chrome 62.0.3202.75
- [x] Firefox 56.0.2
- [x] Internet Explorer 11

**Comment by marijnh** [comment]
Attached patch should help with this.
