### ISSUE TITLE
Drag and drop is not working on IE 11

### ISSUE THREAD

**Issue by FelipeTaiarol** [ProseMirror/prosemirror#719]
### Issue details

Drag and drop is not working on IE. I am getting the error below in the Dino example:

### Steps to reproduce

Open the Dino example in IE and try dragging one of them.

### Affected platforms

- [X] Internet Explore 11

### Screenshots / Screencast (Optional)

![image](https://user-images.githubusercontent.com/859559/32483487-8a84111e-c39c-11e7-8902-852a126a5662.png) . 

![image](https://user-images.githubusercontent.com/859559/32483491-93d42c72-c39c-11e7-927a-be49c9d2f2cb.png)

**Comment by marijnh** [comment]
Attached patch should make things a bit better. Does it help for you?

**Comment by FelipeTaiarol** [comment]
Thanks for the quick fix @marijnh !

Can you publish a new npm version so that I can test ? I don't have IE locally and my CD server doesn't like github urls in the package.json, not sure how else I could check..

**Comment by marijnh** [comment]
I'd prefer for you to test before I publish a new version. I'm sure you can set up a server and use browserstack.com or similar to test.

**Comment by FelipeTaiarol** [comment]
@marijnh , I tested and it works, thanks again for the quick fix!

**Comment by marijnh** [comment]
Thanks for the confirmation! Released as prosemirror-view 1.0.1

**Comment by FelipeTaiarol** [comment]
But I still have the problem when I use a NodeView. In Chrome if I block mousedown dragging works, in IE if I block mousedown it doesn't.

**Comment by adrianheine** [comment]
Could you provide example code and maybe open a new issue?
