### ISSUE TITLE
Hook for sanitizing pasted content

### ISSUE THREAD

**Issue by ameliusg** [ProseMirror/prosemirror#72]
Hi,

I'm looking for a way to sanitize content that is being pasted into the editor, before it is actually visible in the editor. For instance, I want to get rid of &lt;A&gt; elements, because they are not needed for my application.

I have looked through the sources and the only method so far I came up with (without modifying the prosemirror source) is to add an event-listener to pm.content (where pm is the editor object). However, for this approach to work, I need to duplicate a lot of code from prosemirror, so this solution is far from satisfactory.

Another approach could be to work with prosemirror's internal "transforms", but so far I had no luck figuring out how to install a hook.

Pointers and/or advise are greatly appreciated.

**Comment by marijnh** [comment]
ProseMirror automatically sanitizes pasted content by using its DOM parser. In your case, you'll want to create a document schema that doesn't include links -- that way, the parser won't make links, and you get content without links.

(Schema definition isn't documented yet, but you could try looking at src/model/schema.js)

**Comment by johanneswilm** [comment]
This is also something of interest to us. Particularly we need to do some transformations with paste content that comes from Word and LibreOffice. The structure of pasted content coming from these sources has a very particular format that doesn't quite match our document structure, but we can make it fit by moving around some items before trying to import it. For example, all footnotes are placed at the end of a LibreOffice paste, but one can find where their references are  in the rest of the content and then move them there. Having a hook for cleaning paste before prosemirror handles it would be very helpful.

**Comment by marijnh** [comment]
The `transformPasted`, `transformPastedHTML`, and `transformPastedText` event handlers cover this.
