### ISSUE TITLE
addEventListener keypress Why enter is not monitored? enter will not let newline

### ISSUE THREAD

**Issue by xgzl87** [ProseMirror/prosemirror#720]
### Issue details

                document.addEventListener("keypress",function(e){
                    console.log(e);
                })

### Steps to reproduce

When pressing Enter key console.log is not output

### Please specify which version of ProseMirror you're running

ProseMirror v[  1.0.0  ]

### Affected platforms

- [x] Chrome _(please specify version)_
- [x] Firefox _(please specify version)_
- [x] Internet Explore _(please specify version)_
- [x] Other _(please specify which)_

**Comment by marijnh** [comment]
Enter is (usually) handled by a key binding, which listens to `keydown` instead, and prevents the default behavior when the key is handled. Thus, no `keypress` event will fire for bound keys.

**Comment by xgzl87** [comment]
Thank you for answering,but will still trigger line breaks .
$("#editor [contenteditable|='true']").keydown(function (e) {
 if (e.key === "Enter" || e.key === "Tab") {
                        e.preventDefault();
}
});

**Comment by marijnh** [comment]
Probably your handler is called after ProseMirror's own handler.

**Comment by xgzl87** [comment]
oh,do you have any solution to it?

**Comment by marijnh** [comment]
The [the relevant prop](http://prosemirror.net/docs/ref/#view.EditorProps.handleDOMEvents).

**Comment by xgzl87** [comment]
this.view = new EditorView(this.dom, {
                    state: this.state.edit,
                    dispatchTransaction: transaction => this.dispatch({type: "transaction", transaction})
                });
                this.view.handleKeyDown = function (view, e) {
                    console.log(23233333333333333333333)
                }
not run...

**Comment by marijnh** [comment]
Yes, because you are using it incorrectly. I'm sorry, but you're going to have to read documentation, in order to use this library.

**Comment by xgzl87** [comment]
oh, I'm sorry,thanks.
                this.view.setProps({
                    handleKeyDown: (view, e) => {
                        console.log(23233333333333333333333)
                    }
                });
