### ISSUE TITLE
Make it possible to delay drawing of widget decoration nodes

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#721]
Decorations are often created during state transactions, in order to keep them consistent with the state. Yet widget decorations are raw DOM nodes, which sometimes need event handlers that have access to the view, or might want to draw something in a way that depends on some view prop or DOM state.

It might be a good idea to allow widget decorations to be created with a draw callback, rather than a finished DOM node, and then call that to actually draw them, with the view as parameter, the first time they are added to the DOM.

**Comment by marijnh** [comment]
See https://github.com/ProseMirror/rfcs/pull/7

**Comment by jhnsnc** [comment]
https://github.com/ProseMirror/rfcs/pull/7 is now implemented. I believe we can close this issue.

Relevant docs in the latest release: https://prosemirror.net/docs/ref/#view.Decoration%5Ewidget

**Comment by marijnh** [comment]
Indeed!
