### ISSUE TITLE
Allow input rules to be disabled in certain block types

### ISSUE THREAD

**Issue by hubgit** [ProseMirror/prosemirror#722]
### Issue details

As an example, input rules such as smart quotes and ellipsis should be disabled when inside a code block.

### Steps to reproduce

http://prosemirror.net/examples/basic/

Change the type of a block to "Code" and type `var foo = 'bar'`. 

The apostrophes (`&#39;`) will be converted to left single quotes (`&#8216;`) by the `openSingleQuote` rule.

### Please specify which version of ProseMirror you're running

ProseMirror v1

### Affected platforms

All

### Screenshots / Screencast (Optional)

![nov-10-2017 09-49-04](https://user-images.githubusercontent.com/14294/32652517-6d3764c8-c5fc-11e7-84ea-9e7d940186a3.gif)

**Comment by marijnh** [comment]
Can you think of any input rule that _should_ be active inside of a code block? I'm tempted to just blanked-disable them instead of adding another configuration field per rule. Would that work for you?

**Comment by hubgit** [comment]
I can't think of any rules that should be active inside a code block (or other block types that would want to disable input rules), but thought you might want to leave the possibility open. 

Blanket-disabling input rules inside code blocks would work for me.

**Comment by marijnh** [comment]
Attached patch (released as prosemirror-inputrules 1.0.1) does this.

**Comment by marijnh** [comment]
Err, patch https://github.com/ProseMirror/prosemirror-inputrules/commit/b4bf67623aa4c4c1e096c20aa649c0e63751f337 that is
