### ISSUE TITLE
Weird behavior of view.coordsAtPos(pos) when 'pos' has a widget decoration

### ISSUE THREAD

**Issue by FelipeTaiarol** [ProseMirror/prosemirror#723]
### Steps to reproduce

Add a decoration widget to a position and try to get its coordinates. It looks like it is getting the decoration widget's coordinate instead of the node's coordinate.

### Please specify which version of ProseMirror you're running

ProseMirror v[1.0]

### Affected platforms

- [X] Chrome

### Screenshots / Screencast (Optional)

See how the left coordinate changes from one position to the other:  
![image](https://user-images.githubusercontent.com/859559/32728527-f0a2a404-c880-11e7-8d75-02833a6893b5.png) . 

I did some debugging and it seems the problem is in this line of the coordsAtPos method.
![image](https://user-images.githubusercontent.com/859559/32728601-363d2f5c-c881-11e7-9700-919667b29498.png)

**Comment by marijnh** [comment]
> Add a decoration widget to a position and try to get its coordinates. It looks like it is getting the decoration widget's coordinate instead of the node's coordinate.

Note that it's called `coordsAtPos`, not `coordsAtNode` — it finds the coordinates of the DOM position (a parent DOM node and an index into it) corresponding to the given document position.

At the moment, when there are widgets at a given position, it finds the DOM position after any widgets with `side < 0` and before those with `side > 0`. Then, it returns the left side of the rectangle around the node after that position, or if that doesn't work (no node, or node with empty rectangle) the right side of the rectangle of the node before it.

It seems that in your case, it ends up using the rectangle of the absolutely positioned node. It may be helpful to add more heuristics to avoid this, but I'm not sure what they'd look like—it'd be nice if we could avoid calling `getComputedStyle` inside of `coordsAtPos`.

**Comment by FelipeTaiarol** [comment]
ok, I am passing side: -1 to the decoration widget constructor and it is now getting the Node's coordinates instead of the widget's. I am not sure about all the implications but I assumed that as I am absolute positioning it it doesn't make a difference? Thanks @marijnh !

**Comment by adrianheine** [comment]
@FelipeTaiarol If I understand @marijnh correctly, the code doesn't check the widget's style (i. e. if it's absolutely positioned), because that would be quite expensive.
