### ISSUE TITLE
Drag and Drop of NodeView doesn't work in IE if mousedown event is stopped 

### ISSUE THREAD

**Issue by FelipeTaiarol** [ProseMirror/prosemirror#724]
### Steps to reproduce

```
git clone https://github.com/FelipeTaiarol/ProseMirror-DragNDrop-Problem
cd ProseMirror-DragNDrop-Problem
npm install
npm start
```

Drag the task in chrome and look to the console, you will see that even though the mousedown event is stopped the dragstart event is fired and not stopped and it is possible to drag the task.

![image](https://user-images.githubusercontent.com/859559/32783707-ff104362-c94c-11e7-8867-9635a6dea0b1.png)

In IE, the mousedown event is stopped but the dragstart event is never fired and it is not possible to drag the task.

### Please specify which version of ProseMirror you're running

ProseMirror v1.0

### Affected platforms
- [X] Edge.
- [X] Internet Explore 11.

I was able to reproduce the issue in both IE and Edge but some problem in my setup is making it throw an exception is IE right now. It is still possible to reproduce it in Edge, I'll try to make IE work later.

**Comment by marijnh** [comment]
I don't see dragging working in Chrome when I preventDefault mousedown events, and I'm not sure that is a reasonable expectation to begin with -- if you're signalling that the browser should take no further action for mouse click, dragging certainly is included in that, no?

**Comment by adrianheine** [comment]
[Spec](https://www.w3.org/TR/DOM-Level-3-Events/#event-type-mousedown) agrees: „Default action | Varies: Start a drag/drop operation; start a text selection; start a scroll/pan interaction (in combination with the  middle mouse button, if supported)“

**Comment by FelipeTaiarol** [comment]
yes, it makes sense, I think what I have to do is to let the mousedown pass unless it was in one of the component elements where it should not pass. I'll try again and narrow the problem down to a better example if I still have it.

**Comment by adrianheine** [comment]
Ok. Please feel free to reopen this issue if you think you found some problem with Prosemirror!
