### ISSUE TITLE
Wrong replace step is being produced on backspace when cursor has same char on both side

### ISSUE THREAD

**Issue by torifat** [ProseMirror/prosemirror#726]
### Issue details

When the cursor is between two same characters. For example `a|a` and you <kbd>backspace</kbd>. It will create the following `step`:
```json
[{"stepType":"replace","from":2,"to":3}]
```

But, if you have different characters. For example `a|b` then it will create the following `step` instead:
```json
[{"stepType":"replace","from":1,"to":2}]
```

### Steps to reproduce

1. https://planet-lyre.glitch.me/
2. Put your cursor between `a` & `a` and <kbd>backspace</kbd>
3. Check `console`

### Please specify which version of ProseMirror you're running

Latest version, using https://prosemirror.net/examples/prosemirror.js

### Affected platforms

- [x] Chrome v62
- [x] Firefox v57

**Comment by marijnh** [comment]
Yeah, this is awkward. To not interfere with the browser's understanding of what the user is doing (which would disrupt spell-check and such), ProseMirror is letting the native effect go through and then using document diffing to figure out what changed. In cases like this, that is ambiguous. For insertions, it does some disambiguation based on the cursor position, but here that doesn't help—if you press delete, the character after would have been deleted.

Using key events to 'hint' the disambiguation might be a good idea. On Android or other systems which don't fire useful key events that won't help, but at least on desktop the steps would be a little more accurate. The way I'd do that is to store the last keycode seen (by the keydown handler) in the view object in view/src/input.js, and then pass that to `findDiff` in view/src/domchange.js and use it to bias ambiguous deletions one way or another.

Is anyone interested in working on that? I'll gladly answer further questions you have.

**Comment by torifat** [comment]
Thanks for the explanation. I will try to create a PR based on your suggestion.

**Comment by marijnh** [comment]
Fixed via https://github.com/ProseMirror/prosemirror-view/pull/26
