### ISSUE TITLE
Constraint editor to have only one single block

### ISSUE THREAD

**Issue by srenault** [ProseMirror/prosemirror#727]
### Issue details

Hello, I would like to constraint the editor to have only one block.
So basically, I change the schema to:
```
const nodes = {
  doc: {
    content: "block"
  }
```
### Steps to reproduce

If I hit enter key, I have the following error:
`Cannot read property 'validContent' of undefined` on Chrome
`TypeError: innerType.type is undefined` on Firefox

### Please specify which version of ProseMirror you're running

ProseMirror v0.22

### Affected platforms

- [ X] Chrome 61.03
- [ X] Firefox (Nightly) 58.0a1

### Screenshots / Screencast (Optional)
<img width="993" alt="screen shot 2017-11-21 at 17 15 49" src="https://user-images.githubusercontent.com/1011289/33083449-b2719d7e-cedf-11e7-83c8-6e06fe4cdb32.png">
<img width="1680" alt="screen shot 2017-11-21 at 17 16 31" src="https://user-images.githubusercontent.com/1011289/33083471-be0ce256-cedf-11e7-9590-97b685f5d442.png">

**Comment by marijnh** [comment]
That was a bug in the `splitBlock` command, fixed in attached patch, which is released as prosemirror-commands 1.0.2.

(You might want to make your schema just include the inline content directly in the doc node, as in the first example at http://prosemirror.net/examples/schema/ )

**Comment by srenault** [comment]
Okey thanks!
