### ISSUE TITLE
Link word can't select by mouse

### ISSUE THREAD

**Issue by amkgo** [ProseMirror/prosemirror#729]
The last word `examples` is a link in the editor on the prosemirror.net home page. 
I can select the word `examples` by dragging the mouse from the first letter `e` to the last letter `s`, but I can't select the word backward.

**Comment by marijnh** [comment]
Which browser?

**Comment by amkgo** [comment]
IE11 and Chrome Version 62.0.3202.94 have problem select the link backward.
Firefox 57.0 works well.

**Comment by marijnh** [comment]
The problem appears to be related to the cursor wrapper (the dummy node created around the cursor when in a position where it has to be wrapped in an additional node—in this case the link). That is created when the cursor is first moved (when the mouse button is pressed down) to the end of the link. The resulting selection reset seems to prevent drag-selection from happening on the effected browsers. I'll see if I can work around it.

**Comment by marijnh** [comment]
Attached patch seems to address this.
