### ISSUE TITLE
Improve markdown implementation for italic/bold handling (edge cases)

### ISSUE THREAD

**Issue by Mobiletainment** [ProseMirror/prosemirror#730]
### Issue details

When putting italic and bold text directly next to each other, there's a good chance that it gets interpreted wrongly due to weaknesses in markdown's italic and bold formatting.

### Steps to reproduce

Take the following markdown for example:

`*italic text directly next to ***bold text**`

- Expected output: _italic text directly next to_ **bold text**
- Actual output: *italic text directly next to ***bold text**

### Please specify which version of ProseMirror you're running

ProseMirror v0.10.1
ProseMirror example at http://prosemirror.net/examples/markdown/ (as of 28th November 2017)

### Affected platforms

- all

### Screenshots / Screencast (Optional)
![prosemirror-markdown](https://user-images.githubusercontent.com/1514111/33323999-72bd906a-d44e-11e7-81fc-f2b1b2ea7ae1.gif)

I tested this behavior with other markdown implementations and saw that this edge case is properly handled by some, e.g. pandoc: http://johnmacfarlane.net/babelmark2/?text=*italic+text+directly+next+to+***bold+text**

![prosemirror markdown](https://user-images.githubusercontent.com/1514111/33324199-3777fec2-d44f-11e7-8aea-baa1ac8329ac.jpg)

**Comment by marijnh** [comment]
I've moved this to https://github.com/ProseMirror/prosemirror-markdown/issues/16
