### ISSUE TITLE
Extra line using code style

### ISSUE THREAD

**Issue by amkgo** [ProseMirror/prosemirror#731]
Type several lines in the editor of ProseMirror home page, select these lines and apply code style, there will be an extra line between each of them.

To be more clear, you can do the same in the Markdown example WYSIWYM editor, then switch to Markdown, the extra lines will shows out.

[Firefox, Chrome, IE11]

Andrew

**Comment by amkgo** [comment]
If you Inspect the code in Chrome, I'll the html code below when I apply `code` style:
```
<pre><code>Line A</code></pre>
<pre><code>Line B</code></pre>
```

But when I go back from Markdown view to WYSIWYM view, the html becomes
```
<pre><code>Line A

Line B</code></pre>
```

So I think the problem is that the `code` style uses a <pre><code> pairs for each line instead of one pair for all the lines.

**Comment by marijnh** [comment]
Do you mean paragraph when you say _line_? If so, sure, you'll be converting multiple paragraphs to code blocks, which will give you multiple code blocks. If you want that to behave differently you could change the command that changes the selection to a code block to join all the textblocks it contains.

**Comment by amkgo** [comment]
This is the screen cast:

![prosemirror1](https://user-images.githubusercontent.com/8333491/33450302-35e99c10-d5c0-11e7-8967-d7a0f3e04f12.gif)

**Comment by marijnh** [comment]
Yes. I explained what is going wrong.

**Comment by amkgo** [comment]
I think this one related to [this one](https://github.com/ProseMirror/prosemirror-markdown/issues/17).

If you can convert all the selected paragraph into a single `<pre><code>` block, these two issues can be solved together.
