### ISSUE TITLE
code block after list problem

### ISSUE THREAD

**Issue by amkgo** [ProseMirror/prosemirror#732]
In the markdown example, the first line of the code block after list will change to a list when add a paragraph after list. See screen cast below.

![prosemirror](https://user-images.githubusercontent.com/8333491/33446028-a123948e-d5b3-11e7-96a8-91a83c4b63aa.gif)

Andrew

**Comment by marijnh** [comment]
I've moved this to https://github.com/ProseMirror/prosemirror-markdown/issues/17
