### ISSUE TITLE
Private Node#resolveNoCache method used in prosemirror-schema-list

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#734]
In [prosemirror-schema-list](https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.js#L170) a private `resolveNoCache` method is used on `Node`. It seems desirable to restrict prosemirror-schema-list to only use public APIs so that it can serve as an example of how to implement a plugin.

**Comment by marijnh** [comment]
That's a slight optimization (don't cache resolved positions that we know are unlikely to be resolved again soon), that I didn't want to complicate the public API with. I guess I can just switch those calls to use `resolve` instead. See attached patch.
