### ISSUE TITLE
deleting first node deletes all decorations after it

### ISSUE THREAD

**Issue by alidcastano** [ProseMirror/prosemirror#735]
### Issue details

I am trying to create a plugin that uses decorations to create placeholders for all empty text containers.

The problem I'm encountering is that when there are two different node types, e.g. `notetitle notegroup`, deleting the text in the first node type deletes all decorations. 

(Interestingly, this does not happen if only one note type is found, e.g. a `notegroup`. Deleting the first item in this case does not interfere with other decorations.)

### Steps to reproduce

I modified the note example found in the documentation to reproduce the behavior. Here's the glitch: https://glitch.com/edit/#!/important-message?path=index.js:1:0

See the example live. Type a list title, then delete it. You will see that all decorations/placeholders after it are deleted as well.

### Please specify which version of ProseMirror you're running

ProseMirror v[ ^1.0.0]

### Affected platforms

- [x] Chrome _(please specify version)_
- [ ] Firefox _(please specify version)_
- [ ] Internet Explore _(please specify version)_
- [ ] Other _(please specify which)_

**Comment by marijnh** [comment]
I'm not seeing this happen (typing into the block marked 'title your list' and then deleting the text doesn't cause further placeholders to disappear). Also the code contains at least one obvious bug (a misspelling of chunkPlaceholder) and seems quite a bit more complex than it needs to be if the bug is in ProseMirror—can you reduce it further?

**Comment by alidcastano** [comment]
![20171204_144951_1](https://user-images.githubusercontent.com/11031952/33575748-46792604-d903-11e7-92c9-9c7ed0d6a02c.gif)

Weird. Here's my live interaction with the above example. As you can see when I delete text in the title, the placeholder after it disappears. 

Sorry about the extra code, it was a fork from an example I found on the site. But I deleted all the irrelevant code and added modified the schema to match what was causing the behavior for me.

**Comment by adrianheine** [comment]
I can reproduce the behavior in the video in my Firefox 57.

**Comment by marijnh** [comment]
I still can't see it in Firefox, but from the video I could reproduce in Chrome. This triggered a bug in `DecorationSet.map`. Attached patch fixes it, and prosemirror-view 1.0.5 contains the fix.

**Comment by alidcastano** [comment]
My schema changed slightly, so not sure if released would have fixed it previously, but it's still currently occurring for me and I've updated to latest release
