### ISSUE TITLE
Private Node#defaultContentType method used in prosemirror-schema-list

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#737]
In [prosemirror-schema-list](https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.js#L138) a private `defaultContentType` method is used on `Node`. It seems desirable to restrict prosemirror-schema-list to only use public APIs so that it can serve as an example of how to implement a plugin.

**Comment by marijnh** [comment]
Opened https://github.com/ProseMirror/rfcs/pull/4 to make it easier to do this on top of public methods.

**Comment by marijnh** [comment]
Fixed by attached patches.
