### ISSUE TITLE
Type of handleDOMEvents

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#738]
Regarding https://prosemirror.net/docs/ref/#view.EditorProps.handleDOMEvents, I suspect the return type is supposed to be `?bool`?

This is going by https://github.com/ProseMirror/prosemirror-tables/blob/master/src/columnresizing.js#L29 which is fairly modern code that doesn't return booleans.

**Comment by adrianheine** [comment]
`undefined` is cast to `false`. I don't know how we handle such cases in the doc, but writing `?bool` would feel wrong to me, since that would imply there are three distinct return values.

**Comment by marijnh** [comment]
I think that `bool` is an appropriate type here. Returning a number from these would work too, but we don't want to say `?bool | number`, and so on. If you feel the table code should be more rigorous about actually returning a boolean, adding a `return false` there would be the way to go.
