### ISSUE TITLE
marksAcross() without arguments cause "cannot read property 'parent' of undefined"

### ISSUE THREAD

**Issue by astashov** [ProseMirror/prosemirror#739]
### Issue details

The docs don't specify any arguments for `marksAcross()`, but if you try to call it without arguments, you'll get "cannot read property 'parent' of undefined" error.

Look, [here](https://github.com/ProseMirror/prosemirror-model/blob/f8da03eedb2fb96c0e80b2039bf413476e98887e/src/resolvedpos.js#L159) it accepts `$end`, though it's not mentioned in the docs above.

And [here](https://github.com/ProseMirror/prosemirror-model/blob/f8da03eedb2fb96c0e80b2039bf413476e98887e/src/resolvedpos.js#L163) it will crash if `$end` is undefined.

### Steps to reproduce

Just call `marksAcross()` method.

### Please specify which version of ProseMirror you're running

prosemirror-model 1.0.1

### Affected platforms

All of them

**Comment by marijnh** [comment]
Yeah, that's definitely a mistake in the type declaration. Fixed by attached patch.

**Comment by astashov** [comment]
Thanks!!!

**Comment by astashov** [comment]
I know it's a very small thing, but when do you think you could release it? We use TypeScript, and the types are built from the docs, so now the types are wrong, and we have to do ugly casts here and there to workaround the issue.

Thanks!
