### ISSUE TITLE
Remove comments in files before publishing to NPM

### ISSUE THREAD

**Issue by 5id** [ProseMirror/prosemirror#740]
### Issue details
Investigating ways to reduce our bundle size while using Prosemirror, I noticed that the dist/* files published to NPM still retain the comments from the source files. Using prosemirror-model as an example, the comments account for roughly 1/3 of the size of index.js (before compression, etc.). 

We could strip these out ourselves, however there's often concerns around stripping copyright licensing info that some libraries licensing require.

It'd be great if as part of the rollup step Prosemirror could strip the comments out

### Please specify which version of ProseMirror you're running
ProseMirror v1.0.5

**Comment by doodlewind** [comment]
Not sure this is the best practice using rollup. With your module bundler you can minify dependencies in your project together with removing comments I suppose?

**Comment by 5id** [comment]
Yeah I've had a bit more of a look into this. It should more or less be solved during the uglification phase, I was just a bit surprised that it was being shipped in the as part of the NPM dist. It's probably better to keep the rollup config here as simple as we can, and push this sort of thing on the consumers
