### ISSUE TITLE
nodeView let user inserts text before contentDOM

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#741]
### Issue details

I'm building a nodeView that has a "constant" (supposedly non-editable) placed before contentDOM, like this:
https://github.com/kapouer/prosemirror-sample/blob/c9829c31d829618c4cbeb251279c79d7384de226/example2/main.js#L1-L44

### Steps to reproduce

https://crystal-fine.glitch.me/

Place caret at the beginning of the contentDOM and type some text.

Expected result: text is inserted inside the contentDOM.

Actual result:
- webkit: text is insert just before (chrome, but also webkitgtk, so i guess safari as well).
- firefox, text is inserted at the right place, but if placing caret before "constant" node, the first typed character will be inserted before that node.
- edge: behaves somewhat like firefox

### Please specify which version of ProseMirror you're running

ProseMirror v1.0

### Affected platforms

- [X] Chrome 55, 60, 63
- [X] Firefox 54, 57
- [X] Internet Explore Edge 16
- [X] Epiphany 3.26

### Somewhat working around

If i set `contenteditable="false"` on the "constant" node, behavior seems to be much better.

**Comment by marijnh** [comment]
> If i set contenteditable="false" on the "constant" node, behavior seems to be much better.

Yes, this is the recommended approach for such a situation. Is there a problem with it?

**Comment by kapouer** [comment]
No problem, i thought it was up to prosemirror-view to do that job !

**Comment by marijnh** [comment]
It's hard to automatically determine what is supposed to be editable and what isn't, so yes, the library relies on explicit use of the `contentEditable` attribute there.

**Comment by kapouer** [comment]
All nodes in nodeView.dom but not containing nodeView.contentDOM ?

**Comment by marijnh** [comment]
There might be editable information encoded in nodes besides `contentDOM`. Also, creating 'islands' of editable content inside uneditable nodes makes selecting from the outside to the inside or vice-versa impossible, which isn't great for use experience.

**Comment by kapouer** [comment]
However, i still dont understand why this other example behaves perfectly well:
https://zippy-value.glitch.me/
where the only thing that changes is https://github.com/kapouer/prosemirror-sample/blob/29e3cb1de417075da6223b6693fdb60c7dfe9797/example3/main.js#L15

**Comment by marijnh** [comment]
The browser won't put the cursor in non-inline contexts, so assuming that `<div>` is display: block, the user won't be able to put a selection directly in the outer `<div>`
