### ISSUE TITLE
Inserted image how to add a click event?

### ISSUE THREAD

**Issue by xgzl87** [ProseMirror/prosemirror#742]
### Issue details

Inserted image how to add a click event?

### Steps to reproduce
Inserted image how to add a click event?

### Please specify which version of ProseMirror you're running

ProseMirror v[ 1.0.1  ]

### Affected platforms

- [x] Chrome _(please specify version)_
- [x] Firefox _(please specify version)_
- [x] Internet Explore _(please specify version)_
- [x] Other _(please specify which)_

**Comment by marijnh** [comment]
This doesn't seem like it belongs here. If you want to ask a question, try https://discuss.prosemirror.net/ , but you'll have to provide **a lot** more context if you want anyone to be able to help.
