### ISSUE TITLE
editorView loses focus when nodeView has dom.contenteditable false and contentDOM.contenteditable true

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#743]
### Issue details

I guess everything's in the title...

### Steps to reproduce

Run https://github.com/kapouer/prosemirror-sample/blob/master/example4/
or check console and click inside the nodeViews or in the first paragraph at
https://brave-radar.glitch.me/index.html
or
https://glitch.com/edit/#!/brave-radar
 
### Please specify which version of ProseMirror you're running

ProseMirror 1.0

### Affected platforms

All, i guess.
- [X] Chrome 62

**Comment by marijnh** [comment]
See the discussion in #745 — editable islands will not be supported by this library.
