### ISSUE TITLE
nodeView with partially non-editable content: dom reader problems

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#745]
### Issue details

I made a schema which is basically (spaces inserted for readability)
```
<div class="item">
  <div class="title" contenteditable="false">
    <i>€</i>
    <span class="text" contenteditable="true">TITLE</span>
  </div>
  <div class="content">
    <p>CONTENT</p>
  </div>
</div>
```
item contains two nodes, title and content, and title tries to achieve what was discussed in #741.
When inserting DOM in the editor, it throws an exception `Invalid content for node item`.

### Steps to reproduce

Live sample and steps are explained at:
https://kapouer.github.io/prosemirror-sample/example5/
and the source for it is at
https://github.com/kapouer/prosemirror-sample/tree/master/example5

### Please specify which version of ProseMirror you're running

ProseMirror 1.0 (every modules to their latest versions as of today).

### Affected platforms

- [X] Chrome 62
- [X] Firefox latest
- [X] Epiphany 3.26 / webkitgtk 2.18

**Comment by kapouer** [comment]
The problem is on my side again: if i set selection to a place where it's legit to insert an "item", there is no bug.

**Comment by kapouer** [comment]
Ha damn, now it fails when i try to insert stuff at `doc.content.size`. Probably the non-editable content is not counted and positions are computed wrong.

**Comment by kapouer** [comment]
Then again, i insert DOM nodes out of selection.

**Comment by kapouer** [comment]
Sorry, but i'm pretty sure there's something wrong going on anyway:
It seems this shares a common cause with #743, because when i click on the `<span contenteditable=true>` no transaction happens (i updated the example5 so that it logs dispatched transactions) whereas any other click anywhere dispatches a transaction (selection change).
DOMChange then won't have proper state.selection and in some cases will compute a range that is wrong (and that messes things). I'm still trying to reproduce the "some cases" i'm seeing in a more complicated setup...

**Comment by kapouer** [comment]
... and i tracked this down to the place where [selection poller is stopped because view.dom receives blur event](https://github.com/ProseMirror/prosemirror-view/blob/9d2295d03c2d17357213371e4d083f0213441a7e/src/selection.js#L20), thus not updating selection when a mousedown event is made inside the contentDOM of this nodeView.
The blur event is caused because somehow browser considers focusing inside a non-contenteditable part of view.dom is like going out of view.dom (?!?).

**Comment by marijnh** [comment]
Yeah, I think I gave to simple an answer in the other issue. Does a DOM structure like this, which doesn't create a new editable island, provide better results?

```html
<div class="title">
  <i contenteditable=false>€</i>
  <span class="text">TITLE</span>
</div>
```

**Comment by kapouer** [comment]
w.r.t. losing focus, yes, but it loses what i tried to do in the first place - making sure it's not possible to type text outside the contentDOM, as you can check in https://kapouer.github.io/prosemirror-sample/example6/index.html (where you can type a character left of the euro sign).

**Comment by marijnh** [comment]
Good point. Editable HTML is really bad at this, and ProseMirror doesn't really have a way to paper that over. In this specific case, you could probably make the `$` a CSS `:before` element to get the behavior you want. Or make the inner element (`class=text`) a block (on the CSS level) element and use CSS and padding hacks to position the `$` in the right place. But a general solution doesn't exist yet.

**Comment by kapouer** [comment]
Are there complications about adding checks in the blur/focus handlers ?
Something like checking if the blur event target is actually inside an editable island of the current view.dom ?

**Comment by marijnh** [comment]
> Are there complications about adding checks in the blur/focus handlers ?

Yes, there are. Such an island is considered a separate editable element by the browser, and events for edits inside it will fire on the island node, rather than the outer editable node.

**Comment by kapouer** [comment]
Another idea: nodeView could redispatch those editor events to view.dom ? I just tried that and it somehow worked.

**Comment by marijnh** [comment]
I think I am going to consider this kind of DOM structure (editable islands) unsupported. Even if you can sort of make it work with kludges, I expect it to break in all kinds of interesting ways in corner cases. Usually, the structure of the node view can easily be adjusted to put the uneditable content in a node that's not a parent of the editable content, and in cases where that is really impossible, I recommend nesting a separate ProseMirror instance for the content and broadcasting the steps to the parent document (as in the [footnote demo](http://prosemirror.net/examples/footnote/)).
