### ISSUE TITLE
Inserted image how to add a click event? 

### ISSUE THREAD

**Issue by xgzl87** [ProseMirror/prosemirror#746]
### Issue details

Inserted image how to add a click event?

### Steps to reproduce
Inserted image how to add a click event?
![image](https://user-images.githubusercontent.com/12945325/34136916-00597fb0-e4a3-11e7-9b77-1ae88d2c800a.png)

### Please specify which version of ProseMirror you're running

ProseMirror v[ 1.0.1  ]

### Affected platforms

- [x] Chrome _(please specify version)_
- [x] Firefox _(please specify version)_
- [x] Internet Explore _(please specify version)_
- [x] Other _(please specify which)_

**Comment by doodlewind** [comment]
For your image plugin, you can provide a `handleClick` handler to its `Plugins.props`, then handle the click event in top-most editor frame, wire in your popup logic and return `true` if event is related to your image, `false` if other editor nodes are clicked.

For my understanding, ProseMirror does not provide the React-like component event handlers and lifecycle hooks, so implementing some behaviors may require a bit more work :)

**Comment by xgzl87** [comment]
Thank you for your answer, this is a good idea

**Comment by doodlewind** [comment]
@xgzl87 I suppose you can turn to the [forum](discuss.prosemirror.net) for more details? To my knowledge here is the bug tracker instead of Q&A?

**Comment by xgzl87** [comment]
ok
