### ISSUE TITLE
Node attributes not preserved with new line

### ISSUE THREAD

**Issue by doodlewind** [ProseMirror/prosemirror#748]
### Issue details
With the `splitBlockKeepMarks` command, we can preserve marks with new line. This works great, whereas there are also "styles" stored in node attributes. Say if the paragraph node has a `align` attribute, when pressing <kbd>enter</kbd> at end of a center-aligned line, it's natural to keep the center align intact.

### Steps to reproduce
This minimal reproduction [snippet](https://glitch.com/edit/#!/capable-plywood?path=index.js:1:0) enables aligned schema for paragraph node, on its [live page](https://capable-plywood.glitch.me/), pressing enter on end of first right aligned line, bold marks retained but align state is lost.

As a contrast, pressing enter in middle of this line has expected behaviour, editor splits new line with inherited align.

### Please specify which version of ProseMirror you're running
Latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] IE unknown

**Comment by marijnh** [comment]
This is by design -- when you press enter at the end of a textblock, you create a _new_ default textblock, not a copy of the one you were in. You also see this when you, for example, press enter at the end of a heading and create a paragraphy.

You'll have to write your own version of the command if you want the copying behavior.

**Comment by Gamerth-cyo** [comment]
hi, i'm having the exact opposite behavior, when i press enter and a new block is created, it inherits the attributes (which i don't want to). 

has anything changed since you replied this question to this user? thanks in advance.
