### ISSUE TITLE
Missing first-class method translating between pos and DOM

### ISSUE THREAD

**Issue by doodlewind** [ProseMirror/prosemirror#749]
### Issue details
Transforming between DOM node and ResolvedPos is widely required in an editor project, i.e.:

* Arrow key events can change cursor position, if a custom block is selected by pressing arrow key, we need to customize the block node. In this case we need to find DOM node by `pos` in plugin's keyup handler.
* For context menu events, different types of menu may be displayed according to mouse position on `contextmenu` event. In this case we need to find `pos` by DOM node in `e.target`, then can we find `node` via `pos` and wire in custom logic.

Although I found the `view.docView` model from source code and its `domFromPos` / `posFromDOM` method helps, from current documentation I haven't found an intuitive way for such operation, so I'm not aware of the risk using them. Is this module designed to be private or I'm missing something?

### Steps to reproduce
Simple checkout docs on official site 😅

### ProseMirror version
Latest

**Comment by marijnh** [comment]
> we need to customize the block node

As in directly manipulate it? You shouldn't do that, generally—the DOM nodes rendered by the editor are off limits for direct manipulation. Can you create the effect you're looking for with a decoration?

> In this case we need to find pos by DOM node in e.target

Doesn't feeding the event's `clientX` and `clientY` to `posAtCoords` help?

**Comment by doodlewind** [comment]
Thanks for your advice, `posAtCoords` works great!

> Can you create the effect you're looking for with a decoration?

The advanced case of finding DOM node via pos, instead of decoration is challenging for us.

Say we have an editor that supports attachment nodes, during uploading, a placeholder block with **progress bar** is shown in editor.

Here comes the problem: with multi files uploading we have multi placeholder blocks, each upload progress event should update the "correct" progress bar. Since during uploading, user can still input and change document `pos`, so updating decoration via `pos` can be leaky. As a workaround, we introduce `id` attrs for attachement block, for upload progress events, finding DOM node via `id`, finding pos via DOM node, then updating progress bar decoration works, but verbose indeed.

In a word, the question is **when maintaining multi block with different "state", what's the best mental model to rely on?** In this scenario undo stack is also leaky, since updating decoration also records to the stack, undoing this makes progress bar move backward 😅 (that looks pretty impressive...)

Hope for your thoughts!

**Comment by marijnh** [comment]
Decorations can do all that. Add widgets in the appropriate places and remove and recreate the relevant decorations when the state changes. You have to stop thinking in terms of a mutable DOM—state goes in the editor state, and the DOM is just a reflection of that state.
