### ISSUE TITLE
DecorationSet.remove does not use decoration's equality checks.

### ISSUE THREAD

**Issue by brainkim** [ProseMirror/prosemirror#750]
### Issue details
DecorationSet.remove with a widget decoration uses object identity and not the decoration type's defined equality check

```javascript
let div = document.createElement('div')
let start = 5
let widget = Decoration.widget(start, div)
let widget1 = Decoration.widget(start, div)
widget.type.eq(widget1.type) // true
let decorationSet = DecorationSet.empty
decorationSet = decorationSet.add(editorState.doc, [widget])
decorationSet = decorationSet.remove([widget1])
// decorationSet still contains first widget
decorationSet = decorationSet.remove([widget])
// decorationSet no longer contains widget
```
For me, the expected behavior would be to use the decoration's defined equality semantics to remove any matching decorations from the decoration set. In the case of the widget decoration, equality is based on whether the inserted dom node matches, if there is no key property in the spec. In the code, it would mean turning `local[j].type == span.type` to `local[j].type.eq( span.type )` in the following line:
https://github.com/ProseMirror/prosemirror-view/blob/master/src/decoration.js#L334

### ProseMirror version
Latest

**Comment by marijnh** [comment]
Agreed. Attached patch makes the suggested change. I've released it as prosemirror-view 1.0.6.
