### ISSUE TITLE
Error running examples on official site

### ISSUE THREAD

**Issue by doodlewind** [ProseMirror/prosemirror#751]
### Issue details
All examples on [prosemirror.net](http://prosemirror.net/) are unusable for now.

### Steps to reproduce
Open [basic example](http://prosemirror.net/examples/basic/) and see errors reported in console:

```
prosemirror.js:1 Uncaught ReferenceError: prosemirrorModel is not defined
    at Function.e.create (prosemirror.js:1)
    at Be.addNode (prosemirror.js:1)
    at prosemirror.js:1
    at R (prosemirror.js:1)
    at e.updateChildren (prosemirror.js:1)
    at new e (prosemirror.js:1)
    at k (prosemirror.js:1)
    at new wn (prosemirror.js:1)
    at example.js:12
    at example.js:20
```

### ProseMirror version
Latest

### Affected platforms
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer unknown
- [ ] Other unknown

**Comment by adrianheine** [comment]
This should be reported at https://github.com/ProseMirror/website. I definitely remember seeing this problem before, but I cannot currently reproduce it locally. @marijnh?

**Comment by marijnh** [comment]
Thanks for letting me know! I had upgraded Rollup to a version that apparently creates broken output. Upgrading further fixed the issue, and is done in https://github.com/ProseMirror/website/commit/cd04492bb34400db3585bcaf5f49df4b1c83c53b
