### ISSUE TITLE
Demo doesn't run

### ISSUE THREAD

**Issue by adamdonahue** [ProseMirror/prosemirror#753]
I'm having trouble getting the demo code to run.  I suspect it's because moduleserve has changed, or there are some missing symlinks or files?  In any case, out of the box, after installing and building via bin/pm, running `npm run demo` and accessing `http://localhost:8080/` raises an exception:

![image](https://user-images.githubusercontent.com/2406542/35017922-33f89314-faed-11e7-881a-6dd5abfcee4d.png)

Perhaps you can snapshot what exactly your development environment looks like now, or let us  know if anything has changed.

**Comment by marijnh** [comment]
I just cloned prosemirror/prosemirror, and then ran `bin/pm install` and `npm run demo`, which got me a working demo. Did your build finish successfully? Is there a `node_modules/prosemirror-model` linked to `model`? Does `model/dist/index.js` exist?

**Comment by adamdonahue** [comment]
Let me verify.  Could be a version thing.

**Comment by adamdonahue** [comment]
There is no `node_modules/prosemirror-model` file at all, nor any other ProseMirror links.  I looked through the diff of `pm.js` and see that you'd removed the linking in favor of Yarn, and my outdated Yarn was the issue.  Thanks for verifying.
