### ISSUE TITLE
Question about the versioning strategy

### ISSUE THREAD

**Issue by Narretz** [ProseMirror/prosemirror#759]
As far as I can tell, after version 1.0.0 for each module, these modules were updated with patch versions when only fixes were added, but in the minor version when features were added - at least this is how it looks like in the changelog. However, prosemirror-state is latest 1.1.0, which actually contains a bug fix: https://github.com/ProseMirror/prosemirror-state/commit/53325f3c6b394c455cc3b4d19e7a82c2794b48be

Now the problem is that the individual modules have ^ dependencies in the package.json. That means, for example if you want to use prosemirror-state@1.1.0 to get the bug fix, but you are also using prosemirror-inputrules@1.0.1, and you use yarn to install your dependencies, inputrules will create sub-dependencies, which in turn can break prosemirror completely, as components pull in multiple versions of other components. (You can fix this with "resolutions" in package.json / possibly your module loader, but it's far from ideal.

So I would like to see the version strategy clarified - and possibly, either state should get a new 1.0.3 patch release, or the dependant modules should relax their version contstraints so they can pull in 1.1.0

**Comment by marijnh** [comment]
> However, prosemirror-state is latest 1.1.0, which actually contains a bug fix: ProseMirror/prosemirror-state@53325f3

No, that's a new feature.

> Now the problem is that the individual modules have ^ dependencies 

Isn't that exactly the right thing? `"^1.0.0"` matches 1.1.0 (anything between 1.0.0 and 2.0.0, in fact). I'm not sure why your tool is creating recursive installs of the modules, but it shouldn't.

**Comment by Narretz** [comment]
Oh my, I mixed up my ~ and ^ again, sorry about that.

[yarn](https://yarnpkg.com/lang/en/) is adding the dependencies explicitly multiple times if package (a) is requiring a version of package (b) that is not satisfied by the version you require of package (b) in your package.json (for example).

I guess the dependency tree was broken to due my own doing.

> No, that's a new feature.

Ok. But then maybe it shouldn't have "Fixing" in the commit message ;)
