### ISSUE TITLE
hasOwnProperty is not a function 

### ISSUE THREAD

**Issue by kurtharriger** [ProseMirror/prosemirror#761]
### Issue details

`Object.create(null)` optimization creates issues using hasOwnProperty.  

https://github.com/ProseMirror/prosemirror-model/blob/cdded3da5d0a21f1091f6eb6232d568af4a8e76d/src/schema.js#L13

### Steps to reproduce

Test case to reproduce issue
```
      const data = {
        "type": "text",
        "marks": [
          {
            "type": "link",
            "attrs": {
              "href": "https://google.com"
            }
          }
        ],
        "text": "Link"
      };

      const node = schema.nodeFromJSON(data);
      const json = node.toJSON();

      // ok
      data.marks.attrs[0].hasOwnProperty('href');
      // broken: Uncaught TypeError: json.marks[0].attrs.hasOwnProperty is not a function 
      json.marks.attrs[0].hasOwnProperty('href');

```

Currently using `JSON.parse(JSON.stringify(json))` as a workaround.

### ProseMirror version

1.0.0

### Affected platforms

Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by marijnh** [comment]
> Object.create(null) optimization creates issues using hasOwnProperty.

Do I understand correctly that call to `hasOwnProperty` comes from your own code, not ProseMirror? If so, the broken assumption is in your code (use `Object.prototype.hasOwnProperty.call` instead), not the library.

**Comment by kurtharriger** [comment]
That is sort of true, hasOwnPropery is not used in prosemirror, but the assumption is not in solely in my code but a common pattern in many third party libraries, specifically in my case this issue https://dev.clojure.org/jira/browse/CLJS-2408

As far as I can tell Object.create(null) is a hack promoted [here](http://adripofjavascript.com/blog/drips/creating-objects-without-prototypes.html), but does not seem to be a common pattern in many other libraries.  I think it is fine if prosemirror uses it internally, but it would be great if toJSON in the public api returned objects.

**Comment by marijnh** [comment]
If you're going to use objects as dictionaries, which the attribute objects are, you can't rely on `getOwnProperty` not being overwritten anyway, so no, using `getOwnProperty` as a method on such objects is shaky, and not something the library should feel obliged to make possible.
