### ISSUE TITLE
Cannot set property 'pmViewDesc' of undefined

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#764]
### Issue details

I found an issue in `prosemirror-view` while testing tables (uses `nodeView`) in collab editing mode. At a certain moment (one person is typing something inside a table, another person creates a CellSelection on the same cell (by clicking on a button "select column x" -> dispatches a transaction)) it throws an error `Cannot set property 'pmViewDesc' of undefined`.

### Steps to reproduce

Apparently the problem appears inside ViewDesc class
```
class ViewDesc {
  // : (?ViewDesc, [ViewDesc], dom.Node, ?dom.Node)
  constructor(parent, children, dom, contentDOM) {
    this.parent = parent
    this.children = children
    this.dom = dom
    // An expando property on the DOM node provides a link back to its
    // description.
    dom.pmViewDesc = this
    // This is the node that holds the child views. It may be null for
    // descs that don't have children.
    this.contentDOM = contentDOM
    this.dirty = NOT_DIRTY
  }
  ...
```
At some point `dom` reference becomes `undefined`. The simplest way to reproduce I could find is to open prosemirror website (cloned `website` repo), put a debugger inside ViewDesc's constructor and then resume the page load. It will throw the same error:

```
Cannot set property 'pmViewDesc' of undefined
    at NodeViewDesc.ViewDesc (eval at evalFunction (load.js:68), <anonymous>:514:18)
    at new NodeViewDesc (eval at evalFunction (load.js:68), <anonymous>:964:14)
    at docViewDesc (eval at evalFunction (load.js:68), <anonymous>:1129:10)
    at new EditorView (eval at evalFunction (load.js:68), <anonymous>:4083:18)
    at eval (/../example/basic/index:16)
    at Module.require (load.js:58)
    at load.js:79
    at load.js:80
```

### ProseMirror version

prosemirror-view `1.0.11`

### Affected platforms

- [ x] Chrome
- [x ] Firefox

Thanks.

**Comment by marijnh** [comment]
Hi. Your stacktrace shows a ProseMirror instance being initialized, but your initial reproduction instructions suggest this happens during editing. And then you suggest that this can be reproduced by adding a breakpoint when loading the basic example, which seems odd, because the basic example loads without that error. Can you explain what you mean?

**Comment by eshvedai** [comment]
Sorry for the confusion. Initially I caught the error while editing tables, but I thought it'd be impossible to communicate the repro instructions because it involves collab editing and semi-random clicking so I wanted to find a simpler way to get the same error.

The basic example loads without the error as expected, unless you follow the steps from this video:

![pm-view-video](https://user-images.githubusercontent.com/26512812/36419301-9ae9f4e2-1685-11e8-91e0-4dfabc44b479.gif)

I'm sure no one will ever put a debugger there just for fun, I did it only to demo how I got exactly the same error with collab. 

I assume its a timing issue, because `dom` argument has reference at first, but turns into `undefined` at some point:

![pm-view-video2](https://user-images.githubusercontent.com/26512812/36419795-0dcfeab0-1687-11e8-9ebe-4b115a126b3b.gif)

I'd say its a dev console joke if I hadn't seen the same error with collab.

**Comment by eshvedai** [comment]
Sorry for the confusion, I'll try to find a better way to repro this error

**Comment by eshvedai** [comment]
Okay, the problem is fixed with a workaround, but if you don't have anything better to do, you can probably investigate what's going on. Here are steps to reproduce (you're gonna love this):

1. Open a document with a table, in my case its something like that:
```
defaultValue={{"type":"doc","content":[{"type":"table","attrs":{"isNumberColumnEnabled":false},"content":[{"type":"tableRow","content":[{"type":"tableHeader","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]},{"type":"tableHeader","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph","content":[{"type":"text","text":"test"}]}]},{"type":"tableHeader","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]}]},{"type":"tableRow","content":[{"type":"tableCell","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]},{"type":"tableCell","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]},{"type":"tableCell","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]}]},{"type":"tableRow","content":[{"type":"tableCell","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]},{"type":"tableCell","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]},{"type":"tableCell","attrs":{"colspan":1,"rowspan":1,"colwidth":null,"background":null},"content":[{"type":"paragraph"}]}]}]}]}}
```

2. Generate state updates with `editorView.updateState(editorView.state.tr.insertText('1', 8))` in `setInterval`, just to emulate collab editing of the table (maybe you could find a better approach for that). 

3. While the table content is updating, create `CellSelection` on a range of cells (in my case its possible by clicking on a button).

4. The fun part: table has a `nodeView`, also selected cells have node decoration (className). So the error happens when I apply step 3 (`CellSelection`) on those cells with decoration, table keeps updating from setInterval. My assumption is that table nodeView gets re-rendered when ProseMirror re-creates DOM nodes for edited cells, which kills DOM references (ViewDesc get `dom` = `undefined`)

The issue is fixed by removing decorations from those cells whenever `tr.docChanged = true`, which okay for us.

**Comment by marijnh** [comment]
> My assumption is that table nodeView gets re-rendered when ProseMirror re-creates DOM nodes for edited cells

Yes, it may do that.

> which kills DOM references (ViewDesc get dom = undefined)

Which DOM reference is this? The `dom` property of the node view? And who kills it?
