### ISSUE TITLE
scrollIntoView throws error for NodeSelection at end of the document.

### ISSUE THREAD

**Issue by jpuri** [ProseMirror/prosemirror#765]
### Issue details

Following gives issue if anchor is instance of NodeSelection at the end of doc.
`state.tr.setSelection(anchor).scrollIntoView()`
It works fine if `.scrollIntoView()` is removed from above.

### Steps to reproduce
Set selection to a terminal node in the editor.

### ProseMirror version
prosemirror-transform: 1.0.0
prosemirror-view: 1.0.0
prosemirror-state: 1.0.0

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Other

**Comment by jpuri** [comment]
Here is the error:
```
Uncaught RangeError: No node after pos 4
    at NodeViewDesc.domAfterPos (index.js:761)
    at EditorView.updateState (index.js:4168)
    at dispatchTransaction (create-editor.ts:179)
    at EditorView.dispatch (index.js:4329)
    at Object.moveCursorToTheEnd (index.ts:227)
```
Also, plz note that its not textNode, node has nodeView.
I am trying to replicate it in demos.

**Comment by marijnh** [comment]
That suggests either the DOM ended up in an unexpected state (the node that is selected isn't found in the DOM) or the selection object is invalid (pointing into the wrong document)

**Comment by jpuri** [comment]
Selection is set correct, in fact if I remove this `.scrollIntoView()` there is no exception.

**Comment by jpuri** [comment]
Issue is not replicating in demos, if I remove nodeViews from nodes - its fixed in my code also.

**Comment by marijnh** [comment]
Okay. If you can put together a minimal demo that reproduces this with a node view, I'd be interested in taking a look.

**Comment by jpuri** [comment]
Its happening in our code with nested node views in React but not replicating with simple node views I tried in demos. This does not seems to be issue with the lib.
Sorry for bothering you with this.
