### ISSUE TITLE
The given range isn't in document Error

### ISSUE THREAD

**Issue by Gozala** [ProseMirror/prosemirror#767]
### Issue details

I get a strange `The given range isn't in document Error` error during cursor movements. From what I can tell that is due to strange `Selection` instance that has `anchorNode` set to `null` and as far as I can tell `ProseMirror` such selection to ever occur (or at least [there this cases](https://github.com/ProseMirror/prosemirror-view/blob/6f5b7bee8940c268bc3aafc7a1ec05150c9b7cac/src/capturekeys.js#L102) where it dose not and throws)

### Steps to reproduce

~~So far I'm struggling to isolate this issue from the rest of my code base, I'll update this issue once I'm able to create reproducible test case. I though it was still worth reporting this given that ProseMirror does not handle case where anchorNode is `null`.~~

Here is [an example](https://glitch.com/edit/#!/join/a7d24326-4dc9-41ce-8449-b6a5f47a7846). I also narrowed down issue to be caused by following combination of things:

1.  `inclusive: false` in the mark that are added.
2. Having a custom NodeView.

### ProseMirror version

```
yarn list | grep prosemirror
├─ prosemirror-commands@1.0.5
│  ├─ prosemirror-model@^1.0.0
│  ├─ prosemirror-state@^1.0.0
│  └─ prosemirror-transform@^1.0.0
├─ prosemirror-dropcursor@1.0.0
│  ├─ prosemirror-state@^1.0.0
│  ├─ prosemirror-view@^1.0.0
│  └─ prosemirror-view@1.0.10
│     ├─ prosemirror-model@^1.1.0
│     ├─ prosemirror-state@^1.0.0
│     └─ prosemirror-transform@^1.0.0
├─ prosemirror-gapcursor@1.0.1
│  ├─ prosemirror-keymap@^1.0.0
│  ├─ prosemirror-keymap@1.0.0
│  │  ├─ prosemirror-state@^1.0.0
│  ├─ prosemirror-model@^1.0.0
│  ├─ prosemirror-state@^1.0.0
│  ├─ prosemirror-view@^1.0.0
│  └─ prosemirror-view@1.0.10
│     ├─ prosemirror-model@^1.1.0
│     ├─ prosemirror-state@^1.0.0
│     └─ prosemirror-transform@^1.0.0
├─ prosemirror-history@1.0.0
│  ├─ prosemirror-state@^1.0.0
│  ├─ prosemirror-transform@^1.0.0
├─ prosemirror-inputrules@1.0.1
│  ├─ prosemirror-state@^1.0.0
│  └─ prosemirror-transform@^1.0.0
├─ prosemirror-keymap@1.0.1
│  ├─ prosemirror-state@^1.0.0
├─ prosemirror-menu@1.0.3
│  ├─ prosemirror-commands@^1.0.0
│  ├─ prosemirror-commands@1.0.4
│  │  ├─ prosemirror-model@^1.0.0
│  │  ├─ prosemirror-state@^1.0.0
│  │  └─ prosemirror-transform@^1.0.0
│  ├─ prosemirror-history@^1.0.0
│  └─ prosemirror-state@^1.0.0
├─ prosemirror-model@1.1.0
├─ prosemirror-schema-basic@1.0.0
│  └─ prosemirror-model@^1.0.0
├─ prosemirror-schema-list@1.0.0
│  ├─ prosemirror-model@^1.0.0
│  └─ prosemirror-transform@^1.0.0
├─ prosemirror-state@1.1.0
│  ├─ prosemirror-model@^1.0.0
│  └─ prosemirror-transform@^1.0.0
├─ prosemirror-transform@1.0.2
│  └─ prosemirror-model@^1.0.0
├─ prosemirror-view@1.1.1
│  ├─ prosemirror-model@^1.1.0
│  ├─ prosemirror-state@^1.0.0
│  └─ prosemirror-transform@^1.0.0
```
### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

### Screenshots / Screencast (Optional)

<img width="806" alt="screen shot 2018-03-09 at 11 26 43 am" src="https://user-images.githubusercontent.com/21236/37226190-f8cfdc88-238d-11e8-802a-9060663494a2.png">

**Comment by Gozala** [comment]
This seems to be related to the fact that I dispatch transaction that adds markup fragments (text nodes marked with custom mark) around the marked text ranges. It appears that this error occurs every time cursor is about to enter or leave marked segment and only if the markup is added at the beginning and end of the node.

**Comment by marijnh** [comment]
Thanks for the reduced reproduction. Attached patches should solve this. I'll release them in a few days.

**Comment by Gozala** [comment]
@marijnh Thank you!

**Comment by nithisathish** [comment]
Fixed it in Angular 7 by adding below code.
@ViewChild('editor') editor: Editor;
setTimeout(() => {
this.editor.writeValue(data);
this.editor.quill.setSelection(null, data.length, null);
}, 100);
