### ISSUE TITLE
Wrap in ordered list splits last node when selection contains a list

### ISSUE THREAD

**Issue by kevinzang** [ProseMirror/prosemirror#769]
### Issue details

When "wrap in ordered list" button is used over a selection that contains a list, the last node in the selection gets unexpectedly split.

### Steps to reproduce

Copy-paste the following into the example editor at http://prosemirror.net/

-------------

<p>All</p><ol><li><p>About</p></li></ol><p>Acorns</p>

-------------

Select all of the text.
Click the "wrap in ordered list" button.
The result:

-------------

<ol><li><p>All</p><ol><li><p>About</p></li></ol><p>A</p><p>corns</p></li></ol>

-------------

Is there any way to prevent the last node "Acorns" from getting split into "A" "corns"?

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
That was a bug in the `wrapInList` command—it was trying to split the bottom paragraph into its own list item, but miscounted and ended up splitting the paragraph itself. Fixed by attached patch, which is released as prosemirror-schema-list 1.0.1

**Comment by kevinzang** [comment]
Thanks for fixing it so quickly! I confirm it works in prosemirror-schema-list 1.0.1.
