### ISSUE TITLE
Ask about browser compatibility

### ISSUE THREAD

**Issue by walnutzhang** [ProseMirror/prosemirror#770]
Hi, thanks for this great project! I wanna ask about the browser compatibility of this library because I can't find it in the documentation. I found some code about ie < 11 but I'm not sure how well it work on IE9 - IE10. Thanks.

**Comment by marijnh** [comment]
We're targeting IE11 + halfway recent versions of evergreen browsers. Fixes that make things better on IE9/10 are accepted, but I am not going to test that platform.
