### ISSUE TITLE
toggleMark worked unexpectedly

### ISSUE THREAD

**Issue by walnutzhang** [ProseMirror/prosemirror#771]
### Issue details

hi, I have a mark section in my schema like this:

```
  color: {
    attrs: {
      color: { default: '' }
    },
    parseDOM: [
      {
        style: 'color',
        getAttrs (value) {
          return { color: value }
        }
      }
    ],
    toDOM (mark) {
      let { color } = mark.attrs
      return ['span', { style: `color: ${color}` }, 0]
    }
  }
```

and then, I use `toggleMark(schema.marks.color, { color: 'red' })`  to generate a command, my purpose is to wrap the selection with red color span. if there were no color span before, the command worked as expeced. but if there were already a span with another color around the selection, I need run the command twice. the first time it just remove the original colored span, the second time it add the new colored span.  What I expected is, if there's already a colored span, modify the span directly.  is it possible to do that with the toggleMark command?

thanks

**Comment by marijnh** [comment]
> is it possible to do that with the toggleMark command?

No, as its name implies, this command _toggles_ a given mark type on and off. Sounds like you want a relatively simple command that calls `Transaction.addMark` on the selection instead.
