### ISSUE TITLE
Cursor jumps to the second required block when erasing content

### ISSUE THREAD

**Issue by mitar** [ProseMirror/prosemirror#772]
### Issue details

When having two required blocks, if I delete the content, the cursor skips to the second block.

### Steps to reproduce

See example here:

https://glitch.com/edit/#!/button-war?path=index.js:20:23

1. Type into a title something, with cursor being at the end of the title content.
2. Press ctrl-a to select everything.
3. Press backspace to erase everything.
4. See cursor jumping to the second block, instead of going to the beginning of the title.

### ProseMirror version

Whatever is at https://prosemirror.net/examples/prosemirror.js (a comment with a version would be helpful). Not sure how to report this because there are many packages involved.

### Affected platforms

- [x] Chrome
- [x] Firefox

**Comment by marijnh** [comment]
This somehow got lost in my email pile, sorry. Attached patch should fix it.

**Comment by mitar** [comment]
Thanks! Better later than never. :-)
