### ISSUE TITLE
Inclusivity does not work when you get to the edge of the mark through deletion

### ISSUE THREAD

**Issue by mitar** [ProseMirror/prosemirror#773]
### Issue details

If I get to a bold content in the [basic example](http://prosemirror.net/examples/basic/) by deleting content afterwards with backspace key, and then start typing, the new content is not bold. If I do the same by moving a cursor with arrow key, it is bold.

### Steps to reproduce

1. Have some content like: foo **bar** faa
2. Start deleting "faa" until you hit the "bar"
3. Start typing something new
4. New content is not bold

### ProseMirror version

Whatever is at https://prosemirror.net/examples/prosemirror.js (a comment with a version would be helpful). Not sure how to report this because there are many packages involved.

### Affected platforms

- [x] Chrome
- [x] Firefox

**Comment by marijnh** [comment]
This is intentional and mirrors how most WYSIWYG editors handle this (compare for example Google Docs)—when you insert something directly after deleting text, the inserted content gets the same marks as the deleted content.

**Comment by mitar** [comment]
Hm. I compared with LibreOffice where this is not like this.
