### ISSUE TITLE
Provide property for `OrderedMap<MarkSpec>` and `OrderedMap<MarkSpec>`

### ISSUE THREAD

**Issue by Gozala** [ProseMirror/prosemirror#774]
### Issue details

Can prose-mirror please expose access to  `nodes` and `marks` that are `OrderedMaps` instead of `Object<MarkSpec> | OrderedMap<MarkSpec>`. As far as I can tell `schema.spec` in practice is always contains `OrderedMap` but as it's not reflected in the type-signature (presumably because non OrderedMap version was for instantiation of Schema)  it makes extending existing schema somewhat cumbersome as one needs to add `OrderedMap` to the dependency tree etc..

**Note:** I'm using flow with prose-mirror and there is no easy way to deal with this.

**Comment by marijnh** [comment]
> As far as I can tell schema.spec in practice is always contains OrderedMap

Yes, it is specified to. Can't you just typecast it?

**Comment by Gozala** [comment]
> Yes, it is specified to. Can't you just typecast it?

Yes but I'd need to `instanceof OrderedMap` and there for add `OrderedMap` as dependency. It's not too bad except cases where I end up with diff version of `OrderedMap`.

Alternative could be to just expose `OrderedMap` class from `prosemirror-model` which would avoid above pitfall.

**Comment by marijnh** [comment]
Ugh, the burdens of type systems. But since changing to a breaking version of `OrderedMap` would be a breaking version in ProseMirror, I think you can assume that the `"^1.0.0"` version is going to be compatible with anything ProseMirror uses in the foreseeable future, and depend on that.
