### ISSUE TITLE
Support passing storedMarks to EditorState.create

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#775]
It would be useful to allow EditorState.create to be passed storedMarks. At the moment I need to do something like this:

```
const editorState = EditorState.create({ doc });
editorState.storedMarks = …
```

**Comment by marijnh** [comment]
That's a good idea. Want to write a short RFC with a proposed interface? (I guess supporting a config field called `storedMarks` is all this will involve.)

**Comment by marijnh** [comment]
I guess it wasn't worth writing an RFC for ;). I'm going to close this, since immediately applying a transaction that enables the stored marks when creating your new state is easy enough, and this is probably not a very common use case.
