### ISSUE TITLE
DOMParser adds extra <br> inside <p><br></p>

### ISSUE THREAD

**Issue by kevinzang** [ProseMirror/prosemirror#776]
### Issue details

DOMParser adds extra `<br>` inside `<p><br></p>`, turning it into `<p><br><br></p>`. Is there any way to avoid this extra `<br>`?

I'm building an "HTML view" of the editor which allows user to enter HTML directly. If content ends with a newline, then every time user toggles between the normal WYSIWYG view and the HTML view, an extra `<br>` is appended in the WYSIWYG view.

### Steps to reproduce

See https://glitch.com/edit/#!/confused-crayfish?path=index.html:15:13. HTML inside `#content` is:

```
<p>test</p>
<p>test</p>
<p><br></p>
```

but inside the contenteditable, it becomes:

```
<p>test</p>
<p>test</p>
<p><br><br></p>
```

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by kapouer** [comment]
I made the same mistake ! I suppose you don't use a [http://prosemirror.net/docs/ref/#model.DOMSerializer](DOMSerializer) to show the html view, and instead you just clone the editor node ?

**Comment by kevinzang** [comment]
@kapouer you're right! I did not use DOMSerializer- I used something like `$('.ProseMirror')[0].innerHTML` to get the HTML from the editor. Using DOMSerializer is one solution to this issue- it turns `<p><br></p>` into `<p></p>`, avoiding the extra `<br>`. But I am kind of worried about the performance of parsing back and forth between ProseMirror doc and HTML. It seems like it would be slower than using innerHTML.

@marijnh would you recommend DOMSerializer for this case?

**Comment by kevinzang** [comment]
There's also the edge case where we'd still run into this issue when initializing the ProseMirror doc with HTML that contains `<p><br></p>`, as is the case in [the repro](https://glitch.com/edit/#!/confused-crayfish?path=index.html:15:13).

**Comment by marijnh** [comment]
> @marijnh would you recommend DOMSerializer for this case?

Absolutely. The HTML inside the editor is not a clean representation of the document, since it has to work around browser quirks like this.

> There's also the edge case where we'd still run into this issue when initializing the ProseMirror doc with HTML that contains <p><br></p>,

I don't think there is—the extra `<br>` is only added when rendering such a paragraph in the editor, it doesn't become part of the actual document.
