### ISSUE TITLE
Prosemirror does not handle DOM focus events

### ISSUE THREAD

**Issue by Gozala** [ProseMirror/prosemirror#777]
### Issue details

If focus event is dispatched on one of nodes with-in the editor prosemirror does not handle it. For example if there is a `tabindex` attribute present on the paragraph or heading nodes using `Tab` / `Shift-Tab` key combination dispatches focus event on a corresponding node (which does not bubble up if container is focused) so prose-mirror does not handle it in any way.

It is also won't make it into [handleDOMEvents](http://prosemirror.net/docs/ref/#view.EditorProps.handleDOMEvents) for the same reason.

### Steps to reproduce

Here is an example that adds `tabindex=0` attribute to the `paragraph` and `heading` nodes
https://glitch.com/edit/#!/join/a592d66e-470c-4c5d-a7d9-9c351aae426d

If you press `Tab` / `Tab-Shift` you'll see an outline appearing on o corresponding node but selection will remain in it's original location. 

I would expect `Tab` / `Tab-Shift` to update selection so that content of the corresponding paragraph / heading is selected.

### ProseMirror version

"prosemirror-view": "1.2.0"

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Closing as out of scope—the project assumes a single focusable editor, and I'm not even sure how a different approach would work.
