### ISSUE TITLE
Restoring document from JSON fails with "out of range" error

### ISSUE THREAD

**Issue by lessless** [ProseMirror/prosemirror#779]
### Issue details

Restoring document from JSON fails with `RangeError: Position 0 out of range`
https://github.com/ProseMirror/prosemirror-model/blob/master/src/resolvedpos.js#L220

### Steps to reproduce
1. Use example setup from the http://prosemirror.net/examples/basic/
2. Load JSON document

```
const json = JSON.parse("{\"doc\":{\"type\":\"doc\",\"content\":[{\"type\":\"paragraph\",\"content\":[{\"type\":\"text\",\"text\":\"text\"}]}]},\"selection\":{\"type\":\"text\",\"anchor\":5,\"head\":5}}");
window.view = new EditorView(document.querySelector("#editor"), {
  state: EditorState.create({
    doc: Node.fromJSON(mySchema, json.doc),
    plugins: exampleSetup({schema: mySchema})
  })
})

```
I couldn't reproduce it on glitch.com - maybe the version is not current? 

Here is a good, old github repo https://github.com/lessless/pm-json-import-bug

- clone
- run `npm install`
- open index.html
- type anything in the editor

### ProseMirror version

```
"prosemirror-commands": "^1.0.5",
"prosemirror-history": "^1.0.1",
"prosemirror-keymap": "^1.0.1",
"prosemirror-model": "^1.4.0",
"prosemirror-schema-list": "^1.0.1",
"prosemirror-state": "^1.1.1",
"prosemirror-transform": "^1.0.7",
"prosemirror-view": "^1.2.0",
"prosemirror-schema-basic": "1.0.0",
"prosemirror-example-setup": "1.0.1"
```

### Affected platforms

- [x] Chrome
- [x] Firefox

**Comment by marijnh** [comment]
I can't reproduce the problem. Do you have a stack trace (with non-minified names)?

**Comment by lessless** [comment]
It went away yesterday. After another cycle of playing with prosemirror package versions in order to find when exactly this issue was brought to life it just stopped to reproduce.
I thought that it was fixed in prosemirror, frankly.

**Comment by kurtharriger** [comment]
I encountered this issue again after updating from prosemirror-model@1.1.0 to prosemirror-model@1.2.0.
I noticed that the node.size appears to be NaN thus resulting in the following
<img width="1209" alt="screen shot 2018-04-09 at 2 27 08 pm" src="https://user-images.githubusercontent.com/112603/38536741-25d7683c-3cce-11e8-92c5-fc4c751e4907.png">

**Comment by kurtharriger** [comment]
I did just try that example and did not encounter the issue. I'll need to do a bit more work to figure out how to create a minimal test project that reproduces the issue, but here is me playing with the debugger  http://g.recordit.co/LhsNe0VtLJ.gif and my yarn.lock file 
https://gist.github.com/kurtharriger/92369c937c1b1bb55344a828abcb821d

**Comment by marijnh** [comment]
> I encountered this issue again after updating from prosemirror-model@1.1.0 to prosemirror-model@1.2.0.

The JSON deserialized started doing more sanity checking, so it's possible that the issue existed before but went unnoticed

**Comment by marijnh** [comment]
Yeah, this has come up before. Both Yarn and NPM are prone to leaving duplicates of packages around even when that isn't necessary. Removing node_modules and reinstalling usually fixes it.

**Comment by howardjing** [comment]
I ran into this issue using yarn. Removing node_modules did not fix the problem because the yarn.lock file ensures that the projects transitive dependencies remain the same even after wiping out node_modules (which is good!). 

Installing the update twice appears to fix the issue. So for example:

```
yarn upgrade prosemirror-state@^1.2.2 prosemirror-view@^1.6.8 prosemirror-model@^1.6.4
yarn upgrade prosemirror-state@^1.2.2 prosemirror-view@^1.6.8 prosemirror-model@^1.6.4
```

In other words running

```
yarn upgrade prosemirror-state@^1.2.2 prosemirror-view@^1.6.8 prosemirror-model@^1.6.4
```

brings about the RangeError: Position 0 out of range bug, and then running the same command again appears to rejigger things and fix things.

**Comment by davewasmer** [comment]
Ran into this myself as well. Unfortunately, it's not an extraneous copy lying around for me: in my case, I'm using `yarn link` to work on a library and a consuming app at the same time.

This results in tools like webpack loading both copies of prosemirror-model, leading to the instanceof check failing.

I realize this is not a bug with prosemirror-model, but @marijnh would you be open to a PR that attempts to swap out the instanceof check with some other kind of check that doesn't rely on module identity? Obviously shipping two copies of prosemirror-model in a production build should be avoided, but it seems like my library development scenario isn't easily supported given the current instanceof checks.

**Comment by marijnh** [comment]
I don't really want to try and support the situation where multiple versions of the packages are used together (there'll probably be other subtle issues), and as such I kind of consider this bug to be a useful early warning that a given install is corrupted.

**Comment by davewasmer** [comment]
Fair enough. Would you be open to a PR that improves the error message in this specific scenario? It took a fair amount of stepping through the Prosemirror source to realize the "out of range" error was due to the fact that there were multiple copies of Prosemirror. Something like:

```js
assert(fragmentInstance.constructor === Fragment, 'It looks like you may have multiple copies of Prosemirror that are conflicting with each other. Multiple copies of Prosemirror in a bundle are not supported. Try checking your node_modules to see if duplicate copies exist.')
```

might help ~my future forgetful self~ others save that time.

**Comment by marijnh** [comment]
> Would you be open to a PR that improves the error message in this specific scenario?

Yes, that'd be a very good idea.

**Comment by mike-seekwell** [comment]
if you're getting this error from tiptap, check here for a workaround https://github.com/scrumpy/tiptap/issues/577
