### ISSUE TITLE
Node marks get removed when it's content is edited

### ISSUE THREAD

**Issue by Gozala** [ProseMirror/prosemirror#780]
### Issue details

It seems that node marks get cleared and moved over to node content on any editing of it's content.  I created an example to illustrate this issue https://glitch.com/edit/#!/join/010002a1-fde3-46c9-a4d8-efabbb1de9d3. That is problematic for my markdown editor use case because if original source was typed as`__[link](#link)__` and user changed label to say `link2` it would end up serialized as `[__link2__](#link)` instead.

### Steps to reproduce

Below the editor I display serialized doc of the state. Initially link has a following structure `strong(link(...` but as soon as you type any character it switches to `link(...strong( ` instead. 

### ProseMirror version

```
     "prosemirror-model": "1.4.0",
    "prosemirror-schema-basic": "1.0.0",
    "prosemirror-schema-list": "1.0.1",
    "prosemirror-state": "1.1.1",
    "prosemirror-view": "1.2.0"
```

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [x] Electron

**Comment by johanneswilm** [comment]
I believe this may be the same issue or a closely related one: https://glitch.com/edit/#!/handsome-python

**Comment by marijnh** [comment]
Sorry for the terrible response time, but yes, ProseMirror normalizes mark order (as determined by the order in which the marks appear in the schema definition) to avoid unnecessary ambiguity in how a given document should be represented. That's part of the design and not going to change anymore.
