### ISSUE TITLE
Cursor jumps in certain scenarios

### ISSUE THREAD

**Issue by Gozala** [ProseMirror/prosemirror#781]
### Issue details

I suspect this might be somewhat related to the #780 as it only occurs if inline node has a mark like in the following example https://glitch.com/edit/#!/colossal-prince issue only occurs when doc has `strong(link(...` and doesn't if it has `link(strong(...`.  

### Steps to reproduce

If have cursor in `pos:6` and type any character cursor will stay on `pos:6` rather than move to `pos:7` as one would expect. If instead you press arrow right and any character character will appear where expected but cursor jumps to `pos:53`. Inputting character in `pos:12` has same issue.

### ProseMirror version

```
"prosemirror-model": "1.4.0",
"prosemirror-schema-basic": "1.0.0",
"prosemirror-schema-list": "1.0.1",
"prosemirror-state": "1.1.1",
"prosemirror-view": "1.2.0"
```

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [x] Electron

**Comment by marijnh** [comment]
This appears to have been fixed in the meantime.

(Not sure why I missed a whole series of your issues here, @Gozala. I tend to not look much at issue lists and use email notifications to manage my work list, but that seems to have gone entirely wrong here.)
