### ISSUE TITLE
Pasting a Slice across a node that has content NodeSpec like 'column{2, 3}' , can create an invalid document

### ISSUE THREAD

**Issue by 5id** [ProseMirror/prosemirror#782]
### Issue details

With a schema that defines a constraint like:
```
const doc = { content: '(block|row)+' }

const row = {
  content: 'column{2,3}',
};

const column = {
  content: 'block+',
  isolating: true,
};
```

It's possible to copy a slice that just includes one column - which then on paste will create a node like `doc(row(column()))` instead of `doc(row(column(), column()))` as per the minimum in the schema constraints.

I'd have expected it to pad the row it created with enough columns to make it a valid element.

### Steps to reproduce

Using https://sugar-gallon.glitch.me/ (code is at glitch.com/edit/#!/sugar-gallon)

1. Make a selection from the first column, to the line below
2. Copy this selection
3. Click at the end of the document
4. Paste
5. Notice there's only one column pasted, but this violates the schema

### ProseMirror version

Latest 

### Screenshots / Screencast (Optional)

![paste-of-column-is-single](https://user-images.githubusercontent.com/3411140/38283293-8a77b902-37f8-11e8-9a2a-e2a46dd136c7.gif)

**Comment by marijnh** [comment]
That was a bug in the logic that generated the replace step. Patch https://github.com/ProseMirror/prosemirror-transform/commit/8b77e462663bc5a713baee63759c8547015331b4 should fix it.

(Tangentially, you may want to set `isolating` on your column nodes to make copy-pasting them as a whole easier and disable some editing actions across their boundaries.)
