### ISSUE TITLE
Uncaught Range Error on Arrow-Down after backspace

### ISSUE THREAD

**Issue by 5id** [ProseMirror/prosemirror#783]
### Issue details

Found an issue where delete and then arrowing-down causes a RangeError to be thrown

### Steps to reproduce

Still using https://sugar-gallon.glitch.me/  (code is at glitch.com/edit/#!/sugar-gallon)

1. Remove all the content on the first line
2. Delete Forwards
3. Arrow-down
4. Notice the Range Error that gets thrown

### ProseMirror version

Latest

### Affected platforms

Chrome / Firefox

### Screenshots / Screencast (Optional)

![delete-then-downarrow](https://user-images.githubusercontent.com/3411140/38284016-94ddd832-37fc-11e8-9026-6d5deb036652.gif)

**Comment by marijnh** [comment]
Attached patch should help.
