### ISSUE TITLE
Copy and paste problems

### ISSUE THREAD

**Issue by xgzl87** [ProseMirror/prosemirror#788]
prosemirror-view v1.0.0
![default](https://user-images.githubusercontent.com/12945325/38724909-2f72b060-3f38-11e8-83b9-6f9731fe3b99.png)
paste img img attrs id class opinionId disappear
![default](https://user-images.githubusercontent.com/12945325/38725890-4100a7bc-3f3b-11e8-8881-a60663bcf5c1.png)

![default](https://user-images.githubusercontent.com/12945325/38725766-f3b36f26-3f3a-11e8-89b5-29811ff0bc63.png)

**Comment by marijnh** [comment]
Upgrading to 1.1.1 or later should fix this.

**Comment by xgzl87** [comment]
"prosemirror-state": "^1.2.0"
Adding different instances of a keyed plugin (plugin$)
![default](https://user-images.githubusercontent.com/12945325/38797057-eda6e3d6-418f-11e8-9829-497df1b867d7.png)
