### ISSUE TITLE
setBlockType removes marks

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#789]
### Issue details

Using tr.setBlockType removes any attributes and marks that have been on the block. Attributes could be  important for example if an editor has added unique IDs to headings so that these can be referenced from internal links. No need to break the internal link when the headline changes from an H2 to an H3. Marks should not be affected by changing the blocktype, as the same marks should be allowed on the new type under all circumstances.

### ProseMirror version

prosemirror-transform 1.0.9

### Affected platforms

- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Other

**Comment by marijnh** [comment]
Attached patch (released as 1.0.10) should solve this.

**Comment by geminys** [comment]
Hello, my apologies for resurrecting this old issue, but as far as I understand, with this fix the marks are indeed preserved, but all custom attributes are still lost, for example custom ids. This is causing our custom paragraph IDs to be replaced by new IDs, and this causes big problems not only with broken links, but also with our translation system. If you could possibly look for a way to fix this, it would be great.

**Comment by marijnh** [comment]
> but all custom attributes are still lost, for example custom ids

Yes, you're providing a full set of new attributes. Fill in the old ones in the object you pass to `setBlockType` if you want to preserve them.

**Comment by geminys** [comment]
Yes, but that attribute set that is passed are the common attributes, for example the list type or the title level. You need to take into account that this method can be called when selecting a range of paragraphs, and each paragraph has a unique ID. We can't set those custom attributes when calling the method from our code, it needs to be done internally when processing each node in the loop of the "setBlockType" function.

**Comment by marijnh** [comment]
I see what you mean. Attached patch adds support for passing a function there that computes the attributes from the existing node.
