### ISSUE TITLE
Copy and paste problems

### ISSUE THREAD

**Issue by xgzl87** [ProseMirror/prosemirror#790]
paste img img attrs id class opinionId disappear
![default](https://user-images.githubusercontent.com/12945325/38800760-ab64d400-419a-11e8-8cc5-ef2cb8934e1f.png)
![default](https://user-images.githubusercontent.com/12945325/38800882-f75aabfa-419a-11e8-9328-974a0e871fdf.png)
![default](https://user-images.githubusercontent.com/12945325/38800891-fe8666c6-419a-11e8-98ff-b032c23807f6.png)

img attrs id class opinionId still have not

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Other

**Comment by marijnh** [comment]
Does the DOM node still have the attribute when you `console.log` it from `getAttrs`?

**Comment by xgzl87** [comment]
console.log not run.....

**Comment by xgzl87** [comment]
![default](https://user-images.githubusercontent.com/12945325/38852365-2bf973ee-424c-11e8-9677-e4938d2a3e0d.png)
Strange this console.log is working...

**Comment by xgzl87** [comment]
solved  thanks
![default](https://user-images.githubusercontent.com/12945325/38854937-a90c87d8-4254-11e8-92fb-2ca750e71dd4.png)
