### ISSUE TITLE
liftListItem should avoid lifting items out from same level into new list

### ISSUE THREAD

**Issue by ahixon** [ProseMirror/prosemirror#793]
### Issue details

Currently, lifting a list item and any children works correctly, but any nodes at the same level get lifted out into **another list**. 

This causes multiple, side-by-side list nodes to be created from a single list. This either:

* in the case of bullet lists, is almost invisible to the user, but litters the document with multiple unorderedList nodes
* in the case of numbered lists, restarts numbering when the user probably didn't intend it to

### Steps to reproduce

https://kaput-find.glitch.me/ - glitch.com/edit/#!/kaput-find

Click on the first level list item, and click the "lift list item" button.

The child list item lifts correctly, but one would expect the following node (previous sibling) to be in the same list, not a new one.

### ProseMirror version

`prosemirror-schema-list` 1.0.1

**Comment by marijnh** [comment]
Appears to have been fixed in the meantime. Sorry about the glacially slow response.
