### ISSUE TITLE
Use Object.freeze on all immutable state objects

### ISSUE THREAD

**Issue by mitar** [ProseMirror/prosemirror#795]
This is a feature request. To my understanding, all state objects (state, doc) are immutable. I think it would be great to then call [Object.freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) on them. This will make interoperability with some other libraries better. For example, in Vue, I can then pass ProseMirror state through its reactivity system and it will know to not add its proxy methods because it is frozen. I also think it might help with debugging to prevent people accidentally modifying the state. I think I could always do it myself, but having it done inside ProseMirror would make it easier to not do something wrong by mistake. I do not understand all the details of which objects are most suitable for something like this.

**Comment by marijnh** [comment]
As it stands, freezing objects causes too much of a performance impact to do it in the library itself. So if you really need this, you'll have to do it on your side.

**Comment by mitar** [comment]
I do not think there are differences in performance anymore: https://stackoverflow.com/questions/8435080/any-performance-benefit-to-locking-down-javascript-objects

**Comment by marijnh** [comment]
That just tests access speed, not the cost of changing the object shape.

**Comment by mitar** [comment]
Hm, by reading around it seems you are right.

Anyway, do I understand correctly: editor view is mutable. State is immutable. Every time it changes, it is assigned to view's `state` property?

So I could do something like this and this would not break things?

```js
dispatchTransaction: (transaction) => {
  const newState = editorView.state.apply(transaction);
  editorView.updateState(newState);
  Object.freeze(editorView.state);
}
```

Or maybe even:

```js
dispatchTransaction: (transaction) => {
  const newState = editorView.state.apply(transaction);
  Object.freeze(newState);
  editorView.updateState(newState);
}
```

Is there anything else which is immutable?

**Comment by marijnh** [comment]
> Anyway, do I understand correctly: editor view is mutable. State is immutable. Every time it changes, it is assigned to view's state property?

Right. And freezing such objects (states, nodes, selections, etc) is safe. You could even recursively freeze the objects in their properties.
