### ISSUE TITLE
Dragging and Dropping a listItem breaks other nodes in two

### ISSUE THREAD

**Issue by patsimm** [ProseMirror/prosemirror#798]
### Issue details

When dragging and dropping a ListItem onto a node that is not a child of the list the listItem is currently part of, the node dropped onto will be split at the position of the cursor.

### Steps to reproduce

- Check out https://github.com/ProseMirror/prosemirror
- Insert `draggable: true` in the listItem schema (Don't actually know if this has to be done to reproduce the issue)
- Start the Demo Server
- Drag and Drop ListItems

### ProseMirror version

The current version on https://github.com/ProseMirror/prosemirror master

### Affected platforms

- [x] Chrome
- [x] Firefox
- [?] Internet Explorer
- [?] Other

### Screenshots / Screencast (Optional)

![drag-drop-lists](https://user-images.githubusercontent.com/5880346/40228742-664666d4-5a92-11e8-9448-098354b392d1.gif)

**Comment by marijnh** [comment]
What did you expect to happen?

**Comment by patsimm** [comment]
I'd expect the dragged node to be inserted in between two nodes instead of splitting nodes. I think my issue is very similar to: https://github.com/ProseMirror/prosemirror/issues/188.

**Comment by marijnh** [comment]
Ah, I see what you mean. The editor _will_ look for a valid parent node to drop the content in, but in the case of `list_item` nodes dropped outside of a list, none is found so it is inserted directly at the mouse cursor.

It would be possible to add logic to allow wrapping the content, if that helps placing it, but I'm not sure that's always appropriate. I'll think about it some more.

**Comment by neknalb** [comment]
Yes, in this case the dragged node (a `list_item`) cannot be inserted as is - since a `list_item` node may only exist as a child of a `list` node. It needs to be auto-wrapped into a newly created `list` node.

That's what already seems to work. But I'd expect the new list to be placed before or after the node where the `list_item` is dropped. It may not split another block.

**Comment by patsimm** [comment]
Any new thoughts on this?

**Comment by marijnh** [comment]
Yeah, I think it is the right solution to make `dropPos` more intelligent about this. See attached patch. I'm following up with [this RFC](https://github.com/ProseMirror/rfcs/pull/8) to export `dropPos` so that 3rd party code can use the main implementation.
