### ISSUE TITLE
Decorations on edges are not deleted 

### ISSUE THREAD

**Issue by alidcastano** [ProseMirror/prosemirror#799]
### Issue details

In the collab example, if you add a comment that includes the first letter of a line, the comment isn't deleted when the text is deleted.

This seems more like a bug with decorations/mapping, than in the example itself, since the issue happens in chrome but not in firefox.

### Affected platforms

- [ x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by alidcastano** [comment]
Any word on whether this is a confirmed bug?

**Comment by marijnh** [comment]
It appears to be inserting a hard break, which then gets the decoration. Chrome apparently thinks it is a good idea to create a `<br>` node when you backspace out the last character between the start of the line and a widget, which ProseMirror then read as an actual document node. Attached patch should help.

**Comment by RichieAHB** [comment]
@marijnh should that not be `tagName` rather than `nodeType`?

**Comment by marijnh** [comment]
Oh, yes, it should... I am pretty sure I tested this and saw a difference, but I may have messed something up. I've updated the patch in #831
