### ISSUE TITLE
Suggested way to save the content

### ISSUE THREAD

**Issue by davideicardi** [ProseMirror/prosemirror#8]
What is you suggested way to save content generated by ProseMirror?
I mean do you think it is better to store HTML? Markdown? Or maybe some internal data model?
Maybe some kind of [delta](http://quilljs.com/docs/deltas/)?

The fact that you internally work with an abstraction data model seems very interesting and so I think that maybe using it also for storage can have some advantages.
I think this is also related in someway to [collaborative editing](http://marijnhaverbeke.nl/blog/collaborative-editing.html) right?

P.S. Congratulations for you work, I hope you manage to get the funds....

**Comment by marijnh** [comment]
This depends on your use case. If you're using it as an alternative view on an HTML or Markdown editor, you'll want to save as HTML or Markdown. If ProseMirror is the only editor in your system, you could also save the JSON representation of ProseMirror's document model, for easy inspecting and modification support. All should work, and, barring bugs in serializers and parsers, should not lose information.

**Comment by davideicardi** [comment]
Yes, my idea is to have ProseMirror as a single editor, and then output the final result on HTML only on the "front end" side. Eventually having an abstraction can also be useful to output a slight different HTML (for example one for desktop and one for mobile and so on...).

Thanks for you info!
