### ISSUE TITLE
Mixing content with EJS

### ISSUE THREAD

**Issue by mercmobily** [ProseMirror/prosemirror#801]
In my app, I need to make it possible for users to be able to write EJS-based templates. Asking them to write HTML is a little too much.

The original idea was to allow them to write their templates using either contenteditable OR markdown, and mix contents. The problems are obvious:

* `contenteditable` will _always_ add `<div>` to each line, even in the EJS section of the site, hence ruining it
* `Markdown` has the same problem

Could prosemirror fix the issue for me? Would it be trivial enough to generate a result that would leave anything within <% and and %> untouched? (Note: Consider that the templates potentially include tables too.)

**Comment by marijnh** [comment]
You can probably build the editor you want with ProseMirror, but it's not trivial—you'll have to somehow encode the thing you want as a ProseMirror schema, code up the user interface, and extend the markdown parser to handle EJS blocks the right way.
