### ISSUE TITLE
Extra BR tags are rendered when copy-pasting from Google Doc

### ISSUE THREAD

**Issue by kevinzang** [ProseMirror/prosemirror#802]
### Issue details

Extra BR tags are rendered when copy-pasting from Google Doc.

### Steps to reproduce

Create a Google Doc with "Test\nTest". Example: https://docs.google.com/document/d/10tmzqPy2iq9oiszt-iQ7Vcl6ZMatf9lne-12UjWVUpM/edit.

Copy-paste the contents into the editor at http://prosemirror.net/.

The rendered HTML has extra BR tags, making it look like the copy-pasted text has more newlines than the original text:

<img width="300" alt="screen shot 2018-05-22 at 10 20 34 pm" src="https://user-images.githubusercontent.com/6496295/40404802-8b21988c-5e0e-11e8-974c-863409edca94.png">

The copy-pasted HTML looks like this:

```
<meta charset='utf-8'>
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1dc97aa6-8b6f-18e9-55b9-8cfe071a49b2">
<p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Test</span></p>
<br />
<p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Test</span></p></b>
<br class="Apple-interchange-newline">
```

As far as I understand, `<br />` tags are automatically wrapped in `<p>` tags if not already in `<p>`, so in ProseMirror doc they look like `<p><br></p>`, however the EditorView [inserts another `<br />`](https://github.com/ProseMirror/prosemirror-view/blob/1.3.0/src/viewdesc.js#L1018) to work around limitations with `contenteditable`, so rendered HTML is `<p><br><br></p>`.

Is it possible to only apply "BRHackViewDesc" if the node does not already end with a `<br />`?

### ProseMirror version

Same as the sample editor at http://prosemirror.net/

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

None

**Comment by marijnh** [comment]
> Is it possible to only apply "BRHackViewDesc" if the node does not already end with a <br />?

No, that would be the wrong solution—if a textblock ends with a break, that should be visible. The issue, if we take the ridiculous HTML produced by Google Docs as a given, would be in the parsing—these extra stray `<br>` tags should be ignored and not added to the document.

One possibly good approach would be to treat `<br>` tags outside of textblock nodes the way we [currently](https://github.com/ProseMirror/prosemirror-model/blob/master/src/from_dom.js#L380) treat whitespace text—ignore it on the assumption that it's not part of the actual content. I'd be interested in a pull request that does that.

**Comment by kevinzang** [comment]
> these extra stray `<br>` tags should be ignored and not added to the document.

It's not extra though. The `<br>` represents the newline.

```
Test // <p>test</p>
        // <br>
Test // <p>test</p>
```

If Google Docs had used `<p></p>` instead of `<br>`, everything would work. But since it uses `<br>`, wouldn't we need some way to parse `<br>` outside textblock as `<p></p>` rather than ignoring them completely?

**Comment by marijnh** [comment]
You described the doc as containing `Test\nTest`, which does not have any empty lines. Did you mean `Test\n\nTest`, or do you think the margins between paragraphs should be represented with separate nodes?

**Comment by kevinzang** [comment]
Sorry for not being clear. You're right, I meant "Test\n\nTest". The exact sequence I typed into Google Docs was

Type "Test"
Hit "Enter"
Hit "Enter"
Type "Test"

I would expect this text, when copy-pasted, to generate the following doc:

```
<p>Test</p>
<p></p>
<p>Test</p>
```

as that's what I get if I type the same sequence in the ProseMirror editor. However, the rendered HTML looks as if I had typed the following:

Type "Test"
Hit "Enter"
Hit "Shift+Enter" (for `<br>`)
Hit "Enter"
Type "Test"

I do not expect the margins between paragraphs to be represented with separate nodes. Even if the paragraphs are styled with `margin: 0`, there's still more space between the two "Test" lines due to the extra `<br>` injected by the EditorView.

**Comment by marijnh** [comment]
Okay, that makes more sense—they are using `<br>` to encode an empty paragraph. You could try adding a [parse rule](http://prosemirror.net/docs/ref/#model.ParseRule) that says that such a tag at the top of the document is to be parsed as a paragraph (something like `{tag: "br", context: "doc/", node: "paragraph"}`)

**Comment by kevinzang** [comment]
Ah, that does resolve my issue! Thank you very much! I have one last question: I am using `DOMParser.fromSchema` to create my parser, and my parse rules are defined in my schema like so:

```
nodes: {
    hard_break: {
        inline: true,
        group: 'inline',
        selectable: false,
        parseDOM: [
            { tag: 'br', context: 'doc/', node: 'paragraph' },
            { tag: 'br' },
        ],
        toDOM() {
            return ['br'];
        },
    },
}
```

but it seems that `node` option is overridden by schema's node name via this line: https://github.com/ProseMirror/prosemirror-model/blob/1.4.4/src/from_dom.js#L240. So, it's overriding my `node: 'paragraph'` option with `node: 'hard_break'`.

I have verified the parse rule works by hacking that line to be `rule.node = rule.node || name`, but I am wondering what is the intended way to add this parse rule?

**Comment by marijnh** [comment]
Right, if you store rules on node specs you need to put them on the node that they produce (so `paragraph` in this case). The alternative is to manually create a DOMParser and pass the full rules.

**Comment by kevinzang** [comment]
Ah, defining in `paragraph` worked! I consider my issue resolved- thanks again for the help!
