### ISSUE TITLE
WidgetViewDesc without selectNode method.

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#805]
### Issue details

User clicks on a leaf node that has a decoration widget in front of it.  In function `syncNodeSelection(view, sel)` an error is thrown on the line `if (desc) desc.selectNode()`. `desc` is an instance of `WidgetViewDesc` which doesn't seem to have a `selectNode()` method.

### Steps to reproduce

I figure this may  possibly be a simple issue in that either WidgetViewDesc needs a selectNode method, or WidgetViewDesc should never show up in syncNodeSelection. Let me know if it is more complex than that, in which case I'll try to make a minimal example.

### ProseMirror version

latest versions of all main packages (prosemirror-model 1.5.0)

### Affected platforms

- [X] Chrome
- [X] Firefox
- [X] Internet Explorer
- [X] Other

**Comment by marijnh** [comment]
That `desc` value comes from `ViewDesc.descAt`, which should never return a desc for a zero-length element. Can you create a minimal example that can help me reproduce the problem? I can't reproduce it from your description.
