### ISSUE TITLE
On IE11, arrow left and delete get stuck at links

### ISSUE THREAD

**Issue by kevinzang** [ProseMirror/prosemirror#807]
### Issue details

On IE11, arrow left and delete get stuck at links.

### Steps to reproduce

Go to prosemirror.net.
The editor already has a sample text `Try it out by typing in here or see more examples.`. Place the cursor at the end of this line. Try to use arrow left key to move the cursor before the word `examples`. The arrow key gets stuck. Also, delete key doesn't work when the cursor is right after the `s` in `examples`, but interestingly if you move the cursor back to the end of the line, and hold delete, it does work.

I was not able to reproduce the issue on a `contenteditable` without ProseMirror, e.g.

```
<div contenteditable="true">
    <a href="http://asdf.com">asdf</a> asdf</a>
</div>
```

so I thought maybe this is a ProseMirror bug rather than an IE11 bug.

### ProseMirror version

The version used by prosemirror.net.

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer (I tried Windows 8.1 IE11 and Windows 10 IE11 via browserstack.com)
- [ ] Other

**Comment by marijnh** [comment]
Attached patch should take care of this (IE wasn't, for some reason, moving the cursor when it was directly in front of a zero-width space, which ProseMirror uses in its hack to make text typed after a link not be part of the link).

**Comment by kevinzang** [comment]
Thank you! I confirm the patch works.
