### ISSUE TITLE
prosemirror-history: using private prosemirror-transform APIs

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#808]
### Issue details

Using private `mirror` argument in `Mapping` constructor:

prosemirror-history: https://github.com/ProseMirror/prosemirror-history/blob/59afa9e4780f92e26d6c435861af5200492e9e25/src/history.js#L124
prosemirror-transform: https://github.com/ProseMirror/prosemirror-transform/blob/5335a43140c2b48fffef1becc34a4041741ecfde/src/map.js#L151

Using private `Mapping#getMirror` API:

prosemirror-history: https://github.com/ProseMirror/prosemirror-history/blob/59afa9e4780f92e26d6c435861af5200492e9e25/src/history.js#L149
prosemirror-transform:  https://github.com/ProseMirror/prosemirror-transform/blob/5335a43140c2b48fffef1becc34a4041741ecfde/src/map.js#L177

Package versions at the time of writing:

- `prosemirror-history` (1.0.2)
- `prosemirror-transform` (1.0.10)

**Comment by marijnh** [comment]
`collab` also needs them. I guess we should just make them public.

**Comment by marijnh** [comment]
I avoided using the constructor argument, and documented `getMirror`, in attached patches.
