### ISSUE TITLE
spaces and dom importer

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#81]
The DOM importer doesn't like empty text nodes and it throws the error "Text node content must be a non-empty string". That's OK. One can avoid the error by normalizing the node before import.

More difficult to understand is why it doesn't like a combination of spaces inside and outside of an inline style. For example the below produces the same error message:

```
<p><b>1 </b> </p>
``` 

Is this on purpose? If so, what's the recommended way of cleaning nodes so that they comply with the requirements of prosemirror's importer?

**Comment by marijnh** [comment]
It shouldn't be raising that error -- that's a bug, I'll look into it soon.

**Comment by johanneswilm** [comment]
cool!

This is another case:

```
<p> <b>&#09;</b></p>
```
