### ISSUE TITLE
TextNode's toString method leaks Personally Identifiable Information (PII)

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#810]
### Issue details

TextNode's `toString` method serializes text content of a node when error is thrown. Which leads to unwanted leakage of PII if we are using products like Sentry, etc..., that intercept errors globally. We really want to prevent that from happening.

Ideally we would be able to override `toString` method on a node so that we can control it's representation in an error message. 

Just want to get your opinion on – does it make sense to add toString to the NodeSpec and then use it in a node if defined? If you think it's reasonable I can put up a PR with this change :)

**Comment by d4rkr00t** [comment]
For example Fragment does that: https://github.com/ProseMirror/prosemirror-model/blob/3b3671609bb222dcfae4dc3fe0bcebd94b3ca15a/src/fragment.js#L201

And the error we get:
```
Position -2 outside of fragment (<mediaGroup(media), paragraph("that’s three branches:", hardBreak, hardBreak, "CA remote - release/3.2", hardBreak, "origin remote - CA/release/3.2", hardBreak, "local - CA/release/3.2")>)
```

**Comment by marijnh** [comment]
Ah, right, so it goes for any node, not just text nodes. Checking for `this.type.spec.toString` and calling that (passing the node as argument) if present does sound reasonable. A pull request would be great.

**Comment by d4rkr00t** [comment]
Awesome, thanks, I'll start working on a PR.

**Comment by marijnh** [comment]
Closed via https://github.com/ProseMirror/prosemirror-model/pull/26
