### ISSUE TITLE
domAtPos gives incorrect offset when there's a preceding widget decoration node

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#812]
### Issue details

My DOM structure looks like this:
```
[doc]
  [widget decoration][codeblock][paragraph]
[/doc]
```
`view.state.doc.nodeAt(0)` - gives me codeBlock PM node, which is expected.

`view.domAtPos(0)` gives me `dom = {node: <div>, offset: 0}`, so that `dom.node.childNodes[dom.offset]` returns a decoration node. I expected to get `codeblock` DOM reference at position `0`.

Presumably the problem is in here: https://github.com/ProseMirror/prosemirror-view/blob/286ecfe40f0e15304b30eb2f2b4c94cf6e87432f/src/viewdesc.js#L255
where `i` should be greater than `0`.

- [x ] Chrome

**Comment by marijnh** [comment]
If the widget has a [`side`](http://prosemirror.net/docs/ref/#view.Decoration^widget^spec.side) option >= 0, or not given, this is the correct behavior—`domAtPos` uses the same logic as the cursor placement, so it will end up after widgets with a negative `side`, and before other widgets.

**Comment by eshvedai** [comment]
Got it, that's exactly what I need, thanks a lot!
