### ISSUE TITLE
keydownHandler does not function as described in docs

### ISSUE THREAD

**Issue by isTravis** [ProseMirror/prosemirror#813]
### Issue details

[keydownHandler](http://prosemirror.net/docs/ref/#keymap.keydownHandler) seems to not pass the function variables described in the documentation. 

Looking at [the source](https://github.com/ProseMirror/prosemirror-keymap/blob/master/src/keymap.js#L85), it seems that the function is passed `(view.state, view.dispatch, view)` rather than `(view: EditorView, event: dom.Event)`.

### Steps to reproduce

When creating an `EditorView` with the following the function the `evt` value is not a dom.Event:

```
new EditorView(this.editorElement, {
	state: this.state,
	handleKeyDown: keydownHandler({
		'Mod-s': (view, evt)=>{
			console.log(evt);
		},
	})
});
```

### ProseMirror version

prosemirror-keymap: 1.0.1

### Affected platforms
- [x ] Chrome
- [x ] Firefox
- [x ] Internet Explorer
- [x ] Other

**Comment by marijnh** [comment]
You're reading the docs wrong. `keydownHandler` returns a function with those arguments, which can then be used as a `handleKeyDown` prop in a plugin, but the commands you bind keys to will be called as commands, and passed the arguments you observed.

**Comment by isTravis** [comment]
Oooh - got it - I see now. Thank you for the very prompt response.
