### ISSUE TITLE
Copying an empty bullet list into the editor breaks it

### ISSUE THREAD

**Issue by vijaysutrave** [ProseMirror/prosemirror#814]
### Issue details

Copying an empty bullet-list (or ordered list) from the Mac Notes App (or any other app), to the Editor breaks the schema, and hence the editor.  The bullet list item on the editor becomes un-clickable since it does not contain a paragraph. 

### Reason
I tried to debug to see what's going on, my findings say that when the content from the clipboard is parsed, we might need to check if the pasted content conforms to the schema. In this case, a bullet-list  without any text context or a leaf inline node was allowed to created.

### Steps to reproduce
- On the notes app, enter a bullet point
- Leave the bullet point empty by navigation with arrow keys
- Add some text in the new line below (with the empty bullet point on the top)
- Copy all (Cmd + A)
- Paste into the Editor

### ProseMirror version
Latest

### Affected platforms

All

### Screenshots / Screencast 
![bullet-2](https://user-images.githubusercontent.com/6284969/42035739-04aa5b64-7b27-11e8-82e1-24c25e1e967b.gif)

**Comment by marijnh** [comment]
The document parser should make sure the schema is followed. I don't have access to Notes App. Could you find out which HTML, exactly, is being copied (possibly by adding a console.log to ProseMirror's paste handler)?

**Comment by marijnh** [comment]
The bug wasn't in the parser, but in another part of the system. Attached patch fixes this.
