### ISSUE TITLE
Is there any callback function on view update?

### ISSUE THREAD

**Issue by musaffa** [ProseMirror/prosemirror#818]
I want to hook into a callback function when the editor view changes. There's a callback function named `dispatchTransaction` when a new transaction is created. But this function is invoked even if I just move the cursor. I would rather want to hook into a callback function when there's a true change in the document.

Edit: We can write a plugin that can hook into [view update](http://prosemirror.net/docs/ref/#state.PluginSpec.view^returns.update). But this is still called when I just move the cursor. Is there any way to check whether the view has changed?

**Comment by rsaccon** [comment]
You can check at each Transaction for the `docChanged` flag.
https://prosemirror.net/docs/ref/#transform.Transform.docChanged

**Comment by musaffa** [comment]
Oh Transaction is a subclass of Transform. So docChanged flag is inherited.

This has solved my issue. Thanks.
