### ISSUE TITLE
[prosemirror-history] appendTransaction to undo

### ISSUE THREAD

**Issue by RichieAHB** [ProseMirror/prosemirror#819]
### Issue details

If I want to append a transaction to an `undo` command I think the `HistoryState` should probably be keeping the `undone` that was created by the  `undo` command. However, this line seems to be ignoring the fact that the previous transaction could (and in this case, does) have been an `undo`, which means a `redo` is then impossible. https://github.com/ProseMirror/prosemirror-history/blob/22f773640ce79c91f328d14ef20de8361b2fb7f0/src/history.js#L270

I can't flag it with an `addToHistory` set to `false` as I do want the edits appended in the transaction to be added to the history. Either way, the first undo doesn't actually get rid of the extra information added in the `appendTransaction` call.

### Steps to reproduce
[Repro](https://glitch.com/edit/#!/whispering-celsius?path=index.js:1:0) - just do anything, undo it, then redo it. As mentioned above, `redo` won't work, ~~and before this the `undo` won't actually remove the appended information (the º symbol)~~.

Edit: it just appends another one after this history transaction 🙄 

I may be missing something obvious here but I can't see it in the docs.

**Comment by RichieAHB** [comment]
Maybe a naïve solution for this would be adding a `rootTransaction` meta key, that held the first transaction to kick off the plugins, on all transactions that were appended. The history plugin can then reflect on this and keep the `redone` history as appropriate?

I've actually hacked on this and it fixes my issue and doesn't break any `prosemirror-history` tests but it does change the API ...

**Comment by RichieAHB** [comment]
Have made a couple of strawman PRs here to explicitly show the fix I proposed.

**Comment by marijnh** [comment]
Does attached patch work for you?

**Comment by RichieAHB** [comment]
The minimal repro seems to work fine but I’ve gone quite a lot of abusing
filterTansaction that needs unpicking first in the actual use case for this
change that I’ll have to let you know as I I make those changes. But from
what I can see it looks good and makes sense 👌🏻

**Comment by marijnh** [comment]
Great. Closing for now, feel free to reopen if anything comes up.
