### ISSUE TITLE
Android - Backspacing in front of a line puts cursor at the wrong position

### ISSUE THREAD

**Issue by beckiechoi** [ProseMirror/prosemirror#820]
### Issue details

When you have multiple paragraphs, and you delete from the beginning of the line, joining the paragraphs, the cursor will be positioned 1 character after the correct position.

I can reproduce this on the main example editor on [prosemirror.net](http://prosemirror.net).

### Steps to reproduce

1. Create multiple paragraphs
2. Put cursor in front of the last paragraph
3. Press backspace to join paragraphs and watch your cursor end up at the wrong position

This only happens when you have the virtual keyboard open, whether or not you used the virtual keyboard. If you backspace from a hardware keyboard without the software keyboard present, this will not happen. It didn't matter whether I turned off autocomplete/predictive suggestions. Just the presence of the virtual keyboard affected this issue.

### ProseMirror version

This is my current set up:

prosemirror-model@1.5.0
prosemirror-commands@1.0.7
prosemirror-state@1.2.0
prosemirror-transform@1.0.10

### Affected platforms

Mobile Chrome (Android)
(Have tested on Android 8.0 & 8.1, Chrome 61 and 67)

### Screenshots / Screencast (Optional)

[Screencast Video](https://drive.google.com/file/d/1j_Et2lktgNM8I4WBcHXKdpH9X2PXbdbP/view?usp=sharing)

**Comment by beckiechoi** [comment]
It seems to be related to this change: https://github.com/ProseMirror/prosemirror-view/commit/eb194674f5095f454216d6330440ee0b0320112f

The condition fails as the `e.keyCode` is always `229` with the virtual keyboard open. I'm not sure how this may also affect other things like the keymap plugin. More details here: https://bugs.chromium.org/p/chromium/issues/detail?id=118639

**Comment by marijnh** [comment]
Right, Android is terrible about telling you when backspace or enter are actually pressed (you can find a comment from me from 2016 in the issue you linked ☹️). There is a kludge in ProseMirror that tries to notice when a DOM change is likely a backspace press, and call the keymap's backspace handler in that case, but it doesn't handle the diffing ambiguity that's probably at the root of this issue.

I'll try to debug this next week.

**Comment by marijnh** [comment]
ProseMirror's backspace-detection code was working as intended, but after that ran the join command, Chrome would go and move the selection once more, for obscure reasons. Attached patch adds a kludge to work around this.
