### ISSUE TITLE
[prosemirror-view] scrollRectIntoView breaks some layouts

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#823]
### Issue details

Using tr.scrollIntoView() can break layouts in some cases. It uses scrollReactIntoView which goes all the way up to `document` and applies `scrollLeft` and `scrollTop` to every node. Which in some cases leads to issues like:

<img width="928" alt="screen shot 2018-07-16 at 11 04 06 am" src="https://user-images.githubusercontent.com/200119/42740255-fd9b60e2-88e7-11e8-88b3-26f9f2c0cfa3.png">

### Steps to reproduce

1. Need to have a scrollable node inside editor content.
2. Move cursor to the end of that node.

### ProseMirror version

prosemirror-view@1.3.7

### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Other

**Comment by marijnh** [comment]
Can you create a simpler example that demonstrates the issue? I can't tell what the layout in the screenshot is supposed to look like.

**Comment by adrianheine** [comment]
Also, I don't know what `scrollReactIntoView` is supposed to be, but it's not in ProseMirror as far as I know. I'm closing this for now, feel free to re-open when you provide a simpler example.

**Comment by marijnh** [comment]
(`scroll`**`Rect`**`IntoView` is an internal method in the view package.)
