### ISSUE TITLE
dispatchTransaction doesn't provide enough details?

### ISSUE THREAD

**Issue by coodoo** [ProseMirror/prosemirror#824]
Say I have following multi-line texts

```
foo
bar
```

When user deleted `a`, is there a way to know the index position of `a` in the whole string, say in this case it might be `5`?

Currently I'm capturing the update event by providing `dispatchTransaction` to editor props, but unfortunately it didn't seem to provide enough information I need, is there any other way to achieve this?

```js
dispatchTransaction(tr) {
  // trying to find above-mentioned details from `tr` but to no avail
}
```

In short, I'm looking for something like `changeObj` from `codemirror` with following siganture`{from, to, text, removed, origin}`.

**Comment by marijnh** [comment]
You can use the step maps (`tr.mapping.maps`) and their [`forEach`](http://prosemirror.net/docs/ref/#transform.StepMap.forEach) method to get the ranges that were replaced—but note that these are relative to the document before the step so interpreting them requires some care in multi-step transactions.

Also, these are document positions, not string positions. There is no single, definite way to convert a ProseMirror document to a string, thus the library does not concern itself with string position.

**Comment by coodoo** [comment]
Very helpful responses, as always, thanks!
