### ISSUE TITLE
Node attrs are not re-computed on DOM changes

### ISSUE THREAD

**Issue by kevinzang** [ProseMirror/prosemirror#825]
### Issue details

In [prosemirror-view NodeViewDesc.parseRule](https://github.com/ProseMirror/prosemirror-view/blob/d76157e7bac58831155a3fbbe32f4f27a8ab1ccc/src/viewdesc.js#L558-L561), there is this note:

```
// FIXME the assumption that this can always return the current
// attrs means that if the user somehow manages to change the
// attrs in the dom, that won't be picked up. Not entirely sure
// whether this is a problem
```

I found one case where it is a problem. There exist browser extensions and hotkeys that change text direction, which is useful for users who type in rtl languages such as Arabic. For example, see https://chrome.google.com/webstore/detail/switch-direction/fldkjfjmcadcklboajlnclnfjpdopcce and https://blogs.technet.microsoft.com/office_global_experience/2010/02/19/useful-tricks-and-shortcuts-for-users-around-the-world/. These work by injecting `style="direction: rtl"` into the DOM. With the current implementation of `parseRule`, ProseMirror does not recompute node attrs when this DOM change happens, so I am unable to update the text direction.

Admittedly this is quite the edge case, so feel free to close the issue if you think it's not worth handling.

### Steps to reproduce

Install Chrome extension to change text direction: https://chrome.google.com/webstore/detail/switch-direction/fldkjfjmcadcklboajlnclnfjpdopcce

Use this schema:

```
paragraph: {
    attrs: { dir: { 'default': '' } },
    content: 'inline*',
    group: 'block',
    parseDOM: [
        {
            tag: 'p',
            getAttrs(dom) {
                const dirStyle = (dom.style.direction || '').toLowerCase().replace('!important', '').trim();
                const dirAttr = (dom.dir || '').toLowerCase();
                return { dir: dirStyle || dirAttr };
            },
        },
    ],
    toDOM(node) {
        return ['p', node.attrs, 0];
    },
}

```

Type "test test" into the editor.

Select all of the text, right click, and click "Switch Text Direction":

<img width="300" alt="screen shot 2018-07-25 at 5 35 39 pm" src="https://user-images.githubusercontent.com/6496295/43234497-3746113e-9031-11e8-96c7-afd04a4b3e69.png">

Expect the text to be rtl, but actually it's still ltr.

My current workaround is a monkey patch to `parseRule` to force it to recompute the `dir` attr:

```
NodeViewDesc.prototype._originalParseRule = NodeViewDesc.prototype.parseRule;
NodeViewDesc.prototype.parseRule = function monkeyPatchedParseRule() {
    const parsed = this._originalParseRule();
    const dirStyle = (this.dom.style.direction || '').toLowerCase().replace('!important', '').trim();
    const dirAttr = (this.dom.dir || '').toLowerCase();
    parsed.attrs = { ...parsed.attrs, dir: dirStyle || dirAttr };
    return parsed;
};
```

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Thanks for providing this use case.

This is a somewhat confusing part of the system, in that it would in principle be possible to always fully reparse nodes in the view, except that that adds the requirement that nodes' editable representation is parseable by the parser provided by the `domParser` prop, which isn't currently the case. I also vaguely remember doing things this way works around some other complications, but I unfortunately didn't write down what those are.

So at this point just removing `parseRule` for node view descs is too scary. But attached patch adds a way to opt out of it by giving your node type spec a truthy `reparseInView` property. For simple nodes without a custom view, this should be safe to do. Could you try building the current prosemirror-view code with that change, add that property to your node types, and tell me how it works for you? I'm not committing to officially adding this feature at this point, but it may be a (somewhat kludgy) solution.

**Comment by kevinzang** [comment]
@marijnh thank you! The attached patch does work for me.
