### ISSUE TITLE
Bind `this` to EditorView in `dispatchTransaction` prop?

### ISSUE THREAD

**Issue by RichieAHB** [ProseMirror/prosemirror#826]
I wondered if it might be a good idea to bing `this` to the EditorView instance in `dispatchTransaction`. I have a situation where I'm deriving some data from a node view and want to dispatch a transaction as soon as it mounts. This can happen when instantiating a view so the variable for `view` won't have been bound yet and so `dispatchTransaction` will throw an error.

```js
// a basic example
dispatchTransaction: tr => {
    const state = view.state.apply(tr);
    view.updateState(state);
    document.body.style.backgroundColor = hasErrors(state)
      ? 'red'
      : 'transparent';
  }
```

I realise binding to `this` will probably be fine for updating state, but if a consumer where to use something that was not yet constructed this may cause a problem.

**Comment by marijnh** [comment]
I'd accept a pull request that implements that (make sure to document and add a test).

I am quite curious how you managed to dispatch a transaction before the view finished constructing, though—initialization is synchronous and, in principle, shouldn't itself fire transactions.

**Comment by RichieAHB** [comment]
Well I did think this, perhaps there is a more idiomatic way of doing this. When the node view constructs, parts of its setup is to validate itself and then store that in the plugin state that is handling the node view (by dispatching a transaction). This may not be the wisest move but means that I don't have validation information in the plugin state until and edit is made.

**Comment by marijnh** [comment]
Ah, I see, the dispatch happens after the constructor returns, but before the necessary binding is available.

I've merged https://github.com/ProseMirror/prosemirror-view/pull/34
