### ISSUE TITLE
Console error when double-clicking on an uneditable view

### ISSUE THREAD

**Issue by kevinzang** [ProseMirror/prosemirror#828]
### Issue details

There's a console error when double-clicking on an uneditable view.

### Steps to reproduce

See:
https://glitch.com/edit/#!/kind-barnacle?path=index.js:1:0
https://kind-barnacle.glitch.me/

- Initialize an EditorView with `editable: () => false` and empty content.
- Render the editor before a focusable element, such as an anchor.
- Double-click the editor.
- Observe console error.

```
<div id=editor style="margin-bottom: 23px"></div>
<div style="display: none" id="content"></div>
<a id="test" href="https://glitch.com/edit/#!/kind-barnacle?path=index.html:15:71"># An anchor</a>
```

```
Uncaught TypeError: Cannot read property 'size' of undefined
    at Je.readFromDOM (prosemirror.js:1)
    at HTMLDocument.We.readFunc (prosemirror.js:1)
Je.readFromDOM @ prosemirror.js:1
We.readFunc @ prosemirror.js:1
```

I believe the focusable element causes SelectionReader.domChanged to return true when you double-click, even though the DOM has not actually changed. Perhaps we should explicitly ignore selection updates when the view is not editable?

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

<img width="300" alt="screen shot 2018-08-02 at 12 56 15 pm" src="https://user-images.githubusercontent.com/6496295/43607599-7853dfbc-9653-11e8-8fc3-a25d261059b0.png">

**Comment by marijnh** [comment]
Attached patch should help. I don't think there's a reason to ignore selection updates when uneditable—it can still be nice to have the editor selection match the DOM selection.

**Comment by kevinzang** [comment]
@marijnh thanks for the patch! It fixes `TypeError: Cannot read property 'size' of undefined` but now I get a different error when I double-click an uneditable view:

`TypeError: Cannot read property 'pmViewDesc' of null`

<img width="300" alt="screen shot 2018-08-06 at 6 34 48 am" src="https://user-images.githubusercontent.com/6496295/43719627-0d924a2c-9943-11e8-9f73-32147edb412f.png">

You can use the same glitch to reproduce the issue:

https://glitch.com/edit/#!/kind-barnacle?path=index.js:1:0
https://kind-barnacle.glitch.me/

**Comment by saranrapjs** [comment]
@marijnh we're also seeing this persist as a console error, post-fix

**Comment by marijnh** [comment]
Ah, the error occurred when the anchor side of the selection was inside the editor, but the other side was outside. Attached patch should address this. I've released it as prosemirror-view 1.5.1

**Comment by azaslonov** [comment]
Hi @marijnh, don't know if this is the same issue but looks similar (on latest bits):

![image](https://user-images.githubusercontent.com/2320302/82830662-379dd000-9e6b-11ea-8215-c4e783da7a36.png)

**Versions used:**
 prosemirror-keymap   ^1.1.3
 prosemirror-model    ^1.9.1
 prosemirror-view    ^1.14.8

Please advice.

**Comment by marijnh** [comment]
@azaslonov I couldn't reproduce this, but going by the stack trace, attached patch might help.

**Comment by azaslonov** [comment]
Yeah, this is not easy to repro, but on the volume of thousands of customers it comes up pretty often. To clarify, what do you mean by "attached patch"?

**Comment by marijnh** [comment]
Sorry, I messed up the issue link—see https://github.com/ProseMirror/prosemirror-view/commit/87c65926a97e3ee2b29531d6afa715cad998d8aa

**Comment by azaslonov** [comment]
Oh, thanks for quick turnaround! Do you have ETA on releasing new npm package?
