### ISSUE TITLE
Link insertion not working?

### ISSUE THREAD

**Issue by wes-r** [ProseMirror/prosemirror#83]
Playing around with the editor locally and on prosemirror.net it appears links can only be created on existing text. Is this by design? Should I build a new command to insert an entirely new link with text?

Ideally:
* No text selected = entirely new link
* link selected = allow editing of href & link text

**Comment by marijnh** [comment]
The current link command works like the other styling commands -- if you click it when there is no text selection, it'll update the current caret style, and you have to type something after doing that to have your link show up.

It would be possible to create your own command that does insert a whole link. Something like this (untested):

```javascript
LinkStyle.attachCommand("insertLink", type => ({
  label: "Insert a link",
  run(pm, href, text, title) {
    pm.tr.replaceSelection(pm.schema.text(text, [type.create({href, title})])).apply()
  },
  params: [
    {name: "Target", type: "text"},
    {name: "Text", type: "text": ""},
    {name: "Title", type: "text", default: ""}
  ]
}))
```

**Comment by wes-r** [comment]
Ok, that makes sense, although I think most people expect different behavior.

Also - thanks for the amazingly quick response!

**Comment by Hunter-Github** [comment]
This is non-intuitive.

**Comment by ericandrewlewis** [comment]
Perhaps we could request "link text" from the user in the "new link" dialog.

**Comment by marijnh** [comment]
That's what the code I showed above does.

**Comment by wes-r** [comment]
The other problem I ran into is that since link is a normal "style", if you were to add text after the link, you'll still be in link mode.

E.G:
"hello LINK world"
Moving your cursor just after the K and typing "(space) the" would change the link text to "LINK the". Instead of adding the non link text " the".

I had to hack the style code to check if it was at the end of a link and kill the style.
