### ISSUE TITLE
Android: Applying Marks to Text Does Not Apply Until View Re-Rendered

### ISSUE THREAD

**Issue by steveccable** [ProseMirror/prosemirror#830]
### Issue details

When adding marks to text while editing on Android (in both WebViews within apps as well as the Chrome browser), applying the mark does not reflect in the editor until the view is redrawn, either via rotation or locking/unlocking the device.

### Steps to reproduce

https://glitch.com/edit/#!/ember-cactus (same as the basic demo but with all the initial contents removed from the editor)
On Android, begin typing in the editor using the software keyboard and DO NOT add any whitespace to what you are typing.  At some point, apply a mark by clicking the buttons provided in the demo (ie bold).  Continue typing, and notice that the mark is not applied.
Rotate the screen, and see that now the entire block of text has the selected mark applied, not just the part typed after selecting the mark.
The same behavior can be repeated, but substituting `lock and unlock the device screen` for `rotate the screen`.

### ProseMirror version

Appears in the current demo version (at time of writing, that appears to be 1.4.1) but has been noted back to 1.3.1 (the version my app was using at time of first seeing this behavior).

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other

This is seen only on Android devices, but has been noted across multiple browser versions (all Chrome, since that is the default Android browser) and multiple Android OS versions.

May be related to #543 but making a separate issue as requested in that discussion.

**Comment by marijnh** [comment]
You were right, that is indeed a symptom of #543. Thanks for the detailed documentation. Merging this back into that issue.

**Comment by marijnh** [comment]
(There's been some progress in #543 — do help test if you're still interested in this.)
