### ISSUE TITLE
[prosemirror-view] Rogue br tag when deleting through widget

### ISSUE THREAD

**Issue by RichieAHB** [ProseMirror/prosemirror#831]
### Issue details

Backspacing through absolutely positioned widget decorations introduces a rogue `br` tag

### Steps to reproduce

Open this doc, select at the end, backspace through the doc

https://glitch.com/edit/#!/join/b5a9d33d-c933-4594-995c-6b756d47e977

### Affected platforms

- [x] Chrome
- [ ] Firefox (untested)
- [ ] Internet Explorer (untested)
- [ ] Other

### Screenshots / Screencast (Optional)

http://recordit.co/wWtSoyWxQ7

**Comment by RichieAHB** [comment]
It's tested with 1.4.2 unfortunately - interestingly, it doesn't seems to be a problem when the widget isn't absolutely positioned.

**Comment by RichieAHB** [comment]
Given it does sound like #799 I tested it in FF and it works so I think it's probably a very similar issue.

**Comment by marijnh** [comment]
Does this patch solve your issue?

```diff
diff --git a/src/domchange.js b/src/domchange.js
index b58ff4a..c258d1e 100644
--- a/src/domchange.js
+++ b/src/domchange.js
@@ -118,9 +118,15 @@ function parseBetween(view, oldState, range) {
     if (!selectionCollapsed(domSel))
       find.push({node: domSel.focusNode, offset: domSel.focusOffset})
   }
-  // Work around issue in Chrome where backspacing sometimes replaces the deleted content with a random BR node
-  if (browser.chrome && view.lastKeyCode === 8 && toOffset > fromOffset &&
-      parent.childNodes[toOffset - 1].nodeType == "BR" && !parent.childNodes[toOffset - 1].pmViewDesc) toOffset--
+  // Work around issue in Chrome where backspacing sometimes replaces
+  // the deleted content with a random BR node (issues #799, #831)
+  if (browser.chrome && view.lastKeyCode === 8) {
+    for (let off = toOffset; off > fromOffset; off--) {
+      let node = parent.childNodes[off - 1], desc = node.pmViewDesc
+      if (node.nodeType == "BR" && !desc) { toOffset = off; break }
+      if (!desc || desc.size) break
+    }
+  }
   let startDoc = oldState.doc
   let parser = view.someProp("domParser") || DOMParser.fromSchema(view.state.schema)
   let $from = startDoc.resolve(from)
```

**Comment by RichieAHB** [comment]
I actually already tried that and it removes the decoration that was skipped over, I considered mutating the `NodeList` but that might be heresy?! Also there are maybe a few issues in that patch if you were still looking at it:
- I think it should be `toOffset = off - 1` (I'm assuming `toOffset` is exclusive)
- `tagName === "BR"
- `result.chrome`.

**Comment by RichieAHB** [comment]
Actually - I think _I_ had `nodeType` in my code ... this may work now work for the backspace case, will double check. Although, unlike #799, it does have a delete case too ...

**Comment by RichieAHB** [comment]
FYI - for now I can sort of fix this for my use case using elements that are not absolutely positioned.

**Comment by ahallora** [comment]
I stumbled upon this issue today with an inline node that contains an absolute positioned element.
```html
<span>
    <span class="input"></span>
</span>
```

When I delete the text before the inline node (using backspace/delete) Chrome inserts an empty `<br>` as the first element in the paragraph resulting in an undesired line-break. It works as expected in Firefox. 

In this demo you can see, the only difference between the two inline nodes is the 2nd `span.input` have a different background color and a different position not being absolute, resulting in the correct behaviour, while the blue node, containing an absolutely positioned inner element, gets a `<br>` injected before it. 

![blue-br](https://github.com/ProseMirror/prosemirror/assets/5302751/71056b15-e647-4d61-b65b-4d332c241dff)

How to stop chrome from inserting the `<br>` ?

**Comment by marijnh** [comment]
This appears to be a Chrome bug (it reproduces even in a plain contenteditable element). I don't see much of a way ProseMirror can fix that, except adding some dodgy code to try and detect and undo it. But since that kind of code often ends up producing problems, and this is a very specific and hopefully rare scenario, that doesn't seem like a good approach.

I'd recommend just finding a DOM structure/styling that avoids the Chrome issue.
