### ISSUE TITLE
Stuck plaintext paste

### ISSUE THREAD

**Issue by quirm** [ProseMirror/prosemirror#834]
### Issue details

When a clipboard payload is pasted into the editor it works just fine. However, when I change a tab in Chrome using `CMD + Shift + [` shortcut and go back to paste again, content is pasted as a plaintext. The problem is that `view.shiftKey` gets somehow stuck to `true` and params in this function:
```javascript
function doPaste(view, text, html, e) {
  var slice = parseFromClipboard(view, text, html, view.shiftKey, view.state.selection.$from);
  ...
```

...will cause that paste is always plaintext based on the signature of `parseFromClipboard(view, text, html, plainText, $context)`.

### Steps to reproduce

1. Just copy a piece of text with format and paste it in.
2. Press `CMD + Shift + [` to change to a tab on the left or `]` on the right.
3. Get back to the tab with the editor and try to paste again.

### ProseMirror version

"prosemirror-commands": "1.0.7",
"prosemirror-history": "1.0.2",
"prosemirror-keymap": "1.0.1",
"prosemirror-model": "1.6.1",
"prosemirror-state": "1.2.2",
"prosemirror-transform": "1.1.3",
"prosemirror-view": "^1.0.11",

### Affected platforms

- [x] Chrome v68
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

I tested only Chrome and Firefox.

### Screenshots / Screencast

http://g.recordit.co/KbyisGXYap.gif

**Comment by marijnh** [comment]
Attached patch should help with this (it's still not 100% perfect, since paste events unfortunately don't come with a `shiftKey` property, but should be a lot harder to confuse)

**Comment by quirm** [comment]
@marijnh thank you
