### ISSUE TITLE
[prosemirror-inputrules] Is InputRule supposed to be an opaque class?

### ISSUE THREAD

**Issue by lostfictions** [ProseMirror/prosemirror#835]
### Issue details

The maintainers for the [typings for ProseMirror on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prosemirror-inputrules/index.d.ts) seem to be pretty staunch about mapping directly to the ProseMirror documentation. There's debate in this [PR to make the fields of InputRule accessible](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27770), since they're not described as such in the docs. That doesn't really make sense to me, since if those fields aren't public InputRule is a totally opaque class that can't really be used by consumers who want to apply InputRules themselves. Any chance this could be clarified, either here or in that issue?

**Comment by marijnh** [comment]
I do consider it an opaque class, mostly because I don't really see why you'd want to use these objects in any other way than feeding them to the plugin. Do you have a use case like that?

**Comment by lostfictions** [comment]
Sure. I had to introduce an alternative plugin that works differently from the default InputRules plugin: 

https://github.com/PeerioTechnologies/peerio-desktop/blob/43c063deb4d130999ac93d91bff16581c31ea6a1/src/helpers/chat/prosemirror/ensured-input-rules.ts#L20-L58

**Comment by marijnh** [comment]
Would it be difficult to use your own rule class for such code?

**Comment by lostfictions** [comment]
Nope, that's fine by me too. Thanks for the clarification!
