### ISSUE TITLE
Backspace puts the cursor in wrong position in certain cases when using Android Gboard keyboard

### ISSUE THREAD

**Issue by kkasinathan** [ProseMirror/prosemirror#837]
### Issue details
Backspace puts the cursor in wrong position in certain cases when using Android Gboard keyboard

### Steps to reproduce

* Navigate to the [Prosemirror example web page](https://prosemirror.net/examples/basic/) on Android (Chrome browser)
* Enter the words "One three"
* Take the cursor to the end of the word "One"
* Press space and then select "bold" style and type "two"
* Press backspace

Expected Behavior
* The "o" in "two" should be deleted and the cursor should move to the end of "w" in "two"

Current Behavior
* The cursor does not move to the end of "w" ([attached video](https://github.com/ProseMirror/prosemirror/files/2291851/Prosemirror_Backspace.zip))

NOTE: This only happens when I use the Gboard virtual keyboard with Suggestion strip and Auto-correction turned on

### ProseMirror version

The current version of Prosemirror version (1.4.4)

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [X] Other

### Screenshots / Screencast (Optional)

[Prosemirror_Backspace.zip](https://github.com/ProseMirror/prosemirror/files/2291851/Prosemirror_Backspace.zip)

**Comment by manderssen** [comment]
I'm having a similar issue, deleting content with marks using backspace will stop when the node becomes empty: [Deletion stops](http://recordit.co/kQxpeJjbAv)

Chrome on Android emulator and ProseMirror collaboration example running locally
prosemirror-view 1.8.3
prosemirror-model 1.7.0
prosemirror-state 1.2.2

Strangely this does not happen with the version running on ProseMirror.net: [Expected behaviour](http://recordit.co/W6D1gmLVnm)

**Comment by randolf** [comment]
I also reported this issue, which, I suppose, might have the same cause:  https://github.com/joelewis/prosemirror-mentions/issues/1

**Comment by 1Jesper1** [comment]
Hello @marijnh Could you please look into this problem? I was hoping the fixes of https://github.com/ProseMirror/prosemirror/issues/543 would also fix the Gboard issues.

**Comment by 1Jesper1** [comment]
Hello @marijnh Could you please look into this if you have time?

**Comment by jljorgenson18** [comment]
This might be related to https://github.com/ProseMirror/prosemirror/issues/935. Internally, CompositionViewDesc's are replacing MarkViewDesc's when syncing marks. This makes the mark reapply itself on every new character which modifies the dom beyond just adding a character. Android uses composition in a similar way to Japanese IME inputs so this could just be the browsers reacting poorly to the dom modifications.

**Comment by marijnh** [comment]
This appears to be fixed in the current version (following the reproduction instructions doesn't cause any wrong behavior for me).
