### ISSUE TITLE
Wrong style applied in certain cases when using Android Gboard keyboard

### ISSUE THREAD

**Issue by kkasinathan** [ProseMirror/prosemirror#838]
### Issue details

Wrong style applied in certain cases when using Android Gboard keyboard

### Steps to reproduce

* Navigate to the [Prosemirror example web page](https://prosemirror.net/examples/basic/) on Android (Chrome browser)
* Enter the word "Three"
* Take the cursor to the start of the word "Three"
* Enter the word "One" and press space
* Select the bold style and type "two"
* Press space again

Expected Behavior
* The bold style should only be applied to the word "two"

Current Behavior
* Bold style gets applied to "two" and "three" ([attached video](https://github.com/ProseMirror/prosemirror/files/2291865/Prosemirror_style.zip))

NOTE: This only happens when I use the Gboard virtual keyboard with Suggestion strip and Auto-correction turned on

### ProseMirror version

The current version of Prosemirror version (1.4.4)

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [X] Other

### Screenshots / Screencast (Optional)

[Prosemirror_style.zip](https://github.com/ProseMirror/prosemirror/files/2291865/Prosemirror_style.zip)

**Comment by marijnh** [comment]
This seems to have been fixed in the meantime. (But feel free to add details if it's still happening for you.)
