### ISSUE TITLE
Cursor jumps a character on pressing space key in certain cases when using Android Gboard keyboard

### ISSUE THREAD

**Issue by kkasinathan** [ProseMirror/prosemirror#839]
### Issue details

Cursor jumps a character on pressing space key in certain cases when using Android Gboard keyboard

### Steps to reproduce

* Navigate to the [Prosemirror example web page](https://prosemirror.net/examples/basic/) on Android (Chrome browser)
* Enter the word "Two"
* Take the cursor to the start of the word "Two"
* Select the bold style and type "One"
* Press space

Expected Behavior
* The cursor stays at the beginning of "Two"

Current Behavior
* The cursor jumps to end of "T" in "Two" ([attached video](https://github.com/ProseMirror/prosemirror/files/2291870/Prosemirror_space.zip))

NOTE: This only happens when I use the Gboard virtual keyboard with Suggestion strip and Auto-correction turned on

### ProseMirror version

The current version of Prosemirror version (1.4.4)

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [X] Other

### Screenshots / Screencast (Optional)

[Prosemirror_space.zip](https://github.com/ProseMirror/prosemirror/files/2291870/Prosemirror_space.zip)

**Comment by marijnh** [comment]
I don't see any cursor jumping anymore when I try this. But I did run into a possibly related bug in this scenario (https://github.com/ProseMirror/prosemirror/issues/1043).
