### ISSUE TITLE
Pasting content copied from an HTML page inserts double spaces in some cases

### ISSUE THREAD

**Issue by kiejo** [ProseMirror/prosemirror#842]
### Issue details

Copying content from an HTML page and pasting it in a ProseMirror editor inserts two spaces where the original document only contains one space in certain cases.

Inspecting the clipboard content, I noticed that Firefox puts additional line breaks in the html clipboard content which seem to translate to additional spaces in ProseMirror. Here is an example of the html clipboard content I got when copying the text from step 1:
```
Computer science is the study of the theory, experimentation, and 
engineering that form the basis for the design and use of computers. It 
is the scientific and practical approach to computation and its 
applications and the systematic study of the feasibility, structure, 
expression, and mechanization of the methodical procedures (or 
algorithms) that underlie the acquisition, representation, processing, 
storage, communication of, and access to, information.
```
For every line break there is an additional space in the ProseMirror content.

### Steps to reproduce

1. Copy the following text:

Computer science is the study of the theory, experimentation, and engineering that form the basis for the design and use of computers. It is the scientific and practical approach to computation and its applications and the systematic study of the feasibility, structure, expression, and mechanization of the methodical procedures (or algorithms) that underlie the acquisition, representation, processing, storage, communication of, and access to, information.

2. Paste the text in a ProseMirror editor, e.g. on https://prosemirror.net/
3. Notice that some words are separated by two spaces even though the original content only has one space at the same position.

### ProseMirror version

prosemirror-view 1.4.4
prosemirror-model 1.6.1

### Affected platforms

- [ ] Chrome
- [X] Firefox 60, 61 (tested on macOS and Linux)
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
It seems the browser considers whitespace in copied HTML to be collapsable, and thus feels free to include extra newlines. Attached patch makes the editor only parse content with preserved whitespace when it was generated by ProseMirror itself, or pasted as text. Does that solve the issue?

**Comment by kiejo** [comment]
Looks good, I can't reproduce the issue anymore!

**Comment by adrianheine** [comment]
Ok, I close this :)
