### ISSUE TITLE
[view] 1.5.0 third argument marks view getPos -> Boolean is a breaking change ?

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#846]
Hi,

https://github.com/ProseMirror/prosemirror-view/commit/73c3ebb1816e68396e3efaa6b8cc7989c5b87766 broke some code here. Not that it's hard to fix, but i thought it would have been worth a major version bump.

**Comment by kapouer** [comment]
Well, never mind the pizza. I blindedly checked the presence of third argument.

**Comment by marijnh** [comment]
Yeah, it's a borderline case, but I think adding a value in a situation where it wasn't previously available only breaks code that was a little dodgy in the first place, so I was willing to let this slip through as non-breaking.
