### ISSUE TITLE
decorationSet.map doesn't remap position correctly

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#849]
### Issue details

Hey, @marijnh 
I'm struggling with getting `decorationSet.map` to work. Here's my document:
```
doc
  table
    tr
      td p /p /td  td p /p /td 
    /tr
    tr
      td p "X" /p /td  td p /p /td 
    /tr
  /table
/doc
```
* "X" is a widget decoration (telepointer in collab editing), position is 14. 
<img width="362" alt="screen shot 2018-09-26 at 5 18 43 pm" src="https://user-images.githubusercontent.com/26512812/46063537-779d4300-c1b0-11e8-85e7-d37e8477cb46.png">

* when the first column gets removed (only two cells left, one in each row), `decorationSet.map` gives decoration position = 6 (expected 8). 
<img width="456" alt="screen shot 2018-09-26 at 5 18 23 pm" src="https://user-images.githubusercontent.com/26512812/46063578-9996c580-c1b0-11e8-8059-bc8df22bf374.png">
<img width="355" alt="screen shot 2018-09-26 at 5 18 55 pm" src="https://user-images.githubusercontent.com/26512812/46063586-9e5b7980-c1b0-11e8-8e21-6c4ebcffd1ee.png">

As a result, telepointer ends up after the <td> node which breaks the table. It seems like the issue started to happen after bumping `prosemirror-view` to `1.5.2`. If you have time to have a look that'd be great. Thanks.

### ProseMirror version

`prosemirror-view`: 1.5.2 
`prosemirror-state`: 1.2.2 
`prosemirror-transform`: 1.1.3

### Affected platforms

- [x ] Chrome

**Comment by marijnh** [comment]
The decoration appears to be _in_ the first column, so I'd actually expect it to be removed when you map like this. Looking at the code, I don't see any reason why it would be preserved, and when I try to reproduce this locally, the decoration is removed by the mapping.

Can you set up a small, self-contained demo for this?

**Comment by eshvedai** [comment]
right, its in the first column of the second row. It seems like in my case instead of calling [onRemove callback](http://prosemirror.net/docs/ref/#view.DecorationSet.map^options.onRemove) it just remaps the position. 
I use 
```
decorationSet.map(tr.mapping, tr.doc, { onRemove });
```
`tr.mapping` looks like this:
<img width="409" alt="screen shot 2018-09-26 at 10 32 28 pm" src="https://user-images.githubusercontent.com/26512812/46080137-6ec26680-c1dc-11e8-9ccc-9a07f56db4a8.png">
`tr.doc` already has one column table.

I'll try to setup a demo tomorrow.

**Comment by eshvedai** [comment]
Please have a look at the [demo](https://github.com/ProseMirror/prosemirror-tables/tree/eshvedai/decoration-test)

Open `index.html` and try to remove the first column:

![table_deco](https://user-images.githubusercontent.com/26512812/46113136-81668b00-c230-11e8-8561-efab67bf09eb.gif)

**Comment by marijnh** [comment]
Thanks for the demo! I could reproduce the issue with that, and I've fixed it in attached patch.
