### ISSUE TITLE
html paste throws error when not equal to lastCopied

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#85]
Steps to reproduce:

1. Load single editor demo page
2. Select some parts of the contents within the editor
3. Copy with CTRL+C
4. Reload the page
5. Place the caret inside the editable area
6. Try to insert the copied contents using CTRL+V

Expected result:
HTML content should be inserted at the place of the caret.

What happens:
Error message "Uncaught Error: Index 1 out of range in doc(paragraph("the usual ", strong("strong"), " an"))"

**Comment by marijnh** [comment]
Thanks for the report! Fixed by 6791608c84d7
