### ISSUE TITLE
prosemirror-commands autoJoin type

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#850]
### Issue details

https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L521-L534

Current signature is:

```
// :: ((state: EditorState, ?(tr: Transaction)) → bool, union<(before: Node, after: Node) → bool, [string]>) → (state: EditorState, ?(tr: Transaction)) → bool
```

however I think the type should be:

```
// :: ((state: EditorState, ?(tr: Transaction)) → bool, union<(node: Node) → bool, [string]>) → (state: EditorState, ?(tr: Transaction)) → bool
```

So the signature of `isJoinable` changes to take a single node.

**Comment by marijnh** [comment]
Why do you think that? `isJoinable` is called on line 506, with two arguments.

**Comment by bradleyayers** [comment]
Whoops I stand corrected!

I think a few things led to my wrong conclusion:

- I was confused by the implementation on https://github.com/ProseMirror/prosemirror-commands/blob/master/src/commands.js#L531 only using a single argument
- I interpreted the comment as implying nodes are considered in isolation: (in retrospect I see how it could mean _both are considered together_)

    > Nodes are considered joinable when they are of the same type and when the `isJoinable` predicate returns true for them.

- I didn't comprehend exactly what `before` and `after` would correspond to
- I've come across invalid types in the past

I think those exposures led me to draw the wrong assumption that it was a stale.
