### ISSUE TITLE
NodeView reconstruction

### ISSUE THREAD

**Issue by pulse14** [ProseMirror/prosemirror#851]
I use this example nodeview
```javascript
class Demo {
    _options = null;
    _node = null;
    _view = null;
    _getPos = null;
    _decorations = null;

    _componentRenderDomElement = undefined;
    _componentManagedDomElement = undefined;

    constructor( options, node, view, getPos, decorations) {
        this._options = options;
        this._node = node;
        this._view = view;
        this._getPos = getPos;
        this._decorations = decorations;

        console.log("init");
        this._componentRenderDomElement = this._createRenderDomElement();

        if (this._options.hasManagedContent) {
            this._componentManagedDomElement = this._createManagedDomElement();
            this._componentRenderDomElement.appendChild(this._componentManagedDomElement);
        }
    }

    _createRenderDomElement() {
        const element =  this._node.isInline ? document.createElement('span') : document.createElement('div');
        element.className = "ReactNodeView-wrapper";
        element.innerHTML = "gg";
        return element;
    }

    _createManagedDomElement() {
        const element =  document.createElement('div');
        element.className = "ReactNodeView-managed";
        return element;
    }

    /**
     * Properties used by ProseMirror
     */
    get dom() {
        return this._componentRenderDomElement;
    }
    get contentDOM() {
        return this._componentManagedDomElement;
    }

    destroy() {
        console.log("destroy");
    }
}
```
This schema
```javascript

const schemaToUse = new Schema({
    nodes: schema.spec.nodes.append({
        test: {
            content: 'text*',
            group: 'block',
            parseDOM: [{tag: "test"}, 0],
            toDOM: function toDOM() {
                return ["test", 0];
            }
        }
    }),
    marks: schema.spec.marks
});
```

And this state
```javascript
EditorState.fromJSON(
            { schema: schemaToUse },
            {
                doc: {
                    type: 'doc',
                    content: _.range(100).map(() => {
                        return { type: 'test', content: [] }
                    })
                },
                selection: { type: 'text', anchor: 0, head: 0 }
            }
        )
```
# First issue

When I configure my NodeView like this
```javascript
                        nodeViews: {
                            test: (...args) => {
                                return new Demo({ hasManagedContent: false }, ...args)
                            }
                        }
```

And I remove approx. first 10 nodes I get
- 79 init
- 89 destroy

And I remove approx. last 10 nodes I get
- 1 init
- 11 destroy

If I change the option to `{ hasManagedContent: true }` I get similar results

# Second issue

Now I update `_createRenderDomElement` in the Nodeview. 

```javascript
    _createRenderDomElement() {
        const element =  this._node.isInline ? document.createElement('span') : document.createElement('div');
        element.className = "ReactNodeView-wrapper";
        element.innerHTML = "gg";
        setTimeout(() => {
            const test = document.createElement('div');
            test.innerHTML = "gg2";
            element.appendChild(test);
        }, 2000);
        return element;
    }
```
With `{ hasManagedContent: false}`, I don't have any issue. 
But when I change options to be `{ hasManagedContent: true}`, I enter in a render loop.

This code is really simplified compare to my code. But it's the same issue. In my code, when I mount my react component it does not always enter in a render loop, but it causes a lot of init and destroy. If there is some delay between the mounting and NodeView creation, it causes the render loop.
At minimum it causes double creation of NodeView.

My understanding of the issue is that when there is no `contentDOM` ProseMirror doesn't analyse element. So no issue. But when I change `dom`, even If I don't change `contentDOM`, ProseMirror try to compare things.

**Comment by marijnh** [comment]
That's still not really a self-contained demo, though.

>  But when I change dom, even If I don't change contentDOM, ProseMirror try to compare things.

The issue there might be that you're not defining an [`ignoreMutation` method](http://prosemirror.net/docs/ref/#view.NodeView.ignoreMutation), which will cause the editor to assume that if the DOM inside the view is mutated, it should re-render it.

**Comment by pulse14** [comment]
` ignoreMutation` seems to solve the second issue. Performances are way better. 
For the first issue : https://codesandbox.io/s/3y75x47jxp Simply select first 10 and press any key

**Comment by pulse14** [comment]
@marijnh Hello, do you have news on this issue ? I have a lot of nodeview and it causes performance issues... When lines are deleted at the end, it works fine.

**Comment by marijnh** [comment]
I'm not seeing any spurious node view construction happen in that demo—when I delete nodes at the start, only their destroy method is called, no new ones are allocated. Are you using the latest version of prosemirror-view?

**Comment by pulse14** [comment]
@marijnh Seems to work now, we didn't notice the change because of another performance issues caused by  `prosemirror-dev-tools`. It slows down the dispatch.
NodeView updating and deleting seems to work fine now
