### ISSUE TITLE
Block level marks

### ISSUE THREAD

**Issue by d4rkr00t** [ProseMirror/prosemirror#853]
### Issue details

Hi,

I read your stance on [block level marks](https://discuss.prosemirror.net/t/discussion-what-are-marks/862/15), but I was experimenting with them as they look very useful for some of our use cases:
* Indentation of blocks

I got stuck very quickly with my experimenting because of the following issues:
* Document doesn't validate if there are blocks with marks.
* There isn't any way to add them using existing PM apis. (I tried add/remove mark, and replacing node with another node with block level marks).
* Editing a document containing blocks with marks throws lots of errors in console.

### Steps to reproduce

Example: https://codesandbox.io/s/r4prxx777o

* You can look at validation errors in console. They are from `node.createChecked`.
* Editing document blows up the editor.
* Replace node button shows that replacing node doesn't work, marks on a block just get ignored.

### ProseMirror version

<img width="250" alt="screen shot 2018-10-04 at 10 40 34 am" src="https://user-images.githubusercontent.com/200119/46446858-0cf89280-c7c2-11e8-8cc9-2ddfc73056a6.png">

**Comment by marijnh** [comment]
The first problem appears to be that you didn't actually adjust the schema to allow your block-level marks, which explains symptom number 1, and probably the others as well. See the [`marks` property](http://prosemirror.net/docs/ref/#model.NodeSpec.marks) on node specs.

**Comment by d4rkr00t** [comment]
Oh, you are right 🤦‍♂️
