### ISSUE TITLE
failed to implement editMark method for a keymap

### ISSUE THREAD

**Issue by keelii** [ProseMirror/prosemirror#855]
Hi, there. I want to implement `editMark` method on links, but it doesn't work, because of the closure in keyDown event maybe? is there any way to do this. thx

```js
keymap({
    'Mod-z': undo,
    'Mod-y': redo,
    'Mod-e': myEditMark(schema.marks.link, {
        href: 'http://dynamic.link' + Math.random(),
        title: 'dynamic.title.' + Math.random(),
    }),
    'Mod-i': toggleMark(schema.marks.em),
    'Mod-b': toggleMark(schema.marks.strong),
}),
...
// keymap
return new Plugin({props: {handleKeyDown: keydownHandler(bindings)}})
```

**Comment by adrianheine** [comment]
Hi, could you give us a link to a complete, minimal example showing the issue? Also, please describe what you would expect to happen and what happens instead.
