### ISSUE TITLE
Pasting a file inside table triggers browser window scroll

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#856]
### Issue details

When I paste a file (e.g. on mac: cmd+ctrl+shift+4 puts a screenshot to a clipboard)

<img width="542" alt="screen shot 2018-10-11 at 1 38 02 pm" src="https://user-images.githubusercontent.com/26512812/46777349-f078cf00-cd5a-11e8-9ed7-2e22b0b090e5.png">

`prosemirror-view` -> `capturePaste` gets fired (slice === null), where `target.focus();` sets focus to a hidden element and restores it back to the editor in a setTimeout. 

Our code handles pasting files by converting a screenshot to a media node. 

When pasting happens, 50 ms later when `capturePaste` -> `setTimeout` gets fired, `view.focus()` triggers the browser scroll all the way up. It only happens inside table cell, pasting outside doesn't scroll the page.

`capturePaste` does nothing when `e.clipboardData.types.indexOf('Files') > -1 === true`. Would it make sense to return from `capturePaste` when that happens so that we don't loose the focus in the first place?

### ProseMirror version

prosemirror-view:  `1.6.0`

### Affected platforms

- [x ] Chrome

**Comment by marijnh** [comment]
Would it work for you if the `paste` event handler simply calls `preventDefault()` when `data.files.length > 0`? Since the core can't handle file pastes, it should probably just do nothing for them.

**Comment by eshvedai** [comment]
that works, thanks!

**Comment by marijnh** [comment]
Done in attached patch and released as 1.6.3

**Comment by saranrapjs** [comment]
@marijnh the patch in 1.6.3. breaks pastes which originate from Microsoft Word; not sure if there's a different way to detect the files-only use case here, but it seems important to preserve cases where an app chooses to attach files even if the paste is _not_ a file paste

**Comment by marijnh** [comment]
Oh, that's pretty bad. I've released 1.6.4 with a fix (only suppresses the fallback hack, not the default paste behavior)
