### ISSUE TITLE
How to exit code block when cursor at last

### ISSUE THREAD

**Issue by keelii** [ProseMirror/prosemirror#858]
### Issue details

The word `dolor` is last one in the paragraph with inline code mark, I want to jump out and couninue writing at the current paragraph.

```
-----cursor-------↓
Lorem ipsum `dolor` 
```

when move right, the cursor goes to the next paragraph, which is not the expected result
```
  Lorem ipsum `dolor` 
↓
```
just jump out the code mark maybe collect?
```
-------cursor-------↓
Lorem ipsum `dolor` 
```
here is a gif to show what I want

![test](https://user-images.githubusercontent.com/458894/46865723-1b454f00-ce51-11e8-86c2-e4e5cb36d92b.gif)

**Comment by marijnh** [comment]
> which is not the expected result

This is, however, the way the editor is designed. Each paragraph position has a single cursor position associated with, there is no separate place before and after the end of a given mark. In the default menu bar, the way to do this would be to move to the end of `amet` and press the code font button to disable that mark before continuing to type. You'll have to provide something like that in your interface — you could, I guess, even build keybinding that detects this case and uses something like [`removeStoredMark`](http://prosemirror.net/docs/ref/#state.Transaction.removeStoredMark) to clear the marks instead of letting the default behavior go through.

**Comment by keelii** [comment]
@marijnh Thanks for the reply, I finally solve this issue with a inputRule which works pretty fluent.

```js
function jumpOutMarks(type) {
    return new InputRule(/\s\s$/, (state, match, start, end) => {
        const {$cursor} = state.selection

        if (type.isInSet(state.storedMarks || $cursor.marks())) {
            let tr = state.tr.insertText('', $cursor.pos - 1, $cursor.pos)
            return tr.removeStoredMark(type)
        }
    })
}
```

**Comment by rudolfbyker** [comment]
@keelii  I'm struggling with the same thing, and I don't quite grasp how your solution works. Would you care to explain it?

**Comment by rudolfbyker** [comment]
I figured it out. Here's my documented version of @keelii 's function:

```js
/**
 * Create a rule that jumps out of the current mark when
 * two spaces are typed. This makes exiting a mark while staying in the same
 * paragraph very easy and fluent.
 *
 * Taken from https://github.com/ProseMirror/prosemirror/issues/858
 *
 * @param {MarkType} type
 *   The mark type to exit from.
 *
 * @returns {InputRule}
 *   A ProseMirror InputRule.
 */
export function jumpOutMarks(type) {
  // This regex matches on two consecutive whitespace characters
  // right before the cursor.
  return new InputRule(/\s\s$/, (state) => {
    const { $cursor } = state.selection;

    // If the given mark type is in the stored marks
    // (i.e. you would begin typing with that mark next)
    // or in the marks of the cursors current position, then remove it.
    if (type.isInSet(state.storedMarks || $cursor.marks())) {
      return (
        state.tr
          // Remove the spaces.
          .insertText("", $cursor.pos - 1, $cursor.pos)
          // Remove the mark, so that we type "outside" of it next.
          .removeStoredMark(type)
      );
    }
  });
}
```

Now I just need to figure out how to do the same for nodes.

**Comment by neongreen** [comment]
Btw, Remirror somehow does it. I haven't yet figured out how.
