### ISSUE TITLE
DropCursor breaking words causing cursor jumping

### ISSUE THREAD

**Issue by jemhuntr** [ProseMirror/prosemirror#859]
### Issue details

The drop cursor breaks a word in the middle, causing unwanted reflow+rewrapping, leading to cursor jumping and jittering.

### Steps to reproduce

1. https://prosemirror.net/examples/basic/
2. Drag a text over the paragraphs close to the left side before it wraps.

### Screenshots / Screencast (Optional)

https://jmp.sh/SDmIdkn

**Comment by marijnh** [comment]
It's not hard to do on top of [`coordsAtPos`](http://prosemirror.net/docs/ref/#view.EditorView.coordsAtPos). The plugin would get a plugin view and manage the cursor node from there.

**Comment by jemhuntr** [comment]
Looking at https://github.com/ProseMirror/prosemirror-dropcursor/blob/master/src/dropcursor.js, I might have some idea of how this could work. Do you need some manpower on this or is this something that still needs to be planned before working on?

**Comment by marijnh** [comment]
Thanks for offering to help! This was a bit subtle to get right, so I decided to go ahead and do an implementation myself in attached patch. Could you see if it works for you?

**Comment by jemhuntr** [comment]
Works much better for me with the fix :)

This also fixes a jumping issue when I hover somewhere in between lines in some cases. Thanks!
