### ISSUE TITLE
style menu "tooltips"

### ISSUE THREAD

**Issue by MegaBedder** [ProseMirror/prosemirror#86]
I wish instead to click on in tooltips,
the menu to overlap the mouse
pointer over the menu button to open.
I speak style menu "tooltips"

http://prosemirror.net/demo_basic.html

**Comment by marijnh** [comment]
If I understand you correctly, you want the floating button menu to open when the mouse hovers over the button.

The floating button menu is going away (it has already been deleted from the repository) -- people seem to not like it a lot, and I'm not enthusiastic about it myself. Instead, I'll have the tooltip block menu show up when you select a node (escape key), and optionally whenever your cursor is in an empty textblock.
