### ISSUE TITLE
Deleting the last character in a table cell causes odd behavior in Safari

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#862]
### Issue details

Seems like this issue is very similar to https://github.com/ProseMirror/prosemirror/issues/708, but this time it happens for tables. When I delete the last character in a table cell, Safari puts a `<br>` before the cell.

### ProseMirror version

prosemirror-view `1.6.4`

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari 12

### Screenshot

<img width="820" alt="screen shot 2018-10-26 at 1 48 36 pm" src="https://user-images.githubusercontent.com/26512812/47541694-eabbe580-d925-11e8-94b3-4c5f4e7789e5.png">

**Comment by marijnh** [comment]
Indeed, that seems a very similar issue, and I've kludged around it in a similar way in attached patch. Does that solve the problem for you?

**Comment by marijnh** [comment]
Great. Released as 1.6.5

**Comment by eshvedai** [comment]
I put a debugger inside `ruleFromNode` after the line 
`} else if (dom.nodeName == "BR" && dom.parentNode) {`:
 
<img width="385" alt="screen shot 2018-11-01 at 9 38 34 pm" src="https://user-images.githubusercontent.com/26512812/47847186-8ebdf900-de1e-11e8-84ac-2369cf056dfa.png">

it does return `{ignore: true}`, but then we end up with an empty cell without nested markup:
<img width="330" alt="screen shot 2018-11-01 at 9 47 02 pm" src="https://user-images.githubusercontent.com/26512812/47847568-bbbedb80-de1f-11e8-9b95-185642d5c20f.png">

Ideally the fix should not be tight to the DOM structure of the cell node view so that it'd give us the freedom to change it in the future 🤔

**Comment by marijnh** [comment]
You mean you'd like to preserve the cell node? That's tricky—if the browser deletes it, ProseMirror will assume it was intentionally removed. You could try binding a command that overrides backspace or delete in a situation like this, so that the browser behavior doesn't even occur, but that's a bit of an awkward kludge.

(Ideally, this'd get fixed in Safari, of course, but that might take a loooong time.)

**Comment by marijnh** [comment]
> current behaviour after the last fix is that when the last character is removed, the cell becomes empty (without a paragraph so that I can't put cursor inside).

That's odd. Does your schema allow such cells?

**Comment by eshvedai** [comment]
nope, here's the nodeSpec:
```
const cellAttrs = {
  colspan: { default: 1 },
  rowspan: { default: 1 },
  colwidth: { default: null },
  background: { default: null },
};

export const tableCell = {
  content:
    '(paragraph | panel | blockquote | orderedList | bulletList | rule | heading | codeBlock |  mediaGroup | mediaSingle | applicationCard | decisionList | taskList | blockCard | extension)+',
  attrs: cellAttrs,
  tableRole: 'cell',
  isolating: true,
  parseDOM: [
    {
      tag: 'td',
      getAttrs: (dom: HTMLElement) => getCellAttrs(dom),
    },
  ],
  toDOM(node) {
    return ['td', setCellAttrs(node), 0];
  },
};
```
I'll try to create a demo on pm-tables

**Comment by eshvedai** [comment]
Finally! `ignoreMutation` in cell node views caused this, now I'm checking MutationRecord and conditionally ignore mutation when needed and it works in Safari with your previous fix. Thanks a lot!

**Comment by marijnh** [comment]
Glad to hear!
