### ISSUE TITLE
ESM compatibility 

### ISSUE THREAD

**Issue by Gozala** [ProseMirror/prosemirror#863]
Hi,

I would like to use prose-mirror in the setting with native ES module support and without a build system. At the moment there are only two things in the current code base that prevent me from doing so:

1. Module imports don't include `.js` file extension and that causes loader to fetch URL without file extension and failing.
2. Modules across sub-projects are imported as `prosemirror-state` which in case of `prosemirror-view/src/index.js` would be `prosemirror-view/src/prosemirror-state`.

Addressing No 1. should be fairly easy and should have 0 impact on the way things are setup across repos toady.

Addressing No 2 is more difficult & I don't have any good solution to offer. One would be to just assume that all the transitive dependencies are contained in a same root, which I believe in most cases is true and will be `node_modules` in which case changing imports from `prosemirror-state` to `../../prosemirror-state/src/index.js` would probably work, but I do understand that does not look so great.

My question is would you be willing to accept any patches to improve compatibility with native ES modules ? If so I'd happily submit ones to address No 1, as that would allow me to get away without source modifications, using a tool that would arrange all modules so they'd resolve appropriately.

If there is a chance to also address No 2 I would be happy to drive the work to making it happen.

Thanks

**Comment by marijnh** [comment]
No. As long as it's unclear how node is going to support ES modules, and proposals that would make them usable in the browser aren't far enough along to know where they are going, I feel it is too easy to try and adjust the code to a reality that we can't really predict yet. You'll have to use some intermediate tool for the time being.
