### ISSUE TITLE
Pasting HTML from Firefox into ProseMirror in any browser adds extra spaces

### ISSUE THREAD

**Issue by RichieAHB** [ProseMirror/prosemirror#865]
### Issue details

Copying test from Firefox into ProseMirror (tested into Firefox and Chrome) results in double / triple spaces appearing throughout the text. HTML will collapse these when we render the document for consumption but it's proving to be a bit of a pain even when editing. At first I thought it may be to do with #861 but I'm pretty sure it isn't given it's looking for explicit `br` tags.

I've done a tiny bit of investigation since and it seems to be down to `preserveWhitespace` in the default dom parsing strategy for pasting - the double / triple spaces seem to occur where the HTML inside `getData(text/html)` is arbitrarily breaking. I'm not quite sure why this is different between FF and Chrome, especially given that when I've compared the `clipboardData` between them the only difference between the two is that Chrome seems to wrap it's clipboard content with:

```html
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body>...</body></html>
```

It's not a huge issue and, when I get time, I can fix this in other ways but I thought it was worthy of note.

### Steps to reproduce

https://remarkable-blade.glitch.me/

Copy the document below the editor and paste it into the editor.

### ProseMirror version

Versions in the `glitch` setup

### Affected platforms

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Firefox often adds random newlines to clipboard content, which ProseMirror will convert to spaces when preserving whitespace. This seems related to #842. How are you copying the content? Could you take a look to see why the workaround introduced in that issue isn't helping?

**Comment by RichieAHB** [comment]
It looks exactly the same, apologies for missing that - will investigate.

**Comment by RichieAHB** [comment]
I upgraded both `prosemirror-model` and `prosemirror-view` to `1.6.3`, where as `view` needed to be at `1.6.5` 🙄
