### ISSUE TITLE
Down arrow not handled when selection is before inline node in Chrome

### ISSUE THREAD

**Issue by jordoh** [ProseMirror/prosemirror#867]
### Issue details

When the cursor is before an inline node that is at the beginning of the containing node, pressing the down arrow does not move the selection down. The key input appears to be unhandled by ProseMirror: if the page is long enough for a scrollbar, it will scroll down.

I've only observed this in Chrome, Firefox works as expected.

### Steps to reproduce

1. Visit [Dinos in the document](http://prosemirror.net/examples/dino/) demo.
2. Delete everything on the second line, up to the first dino node, ensuring cursor is immediately before the dino node:
![image](https://user-images.githubusercontent.com/450345/48099067-49f5e180-e1d3-11e8-83f9-18ae946d44d3.png)
3. Press down arrow key.

Observe that the page scrolls down and the ProseMirror selection does not change.

The editor also _appears_ to be un-focused, as typing text will not insert it in the document and the cursor is no longer rendered, but pressing the up arrow key does move the cursor up as if it had been before the dino node.

Using any other arrow key on step 3 works as expected.

Note that any text content in the paragraph node before the inline node will result in the expected cursor behavior. The cursor also renders slightly differently (it's shorter) when there is text content before the inline node:

![image](https://user-images.githubusercontent.com/450345/48099488-8b3ac100-e1d4-11e8-94dc-3fc053cff858.png)

### ProseMirror version

prosemirror-view 1.6.4

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

Tested on Chromium 68.0.3440.106 on Linux and Firefox 61.0.2

**Comment by marijnh** [comment]
This appears to be a Chrome bug—I can reproduce it in a similar page with a non-ProseMirror editable element. The editable element loses focus and the page scrolls down when you press arrow-down in that case.

I guess we'll have to add custom logic in `view/src/capturekeys.js` to detect and handle the situation, but that's unfortunate since simulating vertical motion is tricky.

Do you have time to test whether this was introduced in a recent Chrome version or has been around forever? And maybe submit a bug report on the Chrome issue tracker and hope that they fix it soon so that we don't have to keep our kludge around.

**Comment by jordoh** [comment]
I'll take some time today to look into when it was introduced in Chrome. I can submit an issue for Chrome if that would help - I'm guessing the non-ProseMirror reproduction is something like this?
```html
<div contentEditable>
  <p>text</p>
  <p><img ... /></p>
  <p>text</p>
</div>
```

**Comment by marijnh** [comment]
I needed some stuff below the editable div as well for it to reproduce, haven't dug down deeply.

**Comment by jordoh** [comment]
It looks like this one has existed for quite a while - I went as far back as Chrome 37 (on Windows 10) and found the same behavior. Also verified in Chrome 71 (beta) and 72 (dev).

**Comment by marijnh** [comment]
Okay, thanks for digging into that. I've reported this as https://bugs.chromium.org/p/chromium/issues/detail?id=903821 . Will take a look to see if it's hard to work around.

**Comment by marijnh** [comment]
Does attached patch help for you?

**Comment by jordoh** [comment]
I can confirm that patch fixes the issue in my application. Thanks!
