### ISSUE TITLE
Selected nodes with 'draggable=false` in Firefox causes weird selection issues

### ISSUE THREAD

**Issue by RichieAHB** [ProseMirror/prosemirror#868]
### Issue details

Creating a node selection in a `p` tag (with Cmd-click) then immediately putting a cursor selection inside that `p` tag leaves `draggable=false` as an attribute on it. I can't seem to recreate the bug we're facing but this `draggable=false` is causing weird selection behaviour around that tag after it is added until refreshing the page.

This doesn't _seem_ to cause issue that I can replicate in vanilla PM (although others may know otherwise) but if I remove the `draggable=false` manually in the inspector in our app, then it fixes the issue.

Interested to hear if others have seen this.

### Steps to reproduce

Go to http://prosemirror.net
- Cmd-click a line
- Immediately make a cursor position in that line
- Inspect the dom and spy the `draggable=false`

### ProseMirror version

The one on prosemirror.net

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Weird, but not hard to avoid I guess. Attached patch makes sure the entire attributes are removed.
