### ISSUE TITLE
export wrap function of serializer

### ISSUE THREAD

**Issue by johanneswilm** [ProseMirror/prosemirror#87]
It seems to me that exporting the wrap function from src/serialize/dom is quite useful. That allows me to do things such as:

```
FootnoteContainer.prototype.serializeDOM = (node, options) => {
  let dom = wrap(node, options, "div")
  dom.setAttribute("class", 'footnote-container')
  return dom
}
```

But maybe there is another recommended way of doing this (without copying large amounts of code)?

**Comment by marijnh** [comment]
Agreed. The HTML parser, as it is, wasn't really designed to be a public API and I'll clean it up at some point, I'll try to do that soon.

**Comment by marijnh** [comment]
I've overhauled this [interface](http://prosemirror.net/doc/manual.html#DOMSerializer) yesterday. It should be cleaner now.
