### ISSUE TITLE
How to truly make a Node selectable: false?

### ISSUE THREAD

**Issue by nodegin** [ProseMirror/prosemirror#870]
### Issue details & Steps to reproduce

Type some text, insert an image, press arrow left
And the selection focus will stuck within the image
Unless you press arrow left multiple times..

I have already tried all possible spec, like `selectable`, `atom`, `isolating`, etc.
But nothing worked for me. Thanks

![out](https://user-images.githubusercontent.com/8536244/48485419-b9af4080-e853-11e8-96a4-8e86d0531134.gif)

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Other

**Comment by marijnh** [comment]
It looks a bit like you're missing the styles from `prosemirror.css` in `prosemirror-view`, and the image is being selected but you can't see it. That being said, adding `selectable: false` to the image's node spec should turn off the node selection behavior, so I suspect something is going wrong in how you create the schema.

**Comment by nodegin** [comment]
@marijnh I am not sure if the issue is come with CSS or not, but my image is definitely visible, you can see it the green slick icon from my GIF. My scheme is copied from ProseMirror's repo, just added the `selectable` option as false. I will test tomorrow and see if `prosemirror.css` does matter or not, thanks anyway.

**Comment by marijnh** [comment]
I meant the selection isn't visible—see the blue outline you get on the website when you arrow over an image node.

**Comment by nodegin** [comment]
Oh, I see. The blur outline is not visible because I was set the `selectable` option to `false`, if I unset this option the blue outline will appear in Chrome.

**Comment by nodegin** [comment]
BTW, I took a look into `prosemirror.css` I believe adding the CSS will not fix the issue, since the issue most likely a bug where PM is still performing something in selection behavior even `selectable` is set to false.

**Comment by nodegin** [comment]
@marijnh I tried import the `prosemirror.css` from `prosemirror-view` package but the problem is still there, any idea how can I get rid of this issue?

**Comment by marijnh** [comment]
If I update the basic demo to add `selectable: false` to image nodes, the cursor cleanly skips them. So you could try to figure out what's different in your setup.

**Comment by nodegin** [comment]
@marijnh Can you share your basic demo repo please?

**Comment by nodegin** [comment]
This is my spec, which copied from `prosemirror-schema-basic` repo

```js

// https://github.com/ProseMirror/prosemirror-schema-basic/blob/master/src/schema-basic.js
const nodes = {
  doc: {
    content: 'block+',
  },
  text: {
    group: 'inline',
  },
  paragraph: {
    content: 'inline*',
    group: 'block',
    parseDOM: [{
      tag: 'p',
    }],
    toDOM() {
      return ['p', 0]
    },
  },
  image: {
    inline: true,
    attrs: {
      src: {},
      alt: { default: null },
    },
    group: 'inline',
    draggable: true,
    selectable: false,
    parseDOM: [{
      tag: 'img[src]',
      getAttrs(dom) {
        return {
          src: dom.getAttribute('src'),
          alt: dom.getAttribute('alt'),
        }
      },
    }],
    toDOM(node) {
      return ['img', node.attrs]
    },
  },
}
```

**Comment by marijnh** [comment]
That looks correct. What I did was update the schema in `demo/demo.js` in the [dev repository](https://github.com/prosemirror/prosemirror) to this:

```
const demoSchema = new Schema({
  nodes: addListNodes(schema.spec.nodes, "paragraph block*", "block")
    .update("image", Object.assign({selectable: false}, schema.spec.nodes.get("image"))),
  marks: schema.spec.marks
})
```

**Comment by marijnh** [comment]
I can reproduce the problem in Chrome, not Firefox, so I was thrown off by your initial report claiming that it happened on all browsers.

But indeed, this does appear to be an issue—I'll leave this open and try to figure out a workaround when I have time.

**Comment by nodegin** [comment]
Oh sorry, I was thinking this should be a cross-browser issue, didn't expect it's a webkit-only issue.

**Comment by marijnh** [comment]
Doesn't appear to be happening anymore.
