### ISSUE TITLE
parseSlice does not check parseRules context to find wrapping

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#875]
The schema has two block nodes for paragraphs (in that order):
1. one that does not allow anchors in content (call it `pn`)
2. one that does (call it `pl`)

It has also two kinds of `div` blocks, likewise, one can contain `pn`, the other `pl`, let's call them `divn` and `divl`.
The parseRule of `pn` has `context: "divn//"`
The parseRule of `pl` has no specific context set.

If i ask the view parser to parse this dom node:
```
<div class="allow-links">test</div>
```
- the parser will first correctly parse the top node as a `div allowing links`
- then it will try to wrap the text node `test` (addTextNode > insertNode > findPlace > findWrapping)
- however it does not consider the context at that point, and finds `pn` for wrapping the text node.

What was expected ? That it finds `pl` for wrapping the text node.

Using prosemirror-view 1.6.6 and prosemirror-model 1.6.3.

**Comment by marijnh** [comment]
`findWrapping` _does_ take the current content match into account when finding a set of wrapping nodes, and as such should handle this. Could you set up a minimal demo that shows the problem?

**Comment by kapouer** [comment]
Sure ! The console logs what i expect and what i got here:
https://decisive-prince.glitch.me/

**Comment by kapouer** [comment]
`findWrapping` for the `text` nodeType returns the first candidate able to contain text all right,
however here it happens that the first candidate has a parseRule's context that forbids it to be inserted in the actual parent type of the target containing the text to be wrapped.

In my setup i have two types of paragraphs (one allowing links marks, and the other must have a `blocklink//` context). If i try to paste some link, the right paragraph type is selected by `findWrapping`. If i just type some text, the selected type of paragraph depends on the order of declaration, but none of the target parent nodes type is `blocklink`.

**Comment by marijnh** [comment]
>  the first candidate has a parseRule's context that forbids it to be inserted in the actual parent type of the target

Parse rule contexts only apply when matching a DOM node to a parse rule, and don't say anything about whether a given _node type_ can appear somewhere.

It sounds like you want an actual content constraint. Those can only be specified for direct children, so this might involve adding different intermediate node types.

**Comment by kapouer** [comment]
Yes, unfortunately... i understand it would require a hell of a lot more work to achieve what i tried to do.
I'm dropping that usage now, reverting to a safer explicit typing not based on using "context//".
