### ISSUE TITLE
HtmlSelectElement doesn't work on Chrome and Firefox

### ISSUE THREAD

**Issue by patrick8675** [ProseMirror/prosemirror#877]
### Issue details

In Firefox when clicking on a select the dropdownmenu doesn't open.
In Chrome after clicking on an option in the dropdownmenu the select resets to the first option.

### Steps to reproduce

https://glitch.com/edit/#!/full-crayon

### ProseMirror version

Latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
The editor is handling the mousedown event. To embed form fields in an editor, the recommended approach to create node views for them and use [`stopEvent`](http://prosemirror.net/docs/ref/#view.NodeView.stopEvent) to control which events are local to the node.
