### ISSUE TITLE
getPos() sometimes returns NaN when called on a CustomNodeView

### ISSUE THREAD

**Issue by fredguile** [ProseMirror/prosemirror#879]
### Issue details

Hi, may I ask if `NaN` is an accepted return value of Nodeviews' `getPos()` function?

We recently faced a bug in the [Atlaskit Editor](https://atlaskit.atlassian.com/packages/editor/editor-core) where `NaN` values were passed to a `doc.resolve(NaN)` throwing a `RangeError: Position NaN out of range` (as we only tested that the returned value was a defined number).

### Steps to reproduce

It's quite hard to reproduce as we did a lot of customisations to our editor, but the path is basically:

1. viewdesc.js line 551 - this constructor gets called:
`new CustomNodeViewDesc(parent, node, outerDeco, innerDeco, dom, contentDOM, nodeDOM, spec, view)`

2. viewdesc.js line 508 - NodeViewDesc's contructor is invoked with an undefined `pos` parameter:

```
constructor(parent, node, outerDeco, innerDeco, dom, contentDOM, nodeDOM, view, pos) {
    super(parent, node.isLeaf ? nothing : [], dom, contentDOM)
    this.nodeDOM = nodeDOM
    this.node = node
    this.outerDeco = outerDeco
    this.innerDeco = innerDeco
    if (contentDOM) this.updateChildren(view, pos)
  }
```

3. as `contentDOM` is defined, `this.updateChildren()` gets called with undefined `pos`

4. viewdesc.js line 585 - for some reasons within `updateChildren()` `pos` is now equal to `NaN`

5. viewdesc.js line 604 - this gets called with `pos` equal to `NaN`:
`updater.addNode(child, outerDeco, innerDeco, view, pos)`
 
Later on, we synchronously call `getPos()` which returns `NaN`. Of course we now test that this value is correct, but I'm wondering if there isn't something on this commit:
https://github.com/ProseMirror/prosemirror-view/commit/fdf9a0874ab95f4784fb2539937664175971d5b9#diff-b74286c36b45a2cac4dd362fad966cac

This might be a naive analysis, but wouldn't it be better to pass `pos` when creating the  `CustomNodeViewDesc` on line 546?

### ProseMirror version

prosemirror-collab@1.0.0
prosemirror-commands@1.0.7
prosemirror-dev-tools@2.1.0
prosemirror-history@1.0.2
prosemirror-inputrules@1.0.1
prosemirror-keymap@1.0.1
prosemirror-markdown@1.2.0
prosemirror-model@1.6.1
prosemirror-schema-list@1.0.0
prosemirror-state@1.2.2
prosemirror-tables@0.7.10
prosemirror-transform@1.1.3
prosemirror-utils@0.7.2
prosemirror-view@1.6.7

### Affected platforms

- [ x] All

**Comment by marijnh** [comment]
Yes, that was a bug, not intentional behavior. Thanks for diagnosing it. Attached patch should fix it.
