### ISSUE TITLE
Handling IME events does not work well on MacOS Safari

### ISSUE THREAD

**Issue by murata0705** [ProseMirror/prosemirror#880]
When IME user input and start new line, type `Enter` two times.
Almost all browser like Chrome, Firefox, Safari on iOS and Edge work expectedly but only Safari on MacOS does work well.
Safari on MacOS choose word and inert new line same time.

Chrome(good)
![chrome](https://user-images.githubusercontent.com/8707452/50754519-595bde80-1299-11e9-9fb7-9a03a3ae60a0.gif)

Safari(bad)
![safari](https://user-images.githubusercontent.com/8707452/50755486-8493fd00-129c-11e9-9ccd-b82161f6f26c.gif)

I think the reason is explained here [Handling IME events in JavaScript – Not Rocket Science](https://www.stum.de/2016/06/24/handling-ime-events-in-javascript/).
After changing code like below, worked on MacOS Safari too.

```js
// prosemirror-view/src/domchange.js:86

compositionEnd() {
  if (this.composing) {
    this.composing = false
    this.compositionJustEnded = true // add new code
    this.timeout = setTimeout(() => this.finish(), 50)
  }
}
```

```js
// prosemirror-view/src/input.js:73

editHandlers.keydown = (view, event) => {
  view.shiftKey = event.keyCode == 16 || event.shiftKey
  if (view.inDOMChange) {

    // if (view.inDOMChange.composing) return

    if (view.inDOMChange.composing || view.inDOMChange.compositionJustEnded) {
      view.inDOMChange.compositionJustEnded = false
      return
    }
    view.inDOMChange.finish()
  }
```

Please check them when you have time. Thank you.

**Comment by marijnh** [comment]
Ah, so it's firing key events that were part of the composition _after_ the `compositionend` event? That's terrible, but so it goes. Thank you for debugging this!

I see one potential issue -- when no key event is fired as part of the end of the composition, but another key happens to be pressed directly after it, it might incorrectly get stopped here. Have you looked at the event [timestamps](https://developer.mozilla.org/en-US/docs/Web/API/Event/timeStamp) that are assigned to the keydown and compositionend events? If those are always the same, or only a few ms apart, maybe we can store `compositionEndedAt` in the DOMChange object, and block key events that are too close to it.

**Comment by murata0705** [comment]
Thanks for explanation, I check more details.

**Comment by kevinzang** [comment]
@marijnh 

> when no key event is fired as part of the end of the composition, but another key happens to be pressed directly after it, it might incorrectly get stopped here.

I tested this case with @murata0705 's fix. I used my mouse rather than the Enter key to confirm Kanji selection. Things still work as expected because `forceDOMFlush` is called on mousedown, which sets `this.view.inDOMChange = null;`, so we don't enter the `if (view.inDOMChange)` condition in the keydown handler.

forceDOMFlush is also called on touchdown and contextmenu. I can't think of a way that the user could end the composition without the code resetting `view.inDOMChange`. Do you still think we should implement `compositionEndedAt`?

Aside from this one case, I've also tested @murata0705 's fix in general, and I confirm that it works.

**Comment by marijnh** [comment]
I'd still feel more confident if we could use timestamps to make sure the key-blocking effect has a limited lifetime.

**Comment by kevinzang** [comment]
OK, I've implemented solution with `compositionEndedAt` here: https://github.com/ProseMirror/prosemirror-view/pull/44.

**Comment by marijnh** [comment]
Fixed in https://github.com/ProseMirror/prosemirror-view/pull/44
