### ISSUE TITLE
Drag and drop image opens file in Chrome

### ISSUE THREAD

**Issue by EBichel** [ProseMirror/prosemirror#881]
### Issue details

Drag and dropping an image from filesystem opens the image in Chrome instead of inserting it into the editor. Works fine with Firefox. As a workaround I tried the approach from: https://stackoverflow.com/questions/6756583/prevent-browser-from-loading-a-drag-and-dropped-file
However, that doesn't help. Any ideas on what may cause the problem?

### Steps to reproduce

Drag and drop image from filesystem to editor in https://prosemirror.net/examples/upload/

### Affected platforms

- [x] Chrome (Linux)

**Comment by hubgit** [comment]
It looks like there's nothing in ProseMirror handling drag-and-drop of external files in https://prosemirror.net/examples/upload/ - it's just Firefox's implementation of contenteditable that inserts dropped images into the editable content. 

To handle dropped images properly across all browsers you'll probably want to add a [`handleDrop`](https://prosemirror.net/docs/ref/#view.EditorProps.handleDrop) method to the editor.

**Comment by marijnh** [comment]
Yes, I think @hubgit described the issue correctly—ProseMirror's core doesn't know how to handle file uploads/drops, so it doesn't, and you'll have to add custom code for them.
