### ISSUE TITLE
Children in a list item get deleted after enter

### ISSUE THREAD

**Issue by samu** [ProseMirror/prosemirror#886]
### Issue details
Children in a list item get deleted after enter

### Steps to reproduce
https://fallacious-harbor.glitch.me

1. Place cursor on list item after _two_
2. Press enter

The child node _three_ gets deleted. I wonder if this is intended. I'm surprised by the behavior - i would expect a new empty list item to be created.

### ProseMirror version
Versions that are available via the examples.

**Comment by marijnh** [comment]
No, that's not intended. Looks like a problem in the `liftEmptyBlock` command.

**Comment by katepol** [comment]
@marijnh when do you plan to take a look on this issue?

**Comment by marijnh** [comment]
[This patch](https://github.com/ProseMirror/prosemirror-schema-list/commit/5a4c91221eba4c7806b84bce55781b0bbe9e9379) should help with this.
