### ISSUE TITLE
EditorView.destroy() clears dom for mounted, in-place editors

### ISSUE THREAD

**Issue by jrkoenig** [ProseMirror/prosemirror#887]
### Issue details

When a editor is 'mounted' on the same node as the document state (i.e. in place editing of a DOM node), `EditorView.destroy()` clears the edited DOM node rather than leaving the dom nodes in place.

### Steps to reproduce

```javascript
let state = EditorState.create({
   doc: DOMParser.fromSchema(mySchema).parse(domNode),  // <- same node
   plugins: ...
})
let view = new EditorView({mount: domNode},  // <- same node
               {state: state})
```

### ProseMirror version

`prosemirror-view@1.6.8`

### Affected platforms

All

### Fix

In `prosemirror-view/src/index.js` add a new condition for clearing the dom node:

```javascript
class EditorView {
  ...
  destroy() {
    ...
    if (this.mounted) {
          this.docView.update(this.state.doc, [], viewDecorations(this), this)
          // if they are the same then clearing content will undo the docView.update
          if (this.dom !== this.docView.contentDOM) // <- NEW
            this.dom.textContent = ""
    }
```

It's not clear which of the several dom properties on docView should be compared -- in my example all of `.dom`, `.contentDOM` and `.nodeDOM` refer to the same node.

**Comment by marijnh** [comment]
`this.dom` is always equal to `this.docView.contentDOM`. In general, leaving the editor's DOM around isn't a good idea—it's not the original plain content, it's an editable representation thereof, with node views and various hacks related to editing applied. After you've mounted an editor in a node, that node's content get replaced by the editor DOM, and the old content is gone. If you want it back, either store it somewhere, or re-serialize the new document with `DOMSerializer` to recreate it as plain HTML content.
