### ISSUE TITLE
[prosemirror-schema-list] `sinkListItem` copying block marks from parent

### ISSUE THREAD

**Issue by torifat** [ProseMirror/prosemirror#889]
I have a list with block marks with two children. Like the following:

```
ol [some-block-mark]
  li one
  li two
```

When I try to indent `two`, it invokes the `sinkListItem`. Which tries to copy the block mark from the `parent` to create the nested `list` https://github.com/ProseMirror/prosemirror-schema-list/blob/master/src/schema-list.js#L222. And, I get the following error:

```
Uncaught Error: Invalid content for node listItem
    at new TransformError (index.js:301)
    at Transaction.step (index.js:341)
    at schema-list.js:234
```

Is there any workaround for this?

**Comment by marijnh** [comment]
You could allow the block mark in list items, or you could update `sinkListItem` to create a node without marks (`parent.type.create(parent.attrs, inner)` instead of `parent.copy(inner)`) and submit a PR

**Comment by torifat** [comment]
I will submit a PR soon. Wasn't sure if you are ok with the change or not. Thanks.
