### ISSUE TITLE
ESC on Safari deletes selected block

### ISSUE THREAD

**Issue by rsaccon** [ProseMirror/prosemirror#89]
on Safari I observed the following behavior when pressing ESC:

On first ESC, the parent block gets outlined (as in Chrome). I assume this and only this is the expected behaviour.

On second ESC, the outlined block gets removed.

On any subsequent ESC, the preceding block gets removed.

**Comment by marijnh** [comment]
Oh, that is bad. I don't have access to Safari right now, but I think that attached patch will help. Could you try it?

**Comment by rsaccon** [comment]
YES, thanks, that helped, now it behaves as expected.
