### ISSUE TITLE
How to serialize a Transaction?

### ISSUE THREAD

**Issue by trungdq88** [ProseMirror/prosemirror#890]
I see there is no `.toJSON()` in Transaction, is this by design or we haven't implement it yet?

I am having a use case where I need to persist the [CollabState](https://github.com/trungdq88/prosemirror-collab/blob/master/src/collab.js#L34) to local storage, which contains `Transaction` instances.

**Comment by marijnh** [comment]
This is by design — things like metadata fields can contain arbitrary (non-serializeable) values, so there's no reasonable way to reliably serialize `Transaction` objects.

It might be reasonable to write `toJSON`/`fromJSON` functions for the collab state that don't serialize the transactions (treating all the pending changes as having come from a single, plain transaction after deserializing).

**Comment by trungdq88** [comment]
CollabState has a `unconfirmed` which is an array of `Rebaseable`, the `Transaction` is the `origin` property.

```ruby
class Rebaseable {
  constructor(step, inverted, origin) {
    this.step = step
    this.inverted = inverted
    this.origin = origin
  }
}
```

If I only serialize the `step` and `inverted` property, will it loss other information when I deserialize from localStorage?

The use case I'm trying to cover is offline editing, if there is unconfirmed steps and user exit app, I want to restore the unconfirmed steps so that it can be rebased after reconnect.

**Comment by marijnh** [comment]
> If I only serialize the step and inverted property, will it loss other information when I deserialize from localStorage?

Technically yes, code looking at the origin transaction when sending steps to the server might miss information there. But you probably don't have such code, and if we end up integrating something like this into the prosemirror-collab distribution, we'd have to add a disclaimer that, after deserializing, the origin transaction might be a generic one.

>  if there is unconfirmed steps and user exit app, I want to restore the unconfirmed steps so that it can be rebased after reconnect.

You could also just serialize the steps, and replay them when deserializing.

**Comment by trungdq88** [comment]
> You could also just serialize the steps, and replay them when deserializing.

If so I also need to keep track of the "confirmed `doc`", so I can replay the serialized steps on it and get to the previous state, right?

**Comment by trungdq88** [comment]
Thank you!
