### ISSUE TITLE
Uncaught exception when deleting characters from within Android WebView

### ISSUE THREAD

**Issue by fredguile** [ProseMirror/prosemirror#891]
### Issue details

Hi, I'm working on a bug in our editor regarding jumping cursor position when deleting characters from within an Android WebView. 

I know there's an [historical issue](https://discuss.prosemirror.net/t/ime-composition-and-flushing-the-dom/1756) regarding composition events with ProseMirror, but for now I'd like to focus on an uncaught exception that I'm getting when deleting a character in some conditions:

```
Uncaught RangeError: Position 0 out of range
    at Function.resolve (index.js?437d:945)
    at Node.resolveNoCache (index.js?437d:1241)
    at readDOMChange (domchange.js?0d7e:282)
    at DOMChange.finish (domchange.js?0d7e:73)
    at editHandlers.input (input.js?18b8:376)
```

As the stack trace suggests, it starts from an InputEvent of type `deleteContentBackward` (`composed` is true):
- in the event handler  `DOMChange.start(view)` is called and then `change.finish()`,
- `finish()` is calling `readDOMChange()`,
- `readDOMChange()` is calling `parseBetween()`,
- inside this method, `parser.parse()` is getting called passing the DOM, but it returns a node **whose `content.size` equals NaN**, despite it contains fragments.
- Later on, this NaN size is an issue for `findDiff()` which stores NaN into `change.endB` and make the call to `resolveNoCache()` to fail with an uncaught exception.

Any idea why is the parser returning `content.size=NaN`?

I suspect this lead to having invalid cursor positions, I don't know if that's linked to composition events. 

### ProseMirror version

prosemirror-view 1.7.1
prosemirror-model 1.7.0
prosemirror-state 1.2.2

### Affected platforms

- [X] Chrome
- [X] Android WebView

### Screencast

![deleting-node](https://user-images.githubusercontent.com/209813/52321274-0906a680-2a28-11e9-8c53-371eed159714.gif)

**Comment by marijnh** [comment]
Can you reproduce this in a regular browser? Also in the demos on the website? If so, what are the steps I have to take to see it?

**Comment by jljorgenson18** [comment]
Android Web Views in Android Apps tend to have issues with the backspace key not being registered as an actual backspace key. I would guess this is specific to the Android app.

**Comment by marijnh** [comment]
That sounds like something Chrome Android does in general (same with enter and delete)

**Comment by jhnsnc** [comment]
Any ideas on how to implement special delete/backspace handlers in the absence of a delete/backspace signal (like in Android webviews) would be greatly appreciated.

The only approach we have so far is putting "canaries" (hidden landmark characters) around structures in the document to recognize when a delete happens so we can undo the change and handle it differently. But this approach gets quite messy and I would like to find a more elegant solution.

**Comment by marijnh** [comment]
ProseMirror has some really hacky code that looks at modifications read from the DOM, and if they look like they were the effect of backspace or enter, calls key handlers for those keys. See [this code](https://github.com/ProseMirror/prosemirror-view/blob/master/src/domchange.js#L285).

**Comment by fredguile** [comment]
Hey guys, sorry for the delay. And I've found what caused the issue. No worries that's on my side: I'm currently using a branch of `prosemirror-view` and it wasn't correctly linked with `prosemirror-model`, basically leading to this symptom:

Taking from the above stacktrace, it goes through:
- from_dom.js::parse()
- from_dom.js::finish() (l. 576)
- from_dom.js::finish() (l. 322)
- schema.js::create()
- fragment.js:from()

```
static from(nodes) {
  if (!nodes) return Fragment.empty
  if (nodes instanceof Fragment) return nodes
  if (Array.isArray(nodes)) return this.fromArray(nodes)
  return new Fragment([nodes], nodes.nodeSize)
}
```

As the `instanceof` operator is returning false (because of my linking issue), it eventually creates a new Fragment passing an undefined as second argument (size). Which turns up as a NaN because of the code in the constructor:

```
 constructor(content, size) {
    this.content = content
    // :: number
    // The size of the fragment, which is the total of the size of its
    // content nodes.
    this.size = size || 0
    if (size == null) for (let i = 0; i < content.length; i++)
      this.size += content[i].nodeSize
  }
``` 

Nothing wrong there but I'd sugggest adding a 3rd equal to `if (size == null)`, otherwise the for loop will run even when size is undefined, turning it into a NaN.

Asides... happy that it led to some interesting discussion!

**Comment by marijnh** [comment]
Thanks for reporting back. That issue (having multiple versions of a module loaded at once) has come up before, but it seems hard to guard against. There's 62 uses of `instanceof` in the codebase, and I don't really want to complicate all of them to try and behave properly when faced with this issue.

**Comment by adrianheine** [comment]
Argh, package managers :(

**Comment by fredguile** [comment]
@marijnh agree, but you could guard against the destructive for-loop in the case size is undefined!

**Comment by marijnh** [comment]
Right, the `Fragment.from` issue seems to be the place where most people run into this. Attached patch makes it raise a more helpful error.
