### ISSUE TITLE
Whitespaces are not preserving in DOMParser

### ISSUE THREAD

**Issue by nodegin** [ProseMirror/prosemirror#893]
### Issue details

Whitespaces are all gone when parsed using `DOMParser.parse`

Even using either `&nbsp;` or `preserveWhiteSpace` option.

### Steps to reproduce

```js
const testParser = DOMParser.fromSchema(schema)
const node = document.createElement('div')
const para = document.createElement('p')
para.innerHTML = '&nbsp;&nbsp;test'
node.appendChild(para)
console.log(testParser.parse(node, { preserveWhiteSpace: true }))
```

### ProseMirror version

latest

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![screen shot 2019-02-20 at 3 59 03 pm](https://user-images.githubusercontent.com/8536244/53075612-99fd7780-3528-11e9-90d1-1b33203073e6.png)

**Comment by nickolNN** [comment]
Facing the same issue, tried preserveWhitespace: (true/'full') in parseOptions, but nothing works :(

**Comment by marijnh** [comment]
```
console.log(testParser.parse(node, { preserveWhiteSpace: true }))
```

The `s` in the option name should not be capitalized: `preserveWhitespace`
