### ISSUE TITLE
Bold, Italics keyboard shortcuts doesn't work on Windows & Linux (Chrome + Mozilla), when Caps Lock is turned ON

### ISSUE THREAD

**Issue by Dinesh1902** [ProseMirror/prosemirror#895]
### Issue details

Keyboard shortcuts for formatting will stop working, when the CAPSLOCK key is ON - for Windows 10 & Linux (Ubuntu) (Chrome + Firefox)

### Steps to reproduce

On a Windows PC or l atest Ubuntu [visit](https://darkened-trunk.glitch.me/) the demo with Chrome (mine's on version 72.0.3626.109 64 bit) browser. Also reproducible in Firefox. Works fine in IE & Edge.

### ProseMirror version

Latest Version

#### OS
- [x] Windows
- [ ] Mac
- [x] Linux

#### Browser
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

### Current Workaround

When binding keys I bind bold & italics for both Uppercase & Lowercase.
```
if (type = schema.marks.strong) {
  bind("Mod-B", toggleMark(type))
  bind("Mod-b", toggleMark(type))
}
```

**Comment by marijnh** [comment]
That's a reasonable workaround. Due to the way key bindings work (they distinguish between b and B presses), this can't reasonably be handled automatically.

The core libraries don't bind anything to mod-b/mod-i, but I've added the uppercase bindings to prosemirror-example-setup in attached patch.
