### ISSUE TITLE
Infinte loop in elementFromPoint

### ISSUE THREAD

**Issue by mk** [ProseMirror/prosemirror#896]
### Issue details
We've upgraded to prosemirror-view 1.8.0 and our call to `posAtCoords` can freeze Chrome. When going back to a version before https://github.com/ProseMirror/prosemirror-view/commit/6a54ef6da8516258adc5a83a8c2c999175f21fe1 the issue doesn't occur.

By adding a global break to the loop and logging, we can see that it happens for the following values:
```javascript
startI = 0, len = 1, i = 0, child.nodeType = 3
```
If we change https://github.com/ProseMirror/prosemirror-view/blob/6a54ef6da8516258adc5a83a8c2c999175f21fe1/src/domcoords.js#L177 to
```javascript
if (child.nodeType == 1 || child.nodeType == 3) {
```

the problem goes away but we're not sure this is the proper fix.

### Steps to reproduce
Hard to share a minimal reproduction for this case but it's probably related to us having nodes of type text as the root in our schema.

### ProseMirror version
prosemirrror-view 1.8.0

### Affected platforms
- [x] Chrome 72.0
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Oh, right, I had one statement inside of the `if` that should be below it. Attached patch should address it (and another potential issue when the element has zero height).

**Comment by mk** [comment]
Can confirm this fixes our issue, thank you!
