### ISSUE TITLE
Cannot set CellSelection via clicking on table controls 

### ISSUE THREAD

**Issue by eshvedai** [ProseMirror/prosemirror#897]
Hello,

In our editor we render control buttons around the table node via nodeView, clicking on controls should create CellSelection.

It seems like [this](https://github.com/ProseMirror/prosemirror-view/commit/33fe4a8b01584f6b4103c279033dcd33e8047b95) fix resets selection in Chrome:

![column-selection](https://user-images.githubusercontent.com/26512812/53707570-a4523680-3e83-11e9-9381-c8aa44bb627f.gif)

Would you consider adding a fix in `prosemirror-view` to handle CellSelection? We've been using `handleClick` and returning `true` when clicking on table controls to workaround that. 

### ProseMirror version

`prosemirror-view`: `1.3.0`

### Affected platforms

- [x ] Chrome

**Comment by marijnh** [comment]
What are the DOM selection endpoints when this happens? Maybe we can add an additional condition there to only fire when the DOM selection isn't collapsed.

**Comment by eshvedai** [comment]
hmm, DOM selection is not collapsed when that happens

<img width="1081" alt="screen shot 2019-03-04 at 7 44 09 pm" src="https://user-images.githubusercontent.com/26512812/53720877-e8f6c580-3eb5-11e9-985a-f5653e3c103b.png">

**Comment by marijnh** [comment]
Hm, looking back at the original issue that motivated that patch, it seems that there the selection wasn't actually collapsed either, the browser just drew it as if it was. So checking for a collapsed selection won't be able to distinguish this case.

Does this patch help in your situation?

```diff
diff --git a/src/input.js b/src/input.js
index 9d74ab1..2397bcc 100644
--- a/src/input.js
+++ b/src/input.js
@@ -317,7 +317,8 @@ class MouseDown {
                // (hidden) cursor is doesn't change the selection, and
                // thus doesn't get a reaction from ProseMirror. This
                // works around that.
-               (browser.chrome && !(this.view.state.selection instanceof TextSelection))) {
+               (browser.chrome && !(this.view.state.selection instanceof TextSelection) &&
+                (this.pos.pos == this.view.state.selection.from || this.pos.pos == this.view.state.selection.to))) {
       updateSelection(this.view, Selection.near(this.view.state.doc.resolve(this.pos.pos)), "pointer")
       event.preventDefault()
     } else {
```

**Comment by eshvedai** [comment]
yep, that works, here's what I have for the first selected column:

<img width="214" alt="screen shot 2019-03-04 at 8 46 21 pm" src="https://user-images.githubusercontent.com/26512812/53724726-9b328b00-3ebe-11e9-9936-4d3d0a44ab68.png">

I'm happy with the patch if it doesn't break the original issue.

**Comment by marijnh** [comment]
I've committed it as df9145b62 and released it as 1.8.3

**Comment by eshvedai** [comment]
thanks, Marijn!

**Comment by danarish4** [comment]
@eshvedai I'm facing the same issue, can you please share how did you implement this column selection?
