### ISSUE TITLE
export/import from git

### ISSUE THREAD

**Issue by liljenstolpe** [ProseMirror/prosemirror#9]
It would be really interesting to "save" to git and "load" from git (Markdown).

**Comment by marijnh** [comment]
You can import and export from and to Markdown. But how an in-browser editor would interact with git, I can't imagine. Can you elaborate on that?

**Comment by liljenstolpe** [comment]
Use the git java api's such that a git "save" would be a commit/push and a "load" would be a pull from HEAD.  Bonus points for branches.

**Comment by marijnh** [comment]
You could easily do this on the backend yes, and it'd be a great way to use this. But ProseMirror is a front-end component, so the actual git integration is out of scope for this projeect.
