### ISSUE TITLE
[prosemirror-view] Adding a decoration between two identical characters deletes the latter character from the view

### ISSUE THREAD

**Issue by dddotsev** [ProseMirror/prosemirror#901]
### Issue details

Adding a decoration between two identical characters deletes the latter character from the view. It probably breaks here: https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L601

### Steps to reproduce
A unit test that demonstrated the issue:
https://github.com/dddotsev/prosemirror-view/commit/4c8e210b5b0be9c4b2ba4ef3d80be635cc54e95b

The resulting dom should still contain the same text as before ("test"), but the last "t" is removed, since it only finds the first "t".
### ProseMirror version

prosemirror-view 1.8.3, which is the latest at the moment of creating the issue.
### Affected platforms

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer

**Comment by cmlenz** [comment]
Just to add some more info about this issue. The code in question is:

```javascript
    // Either find an existing desc that exactly matches this node,
    // and drop the descs before it.
    updater.findNodeMatch(child, outerDeco, innerDeco, i) ||
      // Or try updating the next desc to reflect this node.
      updater.updateNextNode(child, outerDeco, innerDeco, view, i) ||
      // Or just add it as a new desc.
      updater.addNode(child, outerDeco, innerDeco, view, pos)
```

The `findNodeMatch` will find a node that exactly matches (in the test, that is the first "t" text node), but (a) that node is at the wrong position and (b) we are not adding/cloning it so to render the second "t" in the view.

Maybe the `updateChildren` function needs to ignore matches that have already been used in the current pass?

**Comment by cmlenz** [comment]
Looks like this is the same issue as #905 which just got fixed.
