### ISSUE TITLE
Support for <textarea></textarea> in HTML forms?

### ISSUE THREAD

**Issue by randolf** [ProseMirror/prosemirror#902]
Is it possible to use ProseMirror rich text editing with a <textarea>...</textarea> element in an HTML form?

I didn't find any examples that show how to do this, and the documentation doesn't seem to cover this.

Any working examples or pointers to the appropriate documentation are appreciated.  Thanks!

P.S.:  This example at https://lead-tomato.glitch.me/ doesn't work because the "textcontent" form element comes up empty unless I modify the default text, and then the modified text includes a lot more content than I'm expecting (e.g., it includes the menus).

**Comment by randolf** [comment]
*** RESOLVED ***
I asked about this on irc.freenode.net#javascript where somename named GreenJello helped me by suggesting that I use this:  document.querySelector('.ProseMirror').innerHTML;

So, to make this work, I have added the following to my HTML form:

`onsubmit="document.getElementById('content').value = document.querySelector('.ProseMirror').innerHTML;"`

**Comment by marijnh** [comment]
That's probably a bad idea—the `innerHTML` of the editor will contain editor-specific hacks like spans with zero-width spaces around the cursor when it's in some positions and extra `<br>` nodes to work around contenteditable's issues. I recommend to use a `DOMSerializer` (via [`fromSchema`](http://prosemirror.net/docs/ref/#model.DOMSerializer%5EfromSchema) on `view.state.doc` to get a clean HTML string instead.
