### ISSUE TITLE
Enter at the end of the document doesn't work on mobile in some situations

### ISSUE THREAD

**Issue by marijnh** [ProseMirror/prosemirror#904]
Originally reported [here](https://github.com/ProseMirror/prosemirror/issues/543#issuecomment-477449895) in #543 by @fredguile:

Also @marijnh (still from my example above), I've found an issue when hitting Enter and you're at the end of the document:

- from desktop I can create paragraphs when hitting Enter (easy):
http://recordit.co/aJiW4DM8fj

- from mobile however, when I'm in during composition, hitting Enter wouldn't create a paragraph and jump to the next line, looks like I'm stuck (I'm hitting Enter several times in the video):
http://recordit.co/ioxwh3uYRG

Looking at the code below I see we deliberately disregard the event when in between composition:
```
editHandlers.keydown = (view, event) => {
  view.shiftKey = event.keyCode == 16 || event.shiftKey
  if (inOrNearComposition(view, event)) return
  view.lastKeyCode = event.keyCode
  view.lastKeyCodeTime = Date.now()
  if (view.someProp("handleKeyDown", f => f(view, event)) || captureKeyDown(view, event))
    event.preventDefault()
  else
    setSelectionOrigin(view, "key")
}
```
Is this intended? What's the magic to have similar behavior between desktop and mobile then?

(btw let us know if you would like us to issue this bugs in a separate issue)

**Comment by marijnh** [comment]
Browser shouldn't even fire key events during composition (though some, notably Safari, do), and since such keys aren't supposed to have their normal effect (they are influencing the composition) we can't handle them.

Doing enter on android does not fire a useful key event at all, so there's code in `view/src/domchange.js` that tries to detect the type of change typically created by enter, and call enter key handlers when it happens. That's the code that might be going wrong here.

**Comment by marijnh** [comment]
I can't get this issue to show up on my device—enter, even when in a composition and at the end of the document, seems to work reliably. Your keyboard also looks like GBoard—it is, isn't it? I'm not sure what else might be different.

**Comment by fredguile** [comment]
I'm using the Android emulator, and I realised it breaks when using ENTER from my physical keyboard, but works using the ENTER key of the virtual keyboard.

I was curious to check the difference of events fired with these 2 input methods (using this nifty [page](https://danburzo.github.io/input-methods/index.html)):
- when I use ENTER on a physical keyboard:
compositionstart
compositionupdate
keydown(ENTER)
keypress(ENTER)
beforeinput(insertLineBreak)
input(insertLineBreak)
keyup(ENTER)
compositionend

- when I use ENTER from the virtual keyboard:
compositionstart
compositionupdate
compositionend
keydown(ENTER)
keypress(ENTER)
beforeinput(insertLineBreak)
input(insertLineBreak)
keyup(ENTER)

So I hope that's my mistake and in real world use cases we would always get the compositionend happening before the keydown/keyup events (in that case we're good).

**Comment by marijnh** [comment]
> input(insertLineBreak)
> keyup(ENTER)
> compositionend

Is the line break presumably inserted by the `input` event not handled correctly by ProseMirror? If not, can you tell me what the DOM and selection look like after that event?

**Comment by fredguile** [comment]
@marijnh, after putting up some fixes in our editor, I think this use case is handled correctly, so we can close this one. Thanks!

**Comment by marijnh** [comment]
Nice!
