### ISSUE TITLE
Devtools yield "URI Malformed" error when unicode emoji present

### ISSUE THREAD

**Issue by wbharding** [ProseMirror/prosemirror#906]
### Issue details

When invoking the Prosemirrors devtools via `applyDevTools(view)`, Chrome yields multiple "URI malformed" exceptions if one pastes in a native emoji and continues typing:

![Selection_072](https://user-images.githubusercontent.com/35342/55248720-8d470000-5207-11e9-8b5d-a35a3996f799.png)

### Steps to reproduce

Open a Prosemirror editor instance that uses devtools in Chrome, and open Chrome inspector. Paste in a native emoji like "🕵️", then continue typing. Observe repeated exception. 

### ProseMirror version

1.8.4 (I think?)

### Affected platforms

Observed in latest Chrome on Linux and macOS

### Screenshots / Screencast (Optional)

![Selection_073](https://user-images.githubusercontent.com/35342/55248948-2413bc80-5208-11e9-9219-3142a4005c4e.png)

**Comment by wbharding** [comment]
Hmm, it looks like Github automatically converts my native emoji into a corresponding image, so you may need to grab a native emoji from outside this issue to get repro.

**Comment by marijnh** [comment]
It sounds like you're using [`prosemirror-dev-tools`](https://github.com/d4rkr00t/prosemirror-dev-tools), and the problem originates from there—that project isn't maintained by the same people as the ProseMirror library, so I suggest you open an issue on that repository instead.
