### ISSUE TITLE
Selection state not alway updated

### ISSUE THREAD

**Issue by pulse14** [ProseMirror/prosemirror#909]
### Issue details

Sometime when I click on a block the selection is visually updated but not updated in the state
https://gyazo.com/adfe59ec418cfcaae101dfc4ae46210b

### Steps to reproduce

I was not able to reproduce without all our plugins and code. We found the reason why it is not updating is because in `SelectionReader` 
```javascript
SelectionReader.prototype.readFromDOM = function readFromDOM (origin) {
  if (this.ignoreUpdates || !this.domChanged() || !hasFocusAndSelection(this.view)) { return }
  if (this.suppressUpdates) { return selectionToDOM(this.view) }
```
`domChanged` returns false because `storeDOMState` is not always called.

If I change `SelectionReader.prototype.readFromDOM` code to this, it works
```javascript
  if (!this.view.state.selection.eq(selection)) {
    var tr = this.view.state.tr.setSelection(selection);
    if (origin == "pointer") { tr.setMeta("pointer", true); }
    else if (origin == "key") { tr.scrollIntoView(); }
    this.view.dispatch(tr);
    this.storeDOMState(selection); // <--------
  } else {
    selectionToDOM(this.view);
  }
```

### ProseMirror version

"prosemirror-view": "^1.8.7",

### Affected platforms

- [x] Chrome
- [x] Firefox

**Comment by marijnh** [comment]
In principle, dispatching a transaction should, when it updates the selection, end up calling `selectionToDOM`, which will take care of calling `storeDOMState`. Can you pinpoint why this isn't happening in your setup?

**Comment by pulse14** [comment]
@marijnh In this case the selection change isn't caused by a transaction but because of the SelectionChangePoller.

**Comment by pulse14** [comment]
Ok this is what happen 
- I click in the first node
- We enter in `readFromDOM` and ` selectionToDOM(this.view);` gets called at the end
- Then I click on the 2nd node
- We enter in `readFromDOM` and `this.view.dispatch(tr);` gets called
- `EditorView.prototype.updateState` gets called
- Then ` syncNodeSelection(this, state.selection);` gets called, and **not** `selectionToDOM(this, false, forceSelUpdate);`. So `storeDOMState` is never called.
- I click on the first node again
- We enter in `readFromDOM` and `this.domChanged()` is true so we exit and the state isn't updated

**Comment by marijnh** [comment]
Ah, I see, yeah, that's a bad corner case produced by a kludge that tries to avoid disrupting a mouse selection. Does attached patch solve this for you?

**Comment by pulse14** [comment]
Yes, thank you, it works better. I found other edge cases, I'll try to reproduce them.
