### ISSUE TITLE
Feature Request: Inline text node with attrs

### ISSUE THREAD

**Issue by woloda375** [ProseMirror/prosemirror#910]
### Scenario:

Creation a PM document from a text, where each word of text has a custom attributes(index attribute for this example), which will be reflected into node attr structure. 

### Issue details

Is there an option (or could you please add a support) how to create inline text node with **attrs** which could be as part of paragraph node?
Something like: 

~~~~
text: {
    attrs: {
        contenteditable: {default: false},
        custom_attr_1: {default: 1},
        custom_attr_2: {default: 2},        
    }    
    group: "inline"
},
~~~~

I ended up with modified paragraph node (due to example from prosemirror-schema-basic) and I created custom_text node:

~~~~
var nodes = {
    doc: {
        content: "block+"
    },

    paragraph: {
        content: "block*",
        group: "block",
        toDOM: function toDOM() { return ["p", 0] }
    },

    custom_text: {
        attrs: {
            index: { default: -1 },
            start: { default: -1 },
            end: { default: -1 },
        },
        content: "inline*",
        group: "block",
        toDOM: function toDOM() { return ["span", 0] }
    },

    custom_space: {
        attrs: {
            contenteditable: {default: false},
            id: {default: -1},
        },
        content: "inline*",
        group: "block",
        selectable: false,
        toDOM: function toDOM(node) { return ["span", node.attrs, 0] }
    },

    text: {
        group: "inline"
    },
};
~~~~

Which could be used as:

~~~~
schema.node("custom_text", {index: item.index}, [editorSchema.text(item.text)])
~~~~

But when you want add a **custom_space** node between **custom_text** nodes, than the PM editor has a performace issue during typing into it (if number of nodes is > 3000). 

Could you help me with it, please?

Thank you

Vlado

**Comment by marijnh** [comment]
Sorry, but it doesn't sound like ProseMirror is going to be able to help you with what you are doing. It treats text nodes as just plain text, without attributes, and that is not going to change. I'm not sure where your performance problems are coming from.

**Comment by woloda375** [comment]
@marijnh thank you for you response. I linked performance related issue.

**Comment by marijnh** [comment]
Okay, going to close this, let's continue the discussion there.
