### ISSUE TITLE
Can't select after node at the end of line

### ISSUE THREAD

**Issue by pulse14** [ProseMirror/prosemirror#912]
### Issue details

Can't select after node at the end of line when there is text before and when it's a span.
The `&#8303;` trick solves the issue but the selection change isn't detect and isn't updated in the state

### Steps to reproduce

https://glitch.com/edit/#!/eager-crab
Click after the dino on chrome 73.0.3683.103 (last)

### ProseMirror version

`https://prosemirror.net/examples/prosemirror.js`

### Affected platforms

- [X] Chrome
- [ ] Firefox (Works here)

**Comment by marijnh** [comment]
This is a Chrome bug, and the only workaround I'm aware of is to make the span `display: inline-block`.

**Comment by pulse14** [comment]
@marijnh `display: inline-block` works too. And the selection update problem seems to be solved by #909
