### ISSUE TITLE
Unable to use the tr.setNodeMarkup on paragraph nodes

### ISSUE THREAD

**Issue by doanguyen** [ProseMirror/prosemirror#914]
### Issue details

I tried to implement a simple feature with a menu when it clicked, it changes the attrs of the selection paragraph. The editor state is transformed (I checked by console.log) but the view does not update attribute to the DOM. I'm not sure it is a bug or it's a feature because I'm new to JS and ProseMirror.

### Steps to reproduce

Please take a look at: https://codesandbox.io/embed/4zxm3yy707

### ProseMirror version

pm-state: 1.2.2
pm-commands: 1.0.7
pm-view: 1.8.8

### Affected platforms

- [x] Chrome
- [x] Firefox
- [?] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![out](https://user-images.githubusercontent.com/6127272/56167423-63982200-5fd8-11e9-9992-13d3937dd630.gif)
In the gif I did multiple clicks

**Comment by bZichett** [comment]
Try `node.attrs.dropCap` in the `toDOM` method and report back :+1:

**Comment by doanguyen** [comment]
Oops, silly mistake, it worked. Thanks
