### ISSUE TITLE
state.selection.empty sometimes return false when double click 

### ISSUE THREAD

**Issue by keelii** [ProseMirror/prosemirror#915]
I'v been use the Official tooltip example `SelectionSizeTooltip` to build a float menu, but when  double click on single word, `state.selection.empty` seems return true. 

While the example on [https://prosemirror.net/examples/tooltip/](https://prosemirror.net/examples/tooltip/) looks ok, but my demo not working, the strange thing is i almost add nothing custom code on my demo.

Here is my example code: 

[https://codesandbox.io/s/xp73oz43l4](https://codesandbox.io/s/xp73oz43l4)

Here is screenshot:

![quiz](https://user-images.githubusercontent.com/458894/56343408-40928b80-61ed-11e9-9ac5-0609bf5f9889.gif)

**Comment by marijnh** [comment]
This was a bug that was present in prosemirror-view 1.8.8 (to which the website hadn't updated yet). Upgrade to 1.8.9 and it should be gone!
