### ISSUE TITLE
sinkListItem should not copy parent attrs

### ISSUE THREAD

**Issue by pierrebateau** [ProseMirror/prosemirror#916]
### Issue details

When a `listItem` of an `orderedList` that does not start at "1." (e.g. the `order` attribute is larger than 1) is sinked by the `sinkListItem` command, the new list also starts at a higher number. I think this is weird behaviour. 

In https://github.com/ProseMirror/prosemirror-schema-list/blob/87c49463c407f11515f92e01883e67affd946030/src/schema-list.js#L222 the `attrs` of the parent node are explicitly copied, but I doubt this is correct. Since the default `orderedList` node only has one attribute that will lead to this artifact, it would be better to not pass the parent attributes to the newly created list at all.

I can think of 2 solutions:
 * replace `parent.attrs` with an emtpy object
 * add a second argument to `sinkListItem`, containing the attributes of the new node

### Steps to reproduce

1. Start a new list with an offset by typing `4.[space]`
2. Create a second listItem by pressing enter
3. Sink the listItem (`Mod+[`)
4. The starting number of the new list is now "4."

### Screenshots / Screencast (Optional)
![image](http://g.recordit.co/xYh4c6mpDa.gif)

**Comment by marijnh** [comment]
Agreed. Want to submit a patch?

**Comment by pierrebateau** [comment]
Sure, see ProseMirror/prosemirror-schema-list/pull/5
