### ISSUE TITLE
ReplaceAroundStep Bug

### ISSUE THREAD

**Issue by jakeknerr** [ProseMirror/prosemirror#919]
### Issue details

I am getting an error "Uncaught RangeError: Index 1 out of range for <list_item>" when I attempt to lift nested structure.

### Steps to reproduce

Glitch is at https://glitch.com/edit/#!/canyon-soybean

I put together a very simple list.  To reproduce, simply focus the editor and hit "Mod-[", which should lift the nested list_item but instead throws the error.  The ReplaceAroundStep is clearly defined in the example code.  

I also have included the ProseMirrorDevTools to make seeing the structure and positions easy.

### ProseMirror version

view: 1.88
transform: 1.1.3 
model: 1.7.0
state: 1.2.2

Not sure which versions the Glitch is using.

### Affected platforms

- [ X] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
`Mod-[` in that example isn't bound to `sinkListItem`, but to some hard-coded, apparently incorrect (the outer bounds of the step don't point into the same depths, even though `openStart`/`openEnd` are zero) step. So I'm not sure what I'm supposed to do with this.

**Comment by jakeknerr** [comment]
> Mod-[ in that example isn't bound to sinkListItem... So I'm not sure what I'm supposed to do with this.

I thought I had found a bug in ReplaceAroundStep, so what I was trying to do was to create an unambiguous and simple illustration of the possible bug.  My thoughts were that by hard-coding the step and including Atlassians's ProseMirrorDevTools and its "structure" tab, it would be very easy for you to see what I was trying to point out.

> apparently incorrect (the outer bounds of the step don't point into the same depths, even though openStart/openEnd are zero) 

For the example, the slice in the ReplaceAroundStep actually has an openStart of 1. My understanding of the example is that it should lift the nested list up and make it a sibling of the first list item.  The step replaces a range starting from nested list and ending at the the closing token for the first list_item.  The slice should close off the initial open list_item.

If this isn't a bug, but a failure of comprehension on my part, I would greatly appreciate a little guidance as to why this step fails because a very similar type operation is driving me nuts.  Thanks.

**Comment by jakeknerr** [comment]
If you would prefer for me to create an example that uses the API to calculate the positions instead of hard-coding them, let me know and I would be happy to do it.

**Comment by marijnh** [comment]
It might be a bug in `liftListItem`—it shouldn't be creating steps that can't be applied. If you have an example where it does that, let me take a look.

**Comment by jakeknerr** [comment]
I wasn't trying to point out a problem with `sinkListItem` or `liftListItem`.  As far as I know they work perfectly.  I was building some custom list logic and I thought I had found a bug in ReplaceAroundStep.

Anyway, I'll close this issue.
