### ISSUE TITLE
Ability to decrease indentation of an item in a bullet list

### ISSUE THREAD

**Issue by bjoernm** [ProseMirror/prosemirror#92]
So far, there does not seem to be an easy way to decrease the indentation of a bullet item in a bullet list.
In the example below I would like to put the bullet item "two" on the same level as the other two items.

![bullet](https://cloud.githubusercontent.com/assets/1728765/11509576/16182744-985f-11e5-9c5d-cd67cd2dfa24.png)

So far, the only possibility to achieve this I have found is the following:
1. Navigate to the beginning of the second bullet item
2. Pressing the "Lift out of enclosing block" button twice
3. Pressing the "Wrap in bullet list" button
4. Pressing the "Join with above block"

OR

1. Navigate to the beginning of the second bullet item
2. Pressing BACKSPACE twice
3. Pressing ENTER once

Is there an easier way to achieve this? If not, a dedicated function for decreasing indentation would be great.

**Comment by marijnh** [comment]
Use the lift command (alt-left arrow, or the icon in the menubar, or in the node tooltip menu if you're not using a menubar -- press escape to select the paragraph block, to get the tooltip menu).

Does that help?

**Comment by marijnh** [comment]
Also, pressing enter twice at the start of the nested list paragraph currently works, but you yourself [protested](https://github.com/ProseMirror/prosemirror/issues/88) that, and it might change in the future.

**Comment by bjoernm** [comment]
Thanks for your fast reply!

I played around with it a bit more and discovered an interesting behaviour. Navigating with the cursor to the beginning of a **single bullet item** and using the lift command does not create the expected behaviour as the bullet is completely removed, as seen here:

<img width="98" alt="screen shot 2015-12-04 at 16 10 10" src="https://cloud.githubusercontent.com/assets/1728765/11592920/a9140060-9aa1-11e5-8f83-7780b20e36b8.png">

If there are **multiple bullet items** that I want to decrease the indentation of such as here:

<img width="135" alt="screen shot 2015-12-04 at 16 12 15" src="https://cloud.githubusercontent.com/assets/1728765/11592970/01a5b9d0-9aa2-11e5-90e5-1bf327c3517c.png">

Selecting them and using the lift command actually decreases the indentation and does not remove the bullets:

<img width="124" alt="screen shot 2015-12-04 at 16 12 23" src="https://cloud.githubusercontent.com/assets/1728765/11592978/12ecb6a8-9aa2-11e5-84e3-37fe83100bcc.png">

My suggestion would be to either have the lift command behave the same way for single bullet items as for multiple bullet items or add a new command such as "decrease indentation".

Your suggestion about pressing ENTER twice also works, but I think a consistent behaviour or dedicated indentation command would be a more discoverable and usable way for users.

**Comment by marijnh** [comment]
If you have a selection across multiple blocks and use block commands, the commands are applied not to individual textblocks, but to the nearest range of sibling nodes that contain the entire selection (in this case, the list_item nodes for 'foo' and 'bar').

I understand your intuition that you're lifting the individual items, but I am not sure how to formulate that behavior in a way that generalized to arbitrary selections. Any ideas?

**Comment by kiejo** [comment]
Any updates on this? I think that having a reliable way of indenting and unindenting list items is a very basic and important feature for any rich text editor.
I came up with the following rules when thinking about how to generalize the idea of an unindent command. The main goal was to produce output that visually makes sense (see unindention behavior of other editors like Word or Google Docs).

Unindenting a single node should have the following effects:
* The node's subsequent siblings get concatenated to the node's existing children
* The node becomes the direct sibling of its parent

Handling arbitrary selections:
* If multiple nodes are selected, this rule needs to be applied sequentially to all the selected nodes from bottom to top (starting with the last selected node)
* If the start/end of the selection includes only part of a node, the whole node should be included in the command
* The command should only be applied to nodes that represent a nested data structure (e.g. list items)

I thought through this using multiple bullet list scenarios and think that this might work. Would this be a feasable approach for ProseMirror? I know that other editors handle indention/unindention simply using an integer representing the current indention level of an item, but this would remove the nice semantic data model that ProseMirror offers. Directly working on the nested data structure would allow us to keep ProseMirror's current data model.
What do you think?

**Comment by kiejo** [comment]
With the new `list_item:lift` command we can close this issue :) See #261.

**Comment by marijnh** [comment]
🌝
