### ISSUE TITLE
Calling `EditorView.setProps` re-creates all plugins

### ISSUE THREAD

**Issue by nathf** [ProseMirror/prosemirror#924]
### Issue details

Hi @marijnh ,

When calling `EditorView.setProps`, all plugins are destroyed and re-created, this looks to be a recent regression introduced in `1.8.9` (https://github.com/ProseMirror/prosemirror-view/commit/495c3dfd6017e00117dd4268313fed3ca76445b8#diff-1fdf421c05c1140f6d71444ea2b27638L159). I'm not sure whether this new behaviour is intended or not but it creates a lot of overhead and unexpected results in our application (see codesandboxes below)

### Steps to reproduce

These two apps are identical aside from their `prosemirror-view` version.
ProseMirror v1.9.3 example: https://codesandbox.io/s/w6mk6j9v97
ProseMirror v1.8.8 example: https://codesandbox.io/s/j357zzjm8v

### ProseMirror version

v1.8.9

**Comment by marijnh** [comment]
That was an unintended regression. I've released 1.9.4 with a fix.

**Comment by nathf** [comment]
Thank you for the fast turn around @marijnh, updating the example to the latest version issue seems to fix the issue.
