### ISSUE TITLE
parserules context usage example

### ISSUE THREAD

**Issue by frendyguo** [ProseMirror/prosemirror#925]
Related to #665 

Here in my case, I have 2 nodes with the same `figure` parent tag, but one with `img` child and the other with `iframe` child.

```
nodes: {
    doc: {
      content: "div"
    },
    img: {
      content: 'inline*',
      group: 'block',
      parseDOM: [
        tag: 'figure',
        context: 'figure/img/',
        contentElement: 'figcaption',
        getAttrs(dom) {
          const img = dom.querySelector('img');
          return {
            src: img ? img.src : null,
          };
        },
      ],
    },
    iframe: {
      content: 'inline*',
      group: 'block',
      parseDOM: [
        tag: 'figure',
        context: 'figure/iframe/',
        contentElement: 'figcaption',
        getAttrs(dom) {
          const iframe = dom.querySelector('iframe');
          return {
            src: iframe ? iframe.src : null,
            width: iframe && iframe.src ? iframe.width : 0,
            height: iframe && iframe.src ? iframe.height : 0,
          };
        },
      ],
    },
    text: {
      inline: true
    }
  }
```

I tried using context as suggested in #665, by setting the context value to `figure/`, `figure/img`, `figure/iframe`. However I got no result.

Could you shed me some light here @marijnh ?

**Comment by marijnh** [comment]
Firstly, context refers to ProseMirror nodes, not DOM nodes, so unless you have a `figure` node you didn't show, those contexts won't match.

Secondly, I'm guessing that you're trying to parse `<figure><img></figure>`, or something similar, as a single document node here. It would be enough to just target `figure` and have a `getAttrs` function that returns false if the figure element doesn't match the expected structure.

Does that help?

**Comment by frendyguo** [comment]
Okay, the second part solved my problems, Thanks..

As for the first part, when you say the context refers to ProseMirror nodes, do you mean the `image` and `iframe` in my case above? And if so, how should I set the context so it'd match?

**Comment by marijnh** [comment]
It'll be matched against the set of parent ProseMirror nodes that the parser is trying to place this node into. I.e. you could use this to parse img nodes inside paragraphs different from those at the top level of the document.
