### ISSUE TITLE
creating code block with textblockTypeInputRule throws an error

### ISSUE THREAD

**Issue by philippkuehn** [ProseMirror/prosemirror#926]
### Issue details

After creating a code block with `textblockTypeInputRule` an error is thrown.
```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
```

### Steps to reproduce

- go to the example editor on https://prosemirror.net/
- type three backticks (```)
- a code block will be created
- type any character
- an error will be thrown

### ProseMirror version

latest

### Affected platforms

- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
I'm not able to reproduce this in either Firefox or Chrome. I've tried both turning the first paragraph into a code block with three backticks and continuing to type, and starting a new paragraph, typing three backticks, and then typing some more.

**Comment by philippkuehn** [comment]
Hmm this is strange. I see this error in Chrome and Firefox. I do not have any addons activated in Firefox and I'm using the latest version.

screenrecord: https://drop.philipp-kuehn.com/Utm6Juh0pw.mp4

**Comment by philippkuehn** [comment]
I don't get this error using the menu to add a code block.

**Comment by marijnh** [comment]
That _is_ strange. I tried doing exactly the same as you show in the video (typing at the end of the document on the front page of the website), and still get no error. Since this occurs in different browsers, it's unlikely to be a browser version thing. I hard-refreshed to make sure I have the latest scripts.

Can you paste the full stack trace? I'm not sure I can make much of that without being able to reproduce the problem, but maybe there's something useful in there.

**Comment by philippkuehn** [comment]
Since your assets are minified this don't tell that much. But I can also reproduce this on the tiptap demo site, so I can give you a stack trace of my mobile environment:

```
index.js?703f:1472 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
    at renderDescs (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1472:17)
    at NodeViewDesc.renderChildren (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1228:5)
    at NodeViewDesc.updateChildren (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1223:12)
    at NodeViewDesc.updateInner (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1291:33)
    at NodeViewDesc.update (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1283:10)
    at ViewTreeUpdater.updateNextNode (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1704:25)
    at eval (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1209:17)
    at iterDeco (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1786:7)
    at NodeViewDesc.updateChildren (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1194:5)
    at NodeViewDesc.updateInner (webpack-internal:///./node_modules/prosemirror-view/dist/index.js:1291:33)
```

The error occurs for `parentDOM.insertBefore(childDOM, dom)`

```js
// : (dom.Node, [ViewDesc])
// Sync the content of the given DOM node with the nodes associated
// with the given array of view descs, recursing into mark descs
// because this should sync the subtree for a whole node at a time.
function renderDescs(parentDOM, descs) {
  var dom = parentDOM.firstChild;
  for (var i = 0; i < descs.length; i++) {
    var desc = descs[i], childDOM = desc.dom;
    if (childDOM.parentNode == parentDOM) {
      while (childDOM != dom) { dom = rm(dom); }
      dom = dom.nextSibling;
    } else {
      parentDOM.insertBefore(childDOM, dom);
    }
    if (desc instanceof MarkViewDesc) {
      var pos = dom ? dom.previousSibling : parentDOM.lastChild;
      renderDescs(desc.contentDOM, desc.children);
      dom = pos ? pos.nextSibling : parentDOM.firstChild;
    }
  }
  while (dom) { dom = rm(dom); }
}
```

**Comment by marijnh** [comment]
Thanks. But unfortunately that doesn't get me much further. Something has to be going really haywire for that line to be trying to insert a node somewhere in its own children—that's not a failure for which I can come up with any reasonable scenario.

I just tried another machine but no dice there either. This is all highly confusing.

**Comment by philippkuehn** [comment]
Hmm. I don't know if this can be related but in Safari I can't even type multiple backticks 😅

screenrecord: https://drop.philipp-kuehn.com/SEbFGTnpiU.mp4

**Comment by philippkuehn** [comment]
what the hell is going on here? :) I walked through our office and tested this on different devices (all mac) and I could reproduce this on all devices.

**Comment by marijnh** [comment]
I'll give it a try on a Mac machine (but I don't have one handy right now)

**Comment by marijnh** [comment]
Must be the fingerprints on the keyboard or something—when I try on a Macbook, it's not happening either (tried Chrome and Safari).

**Comment by philippkuehn** [comment]
How is this possible? 😂 I see this issue on 4 different MacBooks. I tried to reproduce this error on Browserstack but unfortunately it's not possible to type backticks in their vms.

**Comment by philippkuehn** [comment]
I did some more tests in a local vm:
- Ubuntu Firefox: working fine
- Windows Edge: working fine
- Windows Chrome: working fine

**Comment by philippkuehn** [comment]
I downgraded all my prosemirror dependencies and found that this bug was introduced with `prosemirror-view@1.9.0`.

**Comment by philippkuehn** [comment]
And there is another difference for this code block input rule: Until prosemirror-view@1.9.0 I have to type any char after the backticks to convert it to a code block. Now it will be converted immediately after I have typed the third backtick.

**Comment by philippkuehn** [comment]
@marijnh I finally found the difference! This bug happens only with a german keyboard layout. If I change the layout from `qwertz` to `qwerty` everything works fine 🤯
(On my german layout I have to hold shift to be able to type a backtick)

**Comment by marijnh** [comment]
Ahh, glad to hear we're not losing our minds. I can reproduce it now! But only on Chrome with German keyboard settings with dead keys turned _on_, and after figuring out where the backtick is in that layout :grin: 

I've fixed this in two places: firstly, the input rules shouldn't be butting in when a composition is active, which is fixed in https://github.com/ProseMirror/prosemirror-inputrules/commit/, and secondly, the crash was created by a bug in the view, which is fixed in https://github.com/ProseMirror/prosemirror-view/commit/1280bb05c057fc7a86d0efd9a05fdaaa3a6b6cc0

Can you confirm that this helps for you?

**Comment by philippkuehn** [comment]
Thank you and sorry for the confusion. Unfortunately there is a different bug now, when applying a code block or inline code input rule (new!). 

This error is thrown at prosemirror-state:

```
Uncaught TypeError: Cannot read property 'key' of undefined
    at Transaction.setMeta (index.js?6ffb:675)
    at run (index.js?72a8:83)
    at eval (index.js?72a8:63)
```

This occurs only on the german layout again.

**Comment by marijnh** [comment]
Ah, right, and only in strict mode, which is why my test setup didn't catch it. Try with prosemirror-inputrules 1.0.4

**Comment by philippkuehn** [comment]
Better, but now there is something different for inline code input rules 😂
![May-17-2019 11-57-39](https://user-images.githubusercontent.com/2500670/57920309-0cb58f00-789b-11e9-96b1-8d12a54fb265.gif)

The inline code mark is not applied immediately after I type a backtick. After I type a space it will leave a backtick. I know mark input rules are not part of the core but these input rules worked like a charm before.

**Comment by marijnh** [comment]
Double-check how you defined them. It is now possible for the closing backtick to already be in the state when the rule handler is called (when the rule is triggered after a compositionend event), which wasn't the case before.

**Comment by philippkuehn** [comment]
Ah yeah, that changed. Fixed it on my side. Seems to be working fine now. Thank you so much! 👍

**Comment by herbertpimentel** [comment]
> Better, but now there is something different for inline code input rules 
> ![May-17-2019 11-57-39](https://user-images.githubusercontent.com/2500670/57920309-0cb58f00-789b-11e9-96b1-8d12a54fb265.gif)
> 
> The inline code mark is not applied immediately after I type a backtick. After I type a space it will leave a backtick. I know mark input rules are not part of the core but these input rules worked like a charm before.

@philippkuehn I am trying to achieve a very similar behaviour of that. But I am really strugling with that, can you point to some directions ?!

My goal is create a rule to replace the input with a custom Node
