### ISSUE TITLE
Concat and setInterval errors in ie11

### ISSUE THREAD

**Issue by AlecTroemel** [ProseMirror/prosemirror#927]
### Issue details
The following 2 errors show in the ie11 terminal 

```
Unable to get property 'concat' of undefined or null reference
Object doesn't support property or method 'setTimeout'
```

I've narrowed it down to these 2 lines 
[setTimeout](https://github.com/ProseMirror/prosemirror-view/blob/master/src/domobserver.js#L36) 
[concat](https://github.com/ProseMirror/prosemirror-view/blob/master/src/domobserver.js#L77) 

and the commit https://github.com/ProseMirror/prosemirror-view/commit/c7b98a3f50255716fe78e65de9d47372565fe2f9. 

These errors break https://tiptap.scrumpy.io/suggestions, which is built on prosemirror and vue. Text selection on the prosemirror website in ie11 is also broken, though I am unsure if that is cause by these errors

### Steps to reproduce
go to https://prosemirror.net/ in ie11 and open the console.

### ProseMirror version
prosemirror-view 1.9.4 

### Affected platforms
- [ ] Chrome
- [ ] Firefox
- [ X] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Argh, I guess that kind of thing could really be a case for porting to TypeScript at some point. Those were both completely obvious typos that I didn't catch because the code only runs on IE11. Attached patch fixes them.

**Comment by AlecTroemel** [comment]
dang, lightning fast fix @marijnh. thank you!
