### ISSUE TITLE
commands.splitBlock error

### ISSUE THREAD

**Issue by jakeknerr** [ProseMirror/prosemirror#928]
### Issue details

When selection `from` is at the beginning of a nested textBlock and selection `to` is at the end of the document, hitting the `Enter` key can throw an `Uncaught RangeError: Position XX out of range` error.

### Steps to reproduce

https://enthusiastic-trout.glitch.me/

Start selection from the end of the document and select up to the beginning of the list_item. Then hit the `Enter` key.

### ProseMirror version

Latest versions of everything.

### Affected platforms

- [X ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![pm_enter](https://user-images.githubusercontent.com/12791900/57676717-66d7fb00-75e2-11e9-9e98-b33f9ca66bd7.gif)

### Fix
The offending line of code is in commands.js line 302 
```let can = canSplit(tr.doc, $from.pos, 1, types)```

I think the fix is as simple as mapping `$from.pos`, like the following:
```let can = canSplit(tr.doc, tr.mapping.map($from.pos), 1, types)```

I can submit a pull request if you would prefer, just let me know and it's done.

**Comment by marijnh** [comment]
Thanks for reporting that. I've fixed it in attached patch.
