### ISSUE TITLE
documentation about core, supported, extra modules

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#929]
http://prosemirror.net/docs/guide/
list four core modules:
- prosemirror-model
- prosemirror-state
- prosemirror-transform
- prosemirror-view

However
https://github.com/prosemirror/prosemirror-commands
is described as a "core" module: it's confusing.

Especially now that someone is trying to package prosemirror for debian;
where bundling related core prosemirror modules makes more sense.

**Comment by marijnh** [comment]
I guess I'm using that terminology a bit loosely. I see four types of modules:

 - The stuff you absolutely need to get a ProseMirror editor to run (model/state/transform/view)
 - The other things maintained seriously by me (commands, keymap, history, collab, schema-list, schema-basic, gapcursor, inputrules)
 - Stuff that I put online but don't plan on supporting beyond basic bugfixes (menu, example-setup, markdown)
 - 3rd party modules

I guess I meant the first meaning in the guide, and the second in the commands docs. I've changed the wording in the guide to use "essential" instead.
