### ISSUE TITLE
Japanese problem on Safari 

### ISSUE THREAD

**Issue by shinichiro81** [ProseMirror/prosemirror#931]
### Japanese Input is max length 9. And, pressing enter key vanished the Japanese input.

This happened In [http://prosemirror.net/examples/basic/](url).

#### Japanese Input is max length 9.
I input 9 Japaneses characters  at line head.
↓
Then, I input a 10h Japaneses character.
↓
But, the 10th character was not shown in the editor.Instead, 9th character vanished.
In the other words, I expected 10 Japanese characters on the screen, but I get 8 ones.

#### Pressing enter key vanished the Japanese input.
I input Japanese characters.
↓
I pressed Enter key.
↓
inputed Japanese characters vanished.

### Steps to reproduce

go to  [http://prosemirror.net/examples/basic/](url) by safari and input Japanerse at line head.This problem happens  only at line head.

### ProseMirror version
 [http://prosemirror.net/examples/basic/](url)

### Affected platforms
- [✔︎ ] Safari12.1.1

### Screenshots / Screencast (Optional)
I kept pressing A key and at the end ,pressed Enter key.
![838aab568f688e8c5d7fc5c3b6e13cbc](https://user-images.githubusercontent.com/27888658/58224087-3832f080-7d57-11e9-914a-46d9ae83d097.gif)

Thank you for reading my bad English.
I respect and appreciate the existence of ProseMirror.
Tell me what I can do to resolve this problem.

**Comment by hiro-yam** [comment]
I have same type of issue on IOS Safari.

![output6](https://user-images.githubusercontent.com/1026472/58366123-97843280-7f08-11e9-884a-0ccbe1f453e8.gif)

**Comment by marijnh** [comment]
Could you check whether patches e96c9a6c740e07 and 5e491af1569df6 (released as 1.9.7) help for you?

**Comment by shinichiro81** [comment]
@marijnh 
Thank you!!!

![41bd27433179e5534c2eff6cd7362e53](https://user-images.githubusercontent.com/27888658/58757452-c40efe80-8547-11e9-9793-1ccbf19f24d3.gif)

I checked that this problem was resolved.

**Comment by hiro-yam** [comment]
@marijnh 
Thank you fixed problem!
I can type japanese text in mobile safari!

@shinichiro81 
Also, Thank you open this issue! very helpful!

**Comment by marijnh** [comment]
Great! Thank you for getting back to me.
