### ISSUE TITLE
Possible bug in collab#receiveTransactions()

### ISSUE THREAD

**Issue by Narretz** [ProseMirror/prosemirror#932]
### Issue details
collab#receiveTransactions() increases the state version even when no steps are applicable.

### Steps to reproduce

If you call receiveTransactions() with steps that should not be applied because they originated from the same client, the collab plugin nevertheless increments the version number by the number of (non-applicable) steps:
https://github.com/ProseMirror/prosemirror-collab/blob/18d6fb62444a281c5bfd63f3fb6ba761f4e6ef1f/src/collab.js#L122

If all steps are "own" steps, both "steps" and "unconfirmed" are length 0, therefore the state should not have its version increased. Does that make sense?

I think it should look like this: 

https://github.com/ProseMirror/prosemirror-collab/compare/master...Narretz:patch-1?diff=unified

The incrementing version is problematic because the client will have a higher version than the central authority. 

### ProseMirror version
prosemirror-collab#1.1.1

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Does this cause any issues for you? I think that what's happening is that receiving your own steps _confirms_ those steps, so the version field (which refers to the last seen remote version, not the local version) should be increased in that case.

**Comment by Narretz** [comment]
Yes, you are right. I realized that when the change I wanted to make broke the updates. :)
