### ISSUE TITLE
Safari starting composition over and over on Japanese IME after applying marks

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#935]
### Issue details

When marks are applied (I believe from `setStoredMarks`) while typing with a Japanese IME, Safari seems to keep trying to start the composition. This creates an effect where old composition text is not deleted and all of the composition text is appended. This makes typing with an IME on Safari unusable as soon you apply a mark.

### Steps to reproduce

1. Go to the basic editor at http://prosemirror.net/examples/basic/ on Safari
2. Enable a Japanese IME (I'm using Hiragana)
3. Put the cursor in the editor and hit "bold"
4. Begin typing

### ProseMirror version

1.9.8

### Affected platforms

- [x] Safari

### Screenshots / Screencast (Optional)

![ezgif-4-505220e290e1](https://user-images.githubusercontent.com/5751354/59070523-b1b2fe80-8880-11e9-82d6-b88628624de0.gif)

**Comment by jljorgenson18** [comment]
I've been digging into the internals and I'm a bit stumped on this one. Something is causing Safari to be confused about the composition, but I can't find other cases of this happening.

**Comment by jljorgenson18** [comment]
Looks like the issue could have something to do with the syncToMarks function. The MarkView ends up being recreated over and over again because the mark ends up not being "found".

```js
    while (depth < marks.length) {
      this.stack.push(this.top, this.index + 1)
      let found = -1
      for (let i = this.index; i < Math.min(this.index + 3, this.top.children.length); i++) {
        if (this.top.children[i].matchesMark(marks[depth])) { found = i; break }
      }
      if (found > -1) {
        if (found > this.index) {
          this.changed = true
          this.top.children.splice(this.index, found - this.index)
        }
        this.top = this.top.children[this.index]
      } else {
        let markDesc = MarkViewDesc.create(this.top, marks[depth], inline, view)
        this.top.children.splice(this.index, 0, markDesc)
        this.top = markDesc
        this.changed = true
      }
      this.index = 0
      depth++
    }
```

When typing without an IME, the MarkViewDesc is created once and then `found` equals 1 on additional syncToMarks calls. However when typing with an IME on Safari, `found` is always -1. I'm going to dig in farther and try to figure out why.

**Comment by jljorgenson18** [comment]
I believe the CompositionViewDesc and the MarksViewDesc are not getting along somehow. Even though the MarkViewDesc is added correctly, the CompositionViewDesc is added back in. I'm wondering if this is due to Safari's backwards order of certain composition operations?

Anyways, you can see what is in `this.top.children` after applying a mark and then typing. The first half of the logs are what happens without an IME, the second half shows what happens "with" an IME. I believe the MarkViewDesc should be in this list and because it is not, we end up recreating the marks over and over in Safari.

<img width="415" alt="Screen Shot 2019-06-11 at 4 36 41 PM" src="https://user-images.githubusercontent.com/5751354/59308801-8dcc3000-8c67-11e9-8a14-eb538110fbfb.png">

**Comment by jljorgenson18** [comment]
So it looks like Chrome is running through the same code and is syncing the marks each time as well. However on Chrome, it seems to be smart enough and doesn't restart the composition each time. I believe the solution would be to somehow make marks and composition views play nicely, but I'm not sure how to make that happen. @marijnh do you have any thoughts on how best to fix this?

**Comment by jljorgenson18** [comment]
Just tried this in Firefox and it looks like Firefox doesn't have this exact behavior but it seems like it got rid of the mark after the composition was complete (after you hit enter). Not sure if it is the same underlying problem or a different issue.

**Comment by jljorgenson18** [comment]
Almost there with a potential fix, although I'm still uncertain. The crux of this issue is the `protectLocalComposition` function and how it is replacing the mark here 

```js
    // Patch up this.children to contain the composition view
    this.children = replaceNodes(this.children, pos, pos + text.length, view, desc)
```

I believe the position needs to be updated to factor in the newly added Marks. The structure has changed when syncing marks but the position and the rest of composition object are staying the same.

**Comment by jljorgenson18** [comment]
We tried a few more things out and tried to create a variation of the `replaceNodes` function that checks to see if the child is a MarkViewDesc. If it is, then the MarkViewDesc is cloned and then the replaceNode variation is called recursively. We are going to research a bit more but the issue still occurred, even after getting the nodes into the correct format (although we need to do more research). I think the problem is a combination of the nodes not being in the correct structure when compositions are involved as well as the dom manipulation that occurs when syncing pending marks. @marijnh this issue makes typing with an IME on Safari unusable and I'm guessing it could have bad effects on other browsers as well.

**Comment by Xheldon** [comment]
I meet this bug too, see: https://discuss.prosemirror.net/t/chinese-ime-not-work-fine-in-safari-when-use-marks/2090
CJK languages IME have these problem in Safari. @marijnh Any idea?

**Comment by jljorgenson18** [comment]
@marijnh The issue I referenced here https://github.com/ProseMirror/prosemirror/issues/935#issuecomment-501038550 is due to an extra mutation Firefox is firing right before compositionend. It fires a mutation but doesn't change the underlying text node which then sets the "typeOver" flag to true internally. I was going to submit a PR tomorrow to try to resolve it.

**Comment by marijnh** [comment]
I think it should be safe to ignore `typeOver` (or just not set it) when a composition is active.

**Comment by marijnh** [comment]
I've done so in attached patch.

**Comment by jljorgenson18** [comment]
O nice! Also, I do think this is essentially a dupe of https://github.com/ProseMirror/prosemirror/issues/944#issuecomment-518588671. The core issue seemed to be fixed on `1.9.14-prerelease`. There may be another small issue with marks and FF (and potentially other browsers) where the selection ends up outside of the mark element and the mark isn't applied until after the composition is inserted. I can create another issue if needed if it still occurs after the most recent changes.

**Comment by jljorgenson18** [comment]
@marijnh The typeOver being to true was actually a red herring and the issue is just do to registering that extra mutation. My local solution was ignoring mutations on the CompositionViewDesc where the oldValue and newValue are the same.

```
  ignoreMutation(mut) { 
    return mut.type === 'characterData' && mut.target.nodeValue == mut.oldValue;
   }
```

If you think this will work, I can submit a PR.

**Comment by marijnh** [comment]
Yes, that sounds reasonable—a PR would be great.

**Comment by jljorgenson18** [comment]
PR can be found here https://github.com/ProseMirror/prosemirror-view/pull/56

**Comment by jljorgenson18** [comment]
I'm going to go ahead and close this since it is essentially a dupe of https://github.com/ProseMirror/prosemirror/issues/944 and the prerelease branch appears to be solving it.
