### ISSUE TITLE
prosemirror-collab rebaseSteps documentation missing

### ISSUE THREAD

**Issue by ungoldman** [ProseMirror/prosemirror#936]
### Issue details

It appears the exported collab method [`rebaseSteps`](https://github.com/ProseMirror/prosemirror-collab/blob/903900464b9727a57c3e83cf4308396a5d58f88c/src/collab.js#L11-L14) is documented with inline comments, but that documentation isn't present in the reference manual (http://prosemirror.net/docs/ref/#collab), making it a bit challenging to discover that it's available. Is there a reason it's not documented in the reference manual? If not, would it be possible to expose that?

Thank you 🙏

**Comment by marijnh** [comment]
That function is only exported for testing purposes, if I remember correctly. Comments with a single colon (as opposed to `::`) aren't picked up by the documentation, and generally aren't public. What are you intending to use `rebaseSteps` for?

**Comment by ungoldman** [comment]
I was hoping to investigate using the `rebaseSteps` method to manually rebase steps after recovering from disconnection. Specifically I'm looking into how to prevent data loss when two users are disconnected, keep writing, and then are reconnected to a central authority in a collab setting.

I read elsewhere that this should "just work" (https://discuss.prosemirror.net/t/best-way-to-replay-steps/1752) but I believe in the scenario outlined above is similar to a comment you wrote in the linked discussion:

> If you are offline for a while, and both you and other people make a lot of changes, the non-interactive merge that rebasing does might cause data loss, though (if you wrote stuff in a place that someone else deleted, it’ll be gone). There isn’t an out-of-the-box solution for that case yet, but it’d probably look like showing the changes side-by-side when they overlap and letting the use manually merge somehow.

I'd like to figure out how to attempt to rebase steps and continue if no problems were encountered, and if a problem (potential data loss) is detected, figure out the "showing the changes side-by-side when they overlap and letting the use manually merge somehow" step.

**Comment by ungoldman** [comment]
Perhaps I'm investigating from the wrong direction and should instead create a discussion in discuss.prosemirror.net asking for help from the community there.

**Comment by marijnh** [comment]
> I read elsewhere that this should "just work" 

It _will_ "just work", as in it'll rebase your local steps and re-sync with the server, it's just that that might lead to data loss and/or a messy document because things are blindly merged without anyone actually looking at the outcome in real time.

**Comment by ungoldman** [comment]
Thank you for the responses @marijnh! I now understand that this method is left undocumented intentionally and is only meant for internal use.

For those happening upon this thread in the future, this recently published module may be of use for managing reconciliation between diverging document states.

https://www.npmjs.com/package/@manuscripts/prosemirror-recreate-steps
