### ISSUE TITLE
Inline nodes marked as selectable false, don't work as expected in Safari / Chrome

### ISSUE THREAD

**Issue by ugin** [ProseMirror/prosemirror#937]
### Issue details

When marking an inline node as `selectable: false`, navigating using the arrow keys to pass over the node is required to double press the arrow key to navigate over it, as if it was marked as selectable.

### Steps to reproduce

Starting from the Dino example we remixed to add `selectable: false` to the dino node. [Click on the remix](https://glitch.com/edit/#!/dune-climb?path=index.js:20:0), place the cursor at the end of `This paragraph` and press the arrow right to pass over the dino inline element.

### ProseMirror version

latest

### Affected platforms

- [ ] Safari
- [ ] Chrome
- [ ] Firefox -- works as expected

**Comment by marijnh** [comment]
Ugh, I guess that's a thing what webkit-based browsers do around uneditable inline nodes. Does attached patch help for you?

**Comment by ugin** [comment]
Fixed
