### ISSUE TITLE
coordsAtPos use undefined parent variable

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#938]
Using prosemirror-view@1.9.9 but this has been around for two months.
https://github.com/ProseMirror/prosemirror-view/blob/28e233745a5af59cd3f8fb6b87f15e40979f7271/src/domcoords.js#L268

refers to a `parent` variable from global scope but it cannot be `window.parent`.
I suppose it's a copy/paste mistake.

Also i happen to walk that path and it fails with `parent.getBoundingClientRect is not a function`.

**Comment by marijnh** [comment]
Thanks. I guess the linter accepted this because `window.parent` exists. Attached patch should fix it.
