### ISSUE TITLE
emptyBlockMenu code option doesn't seem to work

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#94]
![tooltip-code](https://cloud.githubusercontent.com/assets/395307/11541417/2e798d0e-9900-11e5-94a2-1f4b2c17a057.gif)

with this error when "code" is selected:

> Uncaught TypeError: Cannot read property 'contentEditable' of null
renderInlineContentFlat @ demo_basic_bundle.js:8829
wrap @ demo_basic_bundle.js:8745
(anonymous function) @ demo_basic_bundle.js:8876
renderNode @ demo_basic_bundle.js:8762
renderNodeToDOM @ demo_basic_bundle.js:8735
scan @ demo_basic_bundle.js:1659
redraw @ demo_basic_bundle.js:1671
flush @ demo_basic_bundle.js:3252
(anonymous function) @ demo_basic_bundle.js:3233

**Comment by marijnh** [comment]
This appears to have been fixed -- I can't reproduce it anymore, and I did mess around with the renderer a lot in the past two weeks.

Post an update if you can still reproduce it with the current master branch.

**Comment by forresto** [comment]
Might be a different bug:

1. newline
2. select code
3. type, and it ends up above the `code` tag, not in it as expected.

```
<pre pm-offset="2">
  <span pm-offset="0" pm-leaf="3">fff</span>
  <code></code>
  <span pm-ignore="cursor-text"></span>
</pre>
```

**Comment by forresto** [comment]
1. convert `p` to `code`
2. click to move cursor to code, get this error and no cursor:

> Uncaught Error: Offset 35 out of range

The text is within the `code` el, but it is missing the `pm-offset`.

```
<pre pm-offset="0" class="">
  <code>
    <span pm-offset="0" pm-leaf="68">No pressure.</span>
  </code>
  <span pm-ignore="cursor-text"></span>
</pre>
```

**Comment by marijnh** [comment]
Definitely a different bug, but one that I could reproduce. Attached patch should help.
