### ISSUE TITLE
1.8.9 => 1.9.0 Breaking changes?

### ISSUE THREAD

**Issue by 1Jesper1** [ProseMirror/prosemirror#941]
After migrating from Prosemirror-View 1.8.9 to 1.9.0 we have problems with backspacing on marks.

See attached GIF.
![prosemirror bug](https://user-images.githubusercontent.com/4539406/59921823-3d0ac300-942f-11e9-8fe5-7b7c96977b32.gif)

1. After 1 backspace on bold a, the bold a gets removed. A 2nd backspace doesn't work.
2. A backspace at end of the link doesn't work.

We don't have these problems in the 1.8.9 version.

**Comment by marijnh** [comment]
Which platform does this happen on, and can you reproduce the problem on https://prosemirror.net ?

**Comment by 1Jesper1** [comment]
@marijnh Thanks for the fast reply! The above happens on Chrome and Firefox.

In Edge: 
1. Same problem as Chrome and Firefox.
2. Can remove the last character.
![edge](https://user-images.githubusercontent.com/4539406/59930145-8e707d80-9442-11e9-96d3-89e8f2daba81.gif)

In IE11:
1. Cursor jumping and removing too much.
2. Removing works.
![ie11](https://user-images.githubusercontent.com/4539406/59930151-929c9b00-9442-11e9-941a-66a41ed136f3.gif)

**Comment by marijnh** [comment]
But it's not happening on https://prosemirror.net , right? So the first thing to do would be to figure out what is different about your setup that triggers this, and whether it's a bug in the library or in your code.

**Comment by 1Jesper1** [comment]
@marijnh Thanks for the reply, I will compare it.
