### ISSUE TITLE
Overlapping marks of same type with different attribtues behave strangely

### ISSUE THREAD

**Issue by matej-svejda** [ProseMirror/prosemirror#943]
### Issue details
I have schema where I use marks to identify and track certain parts of the document. They may overlap, i.e. text nodes can have the mark multiple times with different attributes.
Today I noticed a weird behaviour: when you have text marked with two marks with different attributes that partially overlaps, edditing the non-overlapping parts causes strange behaviour: the overlapping part changes or is removed, depending on "which side" you edit it.

### Steps to reproduce

https://glitch.com/edit/#!/deluxe-day

- Edit text that has both marks -> works as expected
- Edit text that only has mark with id 1: the overlapping part dissapear
- Edit text that only has mark with id 2: parts of that text gets moved to the overlapping part.

### ProseMirror version

Current

### Affected platforms
Mac/Linux Chrome

**Comment by marijnh** [comment]
Look into the [`excludes` field](http://prosemirror.net/docs/ref/#model.MarkSpec.excludes) in the mark spec.

**Comment by matej-svejda** [comment]
I forgot to add `exlude: ""` in the minimal example (I had it in my local code). However, adding it to the minimal example code made it work, after which I figured out the problem was my prosemirror-model version: I had 1.7.0 and 1.7.1 included the fix I needed :) Should have checked that everything is up to date before posting, sorry.
