### ISSUE TITLE
Duplicated characters in Safari with IME - unreliable cause and solution

### ISSUE THREAD

**Issue by quirm** [ProseMirror/prosemirror#944]
### Issue details

There is a problem that editor duplicates text characters in Safari, when marks are applied and IME input is active.

![image](http://g.recordit.co/thb9zQujoQ.gif)

### ProseMirror versions

"prosemirror-commands": "^1.0.8",
"prosemirror-dev-tools": "^2.1.1",
"prosemirror-dropcursor": "^1.1.1",
"prosemirror-history": "^1.0.4",
"prosemirror-inputrules": "^1.0.4",
"prosemirror-keymap": "^1.0.1",
"prosemirror-model": "^1.7.1",
"prosemirror-state": "^1.2.3",
"prosemirror-tables": "^0.8.1",
"prosemirror-transform": "^1.1.3",
"prosemirror-view": "^1.9.10",

### Affected platforms

- Safari only as far as I know

### Detailed description

The root cause is not 100% clear to me because I could not reliably reproduce it but I suspect it has something to do with native selection. Please bear with me, this description is a bit longer.

I have two simple test cases:
1. type "n" with Pinyin IME keyboard; capture the log
2. type "n" with Pinyin IME keyboard while mark "bold" is active; capture the log

These two actions are identical, while the second one is causing troubles. I swizzled few methods to find out how stack traces differ under the hood:

![image](https://user-images.githubusercontent.com/236249/60274397-447f1000-98f8-11e9-8f54-e90364e603d3.png)

In Safari, once a selection is re-selected right after `compositionstart`, `compositionend` will not happen anymore and any keypress with an active IME input will be calling redundant `compositionstart`, followed by `compositionupdate`. Event `beforeinput` also will not match correct types in the right order.

I pin pointed the issue in `setSelection` function:
https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L331

There is a blocking part which should prevent re-selection from happening:
https://github.com/ProseMirror/prosemirror-view/blob/master/src/viewdesc.js#L343-L346

I logged the state after the if-clause from the link above (it can be done through a breakpoint):
```
console.log(anchorDOM.node, anchorDOM.offset, domSel.anchorNode, domSel.anchorOffset);
console.log(headDOM.node, headDOM.offset, domSel.focusNode, domSel.focusOffset);
console.log(headDOM.node.textContent);
```

This is the output:

![image](https://user-images.githubusercontent.com/236249/60275116-abe98f80-98f9-11e9-8bdc-9bd1fc75b024.png)

The interesting part is, that an element with the cursor (`anchorDom` or `headDom` in this case) will show `nn` as its content but `node.textContent` is only `n`. Function `isEquivalentPosition` will fail in this case to prevent re-selection and then the whole IME input lifecycle breaks down. I could not figure out why and I could reproduce it only a few times with a single `<div contentEditable=true />` element. My guess is, that something under the hood returns a differently evaluated content in Safari DOM.

**How to fix this?**

Blocking `setSelection` call was the only reliable fix that worked:
https://github.com/ProseMirror/prosemirror-view/blob/master/src/selection.js#L57

I changed it to following as you can't really do too many things or even select text with an active IME input:
```
if (!view.composing) {
  view.docView.setSelection(anchor, head, view.root, force);
}
```

@marijnh, does the change make sense and could be used as a fix? I can create a PR if you are not against it.

**Comment by marijnh** [comment]
Blanket-blocking setSelection when IME is active will also interfere with, for example, inentionally moving the selection away when composing. I'll dig up my macbook and try to look into this soon.

**Comment by quirm** [comment]
I've just tested it again that this fix will cause a reversed problem when no marks are present. For example, typing `ni hao` will start duplicating characters after a space char. No native selection change is involved in this case :/

**Comment by marijnh** [comment]
[This patch](https://github.com/ProseMirror/prosemirror-view/commit/4eb14f6621aa95bb88a47e2c78292217944b5144) might help with this. I've released it as `prosemirror-view@1.9.14-prerelease` — it'd be great if you could test it and report whether it solves this issue.

**Comment by quirm** [comment]
I tested `1.9.14-prerelease` and I can see that the problem with duplication is gone but a new problem with mixed/not-applied marks is happening. There might another IME + marks problem on earlier versions which I did not notice.

I'm trying to type twice 你好, once normal and once in bold. I can't get bold active in `1.9.14-prerelease`. I need to finish the composition and then bold a piece of text and keep writing again in bold. Sometimes, a composition text is normal and sometimes it's bold. Also, just simple cursor navigation over a text is triggering bold on/off (the last line). 

Please check the recordings here (I could not paste the image here as it's somehow not playing the full length):
https://recordit.co/1a16DtR9Io

**Comment by marijnh** [comment]
Ahh, indeed, that is a problem that's caused by not having cursor wrappers. I'm going to have to think about this more.

**Comment by marijnh** [comment]
Please try 1.9.14-prerelease2, which adds a kludge where the editor will wrap the cursor in the appropriate marks on compositionstart (if necessary).

**Comment by quirm** [comment]
I tested it on a "basic example" with 1.9.14-prerelease2 as my repo has other problems in my code.

It's "almost" there. When you type "normal **bold** " and then disable bold and try to type another piece of text, the mark is re-enabled in case of a space in the composition (not sure about the terminology here). I need to disable bold beforehand and start the composition without undesired mark, then it works as expected.

https://recordit.co/AwrGzKhlCg - left safari, right chrome

Isolated problem with marks in Safari:
![image](http://g.recordit.co/bQCju727wB.gif)

Thanks a lot for fixing the original issue. I will close this as the original problem has been resolved. I'm happy to do further testing/debugging if you have other changes for the mark issue.

**Comment by marijnh** [comment]
Thanks for the feedback. Do I understand correctly that the problem occurs when you try to enable/disable marks _during_ a composition? If so yes, that isn't handled yet—and can't be handled without interrupting the composition, since the editor can't touch the DOM that's being composed without interrupting. But maybe interrupting is the right thing to do there. What would be the expected behavior for you?

**Comment by quirm** [comment]
Steps to reproduce:
1. type normal text "你好 "
2. enable bold
3. type bold text "你好 "
4. disabled bold
5. type normal text "你好 "

If the bold mark is disabled and then you start typing, it will be re-enabled during the composition in case of space. But, if there are no marks, e.g. disabled a character before, it will work as expected.

Another gif showing this issue. The first line has the bold mark disabled 1 character before, the second line (attempt) has the bold disabled just before another keypress starting the composition. I'm only clicking on the bold toolbar button, no key shortcuts.
![image](http://g.recordit.co/S22Nyk7G3T.gif)

**Comment by marijnh** [comment]
Which Chinese input method are you using, precisely? I wasn't able to get those characters for 'ni hao', and I'm not seeing the bug happen.

**Comment by quirm** [comment]
I'm using "Pinyin - Simplified", Safari v12.1.2.
I also tried Safari iOS and it works fine.
