### ISSUE TITLE
With whole block selected, block type tooltipMenu

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#95]
I like the `emptyBlockMenu` on new lines, but would also like to have a way to change block type after selecting whole block. Mockup:

![pm-block-selected-mockup](https://cloud.githubusercontent.com/assets/395307/11603956/9aba3f80-9ab4-11e5-8973-055bec4e9972.png)

_(edited title and mockup image dec 4)_

**Comment by marijnh** [comment]
If you select the paragraph (by pressing esc when the cursor is inside it, or by control-clicking), you get the block tooltip menu that allows you to do this. Integrating it with the inline style tooltip seems like it would mix concepts in an awkward way -- selecting some text doesn't really have anything to do with performing actions on the whole block. (I know medium does it this way. I still don't like it.)

**Comment by forresto** [comment]
Another funny thing with the tooltipMenu is that you have to select some text to add an image.

Escape isn't so intuitive there, but I do like seeing the block selection :+1:. What about triple-click, or selecting the whole block?

**Comment by marijnh** [comment]
I guess I could redefine emptyBlockMenu to selectedBlockMenu, and show it both when the cursor is in an empty block and when the whole block is selected.

As for needing to select to insert an image, if you consider the workflow 'type alt text, select, add image', it's not so bad (though it appears that defaulting the alt text to the selection is currently broken), but I guess most people don't think of it this way. I suppose we'll eventually want an 'insert' control, which also lists stuff like horizontal rules, videos, etc, but I'm not sure when to show that in the tooltip menu style. Any ideas?

**Comment by forresto** [comment]
Our images are all going to be block-level. Showing (upload image, link video, ...) on newline makes sense to me. Is there a plan how to plug in to those?

**Comment by marijnh** [comment]
You can attach an insert command to your node type, like `insertHorizontalRule` in edit/commands.js, and add `icon` and `menuGroup: "block"` properties to it to have it show up in the menu

**Comment by marijnh** [comment]
Attached patch renames `emptyBlockMenu` to `selectedBlockMenu` and, as the name suggests, makes it also show block menu items when a non-empty block is entirely selected.
