### ISSUE TITLE
pasted empty Node with block+ content schema not filled properly

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#950]
Hi,
using https://glitch.com/edit/#!/remix/prosemirror-demo-schema

1. modify the schema to allow empty `notegroup` for a moment (`content: "note*"`)
2. empty a `notegroup`, select it, copy it
3. restore original schema (`content: "note+"`)
4. paste empty notegroup: it stays empty

What is expected: that the notegroup gets a note upon pasting.

**Comment by kapouer** [comment]
As far as i understand, `addElementByRule` would need to call something that doesn't exist like `checkAndFill` to post-process the node after it's been parsed. Looks do-able, maybe even PR-able...

**Comment by kapouer** [comment]
I ended up adding a transformPasted plugin with
```
transformPasted(slice) {
	slice.content = fillContent(slice.content);
	return slice;
}
function fillContent(frag) {
	if (!(frag instanceof Fragment)) frag = Fragment.from(frag);
	var list = [];
	frag.forEach((node) => {
		var content = node.content;
		if (content.size) {
			var before = node.type.contentMatch.fillBefore(content);
			if (before) content = before.append(content);
		}
		var after = node.type.contentMatch.matchFragment(content).fillBefore(Fragment.empty, true);
		if (after) content = content.append(after);
		list.push(node.copy(fillContent(content)));
	});
	return Fragment.from(list);
}
```

**Comment by marijnh** [comment]
Attached patch should address this. Could you double-check whether it solves your issue?

**Comment by kapouer** [comment]
Sure, going to check that at sun set !

**Comment by kapouer** [comment]
It fixes the issue when there the dom came from a prosemirror instance indeed.
However i don't understand why it shouldn't do the same with the same dom without the slice-data attribute.

**Comment by marijnh** [comment]
Because then it won't force the `openStart`/`openEnd` properties, so the thing that comes from the parser can be trusted.

**Comment by kapouer** [comment]
Ok, but it parser fails the exact same way in that precise case.

**Comment by marijnh** [comment]
The parser isn't actually failing here.
