### ISSUE TITLE
[feature request]Need Official Typescript support

### ISSUE THREAD

**Issue by lwyj123** [ProseMirror/prosemirror#952]
### Issue details
Maybe we need to do something for the trend of Typescript. Now most of my code is written using typescript, But the prosemirror's types support is not complete.

**Comment by marijnh** [comment]
I'm sympathetic to that, and eventually it'd be nice to port ProseMirror to TypeScript entirely. (It started as typed code, but at the time neither Flow nor TypeScript were mature enough to warrant the extra friction—but by now TypeScript has come a long way, and using it in CodeMirror 6 has been a great experience.)

However, I don't see myself having time to do this in the near future, and it'd involve finnicky stuff like porting over our documentation generation to another approach.

So for now, I recommend continuing to submit fixes to the types provided by definitelytyped when you notice problems.

**Comment by lcswillems** [comment]
I don't know if you heard about it but with the latest version of TypeScript (3.7), the `--declaration` and `--allowJs` can be used together (https://github.com/microsoft/TypeScript/issues/7546). It means that typings can be directly generated from JS code. It might help in your case?

Moreover, a JS codebase can be progressively moved to a TypeScript one. So, some files can be first transformed into TypeScript, some other later, and so on...

**Comment by ocavue** [comment]
Most packages are maintained by @marijnh, but `prosemirror-tables` is not. See this https://discuss.prosemirror.net/t/why-is-prosemirror-tables-not-maintained/4522/2

Porting prosemirror-tables is on my list, but I don't have ETA for it.

**Comment by PowerKiKi** [comment]
Would you accept a PR that replicate what @marijnh did for other packages, specifically leveraging [`@prosemirror/buildhelper`](https://github.com/ProseMirror/buildhelper) ?

**Comment by ocavue** [comment]
I would appreciate a PR.

**Comment by PowerKiKi** [comment]
> I would appreciate a PR.

See https://github.com/ProseMirror/prosemirror-tables/pull/183 for the work in progress

@lwyj123 or @marijnh could you please close this issue, since all packages that you maintain are available as Typescript ?
