### ISSUE TITLE
[prosemirror-view] posAtCoords can throw exception in Firefox when cursor is over a non-empty input[type="text"]

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#953]
### Issue details

In Firefox it's possible for `posAtCoords` to throw an exception when accessing a property of `undefined`. It reproduces in Firefox (but not Chrome) due to the browsers seemingly having different behaviour of `caretPositionFromPoint`.

When the cursor is over an `<input type="text" value="e" />` (it's important that it's not empty) and `posAtCoords` is called, the following code is executed:

```js
function posAtCoords(view, coords) {
  var root = view.root, node, offset;
  if (root.caretPositionFromPoint) {
    var pos$1 = root.caretPositionFromPoint(coords.left, coords.top);
    if (pos$1) {
      var assign;
      ((assign = pos$1, node = assign.offsetNode, offset = assign.offset));
    }
  }
  // †
```

† At this point in Firefox `node` is the INPUT, and offset is `1`. In Chrome both of these are `undefined`.

The exception is thrown further down in that function:

```js
 if (node) {
    // Suspiciously specific kludge to work around caret*FromPoint
    // never returning a position at the end of the document
    if (node == view.dom && offset == node.childNodes.length - 1 && node.lastChild.nodeType == 1 &&
      coords.top > node.lastChild.getBoundingClientRect().bottom) { pos = view.state.doc.content.size; }
    // Ignore positions directly after a BR, since caret*FromPoint
    // 'round up' positions that would be more accurately placed
    // before the BR node.
    else if (offset == 0 || node.nodeType != 1 || node.childNodes[offset - 1].nodeName != "BR") { pos = posFromCaret(view, node, offset, coords); }
  }
```

`node.childNodes[offset - 1].nodeName` throws, because `node.childNodes.length` is `0`, so it ends up evaluating `undefined.nodeName`. It looks like there's an assumption in this code that `offset > 0` from `caretPositionFromPoint` implies there are child nodes, however this is not the case with a text input (at least in Firefox).

I have the text input in my editor as part of some extra widget interactions that let the user type in data that's not stored directly as text in the doc.

### ProseMirror version

prosemirror-view 1.8.7–1.9.11 (probably a wider range, but this is all I tested).

### Affected platforms

- [ ] Chrome (tested)
- [x] Firefox
- [ ] Safari (tested)
- [ ] Internet Explorer (maybe?)
- [ ] Other (maybe?)

**Comment by marijnh** [comment]
Hah, thanks for diagnosing that. Attached patch should fix it.
