### ISSUE TITLE
Cannot focus child widget of non-editable Editor

### ISSUE THREAD

**Issue by isTravis** [ProseMirror/prosemirror#954]
### Issue details

We have a non-editable (`editable: () => false`) Editor. In that editor we have a Decoration Widget with `stopEvent: () => true` and the DOM content of the widget is an HTML `<span />` with a few children, one of which is an `<input />` field. When clicking on the input field, it is impossible to focus the element.

It appears that focus is being stolen by the parent. We wish to be able to focus and type within the element even though the parent ProseMirror Editor is not editable. 

Surprisingly, this is not an issue if I remove `editable: () => false`, or if the `<input />` is the first sibling, rather than the second or Nth.

Tracing the code down leads us to the [`selectionToDOM` function](https://github.com/ProseMirror/prosemirror-view/blob/f1eece9045c35cc39d5b708b89a6428e7fe859f5/src/selection.js#L29). The logic here is clearly handling a number of edge cases, so apologies if I'm misunderstanding it, but should [line 41](https://github.com/ProseMirror/prosemirror-view/blob/f1eece9045c35cc39d5b708b89a6428e7fe859f5/src/selection.js#L41) actually read `else if (!view.editable || !hasSelection(view) || !takeFocus)`? That is ORs instead of ANDs.

It seems to me that in each of those cases (the view is not editable, the view does not have a selection, the view should not takeFocus) you simply want to return.

### Steps to reproduce

https://glitch.com/edit/#!/ten-sovereign?path=index.js

### ProseMirror version

prosemirror-view@1.9.11

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [?] Internet Explorer

**Comment by marijnh** [comment]
Context for that code can be found in [this thread](https://discuss.prosemirror.net/t/selection-changes-when-inline-decoration-is-applied/1027). In short, the editor is trying to sync the DOM selection with its internal selection even for uneditable editors _if_ the selection is already in/on the editor. It was just defining that latter condition in too simple a way. Does attached patch help for you?

**Comment by isTravis** [comment]
Fantastic - thanks for the context. Yes, the attached patch resolves the issue in our setup!
