### ISSUE TITLE
prosemirror-commands is having other core modules as strong dependencies

### ISSUE THREAD

**Issue by mgenware** [ProseMirror/prosemirror#956]
### Steps to reproduce

prosemirror-state, prosemirror-view and prosemirror-commands are all core modules, it seems that prosemirror-commands is having other core modules as strong deps and doesn't keep them updated ([source](https://github.com/ProseMirror/prosemirror-commands/blob/master/package.json#L18)), so users will always end up with multiple versions of prosemirror-state and prosemirror-view installed.

Thanks for this great library!

### ProseMirror version

Latest

**Comment by marijnh** [comment]
It depends on `^1.0.0` of those packages, which will match any stable version, so I don't see how this could keep them from updating.

(Note, npm is sometimes stupid about upgrading dependency trees, and occasionally such problems go away by deleting `node_modules` and `package-lock.json` and reinstalling.)

**Comment by mgenware** [comment]
Thanks, deleting `node_modules` and reinstalling solves the issue
