### ISSUE TITLE
Keymaps that contain 'Ctrl'  on windows for non-latin languages dont fire.

### ISSUE THREAD

**Issue by nathf** [ProseMirror/prosemirror#957]
### Issue details

For languages like Russian, trying to use a keymap like `Ctrl+b` or `Ctrl+z` end up no-oping.

Looks like the keymap plugin is not checking `event.ctrlKey` on this line (adding that check fixes the issue): https://github.com/ProseMirror/prosemirror-keymap/blob/469840b1e50e2a8ba1463313f05f8aa1a9133539/src/keymap.js#L86

Not sure if that was an intentional omission or not.

### Steps to reproduce

Using a non-latin based keyboard layout (e.g. Russian) on Windows, navigate to http://prosemirror.net/ and attempt to toggle bold in the example editor, using the keymap `Ctrl+b`

### ProseMirror version

Latest

### Affected platforms

- [X] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Hi. Please see [this thread](https://discuss.prosemirror.net/t/mod-keymap-binding-on-non-english-layout-in-windows/1975). I believe the expectations for Cyrillic script users (and possibly other languages, but I haven't run into them yet) in this case differ from those of other scripts when it comes to the behavior of key handlers bound to Latin combinations. Please review the suggestion I make towards the end of the thread and tell me whether it makes sense to you.

**Comment by nathf** [comment]
Hey @marijnh, thanks for that handy link. I think I understand what you mean, for example a qwertz keyboard hitting the fallback could emit incorrect events. I'll try a different approach, thanks!
