### ISSUE TITLE
Caret still invisible after hideselection removing from classes.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ProseMirror/prosemirror#958]
For reproduce check gift:
https://github.com/scrumpy/tiptap/issues/405#issuecomment-514813824

Also image overflow caret.

Can be reproduced on prosemirror.net too.

**Comment by afwn90cj93201nixr2e1re** [comment]
@marijnh

**Comment by afwn90cj93201nixr2e1re** [comment]
Is that issue duplicate of https://github.com/ProseMirror/prosemirror/issues/958 ?

**Comment by marijnh** [comment]
Can you condense your reproduction steps to a precise list of actions (in text, not screencast)? I can't understand the ones in the issue you linked.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/ProseMirror/prosemirror/issues/583#issuecomment-514819708

At site everything is described.

**Comment by marijnh** [comment]
Right, I guess this is a duplicate of #583 then.
