### ISSUE TITLE
Node in NodeSelection is different from Node in State

### ISSUE THREAD

**Issue by gaetansnl** [ProseMirror/prosemirror#959]
### Issue details

Selection seem inconsistent with state

### Steps to reproduce
Dispatch a transaction
```javascript
export default (pos) => {
    return (state, dispatch) => {
            dispatch(
                tr.setNodeMarkup(pos, null, { ....... }).setSelection(state.selection)
            );
        return true;
    };
};

```
In a nodeview
```javascript
update(view) {
    const selection = view.state.selection;
    if (selection instanceof NodeSelection) {
        // The two node attrs are different
        console.log(selection.node); //Still old attrs
        console.log(view.state.doc.nodeAt(selection.from)); // new attrs
    } 
}
```

### ProseMirror version

```
        "prosemirror-commands": "^1.0.8",
        "prosemirror-gapcursor": "^1.0.4",
        "prosemirror-keymap": "^1.0.1",
        "prosemirror-model": "^1.7.1",
        "prosemirror-schema-basic": "^1.0.0",
        "prosemirror-state": "^1.2.3",
        "prosemirror-view": "^1.9.12",
```

**Comment by marijnh** [comment]
Where does `tr` come from in the top code snippet?

It is possible to call `setSelection` with an invalid selection (a selection whose resolved positions point into the wrong document). But I consider that an error on the part of the code that calls `setSelection`. It would be possible to check for this, though the current code doesn't do so. If you want to submit a pull request that adds such a check, that'd be welcome.

**Comment by gaetansnl** [comment]
I thought the ResolvedPos wasn't related to the document. 
I will try to make a PR at the same time I fix this code
