### ISSUE TITLE
[prosemirror-view] focus() prevent IE scroll

### ISSUE THREAD

**Issue by petermatik** [ProseMirror/prosemirror#962]
When calling pmView.focus() from other element, IE scrolls document to top so maybe we could enhance focus method like this:

```
focus() {
	this.domObserver.stop()
	selectionToDOM(this, true)
	this.domObserver.start()
	
	//if (this.editable) this.dom.focus()

	if (this.editable) {		
	    if ( this.dom.setActive  ) {
	    	// non-standard setActive for IE11
	    	this.dom.setActive();
	    } else {
	    	// BAU (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)
	    	this.dom.focus({preventScroll: true})
	    }
    }
}
```

**Comment by marijnh** [comment]
`selectionToDOM` with `true` as second argument will already make sure that the element is focused if it isn't already, so it seems that this extra call to `focus` was redundant. I've removed it in [this patch](https://github.com/ProseMirror/prosemirror-view/commit/2156afbca154f5270dd378e71a8c32fe413bee71), which seems to resolve the IE scroll position issue.

**Comment by petermatik** [comment]
So I guess it's just my implementation because without additional code
 IE keeps scrolling to top when view.focus() is called.

![ie_focus](https://user-images.githubusercontent.com/5718113/62527811-28965480-b83c-11e9-8392-fb402fdf59d6.gif)

**Comment by marijnh** [comment]
Odd. Can you set up a minimal demo of the issue? Is the scrolling happening on the body or in a container element?

**Comment by petermatik** [comment]
Scrolling is happening on the body in my test editor (https://github.com/heyhou/simpleeditor) but I just checked example at http://prosemirror.net/examples/basic/ and IE scrolls there as well:

![ie_focus (1)](https://user-images.githubusercontent.com/5718113/62561495-9fa10c80-b87f-11e9-8fbf-9459ff2f58fe.gif)

**Comment by marijnh** [comment]
Using the link menu item to test might be misleading—that calls `toggleMark` which in turn creates a `scrollIntoView` transaction, so there scrolling into view is the expected behavior.

**Comment by petermatik** [comment]
It looks like latest version doesn't have `if (this.editable) this.dom.focus()` that was causing IE to scroll to top on focus so everything behaves as expected. Thanks for checking.

**Comment by marijnh** [comment]
Oh, my patch seems to work with Firefox and IE, but breaks focusing on Chrome/Safari. Also, the thing I claimed before about `selectionToDOM` calling `focus` is nonsense.

I've implemented your patch in https://github.com/ProseMirror/prosemirror-view/commit/24e0ab1f6e445a421e444ca89d2241d7e7faecae . Let me know if that works for you.

**Comment by petermatik** [comment]
I wasn't able to reproduce this issue on Chrome/Safari but the patch works for me in all browsers. Thanks.
