### ISSUE TITLE
Pressing End key scrolls to end of webpage instead of moving caret

### ISSUE THREAD

**Issue by bjoernm** [ProseMirror/prosemirror#963]
### Issue details

If a caret is placed inside a paragraph in the editor, pressing the End key scrolls to the end of the webpage instead of moving the caret correctly to end of a paragraph if the browser window is scrollable.

### Steps to reproduce

1. Go to https://prosemirror.net
2. Make sure the height of the browser window is small enough that the webpage is scrollable
3. Place caret anywhere inside the editor except of the last position in a paragraph
4. Press End key

Expected behaviour: Caret is moved to the end of paragraph
Actual behaviour: Browser scrolls to the end of the webpage
Additional note: Pressing End key a second time jumps to correct page position and moves caret to the correct position in editor

### ProseMirror version

latest

### Affected platforms

- [x] Chrome 76, macOS
- [x] Firefox 68, macOS

**Comment by marijnh** [comment]
Confirmed (finally got my macbook charged after the adaptor cable broke once again).

This seems to be default behavior on OS X. If I focus a textarea or generic contenteditable div and press Fn-Right (no dedicated End button on my keyboard, but this generates an End key event so I guess it's exactly equivalent), it also scrolls down to the bottom of the document.

So the question is, should ProseMirror interfere with this default behavior, or is there some logic to it? Ctrl-E seems to be the 'move to end of line' shortcut. Any macOS experts want to chime in?

**Comment by marijnh** [comment]
I asked around on Twitter, and experienced Mac users seem to expect this and would be annoyed if it was changed. You can use a snippet like the code below (untested) to override this, but I don't think the library core should. (Cmd-Right seems to be the usual way people move to end of line.)

```
keymap({"End": (state, dispatch) => {
  if (!state.selection.$from.parent.isTextblock) return false
  if (dispatch)
    dispatch(state.tr.setSelection(TextSelection.create(state.doc, state.selection.$from.end())).scrollIntoView())
  return true
}})
```

**Comment by bjoernm** [comment]
Thank you for your answer and checking on Twitter. Some text and code editors (e.g. Google Docs, VSCode, IntelliJ) seem to override this behaviour on macOS, but overall it might be a better trade-off to keep it consistent with the platform.
