### ISSUE TITLE
elementFromPoint can produce an "Cannot read property of undefined" error

### ISSUE THREAD

**Issue by matej-svejda** [ProseMirror/prosemirror#966]
### Issue details

`elementFromPoint` in prosemirror-view in domcoords.js can produce `Cannot read property 'nodeType' of undefined` when accessing `child.nodeType`.

### Steps to reproduce

I dont have a concrete example that can reproduce this, I was just seeing the error in our error tracking software. However, I found a configuration of parameters where `startI >= len` causing the child to be undefined because the index is invalid:

```
let coords = { left: 2, top: 2 }
let box = { left: 0, top: 0, right: 3, bottom: 1 }
inRect(coords, box) // thats true
box.top < box.bottom // also true
(coords.top - box.top) / (box.bottom - box.top)
// thats 2 so not <= 1, causing startI to become >= len if len >= 2
```
So unless Im missing something that could be an explanation of the error. I guess just adding `Math.min(len - 1, startI)` should fix this.

### ProseMirror version
prosemirro-view 1.10.1

### Affected platforms
All

**Comment by marijnh** [comment]
Thanks for the report. Attach patch makes sure the index is always in range.
