### ISSUE TITLE
Impossible to enter text in text nodes above a hard break in IE

### ISSUE THREAD

**Issue by dddotsev** [ProseMirror/prosemirror#967]
At the time of writing this the issue is reproducible in the prosemirror website.

### Steps to reproduce

1. Create a few hard breaks (more than 2)
2. Enter some text
3. Press the up arrow to go to the line above
4. Try entering text

The cursor will be moved even higher and it won't be possible to enter text

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer

### Screencast

![ezgif-3-8cdd4985cfdb](https://user-images.githubusercontent.com/3427814/64026003-976a8300-cb46-11e9-9641-a0ba39576941.gif)

**Comment by marijnh** [comment]
The mutation records IE produces in this situation are wrong. Attached patch kludges around that.

**Comment by cmlenz** [comment]
Unfortunately this seems to be happening again with the latest version (prosemirror-view 1.11.3)

**Comment by marijnh** [comment]
Huh, indeed, it still occurs. Not sure why, maybe we just only tested and fixed one specific case of a bigger issue last time. Attached patch should fix this in in a more robust way.

**Comment by TheRealNic** [comment]
Thanks, this patch fixed our issue 👍
