### ISSUE TITLE
Problem with whitespace selection in IE 11

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#968]
### Issue details

We wrote a custom input rule, which retains a trailing whitespace in a selection on replacing this selection. This works in Chrome without a problem and used to work in IE 11 up to and including prosemirror-view version 1.8.9. The next version broke this functionality, since the whitespace is no longer included in the selection (but only in IE 11).

### Steps to reproduce

Glitch: https://glitch.com/edit/#!/radial-bicycle?path=index.js:37:0

1. Select a word with a trailing space
2. Start typing

Expectation: The whitespace is retained
Reality: The whitespace is not retained.

The glitch demo is unfortunately not working in IE, since glitch doesn't supprt IE, but you can at least review the code and maybe include the input rule in your own test system.

### ProseMirror version

This problem startet occuring with versions after 1.8.9 of prosemirror-view.

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [ ] Other

**Comment by petermatik** [comment]
My fix might require additional review but I did solve several IE specific issues with following addition to [DOMObserver](https://github.com/ProseMirror/prosemirror-view/blob/master/src/domobserver.js#L43):

```
if (useCharData) {
  this.onCharData = e => {
    // IE fix 
    this.disconnectSelection();
    // BAU
    this.queue.push({target: e.target, type: "characterData", oldValue: e.prevValue})
    window.setTimeout(() => this.flush(), 20)        
  }
}
```

As mentioned [elsewhere](https://discuss.prosemirror.net/t/problems-with-replacing-non-empty-selection-in-ie11/2180/3?u=pet), I suspect this is related to selectionchange event being fired out of order in IE.

Let me know if this works for you.
P.

**Comment by TheRealNic** [comment]
Unfortunately this doesn't seem to fix our problem, but thanks for the comment.

**Comment by petermatik** [comment]
Interesting... Your input rule is working for me. However, when I remove additional code - `this.disconnectSelection()`, this rule is failing as described.  Are you using latest version of prosemirror-view (1.10.1)?

**Comment by petermatik** [comment]
UPDATE: I tried this in IE on Windows instead VM and indeed proposed solution doesn't work. 
However, when I adjusted also MutationObserver callback it fixed the issue for me:

```
constructor(view, handleDOMChange) {
  this.view = view
  this.handleDOMChange = handleDOMChange
  this.observer = window.MutationObserver &&
    new window.MutationObserver(mutations => {      
      if (browser.ie && browser.ie_version <= 11)
        // IE Fix
        this.disconnectSelection();
        setTimeout(() => this.flush(mutations), 10)
      else
        this.flush(mutations)
    })
  this.currentSelection = new SelectionState
  this.queue = []
  if (useCharData) {
    this.onCharData = e => {
      // IE Fix
      this.disconnectSelection();
      // BAU
      this.queue.push({target: e.target, type: "characterData", oldValue: e.prevValue})
      window.setTimeout(() => this.flush(), 20)
    }
  }
  this.onSelectionChange = this.onSelectionChange.bind(this)
  this.suppressingSelectionUpdates = false
}
```

Probably this is still not definitive answer but at least I have temporary solution.

P.

**Comment by marijnh** [comment]
Attached patch should help with this. IE breaks overwriting into two different steps, first deleting the selected text, and then inserting something new in its place, and fires events for these separately. There was already a kludge for a similar situation, which attached patch extends to also handle this one.

**Comment by petermatik** [comment]
Great. Thanks! Removed my workaround and this patch solved all issues I had in IE 11. 

There is still one more IE specific behaviour that bothers me and maybe it is related to this.
When you delete selected text at the begging of the node, selection will not collapse afterwards but remaining text is selected. Not a big deal but one would expect this will end up just with a blinking caret at the begging.

**Comment by TheRealNic** [comment]
Thank you, the new version is working great!

**Comment by marijnh** [comment]
> When you delete selected text at the begging of the node, selection will not collapse afterwards but remaining text is selected.

I'm not seeing this. Could you go through what you're doing step-by-step (how do you select, how do you delete)?

**Comment by petermatik** [comment]
I just select the text at the begging (mouse drag, double click, shift + arrow...) and hit Backspace or Delete. Attached GIF is showing 2 examples of this behaviour. 

![ie-delete-selected](https://user-images.githubusercontent.com/5718113/64269988-1e4e9f80-cf3b-11e9-85a1-3914aff3c957.gif)

**Comment by marijnh** [comment]
Strange. That's doesn't happen when I do this.

**Comment by TheRealNic** [comment]
Just FYI: I too can reproduce this issue in the prosemirror web demo

**Comment by petermatik** [comment]
Probably this is happening only in IE 11 because when I tried to reproduce this in IE Edge 15+ there was no issue.  Unfortunately I still need to support IE 11 so probably will keep to this one on radar until somebody starts to complain. 

Only difference I can see so far is that anchorNode and also focusNode from `this.view.root.getSelection()` in `setCurSelection()` is showing text in Chrome, but IE 11 is showing me paragraph after the text is deleted. I was thinking if we could somehow catch this case and force `selectionToDOM(view, takeFocus, force)`.  But I am not sure if this observation is relevant.

**Comment by TheRealNic** [comment]
I have created a new issue for this bug: https://github.com/ProseMirror/prosemirror/issues/973
