### ISSUE TITLE
descendants documentation problem

### ISSUE THREAD

**Issue by MrErHu** [ProseMirror/prosemirror#972]
> descendants(f: fn(node: Node, pos: number, parent: Node) → ?⁠bool)
Call the given callback for every descendant node. Doesn't descend into a node when the callback returns false.

descendants Implemented by the function nodesBetween, Therefore the fourth parameter should be supported: index，but document do not have this。Is this intentional?
Can I create PR to fix this problem?

**Comment by marijnh** [comment]
I think the extra parameter to `nodesBetween` wasn't public initially, either. I'd be okay with exposing it in `descendants` too.

**Comment by MrErHu** [comment]
@marijnh  May I can create PR to fix this?

**Comment by marijnh** [comment]
Yes.

**Comment by pasDamola** [comment]
should the descendants function have a default index of 0?

**Comment by marijnh** [comment]
I suppose so, yes.
