### ISSUE TITLE
Problems with mark content overriding in IE 11

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#974]
### Issue details

When selecting a mark and replacing the selection by typing, the the mark is lost and the cursor jumps to different position (end of the node).

### Steps to reproduce

1. Open http://prosemirror.net/ in IE11
2. Double click on “examples” to select the whole link
3. Type character “a”
4. Observe how the link is removed and the “a” is actually inserted behind the period at the end (bearbeitet) 

### Affected platforms

- [ ] Internet Explorer

### Screenshots / Screencast (Optional)

![Mark selection](https://user-images.githubusercontent.com/8322279/64848175-f1704b80-d610-11e9-917f-9b26379fed16.gif)

**Comment by marijnh** [comment]
Hah, this one only occurs with the dev tools _closed_ (seems the order in which events are delivered changes when you open the dev tools).

Attached patch (released as prosemirror-view 1.11.1) should help with this. It was another case of replacement changes leading to bizarre change/selection event ordering, which threw off ProseMirror's DOM observer.

**Comment by TheRealNic** [comment]
Hi Marjin, this issue is unfortunately not completely patched, I've extended the reproduction repo (https://github.com/mediatis/pm975-repro) to reflect this situation. Basically the patch you've added works, when only one editor view is present in the dom but fails, if there are multiple editor views.

Reproduction steps:
1. Open the repo as described in the readme
2. Select the placeholder in the first Editor View
3. Type some text ("hello") 
4. The text gets inserted at the end of the node, just like the original poster described.

![mark selection on multiple editors](https://user-images.githubusercontent.com/8322279/65140523-07b24900-da0f-11e9-8eb3-b9c211d170eb.gif)

Any help would be greatly appreciated.

**Comment by marijnh** [comment]
> but fails, if there are multiple editor views

Wow, that's a new one. Attached patch seems to cover this case as well.

**Comment by TheRealNic** [comment]
Yeah, we were pretty suprised too, thank you for the fix :)
