### ISSUE TITLE
IE 11 custom mark selection problem

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#975]
### Issue details

We have anothe issue, we had hoped would stem from the same problem as issue https://github.com/ProseMirror/prosemirror/issues/974 , but unfortunately this wasn' resolved by version 1.11.1.
When we select a node with a custom mark type and start typing, the first letter of the editing gets lost and the mark completely replaced. The mark is defined as inclusive.

### Steps to reproduce

1. Select a custom mark.
2. Type hello

### Affected platforms

Internet explorer 11

### Screenshots / Screencast (Optional)

![Mark selection typing](https://user-images.githubusercontent.com/8322279/64949920-8cb82980-d87a-11e9-9d5f-446afb6beb0e.gif)

**Comment by TheRealNic** [comment]
It's hard to see, but you actually see the h in "hello" appear, but then get deleted and the rest getting inserted...

**Comment by marijnh** [comment]
Please tell me what the custom marks is, or at least how it is rendered.

**Comment by cmlenz** [comment]
We are working on a minimal reproduction right now.

**Comment by cmlenz** [comment]
Okay I finally managed to get a minimal test going that demonstrates the problem. It's here: 

https://github.com/mediatis/pm975-repro

The gist of the setup is an inclusive mark type for which we also create inline decorations. The code for this is pretty standard I would say: https://github.com/mediatis/pm975-repro/blob/master/src/placeholder.js

Unfortunately in IE11 this leads to the error described in this ticket, and more. precisely in the README of that repo, from which I quote:

> 1. JS illegal argument error
>    - Select the word "placeholder" (it should be light blue). *Don't include the space following > the placeholder in the selection.*
>    - Type a character
>    - Observe an "illegal argument" error being listed in the console
> 2. Typed input discarded, mark removed
>    - Select the word "placeholder ". *Include the space at the end.*
>    - Type a character
>    - Note that the typed character is not shown and the placeholder mark is also gone
> 
> In my testing there was no difference between selecting with the keyboard and mouse.

The illegal argument error is from the `renderDescs` function.

**Comment by cmlenz** [comment]
@marijnh BTW if there's a better way to setup such a repro please let me know. Glitch doesn't work on IE11 and I have been struggling a bit to find the best way to make this. Hope this works.

**Comment by marijnh** [comment]
Ah, right, testing in IE is extremely painful since none of the infrastructure that we're used to works. Just linking to a gist or text file with the code and HTML necessary would also have worked.

The second issue you describe happened in all browsers, and should be addressed by ecf9e28c4d. The first was indeed very similar to the other bunch of IE11 typeover issues we saw, and is addressed by cbda274c79.

**Comment by TheRealNic** [comment]
Thanks so much, this solved our issue :)

**Comment by cmlenz** [comment]
Hurray, thanks so much Marijn!
