### ISSUE TITLE
Prosemirror occasionally gets out of sync with dom during certain mutations on Chrome

### ISSUE THREAD

**Issue by jljorgenson18** [ProseMirror/prosemirror#976]
### Issue details

This is a bit hard to describe but we noticed an issue with our forecolor mark. When replacing text by right clicking on a misspelled word and picking a replacement, our forecolor mark seemed to disappear. However, we noticed it hadn't actually disappeared in the prosemirror doc. After a ton of research, we realized that Chrome was seeing `<span style='color: someColor;'>Some text</span>` and it was trying to turn that span into `<font color='someColor'>Some text</font>`. Even with that crazy mutation, it seemed like this would still be handled in prosemirror but for some reason, prosemirror skipped the mark update. 

We resolved this bug by adding a dummy data attribute to trick Chrome, but this seemed to expose an underlying prosemirror issue.

### Steps to reproduce

1. Go to https://glitch.com/edit/#!/evergreen-flare?path=index.js:50:54
2. Enable a color using mod-o
3. Type a misspelled word (e.g. "This is horrable")
3. Right click on the misspelled word and pick a replacement

### ProseMirror version

1.10.3

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

Might happen on others but I didn't see any issues yet.

### Screenshots / Screencast (Optional)

![ezgif-5-dedbb3644d5d](https://user-images.githubusercontent.com/5751354/64995504-06fba480-d8a1-11e9-883a-936a8254358a.gif)

**Comment by marijnh** [comment]
Does it help when you add a `parseDOM` entry that covers the output your `toDOM` property produces?

**Comment by jljorgenson18** [comment]
It does not. I confirmed that it was running through our parser and it was match our rule. That example has two rules that will end up parsing resulting HTML.

**Comment by marijnh** [comment]
Ah, sorry, I read your `parseDOM` rule wrong.

What was happening is that Chrome, for reasons we probably don't want to think about, cleared the style on the original `<span>` element when it replaced that element with a `<font>` element. After the change, ProseMirror restored the old span element, but didn't realize that it had been vandalized, leading to an incorrect DOM structure.

Attached patch marks nodes that the browser removed from the DOM as dirty, so that they'll be redrawn, in case something like this happens.

**Comment by jljorgenson18** [comment]
Awesome! That makes a lot of sense. When logging all of the mutations, I missed the span mutation and just saw the font tag being added. I'll keep the workaround in because there are less mutations that fire but hopefully this fixes other issues as well. We saw something similar for our font-size mark so it is probably not a one-off problem.
