### ISSUE TITLE
handleTextInput not called for typeOver

### ISSUE THREAD

**Issue by hitsthings** [ProseMirror/prosemirror#978]
### Issue details

If 'j' is selected and I type 'j', handleTextInput is not called.

### Why this matters to me

I have a word-by-word mode that treats the document in a more word-by-word fashion than character-by-character (e.g. arrow keys navigate to next/prev word). This is for a specialized editing use case (I recognize the UX would be awful in most cases).
- I use appendTransaction to always snap the selection to word boundaries.
- I use handleTextInput to append the typed text to the selected word in some cases, rather than overwrite the selection. Otherwise you'd be limited to single character words. E.g. You click the word 'stop' to select it and type 'g' then 'o': we want to end up with the word 'go', not 'stopgo' and not 'o'. So 'g' should overwrite 'stop', but 'o' should not overwrite 'g'.

### Steps to reproduce

https://codesandbox.io/embed/prosemirror-example-qzhtb

Type j here a bunch of times and notice that the count only increments on every other call.

### ProseMirror version

"latest" in package.json

### Affected platforms

- [x] Chrome
- [?] Firefox
- [?] Internet Explorer
- [?] Other

**Comment by hitsthings** [comment]
`readDOMChange` dispatches a `replaceSelectionWith` directly, which circumvents `handleTextInput`.

**Comment by marijnh** [comment]
Good point. Attached patch fixes this.
