### ISSUE TITLE
transform.Mapping.invert (still) not part of the public API?

### ISSUE THREAD

**Issue by bradleyayers** [ProseMirror/prosemirror#979]
### Issue details

https://github.com/ProseMirror/prosemirror-transform/blob/master/CHANGELOG.md says that [transform.Mapping.invert](https://prosemirror.net/docs/ref/#transform.Mapping.invert) is now part of the public API, but the link to the docs doesn't work and it's not listed on the page.

**Comment by marijnh** [comment]
Looks like the reference guide build process hadn't been triggered since May (due to npm setting file timestamps to some long-past date and make thus treating them as not-changed). The method should be there now.

**Comment by bradleyayers** [comment]
Thanks!
