### ISSUE TITLE
can't click in selection to unselect

### ISSUE THREAD

**Issue by forresto** [ProseMirror/prosemirror#98]
I expect single-clicking a selection to unselect and set cursor. Instead, the selection blinks and resets itself. You have to click outside of the selection to unselect,

![pm-triple-click](https://cloud.githubusercontent.com/assets/395307/11609547/bc8a4238-9b57-11e5-9a1d-71313b90616d.gif)

**Comment by bjoernm** [comment]
+1

**Comment by marijnh** [comment]
I was able to reproduce this. Attached patch should help.

**Comment by forresto** [comment]
I'm still seeing this in master, whether selection is made with shift+arrow, click+drag, or double-click.

**Comment by marijnh** [comment]
Which browser?

**Comment by forresto** [comment]
Both Chrome 47 and Firefox 42.

**Comment by marijnh** [comment]
Ugh, I messed up the code and somehow did observe it to work in my manual test. But you are right, it did not. Attached patch should improve the situation.
