### ISSUE TITLE
Shift-Mod-number key bindings not working in IE 11

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#986]
### Issue details

Keymap bindings to "Shift-Mod-" and a number key don't seem to work in IE 11.

### Steps to reproduce

1. Go to prosemirror.net
2. Place the cursor in some text
3. Press Shift-Cmd-1

In  Chrome this results in the text getting transformed to a heading of level 1, but in IE 11 nothing happens. I tried this in our own environment with a command that just prints something on the console, but even this didn't work in IE 11. Therefore I think, that the problem lies in the key binding in IE.

### Affected platforms

- [ ] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
IE appears to put the wrong value into `event.key` when shift is held. If you update the w3c-keyname package (a dependency of prosemirror-keymap) to 2.1.1 this should be better.

**Comment by TheRealNic** [comment]
Hi Marijn, unfortunately this did not solve our problem. The reproduction on the prosemirror homepage also still stands, but I'm not sure if you're using the latest version of w3c-keyname.
If you need any more info on this ticket, don't hesitate to ask...

**Comment by marijnh** [comment]
Ah, the prosemirror-keymap on npm lagged behind the one on github since I hadn't made a release after upgrading the w3c-keyname dependency. Try again with prosemirror-keymap 1.0.2

**Comment by TheRealNic** [comment]
Now it works, thanks so much 👍
