### ISSUE TITLE
view: observeOptions attributeOldValue

### ISSUE THREAD

**Issue by kapouer** [ProseMirror/prosemirror#988]
Hi,

for some reason i need to get attributes old value in the record passed to a nodeView's ignoreMutation method (i need to track pure ui changes to class attributes).
To be able to do that, i need to read record.oldValue, however it's populated only if prosemirror-view DOMObserver observeOptions.attributeOldValue = true.
Can you set that please ? Would this have a performance impact ? It seems fairly well supported by old browsers.

**Comment by marijnh** [comment]
Added in attached patch.
