### ISSUE TITLE
Does it support offline use case?

### ISSUE THREAD

**Issue by coodoo** [ProseMirror/prosemirror#99]
Just wondering does prosemirror support editing while offline and sync after the internet connection is restored? Thanks!

**Comment by marijnh** [comment]
Nope. I go into that a little in my [blog post](http://marijnhaverbeke.nl/blog/collaborative-editing.html) on collaborative editing. Merging 'branches' is a different problem from real-time collaboration, and would be best served with an interactive diff-based interface, which does not exist yet. But I do think ProseMirror's document model would allow such a thing to be implemented in external code.

It is out of scope for this project/repository for the time being, though.

**Comment by coodoo** [comment]
Thanks for the reply!
