### ISSUE TITLE
Improvement: Inform when a NodeView::update is missing `return true`

### ISSUE THREAD

**Issue by hitsthings** [ProseMirror/prosemirror#990]
### Issue details

I was foolish and didn't `return true;` from my update method. Everything worked fine, except there was a massive performance hit since all the child nodes got re-rendered on every keypress (~30ms per character). This took a bunch of manual debugging to figure out (I didn't notice the problem til much later).

I think one thing that got me was I misunderstood the docs:

> should return true if it was able to update to that node

Since only my children were changing (handled by ProseMirror), and not my own attributes (handled by me), I assumed I shouldn't return true.

I'm still not exactly sure when I should return false, but if possible it would be great to warn me if I do since that seems to be an edge case. If that's not possible (because ProseMirror doesn't know the difference between a legitimate and illegitimate `false`), then I guess this can just be feedback to help any future version of the NodeView API.

### Steps to reproduce

1. With great hubris and bravado, implement a NodeView.
2. Forget to `return true;`
3. Desperately try to fix it because you told everyone ProseMirror was fast and you'll have to eat your hat otherwise.
4. Find out you've been a fool the whole time.
5. Relish in the fact that ProseMirror really is fast, thank god.

**Comment by marijnh** [comment]
Firstly, yes, this is an issue that comes up a lot and I really screwed up the design of this interface. But it usually comes up in the form of people not returning `false` when they should (not checking whether the node passed to the `update` method is of the right type). I'm not sure how warning would help here.

**Comment by hitsthings** [comment]
Ah fair enough. I'm also not validating the node type, so I probably need to fix that too. If there's nothing to do, there's nothing to do. Thanks for listening and thanks for the library!
