### ISSUE TITLE
Bad caret behavior in Edge

### ISSUE THREAD

**Issue by jfiala-cz** [ProseMirror/prosemirror#992]
### Issue details

Caret does not function correctly when navigating via keyboard in Edge browser (EdgeHTML). After typing any first character, the caret stays in front of the character.

There is also some weird behavior when using two letters "f" next to each other. The cursor cannot be positioned between the two letters.

### Steps to reproduce

1/ Go to http://prosemirror.net/ Demo example using the Edge browser
2/ Delete content of the editor
3/ Type any character (for example "a")
4/ The cursor stays in front of the character. If you type "b", the string will be "ba".

(optional)

5/ Type the string "ff"
6/ Try to get the cursor between the two letters. It is possible with neither keyboard or mouse.

### ProseMirror version

Latest (prosemirror-view 1.12.0)

Note: I works correctly with prosemirror-view 1.2.0

### Affected platforms

- [x] MS Edge (EdgeHTML) (Tested with Edge 44.18362.329.0, EdgeHTML 18.18362)

**Comment by petermatik** [comment]
I can confirm that issue with caret not showing at correct position is happing on IE Edge 18.  When I try to move it in the middle of "ff" string using right arrow key it stays at the end. You need hit right arrow twice to show caret at new position (begging). However, when you type something input is placed correctly.

![ie_edge](https://user-images.githubusercontent.com/5718113/67268711-7757a000-f4b5-11e9-8895-877679c3474e.gif)

I noticed also several other issues in IE Edge 15+ that were already discussed (e.g. deleting text at the begging for node...) so I am thinking if patching code for IE specific issues is ever going to solve problems with this browser. Maybe something like "Shadow Event Model" might be the way to go.

**Comment by marijnh** [comment]
Are you including the `font-variant-ligatures: none` style from prosemirror.css?

**Comment by petermatik** [comment]
I see. However, for IE Edge 18 it works only if I add also `font-feature-settings: "liga" 0;`.

![Screen-Shot-2019-10-23-at-13 04 03](https://user-images.githubusercontent.com/5718113/67386806-f2908300-f595-11e9-9909-31a25530423c.gif)

**Comment by marijnh** [comment]
Patches 0fc79814c7f74 and 24dd19a8b76 should help here.
