### ISSUE TITLE
JoinBackward not allowed for gapcursor ?

### ISSUE THREAD

**Issue by zssng** [ProseMirror/prosemirror#993]
### Issue details

Can't delete/backspace  when selection is GapCursor,is that design so?
I found in `prosemirror-commands ` commmands.js

`function joinBackward(state, dispatch, view) {
  var ref = state.selection;
  var $cursor = ref.$cursor;
  if (!$cursor || (view ? !view.endOfTextblock("backward", state)
                        : $cursor.parentOffset > 0))
    { return false }`

$cursor is always undefined when selection is GapCursor.

### ProseMirror version
 `prosemirror-commands` "version": "1.0.8"

### Affected platforms

- [X ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Yes, that's intentional. This command is written with textblocks in mind, you won't ever have a gap cursor in a text block.
