### ISSUE TITLE
[prosemirror-view] posAtCoords can throw 'permission denied' errors when accessing offsetNode in Firefox

### ISSUE THREAD

**Issue by cmanou** [ProseMirror/prosemirror#994]
### Issue details

When calling `posAtCoords` in Firefox `caretPositionFromPoint` can return a `Restricted` result and thus when offsetNode is called you get `Error: Permission denied to access property "offsetNode"`. 

### Steps to reproduce

Call `posAtCoords` with coordinates that correspond to the position of a native widget e.g. a native date picker. This isn't limited to date pickers but was the simplest reproduction for firefox, for example it also occurs in video elements. 

See glitch for reproduction:

https://glitch.com/~halved-backbone

### Workaround

For now, we are currently wrapping all calls to `posAtCoords` with a try-catch but potentially there is a better solution. It seems similar to the firefox error that was occurring in `hasSelection` (https://github.com/ProseMirror/prosemirror-view/blob/06147b49efec62f06738ce593a365f0d1d953858/src/selection.js#L159)

### ProseMirror version

prosemirror-view 1.11.4

### Affected platforms

- [ ] Chrome
- [x] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by marijnh** [comment]
Attached patch adds another `try`/`catch` to the library to work around this.
