### ISSUE TITLE
widget.type.toDOM in undefined

### ISSUE THREAD

**Issue by CarmeloXue** [ProseMirror/prosemirror#995]
### Issue details

I use an inline node to wrap some sensitive word, and add inline decoration for each sensitive word to highlight it. 
When I try to modify the content, I want to remove this deco, but I got error widget.type.toDOM

some of nodes will not trigger this error when i try to modify dom content, but some will trigger this. 

My question is why my inline decoration will run into this widget decoration?

### ProseMirror version

prosemirror-state: 1.2.2

prosemirror-view: 1.8.9

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![image](https://user-images.githubusercontent.com/24514156/68374217-6a0e0700-017f-11ea-86be-440e6cc593ab.png)

**Comment by marijnh** [comment]
> When I try to modify the content, I want to remove this deco, but I got error widget.type.toDOM

It would be useful to know how you are removing the deco. Even more useful would be a minimal script that reproduces the problem.

**Comment by CarmeloXue** [comment]
@marijnh Thanks for your reply. I checked my code, I'm not removing the decos, but re-generate new decorationSet. What i'm  missing is to recalculate my node's position after docChanged.
