### ISSUE TITLE
Error when returning the focus to the editor

### ISSUE THREAD

**Issue by TheRealNic** [ProseMirror/prosemirror#996]
### Issue details

In our setup we are using multiple editor components together on one page with one formatbar. After making a change with the formatbar we usually refocus the current editor by calling `editorView.focus()`. When doing this in chrome, we usually get the error message from the screenshot, while in Internet explorer we don't get any error message but a new selection, which usually spans the entire node.

### Steps to reproduce

Unfortunately I wasn't able ti build a minimal reproduction, maybe the console error will help you to give me a hint, what is going wrong?

### Affected platforms

- [x] Chrome
- [ ] Firefox
- [x] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

![image](https://user-images.githubusercontent.com/8322279/68777041-5821dd80-0631-11ea-8e71-5055f40d70a6.png)

**Comment by marijnh** [comment]
The error looks like the DOM inside the editor isn't what the code expects it to be. Without a way to reproduce this I'm not sure how to debug it.

**Comment by TheRealNic** [comment]
Ok, I'll try to build a reproduction again...

**Comment by TheRealNic** [comment]
Hi Marjin, I found the plugin, that is causing our problem:

`import {Node} from 'prosemirror-model';
import {EditorState, Plugin, PluginKey, Selection, TextSelection} from 'prosemirror-state';
import {Decoration, DecorationSet} from 'prosemirror-view';

export const selectionHighlightPlugin = new Plugin({
  key: new PluginKey('selectionHighlight'),
  props: {
    decorations(this: Plugin, {doc, selection}: EditorState): DecorationSet {
      return createDecos(doc, selection);
    }
  }
});

function createDecos(doc: Node, selection: Selection): DecorationSet {
  if (selection.empty || !(selection instanceof TextSelection)) {
    return DecorationSet.empty;
  }
  return DecorationSet.create(doc, [
    Decoration.inline(selection.from, selection.to, {class: 'selection'})
  ]);
}`

This is a plugin we wrote to have the selection shown, when the editor is not active. Unfortunately this means, that in the inactive state the editor view has 3 components (text before selection, selection, text after selection) and when it tries to refocus the dom element representing the selected text no longer exists. Are we doing this highlighting on an unfocused editor wrong?

**Comment by marijnh** [comment]
Ah, I see, the synchronous focus event gets in the way and changes the DOM _while_ the editor is updating its selection. Does this still happen in prosemirror-view 1.13.2 (which sets focus before changing selection in the `focus` method)?

**Comment by TheRealNic** [comment]
No, the version update fixed the bug, thank you
