### ISSUE TITLE
setBlockType unfocus

### ISSUE THREAD

**Issue by lcswillems** [ProseMirror/prosemirror#998]
### Issue details

If setBlockType(paragraph) is called on a paragraph, it loses the focus. The same behavior might appear for h1, h2, etc...

### Steps to reproduce

https://glitch.com/edit/#!/chill-cairnsmore

**Comment by marijnh** [comment]
`setBlockType` does nothing when all of the selected textblocks already have the given block type. The glitch link seems to basically be the basic demo with no extra info, so it doesn't really help reproduce this.

**Comment by lcswillems** [comment]
The glitch is the basic one. I just remapped `ctrl+shift+number` (because it doesn't work on my computer).

In the demo, if you press "ctrl+shift+a" on a paragraph (the new keyboard shortcut to turn into a paragraph), it unfocus.

**Comment by marijnh** [comment]
Okay, that's not happening for me in Chrome or Firefox Linux. Does the entire editor lose focus or is the selection moved out of the paragraph?

**Comment by marijnh** [comment]
> From a user point of view, I think it would be better that the library always capture the keyboard, but do nothing when it is already a paragraph.

We can't do this generally—often people want to contextually override key bindings but let the browser's default behavior happen when none of their bindings apply. A workaround would be to bind another command that always returns `true` as a fallback.

My Linux system does a select-all on ctrl-shift-a. I'm not sure what's system binding you're hitting there.

**Comment by lcswillems** [comment]
> often people want to contextually override key bindings but let the browser's default behavior happen when none of their bindings apply

You are right and I will want to do it at some point, so my solution is not good.

Thank you for your time and your work. I will had a fallback!
