### ISSUE TITLE
Feature request: rangeFullMarkup

### ISSUE THREAD

**Issue by lcswillems** [ProseMirror/prosemirror#999]
In the current [prosemirror editor](https://prosemirror.net/), a selected text is said bold (the `B` icon is active) if some of the selected text is bold.

For me, this is not the behavior I would expect. For me, a selected text should be said bold if all the text is bold. This is how works Google Docs for example.

I am trying to implement this behavior. But, there is currently no method that will detect if a node range is full of given markup, i.e. there is no `node.rangeFullMarkup`, whereas there is a `node.rangeHasMarkup`.

**Comment by marijnh** [comment]
That should be relatively straightforward to implement with `nodesBetween` (`rangeHasMarkup` is 6 lines), so I don't think it is necessary to add it to the core library.

**Comment by lcswillems** [comment]
It is not because it is straightforward that it should not be implemented. Following your way of thinking, `rangeHasMarkup` should not be implemented because it is straightforward.

A library should expose convenient functions, not "not straightforward" functions.

Moreover, I think it should not be the `rangeHasMarkup` function that should have been implemented, but rather the `rangeFullMarkup` because it leads to unexpected behaviors as explained in the issue.
